### ISSUE TITLE
Repeatable jobs duplication

### ISSUE THREAD

**Issue by cloudever** [OptimalBits/bull#1003]
## Description
The number of repeatable jobs increases with each reboot of the server.  The processor processes also those that were before the restart and so number of processings increases with each restart. 
I understand that on server startup the new jobs created by the server but all names keeps unique.

How to avoid that or it's a bug?

## Minimal, Working Test code to reproduce the issue.
I had a job create so
```js
queue.add(FETCH_QUOTES_QUEUE, data, {
  repeat: {
    every: 2000
  },
})
```

and the corresponding processor
```js
queue.process(FETCH_QUOTES_QUEUE, (job, done) => {
  ....
  done()
})
```

## Bull version
3.4.3

## Additional information
In the beginning I didn't used any contants for job and processor names but issue was.

**Comment by cloudever** [comment]
Setting the jobId does not help

**Comment by cloudever** [comment]
Found that issue is actual usign .every parameter and everything well with .cron

**Comment by chrisabrams** [comment]
I also have the same issue where with each restart of the process, the queue even with the same name, will pile up one more request per restart.

**Comment by manast** [comment]
I have reproduced and identified the reason for the bug, I will fill  PR with a fix ASAP.
