### ISSUE TITLE
error object is not passed to backoff function

### ISSUE THREAD

**Issue by mrfoh** [OptimalBits/bull#1004]
## Description
When implementing a custom backoff strategy, the `error` object is not passed to the backoff function.
The [example](https://github.com/OptimalBits/bull/blob/master/PATTERNS.md#custom-backoff-strategy ) in the docs state that an error object is passed to the custom strategy function.
## Minimal, Working Test code to reproduce the issue.
```
import Bull from 'bull'

const queue = new Bull('myqueue', <Bull.QueueOptions>{
            redis: {
                host: env.redis_host,
                port: env.redis_port,
                ...(env.redis_password && { password: env.redis_password })
            },
            settings: {
                backoffStrategies: {
                    jitter: (attemptsMade, err) => {
                        console.log(err); // this is undefined
                        return Math.round((Math.pow(2, attemptsMade) - 1) * 500);
                    }
                }
            }
})
```
## Bull version
3.4.3
## Additional information
Going through the [backoff.js](https://github.com/OptimalBits/bull/blob/v3.4.3/lib/backoffs.js) in the 3.4.3 tag, i see in this method
```
calculate: function(backoff, attemptsMade, customStrategies) {
    if (backoff) {
      var strategy = lookupStrategy(backoff, customStrategies);

      return strategy(attemptsMade);
    }
  }
```
Only attemptsMade is being passed to the `strategy`

**Comment by manast** [comment]
This feature has not been released yet. I think we should start to make merged in a develop branch and only merge to master when doing releases to avoid this kind of missmatch between documentation and functionality. I will make  new release vey soon though.

**Comment by mrfoh** [comment]
Thank you @manast looking forward to the release.

**Comment by manast** [comment]
3.4.4 has now been relesed.
