### ISSUE TITLE
Are priorities cross-queue?

### ISSUE THREAD

**Issue by RobinJayaswal** [OptimalBits/bull#1009]
I'd like to make sure I have a full grasp on the prioritization system. Say I have two queues, `q1` and `q2`. I define processors for both:

```
  q1.process(function(job, done) {
     setTimeout(done, 1000)
  })

  q2.process(function(job, done) {
     setTimeout(done, 1000)
  })
```
Now, if there were 100 jobs queued up in both queues with priority 2, and then I add a job with priority 1 to q2, does that job get executed before any other jobs in both q1 and q2?

As a side question, if I pull these functions into their own files and run them as separate processes do I no longer have to worry about this question?

```
  q1.process('./handler1')

  q2.process('./handler2')
```

**Comment by manast** [comment]
The priority is per queue, not global. And yes, a job with higher priority will be placed before low priority jobs in the queue.
