### ISSUE TITLE
Issue when using with Meteor methods

### ISSUE THREAD

**Issue by marcoschwartz** [OptimalBits/bull#1010]
Hello,

I am trying to implement a job queue into my Meteor application, and this package is the only one I found with all the functions we need (like rate limiting).

However, I am having an issue when implementing it inside my application. Here is a the code to process a given type of job:

```
mainQueue.process('checkAffProduct', function(job, done) {

    console.log('Executing job ' + job.id);
    console.log('Data: ' + job.data);

    Meteor.call('checkAffProduct', job.data.productId);

    done();

});
```
I can see the jobs being added to the queue, but the Meteor method call (which is synchronous) is never executed. I am sure I am doing something wrong, and I think I have to use Promises, but can't figure it out. Could anyone help? Thanks in advance!

**Comment by manast** [comment]
How does the code that add jobs to the queue looks like?
Are the ```console.log``` in your example executed?
