### ISSUE TITLE
[Question] Being notified after all the jobs have been processed 

### ISSUE THREAD

**Issue by apellizzn** [OptimalBits/bull#1013]
Hi, i' am creating the following queue

```javascript
const q = new Queue('test', redisEndpoint)
q.process(sendEmail)
emails.forEach(queue.add({ email }))
queue.on('drained', async () => { conosle.log(await queue.getJobCounts() })
```
I need to get notified or at least be aware that all the jobs in the queue are have been processed
and have found the `queue.on('drained', () => {})` event which seems to fit my case but printing the jobs count inside `drained`
shows `{ waiting: 0, active: 1, completed: 0, failed: 4, delayed: 0 }` so there still a job in the active state therefore not all of them are completed.

Do you know if there is a way to achieve this using bull api ?
Do I need to implement a custom solution for this? Like using `.on('failed)` and `.on('completed)` to keep track of the queue processing state?

**Comment by manast** [comment]
The ```drained``` event emits when there are no more jobs waiting to be processed, unfortunately there is no built-in event for that you are trying to achieve.

**Comment by apellizzn** [comment]
Thank you for your answer, just posting here my workaround in case someone have the same goal
```
const q = new Queue('test', redisEndpoint)
q.on('drained', async () => { 
   console.log(await queue.getJobCounts()) // { waiting: 0, active: 1, completed: 3, failed: 4, delayed: 0 }
   // second param is used to wait for the current active job to finish before pausing the queue   
   await queue.pause(true, false) 
   await sendSmsQueue.getJobCounts() // { waiting: 0, active: 0, completed: 4, failed: 4, delayed: 0 }
   // all your jobs have been processed
})
```
