### ISSUE TITLE
Counting jobs by type

### ISSUE THREAD

**Issue by artem-a** [OptimalBits/bull#1014]
Hi, how can I count jobs by task type?

For example: I have a queue and two types of tasks. 
```javascript
'use strict'

const Queue = require('bull')

const queue = new Queue('global-queue', 'redis://127.0.0.1:6379')

queue.process('task0', 5, './task-processor0.js')
queue.process('task1', 5, './task-processor1.js')
```
How can I count jobs (active, waiting etc...) for specific task (task1 or task0)?

**Comment by manast** [comment]
You need to use different queues in that case, since the ```getCount``` functions are per queue and not per named job.
