### ISSUE TITLE
get and  cancel active queue

### ISSUE THREAD

**Issue by ghazanfar1395** [OptimalBits/bull#1015]
I am trying to hit event to get active job processed and wanted to kill that queue. but that event is not being called and no result is showing, is there any version issue ? well i am using node 6.13.1

```js
queue.on('active', function(job, jobPromise){
 
 console.log("job active: id: "+job.jobId);

obPromise.cancel()

});
```

**Comment by manast** [comment]
please provide a complete example reproducing the issue.
