### ISSUE TITLE
Executes old code

### ISSUE THREAD

**Issue by cesarvarela** [OptimalBits/bull#1016]
## Description
Hi, I'm using bull + arena, and after some jobs failed, I've updated the `queue.process()`code to fix the reason for them to fail, but when I click the `retry job` from arena the job fails again with the same stacktrace as the previous fail, which shouldn't be possible because the process code has changed.

Does bull have some js cache or something?

thanks

## Bull version
3.4.2

**Comment by cesarvarela** [comment]
NVM I had both staging and production pointing to the same queue 🤦‍♂️

**Comment by manast** [comment]
Thats a common pitfall actually. In Taskforce you can also see the workers and that helps to find this kind of issues.
