### ISSUE TITLE
How to retry a job until it's done?

### ISSUE THREAD

**Issue by tonywei92** [OptimalBits/bull#1018]
## Description
How to retry until its done?

## Minimal, Working Test code to reproduce the issue.
```
>> Jobs.js
const Sync = require('./Sync');
const Queue = require('bull');
const job = new Queue('data sync');

job.process(function(job, done){
    console.log('job start');
    Sync.dataSync(job.payload, function(response){
        if(response.status === 200){
            done(response.data);
        }
        else{
            console.log('error');
            throw new Error('some unexpected error');
        }
    })
});

module.exports = {
    job
};


----------------------------------
>> Sync.js
const axios =require('axios');

async function dataSync(payload, callback){
    return await axios.post('https://www.google.com/queue',payload).then(response=>{
        if(callback){
            callback(response);
        }
        return response;
    }).catch(error =>{
       if(callback){
           callback(error.response);
       }
       return error.response;
    });
}

module.exports = {
    dataSync
};

---------------------------------------
>> index.js

const Jobs = require('./Jobs');

Jobs.job.add({
   payload: 'test'
});


```
## Bull version
"bull": "^3.4.4"

## Additional information
run with "node index.js"
The result:
```
error
(node:23105) UnhandledPromiseRejectionWarning: Error: some unexpected error
    at /home/vagrant/sites/queueTest/Jobs.js:13:19
    at axios.post.then.catch.error (/home/vagrant/sites/queueTest/Sync.js:11:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:23105) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23105) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
of course it's error, but it's never retry.
please help!

**Comment by manast** [comment]
if you do not use "done" and instead use promises all the way it will work.

**Comment by manast** [comment]
You need to return a promise from dataSync as well:

```
const Sync = require('./Sync');
const Queue = require('bull');
const job = new Queue('data sync');

job.process(function(job){
    console.log('job start');
    return Sync.dataSync(job.payload);
});

module.exports = {
    job
};
```

```
>> Sync.js
const axios =require('axios');

async function dataSync(payload){
    return await axios.post('https://www.google.com/queue', payload);
}

module.exports = {
    dataSync
};
```

**Comment by KonstantinKudelko** [comment]
@manast thx for your help.
But I'm my job invoke only one time if the request fails.

Request:

`
fetch(`${url}`)
      .then((result: any) => {
        if (!result.ok) {
          throw new Error(`Request ${url} was failed with status - ${result.status}`);
        }

        return result.json();
      })
      .then((res: any) => {
        if (res && res.result === 'success') {
          return res.data;
        }

        throw new Error(`Empty response [${url} - ${res}`);
      })
      .catch((error) => {
        throw new Error(error);
      });
`

`
const testQueue = new Queue('test', 'redis://127.0.0.1:6379');

testQueue.process(async (job) => {
      console.log('job start');
      return request(job.data.payload);
});

await testQueue.add({payload: 'request'});
`

**Comment by KonstantinKudelko** [comment]
@manast If I right understand, I don't need to handle errors of the Promise to retry job?

**Comment by manast** [comment]
The second example is wrong because you are defining a "done" function, however it is never called, so the job will never complete (or fail).

**Comment by KonstantinKudelko** [comment]
> The second example is wrong because you are defining a "done" function, however it is never called, so the job will never complete (or fail).

Yep, but first one, I see like my job invokes only one time

**Comment by bentesha** [comment]
You will have to specify number of attempts and backoff strategy when adding a job for bull to retry a failed job.

Below job will be attempted 5 times in 5secs intervals before failing completely

`testQueue.add({ payload: 'request' }, { attempts: 5, backoff: 5000 });`

Check docs for other options to meet your specific needs

**Comment by tranphuoctien** [comment]
> You will have to specify number of attempts and backoff strategy when adding a job for bull to retry a failed job.
> 
> Below job will be attempted 5 times in 5secs intervals before failing completely
> 
> `testQueue.add({ payload: 'request' }, { attempts: 5, backoff: 5000 });`
> 
> Check docs for other options to meet your specific needs

You must retry each job after get all jobs failed.
I'm using Nestjs this is example:  
```js
import { Logger,  } from '@nestjs/common';
import { Injectable } from '@nestjs/common';
import { Queue } from 'bull';
import { Processor, Process, InjectQueue } from '@nestjs/bull';
import { Job } from 'bull';
import { JOB_QUEUE, JOB_NAME } from '../common/constants/queue.contants';
const logger = new Logger(`QUEUE NAME ${JOB_QUEUE.GHN}`);

@Injectable()
@Processor(JOB_QUEUE.GHN)
export class GhnOrderConsumer {
    constructor(@InjectQueue(JOB_QUEUE.GHN) private queue: Queue){
        logger.log(`JOB RUN ON ${JOB_QUEUE.GHN}`);
        this.queue.getFailed().then((jobs: Job<unknown>[]) => {
            jobs.forEach((job:Job<unknown>) => {
                job.retry();
            })
        });
    }

    @Process(JOB_NAME.ORDER_STATUS)
    orderStatus(job: Job<unknown>) {
        console.log('job >>> ', job.data);
        return {};
    }
}
```
