### ISSUE TITLE
Master process doesn't get killed after queue is done

### ISSUE THREAD

**Issue by LazyFatArrow** [OptimalBits/bull#1019]
## Description
I have a bull queue that runs puppeteer headless browser to scrape some pages, the job scrapes pages with concurrency of one at a time, and then exists and ends the job, My question is that I am using separate processes for each job and I am noticing that even after the jobs are done there is this master process that doesn't get killed for some reason. I don't know if this is intended or not. This is the image:
https://ibb.co/iorrLe

**Comment by manast** [comment]
gonna find some time to investigate this issue.

**Comment by LazyFatArrow** [comment]
I ended up forking a new process inside the job handler and wrapping the process exit event in a promise. 

```
const process = async job => {
  try {
    await addNext(job.data.websiteId, job.data.processingDelay);
    const forked = fork(path.resolve(__dirname, './processor.js'), [], {execArgv:['--max_old_space_size=1000']});

    forked.send({
      message: 'process',
      data: job.data
    });

    await new Promise((resolve) => {
      forked.on('exit', () => {
        logger.info(`Processed job ${job.id} with url ${job.data.url} with delay ${job.data.processingDelay}`);
        resolve();
      });
    });

  } catch(e) {
    logger.error(e.message);
  }

  return;
}

**Comment by manast** [comment]
I have spent some time trying to reproduce this issue without success, the code I used was the following:
```js
var Queue = require('../lib/queue.js');

const queue = new Queue('video transcoding');

queue.process(__dirname + '/thread-test-processor');

queue.on('error', err => console.log(err));

for (var i = 0; i < 100; i++) {
  queue.add({});
}

setTimeout(() => queue.close(), 10000);

const queue2 = new Queue('audio transcoding');

queue2.process(() => console.log('audio job'));

queue2.add({});
```

There is one master process all the time and as soon as the first queue is close the process is terminated.

**Comment by LazyFatArrow** [comment]
maybe it's a problem from my code then, I am going to close this.

**Comment by vdkkia** [comment]
I have the same problem when I use recurrent jobs using Cron:

```
const mainQueue = new Queue("mainQ", { redis: redisOptions });
mainQueuecron.process("main", 1, path.join(__dirname, "mainProcessor.js"));
await mainQueue.obliterate({ force: true });
mainQueue.add("main",{},{ repeat: { cron: "0 4 * * *", tz }, removeOnComplete: true, removeOnFail: false });
```
![image](https://user-images.githubusercontent.com/4618481/118973447-f8b53400-b971-11eb-8325-9da24b10c435.png)

**Comment by manast** [comment]
@vdkkia  the process is kept alive in case you add more jobs to the queue...

**Comment by vdkkia** [comment]
@manast Is there a way to force it to create the process at schedule time and terminate it when job is finished?

**Comment by manast** [comment]
No. why would you like to do that?

**Comment by haipengz** [comment]
> No. why would you like to do that?

Same issue here.
![Snipaste_2021-07-20_10-50-53](https://user-images.githubusercontent.com/11665321/126254542-ac8e15c5-4a2f-4745-a554-ecc608ee0382.jpg)
Because the processes use a lot of memory.
If there is a way to terminate the processes when the jobs are done, it could save us a lot of memory.
Well, it's not a big issue when we are running the application on a server that has a large amount of memory, but when it comes to running on vm at my dev laptop, the issue crashes my vm and I have to restart my vm.
I think the point is that the zombie processes eat up too much memory.

**Comment by manast** [comment]
@haipengz there should not be any zombie processes, processes are reused by the workers so there should not be more processes than your concurrency factor. So there will be no memory gains in killing the processes only a slower performance since creating a new process for every job is a time consuming task.

**Comment by haipengz** [comment]
@manast 

> So there will be no memory gains in killing the processes...

That's true only if the processes release memory when jobs are done. But after 2 months of usage in production environment, I notice that the memory just keeps going up and never get released. 
![Snipaste_2021-09-30_14-39-25](https://user-images.githubusercontent.com/11665321/135400482-d72928f6-4cdb-4249-82fd-9ba29680adad.jpg)
![Snipaste_2021-09-30_14-52-38](https://user-images.githubusercontent.com/11665321/135402116-012d9087-aa73-40d5-b1fa-488cd4ead7d2.jpg)


In my use case, I don't have many jobs added or running in a period of time(no more than 100) but each of them will run several minutes processing large amount of data. My point is, the memory usage issue is a problem for my use case, but the consumption of time when creating a new process for every job does not matter. 

As you can see above, just several master bull processes have eaten up most of the machine memory. What's worse, they are all idle, no jobs are being processed.

**Comment by manast** [comment]
@haipengz ok, but it could also be your processor code that is leaking memory, it is actually quite difficult to write non-leaking memory code in nodejs unfortunatelly. However I see that having an option that kills the process for every time a job is processed would solve your issue, although not practical if you need maximum performance.
