### ISSUE TITLE
Closing queues with shared Redis clients triggers write EPIPE

### ISSUE THREAD

**Issue by Unibozu** [OptimalBits/bull#1020]
Hi,

We're using a queue per type of job, with a unique shared ioredis connection per node. When the worker is shut down, I issue a `queue.close()` command to all of the queue and wait for completion before calling `process.exit()`. In some situation, the error reporting catch several dozen errors `write EPIPE` that are imputed to Bull.

I believe this is happening because `Queue.close()` close the redis client, irrespective of its shared status with other queues, which blocks any running jobs to have their status settled on Redis.

Does calling `Queue.pause()` works as a graceful shutdown (across 20 queues sharing 1 ioredis client) instead?

Might want to update the documentation regarding graceful shutdown and shared redis clients. Both are great features, yet these errors took me a while to investigate due to being unable to replicate. I've found https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueclose and https://github.com/OptimalBits/bull/blob/master/PATTERNS.md#reusing-redis-connections can use a warning.

Bull version: 3.3.1

**Comment by manast** [comment]
```Queue.pause()``` will pause the queues globally, but the jobs that are being processed will continue until they finish, so you would need to account for that.
Regarding the shared connection issue, in newer vesions of bull, the shared connection is not closed by bull, instead you need to close it manually, which you can do after all the queues have gracefully been closed.

**Comment by Unibozu** [comment]
I was using `.pause(true)` to keep it local - after a few failed attempts that paused the queues globally :-) the code I was using was taken from the `Queue.close()` implementation.

I'm glad this was sorted in a new version then, we'll look at upgrading to avoid this issue.
