### ISSUE TITLE
Unhandled rejection ReplyError: ERR unknown command 'eval'

### ISSUE THREAD

**Issue by ProfutW** [OptimalBits/bull#1026]
I use redis sentinels with createClient api but cause an error just like the issue's title.
```
const Redis = require('ioredis');
const Queue = require('bull');
const redisOpts = {
    name,
    password,
    sentinels
};

const queue = new Queue('test', {
    createClient: () => {
        return new Redis(redisOpts);
    },
});
//this can work
queue.count();

//but these cannot
queue.process((job, done) => {
    ...
});
queue.add({msg: 'test'});
```
I have already tested redis sentinels, they can work well without bull.

**Comment by manast** [comment]
seems like your redis server does not support the EVAL command. Can you just use redis-cli to connect to the server and test if it is available?

**Comment by ProfutW** [comment]
@manast  Thanks, you are right. I directly connect to my redis master and try to use eval command but fails.I check the config file and find that the 'eval' command had been renamed to ''(for security?). Anyway,it works now~~Thanks again.
