### ISSUE TITLE
limiter dose not work!!!

### ISSUE THREAD

**Issue by bymaxchen** [OptimalBits/bull#1028]
const opts = {
          redis: app.config.redis,
          limiter: {
            max: 1,
            duration: 1000,
          },
          settings: {
            lockDuration: 3600000,
          },
        };

this is my queue opts

but if i add N jobs Continuously，I get all the jobs done at the same time。

every job is very time consuming

**Comment by manast** [comment]
Please provide a simple test that reproduces the issue. If we cannot reproduce it we have no chance to fix it.
