### ISSUE TITLE
When a queue start it do not process delayed job

### ISSUE THREAD

**Issue by lchenay** [OptimalBits/bull#103]

**Comment by lchenay** [comment]
I can't find a solution to fix it.
CF test unit : https://github.com/lchenay/bull/compare/fix/restartAndDelay?expand=1

It still doesn't works in the case when a worker restart, queue have delayed job but not yet ready to be processed.

The LUA script in updateDelaySet never end ; and "client list" report a blocking function "set".

**Comment by manast** [comment]
I think I know why this happens. Its that the delayTimer needs to be setup with old delayed jobs when starting a worker, but right now it is just setting it to null. I will write a test for this and try to fix it ASAP.
