### ISSUE TITLE
Job was processed only after the application was restarted

### ISSUE THREAD

**Issue by andrucz** [OptimalBits/bull#1030]
## Description
A few months ago I implemented an application that sends SMS to customers using a third-party service. To prevent carrier filtering, I had to split the process into smaller steps and add a delay between them. The customer has successfully sent hundreds of thousands of messages to his customers over the last months, but one of the jobs got stuck two weeks ago and was executed only after the application was restarted.

Unfortunately, I can't reproduce the error, but I created a working test very similar to the real application. I'd like to know what might have caused the problem (considering Bull's implementation details), how could I prevent this from happening again and if I should update Bull's version (I'm using 3.4.2).

The processor functions are async and there are some try/catch blocks surrounding all the logic that catch the errors, log and throw them again. There were no error messages on CloudWatch when the problem happened.

Both processors have concurrency set to 1 to avoid sending campaigns concurrently and reaching the third-party service limits.

When the problem happened, the last message logged by the application was "Scheduling a new step...". The new job should have been processed seconds after that message, but it happened only when the server was restarted. It seems like the processor instance that scheduled a new step was not marked as "available" and when a new instance was started by PM2, it became available to execute the pending job. Does that make any sense?

It happened only once, a few weeks ago, and I'm afraid I can't see the job status on Redis anymore.

## Minimal, Working Test code to reproduce the issue.

`
    
    import Queue from 'bull';

    const stepQueue = new Queue('campaigns.step');

    stepQueue.process(1, async job => {
      try {
        const { number, parentId } = job.data;
        console.log('Processing step', number, 'from campaign', parentId, '...');

        if (number < 100) { // in the real application it checks if there are more customers to send the message
          const jobOptions = {
            delay: 5 // it's around 6 seconds in the real application
          };

          console.log('Scheduling a new step...');
          await stepQueue.add({
            number: number + 1,
            parentId
          }, jobOptions);
        } else {
          console.log('Campaign', parentId, 'is finished.');
        }
      } catch (err) {
        console.log(err);
        throw err;
      }
    });

    const campaignsQueue = new Queue('campaigns');
    const stepQueue2 = new Queue('campaigns.step');

    campaignsQueue.process(1, async job => {
      try {
        console.log('Processing campaign', job.id, '...');
        await stepQueue2.add({
          number: 0,
          parentId: job.id
        });
      } catch (err) {
        console.log(err);
        throw err;
      }
    });

    const sendQueue2 = new Queue('campaigns');

    for (let i = 0; i < 100; i++) {
      sendQueue2.add({});
    }
`

## Bull version
3.4.2

## Additional information
- The application runs on AWS
- Job processors are managed by PM2

**Comment by manast** [comment]
a job can get stuck if you processor function gets stuck. For example, you could set a timer that fires after an infinite amount of time, then the job will never end. I don't know what happened in your specific case, but I see a mistake in the code, for instance you are not awaiting the call ```stepQueue.add```, which I think will among other things not catch any error thrown by it.

**Comment by andrucz** [comment]
Sorry, I forgot to add the `await` in that test, but it exists in the real application. I updated the description.

The code that adds a new message into the queue is the last statement of the processor function and I can say that it didn't throw any error because the new message was processed when the application was restarted.

**Comment by manast** [comment]
If a processor function gets dangling for some reason, bull has no way to know it, but after restart the job will be marked as stalled and picked up after a few seconds, thats why restart helped. The question is if there is a bug in the process code or in bull just after the process was completed.

**Comment by andrucz** [comment]
Yes, I couldn't identify any errors in the processor code so far. I opened this issue to get some help from someone who knows how Bull works internally and could think of any corner cases that might have caused that problem.

**Comment by manast** [comment]
There are not known issues that could produce the problem you are describing.

**Comment by ponomarenkotema** [comment]
I got the same problem. And can reproduce it by stop/start redis service.  
After reconnection redis clients on my queue got status ready but added jobs only performed after app is restarted.

**Comment by manast** [comment]
Ok, I will try to find some time to revisit #890

**Comment by andrucz** [comment]
The mentioned problem has happened again. Now I have more details about the job that scheduled the other and the one that got stuck.

The job that got stuck has been scheduled by:

`
{
            "id": "ad6173fe-ebdd-48f9-ac7c-43f0237280ef_step_0",
            "name": "__default__",
            "data": {
                "campaign_id": "ad6173fe-ebdd-48f9-ac7c-43f0237280ef",
                "offset": 0,
                "limit": 350,
                "interval": 6000,
                "step": 0
            },
            "opts": {
                "jobId": "ad6173fe-ebdd-48f9-ac7c-43f0237280ef_step_0",
                "attempts": 1,
                "delay": 0,
                "timestamp": 1538502922927
            },
            "progress": 0,
            "delay": 0,
            "timestamp": 1538502922927,
            "attemptsMade": 0,
            "stacktrace": [],
            "returnvalue": null,
            "finishedOn": 1538502924609,
            "processedOn": 1538502922928
        }
`

The job that got stuck:

`{
            "id": "ad6173fe-ebdd-48f9-ac7c-43f0237280ef_step_1",
            "name": "__default__",
            "data": {
                "campaign_id": "ad6173fe-ebdd-48f9-ac7c-43f0237280ef",
                "offset": 350,
                "limit": 350,
                "interval": 6000,
                "step": 1
            },
            "opts": {
                "delay": 4322,
                "jobId": "ad6173fe-ebdd-48f9-ac7c-43f0237280ef_step_1",
                "attempts": 1,
                "timestamp": 1538502924607
            },
            "progress": 0,
            "delay": 4322,
            "timestamp": 1538502924607,
            "attemptsMade": 0,
            "stacktrace": [],
            "returnvalue": null,
            "finishedOn": null,
            "processedOn": null
        }
`

After restarting the server, the job was executed:

`{
            "id": "ad6173fe-ebdd-48f9-ac7c-43f0237280ef_step_1",
            "name": "__default__",
            "data": {
                "campaign_id": "ad6173fe-ebdd-48f9-ac7c-43f0237280ef",
                "offset": 350,
                "limit": 350,
                "interval": 6000,
                "step": 1
            },
            "opts": {
                "delay": 4322,
                "jobId": "ad6173fe-ebdd-48f9-ac7c-43f0237280ef_step_1",
                "attempts": 1,
                "timestamp": 1538502924607
            },
            "progress": 0,
            "delay": 0,
            "timestamp": 1538502924607,
            "attemptsMade": 1,
            "stacktrace": [],
            "returnvalue": null,
            "finishedOn": 1538506838915,
            "processedOn": 1538506838840
        }
`
