### ISSUE TITLE
Required freelance developer to develop some Bull PRs 

### ISSUE THREAD

**Issue by nitzanav** [OptimalBits/bull#1032]
if anyone has recomendation please contact, nitzan.aviram@ongage.com

**Comment by manast** [comment]
Is this PRs for Bull or PRs for a private project codebase?

**Comment by nitzanav** [comment]
The concept is to *offer* PR for the maintaners to any feature that will be generic enough (e.g. delayed LIFO) I have two other ideas which need to be discussed: batches and workflow but tge requirements might be too specific.

The specific one will be outside bull project.

**Comment by manast** [comment]
I am going to close this since communication is performed via email.

**Comment by nitzanav** [comment]
sure it needs to be closed. I hoped to get someone from inside this community. but no one approached.

thank you anyway

**Comment by manast** [comment]
hmm, you got mail from me but maybe it ended in the spam folder or something?
