### ISSUE TITLE
Concurrency and order across queues

### ISSUE THREAD

**Issue by Vortec4800** [OptimalBits/bull#1036]
I have a bunch of different job types and each job is scheduled in a particular order. For example, there are a bunch of jobs that run that calculate points for users, then once those jobs complete I've got another job scheduled that sends out score notifications.

Can I do this using Bull? It seems like if I create 1000 calculation jobs and 1 notification job across 2 separate queues, my notification job would likely run before the calculation jobs are all complete.

I can use named jobs to do everything on a single serial queue, but I also have the requirement that I need to be able to lookup and remove all jobs with a specific name, but it seems like there is currently no way to get all jobs from a queue that match a specific name.

**Comment by manast** [comment]
can't you add he notification job in the last of the calculation jobs?
