### ISSUE TITLE
Repeatable Jobs questions

### ISSUE THREAD

**Issue by thelinuxlich** [OptimalBits/bull#1037]
1 - How can I ensure I'm adding a repeatable job only once?
2 - What happens if the repeatable job doesn't find a available worker when it is triggered? Does it retry again after some time or only on the next interval?
3 - How can I remove repeatable jobs?

**Comment by manast** [comment]
> 1 - How can I ensure I'm adding a repeatable job only once?
Bull will only allow one repeatable job with a given set of repeat options.

> 2 - What happens if the repeatable job doesn't find a available worker when it is triggered? Does it retry again after some time or only on the next interval?
Jobs will not be accumulated so you will loose repetitions.

> 3 - How can I remove repeatable jobs?
https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueremoverepeatable

**Comment by thelinuxlich** [comment]
Thanks, was very enlightening

**Comment by manast** [comment]
In fact I am writing a new guide where I also clarify this question: https://optimalbits.github.io/bull/

**Comment by btd** [comment]
@manast why add with repeat is not considering data? For example i have that selects initial data for other jobs, and i am passing in data selector. So if i need to shedule several such jobs with the same repeat it is just adding one
