### ISSUE TITLE
Supporting other stores

### ISSUE THREAD

**Issue by tracend** [OptimalBits/bull#104]
I like the module and I'm using it in a project but I'd like to support other stores apart from Redis. 

Is it in your plans to extend the support to other stores or will Bull always run with Redis exclusively? 

Cheers

**Comment by manast** [comment]
I do not have plans to use other backends. I guess it is possible, the backend needs to support transactions and pubsub (maybe foundationDB would work). The thing is that redis has very good properties that makes it specially well suitable for a design like the one we are using for Bull...

**Comment by tracend** [comment]
Thanks for the response. 

Development on this will continue at Bodacious: https://github.com/makesites/bodacious

**Comment by albertjan** [comment]
@tracend If you do a PR for bull making it support another backend. I bet @manast would consider it.
