### ISSUE TITLE
Add Job Externally

### ISSUE THREAD

**Issue by bobdercole** [OptimalBits/bull#1040]
Hello,

I am trying to add jobs to a queue from an external source (PHP app) by calling [addJob-6.lua](https://github.com/OptimalBits/bull/blob/c52c5e50c6325d9c6ef72129be1ae9bc6d0272b7/lib/commands/addJob-6.lua) (as mentioned in #323 and #573). This is pretty straightforward, except for argument <span>#</span>11 (token). I found that this is a UUID generated in [queue.js](https://github.com/OptimalBits/bull/blob/c52c5e50c6325d9c6ef72129be1ae9bc6d0272b7/lib/queue.js#L120). Since this is generated at Bull runtime, how do I know what to pass to addJob-6.lua in my PHP app?

It's a little unclear whether #969 is directly related, but the token seems to be the issue there too.

Thank you!

**Comment by manast** [comment]
The token is issued so that events are propagated corrected without duplicates. Since I assume you re not listening to events from the PHP code it will not have any impact for you.

**Comment by bobdercole** [comment]
Oh, I see. Thank you for the clarification!
