### ISSUE TITLE
Defining each queue on a separate file and using separate processes

### ISSUE THREAD

**Issue by ronenteva** [OptimalBits/bull#1045]
For convenience, I would like to configure each queue on a separate file.
`Queue.process` requires a string input in order to use separate processes, so I can only export the processor function from each file (and not the concurrency value, for example).

Therefore I created the following setup:

### init.js
```
const glob = require('glob');
const path = require('path');
const Queue = require('bull');

const queues = glob.sync(path.normalize(__dirname + '/jobs/*.js'));

queues.forEach(function (queue) {
  require(queue);
});
```

### jobs/doSomething.js
```
const Queue = require('bull');

const doSomething = new Queue('do something');
doSomething.process(4, __filename);
doSomething.add({}, {repeat: {every: 1000}});

module.exports = (job) => {
  //  do something
};
```

Does my setup make sense? Is there any better way to do it?

**Comment by ronenteva** [comment]
### Update: 
I realized I also need the job name for Arena, so I ended up using this:

### init.js
```
const glob = require('glob');
const path = require('path');
const Queue = require('bull');

const queueFiles = glob.sync(path.normalize(__dirname + '/jobs/*.js'));

queueFiles.forEach(queueFile => {
  const queue = require(queueFile);
  const newQueue = new Queue(queue.name);
  newQueue.process(queue.process);
  newQueue.add({}, {repeat: {every: queue.every}});
});
```

### jobs/doSomething.js
```
module.exports = {
  name: 'do something',
  every: 1000,
  process: (job) => {
    //  do something
  }
};
```

Which means I lost the ability of using separate processes.

**Comment by e-nitram** [comment]
Hello
I have a question

const express = require('express');
const router = express.Router();
const imageGenerationQueue = require('../../queqe');
const QueueModel = require('../../models/Queue');



router.post('/generate-image', async (req, res) => {
    const { prompt, image } = req.body;

    // Assuming user is authenticated and you have the user's ID
    // const userId = req.user._id;

    const queueEntry = new QueueModel({
        // userId,
        prompt,
        originalImageLink: image
    });

    console.log('queueEntry', queueEntry)

    await queueEntry.save();

    try {
        const job = async () => await imageGenerationQueue.add({
            image,
            queueEntryId: queueEntry._id
        });
        console.log("Job added:", job);
    } catch (error) {
        console.error("Failed to add job:", error);
        return res.status(500).json({ error: "Failed to add job to the queue." });
    }
    console.log('123123123')

    imageGenerationQueue.process(async (job) => {
        const { prompt, image, queueEntryId } = job.data;
        console.log('123123123')

        // Update status to processing
        await QueueModel.findByIdAndUpdate(queueEntryId, { status: 'processing' });

        // Logic to generate the image...
        // Let's say `generatedImageLink` is the result

        await QueueModel.findByIdAndUpdate(queueEntryId, {
            status: 'completed',
            generatedImageLink,
            completedAt: Date.now()
        });
    });



    res.json({ queueEntryId: queueEntry._id });
});


module.exports = router;

this is my code using nodejs
Here process part is not run.
can you help me?
