### ISSUE TITLE
Feature Request: How to get if queue is paused?

### ISSUE THREAD

**Issue by btd** [OptimalBits/bull#1046]
Currently it is possible to pause/resume job, but it is not possible to know if queue is paused (locally or globally) after restart. Only way is to get redis key state by hands.

It would be nice to have something like `Queue.prototype.isPaused(isLocal?: boolean): Promise<boolean>` method

**Comment by bogini** [comment]
There is no API method as far as I'm aware but you can check if the key `bull:${queueName}:meta-paused` is `1` directly on Redis.

**Comment by btd** [comment]
@bogini yes i know, i just think it should exposed as Queue method.

**Comment by genuinefafa** [comment]
@bogini can you provide an example code to achieve that? it might be useful for newbies like the one writing here ;)

**Comment by antongorodezkiy** [comment]
@genuinefafa It should be pretty simple with:

```
import Redis from 'ioredis';
import Queue from 'bull';

const redis = new Redis({
  port: process.env.REDIS_PORT,
  host: process.env.REDIS_HOST,
  family: 4, // 4 (IPv4) or 6 (IPv6)
  password: process.env.REDIS_PASSWORD
  //db: 0
});

const queue = new Queue('NAME_QUEUE', {
  redis: {
    port: process.env.REDIS_PORT,
    host: process.env.REDIS_HOST,
    password: process.env.REDIS_PASSWORD
  }
});

console.log('queue is paused -> ', await redis.exists(queue.keys['meta-paused']))
```

**Comment by manast** [comment]
You can use the ```Queue##isPaused``` method: https://github.com/OptimalBits/bull/blob/develop/lib/queue.js#L853
