### ISSUE TITLE
Suggestions for per user jobs within the same bull installation

### ISSUE THREAD

**Issue by alolis** [OptimalBits/bull#1057]
Hello all,

I am looking for suggestions/ideas regarding the following scenario.

We are running a multi-user web application in which each user can perform some actions. Each of these actions create a job in the backend. Each user can view the jobs which currently run on his behalf on a web page within his account (the web app makes a REST API call and fetches a list of those jobs). For each job type, we are using a different queue but the same queues are being used for all users.

So, my question is is since I just started to look into `bull`; Is it possible to fetch the jobs that belong to a curtain user with `bull` by attaching a custom field to the job data?

A few thoughts I had so far were:

1. Attach a `userId` to the job data and directly query `redis` in order to perform a scan and fetch the desired data for all job types or filtered job types (unless there is an API method I missed that can query the job data??).

2. Build on top of `bull` a small model class and use a `user_jobs` mapping within `redis` (or do the same within MongoDB which we are currently using within our system) to keep track of the jobs each user currently runs, and then fetch those jobs with [Queue#getJob](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queuegetjob) (although i would prefer to use [redis mget](https://redis.io/commands/mget) for fetching multiple keys and not looping all ids.

3. Use one queue per user, although I do not really like this idea a lot, i think it will be maintenance nightmare in terms of resources, plus there is no `Queues#list` implemented at the moment so tracking must be implemented as well.

Has anyone tried this scenario with `bull`? If yes, what is your current implementation? or is there a way to do this with `bull` that it's currently not documented?

Thank you for your time and I would happily answer any questions to make things more clear.

**Comment by alolis** [comment]
@manast , thanks for getting back to me. Your answer generated a couple more questions which  I would like your opinion.

1. If I implement (2) then that means that I would still need to load from redis some of the original job data (in order to avoid data duplication) via `bull` and `getJob(id)`. What if a user has 1000 jobs and you need to call `getJob` 1000 times to fetch everything? Wouldn't that impact redis performance? Is it worst/better than implementing a `getJobs([array of ids])` and use `MGET` internally?

2. Is a job id unique among all queues or only within the queue it belongs to? (my apologies if this is somewhere in the docs, I didn't locate it)

3. Do you find the one queue per user a terrible idea, specially from a performance perspective? Some of the actions the users can do e.g. copy a large folder to a remote location that might be slow, might affect the other users waiting for their turn. Even with a high concurrency, this might be a problem. One queue per user can help avoid such a problem.

**Comment by manast** [comment]
[getJobs](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queuegetjobs) is the fastest we can currently get a range of jobs. There is no other way to do it faster, since as I mentioned, the jobs are stored as HSETS, whereas we move just the jobIds around to the different queue states. The above mentioned api also allows you to do pagination, which may be useful in your case to avoid fetching too many jobs at once. Job ids in bull are a counter, although you can specify your own uuid if you wish. All data stored in redis is prefixed so even if the job id is the same it will not conflict with other job ids in other queues. 

Regarding your question 3). I recommend you that you make benchmarks and get some empirical data on what would work best for your use case.

**Comment by alolis** [comment]
@manast , thank you for your answers.
