### ISSUE TITLE
Compatability for Redis Sentinel

### ISSUE THREAD

**Issue by haggy** [OptimalBits/bull#106]
Is this in the roadmap? It would be very easy to do so I might just fork the repo and replace the redis npm module with redis-sentinel :)

**Comment by manast** [comment]
the main risk here is that sentinel is not partition tolerant so I am not sure if it is a good idea to add this capability if it means queues could exhibit weird unpredictable behaviour in some situations :/
https://aphyr.com/posts/307-call-me-maybe-redis-redux

**Comment by manast** [comment]
I am open for discussion about this feature....
