### ISSUE TITLE
Asynchronous task in worker not running

### ISSUE THREAD

**Issue by Robinhoodbharadwaj** [OptimalBits/bull#1060]
Hi,

I have started using bull for queuing jobs.
One thing i found is that one of my queue has not been able to run a worker which handles asynchronous task.
There are mongoose queries in that worker and i am running worker as a separate process as mentioned in the docs.
Can anyone help me with this ??

**Comment by Robinhoodbharadwaj** [comment]
I am using done callback to successfully end the job and also in case of failing.

**Comment by alolis** [comment]
@Robinhoodbharadwaj, did you re-initialize your mongo connection inside the worker before trying to use mongoose models?

**Comment by OkuraSt** [comment]
@alolis 

> @Robinhoodbharadwaj, did you re-initialize your mongo connection inside the worker before trying to use mongoose models?

This worked for me, do you know about other type of resources that should be re-initialized?

**Comment by alolis** [comment]
> @alolis
> 
> > @Robinhoodbharadwaj, did you re-initialize your mongo connection inside the worker before trying to use mongoose models?
> 
> This worked for me, do you know about other type of resources that should be re-initialized?

Since your processor executes in a child process you need to re-initialize everything that your processor requires to use.

**Comment by thangtv611** [comment]
> > @alolis
> > > @Robinhoodbharadwaj, did you re-initialize your mongo connection inside the worker before trying to use mongoose models?
> > 
> > 
> > This worked for me, do you know about other type of resources that should be re-initialized?
> 
> Since your processor executes in a child process you need to re-initialize everything that your processor requires to use.

Sorry, do you mean starting bull will create a new process for Bull queue sir?
