### ISSUE TITLE
Any reason why Queue::clean accepts status as 'wait' and not as 'waiting'?

### ISSUE THREAD

**Issue by mxs42** [OptimalBits/bull#1069]
https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueclean

> status: string; Status of the job to clean. Values are completed, **wait**, active, delayed, and failed. Defaults to completed.

Meanwhile, anywhere else Bull uses **waiting**.

Also, TS typings are wrong because of this:
`clean(grace: number, status?: JobStatus, limit?: number): Promise<Array<Job<T>>>;`
`type JobStatus = 'completed' | 'waiting' | 'active' | 'delayed' | 'failed';`

I think it should be named consistently across the library.

**Comment by mxs42** [comment]
What about marking 'wait' as deprecated and add support of 'waiting'?
I mean it's not a big deal obviously but still.

**Comment by manast** [comment]
yes we can add it also, but it can be confusing having a wait and waiting... for bull 4.0 we will have a chance to correct all this oddities.
