### ISSUE TITLE
Bull v0.2.4 compatibility with AWS Elasticache Redis 2.8.6

### ISSUE THREAD

**Issue by jboga** [OptimalBits/bull#107]
Hi there,
we are using bull v0.1.6 and considering upgrading to Bull v0.2.4.
We are very happy with Bull and want to use the new delayed jobs feature?
But a restriction on the Redis version (2.8.11 minimum) appeared in Bull v0.2.3 and our Redis instance version, deployed on AWS Elasticache, is 2.8.6.
Could you tell us from where did this restriction come from?
Is it from a bug in Redis introduced in 2.8.10 regarding the LUA scripts or is it for a new feature in Bull ?
I'll test v0.2.4 on our Redis instance anyway (bypassing your Redis version check) but wanted to get more information.
Thanks.

**Comment by albertjan** [comment]
Please see: https://github.com/OptimalBits/bull/issues/88

**Comment by jboga** [comment]
OK, thanks. I don't understand how I could not see that closed issue :-)
Sorry and thanks again.
