### ISSUE TITLE
Config option for rate-limiter to do nothing when enabled and hit

### ISSUE THREAD

**Issue by aleccool213** [OptimalBits/bull#1070]
## Description

* As apart of the async multi-repo pattern, I would like a config for the rate-limiter to do nothing when it gets hit.
* Currently it throws jobs into the delayed queue.

## Minimal, Working Test code to reproduce the issue.

```typescript
// enabling the rate limiter
const queueOptions = {
  rate: {
      max: 5,
      duration: 1000
    },
};
const queue = new Queue(description, queueOptions);
```

## Bull version
3.4.2

## Additional information

This has been discussed on this issue thread: https://github.com/OptimalBits/bull/issues/1053.
This issue is for tracking the new feature. I will be working on this.

**Comment by manast** [comment]
so it should be an optional setting like ```discard: true``` in the rate limiter options.
