### ISSUE TITLE
Question about ability to use wildcards

### ISSUE THREAD

**Issue by sebastianarena** [OptimalBits/bull#1081]
Hi.
I have this question about the ability to work a Queue together with named jobs.
Basically I have this requirement, where I need to handle FIFO jobs for thousands of different sources.
Each source needs to be handled by the same "processor", or function in this case, and I only need to handled FIFO jobs from them for each source. Meaning... if I have 1000 jobs from 1000 different sources, I could handled them all concurrently. However if a source gives me 10 jobs... I need to handled them one by one as they come in.

Basically I could solve this by adding 1000 queues... however the amount of sources is dynamic and I don't know beforehand how many there could be.

Is there something I could, with the process name, to say for example:

1) Declare Queue "handleJobs"
2) Then add jobs with name "handleJob-Source1", "handleJob-Source2", and so on...
3) Declare a processor like "handleJob-Source*" that takes jobs from any source, but maintains the FIFO added to each source?

Disclaimer: Right now I'm hashing the sources, and distributing them among a set of fixed queues... but I would be great if I didn't have to so something like that and allow real concurrency between them all.

Thanks!!

**Comment by manast** [comment]
If I understand your requirement correctly it really seems like you need to have one queue per job type, since as you wrote, the jobs of a given type must be processed in order... and since all the job types needs to be processed in parallel you cannot use a priority queue either.

**Comment by sebastianarena** [comment]
@manast thanks for replying! unfortunately I need to go deeper than having a queue per job type...
Separating queues per job type would be easy
The problem is scaling that even inside the job type
Say I need a job type "process", sent by producer 1, 2, and 3. Each producer is independent from the other, but each task sent by each producer would need to be FIFO. If I put all tasks in the same queue, it's not very efficient, as I could be running jobs in parallel... but it seems I can't. I would need 3 queues, "producer-1", "producer-2", "producer-3", etc.
That's why I asked if a consumer could use wildcard for say "producer-*", or similar that would allow me to process each task in a series while trying to parallelize everything.

It's similar to the concept of "Message Group ID" in an Amazon SQS.
Maybe the library had something similar.

Thanks
