### ISSUE TITLE
Why are you using lua to communicate with redis?

### ISSUE THREAD

**Issue by computersrmyfriends** [OptimalBits/bull#1083]
Hi,
Thank you for your work. I am trying out bull for a very serious project.

What is the reason behind using lua instead of a node library like ioredis?

And are you storing full json documents instead of individual keys? Wouldnt that affect performance?

Thanks

**Comment by manast** [comment]
We use ioredis, lua is used for atomic operations. In the latest benchmarks we are around 4500 jobs/sec in a single machine, unlikely that you will every reach that limit since the bottleneck will be your jobs code.

**Comment by computersrmyfriends** [comment]
I just did a basic test with a couple of queues on an existing application and it seems like it uses a lot of memory.But I'm not 100% sure if it is because of Bull. Does bull use a lot of memory? 

Thanks
