### ISSUE TITLE
Ability to disable use of Eval and/or Lua

### ISSUE THREAD

**Issue by ajwootto** [OptimalBits/bull#1088]
Hi,

We want to use Bull in an environment where Eval and custom script usage is disabled due to security restrictions. Is it possible to implement Bull such that it doesn't require these features to operate? I know it may affect performance significantly but it could be a useful configuration option for people with this use case.

Thanks

**Comment by manast** [comment]
No, that is not possible. It is not a matter of performance, but of atomicity. Without LUA many race conditions will appear and the queue will be very unreliable.

**Comment by chaffeqa** [comment]
is there any chance redis v6's additions could replace LUA?

**Comment by manast** [comment]
I don't think so.
