### ISSUE TITLE
Question drain event

### ISSUE THREAD

**Issue by telemmaite** [OptimalBits/bull#1092]
Hello, I noticed that the `drain event` is fired multiple times even though that I bind the listener only once.

Is this normal expected behavior? I did not see it the documentation.

I was going to use the `drain event` to call `queue.close` as I do not see any other way to do it properly when I have external processor file.

Thanks!

**Comment by manast** [comment]
```queue.close``` waits for current active jobs to finalize so you should not need to care about it yourself.

**Comment by telemmaite** [comment]
What I am after is a way to finish/complete gracefully my **consumer** node js process.
Similarly to how my **producer** process handles it by doing :
```
  let myQueue = new Queue(queueName);
  let jobs = [];

  for(let item of items){
    let job = {
      id: item.id,
      type: 'myType',
      ....
    };

    jobs.push(myQueue.add(job.id, job));
  }
  return Promise.all(jobs).then(()=>myQueue.close());
```

I can see in the docs that **[Queue.close](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueclose)** should be the one to use. 

> Closes the underlying Redis client. Use this to perform a graceful shutdown.

There are good examples on how to do it after X amount of jobs **after100**, also how to using the `process` callback. 
However what is the proper way to it when using a `processor` file?

Similar approach with _Promises_ as my producer example does not work(strange) in that case, or doing just:
```
  myQueue.process('*', 5, processorFile)
  myQueue.close();
```
