### ISSUE TITLE
[QUESTION] How to pause a delayed job?

### ISSUE THREAD

**Issue by elyran** [OptimalBits/bull#1093]
Pausing a queue is straightforward but it seems that delayed jobs (this includes cron jobs) execute even when the queue is paused.

Code reproduction:

```
const Queue = require('bull')
const theQueue = new Queue('test-queue', { settings: { maxStalledCount: 0 } })

theQueue.process(1, async (job, jobDone) => {
  console.log('Hi')
  jobDone()
})

const test = async () => {
  const job = await theQueue.add({}, { // Register a cron job (effectively creates a `delayed` job, AFAIK)
    repeat: {
      every: 1000 * 1
    }
  })

  setTimeout(async () => {
    await theQueue.pause(false) // Pause the queue
  }, 2000)
}

test()
```

If pausing it is impossible then I'd like to be able to tell if the queue is paused (right from within the job handler), but didn't find any solution for that on the API ref.

Any idea?

Thank you!

**Comment by manast** [comment]
For the record, calling ```theQueue.pause()``` will also pause repeatable jobs since they are just delayed jobs as any other.
