### ISSUE TITLE
[SUGGESTION] Reset finishedOn, processedOn and failedReason on job.retry

### ISSUE THREAD

**Issue by alolis** [OptimalBits/bull#1097]
Hello,

I would like to suggest to reset to `null` the `failedReason`, `processedOn` `finishedOn` fields whenever `job.retry` is used in order to allow code based on those fields to do further processing until job completes/fails.

Thank you for your time.

**Comment by alolis** [comment]
I worked around the issue like this for now:

```
class ExtendedJob extends Queue.Job {
  async retry() {
    this.failedReason = null;
    this.finishedOn = null;
    this.processedOn = null;

    await this.queue.client.hmset(
      this.queue.toKey(this.id),
      'finishedOn',
      this.finishedOn,
      'processedOn',
      this.processedOn
    );

    await this.queue.client.hdel(this.queue.toKey(this.id), 'failedReason');

    super.retry();
  }
}
```

**Comment by manast** [comment]
could be easily be converted into a PR 💃

**Comment by alolis** [comment]
@manast cool I will do it asap, just wanted to see if you approve first!

**Comment by alolis** [comment]
PR#1106
