### ISSUE TITLE
Error: Could not remove job

### ISSUE THREAD

**Issue by alolis** [OptimalBits/bull#1098]
## Description

I am experiencing the following error whenever I try to remove a job:

```
2018-10-23T14:08:46.619Z - debug: Error: Could not remove job 1
    at /myproject/node_modules/bull/lib/job.js:392:15
From previous event:
    at /myproject/node_modules/bull/lib/job.js:388:42
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

## Minimal, Working Test code to reproduce the issue.

I am using the sandboxed environment and the issue is reproducible even with a simple processor like so:

```
// processor.js
module.exports = function myProcessor(job, done) {
  setTimeout(() => {
    done();
  }, 60000);
}

// normal code
import Queue from 'bull';

const queue = new Queue('myQueue');

queue.process('/path/to/my/processor.js');
await queue.add({foo: 'bar'}, {uuid: 1});

const job = await queue.getJob(1);
await job.remove(); // error here
```

## Bull version

I am using **Node.js v6.9.1** with **bull v3.4.8** and **redis-server v3.0.7**

Also by looking at [this](https://github.com/OptimalBits/bull/blob/master/lib/commands/removeJob-8.lua#L2) I understand that I can remove jobs while in progress. Is this true? What is the correct way to force remove a job if indeed true?

Thank you for your time.

**Comment by manast** [comment]
you cannot remove a job white is is being processed, a job is in the active state and locked until it either: completes, fails or stales, although it should never stale if using a sandbox processor in practice.

**Comment by alolis** [comment]
@manast , thanks for getting back to me. Isn't there some workaround I can do without destroying the library? I find it very strange that nobody has requested this functionality!

**Comment by alolis** [comment]
UPDATE:

I tried to do the following which indeed removes the job from Redis but does not kill the processor process.

```
async remove() {
    await this.releaseLock();
    return super.remove();
 }
```

I didn't like it anyway because I do not want to mess with the locks.

The only way to do this probably is to signal via Redis pub/sub events and `throw new Error('removed')` in the processor to exit as it would normally do.....unless there is something else I could use which I am all ears!

**Comment by manast** [comment]
We have some discussion regarding aborting jobs here: https://github.com/OptimalBits/bull/issues/114
Basically there is no complication in just killing a running job if we are using a sandboxed processor, but what is a challenge is how to do it so that the worker can be closed graciously, still an open discussion.

**Comment by alolis** [comment]
@manast thanks for getting back to me. That discussion is going on since 2015 from what I checked. Last night I had a quick look at what's going on with cancel and I did the following change as an experiment:

```
// sandbox.js

'use strict';

var Promise = require('bluebird');

module.exports = function(processFile, childPool) {
  return function process(job) {
    return childPool.retain(processFile).then(function(child) {
      child.send({
        cmd: 'start',
        job: job
      });

      var done = new Promise(function(resolve, reject, onCancel) {      
        function handler(msg) {
          switch (msg.cmd) {
            case 'completed':
              child.removeListener('message', handler);
              resolve(msg.value);
              break;
            case 'failed':
            case 'error':
              child.removeListener('message', handler);
              var err = new Error();
              Object.assign(err, msg.value);
              reject(err);
              break;
            case 'progress':
              job.progress(msg.value);
              break;
          }
        }

        // Added onCancel handler!
        onCancel(() => {
          child.removeListener('message', handler);         
          reject(new Error('Job has been cancelled'));
        });

        child.on('message', handler);
      });

      return done.finally(function() {
        // Handle cancellation here by removing the job from db first and then killing
        // the process. I do this in that order so the job wont be restarted after the kill.
        if (done.isCancelled()) {         
          job.releaseLock().then(() => {
            job.remove().then(() => child.kill('SIGKILL');           
          }); 
        }

        childPool.release(child);
      });
    });
  };
};
```

```
// normal code
.on('active', function(job, jobPromise){
  jobPromise.cancel(); // Will remove job and kill sandboxed processor
});
```

Do you think you can provide me an alternative which might be better? I do not mind changing my fork and using that for now in order to have abort functionality but I must really implement something so I can complete the project I am doing.

**Comment by manast** [comment]
Unfortunately I have quite a log of workload right now so I could not say when I can implement such a feature. Although I think the right approach is exactly the one you are pursuing, i.e. a cancel mechanism inspired in promise cancellation.

**Comment by alolis** [comment]
@manast i understand although I wasn't expecting a feature implementation at this point, just your thoughts on how to solve it - temporarily at least on my side -. I did solve it yesterday with the sandbox approach I described above but it also required a change in the Queue class. The complete code I am now using, in combination with the refactored sandbox is the following:

```
class ExtendedQueue extends Queue {
  constructor(...args) {
    super(...args);

    this.jobPromises = {};

    this.on('active', (job, jobPromise) => {
      _.set(this.jobPromises, parseInt(job.id), jobPromise);
    });

    this.on('completed', (job) => {
      _.unset(this.jobPromises, parseInt(job.id));
    });

    this.on('stalled', (job) => {
      _.unset(this.jobPromises, parseInt(job.id));
    });

    this.on('failed', (job) => {
      _.unset(this.jobPromises, parseInt(job.id));
    });
  }

  getActiveJobPromise(jobId) {
    return _.get(this.jobPromises, parseInt(jobId));
  }
}

class ExtendedJob extends Queue.Job {
  async remove() {
    if (this.isActive()) {
      const jobPromise = this.queue.getActiveJobPromise(this.id);
      jobPromise.cancel();
    }

    await this.releaseLock();
    await super.remove();
  }

  async moveToFailed(error, ignoreLock) {
    await super.moveToFailed(error, ignoreLock);
    this.queue.emit('failed', this, error, 'active');
  }
}
```

If you look above, i keep track of the job promises inside the `Queue` class and cancel the promise on `remove` before removing the job itself. Seems to work well so far but I will keep testing.

**Comment by simpleshadow** [comment]
@alolis When you have a chance, mind sharing how you used the above?

Also can't believe no one else has asked to abort a job!

**Comment by manast** [comment]
@simpleshadow aborting a job at the end of the day will require your process function to be prepared for it, so basically you could also implement some signalling mechanism to your process function so that your code can fail the process earlier. All in all, a hard problem to solve but we are working on a more integrated solution.

**Comment by alolis** [comment]
@simpleshadow , how do you know which pid is associated to the forked process?

**Comment by kzidane** [comment]
@alolis @simpleshadow I'm curious if you ever found cleaner ways to achieve this?

**Comment by alolis** [comment]
@kzidane I haven't had the time to do something else other than what I described above. For the problem to be solved properly the fix must be done in the core library.

**Comment by entrptaher** [comment]
@manast The changes on the fork looks awesome. This would help with communication as well. Any chances to allow the changes of that fork into the core library? 

https://github.com/OptimalBits/bull/compare/master...alolis:rapiddot

**Comment by meetbryce** [comment]
Any chance this feature is still on the cards?

**Comment by kodeine** [comment]
any work on this yet?

**Comment by kodeine** [comment]
@alolis would you be able to update your fork with latest changes in bull merged with your updates?

**Comment by alolis** [comment]
@kodeine, my apologies for the very long delay in replying. I was trying to find some time to write everything more clearly and...well, you know what they say about time!

So, you can find the latest approach [here](https://www.alexanderlolis.com/riding-the-bull#removing-an-active-job-in-sandboxed-environments).

Let me know if you have any further questions.
