### ISSUE TITLE
"job stalled more than allowable limit" on sandboxed processor

### ISSUE THREAD

**Issue by hbakhtiyor** [OptimalBits/bull#1108]
## Description
getting the error with sandboxed processor, any reason why jobs stalling?

```
at /demo/node_modules/bull/lib/job.js:473:30
at tryCatcher (/demo/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/demo/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/demo/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/demo/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/demo/node_modules/bluebird/js/release/promise.js:694:18)
at _drainQueueStep (/demo/node_modules/bluebird/js/release/async.js:138:12)
at _drainQueue (/demo/node_modules/bluebird/js/release/async.js:131:9)
at Async._drainQueues (/demo/node_modules/bluebird/js/release/async.js:147:5)
at Immediate.Async.drainQueues (/demo/node_modules/bluebird/js/release/async.js:17:14)
at Immediate.args.(anonymous function) [as _onImmediate] (/srv/users/serverpilot/.config/yarn/global/node_modules/event-loop-inspector/index.js:138:29)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)

```

## Minimal, Working Test code to reproduce the issue.
<details>
 <summary>example.js</summary>

```js
const Queue = require('bull');
const path = require('path');

const uuid = 1;

async function sleep(delay) {
  return new Promise((ok) => {
    setTimeout(ok, delay * 1000);
  });
}

(async () => {
  const a = 1;
  const b = 2;

  const queue = new Queue('add');
  queue.process(path.join(__dirname, 'processor.js'));

  const job = await queue.add({a, b}, {jobId: uuid, removeOnComplete: true, removeOnFail: true, attempts: 3, timeout: 180000, backoff: 120000});

  queue.on('global:progress', async (jobId, data) => {
    if(jobId === job.id) {
      if (data === 0) {
        queue.close();
        console.log("closing");
        return;
      }

      await sleep(3);
      console.log(data);
    }
  });

  const result = await job.finished();
  console.log('finished processing', result);
})();

```
</details>
<details>
 <summary>processor.js</summary>

```js
async function addFunc(a, b, cb) {
  await sleep(1);
  cb(1);
  await sleep(2);
  cb(2);
  await sleep(2);
  return a + b;
}

module.exports = async function (job) {
  const result = await addFunc(
    job.data.a,
    job.data.b,
    (data) => {
      job.progress(data);
    }
  );

  job.progress(0);

  return Promise.resolve(result);
}
```
</details>

## Bull version
v3.4.8

## Additional information
node: v10.12.0
redis: 4.0.11

**Comment by manast** [comment]
thats not enough information to give any proper answer to your question. Please provide reproducible code so that we can look into it.

**Comment by hbakhtiyor** [comment]
updated, similar to my codebase, but my sandboxed processor is a bit heavy.

what do you think about using `queue.close()` inside event handler?

```js
  queue.on('global:progress', async (jobId, data) => {
    // ...
    queue.close();
    // ...
  })
```

what do you think about using this code instead of `removeOnComplete: true, removeOnFail: true` options?

```js
queue.on('global:completed', function(jobId, result) {
  const job = await queue.getJob(jobId);
  await job.remove();
});

queue.on('global:failed', function(jobId, err) {
  const job = await queue.getJob(jobId);
  await job.remove();
});
```

**Comment by manast** [comment]
> what do you think about using `queue.close()` inside event handler?
> 
> ```js
>   queue.on('global:progress', async (jobId, data) => {
>     // ...
>     queue.close();
>     // ...
>   })
> ```

Should work since close waits current processed jobs.

> 
> what do you think about using this code instead of `removeOnComplete: true, removeOnFail: true` options?
> 
> ```js
> queue.on('global:completed', function(jobId, result) {
>   const job = await queue.getJob(jobId);
>   await job.remove();
> });
> 
> queue.on('global:failed', function(jobId, err) {
>   const job = await queue.getJob(jobId);
>   await job.remove();
> });
> ```

Will work but it is less reliable than ```removeOn...``` since your worker could die just before managing the call to job.remove(), probably slower too.

**Comment by manast** [comment]
Btw, not need to return  ```Promise.resolve(result)``` if you are inside an async function...
