### ISSUE TITLE
[Feature request] removeRepeatable by job id

### ISSUE THREAD

**Issue by javorosas** [OptimalBits/bull#1111]
It would be super useful to be able to remove repeatable jobs on a case-by-case basis like this:

```javascript
queue.process('my-job', 5, async job => {
  console.log('processing job');
  if (someCriteria) {
    await queue.removeRepeatable(job.id)
  }
  // keep processing
});
```

Is this feasible?

**Comment by kulakowka** [comment]
@manast  Can you please explain why removal is so difficult?

I don’t use repeatable jobs at all, because I don’t understand how to delete them. I will be immensely grateful if you implement this functionality.

**Comment by manast** [comment]
@kulakowka  so why does this method not work for you? https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueremoverepeatable

**Comment by kulakowka** [comment]
I did not understand how to delete a task with a custom jobId. But then I studied the tests and found [this](https://github.com/OptimalBits/bull/blob/develop/test/test_repeat.js#L415). I think it would be great if we add examples of using these methods in the documentation.

**Comment by jmonster** [comment]
FWIW I was also just trying to figure this out and `removeRepeatableByKey` seems to solve my problem. It's unclear how, if at all, I can get `removeRepeatable` to work with my custom id and `repeat: { every: 8.64e+7` (daily) setting

The solution appears to be along these lines:
```js
const jobs = await queue.getRepeatableJobs();
queue.removeRepeatableByKey(jobs[0].key);
```

**Comment by ganeshcse2991** [comment]
When i tried using this method - **removeRepeatableByKey**  I am getting **removeRepeatableByKey** is not a function error.
`queue_1.taskQueue.removeRepeatableByKey is not a function`

**Comment by kulakowka** [comment]
I spent a lot of time to make it work. as a result, we had to use cron. ¯\_(ツ)_/¯

**Comment by ganeshcse2991** [comment]
I just switched from cron to BULL :(

**Comment by ganeshcse2991** [comment]
But if **removeRepeatableByKey** is working for everyone why is it not working for me. pls let me know what am I missing.

**Comment by manast** [comment]
@ganeshcse2991 can you provide a complete code snipped so that we can help you?

**Comment by amitava82** [comment]
Why can't we simply remove a repeatable job by ID?

**Comment by manast** [comment]
@amitava82 we already have it, ```removeRepeatableByKey```, what do you want to do that you cannot do precisely?

**Comment by amitava82** [comment]
`removeRepeatableByKey` Does not take the job ID. Assume a case where I my service post a job to bull and gets a jobId back, not the key. When my service wants to delete the job, it does not know the key. So, the solution to me, is that bull should be able to remove a job by given ID or return the key when a job is created.

**Comment by manast** [comment]
The problem is that bull cannot either know the repeatable job key from a given job id. What you can do is list all the repeatable jobs and pick the ID that matches the repeatable job that you want to remove.

**Comment by amitava82** [comment]
That won't be ideal when you have 1000s of jobs. Can't you return the key along with other payload when the job is created? I saw in the source there is a piece of code that does the key generation. I suppose I could copy and do it myself.

**Comment by fraywing** [comment]
Any update on this? Is there a way to remove a repeatable by jobId?

**Comment by jedspurg** [comment]
I think the biggest issue here is that it is not easy to key the repeatable key easily without listing all jobs. Is there a simple way to get the repeatable key when creating a job?

**Comment by kevin-coelho** [comment]
Still having this issue. No good way to remove repeatable jobs, and I'm using custom jobId.

**Comment by yojeek** [comment]
Not sure why the question was closed? At least give us repeatableJobKey when (well) repeatable job is created, so we can save it somewhere.

**Comment by jedspurg** [comment]
I ended up copying this function into my application and storing this key in a database.

https://github.com/OptimalBits/bull/blob/develop/lib/repeatable.js#L185

```javascript
function getRepeatKey(name, repeat, jobId) {
    const endDate = repeat.endDate
      ? new Date(repeat.endDate).getTime() + ':'
      : ':';
    const tz = repeat.tz ? repeat.tz + ':' : ':';
    const suffix = repeat.cron ? tz + repeat.cron : String(repeat.every);

    return name + ':' + jobId + endDate + suffix;
  }
```
