### ISSUE TITLE
When to use named jobs?

### ISSUE THREAD

**Issue by tonyxiao** [OptimalBits/bull#1112]
Rather than just use a separate queue? The documentation doesn't really explain the use case differences.

**Comment by alolis** [comment]
In my case, I have a per user queue and I use named processors to separate the multiple processors I attach to each queue.

**Comment by tonyxiao** [comment]
@alolis can you say a bit more?

**Comment by manast** [comment]
named jobs are just useful for modularising your code, they do not provide any other higher level function, it is still one queue and all the jobs are processed in order independently of their names.

**Comment by alolis** [comment]
> @alolis can you say a bit more?

Yeah sure. I have a system where each user of the system gets his own `Queue` and multiple named processors are attached to the queue (e.g. copyFile, moveFile, downloadFile etc).
