### ISSUE TITLE
Question: to handle a long background jobs, should I use callback or promise version handler ? 

### ISSUE THREAD

**Issue by qiulang** [OptimalBits/bull#1115]
Hi,
This is a question. All my tasks are long background jobs, downloading files most of time. So does it make any difference to use callback version of promise version of task handler ? Once the task is started, I mainly care about whether it succeeds or fails.

queue.process((job, done) => {...}) or queue.process(async (job) => {...})

Thanks!

BTW, I am using the latest version

**Comment by manast** [comment]
it does it matter, but we are in 2018 now, so maybe better to use promises instead :)
