### ISSUE TITLE
Question: will it be a problem that I don't call done in queue.process, but call job.moveToCompleted in another callback ?

### ISSUE THREAD

**Issue by qiulang** [OptimalBits/bull#1120]
## Description
Hi, my job  has 3 stages,  (1) first download files from a file server, (2) then send the files to another server to further process. After the server finishes processing it will send the updated files back to my share folder. I have a watcher (chokidar) to monitor the share folder, when the watcher finds there are new files, it will notify job to continues and (3) finishes the final stage.

I am struggling in using bull to do that. For example, I come up a solution that is quite awkward. 
So after sending files to another server, I don't call done in queue.process but just return. And in the watcher I call job.moveToCompleted after job is finished. The codes are like this

```
queue.process((job, done) => {
    //1. download files
    //2. upload to another server
    //3. do not call done b/c job is not finished, this also means I can't use the promise version of process.
}

watcher.on('add',  pathName => {
      // continue the job, after we finish the job
      job.moveToCompleted
})
```

So can you help with a better solution ?

**Comment by manast** [comment]
Why not use 3 queues? the first queue downloads the file, and adds a job to the second queue. The second queue uploads to another server and adds a job to the third queue. Now the third queue is special because you want to run the job only after the watcher calls the callback, so one idea is to add the job with a very high delay setting (infinite?), and then when the watcher callback is called you can "promote" the delayed job so that it gets executed.

**Comment by manast** [comment]
btw, if you instead of using infinite in the delay you can put a sensible delay and use it for expressing a timeout.

**Comment by qiulang** [comment]
Hi thank you very much for replying my question. Actually after raising the question we came up with a similar idea like yours, i.e. a specific queue for watcher. But we don't know we we can delay and promote a job so our solution is to let watcher add jobs when it finds new files.

Can I ask another question ? The document said " in order to determine whether job completion is signaled by returning a promise or calling the done callback".

```
// THIS WON'T WORK!!
queue.process(function(job, done) { // Oops! done callback here!
  return Promise.resolve();
});
queue.process(function(job) { // No done callback here :)
  return Promise.resolve();
});
```

But it seems not considering the situation of that  `queue.process(async job => {...} )` , i.e. if I add **async** and return nothing, node will add return` Promise.resolve()` for me. So if I use `queue.process(async job => {...} )`  bull will complain `no done in callback`.

But it still complains no done in callback when I return Promise.resolve() for my async job. Why is that ?

queue.process(async job => {
   ...
  return Promise.resolve(); //Add this myself
});

**Comment by manast** [comment]
I do not have time to test this now, but as you say, it should be enough to write the process function like this:
```js
queue.process(async job => {
  // dummy
});
```

**Comment by manast** [comment]
do not use done and promises at the same time, only one or the other.
