### ISSUE TITLE
Possible unreachable code and question

### ISSUE THREAD

**Issue by alolis** [OptimalBits/bull#1121]
Hello,

I was going through the library and I found the following:

https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L1045
```
return job.moveToFailed(err).then(function(jobData) {
      _this.emit('failed', job, error, 'active');
      return jobData ? _this.nextJobFromJobData(jobData[0], jobData[1]) : null;
    });
```

At the code above, when `moveToFailed` resolves, it should return `jobData` but if you go [here](https://github.com/OptimalBits/bull/blob/master/lib/job.js#L273), you will see that `resolve` does not include anything as parameter so `jobData` is basically never returned and as a result. 

```
return multi.exec().then(function(results) {
      var code = _.last(results)[1];
      if (code < 0) {
        return reject(scripts.finishedErrors(code, _this.id, command));
      }
      resolve(); <---- Nothing is passed to resolve
    }, reject);
```

If this is true, and `_this.nextJobFromJobData(jobData[0], jobData[1])` never gets called, where/how does the queue gets the next job after the previous one has failed?

**Comment by manast** [comment]
It is a known issue. The code is basically prepared so that it will work faster the day we can return the job data from failed jobs. As it is now it works in the normal loop (calling BRPOPLPUSH), so it requires one extra roundtrip to redis, however, failed jobs should be unusual and therefore this optimization is not so critical.

**Comment by manast** [comment]
good observation btw ;).

**Comment by alolis** [comment]
Ah I see. You can close this if you want since it's already known!
