### ISSUE TITLE
moveToFailed works but bull:wait has this job still

### ISSUE THREAD

**Issue by guanlulu** [OptimalBits/bull#1122]
moveToFailed works but bull:wait has this job still

## Description
I invoke 
```js
var job = await queue.getJob(1)
await job.moveToFailed(new Error('error'), true)
```
this job 1 move to bull:name:failed correctly,but this job still exist  bull:name:wait 
so when i retry this job ,job back to bull:name:wait, now it has two job 1!!!
how to resolve it ?
if you can give a hand ,i will be deeply grateful.

## Bull version
3.4.8

**Comment by alolis** [comment]
Try to `job.discard()` first before calling `job.moveToFailed`

**Comment by manast** [comment]
@guanlulu ```moveToFailed``` should only be used if you manually moved the job from the wait list to active manually.

**Comment by guanlulu** [comment]
@alolis job.discard() do not work
and i have another problem，how to pause a job instead of a  queue
i try to move the job to failed queue, but appear above question ,please give me a hand

**Comment by guanlulu** [comment]
@manast  explanation at doc  is `Moves a job to the failed queue`, Is this not contradictory?

**Comment by manast** [comment]
@guanlulu you cannot use moveToFailed directly unless you get the jobs manually using ```queue.getNextJob()```, see this usage pattern: https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#manually-fetching-jobs

**Comment by abdolrhman** [comment]
@guanlulu hey mate
did u find a solution because I have the same problem, 
I want to move a job from waiting directly to failed and it should be removed from the waiting queue ?
thank you

**Comment by sibelius** [comment]
what is the correct way to `fail` a job to make it retry with exponential backoff ?
