### ISSUE TITLE
How do I know when a job has failed forever?

### ISSUE THREAD

**Issue by samclearman** [OptimalBits/bull#1124]
If I have a job with auto-retry enabled, what is the recommended way to perform some action when the job fails all retries?

I think I can write a check inside the processor that does
```
if (job.attemptsMade === job.opts.attempts) {
    permanentFailHandler(job);
}
```

Is this the right way?

**Comment by manast** [comment]
could work, give it a try to see if it works. I think we have a pending enhancement to emit an event when a job has failed permantently.

**Comment by eduardrock** [comment]
@manast.  now in 2019, Is there solution for that?
