### ISSUE TITLE
Upgraded lint-staged package breaks precommit hook with node v6.x

### ISSUE THREAD

**Issue by alolis** [OptimalBits/bull#1133]
## Description

The `lint-staged` packaged was recently upgraded to `^8.0.4` from `^7.1.0`. 
As a result, if you run `npm run precommit` with Node v6.x you get the following error:

```
> bull@3.5.2 precommit 
> lint-staged

undefined requires at least version 8.6.0 of Node, please upgrade
```

## Bull version
v3.5.2

## Additional information
node v6.9.1

**Comment by manast** [comment]
well I guess we can require node > 8 for development, we are on version 10 LTS now :).
