### ISSUE TITLE
Delayed/repeatable jobs not getting invoked

### ISSUE THREAD

**Issue by designhata** [OptimalBits/bull#1138]
I'm facing this weird behavior where sometimes delayed/repeatable jobs, after getting scheduled, doesn't invoke on specified time.

It happens randomly. Sometimes jobs get invoked just fine & sometimes they don't. Also there is no log/response if the job doesn't get invoked. I see them in the queue with the help of `getJobs()` function.
In order to invoke the job I have to add it again to the queue with same specification.

I test the job invocation by manually setting my machine time to few seconds before the job time.

Job configuration:

`jobQueue.add(jobName, {
                        user: user._id
                    }, {
                        repeat: {
                            cron: `00 01 07 * *`,
                            tz: 'Asia/Kolkata',
                            // Make sure that job doesn't start immediately but for the next month
                            startDate: new Date(moment().add(8, 'day'))
                        },
                        removeOnComplete: true
                    });`

How can I debug this? Is this something happened before with someone? Am I doing something wrong with the configuration?

**Comment by hilaldib9** [comment]
What happens when you don't set it so far out that you have to change system time (maybe a few seconds)? Maybe there's an issue with changing time locally and how that affects Redis?

**Comment by manast** [comment]
@designhata without any code that reproduces the issue is really hard to give you help :/

**Comment by ianp** [comment]
Looks like both jobs ran OK next time around, not exactly sure what that tells us though?
