### ISSUE TITLE
jobs stop working if redis is flushed

### ISSUE THREAD

**Issue by jrcastillo** [OptimalBits/bull#1143]
***Question***

Is there any way to register all jobs again if redis variables are flushed, or implement somewhere a fallback ?
We have tried using all type of events provided in the documentation but with no successful way to avoid stop working.

## Description
Currently on our production environment we are having problems with redis so multiple teams keep on flushing redis, and every time this happens our Jobs just stop working. 

## Minimal, Working Test code to reproduce the issue.
- Register some jobs (best if they work every minute)
- Wait until they start executing
- Flush redis

## Bull version
   - "bull": "3.4.8",
   - "bull-arena": "2.4.5"

**Comment by manast** [comment]
If I understand this correctly you mean that after deleting all the data in redis the queues stops working? If that is the case, then I am afraid it works as design, not sure what other behaviour should be the expected one.

**Comment by jrcastillo** [comment]
Yes you understood well, but my question is there any way to validate that the keys exist ? and if they don't exist then recreate everything like the process just started ? 

This because our redis is a shared instance that many teams have access to and there is always someone that says ... flush redis. 

Can you recommend an approach/workaround for this particular "issue"

**Comment by manast** [comment]
Since this use case is not taken into consideration, there can be all kind of unknown hazards. For example I have no idea what happens if a jobs completes and just before that redis get flushed.
Can't you just use the db functionality (https://redis.io/commands/select) to have your own reserved space of the redis instance for yourself?
