### ISSUE TITLE
Question: add multiple jobs by batches

### ISSUE THREAD

**Issue by loris** [OptimalBits/bull#1144]
Hi,

Considering moving from other queues (rabbitmq and agenda) to bull, but would like some insight on one of our use cases: we need to create and store jobs as fast as possible into bull (does not matter if processing is slower), for instance we have use cases where we stream CSV/JSON files and need to create a job per line.
Having a look at the code, it looks like adding a job can only add a single job and requires multiple redis commands. Would it make sense to use redis (am not proficient in redis) pipelines to adding multiple (let's say 100) by batches? Is bull/redis already fast enough so that it can add thousands of jobs per seconds without relying on pipelines?

Thanks!

**Comment by manast** [comment]
you should be able to enqueue many thousands of jobs by calling add in parallel. You can write a simple benchmark for this where you add in parallel using Bluebird and test with different concurrency factors: ```http://bluebirdjs.com/docs/api/promise.map.html```

**Comment by loris** [comment]
Thanks @manast for your reply! Will do some benchmarks by doing parallel calls.
But pipelining should be something bull could implement, it is faster than parallel calls by an order of magnitude (https://redis.io/topics/pipelining) since it removes the network overhead

**Comment by manast** [comment]
yes, I know about pipelining. Add is quite fast already so we have not prioritised its implementation, but for batch adds it makes a lot of sense.
