### ISSUE TITLE
Failing to move a job to completed causes retries

### ISSUE THREAD

**Issue by quinlanjager** [OptimalBits/bull#1145]
## Description

Currently if a job completes but the `moveToCompleted` function fails, it's moved to a failed state and the job is retried. In most cases if the `moveToCompleted` function is reached the job handler has completed it's task. Thus causing a retry seems redundant.

In my program, I'm encountering case `-2` in the [`finishedErrors` function](https://github.com/OptimalBits/bull/blob/9393e3d5bf2418520d423e1f8ac612767ce53e5b/lib/scripts.js#L182) while processing a long running job. This job has it's `stalledInterval` set to `0` so the lock should stick around if my understanding is correct. 

Is it possible for the `moveToCompleted` failure case to be handled internally? Or skip the "retry" portion of the failure handler?

## Bull version

3.4.1

**Comment by manast** [comment]
This long running job is keeping the CPU busy? In that case maybe you would get better results by using a sandboxed processor instead: https://github.com/optimalbits/bull#separate-processes

**Comment by quinlanjager** [comment]
Thanks for your reply. It is certainly keeping the CPU. I have considered moving to the sandboxed process but will that solve this issue? Shouldn't removing the chance of stalling keep the lock intact?

**Comment by manast** [comment]
The lock is renewed by the main process, so if your worker keeps the CPU busy, it has no chance to renew it and issues as the one described could happen. In general, the recommended way of using Bull is to either have a process that does not block the CPU so much or to put the processor on a separate sandboxed process.

**Comment by quinlanjager** [comment]
Thanks I'll give the sandboxed process a try!
