### ISSUE TITLE
Rate Limiter Not Working

### ISSUE THREAD

**Issue by hilaldib9** [OptimalBits/bull#1147]
## Description
Jobs are all being processed without regard for rate limiting.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

```
var queue = new Queue('jobs', constants.redisUrl, {
  limiter: {
    max: 1,
    duration: 1000000
  }
});

var counter = 0;
queue.process('test', function() {
  console.log("Function counter: " + counter);
  counter++;
});
for(var x = 0; x < 1000; x++) {
  queue.add('test');
}

```

Running this code, jobs are processed instantly and are not delayed/limited.
## Bull version
3.4.8

**Comment by manast** [comment]
This example rate limits one job every 16 minutes approx. I do not have time to test it, but other shorter times work perfectly. Do you mean that it does not for very large values?
