### ISSUE TITLE
Question : How to check a queue is in already processing?

### ISSUE THREAD

**Issue by sharmilasudhakar** [OptimalBits/bull#1149]
I want to check and assign the queue.process function for a queue. If i add several queue.process then the queue running in all the process parallelly. At any cast I want only single processing for the queue, So how can i check a queue is already processing? 

Bull version : latest

**Comment by manast** [comment]
By design if you specify more workers the queue will process in parallel, we do not have any option to process serially in that case.

**Comment by sharmilasudhakar** [comment]
Can I get the count of number of workers?

**Comment by manast** [comment]
Yes you can: https://github.com/OptimalBits/bull/blob/9393e3d5bf2418520d423e1f8ac612767ce53e5b/lib/worker.js#L18

**Comment by sharmilasudhakar** [comment]
Thank you !
