### ISSUE TITLE
One queue with dedicated messages to each server

### ISSUE THREAD

**Issue by victornikitin** [OptimalBits/bull#1154]
SITUATION
We have several servers, each server get http-requests, and set job to queue. Any other server can process this job. But only the same server that have got http-request should return result in his http-response.

OUR SOLUTION
We made one queue for jobs and another one for results. For results we made a named queue (pass name argument in process function). Each server listen for the same queue "results" but with unique names (name=serverId).

PROBLEM
But messages were stucked. In Arena log we saw error message "Error: Missing process handler for job type [name here]". We think that messages were got by one of the servers that is not listening for this nemad queue (he is listening for another name). So if a named queue is used, listener still gets ALL messages from queue and only after that call process function for message if it has any. We thought that listener WILL nOT get messages that are not mentioned in process function.

QUESTIONS
1. Should process function of named queues get all messages from queue or should get messages only by mentioned names?
2. Maybe there is another solution for our case?

**Comment by manast** [comment]
For this particular use case, couldn't you just use the ```Job##finished``` method?
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#jobfinished

**Comment by victornikitin** [comment]
@manast 
No. Because in our case there can be many jobs between first one and the last with result:
Server X → Job (to any server) → Job (to any server) → ... Job (to any server) → Result to exactly Server X

For right now me made a personal queue for each server. And a message in Jobs queue know to which result queue it should send result. We also destroy each result queue on each server shutdown.

Is ther a better way with Bull?

If not, how to destroy queue totaly (we use clean() and empty() methods). But in redis there are still some keys related to thsee queuies.


OUR VISION
We think the best solution is that if a Name is set in queue process method, queue SHOULD NOT get other messages from queue (if "*" is not set as Name in process method).
