### ISSUE TITLE
Redis Configuration for most durable setup (AWS elastic cache)

### ISSUE THREAD

**Issue by mladen107** [OptimalBits/bull#1159]
We are integrating Bull in our product for managing scheduled jobs and we have requirement to never loose any jobs in the queue. 
What is the recommended way of configuring Redis in AWS elastic cache for the highest durability?

**Comment by cyrilselasi** [comment]
@mladen107 I'm curious as to how you went about setting this up?

**Comment by stansv** [comment]
Bull provides at-least-once semantics for acquiring jobs from queue, it means that you'll never lose jobs but in case of failures job can be processed more than once. In case of clustered Redis setup make sure you're set a hash tag to queue as explained here https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#redis-cluster

**Comment by cyrilselasi** [comment]
Thanks for the response. I didn't notice the Patterns file.
