### ISSUE TITLE
Unique queue events

### ISSUE THREAD

**Issue by mxstbr** [OptimalBits/bull#1160]
Suppose I have two servers, both handling the same queue. One of them adds jobs, the other processes them. If I listen to events on the queue, will they fire on both servers?

```JS
// server1
const myQueue = new Queue('mine');

myQueue.add(/* ... */)
myQueue.add(/* ... */)

myQueue.on('completed', () => { /* ... */ })
myQueue.on('failed', () => { /* ... */ })
myQueue.on('active', () => { /* ... */ })
myQueue.on('waiting', () => { /* ... */ })
```

```JS
// server2
const myQueue = new Queue('mine');

myQueue.process(job => { /* ... */ })

myQueue.on('completed', () => { /* ... */ })
myQueue.on('failed', () => { /* ... */ })
myQueue.on('active', () => { /* ... */ })
myQueue.on('waiting', () => { /* ... */ })
```

The reason I'm asking is because we'd like to track these metrics in our metric tracking system (DataDog), but I'm afraid that the events will fire on both servers, causing our metrics to be duplicated. In our case, we have 7 servers, so would we get every metric for every job sent 7 times to DataDog, once per server?

If so, how could we get reliable metrics?

**Comment by manast** [comment]
You will only receive the events on the same worker that is producing the event unless you prefix the event name with ```global:``` in which case you will receive the events produced by all the workers.

**Comment by mxstbr** [comment]
I understand that, but given that the job is added by one worker and processed by the other, will both receive the `active` and `completed` events? Which one will receive which events if not?

**Comment by manast** [comment]
The worker will produce the event.

**Comment by mxstbr** [comment]
Okay so it will only fire once. Follow-up question, is the same true for `queue.getJobCounts()` or will that report _all_ jobs?

**Comment by manast** [comment]
@mxstbr I think that is the best that can be achieved today. In Bull 4 we will use streams for events, and then you will get very reliable events, never lost even in case of intermittent connections.
