### ISSUE TITLE
Logging for jobs

### ISSUE THREAD

**Issue by jd20** [OptimalBits/bull#1165]
Is there a way to attach logs to a job, similar to Kue's `job.log()`? I read through the Bull docs, but couldn't find anything. It wouldn't be too hard to implement alongside Bull, but integrating into the Web UI would be a challenge.

**Comment by manast** [comment]
This could be easily be implemented using redis 5.0 streams now, but probably a new feature for bull 4.0 instead of 3.x.

**Comment by jd20** [comment]
Was looking at Kue's source code for `log()`, it actually just uses a Redis list, I'm thinking that would work too, since the only operations you ever do is just append, or fetch the whole list (and the lists generally don't get that big).
I could try taking a stab at implementing this, once I finish porting my code over from Kue to Bull, and get a bit more familiar with it. What's the timeline for 4.0?

**Comment by manast** [comment]
The development of the 4.x version is being done here: https://github.com/taskforcesh/bull
A big PR is coming in the following weeks.
A list per job is feasible although it will pollute the redis keyspace quite a lot, we should think which is the cleanest way to do this.

**Comment by jesperp** [comment]
Great stuff! Will this be released any time soon?

**Comment by manast** [comment]
released in v3.9.0
