### ISSUE TITLE
removeOnFail not working as expected

### ISSUE THREAD

**Issue by iamgr0ot** [OptimalBits/bull#1169]
## Description
Our setup is pretty simple. We are emitting a simple job with `removeOnFail` option set to `true`. The jobs are getting removed after failure successfully (most of the times), but sometimes, the failed job sticks around. How do we fix this? (This is not easy to reproduce).

## Bull version
3.5.1

**Comment by iamgr0ot** [comment]
@manast - This happens when the task goes to `stuck` state. Do you know about why tasks goto stuck state?

**Comment by fluffybunnies** [comment]
I have this issue as well! I have to manually remove the queue to get it going again.

**Comment by manast** [comment]
@iamgr0ot in fact there is not a stuck state. I think you mean that the job has failed due "got stuck" too many times. In that case maybe the logic for removing the failed jobs is not working. I will have to look into it. But I recommend you that you find out why this happens, jobs failing because of this are normally due to processors that hand the event loop too much, i.e, you should avoid this anyway.

**Comment by iamgr0ot** [comment]
@manast - I queried the job state from bull redis and this is what I get:
`{"state":"stuck"}`

**Comment by manast** [comment]
@iamgr0ot you are probably keeping the event loop busy for too long. You need to be careful that your process functions do not take too much CPU, in that case divide the job by doing calls to ```process.nextTick()```.

**Comment by IvanMMM** [comment]
Got same bug here. Using same jobId to prevent job duplicates, so it's critical for my case. That's what I got in redis after job got stucked
![image](https://user-images.githubusercontent.com/3692403/53051677-bad4b700-34ad-11e9-8266-61570c59fbb1.png)

**Comment by manast** [comment]
@IvanMMM can you provide a bit more of background of your case? and if possible some code that reproduces the issue in your end?

**Comment by IvanMMM** [comment]
@manast I'm afraid not. It happens randomly with some tasks and after flushing tasks it works fine. Also I noticed that failed tasks as I'v send on my previous message are not showing in any list and the only way to remove them is to delete them directly from redis.

**Comment by manast** [comment]
Ok, I will review the code that handles failed tasks to see if there is any hazard that may explain the issue.

**Comment by IvanMMM** [comment]
As a temp solution, I wrote a script to search for stuck tasks and remove them from redis.

```javascript
async function removeStuckJobs() {
        let removed = 0;
        let allJobs = [];
        await Promise.each([
            'postUpdater',
            'collector',
            'engager',
            'statistics',
            'proxy',
            'master'
        ], async (taskName) => {
            allJobs = allJobs.concat(await global.conn.redis.keysAsync(`sstiv:${taskName}:*`))
        });
        await Promise.map(allJobs, async (key) => {
            const result = await global.conn.redis.evalAsync('' +
                'if redis.call("TYPE", KEYS[1])["ok"] ~= "hash" then ' +
                'return; ' +
                'end; ' +
                'if redis.call("HEXISTS", KEYS[1],"stacktrace") == 1 then ' +
                'return redis.call("DEL", KEYS[1]); ' +
                'end',
                1, key);
            if (result === 1) removed++;
        });
        console.log(`Removed ${removed}/${allJobs.length} jobs`);
    }

setInterval(removeStuckJobs, 1000 * 60 * 1);
```

**Comment by dko-ahoyhoy** [comment]
I also noticed the exactly same issue. The main key is in Redis (and if I run q.getJob() for it, the job is returned!), but this job is not visible in any lists, e.g. q.getJobs() does not return it.

This happens with failed jobs only. E.g. in the snippet above, Ivan distinguishes such redis keys by "stacktrace" key in the hash as a work-around. I've never seen stuck succeeded jobs, I see only those which were aborted by an exception (an exception may be unrelated to redis, as in my case).

Sounds like a non-atomic operation somewhere which remains the main job key (aka its name) in Redis, but wipes it from all lists.

**Comment by jg-coetzee** [comment]
job state: stuck, removing from queue ---
[Nest] 129  - 05/07/2024, 2:30:19 PM   ERROR [SurveyQueue] Failed to completed job f66a3838accc0d38e2fb2636c3ef57bc42bbec030c05eff1cd1d005032836e8e, with error: Cannot read properties of undefined (reading 'emit')
      job state: stuck, removing from queue ---
