### ISSUE TITLE
Getting Queue By Name

### ISSUE THREAD

**Issue by adamsoffer** [OptimalBits/bull#1171]
It's possible to create queues with unique names, but is it also possible _get_ a queue by name?

For example, if I create a queue named "image transcoding", how do I then retrieve it?

**Comment by adamsoffer** [comment]
Ah nevermind. It seems as though Bull does not create anything in redis when you instantiate a queue

**Comment by ashkank83** [comment]
@adamsoffer Did you find out how to get the Queue? I need to retrieve a Queue in order to add jobs to it from a separate process but can't find out how! Thanks

**Comment by manast** [comment]
can we close this?

**Comment by adamsoffer** [comment]
@ashkank83 I did not unfortunately. 

@manast yeah we can close this. I ended up going about the requirement for my app differently.
