### ISSUE TITLE
add repeat not working as expected

### ISSUE THREAD

**Issue by developer239** [OptimalBits/bull#1172]
## Description
Notice that I want to run the job every 5 minutes but it was executed after every minute. At `21:05` for some reason twice...
![image](https://user-images.githubusercontent.com/14946081/51090150-c844a600-1777-11e9-9a8e-253ee6f4f72b.png)

## Minimal, Working Test code to reproduce the issue.
```
const Bull = require('bull')
const moment = require('moment')

const queue = new Bull('my first job', 'redis://127.0.0.1:6379')
queue.process(() => {
  console.log(`Start Date: ${moment().format('D. M. YYYY k:mm:ss')}`)
})
queue.add(null, { repeat: { every: 300000 } })

```

## Bull version
`"bull": "^3.5.2",`

**Comment by swang2019** [comment]
I just copied your code, and run to my computer, it **works** as normal. 

<img width="335" alt="screen shot 2019-01-19 at 10 54 38 am" src="https://user-images.githubusercontent.com/46506305/51421393-a5334f80-1bd8-11e9-8def-7e59378ade20.png">

<img width="529" alt="screen shot 2019-01-19 at 10 55 03 am" src="https://user-images.githubusercontent.com/46506305/51421397-b5e3c580-1bd8-11e9-9d0d-4c90b4b7f889.png">

**Comment by developer239** [comment]
🤯thank you for your time. I ended up using Heroku Scheduler. I will get back to this later and try to figure out what is wrong with it.
