### ISSUE TITLE
How to add a job to queue defined in separate service?

### ISSUE THREAD

**Issue by booboothefool** [OptimalBits/bull#1176]
```
ServiceA
ServiceB has QueueB definition/processors/events
```

From `ServiceA`, is there a way I can add a job to `QueueB` defined in `ServiceB`?

After reading the docs, it sounds like I would need to duplicate the `QueueB` definition in both `ServiceA` and `ServiceB` in order to call `QueueB.add(job)` from `ServiceA`. I imagine if I just did `new Queue('QueueB')` in `ServiceA` to call it, it would complain about not having the processors, which are actually defined in `ServiceB`.

I imagine there's a better way since everything is connected by Redis?

**Comment by manast** [comment]
@booboothefool you do not need to define a processor. You can just instantiate a Queue and use it for adding jobs that are processed by other workers defined in other processers or machines.

**Comment by aleccool213** [comment]
@booboothefool you may want to read: https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#manually-fetching-jobs
