### ISSUE TITLE
Upgrade to ioredis 4.x

### ISSUE THREAD

**Issue by sarneeh** [OptimalBits/bull#1183]
## Description
There was an [issue](https://github.com/OptimalBits/bull/issues/1025) addressing this but for some reason (most likely because the issue was about two things), this one change was missed and the issue has been closed. `ioredis@4.x` has already many improvements and fixes which would be cool to have.

Are there any reasons why `bull` does not depend on the `4.x` version for now? It's almost half a year since `4.0` got published.

**Comment by manast** [comment]
Fixed in v3.5.3

**Comment by sarneeh** [comment]
@manast That was fast! Thank you! 😄
