### ISSUE TITLE
Cannot dynamically increase concurrency of a queue

### ISSUE THREAD

**Issue by anurag-rai** [OptimalBits/bull#1187]
## Description

Suppose a queue is declared as `queue.process(concurrency, foo)` with some `concurrency`. 

If there are additionally more jobs to process later on, and I have to increase the concurrency of my queue, I need to restart my application and re-initialise my queue with the new concurrency.

1. I could not find anything in the doc as to how to do this dynamically, so is there any API or any way that can dynamically increase the concurrency of the queue without having to restart the application? 

2. If I redefine the `process` with `queue.process(new_concurrency, foo)`, are there any repercussions to the jobs that are currently running in this queue? Or is this the way I can increase the concurrency dynamically?

3. Any API to get the current concurrency of a queue? WIP or future plans or against Bulls ideology?

## Bull version
`bull: "^3.3.7"`

**Comment by Bellk17** [comment]
I would second this. My use-case is IO-bound, so much simpler if there was a way to update the concurrency vs spinning up new processes.

**Comment by manast** [comment]
I will leave this one as an enhancement, it would be a new method to change the concurrency setting of a queue.

**Comment by G1K** [comment]
related https://github.com/OptimalBits/bull/issues/290
much needed improvement.

**Comment by manast** [comment]
Why not just start the queue with the highest concurrency setting you would like? I do not see the point in having less concurrency than the max you want to have. Maybe there is something I am missing.

**Comment by aishadeshmukh** [comment]
> I will leave this one as an enhancement, it would be a new method to change the concurrency setting of a queue.

Has this been implemented?

**Comment by manast** [comment]
It is implemented in BullMQ https://api.docs.bullmq.io/classes/Worker.html#concurrency
No plans ATM to backport it.
