### ISSUE TITLE
multi instance cron problem

### ISSUE THREAD

**Issue by arvandiii** [OptimalBits/bull#1189]
running node server with pm2 (number of instances are 2)

Queue.add({}, { repeat: { cron: '*/5 * * * * *' }, removeOnComplete: true })

It runs 2 times each 5 second. is it working as expected?
How can I use it to run only one time each 5 seconds with multiple instances?

Bull version : 3.5.2

**Comment by manast** [comment]
What if you do not use the ```removeOnComplete``` feature, does it still run twice?

**Comment by arvandiii** [comment]
I think I found the problem

Result of code below is not as expected for the first 2 or 3 crone jobs (run more than one time each 5 second) after that it is running only each five seconds

```
const Queue = require('bull')
const Promise = require('bluebird')
const Redis = require('ioredis')

Redis.Promise = Promise

const client = new Redis(6379, 'redis')
const subscriber = new Redis(6379, 'redis')

const opts = {
  createClient: (type) => {
    switch (type) {
      case 'client':
        return client
      case 'subscriber':
        return subscriber
      default:
        return new Redis(6379, 'redis')
    }
  },
}

const q = new Queue('test', opts)

q.process(async () => {
  await Promise.delay(1000)
  console.log('run')
})

setTimeout(() => {
  q.add({}, { repeat: { cron: '*/5 * * * * *' }, removeOnComplete: true })
}, (Math.random() * 100) | 0)
```

output:
```
19:14:38 0|kanala   | run
19:14:41 2|kanala   | run
19:14:46 2|kanala   | run
19:14:51 0|kanala   | run
19:14:56 3|kanala   | run
19:15:01 3|kanala   | run
19:15:06 3|kanala   | run
```
