### ISSUE TITLE
Is it possible to re-schedule a job ?

### ISSUE THREAD

**Issue by SimoneTaliercio** [OptimalBits/bull#119]
Me again : )

Is it possible to re-schedule the same exact job ?

I'm in a situation where 

```
queue.process(function(job, done)){

If(condition){
   // re-add the job to the queue with a delay
}else {
   ...job logic...
    done()
}

}
```
How can I implement it ? 
Alternatively, I need to keep the jobId the same.

**Comment by albertjan** [comment]
it might not be the best idea to use bull's `jobId `why not add an id to the data and add a new job to the queue with the same data?

You could do this easily enough using a redis client. Something like:

```js
var r = require('redis')
var c = redis.createClient();
c.srem("bull:" + queuename + ":completed", jobId, function (err) {
  c.lpush("bull:" + queuename + ":wait", jobId, function(err) {
    //done
  }
});
```

But it's not my advice to use it. :smile:

**Comment by SimoneTaliercio** [comment]
Thanks for your reply :)

I like the idea to have Bull as abstraction layer towards Redis.. so that "it is forbidden" to manipulate directly bull data in Redis.

Eventually I add a custom 'generationId' to my data and I'll swap it in order to give the 'illusion' that is the same job which has been 're-scheduled'.
