### ISSUE TITLE
Memory leak since v3.5.x (working fine with v3.4.8)

### ISSUE THREAD

**Issue by DavideViolante** [OptimalBits/bull#1194]
## Description
Hi, I wanted to report this issue that we discovered after a while because we thought it was on our side, but it was actually on the bull side. Since we upgraded to 3.5.2 (haven't tested 3.6.x yet) we noticed that the memory of the running Node process (we use Nove v10.15.0) was **just going up** and never going down.
For example these were the top processes showed with `ps aux --sort -rss` when the memory were particulary high (over **500MB** for manager.js, the file running the queues), just after some hours that the queues were processing jobs.

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
mycompany     31471  0.7  6.5 1381048 533564 ?      Ssl  Jan07  31:58 node /home/mycompany/jobber/manager.js
mycompany     32554  9.8  1.5 945340 130056 ?       Sl   Jan09 117:48 /usr/bin/node /home/mycompany/jobber/node_modules/bull/lib/process/master.js
mycompany     31796  0.0  1.5 939856 126548 ?       Sl   Jan07   3:43 /usr/bin/node /home/mycompany/jobber/node_modules/bull/lib/process/master.js
mycompany     13837  0.0  1.3 932804 112536 ?       Sl   Jan09   0:02 /usr/bin/node /home/mycompany/jobber/node_modules/bull/lib/process/master.js
mycompany     32497  0.0  1.2 952100 105112 ?       Sl   Jan09   0:15 /usr/bin/node /home/mycompany/jobber/node_modules/bull/lib/process/master.js
```

The solution we found is downgrading to v3.4.8 where we noticed that the memory leak is not present at all. No other changes were done. We have now running the process with the queues since several days and the memory is **totally stable** at around **88MB**.

I just wanted to tell you that **there is surely** some memory leak problem after v3.4.8 version (I think it's since v3.5.0 in particular, but not sure).

I currently cannot give a code to reproduce, but it should happen with any normal scenario (easier to reproduce with many jobs and many queues).

## Bull version
v3.5.x

**Comment by kartojal** [comment]
Related issue #1110

**Comment by gabegorelick** [comment]
Is this still an issue after v.3.7.0?

**Comment by swayam18** [comment]
We were still seeing a massive memory leak with v3.10. Only way to fix it was to downgrade back to 3.4.2

**Comment by gabegorelick** [comment]
> Only way to fix it was to downgrade back to 3.4.2

@swayam18 OP says that v3.4.8 is fine. So, you may be encountering a different issue.

**Comment by manast** [comment]
Keeping this open for a little while if somebody have more insights or reproducible code that we can look into.

**Comment by Mnigos** [comment]
I think this might be still relevant

**Comment by manast** [comment]
@Mnigos it may be relevant but there is currently no action to do here as there is no code that reproduces the issue...
