### ISSUE TITLE
[Feedback Request] Adding jobs from another language

### ISSUE THREAD

**Issue by Kage** [OptimalBits/bull#1196]
I have a use case where I need to produce jobs in PHP, but would strongly prefer to process those jobs in a different language that isn't [designed to die](https://software-gunslinger.tumblr.com/post/47131406821/php-is-meant-to-die).  The functionality provided by Bull is very favorable for my use case, so I [built a PHP library](https://github.com/HackThisSite/PHP-Bull-Scheduler) to handle scheduling Bull jobs.

Right now it's very barebone and doesn't do much beyond very basic job additions.  It uses the [addJob-6](https://github.com/HackThisSite/PHP-Bull-Scheduler/blob/master/src/RedisCommand/AddJob.php) Lua script direct from this project, but most of the functionality is in the [Queue.php](https://github.com/HackThisSite/PHP-Bull-Scheduler/blob/master/src/Queue.php) file.  I wrote it in such a way to mimic Bull's functionality as much as possible.  I haven't yet assembled any actual unit tests since I only just started cobbling this together, but it's tested to work successfully with Bull 3.6.

I know PHP is probably not a familiar tongue for you, but I wanted to ask if it's possible for you to review my PHP library and provide any feedback you might have.  In particular, I'm interested to know if you see anything important that's missing or done incorrectly, and any suggestions you might have.

Thanks for your help, and for building a truly awesome message/job queue!

**Comment by Kage** [comment]
Thanks @manast ! I have a few more questions if you don't mind.  It's a bit difficult to distinguish what parts of the queue definition matter for adding jobs and what only matter when processing.  Specifically, could you shed some light on how the following work solely within context of adding a job?
* Rate limits
* Repeatable jobs
* Backoff strategies

Is it important that these are defined when adding the job?  More specifically, is there anything special baked into the HMSET (i.e. in opts) or additional Redis keys needed?  Or are these only relevant for the workers?

**Comment by manast** [comment]
Rate limits and backoff are implemented solely on the workers. Repeatable jobs however require a special code for adding the jobs check this: https://github.com/OptimalBits/bull/blob/develop/lib/repeatable.js#L10

**Comment by Kage** [comment]
Hmm, yeah, I see what you mean.  That seems a bit complex to implement, and it's beyond my use case, so I'll skip that for now.  I guess I'll tidy it up from here and do test cases on what I currently have, and if anyone needs repeatable jobs maybe they can just submit a PR.

Thanks for all the help!
