### ISSUE TITLE
Question: can I have a consumer that can process from any named queue?

### ISSUE THREAD

**Issue by jacobpgn** [OptimalBits/bull#1197]
Hey there – many thanks for the library! 💙 

I have many distinct processors, e.g. `sendWelcomeEmail`, `processWebhook`, `refreshWidgets`, `eatChips`, and I'm trying to work out how to have just a couple of workers instead of a separate worker/consumer for each queue.

My reasons for wanting this are:
- "master" workers that wrap the processor in some default behaviour
    - e.g. log that a cron started -> initialise a Sentry context -> call processor -> log cron complete 
- fewer workers
    - if I have 100 processors but not many jobs per queue, I don't want 100+ blocking Redis connections. I could have 2 worker processes that are able to handle any job and call the right processor.

I _think_ it's possible to achieve this by putting every job in a single named queue, naming the jobs, and using those job names in the processor to determine which function to use. Unfortunately that feels a little bit janky because you lose the logical named queue grouping!

Is it currently possible to do something a little more like this?

```js
const sendWelcomeEmailQueue = new Queue("sendWelcomeEmail");
const processWebhookQueue = new Queue("processWebhook");

sendWelcomeEmailQueue.add(foo);
processWebhookQueue.add(bar);

const processors  = {
  sendWelcomeEmail: (job) => { /* */ },
  processWebhook: (job) => { /* */ },
} 

// A queue that can process on behalf of any named queue...
const consumerA = new Queue("*");
// ... and can process any named job!
consumerA.process("*", async (job) => { 
   // job.queue.name could be "sendWelcomeEmail" or "processWebhook"
   log("important log info");
   someContext(() => { 
    processors[job.queue.name](job);
  });
});
```

**Comment by manast** [comment]
Why can't you just define 1 queue and name the jobs instead?

**Comment by jacobpgn** [comment]
Hey @manast, thanks for getting back to me 😄 

A few things break when doing that, so I was wondering if there was a better way that I had missed.

 All the jobs will have the same keys up to the ID part and there will be a single set for the "master queue", so you lose the ability to do name-specific things like:
- "get all failed `sendEmail` jobs so I can review/retry them"
- "count waiting `processWebhook` jobs to see backlog"
- "stop working `startFire` jobs"
- "prioritise `saveKittens` jobs"

(or at least, these things get more complicated and very un-performant to do)

I was thinking it might make more sense to work a specific set of named queues, and iterate rpoplpush through them, but it looks like [Sidekiq found that painful](https://github.com/antirez/redis/issues/1785)

**Comment by manast** [comment]
I am still trying to understand the underlying issue you have, is it that you get performance problems or what is the main motivation here?

**Comment by jacobpgn** [comment]
Sorry @manast – I didn't see that you'd replied!

The main motivation is to avoid having an unreasonably large number of blocking Redis connections, but putting all the jobs in a single queue would lose some other functionality.

**Comment by manast** [comment]
I think blocking connections in redis are quire efficient, so it should not matter too much unless you are on amazingly large amounts (or if you are using a redis provider that limits the amount of connections)
