### ISSUE TITLE
Wait nested job to complete?

### ISSUE THREAD

**Issue by bdrtsk** [OptimalBits/bull#1201]
Is it possible to have a job inside the other job, and to wait until this nested job is complete and then proceed with parent?

Should I create separate queue for that? Then how do I pause() the queue from itself? And it says `A paused queue will not process new jobs until resumed, but current jobs being processed will continue until they are finalized.` so I can't pause parent job executing anyway?

**Comment by manast** [comment]
Duplicate: https://github.com/OptimalBits/bull/issues/340
