### ISSUE TITLE
pause queue globally

### ISSUE THREAD

**Issue by amitgilad3** [OptimalBits/bull#1208]
i read the docs and im not sure if i understand correctly but hopefully some one can assist me 

i have a scenario were a lot of messages are added to the queue and at some point i want to stop processing new messages until i finish with all the current ones running.

when i pause a queue globally im not sure what happens to the current jobs in the queue(the ones that are not in processing state) and what happens to new messages added to the queue(are the added or discarded)??

**Comment by manast** [comment]
When you pause globally it will stop getting new jobs from the wait queue, but the ones already been processed will continue until they are done. New jobs added to a paused queue will just keep waiting until the queue is resumed.
