### ISSUE TITLE
Stop long running jobs

### ISSUE THREAD

**Issue by nemax23** [OptimalBits/bull#1209]
I would like to have some help understanding if my requirements are achievable or not with Bull.
I have a series of jobs (say 100, using sanboxed workers) running on a queue once a day, using the repeat option. They start at morning and end in the evening. 
These jobs keep logging informations on a database and according to the collected data sometimes I must kill one of the job so that they stop executing their computation. I want to remove them from the delayed queue (and thats fine, I use _queue.removeRepeatable_) but I want as well the current node process to stop running. I tried to keep track of the spawned processes and their relative pid so that when I want to stop a job, after removing it from the queue, I kill its node process but this seems to cause some problems the next day when new jobs start (seems a problem of the child-pool used by _sandbox.js_).

Any help?

Thanks

**Comment by manast** [comment]
So if I understand you correctly, what you are asking is if the concurrence setting could be change in runtime, right?
