### ISSUE TITLE
Does Bull support distributed workers?

### ISSUE THREAD

**Issue by zebulonj** [OptimalBits/bull#1213]
Question:
Does Bull support deployment of distributed workers? To be clear, I see that Bull supports creation of separate processes for job processing, but can I spin up worker processes on multiple distinct servers, all pointed to the same Redis instance, and use a single connected manager (also using Bull) to distribute jobs to all those workers?

I tried it and the remote workers pick up the jobs, but their results are not returned to the manager. Put differently, the `queue.on('completed',...)` event fires on the worker when processing of a job is done, but the event does not fire on the remote manager.

Thanks! This looks like a great service and I'm hoping it fits my use case.

**Comment by manast** [comment]
you need to listen to global events for what you want to do, so just append ```global``` to the event name:
```js
  queue.on('global:completed', ...)
```

**Comment by zebulonj** [comment]
Many thanks.
