### ISSUE TITLE
Updating delay value in job already scheduled

### ISSUE THREAD

**Issue by flaviolivolsi** [OptimalBits/bull#1216]
Hi,

I would like to know whether it's possible to change the delay timestamp of a job already scheduled. F.x.: a job is scheduled to execute at 16:00 and I want to update it in order to be executed at 18:00. From the reference it doesn't look like it's possible, since the `update` method accepts only `data` as argument and not `opts`, but I would like to double check here and in case suggest it as a feature.

Thanks,
Flavio

**Comment by manast** [comment]
This is not possible at the moment. You would need to remove the job and add it again. As a new feature it would be needed a new lua script that updates the job in the delay set.

**Comment by flaviolivolsi** [comment]
@manast ok, fine! Thank you!
