### ISSUE TITLE
Repeatable jobs that do not finish before the next job is scheduled

### ISSUE THREAD

**Issue by imagolive** [OptimalBits/bull#1217]
Just trying to understand what happens in this case. 

Basically, there is a job scheduled to repeat every 60 seconds (uses { every: 60000 } as the repeat opts). It has a unique jobId and is only allowed to have one instance running at once.

 What does bull do if the job has not finished in the 60 seconds?  

It seems like it fires a new job even if the other is still running, but it wasn't clear from testing it.

Thought it best to ask the experts.

**Comment by manast** [comment]
It should not fire a new job if the current one has not yet completed, since the next job is only placed in the queue when the current one finalizes.
