### ISSUE TITLE
Redis goes OOM after a sharp dip in available memory

### ISSUE THREAD

**Issue by adeshrd** [OptimalBits/bull#1219]
![screenshot from 2019-02-16 23-14-44](https://user-images.githubusercontent.com/9036080/52908279-a9ff2800-3298-11e9-91e9-f1719fc2e9d3.png)
## Description

I am running 10 jobs with each job of size 3 mb. These jobs can get updated 10-15 times in a single second depending on the data of the job.

Initially everything works fine, but since my job takes 2 days to process; after a day of work there is suddenly a sharp dip in memory usage. The available memory goes down from 6gb to 0gb in a single minute and then redis gets rebooted in elasticache.

I have observed that this problem doesn't happen if I wait for job update using a then but if I do this then the amount of time to complete the job increase by at least 12 hours.
## Minimal, Working Test code to reproduce the issue.
I was able to reproduce this issue by inserting a 3mb job then updating it 50k times in a for loop.

## Bull version
3.0

### Additional details
EC2 instances used: 10 r5.2xlarge
Nodejs max memory: increased to 4 GB 
Redis: m5.large

**Comment by manast** [comment]
Any chance to test with a more recent version? 3.0 is really old by know and many issues have been resolved.

**Comment by adeshrd** [comment]
Hi,

I tested it again on redis 3.7.0 with 6 GB redis using a test code like this:

```
function updateJob() {
    return jobQueue.getJob(job.id).then(updatedJob => {
        jobRefObject.isCancelled = updatedJob.data.isCancelled;
        return job.update(jobRefObject);
    });
}
for (let i = 0; i < 10 * 1000; i++) {
    updateJob();
    Logger.info(`Iteration: ${i}`);
}

Logger.info("Finished");
done();
```
It showed the same behaviour.
Maybe redis is not able to handle the load and goes down ?

**Comment by manast** [comment]
If you can provide a full example that we can just copy/paste and reproduce the issue we will have much more chance to fix it.

**Comment by adeshrd** [comment]
Hi,

I was able to resolve this issue by reducing the number of updateJob() calls. Instead of calling it every time we are now calling it at fixed intervals. Redis seems stable now.

Thanks a lot for your help!
