### ISSUE TITLE
Move job to failed on "complete" job event callback

### ISSUE THREAD

**Issue by sor-barroso** [OptimalBits/bull#1220]
## Description

Hello Bull team!

I have a Bull implementation where several jobs have the same callback method ("completed" event).

During this callback I have common things to process between all of my jobs and some of the steps can represent a "fail state" for me but Bull always assume these jobs as completed ones.

I've tried the `moveToCompleted` method that hasn't work and I found out that it's not the correct way to use it.

Can anyone help me with this issue?

## Example
``` typescript

      var q = new Queue("queue_name", { redis: bullRedisConfiguration });

      q.on('completed', this.handleJobCallback);

      private handleJobCallback = async (job: any, answer: any) =>  {

          try{
              // process stuff
          }catch(error : any){
              // set the job as failed
          }
      }
```

**Comment by manast** [comment]
not sure I follow what you are trying to do. The ```completed``` event is fired after the job has been completed and moved to the completed set. What else do you want to do after that with the said job?

**Comment by sor-barroso** [comment]
Hello @manast. I have a "queue" table in a database where I keep a kind of process status track. I execute an update for every job during `completed` event, but this update can fail somehow and I would like to set the job as `failed` instead of `completed`.

Should I do an approach like that or It looks like a bad implementation?

**Comment by manast** [comment]
It is more reliable to update the database in the ```process```  function itself, in that case the job will fail and it can be retried or maybe in that case only listen to the ```failed``` event.

**Comment by sor-barroso** [comment]
Thanks @manast, I'll do that.
