### ISSUE TITLE
Job.getState() and resolve

### ISSUE THREAD

**Issue by joshhopkins** [OptimalBits/bull#1221]
Is it possible to call Queue.getJob(), then Job.getState() and resolve with disrupting the queue? Seems like Queue.close closes the queue altogether.

**Comment by manast** [comment]
So you should be able to call ```getState``` after ```Queue.getJob```  but what do you ask about closing the queue?

**Comment by joshhopkins** [comment]
I'm simply binding job state to a model. If I don't call Queue.close, the process remains running. Though this closes the underlying Redis client, which kills running jobs. Is there a way to drop the connection to a queue after getting job state that doesn't close it?

**Comment by manast** [comment]
Maybe you can create a new Queue instance just for getting the job state, in that way you will not disrupt the main instance that is processing the jobs?

**Comment by joshhopkins** [comment]
Oh, I assumed Queue.getJob was exclusive to the queueName define in the Queue instance. That should work!

**Comment by joshhopkins** [comment]
Ok. So `Queue.close` closes the connection for that Queue instance only, not all instances of that `queueName`. So I can call this without interfering with jobs running on other processes, right?

**Comment by manast** [comment]
exactly.

**Comment by joshhopkins** [comment]
Great. I misunderstood the docs. Thank you!
