### ISSUE TITLE
Can't get simple setup to work

### ISSUE THREAD

**Issue by Twisterking** [OptimalBits/bull#1225]
Very new to `bull` - can't get it to work!

**MAIN Server**, adding stuff to a queue:
```js
const pricatQueue = new Bull('queue-pricats', {
  redis: {
    port: '6379',
    host: '127.0.0.1',
    // password: ''
  }
});

pricatQueue.on('waiting', (jobId) => { // called instantly after the `addToPricatQueue` is called by the client (below)
  console.log(jobId, 'is WAITING');
});

pricatQueue.on('active', (job, jobPromise) => { // NEVER CALLED! :(
  console.log(job, 'is ACTIVE');
});

pricatQueue.on('completed', (job, result) => {
  console.log(job.id, `Job completed with result ${result}`); // NEVER CALLED! :(
});

Meteor.methods({
  async addToPricatQueue(params) { // called by the client/UI
    console.log('addToQueue()', params);
    try {
      const job = await pricatQueue.add(params);
      return 'job is queued!';
    } catch(err) {
      throw err;
    }
  }
});
```
**WORKER**:
```js
const pricatQueue = new Bull('queue-pricats', {
  redis: {
    port: '6379',
    host: '127.0.0.1',
    // password: ''
  }
});

pricatQueue.process(async (job, done) => {
  console.log('WORKER: processing ...', job.data);
  // do some stuff later here
  console.log('finishing ...');
  // ...
  done({ success: true });
});
```

I am really trying my best right here, I don't see what I am doing wrong.
Can anyone help?

**Comment by manast** [comment]
So what is not working?
If you expect events like ```completed```, etc to work from a different process than the one processing the jobs you need to prefix with ```global:```, like: 
```
pricatQueue.on('global:completed', (job, result) => {
  console.log(job.id, `Job completed with result ${result}`); // NEVER CALLED! :(
});```

**Comment by Twisterking** [comment]
Okay, so just by prefixing my event listener on my `main` server with `global:` I can listen to any jobs being completed on my `worker` server - correct?!
I will try this tomorrow when I am back at the office. I tried it today though like shown [here](https://optimalbits.github.io/bull/) so I had `global: completed` instead of `global:completed` - does this make a difference?
It didn't work though. 😢 
Obviously I am looking for a way to listen to completed jobs and their `results` on my `main` server, which triggered the job, so I can show the result to the user. The job itself is handled by the `worker` server. This is possible correct?!

**Comment by mattcollier** [comment]
I'm seeing that with `pricatQueue.process(async (job, done) => {` you're conflating the promise and callback APIs.  Just drop the `done` as the second param and you should be good to go.

**Comment by Twisterking** [comment]
I tried all the variations out there:

```
js
pricatQueue.process(async (job, done) => {
pricatQueue.process(async (job) => {
pricatQueue.process((job, done) => {
```

None of them worked like they should - the way I think they should at least.

**Comment by Twisterking** [comment]
Okay, got it to work!

Seems like that the one documentation I found was deprecated/wrong, as it works now with `global:completed` instead of `global: completed`.

Also, I ended up using the following `.process()` syntax: `pricatQueue.process(async (job) => { })`.
