### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by wwillsey** [OptimalBits/bull#1228]
getting Error:  TypeError: Converting circular structure to JSON  when marking a job as completed (successful resolve of processing function) but the resolved value of the process function is a request object (circular).

I have removeOnComplete true, so It doesn't need to store the result value in redis, but it fails when trying to moveToFinished trying to JSON.parse the result.

at JSON.stringify (<anonymous>)
at Object.tryCatch (/usr/src/app/node_modules/bull/lib/utils.js:5:15)
at Job.moveToCompleted (/usr/src/app/node_modules/bull/lib/job.js:188:23)
at handleCompleted (/usr/src/app/node_modules/bull/lib/queue.js:1034:16)

This means bull cannot handle any processing job that resolves to circular json?

**Comment by manast** [comment]
you can only resolve with objects that are JSON stringifiable because they will be stored as a string in Redis.

**Comment by wwillsey** [comment]
are the results still stored when removeOnComplete and removeOnFailed are set to true?

**Comment by phrozen** [comment]
Is there a workaround about this? I'm trying to send a Hapi server request to the job, and apparently it cannot be JSON.strigify 'ed

**Comment by hayanisaid** [comment]
I have this issue also, but this only happens on Linux OS, on Mac works fine!
