### ISSUE TITLE
Request: Queue#Add option to reject if jobID already exists

### ISSUE THREAD

**Issue by MicahMartin** [OptimalBits/bull#1229]
It'd be nice if the promise returned by Queue.add() would reject if the job wasn't actually added to the queue

**Comment by manast** [comment]
that is going to be a breaking change difficult to do at this time. However it seems a legitimate use case to know if a given job as been ignored or not after being add if its JobId already exists. Would an event work for you in this case?

**Comment by mattcollier** [comment]
Seems to me that some flag on the `job` returned from `Queue.add` would suffice?  Throwing here seems a bit severe since the desired behavior is the same as for an ES6 Set.

**Comment by MicahMartin** [comment]
gonna take the suggestion from @manast - https://github.com/OptimalBits/bull/pull/1230
