### ISSUE TITLE
Does getting Queue in another process reset the Queue options?

### ISSUE THREAD

**Issue by ashkank83** [OptimalBits/bull#1232]
I set up my main Queues in the main Thread like below:
```js
let QueueJobGenerator = new Queue('generator', redisURL,{repeat:{every:3000}});
QueueJobGenerator.process('path\to\JobGenerator.js');
let QueueProcessor = new Queue('processor',redisURL);
QueueProcessor.process(10,'path\to\processor.js') //+ want to run 10 parallel jobs 
```

and below is the file which generates the jobs (in a sandbox, so it doesn't have access to any of the queues)

```js
//jobGenerator.js
let processQueue = new Queue('processor'); //*
processQueue.add({test: test});    
processQueue.close();
```

Question 1: Does JobGenerator.js create a new instance of the Queue called 'processor' every time (line marked with *)? If yes is there any better way to retrieve/get this queue rather than instantiating it? I think this becomes especially important in distributed designs. 

Question(issue) 2: It looks like the instantiation in jobGenerator.js (line *) is removing the parallel count set initially (in line +). Is this a known/desired behaviour? or am I doing something wrong?

**Comment by manast** [comment]
How does the whole jobGenerator.js file look like?
You are supose to export the processor function like this:
```
module.exports = function(job){
  // Do some heavy work

  return Promise.resolve(result);
}
```

so if you instantiate the queue (```new Queue()```) outside of the exported processor it will only be instantiated once per process (10 in your example).

**Comment by ashkank83** [comment]
Sorry! I didn't want to over complicate the comment by putting my whole code but looks like I oversimplified it! Below is the complete job Generator:
```js
//jobGenerator.js
"use strict";
import glob from "glob";
import Queue from "bull";

module.exports = async function(job) {
  glob(`${job.data.filePattern}`, { cwd: job.data.folder }, (er, matches) => {
    if (er) {      
      return Promise.reject(er);
    }

    let processQueue = new Queue('processor');
    matches.forEach(match => {
      //jobId will guarantee that we can't load the same file again
      processQueue.add(
        {
          fileName: job.data.folder + match
        },
        {
          jobId: match
        }
      );
    });
    processQueue.close();
  });
  job.progress(100);
  return Promise.resolve();
};
```

The issue is that when the above code runs it seems to be overriding the concurrency of "processQueue", which I have previously (in the main module) set to 10.

**Comment by manast** [comment]
but why don't you call this ```let processQueue = new Queue('processor');``` outside of the processor function? 
Please check my revised code, I do not think the code you provided works properly.

```
//jobGenerator.js
"use strict";
import glob from "glob";
import Queue from "bull";

const processQueue = new Queue("processor");

module.exports = function(job) {
  return new Promise((resolve, reject) => {
    glob(`${job.data.filePattern}`, { cwd: job.data.folder }, (er, matches) => {
      if (er) {
        reject(er);
      } else {
        const added = [];
        matches.forEach(match => {
          //jobId will guarantee that we can't load the same file again
          added.push(
            processQueue.add(
              {
                fileName: job.data.folder + match
              },
              {
                jobId: match
              }
            )
          );
        });
        resolve(Promise.all(added));
      }
    });
  });
};

```

**Comment by ashkank83** [comment]
Unfortunately, I'm getting the exact same result. It seems to be ignoring the concurrency setting.
