### ISSUE TITLE
Question about moveToCompleted, maybe a race condition/bug?

### ISSUE THREAD

**Issue by akirilyuk** [OptimalBits/bull#1233]
Hi,

is it possible to not pull a job from waiting to active if calling moveToCompleted(). Or can I mark it as completed on a different way.

We are using Bull for continuous jobs, with separate api and processing layer. My problem is, that when I mark a job as completed from the api, is also sets the next job in the waiting queue to active, but I don't want that, since the api cannot process anything. So the job is in active state, but is not being processed at all.

Also when I have created a Job with removeOnComplete = true, and the job is in the waiting queue, if I move it to completed, the job will be in the active queue instead of the completed. Is this expected?

The following code demonstrates this behaviour:

```
  const Queue = require('bull');
  const queue = new Queue('testqueue', 'redis://localhost:6379');
  const job = await queue.add({ data: 'test' }, { removeOnComplete: true });
  console.log(JSON.stringify(await queue.getJobCounts()));
  await job.moveToCompleted('stopped', true);
  console.log(JSON.stringify(await queue.getJobCounts()));
```

Yields:

`
{"waiting":1,"active":0,"completed":0,"failed":0,"delayed":0,"paused":0}
{"waiting":0,"active":1,"completed":0,"failed":0,"delayed":0,"paused":0}
`

**Comment by akirilyuk** [comment]
I see other questions get answered and mine not, actually I think this is a bug or a race condition and not a question.

**Comment by akirilyuk** [comment]
@manast Thanks! I see that the PR was opened, but the guy never fixed the tests + documentation :(

**Comment by rjcortese** [comment]
Hi! Is there a good alternative / workaround that works with the current version?
