### ISSUE TITLE
Delay for exponential back off calculated wrong

### ISSUE THREAD

**Issue by matthiasfeist** [OptimalBits/bull#1234]
## Description

I currently have a job in production that has the following configuration (read from the production cluster via Arena):
```

"opts": {
"delay": 311040000000000,
"attempts": 11,
"backoff": {
"type": "exponential",
"delay": 120000
},
"timeout": 120000,
"removeOnComplete": true,
"removeOnFail": true,
"timestamp": 1543845804940
}

```
As you can see, the delay is waaaaaay off the charts and therefore my jobs are not executed as they should. I have actually no idea how this can happen. 

## Bull version
3.3.8 (it's pretty old, I know)

## Additional information
We're running Node 10

**Comment by manast** [comment]
any chance to get a minimal test that reproduces the issue?

**Comment by matthiasfeist** [comment]
Not really, because I can't reproduce the bug... I just see the jobs in production are being scheduled wrongly.
Which is weird because the above configuration should give only a delay of 245760000, right?
Because the formula for calculating the exponential delay is `Math.pow(2, 11) * 120000`

**Comment by villasv** [comment]
FYI future readers the actual formula is `Math.round((Math.pow(2, attemptsMade) - 1) * delay);` as shown [here](https://github.com/OptimalBits/bull/blob/master/lib/backoffs.js#L14).

**Comment by YuliyaNovik** [comment]
FYI future readers the formula used in _bull_ differs from one used in _bullmq_

For _bull_ `Math.round((Math.pow(2, attemptsMade) - 1) * delay)`  [reference](https://github.com/OptimalBits/bull/blob/088e5dfcbe9b5c347c2c8f5d9fca5c53c099bbe3/lib/backoffs.js#L14)
for _bullmq_  `Math.round(Math.pow(2, attemptsMade - 1) * delay);` [reference](https://github.com/taskforcesh/bullmq/blob/master/src/classes/backoffs.ts#L18) or [in docs](https://docs.bullmq.io/guide/retrying-failing-jobs)
