### ISSUE TITLE
Prioritise workers

### ISSUE THREAD

**Issue by joshhopkins** [OptimalBits/bull#1236]
Is there a way of prioritising workers: for example, if a bunch of workers on server-1 are killed (jobs fail), fall back on server-2? I'm guessing a seperate queue would be the best way?

**Comment by manast** [comment]
Not sure what you mean with prioritise. If you have several "servers" processing jobs, if one fails the others will continue working as normal.

**Comment by joshhopkins** [comment]
Right, but in this case server-2 should only act as a fallback. Want to avoid server-2 pulling jobs off the queue unless server-1 cannot process them.

**Comment by manast** [comment]
You can implement this by yourself but bull does not have anything like this.

**Comment by nitzanav** [comment]
@joshhopkins 
you can do something similar to DLQ(dead letter queue), for example use different queues, once the code fails in one queue (e.g. queue named "server-1") add a similar job to another queue named for example "server-2".

**Comment by joshhopkins** [comment]
Thanks @nitzanav, this is what I ended up doing 👍
