### ISSUE TITLE
Question: parallel processing of jobs of different type while same type is processed sequentially

### ISSUE THREAD

**Issue by consense** [OptimalBits/bull#1237]
Hi,

hope it is ok to post such a question here:
I have jobs being managed via bull.
Jobs relate to a specific customer. So `job_customerA_payload1`, `job_customerA_payload2`, `job_customerB_payload1` ...

Requirements:

* Jobs relating to the same customer must be processed sequential, but there can be multiple jobs in parallel each for a different customer.
* the setup must allow for multiple worker machines (processors) to run in parallel for scalability i.e. to support many different customers having their data processed in parallel (but as written above sequentially for each customer).

Currently I am handling this in the following way:

* jobs are added to `queueSortJobs` which processes all incoming jobs and re-enqueues them to customer specific queues e.g. `queue_customerA`.
* the worker server sets up processors on the customer specific queues which are initialized with concurrency of 1( `queue_customerA.process('*', 1, processorFunction)`).

This works as supposed to, but will not scale to more than 1 worker machines, as the worker servers are not aware of other worker servers and will each setup a processor on `queue_customerA` leading to multiple jobs of the same customer being processed in parallel (which shouldn't happen).

So currently I am solving this with a custom redis-lock being managed inside the queue_customerX-processors to avoid parallel processing for the same customer, but this seems ugly and I get the strong feeling I am missing something fundamental here,

So questions:

* is above requirement possible with bull-queue?
* am I maybe overlooking something and the custom redis-lock inside application-land is not necessary?

Thanks a bunch!

**Comment by manast** [comment]
It is ok to ask questions here, although I would love to have a bullmq topic in stackoverflow but lack points to create one :).
So, what you are proposing is not supported by Bull, but in general it seems like quite a complex problem to solve. Probably a distributed lock as you propose is one of the simplest approaches, but it also implies that you need a polling mechanism where the workers need to check if the lock has expired or not.

**Comment by consense** [comment]
Thanks a bunch
