### ISSUE TITLE
[Question] Is it possible to set specific run date/time?

### ISSUE THREAD

**Issue by josec89** [OptimalBits/bull#1244]
I'm wondering if it's possible to set a specific date/time for a job. I would like to schedule a job so it's processed at a specific date like:

```ts
imageQueue.add({image: 'http://example.com/image1.tiff'}, new Date(2018, 11, 10, 10, 20));
```

**Comment by manast** [comment]
this has been answered before, just calculate a delay in milliseconds from the moment you add the job to the moment you want it to be processed and add it as a delay job.
