### ISSUE TITLE
async process functions fail silently on error and stall

### ISSUE THREAD

**Issue by codebykenny** [OptimalBits/bull#1245]
## Description
If a queue.process function is an `async` function, errors are not logged and jobs then stall out.

## Minimal, Working Test code to reproduce the issue.

Lets say we do not import the `moment` module

## Working Version
```
queue.add('test', { test: 123});

queue.process('test', (job, done) => {
    moment();
});

Queue failed ReferenceError: moment is not defined
    at Queue.process (/Users/kenneth/...)
    at bound  (internal/util.js:235:26)
    at Queue.processJob (/Users/kenneth/.../node_modules/bull/lib/queue.js:1057:22)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)


```

## NOT Working async Version 

```
queue.add('test', { ok: 123});

queue.process('test', async (job, done) => {
    moment();
});

// fails, and no output or feedback is returned... restarting application advises us of a stalled job
```

In this example there is no reason for this function to be `async` however in real process functions we do need `async` and they all fail silently for some reason

## Bull version

3.7.0

## Additional Info - Temporary workaround

If the `done` callback is missing, and we use `Promise.resolve()` & `Promise.reject()`, errors fail as expected.

```
queue.add('test', { ok: 123 });

queue.process('test', async (job) => {
    moment();
});

// Fails correctly
Queue failed ReferenceError: moment is not defined
    at Queue.process (/Users/kenneth/...)
    at bound  (internal/util.js:235:26)
    at Queue.processJob (/Users/kenneth/.../node_modules/bull/lib/queue.js:1057:22)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

```

**Comment by sarneeh** [comment]
@codebykenny It works as intended. `process('name', async (job, done) => {})` doesn't work, it's in the [docs](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueprocess):

> In order to determine whether job completion is signaled by returning a promise or calling the done callback, Bull looks at the length property of the callback you pass to it. So watch out, as the following won't work:
