### ISSUE TITLE
update job when it fails

### ISSUE THREAD

**Issue by Gappa88** [OptimalBits/bull#1246]
I'm using Bull 3.4.8.

when I process a job I make some operations on data that the job is bringing with him. 
If any operations fail I need to retry that job (I have a custom backoff for that) but I need to remember what operations I already have done on it in order to skip them the next time I process that very same job.

Is there any way to update a job when I make it fail or I have to update it with `job.update`?

code example:

```
queue.process(1, async (job, done) => {

    if(!job.data.hasOwnProperty('operation_one_already_processed')){

                 ...... do operation one .......
                 job.data.operation_one_already_processed = true;
    }

  return done(ERROR);
});
```

**Comment by manast** [comment]
What about dividing the job in several queues, so that every "atomic" operation is performed in one independent processor?

**Comment by Gappa88** [comment]
thanks @manast , I will keep your solution into account for other problems, I like it. 
Unfortunately this solution is not feasible for this specific situation. 
Currently, I don't have problems using `job.update` but I was curious about other possibilities to solve this.
