### ISSUE TITLE
Question: Running from cron

### ISSUE THREAD

**Issue by interpegasus** [OptimalBits/bull#1250]
## Description

Hi, Thank you for sharing the code and creating this great library. 

I would like to know how to run code in my function 'myCustomMethod' via the Queue/Bull . Is this the right way to do it?

**./models/Sport.js**

```
export async function myCustomMethod(type, req)
{
    console.log("This method should be executed via the Queue / Bull");
    let computationResult = true;
    return computationResult;
}
```

**cronCustomFile.js**

```
import { myCustomMethod } from './models/Sport.js';

cron.schedule('*/5 * * * * *', () =>
{
    var battleRoyaleQueue = new Queue('battle_royale_queue');
    console.log('Checking live events every 5 seconds');
    battleRoyaleQueue.process(function (job, done)
    {
        try
        {
            console.log('Processing via battle_royale_queue');
            myCustomMethod('live-events');
            done();
        }
        catch (err)
        {
            console.log(err.message);
        }
    });
    return true;
});

```
## Bull version
`"bull": "^3.6.0"`

## Additional information
It looks like jobs are not being added to the queue or processed. 

<img width="1082" alt="Screen Shot 2019-03-18 at 9 23 27 PM" src="https://user-images.githubusercontent.com/934795/54575920-21bd9100-49c4-11e9-88ca-c11fc9410f2c.png">

**Console**
<img width="1100" alt="Screen Shot 2019-03-18 at 9 31 08 PM" src="https://user-images.githubusercontent.com/934795/54576210-351d2c00-49c5-11e9-90b2-fda67e50b0e9.png">

**Comment by juanantoniodamianv** [comment]
Apparently, you create the process (battleRoyaleQueue) but you never call it.

You can try a repeatable parameter:

```
import { myCustomMethod } from './models/Sport.js';

battleRoyaleQueue.process(function (job, done) {
  try{
    console.log('Processing via battle_royale_queue');
    myCustomMethod('live-events');
    done();
  } catch (err) {
    console.log(err.message);
  }
});

battleRoyaleQueue.add({
  repeat: {
    cron: '*/5 * * * * *'
  }
})
```

**Comment by interpegasus** [comment]
Thank you! The issue has been solved
