### ISSUE TITLE
TypeScript processor support is broken since release 3.5.3

### ISSUE THREAD

**Issue by ianp** [OptimalBits/bull#1251]
## Description

Using a handler with no file extension doesn't work anymore.

## Bull version

3.5.3 –3.7.0

## Additional information

I'll skip to the chase, line 669 in lib/queue.js has a bug in it

```js
(supportedFileTypes.indexOf(path.extname(handler)) !== '-1' ? '' : '.js');
```

is using a strictly typed comparison against the string `'-1'` but `indexOf` returns a number. You need to either change `'-1'` to `-1` or use `!=` instead of `!==`, i.e.

```js
(supportedFileTypes.indexOf(path.extname(handler)) !== -1 ? '' : '.js');
```

**Comment by olivierto** [comment]
+1 nice catch ! 
having the same problem with Ts processors.

**Comment by insanehong** [comment]
I have the same problem!

**Comment by manast** [comment]
Please report type definition errors to the DefinititelyTyped repo https://github.com/DefinitelyTyped/DefinitelyTyped
