### ISSUE TITLE
Can't terminate (child) process from a "reloaded" existing queue

### ISSUE THREAD

**Issue by xavier-rodet** [OptimalBits/bull#1253]
## Description
Closing a queue from a "reloaded" existing queue doesn't terminate child process

## Test code (TypeScript)
```typescript
// test.ts
var Queue = require('bull');


async function test() {

    // Request type-A (add jobs)
    var queue = new Queue('queue-user1', {
        redis:{
            port: 6379,
            host: 'localhost',
        },
    });

    queue.process(__dirname + '/process.js');
    queue.add(1);
    queue.add(2);


    // Request Type-B (stop queue / workers)
    console.log('Wait jobs to be done'); // In real world i do it properly :-)
    await new Promise(resolve => setTimeout(resolve, 5000));

    // BUG HERE : I "reload" an existing queue, which make queue.close not working properly
    var queue = new Queue('queue-user1', {
        redis:{
            port: 6379,
            host: 'localhost',
        },
    });
    await queue.close(); // Child process will never terminate

    console.log('Test ended');
}


test();
```

```node
// process.js
module.exports = function(job){
    // Do some heavy work

    console.log(`processing job ${job.id} with data ${job.data}`);

    return Promise.resolve(true);
}
```

_**Note:**_ _this a simple test code to simulate my issue, in real world thoses requests are called separately from client requests over my http server._

## Bull version
3.7.0

## Additional information
In my case scenario, I am : 
- using a queue per user
- users are sending N requests of type A (which add jobs to the user queue)
- users are sending 1 request of type B (which wait for all jobs to be done, and then stop the user queue)

But it looks like my child process never stop running in background.

**Comment by manast** [comment]
thanks for the report, I will look into it as soon as possible,
