### ISSUE TITLE
Running a repeatable job in docker doesnt execute the job

### ISSUE THREAD

**Issue by gsasouza** [OptimalBits/bull#1254]
## Description
Hi, I'im trying to run a repeatable job using cron, it works locally, using only nodejs, but when I use a docker container, it doesn't run this same job.

```
const queue = new Queue('Q1', {
  redis: process.env.REDIS_HOST,
}),
queue.add(payload, { repeat: { cron: '0 1 * * *' } })
```

## Bull version
`"bull": "^3.5.2",`

**Comment by manast** [comment]
so there must be something that is not correctly configured in your container. I do not think this is an issue with bull. Re-open if you can provide code that reproduces the issue.
