### ISSUE TITLE
`global:waiting` not fired for jobs dispatched with `delay`

### ISSUE THREAD

**Issue by tvedtorama** [OptimalBits/bull#1257]
## Description
I added the `delay` option to the job dispatching options, ie `add`.  The global event for `waiting` is not triggered for this job.   It removed it again and the event is triggered.

The events are observed in a different process.

## Minimal, Working Test code to reproduce the issue.

Add the delay option to add and see if the global:waiting event is triggered in another process.

## Bull version

^3.4.2

## Additional information

I checked the documentation and could not find another event that would better describe what I was trying to do.  Perhaps an `added` event would be more correct, since ,technically, the event is not waiting.

**Comment by manast** [comment]
fixed in 3.4.8: https://github.com/OptimalBits/bull/blob/develop/CHANGELOG.md
