### ISSUE TITLE
Make the Job library plug-able or extensible.

### ISSUE THREAD

**Issue by coldlamper** [OptimalBits/bull#126]
I have a specific need to override the Job.create and Job.fromId functions. Would it be possible to add support to do this?

**Comment by manast** [comment]
Can you provide an example of what you want/need to do?

**Comment by coldlamper** [comment]
Basically I want to use the Job.create as usual but then also add a sorted set in relation to job hash.
The hash will also contain priority.timestamp field. When Job.fromId is called it would use the redis sort command to get the highest priority.timestamp.  I know you have a priority queue but I think this would be more accurate and have more flexibility and guarantee the order.

**Comment by manast** [comment]
will close due to lack of traction.
