### ISSUE TITLE
ERR unknown command ' client '

### ISSUE THREAD

**Issue by minzojian** [OptimalBits/bull#1262]
## Description  
node_modules\bull\lib\worker.js; line 17  
![image](https://user-images.githubusercontent.com/361781/55461394-e9a28900-5626-11e9-9f76-db208d4b23ac.png)

an error thrown out while check redis is ready  
actual error message is **ERR unknown command \' client \'**   
but the condition is   
`if (err.message !== 'ERR unknown command \'client\'') throw err;`  
notice in the actual error message, there are spaces around the "client", so err has been throw out.  
 
as i  run my app in docker containner, when this error throw out, app just restart. that's  too bad.  
is that a redis bug or something?

**Comment by manast** [comment]
your redis server does not support that command, if you check the issues you will find workarounds.

**Comment by minzojian** [comment]
yes，setname command is not supported in my cloud server，is there a way to skip the setname command in worker.js

**Comment by minzojian** [comment]
created a pull request, for adding a plus condition for my strange situation
https://github.com/OptimalBits/bull/pull/1263

**Comment by minzojian** [comment]
created a pull request, for adding a plus condition for my strange situation
https://github.com/OptimalBits/bull/pull/1263

**Comment by minzojian** [comment]
created a pull request, for adding a plus condition for my strange situation
https://github.com/OptimalBits/bull/pull/1263
