### ISSUE TITLE
Why jobs are being processed at the same time?

### ISSUE THREAD

**Issue by qazidop** [OptimalBits/bull#1272]
## Description

Just came across a situation where I found that multiple jobs are being processed almost at the same time. The scenario is that, there are a bunch of user who are being added in the queue and each of them can potentially create a group if they meet certain criterion or otherwise will be added to one of the already created group. So, each of them could be in each other group if they match with each other (matching also have some criterion that is already there) but they cannot be in multiple groups at the same time. In addition, the code is based on `Promises` and all the database read and write operations are being performed with in the `Promise` functions.  
Whats happening is that, there are very few users who are ending up in multiple groups. Upon investigating I found the `Created Date` of those groups and it seems like they are being processed simultaneously otherwise the process which I have defined checks the user while matching if it belongs to any group or not. The groups have created date  `1554439383277` ,  `1554439383743` respectively (Human-Readable for both: Fri Apr 05 2019 15:43:03).
This leads me to couple of questions. First, why the operation is not linear? As, I've always assumed that `queue` will make sure on its own that the second job (user) will go into process only after the first one emits completion or failure. Furthermore, I haven't specified any concurrency, which means that it should have concurrency of `1` (from docs and from this [Ques](https://github.com/OptimalBits/bull/issues/133)). Second, when I used `limiter { { max: 1, duration: 1000 } }` in my queue everything seems to work in perfect order but my question is this that, is this the only way to solve this problem? How can we ensure that our queue is processing only one job at a time?

**Comment by manast** [comment]
It will only process one job at a time if you have concurrency 1 and only one worker. So the issue may be somewhere else. Just make sure that the promise that you return in the process function only resolves when you are done with all the work that is supposed to be done for that job.

**Comment by qazidop** [comment]
Hi @manast thanks for your answer. You are absolutely correct and this is what I understand from your documentation as well. However, I have checked all the promises throughly and console logs just to find whats actually going on and this is what I found. Could you please advise me on, why before the end of first job the second job is already in process. 
```
**Job In process:  9d482e38-2d6c-4ef2-9fdf-873671ad34ab**
A uid:  9d482e38-2d6c-4ef2-9fdf-873671ad34ab
B uid:  9d482e38-2d6c-4ef2-9fdf-873671ad34ab
C-ensure-end-possibile uid:  9d482e38-2d6c-4ef2-9fdf-873671ad34ab
D uid-allNonEng :  9d482e38-2d6c-4ef2-9fdf-873671ad34ab
E uid-actualUpdate :  9d482e38-2d6c-4ef2-9fdf-873671ad34ab
G uid-New-group :  9d482e38-2d6c-4ef2-9fdf-873671ad34ab
Job In process:  504b6f18-0ee8-4f93-9f94-2695830fec80
A uid:  504b6f18-0ee8-4f93-9f94-2695830fec80
B uid:  504b6f18-0ee8-4f93-9f94-2695830fec80
C-ensure-end-possibile uid:  504b6f18-0ee8-4f93-9f94-2695830fec80
D uid-allNonEng :  504b6f18-0ee8-4f93-9f94-2695830fec80
E uid-actualUpdate :  504b6f18-0ee8-4f93-9f94-2695830fec80
G uid-New-group :  504b6f18-0ee8-4f93-9f94-2695830fec80
F1 or G1 uid-EndPossibile:  a86a0446-7f76-4ed5-a857-736f6d98f142
F1 or G1 uid-EndPossibile:  d3a4f620-fe7d-43a2-b517-bf973cda9632
Job:  504b6f18-0ee8-4f93-9f94-2695830fec80  done:  true
Job In process:  a1d85313-8cd0-49c4-9117-b5828ea9dccf
A uid:  a1d85313-8cd0-49c4-9117-b5828ea9dccf
B uid:  a1d85313-8cd0-49c4-9117-b5828ea9dccf
C-ensure-end-possibile uid:  a1d85313-8cd0-49c4-9117-b5828ea9dccf
D uid-allNonEng :  a1d85313-8cd0-49c4-9117-b5828ea9dccf
E uid-actualUpdate :  a1d85313-8cd0-49c4-9117-b5828ea9dccf
G uid-New-group :  a1d85313-8cd0-49c4-9117-b5828ea9dccf
Job In process:  6c117622-8a00-4824-a22a-359df464c11b
A uid:  6c117622-8a00-4824-a22a-359df464c11b
B uid:  6c117622-8a00-4824-a22a-359df464c11b
C-ensure-end-possibile uid:  6c117622-8a00-4824-a22a-359df464c11b
**Job:  9d482e38-2d6c-4ef2-9fdf-873671ad34ab  done:  true** ```
Thanks
