### ISSUE TITLE
Feature request: Queue#status?

### ISSUE THREAD

**Issue by ashkank83** [OptimalBits/bull#1274]
## Description

As discussed on the gitter channel, it would be great to add a new function to queue which returns the status of the queue. i.e. is it "Paused", "Closed", ...

If the generic queue#status is not possible then maybe queue#isPaused which returns a boolean.

**Comment by manast** [comment]
ok, we can report paused, but closed is not a queue status, rather a status of your particular instance of the queue.

**Comment by kand617** [comment]
This feature is really useful. I would like to now if queue is active/paused globally.
