### ISSUE TITLE
Bug: removeRepeatableByKey doesn't remove all associated jobs with repeat

### ISSUE THREAD

**Issue by jithu21** [OptimalBits/bull#1277]
## Description
removeRepeatableByKey function only removes repeat job ie ("bull:queue:repeat"), but It doesn't remove the scheduled jobs created by the repeat job. like "bull:queue: repeat: 94ba15ead7dd228416797b8e6fa59eb0:1554980890000"
## Bull version
 3.7.0

**Comment by manast** [comment]
This works as designed.

**Comment by fd-rey** [comment]
Hello @jithu21 I was in the same situation. What I did to delete the job was bringing all delayed jobs, find the one with the jobId I'd used to create the repeatable job and finally call the remove() method in the found job.
Example:
```javascript
let jobs = await queue.getJobs(['delayed']);
let jobToDelete = jobs.find((delayedJob)=>delayedJob.opts.repeat.jobId=='myJobId');
if(jobToDelete){
   await jobToDelete.remove()
}
```
Note that the jobId has to be set in the opts when adding the repeteable job in the queue, the jobs created by this repeatable job will have this "custom" id in: opts.repeat.jobId

**Comment by sasha-borodin** [comment]
The solution proposed by fd-rey relies on an internal implementation detail, which can change at any time.  It would be great if the "removeRepeatable" or "removeRepeatableByKey" Queue methods were able to (optionally via flag) also remove any delayed "next job" for that repeatable job.

The use case for this seems pretty common - updating a repeatable job with a new "repeat" definition.  This understandably involves removing and adding the job.  But I would argue that intuitively, most developers would expect the next delayed job to get removed as well.

@manast  - is this a feature you are willing to consider?  If not, are you open to considering a pull request?

**Comment by stansv** [comment]
@sasha-borodin removeRepeatableByKey is more low level and indeed doesn't remove assiciated delayed job. But removeRepeatable does this. I'd recommend to use this method instead of more low-level removeRepeatableByKey where possible.

Remove with `removeRepeatable`:
```
const test1 = async () => {
  const queue = new Bull("repeatable-test1");

  queue.process(async (job) => {
    console.log(new Date().toISOString());
  });

  const job = await queue.add({ "foo": "bar" }, {
    repeat: { cron: "*/2 * * * * *" }
  } as any);

  // remove repeatable after 5 seconds
  setTimeout(async () => {
    await queue.removeRepeatable({ cron: "*/2 * * * * *" });
    console.log("Repeatable job is removed");
  }, 5000);
};
```
Output:
```
2019-09-25T09:30:08.013Z
2019-09-25T09:30:10.016Z
Repeatable job is removed
<no more lines added>
```
And with `removeRepeatableByKey`:
```
const test2 = async () => {
  const queue = new Bull("repeatable-test2");

  queue.process(async (job) => {
    console.log(new Date().toISOString());
  });

  const job = await queue.add({ "foo": "bar" }, {
    repeat: { cron: "*/2 * * * * *" }
  } as any);

  // remove repeatable by key after 5 seconds
  setTimeout(async () => {
    const jobs: JobInformation[] = await queue.getRepeatableJobs();
    for(let i = 0; i < jobs.length; i++) {
      await queue.removeRepeatableByKey(jobs[i].key);
      console.log("Repeatable job is removed by key");
    }
  }, 5000);
};
```
Output:
```
2019-09-25T09:30:50.014Z
2019-09-25T09:30:52.013Z
2019-09-25T09:30:54.013Z
Repeatable job is removed by key
2019-09-25T09:30:56.012Z
```

I've tested also these two methods on `every` option instead of `cron`, with custom job ID and with custom job name.
