### ISSUE TITLE
Question: delay restarting stalles jobs.

### ISSUE THREAD

**Issue by akirilyuk** [OptimalBits/bull#1278]
Hi,

is there an option to have stalling jobs restarted with a defined delay?

**Comment by manast** [comment]
No. stalled jobs will be started as soon as a new worker picks them up.

**Comment by akirilyuk** [comment]
@manast Thank you. So for my understanding. If a worker pod crashes, and there are no other pods, the job will remain active in the queue and will be picked up by a new worker once its back online, right?

**Comment by manast** [comment]
@akirilyuk yes that is exactly right (I am assuming pod === a worker server).
