### ISSUE TITLE
Repeatable job is getting removed completely

### ISSUE THREAD

**Issue by impowski** [OptimalBits/bull#1280]
## Description

My problem is that I'm running a repeatable job every minute and I cannot understand why it's getting removed completely after some time.

My `process` function is returning a `Promise`, I add a job to queue when I start the server basically it's a repeatable job with a CRON string which runs a job every minute.

I use `Arena` to monitor the whole process and I see that after some time my `Delayed` job is equal to 0, I tried to debug it with `NODE_DEBUG=bull` and it doesn't show anything.

I'm running my Redis inside of `docker-compose`, in my config I commented out `save` because I thought that this might cause some problems.

When I take a look in my `docker logs` for `Redis` container I see this:
```
1:M 13 Apr 2019 15:55:58.501 * DB saved on disk
1:M 13 Apr 2019 15:55:58.503 * DB saved on disk
1:M 13 Apr 2019 16:38:21.181 * DB saved on disk
1:M 13 Apr 2019 16:38:21.183 * DB saved on disk
1:M 13 Apr 2019 16:38:21.185 * DB saved on disk
1:M 13 Apr 2019 16:39:55.403 * DB saved on disk
1:M 13 Apr 2019 16:39:55.406 * DB saved on disk
1:M 13 Apr 2019 16:39:55.408 * DB saved on disk
```

Maybe it's causing a problem and my repeatable job is just getting removed. But stalled checks a still present, one time a had a problem that all of the keys inside `Redis` were removed due to my problem.

How do I approach this problem and debug it?

## Bull version
Latest

**Comment by alexhung** [comment]
We seem to have same problem too. We have a list of 14 repeatable jobs on a queue and after a while some (or all) will stop and not repeated. Restarting the node process helps but that's a bit hacky.

We've already tried setting `enableReadyCheck` to false with no luck.
