### ISSUE TITLE
Question: difference in configurations and job states

### ISSUE THREAD

**Issue by adame21** [OptimalBits/bull#1282]
So in short, what is the difference between "maxStalledCount" and "attempts" configurations?

It seems only the attempts actually determines anything. 

If attempts it 3 and maxStalledCount is 1, it will still try to do a failed job 3 times before moving it to failed.

While if attempts is 1 and maxStalledCount is 3, it will only do it once and upon failing move it to failed.

So what do these things mean? what's the difference between stalled and failed? is stalled = waiting on the getJobCounts() result object?

Ultimately I want my queue to try a job up to 5 times and if it failed all 5 times, only then move it to failed status. how would i go about configuring my queue to do that?

Thanks.

**Comment by manast** [comment]
You should use "attempts" for what you are trying to do, i.e. retry jobs that failed. Stalled jobs are the ones that have locked nodejs event loop for 30 seconds (default option), and in this case you can decide how many times you are allowed to retry the job in this particular case.

**Comment by adame21** [comment]
Highly appreciated.
Small clarification if you can: if I set attempts to 5, everytime the job fails it willl go like this?
active->failed->waiting->active ? is that how it should look full circle? 
Also should I not be concerned at all about stalled jobs then?
When a job is stalled it means its still "locked" to the worker and nobody else can work on it?
Under what circumstance does a job gets stalled as opposed to failed?
Thank you

**Comment by matikucharski** [comment]
@adame21 It is active->failed->delayed->active.
See `A Job’s Lifecycle` from here https://optimalbits.github.io/bull/

**Comment by adame21** [comment]
So I would just like to quickly update, it seems what was causing my root problem was a bug with redis.
I dont know why it was like this but ill just describe what i figured out and how it was solved:
As long as the process function wasnt using promises or async/await it worked, when I add promises or async/await jobs would get stuck in active or waiting, and rarely randomly fail.
What eventually solved it all was changing the queue instance initiation:
instead of defining redis in object format, all i had to do was change it to a string.
that's it.
To clarify I'm talking about the redis host/port configuration
Hope someone can benefit from this
Thanks for replying I really appreciate the support. 
You can mark this issue as solved
