### ISSUE TITLE
Repeatable job by cron with wrong schedule

### ISSUE THREAD

**Issue by coolnk2001** [OptimalBits/bull#1283]
## Description
Repeatable job by cron expression with wrong schedule

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
Example 
Cron format | 0 */2 * ? * * work for every 2 minute start from 0 is ok
so the schedule is 11:00, 11:02, 11:04, 11:06 .... 
Cron format | 0 1/2 * ? * * work for every 2 minute start from 1 is not ok, 
the expected schedule is 11:01, 11:03, 11:05, 11:07 .... 
but it give 11:01, 12:01, 13:01, 14:01....

Strange that this expression is working ... 0 1-40/2 * ? * *

## Bull version
3.7.0

## Additional information
http://www.cronmaker.com/

**Comment by manast** [comment]
This could be an issue with our underlying library to parse cron expressions which does not support all the syntax in cron: https://www.npmjs.com/package/cron-parser.
Could you verify please?

**Comment by coolnk2001** [comment]
Yes you are correct i use the library test directly here is the result


*/2 * * ? * *
Date:  Tue Apr 23 2019 09:47:26 GMT+0800
Date:  Tue Apr 23 2019 09:47:28 GMT+0800
Date:  Tue Apr 23 2019 09:47:30 GMT+0800
1/2 * * ? * *
Date:  Tue Apr 23 2019 09:48:01 GMT+0800
Date:  Tue Apr 23 2019 09:49:01 GMT+0800
Date:  Tue Apr 23 2019 09:50:01 GMT+0800
1-59/2 * * ? * *
Date:  Tue Apr 23 2019 09:47:25 GMT+0800
Date:  Tue Apr 23 2019 09:47:27 GMT+0800
Date:  Tue Apr 23 2019 09:47:29 GMT+0800
0 */2 * ? * *
Date:  Tue Apr 23 2019 09:48:00 GMT+0800
Date:  Tue Apr 23 2019 09:50:00 GMT+0800
Date:  Tue Apr 23 2019 09:52:00 GMT+0800
0 1/2 * ? * *
Date:  Tue Apr 23 2019 10:01:00 GMT+0800
Date:  Tue Apr 23 2019 11:01:00 GMT+0800
Date:  Tue Apr 23 2019 12:01:00 GMT+0800
0 1-59/2  * ? * *
Date:  Tue Apr 23 2019 09:49:00 GMT+0800
Date:  Tue Apr 23 2019 09:51:00 GMT+0800
Date:  Tue Apr 23 2019 09:53:00 GMT+0800

**Comment by manast** [comment]
so it would be better you report this to that repo and maybe you can find a workaround to resolve your particular issue.
