### ISSUE TITLE
job not processing on for loop for some cases

### ISSUE THREAD

**Issue by LabN36** [OptimalBits/bull#1286]
## Description
I'm facing some strange issue with **bull** although i'm new to it and trying to see if it's good fit for our use case(coming from gearman background) 

### worker code(worker.js)
```
var gCount = 0;
var Queue = require('bull')
var queue = new Queue("test1");
queue.process(function(job, jobDone){
  console.log("Job done by worker", ++gCount);
  jobDone();
});

```

### client code(client.js)
```
var Queue = require('bull')
var queue = new Queue("test1");
for (var i = 0; i < 500; i++) {
    console.log(i);
    queue.add({ foo: 'bar' });
    if (i == 140) {
        process.exit();
    }
};

```
### Step to Reproduce problem 
step1:  run the **node worker.js** on one terminal 
step2: run  **node client.js** on another terminal

you'll notice that on client.js side it'll log form 0-140 and ends the program
and on the worker side nothing happens.

Ideally from according to my understanding when the number is priting on the console it should also process the job.

can you help me understand what's wrong with the code and why it's not working also how to deal with this situations.

on a side note  the worker also doesn't perform when i remove the if statement and add a loop of 500000

**Comment by manast** [comment]
so you are adding the jobs without "awaiting" for them to actually be added. I would bet that the process is exited before they had a chance to actually end into the queue.
