### ISSUE TITLE
Bull.js running times/internal clock

### ISSUE THREAD

**Issue by twigs67** [OptimalBits/bull#1288]
Hello,

I'm trying to figure out how to change the time Bull.js runs/basis it's jobs. My instance internal times are EST, but the jobs are running as if they are in CET. 

I'm sure this isn't a Bull issue, but I'm trying to figure out what time Bull.js basis jobs on?

Thanks

**Comment by manast** [comment]
the timestamps in Bull are generated using Date.now(), so not really timezone dependent. As long as your clocks are synchronised it should just work.
