### ISSUE TITLE
Request / Reply pattern

### ISSUE THREAD

**Issue by alanhoff** [OptimalBits/bull#129]
Is is possible to implement a req/res pattern where I put something on the queue, wait for that job to complete to get the result?

Thx!

**Comment by manast** [comment]
If you check on the README the section called "Returning job completions" it may be what you are looking after.

**Comment by alanhoff** [comment]
So, bull's way would be to create two queues, one for req other for res? That doesn't sounds performatic for me, do you think that redis + bull is the right solution for this kind of pattern?

**Comment by manast** [comment]
not sure how it can be made more performant, consider that its becomes a very stable system where the requester and receiver do not need to be online at the same time...

**Comment by alanhoff** [comment]
my system was using bull for queue management and that was fine, but now I really need req/rep patterns and I don't think that redis is the best solution for this, I'm inclined to use RabbitMQ. Do you have any cents for this senario?

**Comment by manast** [comment]
I have no experience on RabbitMQ, but you should also take a look at ZeroMQ if performance is important for you: http://zeromq.org/

**Comment by alanhoff** [comment]
I will take a look, tanks for your time.
