### ISSUE TITLE
TypeError: queue.client.cleanJobsInSet is not a function

### ISSUE THREAD

**Issue by talkquazi** [OptimalBits/bull#1298]
TypeError: queue.client.cleanJobsInSet is not a function

   at Object.cleanJobsInSet (/var/arbitrage.club/Server/node_modules/bull/lib/scripts.js:376:25)

   at Queue.clean (/var/arbitrage.club/Server/node_modules/bull/lib/queue.js:1122:6)

## Description

As of version 3.8.0 simply using the clean function throws the above error.
//cleans all jobs that completed over 5 seconds ago.
queue.clean(5000);
//clean all jobs that failed over 10 seconds ago.
queue.clean(10000, 'failed');
queue.on('cleaned', function(job, type) {
  console.log('Cleaned %s %s jobs', job.length, type);
});

## Bull version

3.8.0

**Comment by simonflk** [comment]
I have the same problem in 3.10.0. Was this closed as "can't reproduce"? or something else?

**Comment by simonflk** [comment]
For me, this was only broken in production, where the server is compiled using https://github.com/zeit/ncc. A little bit of comparing the structure of `queue.client`, and I discovered it was missing the [lua scripts](https://github.com/luin/ioredis#lua-scripting).

I can workaround this by copying all the .lua files from `node_modules/bull/lib/commands` to the ncc output folder at build time.

This is kind of messy though. @manast Would you be open to a pull request that either:
1. moves [this logic](https://github.com/OptimalBits/bull/blob/ba3e6c44b6f1e74f3cb1e8e4a65086798bcc8c92/lib/commands/index.js#L43-L67) to a build step, exposing them as regular node modules which can be `require`d like any other
2. add an option to override the location of the .lua files [here](https://github.com/OptimalBits/bull/blob/ba3e6c44b6f1e74f3cb1e8e4a65086798bcc8c92/lib/queue.js#L145-L162)

TIA

**Comment by manast** [comment]
@simonflk its closed with a fix.
If you are able to rewrite the current logic so that it is compatible with ncc I will accept the PR as long as it does not sacrifices generalization or flexibility of the current implementation.

**Comment by kaaloo** [comment]
Got bitten by this.  Thanks @simonflk for posting your workaround!
