### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by talkquazi** [OptimalBits/bull#1299]
Related to issue #1298 It would appear that the fix for this issue brought forth a missing promise on an undefined object.

## Description
TypeError: Cannot read property 'then' of undefined
   at Queue.isReady (/var/software/Server/node_modules/bull/lib/queue.js:478:29)
   at Queue.clean (/var/software/Server/node_modules/bull/lib/queue.js:1104:15)

## Bull version
3.8.1

**Comment by manast** [comment]
can you provide a complete snippet that reproduces the issue please?

**Comment by talkquazi** [comment]
It seems to be specific to the project I am working on. I have tried to replicate the error condition but to no avail. You can leave this issue open I will close it within a week if I can't replicate the error.

**Comment by pathikdevani** [comment]
```javascript
(async () => {
  const queue = new Bull('jenkins', process.env.REDIS);
  const jobs = await queue.getActive();
  for (let i = 0; i < jobs.length; i += 1) {
    // assume job is not locked
    const job = jobs[1];
    job.moveToCompleted();
  }
})();
```

getting TypeError when i am trying to remove all jobs from the active state using the above code.

```
(node:7892) UnhandledPromiseRejectionWarning: TypeError: job.queue.client.moveToFinished is not a function
    at Object.moveToFinished (/Users/pathikdevani/Desktop/a2/a2-server/node_modules/bull/lib/scripts.js:164:29)
    at Object.moveToCompleted (/Users/pathikdevani/Desktop/a2/a2-server/node_modules/bull/lib/scripts.js:185:20)
    at Job.moveToCompleted (/Users/pathikdevani/Desktop/a2/a2-server/node_modules/bull/lib/job.js:194:18)
    at /Users/pathikdevani/Desktop/a2/a2-server/test.js:10:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by 
rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js proc
ess with a non-zero exit code.
```

**Comment by manast** [comment]
try this: 
```
(async () => {
  const queue = new Bull('jenkins', process.env.REDIS);
  await queue.isReady();
  const jobs = await queue.getActive();
  for (let i = 0; i < jobs.length; i += 1) {
    // assume job is not locked
    const job = jobs[i];
    job.moveToCompleted();
  }
})();
```

**Comment by pathikdevani** [comment]
```javascript
(async () => {
  const queue = new Bull('jenkins', process.env.REDIS);
  await queue.isReady();
  const jobs = await queue.getActive();
  if (jobs.length > 0) {
    // remove only first active item
    const job = jobs[0];
    // releaseLock if is there any
    await job.releaseLock(job.lockKey());
    // finally move to complete
    await job.moveToCompleted();
  }
})();
```
@manast After trying your code getting some other error.

```javascript
(node:10178) UnhandledPromiseRejectionWarning: Error: Could not release lock for job 3
    at scripts.releaseLock.then.unlocked (/Users/pathikdevani/Desktop/a2/a2-server/node_modules/bull/lib/job.js:173:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10178) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by
 rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10178) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js pro
cess with a non-zero exit code.
```

**Comment by manast** [comment]
because jobs are being processed by other workers, you should not move jobs that are locked for good reasons.

**Comment by pathikdevani** [comment]
@manast All workers are down. jobs are not being processed by any worker.

In my application, I am processing jobs one by one. Each job is running a long task(a few minutes) to complete the job. In the meantime, my job manager(node who is processing jobs) is crashed.

So, Now I have one process in an active state. When I will start my job manager again, I have to resume my process and move it to as complete or failed.

**Comment by manast** [comment]
You do not need to do that, when the crashed worker starts again it will pick up the "stalled" jobs, this is a core function in Bull.

**Comment by pathikdevani** [comment]
@manast But it's not picking already active job after restarting the node. Always pick up a job which is in waiting for the state.

FYI: I am talking about an active job (not stalled)

**Comment by talkquazi** [comment]
Just a follow-up. I was never able to fully replicate the conditions of then being undefined however i believe it has to do with some block level scoping. Creating a queue and then clearing the queue directly after the creation of the queue (previously existing or not) is where I was hitting this problem. For now I am just using bull v3.7.0 instead of upgrading to v3.8.x on my project.

I believe this issue can be closed.

**Comment by manast** [comment]
@talkquazi the reason is that tried to call a redis custom command that has not yet being created since this is an asynchronous process. You just hit a edge case that we have not considered.

**Comment by talkquazi** [comment]
Oh I see. Thanks for the info

**Comment by gabegorelick** [comment]
#1344 contains a way to reproduce this easier.

**Comment by talkquazi** [comment]
** SOLVED **

The fix for me was to upgrade to bull to version 3.18.0 and I made sure that the queue.process was triggered before attempting to use that same queue process to clean the namespace. So essentially you trigger the process function first then before adding any jobs to the queue you clean the queue within the scope of the process function and the error will not occur. You can then use a timeout to begin adding jobs to ensure the clean process finishes first. This is the solution if you are using callbacks and are not using Promises or Await / Async.
