### ISSUE TITLE
More example using promise apis in documentation

### ISSUE THREAD

**Issue by yhpark** [OptimalBits/bull#13]
I see bull make use of promise(bluebird) extensively.

It can be confusing for devs(including me) who are not familiar with this pattern.
Showing a bit of example code with use of promise chain would be helpful.
```javascript
queue.add({ foo: 'bar' }).then(function(job) {
  // do something
}, function(err){
  // handle err
});
```

**Comment by manast** [comment]
promises are well established and understood today so I will close this.
