### ISSUE TITLE
Redis configuration not working

### ISSUE THREAD

**Issue by mahnuh** [OptimalBits/bull#1301]
Using the following configuration does have no effect at all for the redis connection:

```
new Queue('mail-queue', null, { redis: { port: 6378, db: 1 } });
```
It seams any redis configuration is completely ignored. Am I missing something here?
I am using bull v3.8.1.

**Comment by mahnuh** [comment]
Also setting `prefix` option does not seam to work.

**Comment by manast** [comment]
you are not providing the correct params to the constructor, try this:
```
new Queue('mail-queue', { redis: { port: 6378, db: 1 } });
```

**Comment by mahnuh** [comment]
@manast thanks! Did not expect that url has to be omitted entirely. Maybe the docs could be clearer on this.
