### ISSUE TITLE
Can only add Number as job, not string. Your example(queue.add({foo : "bar"})) is not working.

### ISSUE THREAD

**Issue by jordanlola** [OptimalBits/bull#1308]
#### 
debitQueueProducers.add(1) => the work is processed in the consumer as the callback in the consumer is called and i see the data 1
debitQueueProducers.add("1") => the callback used for the consumer is not called, so i even can't use stringified object.
debitQueueProducers.add({foo : "bar"}) => 
```
error in debitQueueConsumer SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Queue.debitQueueConsumer.process (/Users/jordanchevalier/Projects/luckycrush/male-tasks-manager/slave.js:9:23)
    at handlers.(anonymous function) (/Users/jordanchevalier/Projects/luckycrush/male-tasks-manager/node_modules/bull/lib/queue.js:650:42)
    at Queue.processJob (/Users/jordanchevalier/Projects/luckycrush/male-tasks-manager/node_modules/bull/lib/queue.js:1009:22)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
``` 

And when i try to get the value of a job : 
<img width="561" alt="Capture d’écran 2019-05-06 à 11 39 34" src="https://user-images.githubusercontent.com/47326453/57217798-e585d480-6ff3-11e9-82e4-a374e0591402.png">

**Comment by manast** [comment]
I recommend you take deeper look at the documentation and also check the tests. You are not using this library correctly.

**Comment by jordanlola** [comment]
Thanks @manast i do that right now.

**Comment by jordanlola** [comment]
i understand that debitQueueProducers.add("1") will never call my callback used in the consumer as in your code it checks if the first parameter is a string or not. So it considers that is the name of the work. 
But debitQueueProducers.add(1) is working great and not debitQueueProducers.add({a : 1}), not even debitQueueProducers.add("1", {a : 1}). I just don't know what i miss.
<img width="1019" alt="Capture d’écran 2019-05-06 à 12 12 08" src="https://user-images.githubusercontent.com/47326453/57219390-3992b800-6ff8-11e9-941c-da8e1255da7b.png">

**Comment by jordanlola** [comment]
Sorry, in fact it was working great! Thanks
