### ISSUE TITLE
More details on persistence

### ISSUE THREAD

**Issue by bitliner** [OptimalBits/bull#131]
I see bull keeps a task stored in redis also after it terminated.

Is there any  detail on how bull manages persistence?

**Comment by ryan-sandy** [comment]
The jobs hang around until you remove them. There are three ways to do this, `job.remove()`, `queue.empty()`, and `queue.clean()`. Removed jobs will not be found in the `queue.getJob()` method, so you need to pick your cleaning function based on your use case.

```javascript
//This will remove the job after you find it.
queue.getJob(someJobId).then(function (job) {
  job.remove();
});

//This will remove a job as it completes.
queue.on('completed', function (job) {
  job.remove();
});

//This will remove all completed jobs that are older than 5 seconds. (Note: feature is not in 0.3.0)
queue.clean(5000, 'completed');

//This empties everything in the queue (including unfinished jobs.)
queue.empty();
```

**Comment by bitliner** [comment]
Thank you very much, maybe it is worth to add this detail on README.
According to my use case, I am going to remove a job as soon as it is finished (before `done` callback ).

**Comment by zoheirkhonyagar** [comment]
Hi, I want more details about persistence case. does redis store data in the disk ? if it's true so where redis stores queue data ?

**Comment by manast** [comment]
@zoheirkhonyagar I suggest you read redis documentation regarding persistence.
