### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'returnvalue' of null

### ISSUE THREAD

**Issue by dbronin** [OptimalBits/bull#1312]
When multiple threads check if a job is finished by calling the finished prototype, an UnhandledPromiseRejectionWarning is thrown when the returnvalue is called on a null job. This happens because another thread already retrieved the finished job and then removed it. I believe that this is a bug. The error specifically occurs on resolve(job.returnvalue) in the watchdog section. 

Thank you.

**Comment by dbronin** [comment]
Any suggestions? If this is not a bug, am I doing something wrong? Thanks.

**Comment by dbronin** [comment]
Anyone else run into this problem?

**Comment by sagivf** [comment]
I had the same thing. I don't remember the specifics but I think it had to do with removing jobs after they are completed. I think (not sure) it's related to https://github.com/OptimalBits/bull/issues/1371.

**Comment by dbronin** [comment]
@sagivf I think you are absolutely correct. I am glad the issue is being tracked. Thank you for the reply.

**Comment by sagivf** [comment]
Your welcome,  happy it helps. I hope it gets resolved.
