### ISSUE TITLE
Random GetTypeCmds and SortedSetCommands spikes and high redis cpu

### ISSUE THREAD

**Issue by derN3rd** [OptimalBits/bull#1314]
## Description
Our bull-workers are sometimes randomly going crazy.
We are using bull for a high traffic social media network.

Sometime during traffic spikes our redis seems to get stuck in some sort of weird behaviour, causing redis engine cpu to go to 100% and slowing execution time to 1000% and more.

We are currently using bull 3.6.0 as we have many worker environments which are time consuming to upgrade.

We are running a cache.m5.xlarge in AWS ElastiCache with Redis Engine 3.2.10

Is there any bug known from 3.6.0 to 3.8.0 which could be fixed by upgrading?
Could an Redis Upgrade help?

Thanks in advance.

<details><summary>Additional screenshots (click me)</summary>
<p>

![screenshot-2019-05-09_21-25-28](https://user-images.githubusercontent.com/7534045/57484195-b8158100-72a8-11e9-81e8-c8f8e98eee52.png)
GetTypeCmds and SortedSetCommands are getting higher with no reason.
.
![screenshot-2019-05-09_22-29-40](https://user-images.githubusercontent.com/7534045/57485000-da100300-72aa-11e9-9e3b-b30f0dcb039b.png)
Worker execution times go up, while the worker servers cpu/memory stays nomal
.
![screenshot-2019-05-09_22-30-01](https://user-images.githubusercontent.com/7534045/57485044-fe6bdf80-72aa-11e9-8da2-40dd9cca51d0.png)
resultes in much less jobs getting processed.

</p>
</details>

## Bull version
3.6.0

## Additional information
If you need more information, I can prepare an anonymized grafana board with information about redis, bull etc

**Comment by manast** [comment]
are you sure it is version 2.6 and not 3.6? because 2.6 is very old and has known performance issues.

**Comment by manast** [comment]
3.6 on the other hand has performance issues regarding delayed jobs, but they have been resolved in version 3.8 and above.

**Comment by derN3rd** [comment]
yes, sorry we use 3.6.0. I changed it in the issue

**Comment by manast** [comment]
ok, so I highly recommend you to upgrade to latest version, specially if you use a lot of delayed jobs you should see big improvements. It is backwards compatible so it should be relative straightforward.

**Comment by manast** [comment]
let me know  if you still have problems and I will try to help you out.

**Comment by derN3rd** [comment]
Ok. I will try with the upgraded version.

Could the problems somehow come from job processors using files, instead of functions?

**Comment by manast** [comment]
Not that I know about. Since sortedsets is one of the biggest performance eaters in your graphs I would say that it is mostly related to delayed jobs.

**Comment by derN3rd** [comment]
So we updated all our workers to 3.9 now and they seem to chill.
But the issue appeared randomly only every few days. I will let you know if anything happens again.

Thanks for your help and your amazing work on bull! :)

**Comment by sks147** [comment]
Hi @derN3rd which grafana dashboard are you using for bull queues monitoring?

**Comment by derN3rd** [comment]
> Hi @derN3rd which grafana dashboard are you using for bull queues monitoring?

The first screenshot shows AWS ElastiCache metrics on CloudWatch.
The other screenshots show Grafana with metrics saved in prometheus from [bull_exporter](https://github.com/UpHabit/bull_exporter).

I recommend to change your jobs to be configured as `removeOnComplete: false` and edit the bull_exporter [here](https://github.com/UpHabit/bull_exporter/blob/9acc9b2c4a96f65c5bf15c15901b6cde217e61b0/src/metricCollector.ts#L104) to include `await job.remove();` after metrics collection.
Otherwise the metrics collector can't get enough data of the jobs. And without the added line your completed jobs will pile up in the completed queue.

Hope this helps

**Comment by sks147** [comment]
Hi @derN3rd, thanks for suggestions. I'm planning to use a docker image for this bull exporter. Will it be a good idea to implement job removal logic in exporter. What if exporter is not running in High availability and might crash. Will it cause any issue like redis memory spikes etc. Will it scale well?

**Comment by derN3rd** [comment]
It depends on your amount of jobs that could potentially be left over in the completed queue and on the amount of memory that the redis instance has.
We run our exporter with forever, but you could use other tools that will automatically restart the exporter
