### ISSUE TITLE
moveToCompleted with removeOnComplete sets job name to __default__

### ISSUE THREAD

**Issue by gabegorelick** [OptimalBits/bull#1318]
## Description
`moveToCompleted` sometimes sets the job's `name` to `__default__` if `removeOnComplete` is set to `true`. 

## Minimal, Working Test code to reproduce the issue.
Doesn't happen all the time, but happens most of the time for me:
```js
const Queue = require('bull');
const queue = new Queue('foo');

queue.add('bar', {}, {removeOnComplete: true})
    .then(job => job.moveToCompleted(null, true))
    .then(() => queue.getJobs()) // this *should* be empty but isn't
    .then(jobs => console.log(jobs[0].name)); // will output `__default__` most of the time
```
## Bull version
3.9.1

## Additional information
The fact that the queue isn't empty after moving the job to completed is possibly related to https://github.com/OptimalBits/bull/issues/1233, but I don't really understand that issue.

**Comment by chihabhajji** [comment]
up, it also doesnt return a value

**Comment by manast** [comment]
@chihabhajji this issue is closed, if you want any action I recommend you to post a new issue with code that reproduces the issue.

**Comment by chihabhajji** [comment]
> @chihabhajji this issue is closed, if you want any action I recommend you to post a new issue with code that reproduces the issue.

thank you for the reply, i managed to solve it by explicitly providing the name param to __default__ when using bull-board/api
