### ISSUE TITLE
Sample or example for Bull

### ISSUE THREAD

**Issue by GopalChavan** [OptimalBits/bull#1319]
I am a newbie to Bull, I started with [this](https://optimalbits.github.io/bull/) link, It would be great if you can provide a sample application with express.

**Comment by manast** [comment]
There are a handful of samples in the README and also documentation on the API.
Whereas bull can be used in a express based application, it is really not related to webservers and therefore it does not really make sense to provide such specific examples.

**Comment by GopalChavan** [comment]
If you don't mind, can you please provide some references to git repo's, where they are using bull
