### ISSUE TITLE
Custom Job_id

### ISSUE THREAD

**Issue by Giuffre** [OptimalBits/bull#132]
is there a way to set a custom Job_id for a queue?

**Comment by manast** [comment]
No, there is no way to do it, and it would'nt be recommended either since we want to guarantee unique ids for every job. Why do you need this functionality?

**Comment by albertjan** [comment]
Why not add an id to the job data, thats what we do. Bulls jobid is an integral part of a lot of functionality within bull and really shouldn't be part of your implementation, other than pointing to said job.

**Comment by Giuffre** [comment]
I implemented the pattern "message queue" in my application, specifically I have multiple instances listen on a channel Redis, each instance reads messages that pass in this channel and put them in a queue. Unfortunately I can not move the queue before these instances, so if I have n instances that are listening to the channel, i have n identical messages placed in the queue. If I could set a custom identifier, i could overwrite or check that the message has not been added to the queue.

**Comment by ryan-sandy** [comment]
@Giuffre Are you pushing messages back onto the queue because your listener should not be handling that particular message? If so, you probably want to use a pub-sub model instead of a queue. Redis ships with this feature.

If that's not the case, could you differentiate between the "listeners" in your previous post? Are these "listeners" generating new jobs or receiving the output from the completed jobs?

**Comment by pricj004** [comment]
I'd like to reopen this. We have a situation at Mixmax where we have a very high volume of jobs, and we need a concurrency-safe way of ensuring there's only ever one job of a certain type for each user at any given time.

If we could pass `jobId` as a job option, then override it at https://github.com/OptimalBits/bull/blob/master/lib/scripts.js#L81, we could pass in the `userId`.

Happy to do a PR for this. Unless anyone has any advice to the contrary?

**Comment by pricj004** [comment]
As above, see #335
