### ISSUE TITLE
How to remove all data for a specific Queue from redis (full clean up)?

### ISSUE THREAD

**Issue by michalpierzchlewicz** [OptimalBits/bull#1323]
## Description
My use case is as follows:
I dynamically create and remove queues. Each queue is dedicated to one conversation. The conversations live approximately a few hours. The problem is that when I remove a queue using empty, clean and close methods, there are still some leftover data in Redis. This data will mount up over time which will take up more and more space.

## Question
Do you know of any good way to do a full clean up after a Queue?

**Comment by stansv** [comment]
As far as I know there's not such functionality in Bull, try using ioredis directly.

```
import Redis from "ioredis";

const redis = new Redis();

const deleteKeysByPattern = (pattern: string) => {
    return new Promise((resolve, reject) => {
        const stream = redis.scanStream({
            match: pattern
        });
        stream.on("data", (keys: string[]) => {
            if (keys.length) {
                const pipeline = redis.pipeline();
                keys.forEach((key) => {
                    pipeline.del(key);
                });
                pipeline.exec();
            }
        });
        stream.on("end", () => {
            resolve();
        });
        stream.on("error", (e) => {
            reject(e);
        });
    });
};

// "bull" is queue prefix (default), "example" is the name of queue
deleteKeysByPattern("bull:example:*");
```

**Comment by VictorGaiva** [comment]
Since a linked [issue](https://github.com/OptimalBits/bull/issues/1437) has been marked as a new feature to be added to the next version, I believe that this issue can be closed.

**Comment by RodolfoSilva** [comment]
You can use the command line for this:

```bash
// "bull" is queue prefix (default), "example" is the name of queue

redis-cli --scan --pattern bull:example:* | xargs redis-cli  del
```

**Comment by manast** [comment]
Closing since we have the obliterate method now https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueobliterate

**Comment by RodolfoSilva** [comment]
![image](https://user-images.githubusercontent.com/1703020/125613211-80badc03-82d5-4d5a-b4d3-2c693dc8b513.png)
