### ISSUE TITLE
[question] what happens when delay is negative?

### ISSUE THREAD

**Issue by sibelius** [OptimalBits/bull#1327]
question

## Description
what happens when delay is negative?

```jsx
params: { delay: -172800000 }
```

**Comment by stansv** [comment]
There would be also great to have some checks on concurrency setting; currently zero or any negative number will just lead to ignored `process()` call (and I noticed thet returned promise resolves immidiately).

**Comment by lukepolo** [comment]
Setting my limiter 
```
 limiter: {
          max: 2,
          duration: 1000,
        },
```

Causes my delay to go negative : 
![image](https://user-images.githubusercontent.com/2066668/99588101-16e8aa00-29b8-11eb-97e8-4c1eeca8e746.png)


Is there something im setting up wrong?
