### ISSUE TITLE
[Question] Retry Job with Delay

### ISSUE THREAD

**Issue by Kapulara** [OptimalBits/bull#1328]
Hi,

When dealing with API Rate Limits across multi process workers, I would like to retry jobs that have been failed after X seconds. (e.g 1 minute after job failed, retry the job)

Since jobs will fail when rate limits have been reached.

Now my question is how would I go about doing this? Re-add the job with a delay and lose the history of the job? Or is it possible to use `.retryJob`

Thanks 😄

**Comment by stansv** [comment]
Hi! Did you tried to specify a backoff timeout in job options? https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd
