### ISSUE TITLE
Only process one job at a time

### ISSUE THREAD

**Issue by helloworld** [OptimalBits/bull#133]
I would like to only start the next job once the current job is complete. The queue should only process one job at a time. 

How do I accomplish this?

**Comment by manast** [comment]
Thats the default when you do not specify any concurrency level, you should be able to use the examples in the README.

**Comment by helloworld** [comment]
Currently the next job (and several more) are starting immediately and before I call done(); however. Is that the correct way to show the current job is done and to start the next one?

**Comment by manast** [comment]
Yes, calling done() or returning a promise.
There should not start more than one job at a time, if that is the case then something is not working correctly.
