### ISSUE TITLE
Job Logs - How to ensure they are cleaned after job completion?

### ISSUE THREAD

**Issue by arnaudbesnier** [OptimalBits/bull#1330]
## Description
Hi,

I implemented the latest `log` feature.
Seems to work as expected 💪 

I observe that those logs persist on Redis (even for completed jobs).
Is it the expected behaviour?

I didn't find a way to configure the automatic cleaning on job completion in the documentation and didn't find any traces of such implementation in the diff:
https://github.com/OptimalBits/bull/compare/v3.8.1...v3.9.0

As we have a lot of jobs executed in production, I don't want to "explode" my Redis storage.

Thank you and keep up the good work!!

## Bull version
v3.9.1

**Comment by manast** [comment]
that was an oversight from me part, of course job logs should be deleted when the job itself is deleted.
