### ISSUE TITLE
"Missing process handler for job type" error when not reusing queue instance

### ISSUE THREAD

**Issue by stansv** [OptimalBits/bull#1334]
Hi! This is more a question, the problem is that I'm running 5 jobs sequentially and some of them may fail with mysterious "Missing process handler for job type" error:

```
    new Bull("example").on("global:completed", (job, result) => {
        console.log(`COMPLETED: Job ${job} completed with result ${JSON.stringify(result)}`);
    });

    new Bull("example").on("global:failed", (job, error) => {
        console.log(`FAILED: Job ${job} failed with error ${error}`);
    });

    new Bull("example").process("type_a", (job: Job<any>) => {
        return { type_a: true };
    });

    // everything works if we remove this processor
    new Bull("example").process("type_b", async (job: Job<any>) => {
        return { type_b: true };
    });

    for (let i = 0; i < 5; i++) {
        new Bull("example").add("type_a", {
            foo: "bar"
        });
    }
```

The output is:

```
[Node] COMPLETED: Job 1 completed with result "{\"type_a\":true}"
[Node] COMPLETED: Job 3 completed with result "{\"type_a\":true}"
[Node] FAILED: Job 2 failed with error Missing process handler for job type type_a
[Node] COMPLETED: Job 4 completed with result "{\"type_a\":true}"
[Node] COMPLETED: Job 5 completed with result "{\"type_a\":true}"
```

I'm trying to figure out whether I'm using bull API incorrectly here or this can be a bug.

Node v12.2.0, bull 3.10.0.

**Comment by stansv** [comment]
I've played around with named processors a bit and can conclude for myself that this feature have some drawbacks and API can be confusing. I realized that queued jobs cannot be "skipped" if worker cannot process job of some type. So, once you define at least one processor on a Queue, you are forced to accept a job and can't just offer it to another worker which can handle it.

**Comment by manast** [comment]
You are right and in bull 4 this has been made much more clear.

**Comment by Richard-Scap** [comment]
@manast has there been a release date set for bull 4?

**Comment by manast** [comment]
@Richard-Scap targeting this summer

**Comment by yangju** [comment]
I got the Missing process Handler for job type issue too.
It works locally (sandboxed)
queue.process(2, path.resolve('job/JobProcessor.js'));
or
queue.process(2, path.join(__dirname, 'JobProcessor.js'));
However, when I deployed the application to AWS (fargate hosted docker container), it throws Missing process Handler for any job it handles. I can see the jobs are marked as failed in redis.
If I make it in process such as queue.process(function(job){.....}, it works in aws.
I have tried many things such as
queue.process(2, __dirname+'/JobProcessor.js') and others, none work in fargate container.
I printed out the values for process.cwd(): it is /app/job, which is not the absolute path from the root.
Maybe the application could not find the 'JobProcessor.js' in a serverless fargate deployed container?

What is Missing process Handler anyway?

**Comment by stansv** [comment]
Do not specify any name when you put new jobs to queue if you do not use named processors:

```
queue.add('someName', { foo: "bar" }); // <-- wrong, remove 'someName'
```

**Comment by yangju** [comment]
I added job like this
job.add({'request_id': myId, 'other_id': otherId}, {delay: processingDelay});
As you can see it does not have anything unusual. It works locally. It just not working in AWS.
I think the problem is 
queue.process(2, path.join(__dirname, 'JobProcessor.js'));
I printed out the __dirname when running in Fargate ecs contain. The __dirname has a value which is not absolute path as I see when running locally. Its value is more like '/app/job' which is the relative location of the file which invoke this line of code. Locally I have a value something (Mac) like: /Users/[myuserid]/myproject/app/job
So I guess this is the problem?
My question is queue.process(threadCount,processorFile), what should be the path of the processorFile? Should it be an absolute path or just a relative path the the current file?

Thanks.

**Comment by stansv** [comment]
@yangju I have no other ideas, please try

```queue.process('__default__', 2, path.join(__dirname, 'JobProcessor.js'));```

**Comment by yangju** [comment]
@stansv Thanks for your suggestions. Adding '__default__'  worked!
so this worked: queue.process('__default__', 2, path.join(__dirname, 'JobProcessor.js'))
but queue.process( 2, path.join(__dirname, 'JobProcessor.js')) did not work.
It seems that for sandboxed processor, we will need to have a named processor?
Anyway, it works now. Thanks again.

--Richard

**Comment by stansv** [comment]
-- did you tried this?

    queue.process(__dirname__, 2, path.join(dirname, 'JobProcessor.js'))

**Comment by cjancsar** [comment]
Any way to fix this?

**Comment by rama41222** [comment]
```
Queue.prototype.add = function(name, data, opts) {
  if (typeof name !== 'string') {
    opts = data;
    data = name;
    name = Job.DEFAULT_JOB_NAME;
  }
```
internal li says that, it will automatically assign the default if the first arg is not a string

**Comment by raphab3** [comment]
> Do not specify any name when you put new jobs to queue if you do not use named processors:
> 
> ```
> queue.add('someName', { foo: "bar" }); // <-- wrong, remove first arg
> ```
> 
> make sure the input data for your job (as like `{foo: "bar"}` here) is not of type string, it should be object.

Success!

**Comment by langal** [comment]
If this helps anyone,  I had my concurrency set as an environment variable - which I forgot to parse into an Integer....and was then passed as the first argument into "process"....which then gave the processor a name like ("8") instead of the default '__default__'.

I do generally prefer named parameters.

**Comment by aditodkar** [comment]
> Do not specify any name when you put new jobs to queue if you do not use named processors:
> 
> ```
> queue.add('someName', { foo: "bar" }); // <-- wrong, remove first arg
> ```
> 
> make sure the input data for your job (as like `{foo: "bar"}` here) is not of type string, it should be object.

This worked for me. Thanks
