### ISSUE TITLE
Is there any way to catch redis errors?

### ISSUE THREAD

**Issue by ye-will** [OptimalBits/bull#1336]
## Description

If we lose the connection to redis, we shoud catch it and take actions.
But nothing found in the doc.

## Bull version

bull@3.5.2

**Comment by ye-will** [comment]
Found sulution.

    queue.on('error', function(error) {
        // An error occured.
    })

**Comment by matija2209** [comment]
Does this catch all kinds of Redis errors? I've noticed that my Redis was at the limit with clients and it was rejecting. However, I did not get any prompt in my code.
