### ISSUE TITLE
queue.add still throw exception, when ioredis reconnected

### ISSUE THREAD

**Issue by HsinHeng** [OptimalBits/bull#1340]
## Description
I want to test reconnect mechanism of bull/ioredis, my test program as bellow
```
const queue = new Queue("test", {
		redis: {
			maxRetriesPerRequest: null,
			retryStrategy: function (times) {
				console.log("connection retry...");

				return Math.min(times * 50, 2000);
			},
		},
	});

setInterval(() => queue.add({ msg: "hello world" }), 3000);
```

1. Use Case 1
turn off redis -> start my program ( ioredis try to reconnect...) -> turn on redis
however, queue.add still throw Error
```
{ Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379 }
```

2. Use case 2
redis is on -> 
start program ->
turn off redis ->
my program connection retry.. -> 
turn on redis-server ->
reconnected & queue.add work fine.

How can fix the use case 1  or is it  a bug?

## Bull version
3.10.0

**Comment by joewagner** [comment]
I ran into this issue today.  Wanted give a +1 for fixing and to present a potential workaround.  
The idea is to just kill the process and fail as loud as possible if the redis connection can't be established during startup, which is the cause of this issue afaik.

```
const queue = new Queue('worker queue', {
    redis: this.config.redisOptions
});

let initialConnection;
queue.isReady().then(() => {
    initialConnection = true
},
err => {
    if (!initialConnection) {
        console.error('Cannot establish connection to Redis during startup, exiting...')
        console.error(err);

        process.exit(err);
    }
});
```

Any input or alternatives to this approach would be much appreciated

**Comment by manast** [comment]
as promises works it will either resolve or reject, so in your example above you do not have any use for the "initialConnection" variable.

**Comment by joewagner** [comment]
@manast good call, thank you!

**Comment by zyf0330** [comment]
I just cannot find doc about `isReady` in REFERENCE.md
