### ISSUE TITLE
removeOnComplete typescript definition is boolean instead of boolean | number

### ISSUE THREAD

**Issue by FredericLatour** [OptimalBits/bull#1342]
## Description
Typescript definition for interface JobOptions.removeOnComplete is currently boolean:
```
removeOnComplete?: boolean;
```

while It should be:
```
removeOnComplete?: boolean | number;
```
In order to comply with the new feature that makes it possible to keep the last *number* jobs.

## Bull version
latest version.

**Comment by manast** [comment]
please report it on the https://github.com/DefinitelyTyped/DefinitelyTyped repo

**Comment by FredericLatour** [comment]
Wouldn't you rather support typescript directly into the repo?
Typescript is really taking over. Major javascript projects are moving to typescript (jest, vue, etc ...).
Moreover, It's not like you were going to make major changes to Bull public api in the future. Therefore, starting from the current DefinetelyTyped file should not involve much work for each release.
I guess, I know the answer ... however, one can always try ;)

**Comment by manast** [comment]
you do not need to convince me, bull is being rewritten in typescript here: https://github.com/taskforcesh/bull/pull/1
:).

**Comment by FredericLatour** [comment]
lol ... indeed.
Out of curiosity, any idea when it will be released?

**Comment by manast** [comment]
as soon as it is ready. most functionality is done, but there are some tests still failing. So hopefully released during the summer.
