### ISSUE TITLE
queue.isReady should be called queue.onReady

### ISSUE THREAD

**Issue by gabegorelick** [OptimalBits/bull#1345]
## Description

I would expect `queue.isReady` to return (or resolve to) `true` or `false` depending on whether the queue is ready. But it actually only resolves *when* the queue is ready. A more appropriate name would perhaps be `queue.onReady`.

## Bull version
`develop`

**Comment by manast** [comment]
You are correct in that the naming is incorrect, however it will never return false. Changing it now would imply a breaking change which is too much to ask for so small benefit. Currently no plans to release any new breaking changes on Bull.
