### ISSUE TITLE
can a job be stalled before the lock takes action?

### ISSUE THREAD

**Issue by Gappa88** [OptimalBits/bull#1349]
is it possible that between the moment in which a job is going to be assigned to a processor and the moment in which the processor locks this very job the `stalled-check` marks this job as stalled?

if the job is marked as `active` before the processor locks it I think that this is possible.

is it going to be like this?

Thanks

**Comment by manast** [comment]
It can be possible but for that to happen it should take more than "stalled interval" which is 30 seconds by default  from moving to active to taking the lock, which would be a quite abnormal situation anyway.
