### ISSUE TITLE
Question: Events are local or distributed?

### ISSUE THREAD

**Issue by Gappa88** [OptimalBits/bull#1352]
According to [Events doc](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#events) and [#350](https://github.com/OptimalBits/bull/issues/350)
 I thought that events were fired on the same worker which has just processed that job.
I have a bunch of workers (40) installed on different servers (5) which are created with the following structure:

```
// master.js
const jobid_dones = {};
const cp = require('child_process');
const processor = cp.fork(`${__dirname}/processor.js`, []);

const Bull = require('bull');
let redis_conf = nconf.get("redis_angl:connection_parameters");
const queue = new Bull(nconf.get("redis_angl:prefix"),
  {
    settings: {
      maxStalledCount: 1
    },
    redis: redis_conf
  }
);
queue.process(1, (job, done) => {
    // saving the done function
    jobid_dones[job.id] = done;
    processor.send({ cmd: 'proc', job });
  });

processor.on('message', (obj) => {
  switch (obj.cmd) {
      case 'processed': {
         // complete the job
         jobid_dones[obj.job_id]();
         break;
       }
    }
});

queue.on('completed', async (job, result) => {  .... do stuff ...});
queue.on('error', (err) => {  .... do stuff ...});
queue.on('failed', function (job, err) {  .... do stuff ...});
queue.on('stalled', function (job) {  .... do stuff ...});
```

```
// processor.js

process.on('message', async (obj) => {
  switch (obj.cmd) {    
    case 'proc': {
     // execute the job
     .....
     // return the result
      process.send({ cmd: 'processed', result});
      break;
    }    
  }
});
```

During the peek of work where workers have to process 400k jobs in 3 hours it happens that events are logged by different workers.
For example, if `worker1` installed on `server1` processes a job and completes it calling the `done` function it happens that the `completed` event for this `job_id` is logged by `worker3` installed on `server3`.

is this the correct behaviour?
is it possible to get the event **locally** in the same worker that has just processed it?

**Comment by manast** [comment]
if the event names are not prefixed with ```global:``` then they are local. So you have probably some other issue that makes it look like that the job processed by a worker is emitting the event on other worker, but that just cannot be the case.
