### ISSUE TITLE
How to throw data in queue and then process daily?

### ISSUE THREAD

**Issue by hagginoaks** [OptimalBits/bull#1353]
## Description
I'm looking for a (bull.js) example on how to implement a queue that I can throw data into (say `id`s), and then periodically (like once a day) go through and process everything that's in the queue and put it into my Postgres database.

It seems like most implementations add the stuff to the queue on a schedule, but I want to immediately throw it into redis, and THEN process it later.

## Bull version
Latest

**Comment by stansv** [comment]
So you need to collect some amount of jobs and you want them to be processed once a day starting at exact hour? There're many ways to implement this,
1) use ioredis directly to collect all input data for your jobs, then you'll create one scheduled job to iterate through all collected data, create jobs and make clean up if needed.
2) almost the same, depending on current time add jobs to fresh Queue with name containing day pattern, for example, "YYYY-MM-DD"; then in scheduled job just define a processor for this Queue and call done(). Clean queue if needed (https://github.com/OptimalBits/bull/issues/1323).
3) put new jobs in same Queue always, but calculate delay timeout (milliseconds), see JobOpts here https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd. The most simple solution I think.
