### ISSUE TITLE
How to handle nested Rate limiter in single job?

### ISSUE THREAD

**Issue by sandipmavani** [OptimalBits/bull#1354]
**Description**

I have one use case is it possible to fulfill by a bull?

I have one job that executes every 3 seconds once. (this is possible at now bull Rate limiter)

but I have an extra requirement that max 500 jobs execute in 1 hour means nested type rate limiter is it possible if yes then how can I do it. 

**Bull version**
latest

**Comment by stansv** [comment]
There's no such functionality in bull, what you can do is to use some external package. Take a look on https://github.com/SGrondin/bottleneck for example. You'll need to setup as follows:

```
const limiter = new Bottleneck({
  maxConcurrent: 1, // probably doesn't needed in your case
  minTime: 3000,
  reservoir: 500,
  reservoirRefreshAmount: 500,
  reservoirRefreshInterval: 3600 * 1000,
  id: "my-jobs" // All limiters with the same id will be clustered together
  datastore: "ioredis",
  clearDatastore: false,
  clientOptions: {
    // see https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options
    host: "127.0.0.1",
    port: 6379
  }
});
```

It uses Redis as well as bull.

Finally wrap entire job process function with `limiter.schedule()` call:

```
queue.process((job, done) =>
{
  limiter.schedule(() => doSomething(job.data))
   .then((result) => {
     done(result); // to finish job
   });
});
```
