### ISSUE TITLE
Unexpected exit code: 0 signal: null

### ISSUE THREAD

**Issue by adarmanto** [OptimalBits/bull#1362]
## Description

I'm using a processor file as described https://github.com/OptimalBits/bull#separate-processes and got an error "Unexpected exit code: 0 signal: null" for the jobs occasionally.

    Error: Unexpected exit code: 0 signal: null
        at ChildProcess.exitHandler (/home/ubuntu/server/**mydomain**/node_modules/bull/lib/process/sandbox.js:41:13)
        at ChildProcess.emit (events.js:187:15)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)

## Bull version
3.9.1

**Comment by stansv** [comment]
Can you please provide some simplified code examples so we can try to reproduce? As I can see this should happen only if you call process.exit() somewhere...

**Comment by adarmanto** [comment]
Whooops! Yes I did, here are piece of my codes:

    // processor.js
    module.exports = function(job, done){
        const puppeteer = require('puppeteer');
        const browser = await puppeteer.launch();
        const page = await browser.newPage();

        // Do some heavy work

        done(results);
        await browser.close();
        process.exit();
    }

I do that way as I have some zombie processes from 3rd party service called [Puppeteer](https://github.com/GoogleChrome/puppeteer/) when `browser.close()` doesn't exit cleanly.

I'll try remove that now and close this comment. Lets see if that fix my issue. Thanks @stansv!
