### ISSUE TITLE
Multiple server but queue processed only by one

### ISSUE THREAD

**Issue by anddimario** [OptimalBits/bull#1364]
## Description
We are trying to scale bull on multiple server, but we saw a strange problem, there's queue that are processed only by one server. If we stop this server, the others can't take jobs from queue and the queue processing is stopped. Maybe there's some lock variable that allow use to avoid this problem, have you some suggestions about that?

## Bull version
3.4.8

**Comment by manast** [comment]
Are you sure that the other servers have good connection to the redis instance? One server cannot block other workers, there is no such thing in bull. Btw, as a recommendation upgrade to the latest version, it has many bugfixes from 3.4.8.

**Comment by anddimario** [comment]
It seems that the connection is good, other jobs running without problems, is there a way to do some test about that? We set for jobs a really high timeout, could it be the problem?

**Comment by manast** [comment]
what do you mean with very high timeout?

**Comment by anddimario** [comment]
we have this options for queue:
```

  defaultJobOptions: {
    attempts: 2,
    // Time after which the job should fail with a timeout error
    timeout: 1000 * 60 * 60 * 24 * 3, // 3d
    // Time after which the job is retried if failed
    backoff: 60 * 1000, // 60s
    priority: 1
  },
```

**Comment by manast** [comment]
you can always try https://taskforce.sh to see if you can gain more insights

**Comment by stansv** [comment]
So if you just start one of these "other" nodes it would take jobs from queue? And after starting more nodes they won't process anything?

**Comment by manast** [comment]
what do you mean with "these other nodes" ?
A worker that process jobs cannot block other workers.

**Comment by stansv** [comment]
Sure just wondering if queue config on these workers differs from config on that one which is working.
Are you sure you connect to same Redis node, and queue prefix/name exactly matches? Can you please paste how exactly you create Queue on "master" node and workers?

**Comment by manast** [comment]
@stansv sorry for my annoying reply before, I thought you were the poster of the issue so I got quite confused :)

**Comment by anddimario** [comment]
@stansv sorry, i'll try to explain well, we want scale our bull service with more server, on each server run the entire app that can process all queues.
We have for example 3 queue (a,b and c) and start 2 server that run the app. On server 1 all the queues are running, on server 2 only queues, a and b. If we stop server 1, the queue c is not processed. The server 2 can't process the queue on startup, also if there're other server that process the queue.

It seems that redis connection works at the same way, and we can process some queues on all the servers.

**Comment by stansv** [comment]
@anddimario, OK I've got it. So, if server 1 can process queue "c" in your example, and another server 2 cannot, no matter if server 1 is running or not, you can conclude this is not issue with Bull, but something is wrong with your code and/or configuration running on server 2.

Does your servers both have the same codebase? What about environment/configuration provided externally? Please double-check everything.

Can you write event handlers for server 2 to add some more logging?

```
var queue = new Queue(...);
// ...
queue.on('error', function(error) { console.log('Bull/1364 error: ' + error.message + '\n' + error.stack); });
queue.on('waiting', function(jobId) { console.log('Bull/1364 job is waiting: ' + jobId); });
queue.on('active', function(job) { console.log('Bull/1364 job is active: ' + job.id); });
queue.on('stalled', function(job) { console.log('Bull/1364 job is stalled: ' + job.id); });
queue.on('completed', function(job) { console.log('Bull/1364 job is completed: ' + job.id); });
queue.on('failed', function(job, err) { console.log('Bull/1364 job is failed: ' + job.id + ', err: ' + err.message); });
queue.on('paused', function() { console.log('Bull/1364 queue paused'); });
queue.on('resumed', function() { console.log('Bull/1364 queue resumed'); });
queue.on('cleaned', function(jobs, type) { console.log('Bull/1364 jobs are cleaned: ' + (jobs ? jobs.map(job => job.id) : '') + ', type: ' + type); });
queue.on('removed', function(job) { console.log('Bull/1364 job is removed: ' + job.id); });
```

**Comment by anddimario** [comment]
@stansv really thanks for suggestions, i've added some logs, the queue seems on waiting state, i've a lot of logs from waiting state

**Comment by stansv** [comment]
@anddimario, the queue itself is not waiting, it can be paused/resumed, and jobs can be waiting, active etc. I have no ideas now what can prevent jobs from become active. Are there any other events logged, or only waiting? Does each waiting event only logged when new job added or this can happen at any time?

**Comment by anddimario** [comment]
@stansv we are doing some test, maybe it could be our rate limiter settings, but we are trying to debug it
