### ISSUE TITLE
start queue process immediately when repeating queue

### ISSUE THREAD

**Issue by selient** [OptimalBits/bull#1369]
## Description
"every" in RepeatOpts
## Minimal, Working Test code to reproduce the issue.
```
const MS = 1000 * 60;
jobQueue.add(processor.name, {}, {repeat: {every: MS}});
```
#### (An easy to reproduce test case will dramatically decrease the resolution time.)
the queue will execute process after 60 seconds,
how to make it execute immediately?

## Bull version
v3.1.0

**Comment by KayBeSee** [comment]
Did you find a solution to this, @selient?
