### ISSUE TITLE
On job started event

### ISSUE THREAD

**Issue by frct1** [OptimalBits/bull#1372]
Hello, i'm now working with Bull. It's truly awesome.
I have a question: is there are any options to make event listeners like
`workQueue.onStarted('server:something:job')` event which can help users to set triggers when any specified job is started ?
## Description
Job event listeners

Now i see it like:
```
workQueue.onStarted('server:something:job', (job)=>{
  job.on('progress', (data)=>{ /* operate with progress */});
    job.on('completed'), (data) => { 
      console.log('[server:something:job] is completed')
      console.log('starting next job');
      workQueue.add('next:server:job');
    });
})

*p.s: Or setting event like workQueue.on('server:something:job:(started|completed|stalled|etc)')
``` 
and so on...
How do you see that ? I think it add smart use-cases to bull package, because listening global event stream can add difficults and much code like ` if (job.name equals to "smthjobblahblahblah") do something...`
## Minimal, Working Test code to reproduce the issue.
Nope
#### (An easy to reproduce test case will dramatically decrease the resolution time.)
nope

**Comment by manast** [comment]
Please check the 'active' event: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#events

**Comment by frct1** [comment]
@manast Yes, it is.
But in this case it requires to add many many `if ` constructions without flexibility. 
Without that improvement user can not add triggers in any places in app....

**Comment by frct1** [comment]
> Please check the 'active' event: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#events

Hi @manast.
Is emitting like `clients.emit(`${job.name}:started`, { job });` good solution for that ?
I've though about that earlier but not really sure...
