### ISSUE TITLE
Job never repeats

### ISSUE THREAD

**Issue by Banonevar** [OptimalBits/bull#1374]
## Description
My job just never repeats
#### (An easy to reproduce test case will dramatically decrease the resolution time.)
```js
const Bull = require('bull')
const announce = new Bull('announce', process.env.REDIS_URL ? process.env.REDIS_URL : 'redis://127.0.0.1:6379')

announce.process(async (job, done) => {
  await makeAnnounce()
  done()
});

announce.add(null, { repeat: { cron: '0 17 */2 * *' }});
```
## Bull version
3.10.0
## Additional information
I except run it every 2 days

**Comment by stansv** [comment]
I've tried to reproduce this on my PC — the delayed job was created with correct delay using your cron expression. I've changed my clock to 16:59 (local time), restarted bull and exactly at 17:00 delayed job was started, then the new one was created to run exactly after 48 hours. You can see this by exploring `bull:announce:repeat:*` keys in your Redis, each delayed job in schedule will have `timestamp` and `delay` hash fields. Timestamp is pointing to moment of time when delayed job was created for the next run (epoch time in milliseconds), and delay used to calculate time of start as `timestamp + delay`.

**Comment by Banonevar** [comment]
Seems like it was `makeAnnounce` function exception, thx for answer.
