### ISSUE TITLE
Incompatibility with memorystore due to unsupported 'client' command

### ISSUE THREAD

**Issue by rosslavery** [OptimalBits/bull#1375]
## Description
This has already been brought up in #1002 and supposed to be resolved in #1210 (merged).

The new issue is the string returned by `redis-parser` now includes backticks to wrap the strings, meaning the regex no longer matches, causing the error to be thrown.

E.g.:
```
ERR unknown command `client`, with args beginning with: `setname`, `bull:cGVyc2lzdA==`
```

## Bull version
3.10.0

**Comment by skanygin** [comment]
Same error, when fix will be released?
