### ISSUE TITLE
Not possible to create Queue of string

### ISSUE THREAD

**Issue by kikar** [OptimalBits/bull#1377]
## Description
I created a Queue, then if I try to add a string as the job data, the queue uses the string as name, and sets empty object as data.
The error is:
```
Missing process handler for job type 3665668
```
Where '3665668' is just the string I try to pass as job data.

## Minimal, Working Test code to reproduce the issue.
```ts
const publishedSessionQueue = new Queue<string>('session-id-queue', {
  defaultJobOptions: { attempts: 3, backoff: { type: 'fixed', delay: 30000 }, timeout: 5000, removeOnComplete: true }
});

publishedSessionQueue.add(String(session.id));
```

## Bull version
3.10.0

**Comment by stansv** [comment]
This is because there are two variants of this function accepted, as per typescript definitions
```
add(data: T, opts?: JobOptions): Promise<Job<T>>;
add(name: string, data: T, opts?: JobOptions): Promise<Job<T>>;
```

First two args, `name` and `data` are conflicting.

Try instead pass name as well, use default (https://github.com/OptimalBits/bull/blob/develop/lib/job.js#L59) if you don't need named processors feature

```
publishedSessionQueue.add("__default__", String(session.id));
```

**Comment by kikar** [comment]
Thank you very much for the tip @stansv. I would like to use `Job.DEFAULT_JOB_NAME` directly as it is exposed and if it changes it won't break, but looks like the TS types are a bit wrong, and don't expose the Job object.
Are you guys maintaining those, or is it someone external?

**Comment by manast** [comment]
@kikar someone external, otherwise they would be included in this repo :).
