### ISSUE TITLE
How to prioritise workers

### ISSUE THREAD

**Issue by gajus** [OptimalBits/bull#1379]
Suppose I have a pool of 200 workers and a fluctuating stream of jobs in the queue.

I would like to prioritise givings new jobs to the oldest nodes in the pool.

The idea is that I could then detect which pool nodes are mostly idle and scale down the pool.

Does Bull allow any control over which node gets what task?

**Comment by stansv** [comment]
As far as I know there's no such functionality, what you can do is
1) measure mean load on your cluster and shutdown nodes if it's below some threshold
2) or, you can have multiple per-worker queues, then monitor how many waiting jobs in each and control which queue will take new jobs. What's good here is that you can safely shutdown node once queue is empty and all jobs are finished, so no risk to accidentally kill running job.

**Comment by manast-apsis** [comment]
@gajus workers are currently selected by round-robin, so if you have 200 workers, they will all run one after each other. If you want to scale up or down you can measure the amount of waiting jobs in the queue overtime, or the mean waiting time in the queue (by taking the difference between the job creation timestamp and the completed timestamp).

**Comment by gajus** [comment]
> @gajus workers are currently selected by round-robin, so if you have 200 workers, they will all run one after each other. If you want to scale up or down you can measure the amount of waiting jobs in the queue overtime, or the mean waiting time in the queue (by taking the difference between the job creation timestamp and the completed timestamp).

That is a good tip. Thank you.
