### ISSUE TITLE
Question: Associate jobs or queues to a context

### ISSUE THREAD

**Issue by glothos** [OptimalBits/bull#1383]
I got to a certain use case where I have multiple users using delayed jobs. Each user will create a certain set of jobs that should belong only to him. E.g. user with id 1 will create several delayed jobs based on some set conditionals.

However the main problem is that another users can remove, pause, resume that other user's jobs. E.g. user with id 2 needs to do either of the operations above with jobs associated to user 1. This is also based on user requirements.

Since there is no way to name a job (at least I think so) I came to the conclusion that I should use named queues to achieve such behavior. This is all done under socket.io service. The problem with using socket.io with Bull is that I can't recreate a a queue with the same name that already exists and if the connection of user suffers a spike, it will call this controller below and recreate the queue with the same name. I came to this solution for now:

```
import Bull from 'bull';
import { get } from 'lodash';
import Redis from 'ioredis';

const redis = new Redis(process.env.REDIS_URL);

module.exports = async (socket, ws) => {
  let queue;
  const queueId = `queue-${socket.user.id}`;
  if (socket.user.roleId === 3) {
    /* GET SAVED QUEUE MAP IN REDIS */
    const map = await redis.get(queueId);
    /* IF SUCH QUEUE DOES NOT EXISTS, CREATE A NEW ONE AND SAVE IN REDIS */
    if (!map) {
      queue = new Bull(queueId, process.env.REDIS_URL);
      await redis.set(queueId, queue);
    } else {
      /* Queues saves as map in redis. Parsing it to an object */
      const obj = {};
      for (const [k, v] of map) {
        obj[k] = v;
      }
      queue = get(obj, queueId);
    }
    if (queue && (typeof queue.process !== 'function')) {
      queue.process((job, done) => {
        const trip = get(job, 'trip');
        sendSockData(
          socket,
          { trip },
          'socket.request.receivedTripRequest',
          job.data.driver.client,
          'trip-request',
        );
        done();
      });
    }
  }
  ...socket events
}
```
I'm not sure what are the implications of using it that way. Is there a way to just have one queue and create jobs with some kind of name so I can filter them and make a user 2 manipulates jobs of user 1?

**Comment by stansv** [comment]
Why not to use `ioredis` to store separate a user-to-job index (in a list or set), and keep all jobs in a single queue?

**Comment by glothos** [comment]
It can be that as well. But since it's multiple delayed jobs per user, I'm out of ideas how to pause such jobs. Possible through a loop? Wouldn't this cause problems with the queue itself? I'd also to use concurrency a lot.

**Comment by stansv** [comment]
In Bull, you cannot pause a job, only a Queue, and what this mean is that it will just stop calling your `process()` function until resume.

As job-to-user mapping, you can store your additional logical states (paused/resumed/deleted) separately with direct use of `ioredis`. Implementing pause/resume can be tricky. For example, Inside process() code you can check this state from time to time, and, if job is logically paused, save its context somewhere to Redis and complete Bull job. Maybe it will be good idea to save context as a job result. Then, once user resumes a job, just push new Bull job to queue, point it to saved context (you would implement additional check at beginning of process() function for this case) and update user-to-job mapping to replace old job with new.

To "delete" job just remove it from this custom user-to-job index.

**Comment by glothos** [comment]
Sounds a nice solution. But as you said it can be tricky. Is there any implications with my implementation above? If they are lightweight I don't see any problem if I'm not missing something conceptual.

**Comment by stansv** [comment]
To be honest, either I cannot understand your implementation or it doesn't appear to be working (I'm more a Java programmer :). If I understand correctly, you are trying to persist entire Queue object instance to Redis, with all functions, all internal data and then restore and you expect it will work. I'm not sure. You are checking if `queue.process` is not a function and trying to call it right away — why? Queues are lightweight, yes, but they hold the state shared with external process — Redis, at least you must restore connections and reload lua scripts so that Redis would know how to interpret complex commands. Anyway, I don't feel your solution is required to implement what you want. Maybe you can share more info about your case and requirements so I would try to help.

**Comment by glothos** [comment]
You're right. It hasn't worked. I did some testing and it seemed to work. Even though I can save the queues in redis and get them later, it won't have the functions and internal data. I tried this solution because I needed to use the socket in different scopes (socket events) and the different socket connection should be able to manipulate the other user's queue that is created in the other user's own socket connection.

In the end to make it work I just made the user that needs to manipulate the queue to send a message event telling the other client to emit an event to manipulate his own queue:

```
module.exports = async (socket, ws) => {
  let queue;
  const queueId = `queue-${socket.user.id}`;
  if ([3, 5].includes(socket.user.roleId)) {
    queue = new Bull(queueId, process.env.REDIS_URL);
    if (queue) {
      queue.process((job, done) => {
        const trip = get(job, 'data.trip');
        sendSockData(
          socket,
          { trip },
          'socket.request.receivedTripRequest',
          job.data.driver.client,
          'trip-request',
        );
        done();
      });
    }
  }
...
socket.on('queue-pause', () => {
    if (queue) {
      queue.pause();
    }
  });
  socket.on('queue-close', () => {
    if (queue) {
      queue.close();
    }
  });
  socket.on('queue-empty', () => {
    if (queue) {
      queue.empty();
    }
  });
  socket.on('queue-resume', () => {
    if (queue) {
      queue.resume();
    }
  });
...
```
and when the other user needs to manipulate the queue, he does that indirectly using his own socket connection like so: 
```
...
socket.to(room).emit('trips.acceptRequest.triggerPause');
...
```
The whole file is pretty extensive, but this problem is solved for now. Thanks for your help!

**Comment by glothos** [comment]
The main problem was that, socket connections can be volatile, and every time a user reconnected, it was trying to declare the process twice and it was erroring the api.
