### ISSUE TITLE
Repeatable Jobs: Cron pattern conflict

### ISSUE THREAD

**Issue by Igor-Lopes** [OptimalBits/bull#1385]
## Description
If you add 2 jobs with the same cron options, only the first one gets added to the queue. 

## Minimal, Working Test code to reproduce the issue.

Add two jobs with same cron pattern to the queue: 
```
invoiceJob.add(
    'sendNotification', {
        notificationType: 'sendDaysAfter',
        invoiceId: item.id 
    }, {
        repeat: {
            startDate: afterStartDate, // "2019-08-02T03:00:00.000Z"
            endDate: afterEndDate, // "2019-08-29T03:00:00.000Z"
            cron: cronAfter //"00 00 08 */2 * ?"
        }
    }
)
```

#### First Job
```
{
    "id": "repeat:b73833c7c68c8827bcc8dd39ff6531a7:1564830000000",
    "name": "sendNotification",
    "data": {
        "notificationType": "sendDaysAfter",
        "invoiceId": "b5e8bf49-f1c6-4f0d-a68d-b78716f46f21"
    },
    "opts": {
        "repeat": {
            "count": 1,
            "startDate": "2019-08-02T03:00:00.000Z",
            "endDate": "2019-08-29T03:00:00.000Z",
            "cron": "00 00 08 */2 * ?"
        },
        "jobId": "repeat:b73833c7c68c8827bcc8dd39ff6531a7:1564830000000",
        "delay": 1695864327,
        "timestamp": 1563134135673,
        "prevMillis": 1564830000000,
        "attempts": 10,
        "backoff": {
            "type": "fixed",
            "delay": 5000
        },
        "removeOnComplete": false,
        "stackTraceLimit": 10
    },
    "progress": 0,
    "delay": 1695864327,
    "timestamp": 1563134135673,
    "attemptsMade": 0,
    "stacktrace": [],
    "returnvalue": null,
    "finishedOn": null,
    "processedOn": null
}
```
#### Second Job:
```
{
    "id": "repeat:b73833c7c68c8827bcc8dd39ff6531a7:1564830000000",
    "name": "sendNotification",
    "data": {
        "notificationType": "sendDaysAfter",
        "invoiceId": "cc682095-87b8-4403-9622-c899f8647eed"
    },
    "opts": {
        "repeat": {
            "count": 1,
            "startDate": "2019-08-02T03:00:00.000Z",
            "endDate": "2019-08-29T03:00:00.000Z",
            "cron": "00 00 08 */2 * ?"
        },
        "jobId": "repeat:b73833c7c68c8827bcc8dd39ff6531a7:1564830000000",
        "delay": 1695862859,
        "timestamp": 1563134137141,
        "prevMillis": 1564830000000,
        "attempts": 10,
        "backoff": {
            "type": "fixed",
            "delay": 5000
        },
        "removeOnComplete": false,
        "stackTraceLimit": 10
    },
    "progress": 0,
    "delay": 1695862859,
    "timestamp": 1563134137141,
    "attemptsMade": 0,
    "stacktrace": [],
    "returnvalue": null,
    "finishedOn": null,
    "processedOn": null
}
```

You can  see that both jobs returns the same `jobId`.

#### Bull Arena:

![Screen Shot 2019-07-14 at 17 00 21](https://user-images.githubusercontent.com/11265789/61188659-f5a3db00-a658-11e9-89aa-b0b5c42d7e57.png)

As you can see, only the first one is added (You can see that the `invoiceId` param in job data matches the first job added. The second one does not get added to the queue, although `add` function returns as if it was added. 

## Bull version
3.10.0

## Additional information
if you specify `jobId` param, it does solve the problem, as it creates two distinct ids for the jobs.

Is this an expected behavior  ?

**Comment by stansv** [comment]
Bull protects you from accidentally adding the same job with same schedule this way. Yes, setting your own `jobId` works. You can also use numeric values (1, 2, 3, ... etc) as jobId and it won't clash with non-repeatable jobs.

**Comment by Igor-Lopes** [comment]
@stansv , If this is an expected behavior, I think it should be added to the docs, it could save time if someone is having the same issue.

**Comment by stansv** [comment]
@Igor-Lopes of course, docs are far from perfect at this moment. Regarding this particular example, I've came to know about this from here https://optimalbits.github.io/bull/, see the last section about repeatable jobs. But I also noticed the documentation on that site is a bit outdated...
