### ISSUE TITLE
Multi server setup with repeatable queues

### ISSUE THREAD

**Issue by alex-mironov** [OptimalBits/bull#1391]
I have 3 application servers:
<img width="499" alt="Screenshot 2019-07-18 23 28 13" src="https://user-images.githubusercontent.com/2544767/61489849-49455a00-a9b4-11e9-945a-1f0a6fe7ad25.png">

Whenever they start they schedule a repeatable job:
```
  paymentsQueue.process(function(job){
    // Check payments
  });
  // repeat payment job every 60 minute
  paymentsQueue.add(paymentsData, {repeat: {cron: '0 * * * *'}});
```
Does it mean that payment will happed 3 times in 60 mins, or bull is smart enough to run it once on one of the servers?

**Comment by manast** [comment]
It will run only once in one of the servers.
