### ISSUE TITLE
Global events - Point to Point queues

### ISSUE THREAD

**Issue by RPallas92** [OptimalBits/bull#1393]
Is it possible to implement Point-to-point global queues in Bull? 

(https://aws.amazon.com/blogs/compute/implementing-enterprise-integration-patterns-with-aws-messaging-services-point-to-point-channels)

It would be useful when you have multiple instances of listeners but you only want to process one job by one listener. 

Thanks

**Comment by manast** [comment]
So this is how bull works... you can have as many workers (listeners) as you want and every message will only reach one of the workers.
