### ISSUE TITLE
Q: Why is number of concurrencent active jobs decreasing?

### ISSUE THREAD

**Issue by dave7280** [OptimalBits/bull#1394]
Bull version: newest at the time of writing.

I have following setup and i do not understand how some things works.

1. I run a cluster of 10 node processes. Each process is processing a single queue with concurrency parameter set to 300. So overall it should be processing 10x300 = 3000 active jobs.
2. Some of my jobs are hitting stalled state from time to time.
3. I'm using bull-area web interface to watch number of active jobs and waiting jobs.

Now i'm encountering a problem:

1. I start the cluster. I see 3000 jobs being processed concurrently in active state, while the rest is waiting, 10x300  - perfect.
2. I let the cluster run for 1-3 minutes
3. I see that number of activly processing jobs is constantly decreasing. Eg. it was processing 3000 jobs at the moment the cluster was run, then after a while it'r processing 1500 jobs only.
4. The longer cluster rurns, the smaller is the amount of jobs it's being actively processing. It usually stops at around 800, where it's not decreasing anymore (from initial 3000 at the moment of cluster start)

The whole situation looks like some of the workers are stopping processing. What might be causing such behaviour? I though of following reasons:

1. Redis dying, but i added tracing and the redis connection is ok.
2. Node event loop being frozen?
3. It's somehow related to stalled jobs? (my personal favorite)

Below sample code to get better understanding and youtube video (keep a look at "active" count the moment tasks are being inserted from cron every 1M. Starts with 3k, but on every next task insert it's lower and lower)

https://www.youtube.com/watch?v=i5Z4MgPQi0g&feature=youtu.be

```


if (cluster.isMaster) {

//spawn 10 procs
    for (let i = 0; i < 10; i++) {
        cluster.fork();
    }

    cluster.on('exit', function(deadWorker, code, signal) {
    	//Logging to see if worker is dying.
        logger.warn('worker '+oldPID+' died.');
    });

} else {

//below definition of behaviour of worker process. Each is getting seperate redis connection. 

    redisOptions = {
        host: config.get('Redis.host'),
        port: config.get('Redis.port'),
        password: config.get('Redis.password'),
        db: 0,
        options: {}
    };

    var Redis = require('ioredis');



    let httpQueue = new Queue("httpQueue", "", {

    	//Only used to add some debugging callbacks to see if redis connection is not dying. 
        createClient: function() {
            var authedRedis = new Redis(config.get('Redis.port'), config.get('Redis.host'), redisOptions);

            authedRedis.on('connect', function (e) {
                logger.info("REDIS CONNECTED" );
            });

            authedRedis.on('error', function (e) {
               logger.error("REDIS ERROR" + e);
            });

            authedRedis.on('close', function (e) {
                logger.error("REDIS CLOSE" + e);
            });

            authedRedis.on('reconnecting', function (e) {
                logger.error("REDIS RECONNECTING" + e);
            });

            authedRedis.on('end', function (e) {
               logger.error("REDIS END");
            });

            return authedRedis;
        },

        settings: {
                stalledInterval: 3000,
                retryProcessDelay: 0,
                lockDuration: 60000,
                lockRenewTime: 50000
            }
        });

    //300 concurrenct in one process. 30x100 processes = 3000 active jobs should be present.
    httpQueue.process(300, function (job, done) {
        function onCheckFinish (data, err) {
        	//Callback after http request finishes.
            done();
        }

        //callback to onCheckFinish() no matter what.
        sendSomeHttpRequest(job.data.url, onCheckFinish)

    });

    httpQueue.on('stalled', function (job) {
        //logger.info("STALLED");
    });

    httpQueue.on('error', function (error) {
        console.log("ERROR");
        console.log(error);
    })


}
```

**Comment by dave7280** [comment]
I did some more testing and there's possibility that it's related to external library which i'm using to fire outgoing http request. I'll provide more details once i find out, but any kind of general answer of what might be happening would be great! :)

**Comment by stansv** [comment]
Hi! My best bet is that some amount of jobs are indeed stalled, did you tried to measure the CPU utilization on your cluster? I suppose that there can be high load generated by node event mechanism.

**Comment by GeorgeWillaman** [comment]
@dave7280 Did you ever get any more details? Pretty sure I'm experiencing the same thing.
