### ISSUE TITLE
Active jobs move back to waiting while worker still running

### ISSUE THREAD

**Issue by JakubPetriska** [OptimalBits/bull#1397]
## Description
Certain long-running (more than 24 hours) jobs move back from active state to waiting state. This happens approximately after 24 hours from being started. I have one server as master which puts jobs into Bull queue, jobs are then processed on another worker machine which runs all jobs in separate processes with parallelism 2. After jobs move back to waiting state, logs on the worker machine tell me that these jobs are still running.

This is a screenshot from Arena where it's visible that the job already has 44% progress but is still in waiting queue.
![Screenshot from 2019-07-25 09-56-43](https://user-images.githubusercontent.com/5531859/61857497-93eb3880-aec4-11e9-9ea7-613e0db62b77.png)

## Bull version
3.9.1

**Comment by JakubPetriska** [comment]
This might actually just be related to some default job timeout. Unfortunately the documentation does not mention that there is any such default value. https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd

**Comment by manast** [comment]
@JakubPetriska there is no default value for timeout... so a job should never timeout, however, maybe the worker lost connection with redis for more than 30 seconds and some other worker or client may have moved the job back to wait assuming the worker processing it has been stalled.

**Comment by JakubPetriska** [comment]
@manast Is it possible to prolong the period after which job is stalled?

**Comment by JakubPetriska** [comment]
@manast Ok I found in the documentation that I can set `lockDuration` to higher value and achieve exactly that. However I have on question, which documentation does not answer. When I have workers running on different machine, do I have to specify same queue options to all queue instances on all machine? What happens when they differ? Or are the ones that I provide on the worker related only to the worker?

**Comment by manast** [comment]
Since every worker can potentially check for stalled jobs, if they differ they will effectively mark as stalled jobs the minimum value that you had set on any of the workers.

**Comment by JakubPetriska** [comment]
Ok thanks for the information. Right now I think that the issue must have come from other sources than Bull queue, so I guess we can close this for now.

**Comment by stansv** [comment]
@JakubPetriska, please feel free to reopen or create new issue if you have any other questions!
