### ISSUE TITLE
Question: How to get `process.env` of parent process  in tread process?

### ISSUE THREAD

**Issue by insanehong** [OptimalBits/bull#1398]
## Description

I use dotenv for configuration and execute node with process.env.NODE_ENV , but process.env.NODE_ENV is undefined in tread process(child_process.)

How to get `process.env` of parent  in tread process?

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

```js

// worker.js
module.exports = job => {
  console.log('run ENV is: ', process.env.NODE_ENV);
  //// run ENV is:  undefined
  const result = { result: true };
  return Promise.resolve(result);
};
```

```js

app.js
const Queue = require('queue');
const testQueue = new Queue('test');
console.log('run ENV is: ', process.env.NODE_ENV);
// run ENV is: develop
.
.
.
testQueue.process('./worker.js');
testQueue.add({data: 'test});
```

## Bull version
^v3.10.0

**Comment by stansv** [comment]
I cannot reproduce this, tried to set `NODE_ENV` manually just before `add()` and forked child process was able to see the value.

**Comment by insanehong** [comment]
Sorry This is nodemon issue. Thanks.
