### ISSUE TITLE
Stalled job after throwing error in processor

### ISSUE THREAD

**Issue by RPallas92** [OptimalBits/bull#1399]
I am using and async processor, and throwing and error when something goes wrong.
But the job is not retried because Bull says: job stalled more than allowable limit

But I am throwing the error immediately, why it says the job is stalled?

(The job is triggered with backoff 60 seconds)

**Comment by RPallas92** [comment]
I haved added a catch handleFailed method and it throws an error: message:"Sending custom commands in pipeline is not supported in Cluster mode."
which is not handled by the lib

**Comment by manast** [comment]
are you defining the "done" argument? If I do not recall it incorrectly this error can happen if you define a done argument but instead of calling it you just return a promise.

**Comment by manast** [comment]
That error comes from ioredis, we have an issue open for this in their repo but has not been resolved yet.
