### ISSUE TITLE
Question about Bull concurrency with Redis Cluster

### ISSUE THREAD

**Issue by evildead** [OptimalBits/bull#1401]
#607 Description
While testing Bull with a Redis Cluster, I bumped into a weird behaviour: if I use concurrency=1 as process parameter, everything works fine, but when I increase the number of concurrency, I notice a considerable delay between the dispatch and the processing of the job.
This delay increases directly proportional to the value of concurrency.

I did not notice this behaviour with a single Redis instance.

Here is a brief benchmark:
```
concurrency = 1:
18:24:0.528 Added {"data":"My-Task"}
18:24:0.700 Processing {"data":"My-Task"}

concurrency = 2:
18:20:32.124 Added {"data":"My-Task"}
18:20:38.88 Processing {"data":"My-Task"}

concurrency = 4:
18:36:17.326 Added {"data":"My-Task"}
18:36:33.204 Processing {"data":"My-Task"}

concurrency = 8:
18:50:45.963 Added {"data":"My-Task"}
18:51:23.358 Processing {"data":"My-Task"}
```

#### Bull configuration
```
const Bull = require('bull');
const Redis = require('ioredis');
const url = require('url');

const getRedisPasswordFromURI = (redisUri) => {
  const parsedURL = new url.URL(redisUri);
  return decodeURIComponent(parsedURL.password);
}

const redisConfig = {
  host: 'redis://:<pw>@<host>:<port>',
  prefix: 'FPrefix'
};

const nodeOptions = {
  keyPrefix: redisConfig.prefix,
  autoResubscribe: true,
  autoResendUnfulfilledCommands: true
}

const clusterOptions = {
  enableReadyCheck: true,
  retryDelayOnClusterDown: 300,
  retryDelayOnFailover: 1000,
  retryDelayOnTryAgain: 3000,
  slotsRefreshTimeout: 10000,
  clusterRetryStrategy: times => Math.min(times * 1000, 10000),
  redisOptions: nodeOptions
}
clusterOptions.redisOptions.password = getRedisPasswordFromURI(redisConfig.host);
redisClientInstance = new Redis.Cluster([redisConfig.host], clusterOptions);

const bullOptions = {
  prefix: 'FPrefix:{SPrefix}',
  defaultJobOptions: {
    delay: 0,
    removeOnComplete: true
  },
  createClient: (type, opts) => {
    return redisClientInstance;
  }
};

const myQueue = new Bull('testQueueName', '', bullOptions);
```
#### Consumer
```
const concurrency = 1; // Tried with 1,2,4,8
myQueue.process(concurrency, async (job) => {
  const currentDate = new Date();
  console.log(`${currentDate.getHours()}:${currentDate.getMinutes()}:${currentDate.getSeconds()}.${currentDate.getMilliseconds()} Processing ${JSON.stringify(job.data)}`);
});
```
#### Producer
```
setTimeout(() => {
  const myTask = {
    data: `My-Task`
  };
  myQueue.add(myTask);
  const currentDate = new Date();
  console.log(`${currentDate.getHours()}:${currentDate.getMinutes()}:${currentDate.getSeconds()}.${currentDate.getMilliseconds()} Added ${JSON.stringify(myTask)}`);
}, 5000);
```

## Bull version
3.10.0

**Comment by Pistacchione** [comment]
We experienced the same strange issue with redis cluter configuration. Any news?

**Comment by elucidsoft** [comment]
I've been doing extensive testing with RedisCluster after using a single instance Redis for a while and I can say without question Bull does not work properly with RedisCluster no matter what you do you will get random failures and very erratic behavior, which is especially bad under heavy load.

**Comment by evildead** [comment]
Hi everyone.
Regarding my question I just discovered that the problem was inside my configuration:
the `createClient` function returned a pre-created Redis instance; this prevented Bull from creating its necessary Redis instances.
The best approach is to create the instance inside createClient:
```
const bullOptions = {
  prefix: 'FPrefix:{SPrefix}',
  defaultJobOptions: {
    delay: 0,
    removeOnComplete: true
  },
  createClient: (type, opts) => {
    return new Redis.Cluster([redisConfig.host], clusterOptions);
  }
};
```

On the contrary, I'm really worried regarding @elucidsoft reply, because our idea is to use Bull with our Redis cluster...
Do you have any news regarding those 

> random failures

?

**Comment by elucidsoft** [comment]
Just to verify my findings, last night I wrote a test where I add 500k
items to a queue and I have 100 workers process it. This finished with 0
errors on single redis instance.

I did it again with the cluster and I couldn't even get it to add the 500k
items before I get slammed with failed to refresh slot cache errors and
redis errors galore... It only was able to process around 50% but it
crashed multiple times, and the workers also crashed multiple times.

If I bump the timeouts way up I was able to get this to around 90%, but
then I had around 10 items stuck in active that none of the workers were
seeing, just sat there in active for over an hour.

**Comment by manast-apsis** [comment]
@elucidsoft can you confirm that you renamed your queues according to this? https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#redis-cluster

**Comment by elucidsoft** [comment]
Yes I can confirm I did that...

**Comment by stansv** [comment]
I've tried to do some testing on local Redis cluster, and didn't saw any issues, everything works perfectly. Looks like described behavior can only happen with remote cluster.

**Comment by emalamisura-c2m** [comment]
I saw this behavior locally as well, but it was significantly less recurrent.

**Comment by stansv** [comment]
Can you please share more details to help reproduce this locally? I want to prepare some test example including redis setup, which would reliably reproduce issue with stalled workers.

**Comment by elucidsoft** [comment]
Sure I used the grokzen/redis-cluster docker image for local testing.   I
had 100 processors setup in docker images, a node expressjs app for running
the server, I called queue.add inside the request method and also had the
job.finished method returning the response.  I had a load test app I wrote
that would call this end point 500k times adding work and it would record
the response.

Here is how I had the connection setup:
`
const clusterQueue = new BullQueue(
"cluster_queue",
{
prefix: "{clusterQueue}",
createClient: () => new Redis.Cluster([{
host: "redis-cluster",
port: 7000
}])
}
`
);

**Comment by stansv** [comment]
@elucidsoft @emalamisura-c2m thanks! Are you also have any code in your process callback? Do you use concurrency setting and/or sandboxed processors (ie those running in child nodejs process)?

**Comment by elucidsoft** [comment]
All of my processors are running in their own independent docker
containers.

**Comment by waseem-winzo** [comment]
@evildead Hi,
this may be irrelevant to this discussion. But can you tell me while using redis cluster were you be able to distribute jobs in a single queue to different nodes on this cluster. If yes, can you share the configuration on how to achieve this?.
I hit a roadblock when one of my queues can have more that 20-25 million delayed jobs and it will be hard to scale on a single machine.
