### ISSUE TITLE
how to change backoff.delay of job when fail

### ISSUE THREAD

**Issue by phamhoaithuong** [OptimalBits/bull#1403]
when i add job, i config job option : attempts 10 and backoff.delay  10000
so, i want when job fail, i want to update backoff.delay. How to do that?
Thank you very mush.

**Comment by stansv** [comment]
Hi! Please take a look at https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#custom-backoff-strategy. The idea is to provide a function to Bull which can calculate delay based on num of attempts made and job failure details.

**Comment by phamhoaithuong** [comment]
thanks you, i dont nkow why i cant see it when read document
