### ISSUE TITLE
Jobs stuck in active queue

### ISSUE THREAD

**Issue by RPallas92** [OptimalBits/bull#1406]
Jobs are stuck in active queue using redis cluster elasticache (AWS)

First job created is received by the worker, but second one is not. This is happening all the time. It works in local.

![image](https://user-images.githubusercontent.com/3767659/62279671-d4a9fb00-b44a-11e9-806b-c1e3819a9e80.png)

In the Taskforce's worker tab, the worker is connected, but is not receiving any event.

(They are not event moved to stalled/ failed)

**Comment by manast** [comment]
This is probably an error in your workers, maybe after processing one job some old state is interfering and the second time it does not complete. If you just use an empty worker that does nothing, does it work then?
Just to clarify, Bull is used with elasticache in many projects with high concurrency and works just nice. :).

**Comment by RPallas92** [comment]
Thanks for the reply @manast 
Does it work well with Redis Cluster? Looks like IORedis is not working well with redis cluster...
Why are the jobs not moved to fail if they are active for so long? (The queue has default options)

**Comment by manast-apsis** [comment]
they will not fail automatically unless the worker throws an exception.

**Comment by manast-apsis** [comment]
there is a time to live option that will fail after some determined time though, but it is better to understand why the worker did not complete in the first place.

**Comment by RPallas92** [comment]
The workers completes, we have logs to check it. In local, with local Redis cluster works perfect... must be something related with connection

**Comment by manast** [comment]
if you try with workers that do nothing, still does not work?

**Comment by amrendra007** [comment]
![Screen Shot 2019-08-02 at 12 05 48 PM](https://user-images.githubusercontent.com/21372003/62349620-ed371580-b51d-11e9-8889-5789d00d4022.png)

I am facing similar issue also , check screenshot  jobs counts in waiting and active state btw i m using removeOnComplete :true, so no jobs are in completed sec.

i am using node without cluster and redis , 

my flow to process job using bull

    const createSomeJob = (data) => {
      queue.add('somejob', {data}, {removeOncomplete: true} )
    } 
    createSomeJob();

    queue.process('somejob', async job => {
       return new Promise(async (resolve, reject) => {
         try {
            //doing some work
           resolve(true);
          } catch (error) {
             reject(error);
         }
       });
    });

**Comment by RPallas92** [comment]
Also, We have logs on `queue.on("completed")` and jobs are being completed. We are going to try with single redis instance inside our k8s cluster.

**Comment by RPallas92** [comment]
We have tried with single redis intance in our k8s cluster and everything works fine (same code), so i guess there is an issue with redis cluster in aws

**Comment by olivierto** [comment]
I'm facing the exact same issue here. 
Got 2 workers, and a really simple job : fetching pictures and create a pdf file.  
The worker logs prints that it's starting the job, and then nothing... and it doesn't output any errors.

After restarting the worker, the jobs are properly executed by the worker and put to complete state.

**Comment by manast** [comment]
@olivierto I would bet it is something wrong with your workers code. The approach to this errors is to remove all logic in the worker and then add step by step until you find the reason for the issue.

**Comment by olivierto** [comment]
@manast thanks for your answer.
I already set up with a reproducing environment and added the worker's logic step by step , but it seems that this issue appears randomly so I failed to reproduce the active stuck state of the job (after dozens of tries of the same job). 

Do you think the job's timeout option will work in such case? If so i can manage to retry the job after it fails as a workaround.

**Comment by elucidsoft** [comment]
I have a RedisCluster in my k8s, and I have noticed a rather significant degradation in the number of connections I can open, how fast I can add items to a queue before I get redis errors on the cluster that I never got on a single instance. So there are some behavior changes when using a cluster.

**Comment by elucidsoft** [comment]
I am considering a different approach to the redis cluster tbh.  I think instead of having a rediscluster I am going to have multiple servers and worker groups and each of those groups will be smaller and talking to a single redis instance and I will load balance between the multiple groups. I think that approach will be significantly more responsive than having a server and many many many workers talking to a redis cluster as that is giving me a TON of exceptions just randomly.

**Comment by manast** [comment]
I am surprised redis cluster works at all, since there is a bug in ioredis that prevented its use with Bull, unless they fixed it recently. Also cluster does not provide any benefit to bull, since it can only work with keys placed in a given node, here is some explanation and how to use it (in theory): https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#redis-cluster

**Comment by elucidsoft** [comment]
Yes, I had to split out my queues into many queues and then dynamically generate keys based on my user's ids so I can get some benefit of distribution. But I wouldn't recommend it. Redis Queue is a pain in the butt to setup, it adds redundancy in the event of failure. But does it matter?  If you have liveness probes setup you can restart your container and be back up in a manner of seconds.  I had significantly better scalability with a single instance as I mentioned, so there is something wrong with using Bull in a Redis Cluster. Would not recommend wasting your time!
