### ISSUE TITLE
Limit the number of concurrency processes on multiple servers.

### ISSUE THREAD

**Issue by ngochip** [OptimalBits/bull#1407]
## Description
I setup 3 servers to handle processes.
However there is a special queue called 'getAsset', it is only allowed to run sequentially.
I have now handled:
`queue.process (1, '/js/getAsset.js')`

But because I setup on 3 servers, each server will have 1 process 
==> there are 3 processes running in parallel.

How do I control: at one time, only 1 process on all 3 servers will active.

**Comment by manast** [comment]
That is not possible, Bull will run in parallel on all the workers that you have started.
