### ISSUE TITLE
No delayed event. How to detect when the jobs gets delayed?

### ISSUE THREAD

**Issue by bdrtsky** [OptimalBits/bull#1410]
I don't see `delayed` event. So how do I know that jobs is delayed? I can't do this in `getJobs`, because I need this real time in events handler, to notify the client that job is delayed. Right now I don't see literally any explanation where, how and why job gets delayed.

**Comment by manast** [comment]
They only get delayed in 3 situations:
- when using the delay option.
- retries using backoff setting.
- when using the rate limiter and the job has been rate limited.
the delayed event is emitted, however you may need to listen to the global version of it: ```global:delayed```

**Comment by stansv** [comment]
@manast 
I've tried to search in codebase and cannot find where we call emit('delayed'), are you sure we're firing it?
Also, as far as I understand, the 4th case where delayed jobs gets spawned is when job is repeatable.

**Comment by manast** [comment]
yes, we do not emit in javascript, but publish in LUA: https://github.com/OptimalBits/bull/blob/develop/lib/commands/addJob-6.lua#L62
we may miss some place though, I am not sure.

**Comment by bastibeckr** [comment]
Hi, sorry to ask again about this. I cannot get the global:delayed event fired. 

To be sure, I plugged a logger into the emit method of Queue, so all events get logged. I see progress, completed, failed, active, waiting, but not delayed.

I don't know if the event will fire locally, but there seems to be no global:delayed event at the moment.

**Comment by manast** [comment]
@bastibeckr could you provide a test code that reproduces that behaviour and open a new issue with it?
