### ISSUE TITLE
Queue close does not close connections if it is called when is redis offline [BUG]

### ISSUE THREAD

**Issue by misos1** [OptimalBits/bull#1414]
## Description

Seems when is redis offline then bull is trying to reconnect and in this state queues cannot be closed. When is queue closing it should cancel reconnecting. Also seems if are queues created when is redis offline they will never actually connect after is redis run.

## Minimal, Working Test code to reproduce the issue.
``` node js
let Queue = require("bull");
let queue = new Queue("queue");
queue.process(_job => console.log("started"));
queue.on("error", err => console.log("queue error:", err));
queue.close();
```

When is redis running this test code gracefully ends. When is redis not running then this will emit bunch of errors and never ends even after I run redis again:
```
queue error: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```
I also tried to run it without `queue.close` while was redis running, then turn off redis and call `queue.close` and then turn on redis again and it does not closes.

When I try to run queues, then turn off redis it will print error messages, then turn on redis again and call `queue.close` it will gracefully end.

## Bull version
3.10.0

**Comment by theclive** [comment]
I am experiencing something similar, if I subscribe to the client events and pass in my own instance of ioredis, upon `queue.close()`, I experience the following debug output:

```
2019-10-08T14:05:20.693Z - debug:    Redis queue: Disconnected from Redis
2019-10-08T14:05:20.693Z - debug:    Redis queue: Connection to Redis has been terminated, and no more reconnections will be made
2019-10-08T14:05:20.697Z - debug:    Redis queue: Connected to Redis
```

Here is the code for creating my queue connection:
```javascript
    const connection = new RedisParam(getConnectionOptionsParam(logMsgPrefix))

    connection.on('connect', () => {
      logger.log('debug', `${logMsgPrefix}: Connected to Redis`)
    })

    connection.on('error', error => {
      logger.log(
        'error',
        `${logMsgPrefix}: Error in Redis client: %s`,
        error.message,
        { error }
      )
    })

    connection.on('end', () => {
      logger.log(
        warnOnDisconnect ? 'warn' : 'debug',
        `${logMsgPrefix}: Connection to Redis has been terminated, and no more reconnections will be made`
      )
    })

    connection.on('close', () => {
      logger.log('debug', `${logMsgPrefix}: Disconnected from Redis`)
    })

```

if I subsequently call `connection.disconnect()`, then I see the following logs:
```
2019-10-08T14:05:20.708Z - debug:    Redis queue: Disconnected from Redis
2019-10-08T14:05:20.708Z - debug:    Redis queue: Connection to Redis has been terminated, and no more reconnections will be made
```

Does bull call `.disconnect()` on `queue.close()`, or does it just sever the connection?  If it just severs the connection then the Redis retry strategy will cause it to reconnect.

**Comment by rcates1** [comment]
I'm running into this as well, using ioredis.

I'm creating my queue using an existing redis client and subscriber, while creating a new redis connection each time I create a queue.

When I call `queue.close()`, I've noticed that this function runs shortly thereafter, triggering a redis reconnection:

```javascript
/**
 * Returns a promise that resolves when active jobs are finished
 *
 * @returns {Promise}
 */
Queue.prototype.whenCurrentJobsFinished = function() {
  return new Promise((resolve, reject) => {
    if (!this.bclientInitialized) {
      // bclient not yet initialized, so no jobs to wait for
      return resolve();
    }

    //
    // Force reconnection of blocking connection to abort blocking redis call immediately.
    //
    const forcedReconnection = redisClientDisconnect(this.bclient).then(() => {
      return this.bclient.connect();
    });

    Promise.all(this.processing)
      .then(() => {
        return forcedReconnection;
      })
      .then(resolve, reject);

    /*
    this.bclient.disconnect();
    this.bclient.once('end', function(){
      console.error('ENDED!');
      setTimeout(function(){
        this.bclient.connect();
      }, 0);
    });

    /*
    var stream = this.bclient.connector.stream;
    if(stream){
      stream.on('finish', function(){
        console.error('FINISHED!');
        this.bclient.connect();
      });
      stream.on('error', function(err){
        console.error('errir', err);
        this.bclient.connect();
      });
      this.bclient.connect();
    }
    */
    //this.bclient.connect();
  });
};
```

The reason I'm here is implementing a cancel capability. I was closing the queue before all active jobs had finished, so I thought hey, I'll just spin until active jobs are finished, THEN I'll close the queue and this code won't run because active jobs won't be triggering bull's `Queue.prototype.whenCurrentJobsFinished` handler, which is restarting redis.

As it turns out, implementing that like so doesn't stop from `Queue.prototype.whenCurrentJobsFinished` from being called:

```javascript
if (shouldCancel) {
       ...
        await queue.pauseQueue();

	let jobCounts = await queue.getJobCount();

	while (jobCounts.active > 0) {
		jobCounts = await new Promise(async (resolve, reject) => {
		setTimeout(async () => {
			return resolve(await queue.getJobCount());
		}, 2500);
	});
}

await queue.cleanQueue();
await queue.closeQueue();
```

With that being the case, I'm thinking to myself okay maybe I'll just have to close all redis connections myself after the fact? I don't know...

I would definitely appreciate any insight into why this is happening and what the correct way of handling this situation would be.

Thanks in advance!

**Comment by dobesv** [comment]
I think a possible fix would be:

```
Queue.prototype.whenCurrentJobsFinished = function () {
  if (!this.bclientInitialized) {
    // bclient not yet initialized, so no jobs to wait for
    return Promise.resolve();
  }

  //
  // Force reconnection of blocking connection to abort blocking redis call immediately.
  //
  const forcedReconnection = redisClientDisconnect(this.bclient).then(() => {
    if(!this.closing)
      return this.bclient.connect();
  });

  return Promise.all(this.processing).then(() => {
    return forcedReconnection;
  });
};

```

**Comment by julien-me** [comment]
I'm having the same issue. Has this been fixed?

**Comment by FedericoMassaioli** [comment]
News on this issue?
Queue.close() blocking forever when Redis is unreachable significantly complicates a graceful shutdown procedure.

**Comment by throrin19** [comment]
Same problem here, Any solution to bypass this problem ?

**Comment by misos1** [comment]
Seems this part is still not fixed:

> I also tried to run it without `queue.close` while was redis running, then turn off redis and call `queue.close` and then turn on redis again and it does not closes.

Try to run this while is redis running:

``` js
let Queue = require("bull");
let queue = new Queue("queue");
queue.process(_job => console.log("started"));
queue.on("error", err => console.log("queue error:", err));
setTimeout(function()
{
	queue.close();
}, 10000);
```

Then within 10 seconds turn redis off and this "application" never ends.

**Comment by manast** [comment]
I released a new fix that in my tests fixes your last example @misos1

**Comment by misos1** [comment]
I tested with 4.5.5 and it still did not terminate:
```
queue error: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
closing
Error: Connection is closed.
    at Redis.connectionCloseHandler (node_modules/ioredis/built/redis/index.js:367:24)
    at Object.onceWrapper (node:events:510:26)
    at Redis.emit (node:events:390:28)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
```

**Comment by manast** [comment]
@misos1 can you provide a complete test code? It is working in my tests.

**Comment by misos1** [comment]
This will close queue 10 seconds after start:

``` js
let Queue = require("bull");
let queue = new Queue("queue");
queue.process(_job => console.log("started"));
queue.on("error", err => console.log("queue error:", err));
setTimeout(function()
{
  console.log("closing");
  queue.close();
}, 10000);
```

1. Turn on redis.
2. Run the above-mentioned program.
3. Turn off redis (within 10 seconds from the previous step).
4. Wait 10 seconds (or more).

**Comment by manast** [comment]
@misos1 I get the error messages but the queue closes and the process terminates with the latest version, can you please try the latest version again? 4.6.2

**Comment by Tinadim** [comment]
I'm having a similar issue when trying to close the queue. I was doing some debugging inside bull's code - specifically in the function `redisClientDisconnect` inside `queue.js` and from what I observed, this is never called in my test: 

```
 // queue.js
 ...
 client.once('end', __resolve); <----------- promise is never resolving
```

I'm using latest version of bull queue (4.7.0) and ioredis (4.28.5). Not sure If I'm doing something wrong.

**Comment by rpmccarter** [comment]
Hello! I'm experiencing the same issue.

- bull: `4.11.3`
  - ioredis: `5.3.2` 
- node: `18.16.1` | `19.9.0` | `20.5.1`

I used @misos1 's repro steps and was able to produce the same result. Any help appreciated!

**Comment by rpmccarter** [comment]
I've narrowed down the source of this bug, but I don't know enough about `bull` to submit a PR. Hoping this info can help with a fix!

In the `Queue.prototype.close` function, the following promise is returned:
```
return (this.closing = this.isReady()
  .then(this._initializingProcess)
  .catch(() => {
    isReady = false;
  })
  .then(() => isReady && this.pause(true, doNotWaitJobs))
  .finally(() => this._clearTimers())
  .then(() => {
    if (!this.childPool) {
      return;
    }
    const cleanPromise = this.childPool.clean().catch(() => {
      // Ignore this error and try to close anyway.
    });
    if (doNotWaitJobs) {
      return;
    }
    return cleanPromise;
  })
  .then(
    async () => this.disconnect(),
    err => console.error(err)
  )
  .finally(() => {
    this.closed = true;
    utils.emitSafe(this, 'close');
  }));
```

However, an error is occurring at `this.pause(true, doNotWaitJobs)`. Specifically, the `forcedReconnection` function is erroring at `this.bclient.connect()` with `Error: Connection is closed.`

Because this error is never caught, the two subsequent `.finally()` methods are executed, but the subsequent `.then()` methods are not. The relevant missing piece here is the `() => this.disconnect()`, as this is what prevents the redis client from trying to reconnect indefinitely. (Because of this, I found that a hacky workaround is to call `myQueue.disconnect()` immediately before `myQueue.close()`.)

The only "fix" I could find was to add an empty`.catch` after the erroring function:

```
     .then(() => isReady && this.pause(true, doNotWaitJobs))
+    .catch(() => {})
     .finally(() => this._clearTimers())
```

**Comment by melalj** [comment]
Any update on this?

**Comment by misos1** [comment]
> Any update on this?

This is already closed so probably resolved. What update would you expect?

**Comment by misos1** [comment]
> Any update on this?

Ehm sorry, I mistaken this for som other issue. Seems this is still unresolved.

**Comment by misos1** [comment]
@manast It is still the same. Bull 4.11.3 node v20.5.1.

``` js
let Queue = require("bull");
let queue = new Queue("queue");
queue.process(_job => console.log("started"));
queue.on("error", err => console.log("queue error:", err));
setTimeout(function()
{
  console.log("closing");
  queue.close();
}, 30000);
```

1. Turn on redis.
2. Run the above-mentioned program.
3. Turn off redis (within 30 seconds from the previous step).
4. Wait 5 minutes.

You will get errors and the process will never end (expected outcome is that the process gracefully ends in finite time):

```
queue error: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
closing
Error: Connection is closed.
    at EventEmitter.connectionCloseHandler (node_modules/ioredis/built/Redis.js:207:28)
    at Object.onceWrapper (node:events:629:26)
    at EventEmitter.emit (node:events:514:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
```

**Comment by manast** [comment]
I have tested with the proposed fix and it works: https://github.com/OptimalBits/bull/pull/2673
