### ISSUE TITLE
Missing lock for job failed when closing queue and job takes more than 30 seconds to complete [BUG]

### ISSUE THREAD

**Issue by misos1** [OptimalBits/bull#1415]
## Description

Seems job which takes more than 30 seconds to complete is not properly finished when is queue closing and in next runs is announces as stalled. Additionally it takes another 5 seconds to gracefully exit after is queue closed which does not happen when job takes less than 30 seconds to complete.

## Minimal, Working Test code to reproduce the issue.

``` node js
let Promise = require("bluebird");
let Queue = require("bull");
let queue = new Queue("queue");
queue.process(10, _job => Promise.delay(40000));
queue.on("error", (...errs) => console.log(new Date(), "queue error:", ...errs.reverse()));
queue.on("stalled", job => console.log(new Date(), "stalled", job.id));
(async function()
{
	let job = await queue.add({});
	console.log(new Date(), "added", job.id);
	await Promise.delay(1000);
	await queue.close();
	console.log(new Date(), "closed");
})();
process.on("exit", () => console.log(new Date(), "exiting"));
```

Possible output after few runs:
```
2019-08-04T21:14:37.362Z added 1
2019-08-04T21:15:17.379Z queue error: Error processing job Error: Missing lock for job 1 failed
    at Object.finishedErrors (node_modules/bull/lib/scripts.js:182:16)
    at node_modules/bull/lib/job.js:268:31
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
2019-08-04T21:15:17.382Z closed
2019-08-04T21:15:22.382Z exiting
```
```
2019-08-04T21:15:24.398Z added 2
2019-08-04T21:16:04.414Z queue error: Error processing job Error: Missing lock for job 2 failed
    at Object.finishedErrors (node_modules/bull/lib/scripts.js:182:16)
    at node_modules/bull/lib/job.js:268:31
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
2019-08-04T21:16:04.416Z closed
2019-08-04T21:16:09.421Z exiting
```
```
2019-08-04T21:16:11.091Z added 3
2019-08-04T21:16:11.096Z stalled 1
2019-08-04T21:16:51.106Z queue error: Error processing job Error: Missing lock for job 1 failed
    at Object.finishedErrors (node_modules/bull/lib/scripts.js:182:16)
    at node_modules/bull/lib/job.js:268:31
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
2019-08-04T21:16:51.107Z queue error: Error processing job Error: Missing lock for job 3 failed
    at Object.finishedErrors (node_modules/bull/lib/scripts.js:182:16)
    at node_modules/bull/lib/job.js:268:31
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
2019-08-04T21:16:51.108Z closed
2019-08-04T21:16:56.108Z exiting
```

## Bull version
3.10.0
## Additional information
Nothing which I described happens if I change it to 20 seconds:
``` node js
queue.process(10, _job => Promise.delay(20000));
```
```
2019-08-04T21:29:58.423Z added 1
2019-08-04T21:30:18.439Z closed
2019-08-04T21:30:18.439Z exiting
```
```
2019-08-04T21:30:23.516Z added 2
2019-08-04T21:30:43.531Z closed
2019-08-04T21:30:43.532Z exiting
```
```
2019-08-04T21:30:45.734Z added 3
2019-08-04T21:31:05.750Z closed
2019-08-04T21:31:05.750Z exiting
```

**Comment by guidodizi** [comment]
Similar case here

**Comment by inn0vative1** [comment]
I am having a similar issue here. In my case jobs do not even take 30 seconds. I have to types of jobs, one completes very quickly (milliseconds) and another takes a bit longer (still relatively short, a second or two). I find that this error gets thrown more often with the longer running jobs.
The job seems to complete successfully, but this error occurs when the on('complete') callback is called. 
` Missing lock for job fecf814b-8f54-44bf-ab76-6992f11048ac delayed
    at Object.finishedErrors (node_modules/bull/lib/scripts.js:182:16)
    at multi.exec.then.results (node_modules/bull/lib/job.js:293:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by Fossil01** [comment]
Same issue.

**Comment by guidodizi** [comment]
My issue was actually coming from not returning an object on the processing of each queue. So by returning an object, even an empty object, i manage to avoid the `Missing lock for job` error.

Hope it helps!

**Comment by misos1** [comment]
@guidodizi maybe you could create another issue as it does not make much sense to throw such an error in case you are not returning object.

**Comment by yan-michael** [comment]
Same issue here

**Comment by yan-michael** [comment]
> My issue was actually coming from not returning an object on the `processing` of each job queue. So by returning an object, even an empty object, i manage to avoid the `Missing lock for job` error.
> 
> Hope it helps!

C

> My issue was actually coming from not returning an object on the `processing` of each job queue. So by returning an object, even an empty object, i manage to avoid the `Missing lock for job` error.
> 
> Hope it helps!

Hey! Can you elaborate on this?

**Comment by rj-david** [comment]
We are currently experiencing this now when deploying so we need to gracefully close the existing queue

**Comment by BogdanStanciu** [comment]
Same issue. I return a empty object in process method but it always return a `Missing lock for job {id} finished`

**Comment by cpu100** [comment]
What's the reason? Is redis overloaded?

**Comment by harshamv** [comment]
Has anyone solved this? Please share your solution.

**Comment by cpu100** [comment]
updated to the newest bull version. seems it solved.

**Comment by kodeine** [comment]
any updates on this i am on new version but getting the same error.

**Comment by cpu100** [comment]
@kodeine 
Is the CPU load too high when this error throws? If so, My solution is to read `/proc/loadavg` in the repeat process callback to determine whether the current CPU load is too high. If so, skip the processing part. Now my problem is completely solved.

**Comment by brianschardt** [comment]
I still have this issue on bullmq

**Comment by Niek** [comment]
This happens when there's a sync call taking all CPU. You either need to increase the `stalledInterval` or (much better) write your code in such a way that it doesn't block the main thread. See also: https://docs.bullmq.io/guide/workers/stalled-jobs

**Comment by misos1** [comment]
No, there is no sync call taking all cpu in my example. There is no high cpu load. Redis is not overloaded. There is probably some bug in the bull. To properly run my example you need to wait some minute until it prints "exiting" and gracefully exits. Output is still exactly the same with the newest bull 3.22.6.

@guidodizi
> My issue was actually coming from not returning an object on the `processing` of each job queue. So by returning an object, even an empty object, i manage to avoid the `Missing lock for job` error.

It does not make any difference when I change line with `queue.process...` to `queue.process(10, _job => Promise.delay(40000).then(() => ({})));`. Ensure that you are not returning an empty object immediately from the `queue.process` callback. You are supposed to return either a promise where the job will be finished after the promise is resolved or call `done` callback to signal that your job is finished. Returning an empty object immediately signals that your job is finished immediately - it is like if you return `Promise.resolve({})` and if you run things outside of job lifetime then I would say you do not require bull.

@Niek @cpu100 You are probably experiencing something different - see section "Important Notes" in readme.

**Comment by vanthome** [comment]
@misos1 was this issue now solved for you or not?

**Comment by manast** [comment]
it is still there, I am able to reproduce it, will try to fix is asap.

**Comment by vanthome** [comment]
Ahh, we are also suffering from this btw.

**Comment by manast** [comment]
@vanthome in what context? as this is reported it happens when closing a queue.

**Comment by vanthome** [comment]
oh, I just saw it... no. In our case it's related to `bull.remove()` when we want to remove completed jobs, we run into `Could not remove job repeat:393fadd48d6f8e0e1c87913ce6fb8ab8:1625661360000`

**Comment by loris** [comment]
Not sure if related, but could give more hints, on our end, we see once in a while (here its 13 times in 7 days), error `Missing lock for job repeat:...:... failed`.
FYI, the following repeat jobs are from different queues and have different handlers, but they are all very lightweight in term of workload (doing some fast mongo query every minute to check for any work to enqueue in bull). But, they tend to happen more often when our servers are doing lots of other stuff (ie, handling millions of other bull jobs).
Not sure if I should tweak some lockDuration or other property here

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/8362/124902497-46016980-dfe3-11eb-862f-1886fa7387ca.png">

**Comment by manast** [comment]
> oh, I just saw it... no. In our case it's related to `bull.remove()` when we want to remove completed jobs, we run into `Could not remove job repeat:393fadd48d6f8e0e1c87913ce6fb8ab8:1625661360000` and we observe high CPU load when this happens.

If you can create a separate issue with reproducible code I can look into it. By the way, why don't you use "removeOnComplete" ?

**Comment by vanthome** [comment]
We will try to tweak the `lockDuration`.

**Comment by manast** [comment]
@vanthome just to be clear, the error you are getting is probably a bug in Bull, tweaking the lockDuration may hide the bug but not resolve it. So if you manage to reproduce it or gain more insight please share it in a new issue.

**Comment by hgeldenhuys** [comment]
There in v 4.10.4 also

**Comment by thatMan3** [comment]
I have the same problem in  v4.10.4 . My process is similar to copying and compressing several gigabytes of files causing a high CPU load.

**Comment by manast** [comment]
@thatMan3 try using sandboxed processors, otherwise, the NodeJS event loop will not have a chance to run: https://docs.bullmq.io/guide/workers/sandboxed-processors

**Comment by misos1** [comment]
**This issue was already resolved. If you are able to run the provided test code without errors you have probably something different so please open a new issue.**

**Comment by chasdevs** [comment]
I'm hitting this with bullmq 4.12.0 and nestjs 10. We have a @Processor which calls `this.worker.close()` on application shutdown:
```ts
onApplicationShutdown(signal?: string): Promise<void> {
    this.logger.log(`Stopping queue processor on signal ${signal}`);
    return this.worker
        .close()
        .then(() => {
          this.logger.log('Queue processor stopped');
        })
  }
```

When I have a long-running (5 min) debug job that just awaits a Promise and does not block the event loop or do anything CPU-intensive, I get the following error:
```
LOG [DebugJob] Job still executing...
LOG [DebugJob] Printing message: Ducimus dolores rerum et fuga.
Error: Missing lock for job 1. failed
    at Scripts.finishedErrors (/.../packages/api/node_modules/bullmq/dist/cjs/classes/scripts.js:213:24)
    at Job.moveToFailed (/.../packages/api/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleFailed (/.../packages/api/node_modules/bullmq/dist/cjs/classes/worker.js:335:21)
    at async Worker.retryIfFailed (/.../packages/api/node_modules/bullmq/dist/cjs/classes/worker.js:535:24)
LOG [DefaultQueueProcessor] Queue processor stopped
```

**Comment by kareldonk** [comment]
I'm also getting the ` Error processing job Error: Missing lock for job 1 failed` quite often for long jobs. I'm using Bull with nestjs, and have `removeOnComplete` and `removeOnFail` set to true for the jobs. I also have nestjs configured to use a redis key prefix. Nestjs version is `10.0.1` and bull version is `4.11.3`.
The handler for the job completes successfully but after that bull has the lock issue, which causes the job to be retried.

**Comment by manast** [comment]
@kareldonk if the jobs are CPU intensive then most likely the worker is not able to renew the lock and the lock will expire producing said error.

**Comment by kareldonk** [comment]
@manast thanks, for now I was able to stop the error by increasing the `lockDuration` and `lockRenewTime` settings to a value a little higher than the expected completion time for most jobs.

**Comment by misos1** [comment]
I could just add that javascript is not appropriate for CPU intensive tasks (you are using cardboard to drive a nail).

**Comment by manast** [comment]
You can use sandboxed processors for CPU intensive tasks as they run on separate worker threads https://docs.bullmq.io/guide/workers/sandboxed-processors

**Comment by kareldonk** [comment]
@misos1 in my ideal world we would all be using C and C++. but here we are stuck with nodejs and python.

**Comment by manast** [comment]
@kareldonk This may be an over stretch but If there is a good WebSockets client library, then maybe something like this could be used for  heavy-duty work in C/C++: https://github.com/taskforcesh/bullmq-proxy

**Comment by godinja** [comment]
@chasdevs I'm also getting something very similar to your during a graceful shutdown of a worker. For anyone interested, I've opened an [issue here](https://github.com/taskforcesh/bullmq/issues/2258) in the BullMQ repo and have uploaded a minimal reproducible example to [this repository](https://github.com/godinja/bullmq-graceful-shutdown).

**Comment by misos1** [comment]
> @chasdevs and have uploaded a minimal reproducible example to [this repository](https://github.com/godinja/bullmq-graceful-shutdown).

It does not look minimal.

**Comment by godinja** [comment]
Well, in any case, there was a bug in BullMQ that prevented workers from renewing job locks while closing. BullMQ v4.12.8 has the fix. I'd imagine bull has this same bug?

**Comment by manast** [comment]
@godinja not necessarily as the code differs quite a lot regarding closing of workers and how the locks are renewed.
