### ISSUE TITLE
How to change priority in Queue?

### ISSUE THREAD

**Issue by hados99** [OptimalBits/bull#1417]
Is it possible to change job's priority?

I always add job with priority but clients want to change priority after job added (in waiting queue).

I could not find any functions about this. Is there any idea?

How about changing priority when job is in waiting queue (to be precise, in priority waiting queue)?

**Comment by manast** [comment]
There is no built-in way to change priority. The best you could do is to remove and add the same job with a different priority, but keep in mind that being a non atomic operation you could loose jobs in case of failure. This could be of course be implemented in a LUA script, but we do not have planed for this feature.

**Comment by hados99** [comment]
Thanks for comment and I fully understand not have planned.

I read addJob-6 LUA script and I think adding a job with priority works like this
https://github.com/OptimalBits/bull/blob/ba3e6c44b6f1e74f3cb1e8e4a65086798bcc8c92/lib/commands/addJob-6.lua#L87

1. add jobId to priority queue (zsets)
2. calculate jobId's order in priority queue
3. add jobId to waiting queue with order in priority queue

And my idea of changing priority is as below.
1. change priority of jobId in priority queue (maybe ZINCRBY?)
2. calculate jobId's order in priority queue
3. pop and push jobId to waiting queue with order in priority queue (maybe RPOPLPUSH?)

Does it make sense?

**Comment by hados99** [comment]
Wow, more convenient way!
I'll give it a try. Thanks!!

**Comment by abdolrhman** [comment]
@hados99 does it work ?
i want to implment that same feature .

**Comment by hados99** [comment]
@abdolrhman Sometimes it does not work but I couldn't debug at all
