### ISSUE TITLE
Getting "client.addJob is not a function" from bull in serverless environment

### ISSUE THREAD

**Issue by morajabi** [OptimalBits/bull#1418]
## Description
I'm trying to add a job to a queue, but I get this strange error. I tried reading through the source code, searching but didn't find out what could cause it. I'm building using Webpack and tried both bundling and external load. No luck.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
As soon as I know where it could come from I'll try to put together a mini repo.

## Bull version
v3.10.0

## Additional information
![CleanShot 2019-08-05 at 16 28 40](https://user-images.githubusercontent.com/12202757/62466796-6f863a80-b7a7-11e9-84c8-99b415f4faec.png)

**Comment by stansv** [comment]
I suppose your real Bull version is 3.10.0.

The `addJob` is a wrapper function on `ioredis` instance that should be automatically created with `client.defineCommand()`. Commands are lua scripts bundled in Bull package. I suppose that your deployed artifact doesn't include these scripts.

https://github.com/OptimalBits/bull/blob/develop/lib/commands/index.js#L43

**Comment by morajabi** [comment]
That was the issue @stansv!

For people coming later, if you're on ZEIT Now v2, include this in your `now.json` config to include `*.lua` files:

```
{
  "builds": [
    {
      "src": "lambda.js",
      "use": "@now/node",
      "config": {
        "includeFiles": [
          "**/*.lua",
          "../node_modules/bull/lib/commands/*.lua",
          "./node_modules/bull/lib/commands/*.lua"
        ]
      }
    }
  ]
}
...

**Comment by mrfsbDev** [comment]
Any suggestion?
I have the same problem and I'm not using Zeit Now

**Comment by JannikZed** [comment]
I don't fully understand the core issue here - I'm facing the same problem using Serverless with Typescript. Why is the Bull package not bundled completely?

**Comment by manast** [comment]
> I don't fully understand the core issue here - I'm facing the same problem using Serverless with Typescript. Why is the Bull package not bundled completely?

Cannot answer a "why" when bull is bundled perfectly. It is a matter on configure serverless correctly as @morajabi pointed out for ZEIT.

**Comment by JannikZed** [comment]
For everybody looking for a Solution for the serverless framework and AWS Lambda: 
I could solve it by using the plugin serverless-bundle and directly adding bull as external:
```
custom:
  bundle:
    externals:
      - bull 
```
https://github.com/AnomalyInnovations/serverless-bundle#package-specific-config
