### ISSUE TITLE
The event 'global:removed' is never triggered. 

### ISSUE THREAD

**Issue by GalenWong** [OptimalBits/bull#1421]
## Description
I was attempting to use the `global:removed` event listener but found that the event is never triggered. I attempted to find it in the source code and see that it does not seem to be emitted anywhere. 

## Minimal, Working Test code to reproduce the issue.
```js
// provider.js
const Queue = require('bull');
const newQ = new Queue('test bug', 'redis://localhost:8888');

newQ.add({ job: 'provider sent a job with ID 1' }, { jobId: 1 });
console.log('job added');

newQ.on('global:removed', (jobID) => {
    console.log(jobID, 'is removed');
});
```

After `provider.js` is executed, we execute the following consumer code.
```js
// consumer.js
const Queue = require('bull');
const newQ = new Queue('test bug', 'redis://localhost:8888');

(async () => {
    const job = await newQ.getJob('1');
    console.log(job.data);
    await job.remove();
    console.log('remove success');
})();
```

### Expected Behavior
- `provider.js` should log
  ```
  job added
  1 is removed
  ```
- `consumer.js` should log
   ```
   { job: 'provider sent a job with ID 1' }
   remove success
   ```
### Actual Behavior 
- `provider.js` logs
  ```
  job added
  ```
  **`global:removed` is never triggered**
- `consumer.js` logs
   ```
   { job: 'provider sent a job with ID 1' }
   remove success
   ```
## Bull version
bull@3.10.0

**Comment by stansv** [comment]
Yes, only these global:* events are supported in bull v3:

- global:active
- global:completed
- global:drained
- global:failed
- global:paused
- global:progress
- global:resumed
- global:stalled
- global:waiting

The `global:removed` is added currently in next major version, which should be released soon.
