### ISSUE TITLE
[Question] Job executed many times on clustered setup

### ISSUE THREAD

**Issue by nosuchip** [OptimalBits/bull#1423]
Taking as example [code from documentation](https://www.npmjs.com/package/bull#cluster-support), also provided below. Maybe I missed something important in docs, but here I see that each job executed by each worked in cluster, i.e. 8 times. I am a bit confused as expected that one job will be executed only once. How could I achieve this?

I tried to play with lock `lockDuration`, increased to `2000` - for such simple jobs it more the enough, but still see that jobs executed almost once per worker.

```
var
  Queue = require('bull'),
  cluster = require('cluster'),
  counter = 0;
 
var numWorkers = 8;
var queue = new Queue("test concurrent queue");
 
if(cluster.isMaster){
  for (var i = 0; i < numWorkers; i++) {
    cluster.fork();
  }
 
  cluster.on('online', function(worker) {
    // Lets create a few jobs for the queue workers
    for(var i=0; i<20; i++){
      queue.add({foo: 'bar'});
    };
  });
 
  cluster.on('exit', function(worker, code, signal) {
    console.log('worker ' + worker.process.pid + ' died');
  });
}else{
  queue.process(function(job, jobDone){
    counter++;
    console.log("Job done by worker", cluster.worker.id, job.id, counter);
    jobDone();
  });
}
```

**Comment by manast** [comment]
The example above creates 20 * 8 = 160 jobs. Jobs are only processed once. Is not the behaviour you get?. Not sure what you want to achieve with the lockDuration setting.

**Comment by nosuchip** [comment]
@manast I am not sure that jobs actually processed once. Please check updated code. I added `counter` field that is increased during each job processing. I see that it increased far behind `20`. But, if your works correct and each job executed only once, its maximum value should be not greater then 20.

**Comment by stansv** [comment]
@nosuchip maybe you want to create jobs only once and not on each `online` event? Move 2nd for loop just immediately inside `if(cluster.isMaster) {}` block.

**Comment by nosuchip** [comment]
Ohhh, my bad! Thank you @stansv.
