### ISSUE TITLE
Error when built with pkg

### ISSUE THREAD

**Issue by quaj** [OptimalBits/bull#1424]
Hello, i have a problem with bull when running in `pkg`

[#752](https://github.com/zeit/pkg/issues/752)
Seem like problem from `pkg` but still open here? Any suggest?

```
(node:68192) UnhandledPromiseRejectionWarning: TypeError: queue.client.updateDelaySet is not a function
    at Object.updateDelaySet (/snapshot/queue-3g/node_modules/bull/lib/scripts.js:345:25)
    at Queue.updateDelayTimer (/snapshot/queue-3g/node_modules/bull/lib/queue.js:819:6)
    at _initializingProcess.isReady.then.then (/snapshot/queue-3g/node_modules/bull/lib/queue.js:343:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:68192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either)
(node:68192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, p.
```

**Comment by stansv** [comment]
Looks like this is the same as in https://github.com/OptimalBits/bull/issues/1418

**Comment by quaj** [comment]
wow, it fixed, many tks @stansv

**Comment by lluiscab** [comment]
Sorry, to ask, but @andepzai could you share your pkg config?

I've set mine to 
```
{
  "pkg": {
    "assets": [
      "**/*.lua",
      "../node_modules/bull/lib/commands/*.lua",
      "./node_modules/bull/lib/commands/*.lua"
    ]
  },
}
```

With the following command 
```
pkg . -t node12-alpine-x64 --output app.bin
```

But I'm still getting the error
```
TypeError: undefined is not a function
    at Object.updateDelaySet (/snapshot/dist/dist/index.js)
    at Queue.updateDelayTimer (/snapshot/dist/dist/index.js)
    at /snapshot/dist/dist/index.js
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by mrfsbDev** [comment]
any suggestion?
I have the same problem and I'm not using Zeit Now

**Comment by i-ce-fish** [comment]
> Sorry, to ask, but @Andepzai could you share your pkg config?
> 
> I've set mine to
> 
> ```
> {
>   "bin": "dist/index.js",
>   "pkg": {
>     "assets": [
>       "**/*.lua",
>       "../node_modules/bull/lib/commands/*.lua",
>       "./node_modules/bull/lib/commands/*.lua"
>     ]
>   },
> }
> ```
> 
> With the following command
> 
> ```
> pkg . -t node12-alpine-x64 --output app.bin
> ```
> 
> But I'm still getting the error
> 
> ```
> TypeError: undefined is not a function
>     at Object.updateDelaySet (/snapshot/dist/dist/index.js)
>     at Queue.updateDelayTimer (/snapshot/dist/dist/index.js)
>     at /snapshot/dist/dist/index.js
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> ```

it is worked , thank you for fix my problem
