### ISSUE TITLE
question about jobs

### ISSUE THREAD

**Issue by moeinrahimi** [OptimalBits/bull#1427]
how bull calls delayed jobs? do you use settimeout for this purpose ? can I add a delayed job for 2 months later?

**Comment by stansv** [comment]
Yes and yes, every Bull worker looks for the nearest delayed job on startup, then every 5 seconds (default `guardInterval`), and also when new delayed job is added. setTimeout() is used to wake up exactly at the moment of time when the next such job is scheduled, and as usual workers try to acquire a job. You can delay for any amount of time. If no bull workers were online at the moment time the job was scheduled, the job will be processed later at once any worker us up.
