### ISSUE TITLE
Repeatable completed jobs are not clearing out

### ISSUE THREAD

**Issue by moltar** [OptimalBits/bull#1429]
## Description

It looks like repeatable jobs are not automatically clearing from completed list for some reason. I have a job that runs every minute and it really fills up Redis.

## Minimal, Working Test code to reproduce the issue.

Code is not basic, and hard to refactor for a good example. But every queue uses the same setting and all other queues clear out, except the repeatable one.

## Bull version

3.9.1

## Additional information

N/A

**Comment by manast** [comment]
keep in mind that if it is difficult for you to create a test case that demonstrates the issue it is actually even more difficult for me to do it...

**Comment by stansv** [comment]
Tested on 3.9.1

```
import Bull from "bull";

const test = async () => {

  const queue = new Bull("my-queue");

  queue.add({ foo: "bar" }, {
    repeat: {
      cron: "* * * * * *"
    },
    removeOnComplete: true
  });

  queue.process(async (job) => {
    console.log("Processing job " + job.id);
    await new Promise((resolve, reject) => { setTimeout(resolve, 500); });
    console.log("Completed job " + job.id);
  })

};

test();
```

Works flawlessly, jobs are removed as expected; `removeOnFail` also works.

Could you please post here contents of one of these undeleted jobs? There should be keys of type `HASH`. For example,

```
HSCAN bull:my-queue:repeat:47f4767cb7f370f8d7ee905de54cc0a8:1565942846000 0 COUNT 10000
                    ^ job id                                            ^
```

**Comment by moltar** [comment]
```json
{
  "id": "repeat:81f4b91a20baeebcad3503743cded6d3:1565964600000",
  "name": "__default__",
  "data": {},
  "opts": {
    "repeat": {
      "count": 1004,
      "every": 60000
    },
    "jobId": "repeat:81f4b91a20baeebcad3503743cded6d3:1565964600000",
    "delay": 59994,
    "timestamp": 1565964540006,
    "prevMillis": 1565964600000,
    "attempts": 1
  },
  "progress": 0,
  "delay": 0,
  "timestamp": 1565964540006,
  "attemptsMade": 0,
  "stacktrace": [],
  "returnvalue": [],
  "finishedOn": 1565964600027,
  "processedOn": 1565964600002
}
```

**Comment by moltar** [comment]
```json
{
  "data": "{}",
  "timestamp": "1565965860017",
  "delay": "59983",
  "opts": "{\"repeat\":{\"count\":4,\"every\":60000},\"jobId\":\"repeat:81f4b91a20baeebcad3503743cded6d3:1565965920000\",\"delay\":59983,\"timestamp\":1565965860017,\"prevMillis\":1565965920000,\"attempts\":1}",
  "name": "__default__",
  "priority": "0"
}


{
  "name": "__default__",
  "delay": "0",
  "priority": "0",
  "returnvalue": "[]",
  "timestamp": "1565965800007",
  "finishedOn": "1565965860035",
  "opts": "{\"repeat\":{\"count\":3,\"every\":60000},\"jobId\":\"repeat:81f4b91a20baeebcad3503743cded6d3:1565965860000\",\"delay\":59993,\"timestamp\":1565965800007,\"prevMillis\":1565965860000,\"attempts\":1}",
  "processedOn": "1565965860004",
  "data": "{}"
}
```

**Comment by stansv** [comment]
Please use `removeOnComplete` option to clear jobs automatically.
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd

Your another queues should have this option set of jobs are removed after complete there.

**Comment by moltar** [comment]
Yeah, I need to investigate more. But the thing is, that I have just a single code path (factory) that creates queues. And they all share the same settings. All other queues clear automatically, and just that one, that has repeated jobs does not.

It is possible that there is maybe a bug somewhere in my code.

I will investigate. Let's close the issue now, as you clearly demonstrated that it works by default.

I will look at it in a bit and come back, if I find something wrong with bull.

Thank you for your help and attention!

**Comment by stansv** [comment]
@moltar great, feel free to reopen if you'd have more questions. As I know, jobs can only be removed by Bull with either removeOnComplete/removeOnFail or explicit job.remove().
