### ISSUE TITLE
Need a simple working example

### ISSUE THREAD

**Issue by realharry** [OptimalBits/bull#1435]
## Description

I was looking for some simple task queue library (for my typescript project), and when I stumbled upon this project, I thought it was perfect. After spending a few hours today, however, I still could not make a very simple "hello world" example work. I suspect that obviously I'm missing something _very obvious._

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

```javascript
import Bull from 'bull';

const id = 'abc-xyz';
const cb1 = (job: Bull.Job, done: Bull.DoneCallback) => {
  console.log(`callback 1 called for queue: ${id}`);

  const jobId = job.id;
  const jobData = job.data;
  console.log(`jobId = ${jobId}; jobData = ${jobData}`);

  done();
};

const queue = new Bull(id, 'redis://localhost:6379');
queue.process(cb1).then(() => {
  console.log('job processed');
});

setTimeout(() => {
  queue.add(id, { item: 'item 1' }).then((job) => {
    console.log(`job added`);
  });
}, 1000);
```

This code "hangs" after printing out "job added".

## Bull version

3.10.0

**Comment by realharry** [comment]
I tried many different variations, e.g., with or without done(), putting process() before or after add(), etc. Nothing really worked for me. A complete simple example will greatly alleviate this kind of unnecessary pain for the developers new to the library. As I indicated, I'm most likely missing something very obvious, but I have no way to figure that out myself without a good simple example or simple instructions, without having to dig into the source code.

**Comment by stansv** [comment]
Hi! Try to remove `id` from `add()` call. With id you define a job type, what means that you enable named processors feature. You can add multiple processors to single Queue instance with different names and Bull will look for matching processor.

https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueprocess

Try to add some event handling and you'll see your job immediately fails with "Missing process handler for job type" because there's no processor with that id. Another change to make it work is to add `id` to process call.

```
   queue.on("completed", (job, result) => {
        console.log(`Completed: Job ${job.id} completed with result ${JSON.stringify(result)}`);
    });

   queue.on("failed", (job, error) => {
        console.log(`Failed: Job ${job.id} failed with error ${error}`);
    });
```

**Comment by realharry** [comment]
Ah cool. Thanks very much @stansv That worked. And, thanks very much for the tips! I saw that event handler examples earlier, but I was thinking I woulnd't need it until I work on "real work". That was my big mistake. :) I'll close this ticket since I already opened another (related) one. Thanks!
