### ISSUE TITLE
Job state semantics not very clear

### ISSUE THREAD

**Issue by realharry** [OptimalBits/bull#1438]
## Description

A job can in be in one of a number of (mutually exclusive?) states. But, it's not very clear from the documentation what this states mean. For example, what's the difference between waiting/wait and active states? When does a waiting job become active? When does a job get into a "stuck" state? Is a job automatically "completed" when we call `done()`? Or, should we explicitly transition it to "completed" using `moveToCompleted()`? Etc. etc.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

I could not find any precise information as to what these states mean and how jobs transition from one state to another.

## Additional information

The relevant doc: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#jobgetstate

**Comment by manast** [comment]
Please check https://optimalbits.github.io/bull/ "A job's lifecycle".
