### ISSUE TITLE
Allow a custom job lock key

### ISSUE THREAD

**Issue by vilic** [OptimalBits/bull#1441]
## Description

In my case I need jobs that belong to, e.g., a specific user to be processed one by one. 

Allow a custom job lock key seems to be an easy solution.

BTW, why some of those uses `queue.toKey(jobId) + ':lock'` while some uses `job.lockKey()`

```js
  extendLock(queue, jobId) {
    return queue.client.extendLock([
      queue.toKey(jobId) + ':lock',
      queue.keys.stalled,
      queue.token,
      queue.settings.lockDuration,
      jobId
    ]);
  },

  releaseLock(queue, jobId) {
    return queue.client.releaseLock([
      queue.toKey(jobId) + ':lock',
      queue.token
    ]);
  },

  takeLock(queue, job) {
    return queue.client.takeLock([
      job.lockKey(),
      queue.token,
      queue.settings.lockDuration
    ]);
  },
```

**Comment by stansv** [comment]
Yes, such feature was already requested (#1383) and probably would be helpful for some users. But in fact this is hard to implement.
You're requesting to change a fundamental thing on which internal Bull algorithms rely. Suppose you have multiple workers or set concurrency > 1 on a single worker. First, existing lock won't prevent Bull from taking next job from a queue. If two jobs are active and sharing the same lock, the lock would be removed once one of these jobs complete, and second job, still having active state, would be marked as stalled and retried. But if I understand your case correctly you do not want to process two or more jobs for a specific user in parallel. OK, if you'd add a check so we won't take next job from queue if lock exists, the queue would stuck: you cannot simply skip a job at the head of queue, and try take 2nd, 3rd etc. It make things complex and I'm afraid this is out of functionality Bull can offer.

**Comment by vilic** [comment]
@stansv I see, thanks for the explaination.
