### ISSUE TITLE
Bug in the main Queue factory with opts

### ISSUE THREAD

**Issue by Somebi** [OptimalBits/bull#1444]
You have a bug here:
https://github.com/OptimalBits/bull/blob/67206073c07d677ed3782405daf49bd69100b4fc/lib/queue.js#L101

If url is undefined and opts provided, then opts gets overwritten by url and further down, opts filled with blank object because of that. Right here:

https://github.com/OptimalBits/bull/blob/67206073c07d677ed3782405daf49bd69100b4fc/lib/queue.js#L104

**Comment by stansv** [comment]
Thanks for the bug report, indeed better would be to check how many arguments are actually passed into this function as well. The queue.process function written better to handle this specific case.
https://github.com/OptimalBits/bull/blob/67206073c07d677ed3782405daf49bd69100b4fc/lib/queue.js#L592

**Comment by manast** [comment]
thanks for the report. However we wont fix this in 3.x branch since in the upcoming 4.x we have already solved this kind of awkwardness in parameter handling.
