### ISSUE TITLE
Ensure unique queue items

### ISSUE THREAD

**Issue by Ehesp** [OptimalBits/bull#145]
Is there anyway to ensure unique items? 

If I have a job that runs every 5 seconds which adds to the queue, it should only add if it doesn't already exist and is not completed - is this possible? At the moment we're having to assume the job completes within 5 seconds, which is risky.

Cheers

**Comment by Salakar** [comment]
Would also like to know if this is possible. Would save so much logic.

**Comment by manast** [comment]
Not sure that I understand your use case, but wouldn't this be quite straightforward to implement on top of bull? can't you just check if the queue has items waiting and if so do not add any more jobs?

**Comment by manast** [comment]
I just noticed that we lack proper documentation for the "get" methods:
```javascript
Queue##getWaiting = function();
Queue##getActive = function();
Queue##getDelayed = function();
Queue##getCompleted = function();
Queue##getFailed = function();
```

**Comment by Salakar** [comment]
Queues can have multiple types of items though like for example, 'Get Items for date 17-06-2015' as a name, is there anyway for those get methods you listed to also take filter options, like get Active where name contains X   or get waiting where name / data contains Y?

e.g
```
Queue.getWaiting({
    name: 'Some regexp filter on name', 
    data: 'some regex to match on data JSON' 
});
```

**Comment by manast** [comment]
unfortunately we do now have support for filters server side, this would need some LUA code since redis does not offer this kind of filtering support out of the box. So only way to do this right now is with client side filtering.
