### ISSUE TITLE
Unhandled Promise Rejection with Circular Structure in Sandbox Process

### ISSUE THREAD

**Issue by bobdercole** [OptimalBits/bull#1450]
## Description
I have an issue when a job promise rejects with an error-like object that contains a circular structure while using a sandbox process. Here is the warning:

> (node:203) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON at JSON.stringify (<anonymous>) at process.target._send (internal/child_process.js:735:23) at process.target.send (internal/child_process.js:634:19) at Promise.resolve.then.err (/application/node_modules/bull/lib/process/master.js:76:21) at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:203) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

I do not have this problem with promise function callback processes. It only occurs with sandbox processes.

## Minimal, Working Test code to reproduce the issue.

Here is my index file.

```typescript
myQueue.process(1, require.resolve('./processor'));
```

Here is my processor file. AugmentedError is just an extended Error class with one additional property, "extraProperty".

```typescript
export default async(): Promise<void> => {
	const error = new AugmentedError('hello');

	const foo = {
		'bar': {}
	};
	foo.bar = foo;

	error.extraProperty = foo;

	return Promise.reject(error);
};
```

You could just as easily reproduce this issue by rejecting with a plain object that has both a message property and some other property that contains a circular structure.

## Bull version
3.10.0

## Additional information
I am experiencing this issue because [Axios adds extra properties](https://github.com/axios/axios/blob/2ee3b482456cd2a09ccbd3a4b0c20f3d0c5a5644/lib/core/enhanceError.js) to the error object and it can sometimes include circular structures.

I am able to work around the issue by ensuring that my rejections only consist of a plain `Error` object with no extraneous properties. However, I feel like Bull should ensure that the payload is safe to send via [`process.send`](https://github.com/OptimalBits/bull/blob/develop/lib/process/master.js#L76).

I think that maybe this issue was introduced by https://github.com/OptimalBits/bull/pull/1062. This change made it so more than just a simple string could make it to `process.send`.

Thank you!

**Comment by manast** [comment]
I am not sure this is actually possible to fix in a sensible way. I do not think Bull should have a built in circular structure filter, or what do you propose as a solution?

**Comment by bobdercole** [comment]
I see. I suppose a built-in circular structure filter seems out of scope.

I found [this suggestion](https://github.com/nodejs/help/issues/1533#issuecomment-505640256) to use `v8.serialize()` and `v8.deserialize()`. However, I am not sure of the implications that come with implementing those here. I have limited experience with child processes.

At the very least, perhaps we could add a line in the Bull documentation regarding this caveat. I followed [these guidelines](https://github.com/OptimalBits/bull/blob/129c6e108ce67ca343c8532161d06742d92b651c/README.md#separate-processes) to convert my application from promise function callback processes to sandbox processes. I was a little confused to see this difference in behavior between them.

**Comment by manast** [comment]
interesting about v8 serializer, still seems to be pretty new, and I cannot find so much information about it. Could be something to consider in the future.

**Comment by phrozen** [comment]
Im having this particular issue using Hapi server framework and trying to send the request to the job via data params, apparently Hapi equests can't be serialized with JSON.stringify due to circular structure.

**Comment by manast** [comment]
@phrozen no workaround needed, just make sure you pass an object that can be serialized.
