### ISSUE TITLE
Redis connections count going very high (16K+) on AWS and Redis is crashing

### ISSUE THREAD

**Issue by shyamnath** [OptimalBits/bull#1453]
## Description
Redis Connections are going very high (16K+) on AWS Redis and are not dropping even when there is no job to process in the Queue. Have also tried to  reuse Redis connections but still not working  

## Minimal, Working Test code to reproduce the issue.

```
var Bull = require('bull');
var Redis = require('ioredis');

const PORT = 6379;
const HOST = 127.0.0.1;

var client = new Redis({
    port: PORT,
    host: HOST
});
var subscriber = new Redis({
    port: PORT,
    host: HOST
});

var opts = {
    createClient: function (type) {
        switch (type) {
            case 'client':
                return client;
            case 'subscriber':
                return subscriber;
            default:
                return new Redis({
                    port: PORT,
                    host: HOST
                });
        }
    }
}

const dataPayload = {
      'temp':30,
      'time':'9pm'
}

// Add data every 10 second for processing
setInterval(()=>{
const sensorQueue = new Bull('X', opts)
sensorQueue.add(dataPayload, {
            attempts: 3,
            removeOnComplete: true
        })
}, 10*1000);

//Data processor
var processData = new Bull('X', opts);
processData.process(3, async (job, done) => {
    //store data to DB 
    done();
});
        
```

## Bull version
3.10.0

## Additional information
I have a queue named X which is used to process data which is sent by mobile clients in JSON format, the queue is working fine for 3-4 day's and is able to process around 4000-5000 batches of data but after those Redis connections is increased upto 16K and the Queue stops as Redis starts throwing errors.
My code works as following- When a new job comes for processing I create a queue with the same name X and put the job in it, with each job being added the connection count to Redis is increasing and it's not going down even when the queue does not have any job to process

**Comment by stansv** [comment]
Hi! Here is the problem

```
setInterval(()=>{
const sensorQueue = new Bull('X', opts)
sensorQueue.add(dataPayload, {
            attempts: 3,
            removeOnComplete: true
        })
}, 10*1000);
```

Change to

```
const sensorQueue = new Bull('X', opts); // do not create new queue instance on every timer tick

setInterval(()=>{
// now connections do not leak
sensorQueue.add(dataPayload, {
            attempts: 3,
            removeOnComplete: true
        })
}, 10*1000);
```

**Comment by shyamnath** [comment]
> Hi! Here is the problem
> 
> ```
> setInterval(()=>{
> const sensorQueue = new Bull('X', opts)
> sensorQueue.add(dataPayload, {
>             attempts: 3,
>             removeOnComplete: true
>         })
> }, 10*1000);
> ```
> 
> Change to
> 
> ```
> const sensorQueue = new Bull('X', opts); // do not create new queue instance on every timer tick
> 
> setInterval(()=>{
> // now connections do not leak
> sensorQueue.add(dataPayload, {
>             attempts: 3,
>             removeOnComplete: true
>         })
> }, 10*1000);
> ```

Hi @stansv thank you for the quick reply. I get the data from REST API, and as there is no way to get an existing instance of Queue  (or I am not aware of) so I create a queue with the same name each time a new request is made, is there any other way of handling above situation

**Comment by stansv** [comment]
why you cannot define Queue in outer scope before setInterval/or your REST handler like in my example? Especially if name is always the same. You create queue one time when application starts and reuse every time you need to add a job.

**Comment by shyamnath** [comment]
> why you cannot define Queue in outer scope before setInterval/or your REST handler like in my example? Especially if name is always the same. You create queue one time when application starts and reuse every time you need to add a job.

Yes got it working thank you.
