### ISSUE TITLE
Unique JobId with Repeatable Job (cron)

### ISSUE THREAD

**Issue by PrestonR** [OptimalBits/bull#1457]
## Description

Hey Manast, had a question, so here's some context:

I'm experiencing duplicate jobs with cron schedules, no matter the jobId property. Given the following:

```
exports.serviceDataRequest = ( jobData, cron ) => {
    const { uniqueId } = jobData;
    return queue.serviceDataRequest.add(
        'serviceDataRequest',
        jobData,
        {
            attempts:DISPATCHER_MAX_RETRY,
            backoff:DISPATCHER_BACKOFF_OPTS,
            jobId:uniqueId,
            repeat: { cron },
            removeOnComplete: true,
            timeout: 60 * DEFAULT_TIMEOUT
        } );
};
```
Before I add the `repeat: { cron }` option, the job is properly blocked when multiples are added. Let's say the jobId is `438889e0-8171-11e9-8db6-1d3e8034a23d`

However, after adding the cron option, it appears that - if the job is long-lived - the new job is created on the cron schedule, instead of it being blocked by the uniqueness property. 

The resulting job data is:

```
{"repeat":{"count":1,"cron":"*/5 * * * *","jobId":"438889e0-8171-11e9-8db6-1d3e8034a23d"},"jobId":"repeat:01f2eca60dfb372434379e07daed197d:1568109600000","delay":55978228,"timestamp":1568053621772,"prevMillis":1568109600000,"attempts":5,"backoff":{"type":"fixed","delay":15000},"removeOnComplete":true,"timeout":3600000}
```

And it looks like my jobId gets copied into the repeat object. Is this a bug? If not...

So let's say the cron is every 5 minutes (`*/5 * * * *`). If the above job is running for 9 minutes, at the 5th minute, due to the cron schedule, I am seeing the behavior that another job runs at on schedule.

**_A duplicate scheduled job, however, is not created._**

Is this the intention? Simply:

1) jobId w/cron in delayed context means a duplicate job will **not** be scheduled/delayed
2) jobId at execution of cron, in an active context, means multiple executions might occur due to long-lived nature of some jobs, or depending on frequency of the cron

Do I have that correct? And is that the expectation?

## Bull version
~3.10.0

**Comment by manast** [comment]
I am not sure I understand what you are trying to achieve. So basically, a cron job will repeat according to the cron expression, every 5 minutes in your case. If you add other jobs with the same jobId and the same cron expression they will be ignored, otherwise they will add new repeatable jobs.

**Comment by PrestonR** [comment]
Sorry if I wasn't clear in my examples. I am trying to achieve the case you describe. I am experiencing what you describe. I suppose my confusion is when the job processes.

Yes I am seeing only 1 repeatable job added when I specify a jobId, but when the job is processed and is long-lived and it extends beyond the next execution of the cron job, it doesn't detect that the previous cron is still running, and so it creates the same job with the same data despite the jobIds being the same.

I think this example demonstrates that fact:

```
q.add('myCronJob', { foo: 'bar', fizz: 'buzz' }, { jobId: 1, repeat: { cron: '* * * * *' } }); // run every minute

q.process('myCronJob', 3, async (data) => {
    const wait = () => new Promise((resolve) => {
        setTimeout(() => resolve(), 2 * 60 * 1000);
        setInterval(() => console.log(`running job data with id: ${JSON.stringify(data)}`), 1000);
    }); // 2 min
    await wait();
});
```

There is a period of time where the processor is processing data from the same cron job. The interval that is printing the job data has two different repeatable Ids at this moment (between minute 2 and 3 I believe), for example:

```
repeat:b381601ee3b9e8615820977efb392864:1568064540000
repeat:b381601ee3b9e8615820977efb392864:1568064480000
```

I don't know if this is intended? Please let me know if I can help clarify further.

**Comment by PrestonR** [comment]
Oh, I understand the issue.

Once a cron job is scheduled, it doesn't drop itself from the delayed jobs and recreate. Some additional context:

I'm using 1 cron job to trigger the creation of multiple other cron jobs. But those secondary cron jobs have state changes that aren't getting picked up.

I see now that I'm misusing the cron job logic.

Thanks Manast!
