### ISSUE TITLE
How to reset count?

### ISSUE THREAD

**Issue by niftylettuce** [OptimalBits/bull#1458]
Not sure how to reset the count, e.g. if I call `queue.empty` it will clear the queue, but it won't reset the count of number of completed.  I'm guessing I have to do something manual like is done in tests?

**Comment by manast** [comment]
Empty only empties the jobs that are waiting for being processed, for removing completed jobs you should use "clean".

**Comment by niftylettuce** [comment]
@manast 	you the best, thanks! 🙏
