### ISSUE TITLE
If a repeatable job misses its scheduled time (due to server down time, etc) will it still run?

### ISSUE THREAD

**Issue by popcornAC** [OptimalBits/bull#1462]
If a repeatable scheduled job misses the time it was scheduled to run due to server downtown or other issues, will the job still run as soon as it is possible?

I'm running a heroku server that daily restarts, if for some reason the daily restart infringes on the time where a repeatable scheduled job may run, will the job run the moment the server comes back online?

**Comment by Igor-Lopes** [comment]
I use heroku for my app and we don't have any issues regarding repeatable, scheduled or failed jobs. If for some reason your server is down at the time scheduled, your job will run immediately after your server is started and connected to redis.

**Comment by popcornAC** [comment]
I see, thank you!
