### ISSUE TITLE
ETIMEDOUT error trying to connect to a Digitalocean managed Redis instance

### ISSUE THREAD

**Issue by TAnas0** [OptimalBits/bull#1464]
## Description
Trying to connect to a remote Redis instance, hosted on Digital Ocean fails with the following error:
```bash
....
(node:10035) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at Socket.<anonymous> (/root/gitlab/timer/node_modules/ioredis/built/redis/index.js:275:31)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:10035) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
....
```
## Code to reproduce
I tried instantiating my queue both using a connection string and separated parameters:
```js
var auditQueue = new Queue('audit', 'rediss://default:<my-password>@frontscan-timer-db-do-user-4570914-0.db.ondigitalocean.com:25061');
```

```js
var auditQueue = new Queue('audit', {redis: {port: 25061, host: 'frontscan-timer-db-do-user-4570914-0.db.ondigitalocean.com', password: '<unguessable-password>', username: 'default'}});
```

## Bull version
Bull version: v3.10.0
Redis server version: 5.0.4

## Additional information

I was working with a local dockerized Redis server before, and the connection was working fine.

Please note that Digital Ocean requires me to whitelist trusted sources of connection, which include my computer's IP address and another Linux instance hosted on DO in the same region. I tried my code on both environments and it failed in the same way.
Also, Digital Ocean only accepts connection over SSL for Redis instances, which is the reason behind the prefix `rediss://...`

Also worth noting that I can connect to the Redis instance, from both my computer and the DO droplet, using [redli](https://github.com/IBM-Cloud/redli):

```bash
redli --tls -h frontscan-timer-db-do-user-4570914-0.db.ondigitalocean.com -a <my-wonderful-password> -p 25061
```
I am not very Redis-savy, but I can provide further information about the Redis server since I have CLI access.

## Questions
1. I wasn't able to debug the error, and 'catch' the error in my code. Is the `UnhandledPromiseRejectionWarning` happening inside of BullJS? If so, how can I get more details?
2. Is the `rediss://...` prefix enough for BullJS to perform the connection over SSL, as required by DO?
3. What further information can I provide to help you help me?

**Comment by manast** [comment]
Bull uses https://github.com/luin/ioredis#readme for connecting to Redis, so you should try a simple ioredis example and if does not work you can open an issue on ioredis repo instead.

**Comment by ronalddddd** [comment]
For those looking for a solution with DO managed Redis, this worked for me: https://github.com/OptimalBits/bull/issues/1366#issuecomment-506734828

Basically remember to have `tls: {}` and increase connection timeout with `connectTimeout: 30000` in your `redis` queue config.

**Comment by BrunoQuaresma** [comment]
@ronalddddd do you have a sample of how to make it work? I'm still not getting it right :/

**Comment by manast** [comment]
@BrunoQuaresma are you getting issues connecting with Bull or also with plain ioredis? I would recommend you to first try to connect using ioredis directly, you can pass this connection to Bull for example. If it does not work with ioredis then please fill an issue in that repo instead.

**Comment by BrunoQuaresma** [comment]
Thanks! I was able to get it working after reading the ioredis docs:

```ts
new Queue(
  "video",
  "rediss://default:<password>@<host>:25061",
  {
    redis: {
      tls: {},
      connectTimeout: 30000,
    }
  }
);
```

**Comment by alexsds** [comment]
The same issue also with BullMQ and Digitalocean managed cache instances.
Need to add tls and connectTimeout.

```
BullModule.forRoot({
    connection: {
        host: process.env.CACHE_HOST,
        port: parseInt(process.env.CACHE_PORT, 10),
        username: process.env.CACHE_USERNAME,
        password: process.env.CACHE_PASSWORD,
        tls: {},
        connectTimeout: 30000,
    },
}),
```
