### ISSUE TITLE
Node v10.15.3. Async function gets second parameter as a callback

### ISSUE THREAD

**Issue by carlosdubus** [OptimalBits/bull#1465]
## Minimal, Working Test code to reproduce the issue.

Hi, I might be missing something. But the following code on Node v10.15.3 prints the second parameter `data` as a Function and the job never completes.

I believe Bull is not recognizing I'm returning a Promise. Any ideas why this might be happening? 

```
const queue = new Bull('queue');
queue.process(async (job, data) => {
    console.log(job, data);
});
```

## Bull version

3.10.0

**Comment by carlosdubus** [comment]
I was able to fix it by removing the second paramater. Like this:

```
const queue = new Bull('queue');
queue.process(async (job) => {
    console.log(job, job.data); // job.data has the data
});
```

This is different from the docs here: https://optimalbits.github.io/bull/

**Comment by manast** [comment]
seems like the example is wrong in the documentation, thanks for the report.

**Comment by manast** [comment]
seems like github did not release the latest documentation though... because this error was corrected some time ago,

**Comment by gabegorelick** [comment]
I think this is fixed now. All examples on the website look correct:
![image](https://user-images.githubusercontent.com/610129/67221098-e7ecb700-f3f8-11e9-8708-e4d151bed11a.png)

![image](https://user-images.githubusercontent.com/610129/67221127-f0dd8880-f3f8-11e9-8460-9a2da71f0659.png)
