### ISSUE TITLE
Does concurrency affects multi process ?

### ISSUE THREAD

**Issue by asafyish** [OptimalBits/bull#147]
Hi,

Let's say I am running 
```js
queue.process(5, queueProcessor);
```
in a clustered environment, with 8 cores - 8 nodejs processes.
Will each node process concurrently 5 jobs, or the entire cluster will process 5 jobs at a time ?

**Comment by Salakar** [comment]
Believe it's 5 per process, so 5 * 8.  At least it is for me, would be nice if this could be global though, so 5 across all processes in total.

**Comment by manast** [comment]
The way the cluster module works there is no simple way to do this. The concurrency setting is useful when you have asynchronous jobs that can run in parallel on a single process, while the cluster module spawns several processes each of them running a queue with its own concurrency level.

**Comment by pursual** [comment]
Is the default concurrency none? So each queue runs synchronously? Hope so.
