### ISSUE TITLE
How to cluster

### ISSUE THREAD

**Issue by brandoverflow** [OptimalBits/bull#1472]
Not a bug request or an issue.

Can someone tell me the proper way to cluster the workers?

Do i even need to? 

My current scenario : 
(Very cpu intensive)
When i have concurrency above 5 on a queue it tends to just get frozen with no tasks happening

**Comment by manast** [comment]
For very intensive CPU workers you can try with sandboxed processors which will run every work in a separate process, check in the guide for sandboxed processors: https://optimalbits.github.io/bull/
