### ISSUE TITLE
[Question/Issue] Job not started sometimes with AWS ElastiCache Redis

### ISSUE THREAD

**Issue by nosuchip** [OptimalBits/bull#1474]
## Description

- Created Redis instance on ElastiCache (I am using cache.t2.micro instance size).
- Taking simple example from documentation and point to ther AWS Redis instance.
- Creating Bull job

I see that job created but handler doesn't executed and job immediately changed status to "complete". When re-adding job number of times it executed 1 time of 3-4.

Also delayed jobs never called in such configuration. I am not actually sure it is a bug (well, I am pretty sure it isn't) because it works ok with local standalone Redis server.

Maybe somebody faced same problem?

## Bull version
3.10.0

**Comment by manast** [comment]
Bull works just fine in elasticcache. Some people having similar issues found out they had more than one worker running in the background, instead of only 1 as they thought.

**Comment by nosuchip** [comment]
Tested. Created queue without cluster, started job and it again just show in logs "job added" but without and further handler logs.

**Comment by nosuchip** [comment]
Well, finally got it. @manast you are generally right. I have number of queue managers deployed  on different servers. 2 queues wan configured to work with same Redis DB. So while Redis-side trigger emitted next job it was taken by another queue (and I see handler logs on that host. While on original host (who created job) I see only logs "job created".

**Comment by MeiFeiChen** [comment]
@nosuchip can you explain how you fix this issue? I have the same problem, but I don't know how to handle this problem.

**Comment by nosuchip** [comment]
@MeiFeiChen my last comment explained the solution. When you have more than one worker one worker takes the job and that's it - in logs of the other worker you see nothing.
