### ISSUE TITLE
Attach Object to a Job before passing it to a processor

### ISSUE THREAD

**Issue by Roguyt** [OptimalBits/bull#1477]
Hi,
First of all thanks for your work on Bull, it's a life saver for creating jobs/queue system easily and scalable.
I was just wondering if it could be possible to attach an object to each job before passing it to concurrent processor ?

Best Regards

**Comment by stansv** [comment]
Hi! Please provide more details about your case, what are you trying to achieve and why you don't want to do this inside process() callback. As I understood, this object should be attached just before job is processed, not when it added to the queue.

**Comment by Roguyt** [comment]
Hi !

The reason behind why i wanted to proceed was because of the API I'm using that implement a Rate Limit, so I made a previously (Non-Bull) Queue that kind of managed that.
As I checked the code i realized that fork does't allow references to be passed, so I reimplemented it using a Bull Queue 😅
Now I just need to find a way to reset a job when the queue is paused because of the rate limit, because right now I just fail the job and recreate it but that's dirty imo

**Comment by manast** [comment]
But are you using Bull's built in rate limiter?

**Comment by Roguyt** [comment]
I can't really use it because the API doesn't really define clearly the rate limit, therefore i'm waiting for a HTTP 429 in a running job before pausing the queue and waiting 1 minutes through the global event before relaunching it

**Comment by stansv** [comment]
How about make a retry inside job callback, for example, you can use a setTimeout() and try again after 1m? Then call done()/return result only after server respond with something different than 429.

**Comment by Roguyt** [comment]
I thought about doing something similar but the 1 minute is bad (IMO) on the last call that replied, so I may end up in a permanent state of queue paused. But I think I may have another idea using the global:resumed event... Thanks a lot, I'll close the issue :)
