### ISSUE TITLE
Question: Efficiency handling many delayed messages?

### ISSUE THREAD

**Issue by cakoose** [OptimalBits/bull#1478]
I'm considering a use case where I might enqueue many messages with different delays.  Will Bull handle this as efficiently as zero-delay messages?

Why I'm even asking: I'm not that familiar with using Redis as a queue, but I can imagine how zero-delay messages can be processed efficiently with BRPOPLPUSH.  I'm not sure how you would process delayed messages as efficiently.

Is the performance profile of different scenarios documented anywhere?

**Comment by stansv** [comment]
Basically Bull keeps track of how many time is to the next delayed job/set of delayed jobs. Delayed jobs are initially stored in a separate queue ordered by epoch time amount (Redis ZSET). Using time to next delayed job, there is a procedure scheduled with setTimeout() to move all jobs from delayed state to usual queue as like this done with queue.add(). So these jobs are also going through BRPOPLPUSH.

**Comment by manast** [comment]
@cakoose the jobs are moving back to the wait queue (as @stansv explained) in batches of 1k job ids, which is pretty efficient, so unless you have crazy demands on scalability you should be fine.

**Comment by cakoose** [comment]
Are all consumers running the setTimeout-scheduled procedure?  I'm a little worried about the CPU load on Redis as the number of consumers increase.

**Comment by stansv** [comment]
There is one timeout per Queue object instance. If you use concurrency setting > 1 (to implement "multiple consumers") there would still be one timeout.

**Comment by cakoose** [comment]
Ah yeah, that's what I was slightly concerned about.  So if I have tons of Node processes pulling jobs off the queue, they'll all be doing somewhat redundant operations for managing delayed jobs.

Though maybe I can reduce the number of `Queue`s by changing my design.  Normally, I'd just run one Node process per CPU (e.g. 8 per host), each pulling jobs independently.  Instead, I can run one parent process that pulls jobs off the queue, and 8 child processes that actually process the jobs.  That way I'd only have one `Queue` per host instead of eight.

**Comment by cakoose** [comment]
Oh -- another related question.  If I have a `Queue` but I'm just enqueuing (i.e. I call `add` but never call `process`), will there be a `setTimeout` scheduled procedure to move delayed jobs?

In my setup, the number of producers is much larger than the number of consumers.

**Comment by manast** [comment]
@cakoose yes. Btw in Bull 4.x the module that handles delays jobs is separate, so you will be able to minimize the overhead of checking for delayed jobs: https://github.com/taskforcesh/bullmq

**Comment by cakoose** [comment]
Thanks for the information!
