### ISSUE TITLE
Missing process handler for job type __default__

### ISSUE THREAD

**Issue by carlosdubus** [OptimalBits/bull#1479]
Hi guys. Most of my jobs are failing with this reason:

`"Missing process handler for job type __default__"`

Makes no sense that some of the jobs complete but some of them cannot find the process handler. 

getJobsCount:
```
{ waiting: 0,
  active: 0,
  completed: 110,
  failed: 1693,
  delayed: 0,
  paused: 0 }
```

getJobs("failed")
```
...
failedReason: 'Missing process handler for job type __default__' 
```

I only have one worker:
```
const queue = new Queue(argv.queue, process.env.BULL_REDIS as any);
console.log(`Ingesting from ${queue.name}`);
queue.on("error", console.error);
queue.on("failed", (job, err) => {
  console.log(`[job.failed:${job.name}] (${err.message}) job.data=${JSON.stringify(job.data)}`);
});

queue.process(async (job) => {
  // process code
});
```

I even tried with an empty queue.process block... most of the jobs fail and some of them go through. Any ideas why this might be happening?

**Comment by carlosdubus** [comment]
Update: In case someone else finds this issue: I found that another worker without the default handler was still running on the machine. Apparently, every worker needs to define a handler for every named job. If not you will get errors. Killing the other worker and just leaving a single worker with the default handler fixed the issue.

**Comment by manast** [comment]
Ok. I will close since it is working as designed.
