### ISSUE TITLE
Question: What's the best approach to restart a Worker

### ISSUE THREAD

**Issue by Roguyt** [OptimalBits/bull#1482]
Hi again,

When you're working with a cluster of worker that process a Bull' Queue using sandboxed processes, what is the best approach to tell this worker to stop picking up jobs and finish the current one to for example restart / update the worker ?

Best regards

**Comment by manast** [comment]
Just call ```queue.close()``` which gracefully waits for the jobs that are being processed to finalize.

**Comment by Roguyt** [comment]
This seems to be working, however the worker doesn't stop when there is Repeatable Job in the Queue. The process just get stuck and don't do anything.
