### ISSUE TITLE
Duplicate cron job entries added after each restart

### ISSUE THREAD

**Issue by ganesh-sg** [OptimalBits/bull#1483]
## Description
I am adding a number of cron jobs to the queue. I find that sometimes duplicate entries are created when I run the script several times. The behavior is not consistent. I see sometimes, no entries are created at all. 

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
```
const Queue = require('bull');

const fetchQueue = new Queue('MyScheduler');

fetchQueue.add("fetcher", {name: "earthQuakeAlert"}, {repeat: {cron: '1-59/2 * * * *'}});
fetchQueue.add("fetcher", {name: "lightening 1"}, {repeat: {cron: '1-59/2 * * * *'}});
fetchQueue.add("fetcher", {name: "weatherAlert"}, {repeat: {cron: '*/10 * * * *'}});
fetchQueue.add("fetcher", {name: "lightening 2"}, {repeat: {cron: '*/15 * * * *'}});
fetchQueue.add("fetcher", {name: "lightening 3"}, {repeat: {cron: '*/20 * * * *'}});
fetchQueue.add("fetcher", {name: "tornado"}, {repeat: {cron: '*/25 * * * *'}});


```

## Bull version
3.11.0

## Additional information
Arena UI which shows duplicate entries
![image](https://user-images.githubusercontent.com/47838609/65414836-1edba700-de12-11e9-8b48-08b9cf828325.png)

**Comment by ganesh-sg** [comment]
I think, I am making a mistake here by adding multiple jobs with the same name. That might have caused this issue.

**Comment by stansv** [comment]
OK please feel free to reopen if you'll have more questions
