### ISSUE TITLE
Concurrency is not respected for multiple job types in a single queue

### ISSUE THREAD

**Issue by macpatel** [OptimalBits/bull#1486]
## Description
Hi,

We are having one queue. In that queue we are having two types of named jobs(JobType1 & JobType2) with concurrency 1 & 2 (So total concurrency will be 3). 
Now if we add say 10 new jobs into the queue of "JobType1" and another 10 of "jobType2" then queue will process all the 3 jobs of either "jobType1" or "jobType2".

Below scenrios is happening right now:

Case1: 0 of JobType1 + 10 of JobType2 -> 3 Jobs of JobType2 will run concurrenctly (This is FIne)
Case2: 10 of JobTyp1 + 10 of JobType2 -> 3 jobs of either JobType1 or 2 will run concurrently (This is not fine, we are expecting that 1 job of JobType1 and 2 Jobs of JobType2 should run)

Our Expected Behaviour: 

Case 2 is what we want to acheive.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
```
let Bull = require('bull');
const redisConfig = {
  port: 6379,
  host: 'localhost',
};
let queue1 = new Bull('queue1', {
  redis: redisConfig
});

queue1.process('jobType1', 1, (job, jobDone) => {
  console.log('Running Job Type 1');
  jobDone();
});

queue1.process('jobType2', 2, (job, jobDone) => {
  console.log('Running Job Type 2');
  jobDone();
});

queue1.add('jobType1', {}, { lifo: false });
queue1.add('jobType1', {}, { lifo: false });
queue1.add('jobType1', {}, { lifo: false });
queue1.add('jobType1', {}, { lifo: false });
queue1.add('jobType1', {}, { lifo: false });
queue1.add('jobType1', {}, { lifo: false });

queue1.add('jobType2', {}, { lifo: false });
queue1.add('jobType2', {}, { lifo: false });
queue1.add('jobType2', {}, { lifo: false });
queue1.add('jobType2', {}, { lifo: false });
queue1.add('jobType2', {}, { lifo: false });
queue1.add('jobType2', {}, { lifo: false });
```

## Bull version
V3.11

**Comment by stansv** [comment]
Hi.

1. Each call to process() on same object with concurrency set will add additional total concurrency, this is documented (https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueprocess)
2. Bull does not distinguish what concurrency you set for what type of a job, yes. This information just not saved.
3. Basically this behavior is explained with the fact that when bull worker queries queue for the next job, he cannot decide not to process it or process it at some time later if job type differs to what he want. Worker can take next job only from the head of queue, not from arbitrary position.

The solution is simple, use multiple queues.

```
let Bull = require('bull');
const redisConfig = {
  port: 6379,
  host: 'localhost',
};
let queue1 = new Bull('queue1', {
  redis: redisConfig
});
let queue2 = new Bull('queue2', {
  redis: redisConfig
});

queue1.process(1, (job, jobDone) => {
  console.log('Running Job Type 1');
  jobDone();
});

queue2.process(2, (job, jobDone) => {
  console.log('Running Job Type 2');
  jobDone();
});

queue1.add({}, { lifo: false });
queue1.add({}, { lifo: false });
queue1.add({}, { lifo: false });
queue1.add({}, { lifo: false });
queue1.add({}, { lifo: false });
queue1.add({}, { lifo: false });

queue2.add({}, { lifo: false });
queue2.add({}, { lifo: false });
queue2.add({}, { lifo: false });
queue2.add({}, { lifo: false });
queue2.add({}, { lifo: false });
queue2.add({}, { lifo: false });
```
