### ISSUE TITLE
Queue Position

### ISSUE THREAD

**Issue by jonathan-fielding** [OptimalBits/bull#1487]
## Description
I am currently using Bull for a queue for one of my open source projects and I have implemented a queue position using combination of getJob and getWaiting. I was wondering if a PR to add the queue position directly to bull would be welcome so I don't have to call getWaiting to work out the position.

**Comment by manast** [comment]
Do you mean like given a jobId, getting the current position of that job in the queue?

**Comment by jonathan-fielding** [comment]
yes, means from a UI perspective I can tell user where they are in the queue

**Comment by Clemens-E** [comment]
+1
IMO its very useful from the view of the user to know what position the job is in.

**Comment by manast** [comment]
In current design the only way to get the position of a job is by traversing the list key in redis, this can be done iteratively but it is a slow operation. Since I haven't notice a lot of interest in this feature I will close it for now. PRs would be accepted though.

**Comment by phips28** [comment]
We are currently also looking for such a feature.
Our Queue processes only one job at a time, and for UI/Monitoring we would like to have a function to get the queue position by jobId.
@jonathan-fielding how do you do this with getWaiting? just call this on the queue and then use the array position?
Any other workarounds to get this at the moment?

**Comment by manast** [comment]
nope, getWaiting() is the only method we have for now.

**Comment by phips28** [comment]
This is my little hacker function:

 ```
 /**
   * returns the position of the job id in its queue
   * @param jobId
   * @return {Promise<number>}
   */
  async getPosition(jobId) {
    const activeJobs = await this.queue.getActive();
    if (activeJobs.find((j) => j.id === jobId)) {
      return 0; // currently processing
    }
    // this list is ordered by priority and timestamp
    const waitingJobs = await this.queue.getWaiting(0, 1000);
    // console.log('activeJobs', activeJobs.length);
    // console.log('waitingJobs', waitingJobs.length);
    // waitingJobs.forEach((j) => {
    //   console.log(j.id, j.data.priority, j.timestamp);
    // });
    const foundJobIndex = waitingJobs.findIndex((j) => j.id === jobId);
    // console.log('foundJobIndex', foundJobIndex);
    if (foundJobIndex === -1) {
      return 1000; // default
    }
    return foundJobIndex + 1; // +1 because of one is always active
  }
```

We never have more than 1k jobs in a queue. So that is ok. Also no performance issues.
