### ISSUE TITLE
Cannot read property 'returnvalue' of null

### ISSUE THREAD

**Issue by Roguyt** [OptimalBits/bull#1491]
## Description
This issue happens on different jobs of my Queue, I think the issue is coming from the removeCompleted: 1000, that removes jobs that aren't fully completed yet, hence missing the returnvalue of the completed job ?

## Bull version
^3.11.0

## Additional information
`TypeError: Cannot read property 'returnvalue' of null
    at Job.finished (/app/node_modules/bull/lib/job.js:451:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by stansv** [comment]
What is `removeCompleted: 1000`? The Job.finished function fails because it cannot find the job by id in Redis.

**Comment by Roguyt** [comment]
So if removeCompleted is present, you can't use Job.finished at all ?
Which means that you need to manually delete it after retrieving the data ?

**Comment by Roguyt** [comment]
I looked at the source code it seems to be the case.
So I need to disable the removeCompleted and handle it manually. 
Is that correct?

**Comment by stansv** [comment]
It's `removeOnComplete` not `removeCompleted` right? I cannot reproduce any error with finished() function. Even if it's created by another instance of Queue object.

```
const test = async () => {
  const queue = new Bull("test");

  const jobOriginal = await queue.add({}, { removeOnComplete: 1 });

  const sameQueue = new Bull("test");
  const job = await sameQueue.getJob(jobOriginal.id);

  queue.process(async (job) => {
    await new Promise((resolve) => { setTimeout(resolve, 10000); });
  });
  console.log("calling job.finished()...");
  await job.finished();
  console.log("job is finished!");
};
```

always prints

```
awaiting job.finished()...
job is finished!
```

**Comment by Roguyt** [comment]
Yes it was removeOnComplete sorry.
I'll do more testing on my system and get back to you 🤔

**Comment by Roguyt** [comment]
So after more debug, the problem was somewhere with my use of async/await. 

I'll try to do a PR to add examples to the documentation to help future users :-)
