### ISSUE TITLE
removeOnComplete is removing the schedule

### ISSUE THREAD

**Issue by ganesh-sg** [OptimalBits/bull#1492]
## Description
I am adding scheduled jobs with cron option. I am using the option removeOnComplete to remove the completed jobs. I am finding that after a while the scheduled job is removed from the Delayed queue. My understanding was removeOnComplete just removed the job from the Completed queue. 

## Minimal, Working Test code to reproduce the issue.
I don't have code to reproduced as it is happening in long running scenarios. I am sharing the identical code which is causing this issue - 

```
const Queue = require('bull');

async function configure() {
    const fetchQueue = new Queue('MyScheduler');
    await fetchQueue.removeRepeatable("first", {cron: '*/15 * * * * *'}).catch(console.error);
    await fetchQueue.removeRepeatable("second", {cron: '*/15 * * * * *'}).catch(console.error);

    await fetchQueue.add("first", {}, {repeat: {cron: '*/15 * * * * *'}, removeOnComplete: true});
    await fetchQueue.add("second", {}, {repeat: {cron: '*/15 * * * * *'}, removeOnComplete: true});
}
configure();

```
## Bull version
3.11.0

**Comment by ganesh-sg** [comment]
Thanks @stansv. 
I am using Redis provided by AWS ElastiCache. I am suspecting that ElastiCache is evicting the delayed jobs. So I want to add listeners to detect if any jobs are removed. I am using the `removed`  event on the queue. But it does not seem to work when I call removeRepeatable. 

Is there any alternatives to listen to the `removed` event?. Also, will it be called when the delayed job entry is externally removed in redis?

```
const Queue = require('bull');

async function configure() {
    const fetchQueue = new Queue('MyScheduler');

    fetchQueue.on('completed', (job) => {
        console.log(`Job ${job.id} with the name ${job.name} is completed!`);
    });

    fetchQueue.on('removed', (job) => {
        console.log(`Job ${job.id} with the name ${job.name} is removed`);
    });

    fetchQueue.process("*", (job) => {
        console.log(`Handling ${job.name}`);
        return Promise.resolve();
    });

    await fetchQueue.add("first", {}, {repeat: {cron: '*/15 * * * * *'}, removeOnComplete: true});
    await fetchQueue.add("second", {}, {repeat: {cron: '*/30 * * * * *'}, removeOnComplete: true});

    setTimeout(async () => {
        console.log("Removing first repeatable job");
        fetchQueue.removeRepeatable("first", {cron: '*/15 * * * * *'});
    }, 20000);
}

configure();

```

**Comment by manast** [comment]
For the record, it could be the redis instance was wrongly configured, the max memory policy should be set to "noeviction" https://redis.io/topics/lru-cache
