### ISSUE TITLE
KeyDB support? 

### ISSUE THREAD

**Issue by Wizp** [OptimalBits/bull#1493]
Hello.
Do you plan to add support of KeyDB instead Redis as backend?

**Comment by manast** [comment]
Is it not working already? According to the README they support the same protocol so it should be a drop-in replacement.

**Comment by Wizp** [comment]
I didn't checked.
The same protocols is not guaranteed that there is no pitfalls.
Thank you for your answer.

**Comment by laurivosandi** [comment]
Can you confirm Bull works correctly also with KeyDB multimaster?

**Comment by manast** [comment]
Last time I tested I could not make KeyDB to work with Bull nor BullMQ, but maybe things are changed since then, it was a couple of years ago.

**Comment by manast** [comment]
Btw, there are other newer interesting options out there that work with Bull, such as Upstash and Dragonfly...

**Comment by iliasbhal** [comment]
Just wanted to say that BullMQ is one of the best tools to verify when a competing Redis database claims that they are a "drop-in" Redis alternative. BullMQ became a benchmark "à la jepsen" for redis 😅.

**Comment by manast** [comment]
Yes, BullMQ is really pushing the boundaries of what Redis allows.
