### ISSUE TITLE
Redis emitter: MaxListenersExceededWarning

### ISSUE THREAD

**Issue by michalpierzchlewicz** [OptimalBits/bull#1494]
## Description
When starting my app, I attache multiple (over 9) processors to a single queue. Each processor is for a different job type/name. This causes the Redis emitter to throw 'MaxListenersExceededWarning'. This warning, however, stops showing when I "slowdown" the adding of processors (e.g. by adding putting the last 3-4 in a setTimeout function).

## Minimal, Working Test code to reproduce the issue.
Version that throws the warning:
```js
const stripeEvents = new Queue('stripeEvents')

stripeEvents.process('invoice.created', createInvoice(app))
stripeEvents.process('invoice.deleted', deleteInvoice(app))
stripeEvents.process('invoice.finalized', updateInvoice(app))
stripeEvents.process('invoice.marked_uncollectible', updateInvoice(app))
stripeEvents.process('invoice.payment_failed', updateInvoice(app))
stripeEvents.process('invoice.payment_action_required', updateInvoice(app))
stripeEvents.process('invoice.payment_succeeded', updateInvoice(app))
stripeEvents.process('invoice.sent', updateInvoice(app))
stripeEvents.process('invoice.upcoming', createInvoice(app))
stripeEvents.process('invoice.voided', updateInvoice(app))
```

The "slowed down" version: 
```js
const stripeEvents = new Queue('stripeEvents')

stripeEvents.process('invoice.created', createInvoice(app))
stripeEvents.process('invoice.deleted', deleteInvoice(app))
stripeEvents.process('invoice.finalized', updateInvoice(app))
stripeEvents.process('invoice.marked_uncollectible', updateInvoice(app))
stripeEvents.process('invoice.payment_failed', updateInvoice(app))
stripeEvents.process('invoice.payment_action_required', updateInvoice(app))
setTimeout(() => {
  stripeEvents.process('invoice.payment_succeeded', updateInvoice(app))
  stripeEvents.process('invoice.sent', updateInvoice(app))
  stripeEvents.process('invoice.upcoming', createInvoice(app))
  stripeEvents.process('invoice.voided', updateInvoice(app))
}, 100)
```
## Bull version
3.11.0

**Comment by manast** [comment]
Please read this: https://nodejs.org/api/events.html#events_eventemitter_defaultmaxlisteners
There is nothing wrong other than a warning, just increase the max listeners and you will be fine.

**Comment by michalpierzchlewicz** [comment]
@manast Thank you for the response. I think that you have misunderstood the core of the question. A warning is a warning - not an error. The problem is not in the warning being throw or me trying to find a solution on how to ignore it. The question was related to why it throws the warning only in the first case and not in the second case? Why is this inconsistent?

**Comment by stansv** [comment]
@michalpierzchlewicz 

Yes, technically we attach one-time handlers [here](https://github.com/OptimalBits/bull/blob/develop/lib/utils.js#L40) on every process() call to make sure internal Redis connection is ready before continue to register a new named processor.

This obviously can be avoided, but in next major version of Bull we're going to remove the named processors feature at all. Basically anyone can simply implement it with a switch-case statement.

Process function returns a promise; you can call it sequentially to avoid this warning. For example, with modern async/await:

```
const test = async () => {
  const stripeEvents = new Queue('stripeEvents');

  await stripeEvents.process('invoice.created', () => {});
  await stripeEvents.process('invoice.deleted', () => {});
  await stripeEvents.process('invoice.finalized', () => {});
  await stripeEvents.process('invoice.marked_uncollectible', () => {});
  await stripeEvents.process('invoice.payment_failed', () => {});
  await stripeEvents.process('invoice.payment_action_required', () => {});
  await stripeEvents.process('invoice.payment_succeeded', () => {});
  await stripeEvents.process('invoice.sent', () => {});
  await stripeEvents.process('invoice.upcoming', () => {});
  await stripeEvents.process('invoice.voided', () => {});
};

test();
```

**Comment by michalpierzchlewicz** [comment]
@stansv Thanks! Didn't know about the disposable handlers + that you can await the 'process' method. Very grateful!

**Comment by pckessel** [comment]
@stansv Thanks for this!
awaiting of each queue process was the trick for me.
