### ISSUE TITLE
Adding repeated Jobs with same cron string but different data

### ISSUE THREAD

**Issue by Clemens-E** [OptimalBits/bull#1495]
## Description
I'm trying to use repeatable jobs in this way:
1. add job with X data that should run every 2 minutes
2. add job with Y data that should run every 2 minutes
3. have plenty of workers that execute those jobs as soon as they have to be executed again (ever 2 minutes)

But in Bulls Documentation I found this:
> Bull is smart enough not to add the same repeatable job if the repeat options are the same.

So, I cannot add *multiple* jobs doing different things just because they have the same cron string.
Why? And is there any way to disable that behavior?

## Minimal, Working Test code to reproduce the issue.
```js
const queue = new Bull('query', {redis: {host: 'x.x.x.x.x'}});
queue.add({host: 'someAddress.org'}, {attempts: 5, repeat: {cron:'*/2 * * * *'}});
queue.add({host: 'something-completely-different.gov'}, {attempts: 5, repeat: {cron:'*/2 * * * *'}});
// only someAddress.org will actually be queued
```
## Bull version
3.11.0

**Comment by stansv** [comment]
Hi! Yes, just set your own job ID when you create a schedule.

    queue.add({host: 'someAddress.org'}, {attempts: 5, repeat: {cron:'*/2 * * * *'}, jobId: "some-id"});

Repeat options, jobId and job name (if you use named processors) are used to calculate a hash key before adding scheduled job. This prevents scheduled job from being created twice. For example, you can safely add all scheduled jobs to queue at the initialization step in your program and jobs will be created only once if you run it again.

**Comment by Clemens-E** [comment]
Thank you for the fast response!
I just tested and it works like expected.

**Comment by Clemens-E** [comment]
Oh, I just noticed that this is documented, but *only* in the guide that is located in develop, and not in the current guide.
Maybe update that?

**Comment by stansv** [comment]
@Clemens-E yes, for some reason master branch is pretty outdated. Probably some of latest Bull versions were built directly from develop.
@manast if we now have develop as a primary branch, can we switch https://optimalbits.github.io/bull/ to render docs from develop?

**Comment by Clemens-E** [comment]
@stansv Quick Question if you don't mind:
I would like the jobs to be have an offset like this:
1. Job gets added and should run every 5 minutes (time: 10:27)
2. Job gets executed right away (time: 10:27)
3. Job gets executed again (time: 10:32)

Why? Because I would like to prevent all jobs being re-queued at the same time.
I tried doing that with RepeatOpts#every but that didn't do what I wanted.
Is there any way I could do that?

**Comment by stansv** [comment]
Hi! This case is too specific and I don't think Bull should somehow organize your schedules so than jobs are queued in different points of time. What you can simply do is to initially add jobs after some timeout. e.g.

```
setTimeout(() => {queue.add({host: 'someAddress.org'}, {attempts: 5, repeat: {every: 5000}}); }, Math.floor(Math.random() * 5000));
```

**Comment by Clemens-E** [comment]
That will still result in the same execution time.
I think I will just requeue the job inside the worker with a delay. My jobs wont fail anyway.
Thanks for the help
