### ISSUE TITLE
How to unsubscribe the event?

### ISSUE THREAD

**Issue by kelp404** [OptimalBits/bull#1496]
##  Description
I need to get the job result. So I added a global event before adding a job.
But the queue._events['global:completed'] is bigger and bigger.
I don't know how to unsubscribe the event.
Could I just remove `queue._events['global:completed'][index]`?

A server:
1. Get request.
2. Add global event.
3. Add job.
4. Get job result and do response.

B server: Process jobs then return the result.

## Bull version
3.11.0

**Comment by stansv** [comment]
Hi! This is a common mistake. Please do not add subscriptions in each request.

Please find some example here https://github.com/OptimalBits/bull/issues/1452#issuecomment-536168918

**Comment by kelp404** [comment]
Thank you.
