### ISSUE TITLE
Please add example for delayed job

### ISSUE THREAD

**Issue by naseemkullah** [OptimalBits/bull#1497]
Seems like this feature was implemented via https://github.com/OptimalBits/bull/issues/7, could an example please be added as how to use it?

**Comment by naseemkullah** [comment]
Also https://docs.bullmq.io/guide/jobs/untitled is empty (link when you click Jobs->Delayed)

**Comment by stansv** [comment]
Hi! There is some description and example [here](https://optimalbits.github.io/bull/#delayed) and also [more fresh version](https://github.com/OptimalBits/bull/blob/develop/docs/README.md#delayed) of this document on github. Your link points to BullMQ documentation, the next version of Bull, which is not released yet (currently in Beta).

**Comment by naseemkullah** [comment]
Great, thanks @stansv !
