### ISSUE TITLE
Redis cluster issue

### ISSUE THREAD

**Issue by shubham190892** [OptimalBits/bull#1499]
We are getting the following reds-cluster exception while trying to run the bull process
```
command:
{ name: 'brpoplpush',
args: [ 'bull:squadSync:wait', 'bull:squadSync:active', '5' ] } }
09-10-2019 14:34 +00:00: BRPOPLPUSH { ReplyError: CROSSSLOT Keys in request don't hash to the same slot
```

## Bull version
"bull": "^3.11.0"

## Additional information
elasticache 5.0.4

**Comment by stansv** [comment]
Hi! Please try to rename your queue from squadSync to `{squadSync}`, it should help.
See also https://redis.io/topics/cluster-spec#keys-hash-tags
and https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#redis-cluster

**Comment by shubham190892** [comment]
It worked. Thanks

**Comment by tomfun** [comment]
As I understand if I have only 1 queue named `{squadSync}` ( or `{anything}squadSync`) it means all redis cluster nodes except 1 is not working

**Comment by EfrosIonelu** [comment]
Same error as 

```
Error: CROSSSLOT Keys in request don't hash to the same slot
Stack: ReplyError: CROSSSLOT Keys in request don't hash to the same slot
at parseError (/var/www/###/node_modules/redis-parser/lib/parser.js:179:12)
at parseType (/var/www/###/node_modules/redis-parser/lib/parser.js:302:14)
```

solution
```
import Queue from 'bull';

return new Queue(##, {
	prefix: '{queue}',
});

```
