### ISSUE TITLE
Missing process handler for job type __default__

### ISSUE THREAD

**Issue by zhaojunlike** [OptimalBits/bull#1500]
## Additional information
--

Missing process handler for job type __default__Error: Missing process handler for job type __default__     at Queue.processJob (D:\workspace\charp\ts-socketio-tpl-iqiyi\node_modules\bull\lib\queue.js:1034:7)     at processTicksAndRejections (internal/process/task_queues.js:85:5)

```
const file = path.join(__dirname, "./processor.js");
queue.process("proc", 2, file);//定义处理器
queue.add('{audio: '123123'}); // not work throw exception name=__default__


processor.js
module.exports = async function (job) {
    // do some job

    return "asd";
};
queue.add("proc",'{audio: '123123'}); // work will
```

Then ，How do I use the process.ts file。for typescript project

**Comment by zhaojunlike** [comment]
solved

**Comment by sibelius** [comment]
how did you solved it ?
