### ISSUE TITLE
Jobs are bounced back with the error User Rate Limit Exceeded

### ISSUE THREAD

**Issue by ganesh-sg** [OptimalBits/bull#1503]
## Description
I am using bull as a job queue. I have set this rate limit with the queue.

```
const opts = {
    limiter: {
        max: 1,
        duration: 100,
        bounceBack: false
    }
};

let queue = new Queue('FetchQueue', opts);
```
My understanding of bounceBack: false is that it put the job in waiting queue if it can't be processed immediately. But I am getting this error intermittently.

`StatusCodeError: 403 - {"error":{"code":403,"message":"User Rate Limit Exceeded","errors":[{"message":"User Rate Limit Exceeded","domain":"usageLimits","reason":"userRateLimitExceeded"}]}}
`

What are the consequences of this error? Does it mean that the jobs were bounced back from the queue?

**Comment by stansv** [comment]
Hi! I tested bounceBack option and when it's `false`, jobs are added to delayed queue and executed one by one respecting limiter duration (but the execution order is not respected). When it's `true`, jobs saved into Redis but do not added to any queue and never executed. 

Try to increase limiter duration if you are receiving such errors from external API.

**Comment by stansv** [comment]
Bull doesn't throw such errors, your error is very similar to Google API error. Do you use any Google APIs? The 403 is HTTP response code I guess..

**Comment by ganesh-sg** [comment]
Yes, I am using Google translation API. I guess, it might have thrown this error.
