### ISSUE TITLE
TTL for job in active queue

### ISSUE THREAD

**Issue by ms10398** [OptimalBits/bull#1504]
How can I specify TTL for a job? I tried to look through the docs but couldn't find anything related to it though I read that bull has this feature. So that if it stays in active state for the specified time it terminates automatically.

I stumbled upon this as the processor stops processing the jobs suddenly and starts working after restart. There is no log or error thrown but the processor gets stuck and jobs start piling in waiting queue.

## Bull version
v3.11

**Comment by stansv** [comment]
Hi! Basically execution timeout is achieved with timeout option, see JobOpts description here: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd

But hitting timeout doesn't mean your processing procedure would somehow be interrupted. Bull just registers job promise rejection callback with setTimeout(), and that's all. If you have a long-living loop in your processor it'd be better to check for timeout manually on each iteration and explicitly exit.

There's also a possibility to execute jobs in child node process (https://github.com/OptimalBits/bull/blob/develop/docs/README.md#sandboxed-processors).
In this case you can try to kill child process, but this is not implemented in Bull yet, so this would require manual tracking of mapping between each PID and job id.

**Comment by ms10398** [comment]
Actually there is no long-living loop but the jobs get stuck in active state even there is no error and the jobs are processed.

I am not sure exactly right now why is it happening.

So the time out will put it in failed queue?

**Comment by stansv** [comment]
Yes, a working example

```
import Bull from "bull";

const queue = new Bull('test');

queue.process(async job => {
  console.log("Executing job " + job.id);
  await new Promise((resolve) => { setTimeout(resolve, 10000); });
  console.log("Finishing execution of job " + job.id);
});

queue.add({ foo: 'bar' }, { timeout: 3000 });

queue.on('completed', (job) => { console.log("Job " + job.id + " is completed"); });
queue.on('failed', (job) => { console.log("Job " + job.id + " is failed"); });
```

Output

```
Executing job 1
Job 1 is failed
Finishing execution of job 1

```

The job's `failedReason` in Redis is `Promise timed out after 3000 milliseconds`.

As you can see, Bull fails the job but the callback is still executed; result is ignored then even if it completes successfully.

**Comment by ms10398** [comment]
Thanks for the help!

Can you help me with the problem which leads me to use timeouts?

The queue gets with some job in active state and the waiting queue starts piling up

**Comment by stansv** [comment]
The debugging in particular cases may be quite tricky, depending on what you're doing in process callback. Are you using async callback as in my example or call done() once work is completed?

Anyway, the general advice in to add more logging to your procedure.. most likely a promise getting abandoned somewhere (ie neither reject not resolve is called).

**Comment by ms10398** [comment]
I am calling done() when the process is completed

**Comment by stansv** [comment]
I guess something goes wrong and your procedure fails before done() is called. The error is swallowed for some reason. Try to wrap the entire process with try-catch

```

queue.process((job, done) => {
  try {
    .. here is your business logic ..

    done(null, result);
  } catch(error) {
    done(error);
  }
});

```

**Comment by ms10398** [comment]
I will try that will follow back if it solves our problem.

Thanks a lot for the quick response really appreciated @stansv 👏

**Comment by ms10398** [comment]
Right now it is working fine for us. So I would proceed and close the issue if there is any further help needed will reopen it.

Thanks! 😄
