### ISSUE TITLE
How to choose the concurrency value?

### ISSUE THREAD

**Issue by omar-dulaimi** [OptimalBits/bull#1507]
## Description
Hello there,
I looked everywhere through the docs, but couldn't find any guidelines or best practices when it comes to choosing the right concurrency number.
What are the limitations, the drawbacks of say for example choosing a very large number?
How can I decide what number to choose?
Thanks a lot
## Bull version
v3.11.0

**Comment by manast** [comment]
So this is something that you can finetune for your specific use case. For example, if your processors are very IO intensive you probably can have a very large number of concurrency, whereas more CPU intensive task will not benefit so much from concurrency at all.

**Comment by omar-dulaimi** [comment]
Thank you @manast
