### ISSUE TITLE
Complete repeatable job, stop calling recurrently

### ISSUE THREAD

**Issue by frct1** [OptimalBits/bull#1510]
## Description
Hello
What is the best way to stop repeatable job ?
For example: we repeating to ask some service is there any changes. If yes: stop repeatable job.
Callback calling doesn't help. With regular task works without followed troubles
Calling `removeRepeatable` from job handler doesn't help

**Comment by stansv** [comment]
Hi! `removeRepeatable` should work, please double-check you've passed all the following:

- cron expression/repeat interval
- job name, if named processors feature is used
- jobId if custom jobId was set

PS cron expression should be exactly the same string

**Comment by frct1** [comment]
Hi @stansv 
Roger that
I will retest it tomorrow and keep question updated
Thank you for the hint

**Comment by stansv** [comment]
I'm closing this issues as it seems to be solved, please feel free to reopen this issue/create new one if you will have more questions.

**Comment by oneEyedSunday** [comment]
Hello @stansv,

I have tried with different permutations to get `removeRepeatable` to actually remove. 
But the job still runs and the data is still in Redis.

Bull v. 3.11.0

```js
'use strict';

const Queue = require('bull');

const _q = new Queue('test');

const repeat = {
  cron: '*/2 * * * *',
  startDate: Date.now(),
  endDate: '2020-06-16T23:59:59Z',
  tz: 'Africa/Lagos'
};

_q.process(async job => {
  console.log('Processing at: ', new Date().toISOString());
  console.log('Job Details: ', job.opts);
  console.log('is Active: ', await job.isActive());
  console.log('is Completed: ', await job.isCompleted());
});


function backgroundOp(op, ...args) {
  (async() => {
    try {
      await op(...args);
    } catch (err) {
      console.error('Error from backgroundOp: >>> ', err);
    }
  })();
}

function cleanUpRepeatableJob(jobInfos) {
  jobInfos.forEach(async _rJob => {
    console.log('Removing repeatables by key: ', _rJob.key);
    console.log('Getting raw Job', _rJob);
    const rawJob = await _q.getJob(_rJob.opts.jobId);
    if (rawJob) {
      console.log('Raw Job: ', rawJob);
      return;
    }
    await _q.removeRepeatableByKey(_rJob.key);
  });
}

async function cleanUpJob(job) {
  try {
    const j = await _q.getJob(job.id);
    if (j) {
      console.log('FOund job details, attempting to mark as finished and remove: ', j.id);
      console.log('Options: ', j.opts.repeat);
      const { count, ...repeatData } = j.opts;
      console.info('Attempting to clear with: ', { ...repeat, jobId: j.id});
      await _q.removeRepeatable({ ...repeatData, jobId: j.id});
      await _q.removeRepeatable({ jobId: j.id, ...repeat });
    }

  } catch (err) {
    console.error('Error: ', { stackTrace: err.stack, message: err.message });
  }
}

(async() => {
  await _q.add({
    appointmentId: 18,
  }, { repeat });

  setTimeout(async() => {
    const jobs = await _q.getJobs();

    const thisJob = jobs
      .filter(job => job && job.data && job.data.appointmentId === 18)
      .map(({ opts, data, id }) => ({ opts, data, id }))[0];
    if (thisJob) {
      backgroundOp(cleanUpJob, thisJob);
    }
  }, 7000);
})();


```

I do not want to use `removeRepeatableByKey` because JobInformation doesn't have the information I can use to filter the jobs to get the specific one I need. `(I tried passing a custom prop to repeat, but It doesn't show up in the JobInformation payload)`.
