### ISSUE TITLE
[Question] What's the best pattern for selective retries? Returning null to backoff strategy is instantaneous retry? 

### ISSUE THREAD

**Issue by bleafman** [OptimalBits/bull#1512]
## Description

Hello! Really appreciate your work on bull!

I noticed that there doesn't seem to be a way to conditionally skip a job using the backoff strategy. Returning null in a custom backoff strategy instantly retries the job (code example below). 

What's the recommended way to conditionally not retry a job? 

For a lot of usecases (and my current one) there's a number of errors/exceptions where it would be ideal for the job to not retry (ex. data passed to the job was insufficient, a 3rd party API returned no results, etc.). 

I could hack it with ``job.moveToFailed`` by wrapping all the processors' logic in a ``try`` and putting the conditional error handling in a ``catch`` but that means the logic is located on each processor vs. at the queue.

Thanks so much!

#### Ideally would exit and not make any retries. Currently retries.

```javascript
var Queue = require('bull');

function NoSoupException(message, countries) {
  const error = new Error(message);
  error.code = 'NO_SOUP_FOR_YOU';
  return error;
}

NoSoupException.prototype = Object.create(Error.prototype);

var myQueue = new Queue('Seinfeld References', {
  settings: {
    backoffStrategies: {
      SeinfeldBackoffStrategy: function(attemptsMade, error) {
        if (error.code === 'NO_SOUP_FOR_YOU') {
          console.log('No Soup for You!');
          return null;
        }
        return 1000;
      }
    }
  }
});

myQueue.process(function(job, done) {
  if (job.data.character === 'Elaine') {
    throw new NoSoupException();
  } else {
    throw new Error();
  }
});

myQueue.add(
  { character: 'Elaine' },
  {
    attempts: 3,
    backoff: {
      type: 'SeinfeldBackoffStrategy'
    }
  }
);

myQueue.add(
  { msg: 'Jerry' },
  {
    attempts: 3,
    backoff: {
      type: 'SeinfeldBackoffStrategy'
    }
  }
);

```

## Bull version
3.11.0

**Comment by stansv** [comment]
Hi! Did you tried to return -1 as noted [here](https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#custom-backoff-strategy)?

**Comment by bleafman** [comment]
No! I thought I had read through everything and missed that ><

-1 works!
