### ISSUE TITLE
Unlimited attempt. Never fail. Keep trying.

### ISSUE THREAD

**Issue by apmcodes** [OptimalBits/bull#1513]
What should be the value of attempt incase we never want the job to fail but keep attempting unlimited times.
**Use Case**:  It's a long job handled by multiple workers part by part so returned (failed) many times to queue ... say 5000+ times. 

Tried setting attempts to 0, -1. It attempts once and fails.

**Comment by apmcodes** [comment]
Seems this is answerred in #1511 

Will give it a try.

**Comment by stansv** [comment]
Hi! Please feel free to reopen.

**Comment by apmcodes** [comment]
Working as expected. Thanks
