### ISSUE TITLE
question: timeout a job

### ISSUE THREAD

**Issue by shaoxp** [OptimalBits/bull#1517]
do you plan to support timeout a job or have some suggestions to achieve it in client-side. 

that is, instead of unlimited amount of time for an active job, it has a timeout settting. (this could be a global setting) when timeout time reached, the job will enter into the failed status to wait to retry. 
if somehow, the timeout job is complete by previous process at, it maybe processed twice. we still achieve at least once target.

**Comment by manast** [comment]
There is already a timeout option when adding a job: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd
however, your process function will of course continue working, unless you implement a separate mechanism for that.

**Comment by shaoxp** [comment]
thanks very much.
