### ISSUE TITLE
can I get counts on all queues together?

### ISSUE THREAD

**Issue by shmulikmak** [OptimalBits/bull#1518]
`getCompletedCount()` return from the current queue but I want to get from all "new Queue(name)"
I came from Kue and there I can get all count by just connect to 
var kue = require('kue')
kue.completeCount() // get count of all queues

**Comment by manast** [comment]
You will need to save the queue names and then run getCompletedCount on every queue.

**Comment by shmulikmak** [comment]
can I open a feature request about this because it is available in Kue?
I think it's really useful, mainly for UI and statistics...

**Comment by stansv** [comment]
Kue does not support multiple queues, so this is not the same. Stick to single queue setup in Bull or collect counts by yourself as @manast suggested. You cannot just ask Bull to find all your queues in Redis, at least you're not limited to use single Redis instance for all queues.

**Comment by rosslavery** [comment]
Some sample code

```typescript
public async getCompletedCount(): Promise<number> {
    const totalCompletedCount = await Array.from(this.queues.values()).reduce(
      async (countPromise: Promise<number>, queue) => {
        let currentCount = await countPromise;
        const queueCount = await queue.getCompletedCount();
        currentCount += queueCount;

        return currentCount;
      },
      Promise.resolve(0)
    );

    return totalCompletedCount;
  }
```

**Comment by shmulikmak** [comment]
> Some sample code
> 
> ```ts
> public async getCompletedCount(): Promise<number> {
>     const totalCompletedCount = await Array.from(this.queues.values()).reduce(
>       async (countPromise: Promise<number>, queue) => {
>         let currentCount = await countPromise;
>         const queueCount = await queue.getCompletedCount();
>         currentCount += queueCount;
> 
>         return currentCount;
>       },
>       Promise.resolve(0)
>     );
> 
>     return totalCompletedCount;
>   }
> ```

yes, that what I did in my case:
```
const getAllCompletedCount = exports.getAllCompletedCount = async () => {
    let total = 0;
    for (const job of queues) {
        total += await job.getCompletedCount();
    }

    return total;
};

```
