### ISSUE TITLE
Question: is there a way to update job delay time?

### ISSUE THREAD

**Issue by meng-chiang** [OptimalBits/bull#1523]
## Description
Hi, I am trying to find a way to update the job delay time after job has created. I already tried to modify job hash record in redis with key 'delay' & options.delay. But it not worked. 
Any suggestion would be helpful! Thanks.

## Bull version
3.11.0

**Comment by stansv** [comment]
Hi, internally Bull uses setTimeout to wait and move nearest job in delayed queue (in a loop), so probably it will only work if you increase delay.
Try to re-add job to queue: find and remove old version with wrong delay and create new job.

**Comment by meng-chiang** [comment]
@stansv  Thanks for your quick reply!
