### ISSUE TITLE
Option to add TTL or Remove failed jobs older than 2 days

### ISSUE THREAD

**Issue by a-samad** [OptimalBits/bull#1524]
## Description
I have problem in my production code where our sysadmin team has added threshold alert for greater jobs in elastic cache.
The failed jobs are always remains higher in the cache, I have to set TTL or a way to remove failed jobs after 2 days automatically to prevent threshold meeting condition.

## Bull version
3.4.2

**Comment by stansv** [comment]
Hi, use numeric removeOnFail option as described here: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd
