### ISSUE TITLE
isReady is not fired 

### ISSUE THREAD

**Issue by RyuuGan** [OptimalBits/bull#1525]
The `isReady` event is not fired if redis wasn't available at the startup but then it appears, so the `client` is reconnected, but the `isReady` event is not fired.

```
console.log(queue._initializing)
console.log(queue.client.status === 'ready')

Output:

Promise {
  <rejected> Error: connect ECONNREFUSED 127.0.0.1:6379
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 6379,
    level: 'error',
    timestamp: '2019-10-29 10:37:18',
    [Symbol(level)]: 'error',
    [Symbol(message)]: '{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379,"level":"error","timestamp":"2019-10-29 ' +
      '10:37:18"}'
  }
}
true
```

## Description

```
const queue = new Queue(queueOpts.name, {
  redis: {
    port: config.REDIS_CONFIG.port,
    host: config.REDIS_CONFIG.host,
  },
})

queue.isReady().then(() => {
  salesforcePushQueue.process(queueOpts.concurrency, async (job: Job) => {
    console.log(job.data, job);
  });
}); 
```

## Bull version

3.11.0

## Additional information

Start the app without the `redis-server` and then after the first error appears start the `redis-server`.

**Comment by ISO-B** [comment]
Did you mange find workaround for this one? I have same problem. It feels that isReady() is not processed again after client is connected. Since even when client is ready isReady will still return ECONNREFUSED.

**Comment by RyuuGan** [comment]
@ISO-B 

No, I didn't find a proper solution for this.

**Comment by manast** [comment]
calling ```isReady``` should not be needed so it would be interesting to know why you are calling it in the first place...
