### ISSUE TITLE
new Queue or new Jobs Name ???

### ISSUE THREAD

**Issue by abdolrhman** [OptimalBits/bull#1528]
- Am wondering from processing and simplicty of doing ,
- i have orders with two status rush and normal, 
should create for both Queues,
or only one queue with different name (rush and normal)

--- Also can i create some thing for processor,
As to make it finish Queue Named "Rush" OR Jobs with name "Rush",
finish it First , as to always check queue rush is empty then go for queue normal,
same to jobs name ??

**Comment by stansv** [comment]
To prioritize jobs use the priority option: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd

Please note that the next job with higher priority will be taken by worker once it will process current job with normal prio (if any), but if you jobs took much time and you want to process high priority job right away you should consider using two queues; in this case jobs of both types will be processed in parallel, so no priorities required.

**Comment by abdolrhman** [comment]
Hi @stansv ,
thank you for your replay,
Ok so i get from this,
if i want to finish processing RUSH orders first, or to always giving priority to a Rush order to be processed,
i should make like more workers process that Rush Queue,
becaue after all i need to finish the Rush Orders first, 
I need for ex:-
`myFirstQueue.add('Rush',{
     name: 'order1'
  }
})`
`myFirstQueue.add('Rush',{
     name: 'order2'
  }
})`
`myFirstQueue.add('Rush',{
     name: 'order3'
  }
})`
`myFirstQueue.add('Rush',{
     name: 'order4'
  }
})`

`myFirstQueue.add('normal',{
     name: 'order5'
  }
})`
`myFirstQueue.add('normal',{
     name: 'order6'
  }
})`
`myFirstQueue.add('normal',{
     name: 'order7''
  }
})`
`myFirstQueue.add('normal',{
     name: 'order8'
  }
})`

`myFirstQueue.process.('normal', (job, done) => done());`
`myFirstQueue.process('Rush', (job, done) => done());`

now with this apporach how do i acheive that focus rush process always then process normal
as lons as there are no RUSH orders,

And thank you very much bro for the work done in this package,
Magnificent ...
