### ISSUE TITLE
Question:  How to create a delay between jobs?

### ISSUE THREAD

**Issue by kitty-gitbabel** [OptimalBits/bull#1531]
## Description

I have a situation where I have two jobs, the second depends on the first to finish first and they both enter the queue around the same time.  Unfortunately there's no way to determine when the first is done.  As a temporary solution, I would like to create a delay between when the two jobs get executed.  I tried setting `delay` but that's only a delay from the time the jobs enter the queue, it doesn't create a delay between the jobs.  Is there anyway to do this?

## Bull version
3.11.0

**Comment by stansv** [comment]
Does second job getting added to queue always after first one? I think you can just create 2nd job as last action of 1st job. Anyway can you share more details about your case?

**Comment by kitty-gitbabel** [comment]
Not always the second job is conditional.  The biggest challenge is I can't determine when the first job is done then call the second job.  But I think I have a temporary hack right now, by adding a setTimeout in the `process` method to force a time delay between jobs.
