### ISSUE TITLE
Limiter does not consistently rate-limit over a period of time with multiple consumers.

### ISSUE THREAD

**Issue by theclive** [OptimalBits/bull#1540]
## Description

We have experienced issues with the limiter functionality after deploying our solution to production.  To explain what our system does very simply:
- At a specific time, a blast is triggered.
- A blast can contain anything from 1000 to 100,000 jobs
- Each job calls an endpoint
- To prevent flooding the endpoint, we need to rate-limit the jobs.
- We implemented bull w/Redis to limit the speed at which we consume the endpoint. (requests per second).

In a specific production example: A blast was triggered and we needed to process ~30,000 jobs at 32 per second.  Everything worked perfectly or the first 3 minutes, but thereafter the jobs per second dropped to an average of 6 per second.

We have managed to recreate this with minimal code on our local machines.  Below you will find two projects and some instructions on how to start them up and replicate what we have found.  [Here is a video](https://drive.google.com/open?id=1-BAOn95ATwmCLJjV_uxunT9e7uaoyV7q) of myself running this test (a legend is included below under "Additional Information").  In the video, the terminal windows on the left represent 5x processes consuming the same queue.  On the top-right, you will see an average RPS over the last 20 seconds and the top-middle is an output of number of requests for each of the last 20 seconds.  The bottom right is a [bull-board](https://www.npmjs.com/package/bull-board) dashboard.

## Minimal, Working Test code to reproduce the issue.

[bull-limiter-test.zip](https://github.com/OptimalBits/bull/files/3808255/bull-limiter-test.zip)
[test-endpoint-app.zip](https://github.com/OptimalBits/bull/files/3808256/test-endpoint-app.zip)

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

1. Extract both projects above
1. Ensure you have an instance of Redis running locally (localhost:6379)
1. Start up the `test-endpoint-app`: `node .` (don't forget `npm i`)
1. Open `http://localhost:3000/rps` in your browser.
1. Start up an instance of `bull-limiter-test`: `node one-processor.js` (don't forget `npm i`)
1. Note the RPS in your browser shows 32.
1. After about a minute, start up 5x more instances of `bull-limiter-test`
1. After a few minutes, you will notice the RPS yo-yo every 30-60 seconds (drops down to ~10 for a bit and then jumps suddenly back up to 32).
1. Drop the instances back down to 1 or 2, and notice the RPS remains stable.

## Bull version
3.11.0

### Node Version
>node -v
>v12.13.0

### Some extra info

1. We have tested what happens when we don't provide our own Redis client instances.  The issue described above still presents.
1. In the video, you will notice that the number of connected clients keeps increasing.  This can be ignored because it's caused by my implementation of bull-board was not cleaning up connections every time it refreshed the queues from Redis.  Removing this has no effect on the outcome of the test.

### Legend for the above video:

![image](https://user-images.githubusercontent.com/23497305/68197320-bf50e980-ffc2-11e9-8548-2a9e075d0d1e.png)

**Comment by devillexio** [comment]
Can we maybe get an update on this? It remains affecting us on a daily basis. We don't mind helping in the diagnosis of the issue and possible resolutions, but we need to get some direction on where to start and whether other people are also affected.

**Comment by manast** [comment]
maybe the amount of rate limited jobs gets very big and creates some kind of snow ball effect. I have plans to improve the rate limiter to handle much better higher loads but I have not time for fixing it right now.

**Comment by MysteryG** [comment]
@manast do you think it would make any difference if the jobs were removed as they completed?

**Comment by manast** [comment]
it only affects the number of jobs being rate limited at a given point in time.

**Comment by theclive** [comment]
@manast do you have some suggestions for how you would improve the rate-limiting?  Perhaps someone can then submit a PR for you to review?

**Comment by manast** [comment]
I have a design in mind to fix it, but its based on a new status, instead of using the "delay" set we would need a "rate limited" set, that will be handled differently.
