### ISSUE TITLE
how to handle reject promise with process

### ISSUE THREAD

**Issue by shmulikmako** [OptimalBits/bull#1549]
## Description
how to handle reject promise with the process?

my code:

`>
//page 1 
exports.processTask = async (queueName, taskProcessor) => {
    await queueName.process(async (job) => {
        return taskProcessor(job);
    });
};

//page 2
...
...
processTask(queueName, async (job) => {
    try {
        await jobToAction(job);
    } catch (err) {
        job.log('WorkingJobFailed ' + new Date() + err);
    }

    return Promise.resolve();
});
`
my question is how Bull call to complete or failed event?
how does Bull know the job done success? 
how and where can I put the reject()?

Thanks a lot!

**Comment by manast** [comment]
you just throw an exception and that will mark the job as failed.

**Comment by shmulikmako** [comment]
yes, but *where* can I throw the exception? inside the catch?

**Comment by stansv** [comment]
Inside your async process callback,

```
async (job) => {
return taskProcessor(job);
}
```

If taskProcessor is async too then you can throw exception there.
