### ISSUE TITLE
Queue process freezing

### ISSUE THREAD

**Issue by dsjh** [OptimalBits/bull#155]
I have created a basic example that queues 100 jobs and the first time I ran it worked and printed all 100.
```javascript
var Queue = require('bull');
var videoQueue = Queue('video transcoding', 6379, '127.0.0.1');
console.log('starting');

videoQueue.process(function(job, done){
console.log(job.jobId);
});

videoQueue.on('failed', function(job, err){
 console.log('job failed')
})

videoQueue.on('active', function(job, jobPromise){
console.log('active');
})

videoQueue.on('progress',function(job, progress){
console.log('progress');
})

videoQueue.on('completed', function(job){
console.log('completfed');
})

videoQueue.on('paused', function(){
console.log('paused');
})


videoQueue.on('resumed', function(job){
console.log('resumed');
})

videoQueue.on('cleaned', function(jobs, type) {
console.log('cleaned');
});


for (var i =0;i<100;i++)
{
videoQueue.add({video: 'http://example.com/video1.mov'});
}
```

Now when I run my script above, it runs one job and freezes and then the next time runs the next when I kill it. The output is:

starting
5
active

I am using `bull v0.2.7`
and redis `Redis server v=3.0.3`

Any ideas of diagnosing this? It's built on a raspbery pi.

**Comment by manast** [comment]
you need redis 2.8.11 or higher, otherwise bull will not work properly. The reason is that 2.8 introduced lua support, and earlier than 2.8.11 it had a bug that was triggered by bull.

**Comment by dsjh** [comment]
My post shows i'm using 3.0.3 which is higher than 2.8.11, what could be causing the freezing?

**Comment by manast** [comment]
ah, sorry, I saw it wrong :)

**Comment by manast** [comment]
Can you try with the latest version of bull (0.4.0) to see if you get the same freeze?

**Comment by dsjh** [comment]
sure, I can try 0.4.0 but npm shows build as failing.

On Aug 21, 2015, at 09:45 PM, Manuel Astudillo <notifications@github.com> wrote:

Can you try with the latest version of bull (0.4.0) to see if you get the same freeze?

**Comment by dsjh** [comment]
just tried 0.4.0 via NPM and it freezes also, are there any debug logs I can check?

On Aug 21, 2015, at 09:45 PM, Manuel Astudillo <notifications@github.com> wrote:

Can you try with the latest version of bull (0.4.0) to see if you get the same freeze?

**Comment by dsjh** [comment]
I started again with the demo example of the website and it worked, there must of been a bug in my code. Apologies.
