### ISSUE TITLE
How to handle expired repeatable event in Queue ?

### ISSUE THREAD

**Issue by taiptt** [OptimalBits/bull#1551]
## Description
Well i want to add a repeatable job which limit set like 5. After 5 times running, 5 job instances was moved from active to completed in queue. 
So how can i handle the event fired when all my job instances completed ? 
Thanks.

## Bull version
 "3.11.0"
## Additional information
I have try to use queue.on('completed') but they fire when each instance complete , not when all my job instances complete

**Comment by stansv** [comment]
You can access job sequence number as `job.opts.repeat.count` inside your process() callback, just call queue.removeRepeatable() with to disable scheduled. The removeRepeatable accept repeat options you've used to add repeatable job.

**Comment by walkerlifee** [comment]
Thank @stan,
By the way, the `queue.removeRepeatable() ` was not working when i add a new job with a custom jobId. After reading your repo, i figured out that we have to pass the jobId merge with the previous repeat options to make it work _(i.e `{ jobId: 'xxx', cron 'xxx' }` }_. I think you should mention this note in your document.
Thank you guys again.
