### ISSUE TITLE
handel only one job at a time

### ISSUE THREAD

**Issue by abdolrhman** [OptimalBits/bull#1555]
hello,
All i need is a way to make the process function handel only one job at a time ?
so if i added 10 jobs, only one get processed and the rest stay in the waiting list till one is out

thanks ^^

**Comment by abdolrhman** [comment]
@manast @stansv please guys any hint will be much apperciated ,
all i want is it possible or maybe is it avaliable , to process only one job ?

thank you guys.

**Comment by manast** [comment]
If you have 1 worker, with concurrency 1, that is exactly the way the queue works already, you do not need to do anything special.

**Comment by abdolrhman** [comment]
Thanks buddy :) @manast
