### ISSUE TITLE
Q: Automate Adding to Queue with guarantee of none reduandt Jobs in Queue ?

### ISSUE THREAD

**Issue by abdolrhman** [OptimalBits/bull#1556]
## Description
I have a scenario of, Orders That needs to be download via FTP,
Now what i have is Two API that give me the Orders,
One to give me "Rush" Orders Second API to get me "Normal" Orders 

Now Please I have choosed Bull for implemnating the Queue thing,

What i need to know, And am sorry if its a noob or dump questions,
please Bear with me 

1. First thing, I want to automate the process of feeding the Queue by Orders,
Now i have design the cycle that After : 
                 1. i got the orders from api
                 2. i download the order
                 3. then i set the order by another API that it has been downloaded so i dont get it again.
I am saying that because, i have thought of feeding the queue by orders that want to be downloaded, By "A CRON JOB",
But this will insert redundant orders in queue, 
- So i have thought that wait till Queue finish all the jobs, At this time, All orders downloaded and set that they are downloaded so i dont get them Again when i fire API, 
- IS THIS POSSIBLE BY BULL.JS
" to wait till All queue jobs  finishes processing, then fire an event with my method of adding the new jobs to the Queue",,,, this have a problem that ,
 what if the there are no jobs from the API it will  fire the Event countless time , till there are jobs from API, right ???

so am not sure what to do to guarantee none reduandt date in Queue, and also to automate the proess of Adding jobs to the Queue ??

Thanks for all of  the work

## Bull version
@latest

**Comment by avinkavish** [comment]
I think if you use the same job id, it will not be inserted again.
