### ISSUE TITLE
improve documentation at moveToFailed()

### ISSUE THREAD

**Issue by shmulikmak** [OptimalBits/bull#1557]
at [https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#jobmovetofailed](url)
need to improve the doc.
The situation now = "Pulls a job from 'waiting' to 'active'";
please change to = "Pulls a job from 'waiting' to 'failed'";

also at [https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#jobmovetocompleted](url)
change to =  "Pulls a job from 'waiting' to 'completed'";

Thanks

**Comment by abdolrhman** [comment]
yep i was going to post this, but i was waiting my other issues to be resolved to not spam the Issues Form ...

**Comment by manast** [comment]
@shmulikmak you are welcome to open a PR :)

**Comment by manast** [comment]
As mentioned here https://github.com/OptimalBits/bull/pull/1558 the documentation is correct as it is now.
