### ISSUE TITLE
.empty(), .clean(), .remove() don't do anything

### ISSUE THREAD

**Issue by brandonros** [OptimalBits/bull#156]
I'm getting hammered with like, 200k keys because I didn't know Bull doesn't do any automatic cleanup.

Now, when I do .empty() on load, the jobs still process.

When I do .clean(5000), I get

```
Unhandled rejection TypeError: Cannot read property 'timestamp' of null
    at /home/brandon/server/node_modules/bull/lib/queue.js:675:19

```

Please, please tell me what I am doing wrong.

Edit: I'm doing job.remove(), checking redis keys, still there. Restart the app, starts reprocessing all of the jobs. Absolute nightmare.

**Comment by albertjan** [comment]
Are the job id's on the `completed` list after it's done? Are you calling the `done` callback or resolving a promise from within your job handler?

In general it doesn't matter there are jobs in the database, bull will only look at the `wait` and `active` lists for jobs to process.

Could you find the job hash that produced the error you mentioned?

`empty` is not meant to clean the queue it's supposed to resolve when all jobs are done processing.

`clean` how ever should empty the queue but it needs the timestamp to determine the age of the job. 

I do think it should have handled the missing timestamp better though.

**Comment by brandonros** [comment]
I am resolving a promise from within my job handler.

Wouldn't it make sense to add an option to expire completed jobs? I've had 10 users create 200k jobs in under 3 weeks

Even when I call .clean() and it succeeds, nothing is actually cleaned.

**Comment by manast** [comment]
The clean method is quite new, it may have some bugs in it, I have to take a closer look to it:
https://github.com/OptimalBits/bull/pull/130

**Comment by brandonros** [comment]
@manast I think I'm going to have to drop Bull from my project. It doesn't look like jobs that fail are being cleanly removed. New instances that spawn seem to pick up the old jobs, and the next thing I know, I'm rate limited by the external API servers. I am sure I am doing something wrong.

**Comment by manast** [comment]
@brandonros I will look into this as soon as I can, unfortunately I have a lot on my plate right now. If you check the issues labeled with questions you can find similar problems as the one you describe and different ways to resolve it.

**Comment by albertjan** [comment]
@brandonros thats absolutely not the experience we have with bull. We've been running with it production for a while now, I've never seen bull pickup a job that had failed earlier.

Are you sure your jobs are being moved to the `failed` or `completed` set after processing?

I'll see if I can spend some time on the `clean` method this week. We've been able to do without so far, but it will come up at some point.

**Comment by brandonros** [comment]
@albertjan Are those all of the changes that you needed to make for the `.clean()` method? 

There's currently no issue to set an expiration for jobs, correct?

**Comment by albertjan** [comment]
@brandonros yes for as far as I can see this should do it :smile:. No there's no way to expire jobs atm.

**Comment by brandonros** [comment]
Tell me what information I can provide to fix this.

queue.count() resolves 0, .empty() and .clean() resolve, but old jobs are still being added to the queue (and piling up).

**Comment by ryan-sandy** [comment]
Doing `q.clean(5000)` will only clean *completed* jobs. `q.clean(0, 'active')`, will clean all active jobs.

To completely "empty" the queue run this:

```
Promise.all([
  q.clean(0, 'active'),
  q.clean(0, 'waiting'),
  q.clean(0, 'delayed'),
  q.clean(0, 'failed'),
  q.clean(0, 'completed')
]).then(function () {
  //q is empty
});
```

However, any jobs actively being processed will complete.

BTW, we will need the changes from the pull request for this to work. When I wrote the clean method I didn't realise that jobs could have not have a timestamp. Sorry!
