### ISSUE TITLE
Restart a running job

### ISSUE THREAD

**Issue by andyfo** [OptimalBits/bull#1560]
Hello! 👋

I have a job that looks like this:

```
(job, done) => {
  setInterval(() => console.log('I live.', 10000));
  const run = async () => {
    await SomeComplicatedUnreliableMachinery();
    done();
  };
  run().catch((err) => console.log(err));
}
```

From time to time, the `await SomeComplicatedUnreliableMachinery()` method gets stuck so its promise never resolves and `done()` is never called.

I know the job processor is still responsive because the interval keeps running.

When a timeout is hit (code not shown in the example above), I want to restart the job.

1. Can a job be force-restarted from the processor itself?
2. Or what would be the proper sequence of commands that would kill a running job and put it back into queue?

Thank you! 🖖

**Comment by stansv** [comment]
Hello! Use both `timeout` and `attempts` for this:

```
queue.add({ job: "data" }, { attempts: 10, timeout: 5000 });
```

https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd

**Comment by andyfo** [comment]
Thanks for replying!

The problem is that the "complicated" method may legitimately run 5 secs or 30 minutes. You never know. That's why there has to be some dynamic retry mechanism. Like "all is good if the method emits an event every now and then".

**Comment by stansv** [comment]
OK, you can check for the status of your "SomeComplicatedUnreliableMachinery" in a process callback manually; use `setInterval` to check if last heartbeat event was too long ago and call `done()` with error to fail job. Don't forget to clear the timer returned by `setInterval()`.

**Comment by andyfo** [comment]
Oh sure, using `done()` with parameter 🤭thanks!

On a related note, considering a proper design, would you advise to try to break down long-running jobs into as small/short-running chunks as possible (i.e. many jobs instead of one, say, when the smaller jobs order doesn't matter), or are long-running jobs just fine?
