### ISSUE TITLE
multiple jobs add 

### ISSUE THREAD

**Issue by FilipeMazzon** [OptimalBits/bull#1562]
I wondering if it's possible or can be possible add more then one job each time, today I use this away:

tasks.map((task) =>{
   bull.add("sometask",task);
})

but in this way, I can't have atomicity, and I think its to slow because of entering in DB a lot of times.

I want to be like this 

bull.add("sometask",tasks);

tasks will be an array of tasks. and then they create all at once.

I need because I need to put in the queue a lot of queries to execute in parallel in multiple clusters.

**Comment by manast** [comment]
You can use ```addBulk``` https://github.com/OptimalBits/bull/blob/develop/lib/queue.js#L706
I thought it was already documented, but I was wrong...

**Comment by FilipeMazzon** [comment]
@manast, it's possible to give a options like in add? I want to delete after completed.

**Comment by manast** [comment]
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueaddBulk
