### ISSUE TITLE
moved to waiting list instead moved to failed list when using movetofail method

### ISSUE THREAD

**Issue by abdolrhman** [OptimalBits/bull#1564]
## Description
used AddBulk to add array of jobs,
i didnt create a processor so i expected those jobs to go to error queue as there is no handler for them,
yet they went to the waiting list

my code:-
```
/**
 * First Wave
 * Get All Orders And Add Theme in Queue
 * @returns {Promise<*>}
 */
async function getRushOrders() {
  let data = await orderHelper.getOrders();
  let orders = data['Order'];

  for (let order of orders) {
    const orderFileName = `sgFiles_${order['Order_ID']}_${order['subOrder_ID']}_${order['ScanID']}_${order['DocID']}`;
    order['fileNameInServer'] = orderFileName;
    order['filePath'] = '/home/cp.3ddx.com/www/conn/' + orderFileName;
    order['opts'] = {
      jobId: order['Order_ID']
    }
  }
  RushQueue.addBulk(orders);
}

getRushOrders().then(r => {
  console.log('data', r);
});

```

## Bull version
@latest

**Comment by manast** [comment]
The information you provided is not enough to reproduce nor to understand the issue.

**Comment by abdolrhman** [comment]
@manast , thank you for replaying i understand the effort you guys do,
really apperciate all the work you do,
i have edited the question with full code ,

if i could do any thing to help maintain such great work, please let me know,
thank you

**Comment by abdolrhman** [comment]
@manast also i have seen alot of redundant questions that have been asked,
what do u think about creating a readme like refernce and patterns , for the most asked questions ?
i can help in that :)

**Comment by manast** [comment]
ok, so what is the issue? If you do not have a worker running when you add your jobs they stay in the queue, thats the expected behaviour.

**Comment by abdolrhman** [comment]
i thought they go to the failed queue, with the reason of that they faild because there is no handler ? 
right ?

**Comment by manast** [comment]
no. They wait until a worker is available.

**Comment by abdolrhman** [comment]
Great thanks bro :) ,, have a great night, 
also what do u think about create frequent questions page ? @manast
