### ISSUE TITLE
Named Jobs Order of processing

### ISSUE THREAD

**Issue by avinkavish** [OptimalBits/bull#1565]
Quick Question, do named jobs get processed as soon as a named processor is free or do they sit in queue in the order of insertion till other named jobs in front of them are done?

**Comment by abdolrhman** [comment]
what i did got when i test such thing is,
if there are no process functions at all in your code, all jobs you insert it will be in the faild queue,
rather if there is a processor but handel diffrent names of jobs, the jobs you insert it will be in the waiting queue, waititng tell you create another function that handel this jobs that waiting in the queue,

- also you control the Active list by insert a concurency number in the processor function.

**Comment by manast** [comment]
@abdolrhman your answer is not accurate. Jobs only fail if they throw an exception. Named jobs are confusing in that you need to define all of the handlers for every job name, or none.

**Comment by abdolrhman** [comment]
Ohhh, thanks buddy i got this now @manast

**Comment by avinkavish** [comment]
@manast I have 3 job types A, B and C. I want jobs of A, B and C to run in the respective order, but the order of insertion is not guaranteed. However, I can notify when all jobs of each type have been queued. What is the best way to implement this?

**Comment by stansv** [comment]
@avinkavish you can save data related to your jobs A, B and C somewhere else (in Redis, MongoDB, SQL database) and once all are collected move A, B and C to queue one by one.
