### ISSUE TITLE
queue that wait for another queue 

### ISSUE THREAD

**Issue by abdolrhman** [OptimalBits/bull#1566]
## Description
So basically i have two queues, i want to make one of them wait the other queue till it finishes all the items on it,
then it can process its own items,
so for example,
- queue A had 3 items
- queue B waiting queue A then process its items

is some thing like an event to wait queue till it finish its items ?
if there are not , is there a way to make a queue procss its item more fast then another queue?
@manast 
thanks :)

## Bull version
@latest

**Comment by manast** [comment]
This is supported in BullMQ flows: https://docs.bullmq.io/guide/jobs/flows
