### ISSUE TITLE
job completed, but didn't get any event and also not getting process event

### ISSUE THREAD

**Issue by afzalahmad578** [OptimalBits/bull#1568]
i want to update my db data after some times, when some event occur, 
eg: there is booking system, i want to see payment  status of booking after 6 minutes when booking is created.
i created queue for the same, in every booking i added the data in queue with delay time and data added successfully when i tested, but frequently i did not get process event call in my code while job completed after 6 minutes and also not getting completed event. please help me.

In the image booking_id WOOMF595 is in completed state i did not get any callback or event

Thanks
![seat_issue](https://user-images.githubusercontent.com/42282228/69523629-60134300-0f8a-11ea-8291-c2d3c2afeb04.png)

**Comment by manast** [comment]
Can you provide source code that reproduces the issue?

**Comment by afzalahmad578** [comment]
Hi Manast,
Thanks for response, and sorry for late reply,

Here is my code, in my scenario  there are multiple projects running on same dev redis server , and when i connect with my local redis server it's working fine.


const Queue = require('bull');
import { DB } from '../config';
import { APP } from '../constants';
import { BullManagerClass } from "../libs/bullQueueManager";

const bullManager = new BullManagerClass();

export class BullClass {

    private classStatusQueue: any;
    private slotStatusQueue: any;
    private seatLockingQueue: any;
    private splitCancelQueue: any;
    private userSessionQueue: any;
    private chatCompleteQueue: any;
    private chatExpireQueue: any;

    constructor() {
        this.classStatusQueue = new Queue(APP.JOB_PLAN.CLASS_STATUS, DB.REDIS);
        this.slotStatusQueue = new Queue(APP.JOB_PLAN.SLOT_STATUS, DB.REDIS);
        this.seatLockingQueue = new Queue(APP.JOB_PLAN.SEAT_LOCKING, DB.REDIS);
        this.splitCancelQueue = new Queue(APP.JOB_PLAN.SPLIT_CANCEL, DB.REDIS);
        this.userSessionQueue = new Queue(APP.JOB_PLAN.USER_SESSION, DB.REDIS);
        this.chatCompleteQueue = new Queue(APP.JOB_PLAN.COMPLETE_CHAT, DB.REDIS);
        this.chatExpireQueue = new Queue(APP.JOB_PLAN.EXPIRE_CHAT, DB.REDIS);
    }

    async createJob(jobData: BullJob, processTitle: string) {
        try {
            let remainderTimeMs = processTitle !== APP.JOB_PLAN.USER_SESSION ? (jobData.reminderAfter * 60 * 1000) : jobData.reminderAfter;
           

            if (processTitle === APP.JOB_PLAN.CLASS_STATUS) {
                
                this.classStatusQueue.add(jobData, { delay: remainderTimeMs });

            } else if (processTitle === APP.JOB_PLAN.SLOT_STATUS) {
                
                this.slotStatusQueue.add(jobData, { delay: remainderTimeMs });

            } else if (processTitle === APP.JOB_PLAN.SEAT_LOCKING) {
                
                this.seatLockingQueue.add(jobData, { delay: remainderTimeMs });

            } else if (processTitle === APP.JOB_PLAN.SPLIT_CANCEL) {
                
                this.splitCancelQueue.add(jobData, { delay: remainderTimeMs });

            } else if (processTitle === APP.JOB_PLAN.USER_SESSION) {
                
                this.userSessionQueue.add(jobData, { delay: remainderTimeMs });
            }
            else if (processTitle === APP.JOB_PLAN.COMPLETE_CHAT) {
               
                this.chatCompleteQueue.add(jobData, { delay: remainderTimeMs });

            }
            else if (processTitle === APP.JOB_PLAN.EXPIRE_CHAT) {
                
                this.chatExpireQueue.add(jobData, { delay: remainderTimeMs });

            }
        } catch (error) {
    
            return error
        }
    }


    async fetchJob() {
        try {

            this.classStatusQueue.process(async function (job, done) {
     
                await bullManager.updateClassStatus(job.data.data);
                done();

            });
            this.slotStatusQueue.process(async function (job, done) {
               
                await bullManager.updateSlotStatus(job.data.data);
                done();

            });
            this.seatLockingQueue.process(async function (job, done) {
               
                await bullManager.updateSeatLockingData(job.data.data);
                done();

            });
            this.splitCancelQueue.process(async function (job, done) {
                
                await bullManager.updateCancelBookingStatus(job.data.data);
                done();

            });
            this.userSessionQueue.process(async function (job, done) {
               
                await bullManager.updateUserSession(job.data.data);
                done();

            });
            this.chatCompleteQueue.process(async function (job, done) {
                
                await bullManager.updateCompleteChatStatus(job.data.data);
                done();

            });
            this.chatExpireQueue.process(async function (job, done) {
               
                await bullManager.updateExpireChatStatus(job.data.data);
                done();

            });

            
        } catch (error) {
           
            return {}
        }
    }

}

Initialise with following code during the code run:
let { BullClass } = require("../libs/")
const BullLib = new BullClass();
BullLib.fetchJob();

**Comment by manast** [comment]
use either async/await or done, but not both.

**Comment by afzalahmad578** [comment]
Thanks for response
will try and let you know

**Comment by afzalahmad578** [comment]
i tried both one by one, but it  did not resolve the issue
