### ISSUE TITLE
Question: How to configure repeatable job to skip the current iteration if previous is still runnning (not stalled)?

### ISSUE THREAD

**Issue by mintuhouse** [OptimalBits/bull#1570]
https://github.com/OptimalBits/bull/issues/612 briefly mentions the case but it is not clear to me what the final solution is?
Is there a way currently configure this behaviour?

Say I schedule a job every 10s
if run1 takes 22s
I want to skip run2 and run3

**Comment by manast** [comment]
Did you try and it did not work as you expected?

**Comment by mintuhouse** [comment]
I have `repeat: {every: 10000}` and my job sometimes takes more than a minute and bull has started multiple instances of it.

`> hget <jobkey> opts`
`{"repeat":{"count":502,"every":1000},"jobId":"repeat:e65b31a3c7ad2f60c930d92c00ac79a3:1574511189000","delay":0,"timestamp":1574511189298,"prevMillis":1574511189000,"removeOnComplete":1000,"removeOnFail":false,"attempts":1}`

**Comment by stansv** [comment]
Hi! I think everything works as expected. If you have multiple workers (or set concurrency > 1) then multiple repeatable jobs can run simultaneously. When job is started, Bull creates next instance of repeatable job in delayed queue, so one of solutions is to ensure there's always exactly one worker with default concurrency=1 processing jobs for your queue. If Bull would have an option to create next repeatable job when current is finished (rather when started), it would work as you need.

Alternatively, you can implement it without repeat options at all, manually put next job to the queue once current is completed, like:

```
queue.process(async (job) => {
  try {
    // your job logic
  } finally {
    const delay = Math.max(1000 - (Date.now() - job.timestamp), 0);
     queue.add({ abc: "def" }, { delay });
  }
});
```

**Comment by mintuhouse** [comment]
For now I have implemented a hacky singleton behaviour using below code as first step in my handler function
```javascript
if (this.singleton) {
    const activeJobs = await this.queue.getActive() // TODO: Confirm that order or activeJobs is the order in which they are started
    if (activeJobs[0].id !== job.id) {
    debug(`Skipped processing job: ${job.name}:${job.id}`)
    throw new Error('Singleton: Previous job still running')
    }
}
```
