### ISSUE TITLE
Question: Proper use of `endDate`

### ISSUE THREAD

**Issue by mattcollier** [OptimalBits/bull#1573]
## Description
I'm using a repeatable job that I would like to run ever 90 seconds for the next 30 minutes (duration).  The job is running every 90 seconds as expected, but it continues to continue firing every 90 seconds after the `endDate`

```
  await queue.add('monitorNodes', data, {repeat: {
    jobId: uuid(),
    every: 90000,
    // end monitor 10 secs before the end of the stage
    endDate: Date.now() + data.duration - 10000,
  }});
```

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
Usage is here:
https://github.com/digitalbazaar/bedrock-ledger-test-orchestrator/blob/elector-pool/lib/node-api/job-process.js#L131-L136

## Bull version
3.12.1

## Additional information
Thank you!

**Comment by rohitkhatri** [comment]
I'm also trying to understand how to repeat a job until certain time, but it doesn't seem to be clear, can anyone help?

**Comment by manast** [comment]
@rohitkhatri is endDate not working for you?

**Comment by rohitkhatri** [comment]
Yes, It's not working in conjunction with repeat, here's what I'm trying:

Below is the code I'm trying, but It doesn't stop after 1 minute, It keeps running

```
const endDate = new Date();
endDate.setMinutes(endDate.getMinutes() + 1);
queue.add('status_check', { id: 'skdjhfksdhf' }, {
    repeat: {
        endDate: endDate,
        every: 1000
    }
});
```

**Comment by Cabritone** [comment]
Same Problem here. 
I'm using the `cron` and `endDate` but seems that is ignoring the `endDate` 💭 

```
let timeObject = new Date()
timeObject = new Date(timeObject.setTime(timeObject.getTime() + 1000 * 30))  //30 seconds

queue.add(
    data,
    {
        repeat: { cron: ' */5 * * * * *' },
        endDate: timeObject,
    }
)
```
