### ISSUE TITLE
Problem atomic ops

### ISSUE THREAD

**Issue by thuri0n** [OptimalBits/bull#1576]
## Description
I've already created a issue https://github.com/OptimalBits/bull/issues/1575 and made a demo in order to reproduce the problem => https://github.com/thuri0n/test-bulljs
The problem is the sequence of actions. The first process starts simultaneously with the second.

**Console server output**
queue.add request.id => 1
queue.add request.id => 2
queue.add request.id => 3
queue.add request.id => 4
process start job.id => 1
process start job.id => 2
process middle job.id => 2, await - 305 ms
process middle job.id => 2, await - 115 ms
process end job.id => 2
completed job.id => 2
process start job.id => 3
process middle job.id => 1, await - 483 ms
process middle job.id => 3, await - 99 ms
process middle job.id => 3, await - 101 ms
process end job.id => 3
completed job.id => 3
process start job.id => 4
process middle job.id => 4, await - 308 ms
process middle job.id => 1, await - 848 ms
process end job.id => 1
completed job.id => 1
process middle job.id => 4, await - 803 ms
process end job.id => 4
completed job.id => 4

Maybe I'm doing something wrong?

## Bull version
3.12.1

**Comment by manast** [comment]
As mentioned before, we need a simple test case that demonstrates an issue/bug with bull. Your example includes third party code, like socket.io. 
If you can isolate the exact bug, explain what is your expectation and what you are getting instead we can try to solve the issue.

**Comment by thuri0n** [comment]
Oh, I found my mistake. Connection socket.io worked several times and accumulated the process.on queue, which was the problem of 'parallel' processing
