### ISSUE TITLE
Can't retry job when it's locked. Error handling does not catch it.

### ISSUE THREAD

**Issue by adame21** [OptimalBits/bull#1578]
Hi,
Great package - many thanks.
I'm getting this: 
Error: Couldn't retry job: The job is locked
When i'm retrying my failed jobs.
I understand that a locked job can not be retried - I added this error handling to avoid getting "unhandledRejection":

				try {

					failedJob.retry();

				}
				catch (err) {

					logger.debug(`Queue: skipping retry on job ${failedJob.data.transactionId}, job locked in process.`, {})

				}

But I'm still getting this:

Error: Couldn't retry job: The job is locked
    at scripts.reprocessJob.then.result (/app/node_modules/bull/lib/job.js:315:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Please mind the stack.

**Comment by manast** [comment]
can you provide an example that reproduces the issue?

**Comment by adame21** [comment]
Hi,
I'm getting this issue on a pretty big project with a lot of modules.
I will work today towards reproducing the issue in a small block of code to show you.
Please keep open for now while I get the example.
Thanks :)

**Comment by adame21** [comment]
Hello,

While trying to reproduce I understood that I was using the retry feature wrong.

I should've just trusted the lib's options :)

Thanks!

**Comment by jacklee814** [comment]
@adame21 how to fix this problem? I got too :(
