### ISSUE TITLE
Question: Proper way to update job

### ISSUE THREAD

**Issue by kand617** [OptimalBits/bull#1581]
## Description
We have a process where we would like to 
 - create jobs by assigning a jobId using a unique id e.g userid
 - update the data for a given job if the job is not active (i.e not picked up yet)
 - if a job is active, we try to create a job later after a few minutes. 

Question:
I want to know how bull js works what is the recommend approach for implementing the updated behaviour?

Approaches
- Simply adding a new job with the jobId does not work (as per the docs).
- We can check if there is a job and go by its job.getState(), but then its not distributed safe as you state can change since retrieval....

Am I meant to get the job.lock() or something similar....

**Comment by stansv** [comment]
Hi! This is too specific to add support of this to Bull. Good solution is to write Redis Lua script to update non-active job atomically with hset. Return value can be used to check if job was running.

https://github.com/luin/ioredis#lua-scripting

**Comment by kand617** [comment]
Hi @stansv 

Thank you for the reply. 

I guess what I am after is atomic updates of job if and only if the the job is not in progress. 
The tricky part for is given a job id how to identify the non-active job and keep it non-active while update is done.

Can job.lock() assist in this? It does not seem to be part of the public api though

**Comment by stansv** [comment]
@kand617 this is why I suggested lua script, it's executed atomically. You can find examples of lua scripts in Bull sources.

https://github.com/luin/ioredis#lua-scripting
