### ISSUE TITLE
Queue disappears randomly

### ISSUE THREAD

**Issue by cakerake** [OptimalBits/bull#1582]
I have a few delayed jobs that keep running as crons.

My queue keeps randomly disappearing after 5-7 hours

I think there may be a misconfiguration with my redis and I'd like some help to fix this issue.

Here is the error

`BRPOPLPUSH { ReplyError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.`

**Comment by stansv** [comment]
This is not related to Bull, you should figure out why your Redis cannot write a snapshot to disk (probably no space left on your device). There're many suggestions around the internet, for example, https://stackoverflow.com/a/21484282/1848640
