### ISSUE TITLE
Bull processing multiple jobs at once in case of separate process despite of concurrency value

### ISSUE THREAD

**Issue by shivgarg5676** [OptimalBits/bull#1583]
I am defining my process by passing it the path to file containing process function so that it runs as a separate process.
My code looks like something this 
```
queue.process(1,__dirname + '/processor.js');
```
Here, I want Bull to process 1 job at a time. But I can see it starts processing multiple jobs at a time(4-5). 
If instead of passing a path to processor.js I am passing a function. In that case, it runs on the same thread. But I am getting desired results.

Is there any way I can pass filePath so that it runs on a separate process but also run 1 job at a time?

**Comment by manast** [comment]
Can you please provide a complete example that demonstrates the issue?

**Comment by ElvisYang** [comment]
it is very easy for us to reproduce, just make the job running more than 2 hours. the code draftly like
```
for await (const data of stream) {
  // process data
  await new Promise(resolve => setTimeout(resolve, milliseconds));
}
```
