### ISSUE TITLE
docs: link to arena repository which has been archived

### ISSUE THREAD

**Issue by kirit0s** [OptimalBits/bull#1584]
## Description
Documentaiton uses link for arena — https://github.com/mixmaxhq/arena. This repository has been archived by the owner. It is now read-only. And this was a fork from https://github.com/bee-queue/arena.

Why not use original repo — https://github.com/bee-queue/arena?

**Comment by manast** [comment]
because the author of bee-queue refused to acknowledge or credit that he used source code of bull in his implementation, so I will not link to anything related to that repo.
