### ISSUE TITLE
UIs Taskforce link

### ISSUE THREAD

**Issue by JoHuang** [OptimalBits/bull#1587]
## Description

I would like to try third party UIs.
When clicking the "Taskforce" link in README.md, I can't find the open source repo.
Is there a "Taskforce" repo which contains an open source UIs library?

Or any official recommended UIs libs?

Thanks

**Comment by manast** [comment]
Taskforce is commercial only and helps sponsoring the development of Bull, but the rest of the UIs in the README are open source.
