### ISSUE TITLE
Need more details in using tz (timezone) option of RepeatOpts.

### ISSUE THREAD

**Issue by royalpinto** [OptimalBits/bull#1588]
I could not find any details on how exactly to use the `TZ` field of `RepeatOpts`. Can I specify the timezone offset here? Like: `+04:00` or it has to be a standard timezone name like `Asia/Dubai`. If timezone name is required, is it based on some standard that I can look into?
Thanks

**Comment by royalpinto** [comment]
After going through the code, it looks like the `tz` value will be passed to `cron-parser` library which internally uses the `moment-timezone` lib for the timezone handling. So, we can use the timezones defined in the `moment-timezone` lib. Thanks

**Comment by jatinsandilya** [comment]
@royalpinto Did you figure out a solution to add a custom timezone for a repeatable? I can't find anything online on it.
