### ISSUE TITLE
It it possible to preserve order when using multiple workers (concurrency)?

### ISSUE THREAD

**Issue by reinoute** [OptimalBits/bull#1589]
Can Bull guarantee the order in which messages are being processed when using multiple workers?

ActiveMQ has [two solutions for this](https://activemq.apache.org/how-do-i-preserve-order-of-messages): Exclusive Consumer and Message Groups. Amazon has [FIFO queues](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html). I couldn't figure out from the documentation if Bull has a solution for this.

Some context:
We're building a chat bot and we want to (1) process incoming messages from the user in the order they are sent by the user and (2) sent (multiple) outgoing messages to the user in the correct order.

---edit---
I believe (1) can be solved using `Queue.getJobs()`, and ignoring messages from the user if the queue already contains a message for that user.

**Comment by stansv** [comment]
Hi! Short answer is no. The only way to achieve the order is to create queues per each worker, this would work similar to consumer groups. Then you should explicitly map each specific user to one of these queues (round-robin or randomly). You can store mappings in Redis, for example:

```
user1 -> worker1
user2 -> worker2
user3 -> worker1
user4 -> worker2
...
user500 -> worker2
```
Obviously you cannot use bull's concurrency setting, each queue should be processed by only one worker. Though queue is usually selected by calculating hashes, as in ActiveMQ or Apache Kafka, this approach adds some complexity.

**Comment by reinoute** [comment]
Thanks for your response, @stansv 

As an alternative, [some people recommend](https://sookocheff.com/post/messaging/ordered-messaging-in-an-unordered-world/) to attach a sequence number to a message and store the same sequence number in some persistent store.

If we process a new message from the queue and it's not the last message for that user, then we add it back to the queue. Do you see any potential problems with this solution?

I considered the option that the last message can not be processed, and as a result, all messages after that will be "in an infinite loop" being added back to the queue. But maybe it's not a problem at all?

**Comment by stansv** [comment]
Hmm, in this way you'll process messages in inverse order right or I missing something? Sequence number allows to easily find latest message in a queue but I thought you need to process messages from first to last. You can store both last message number per each user and current user message number, first is incremented when new message (bull job) added, and second is incremented when bull job is finished — with either `failed` or `completed` state. And you already have Redis, use it for sequences. I believe this will work. But note that your solution requires many extra work to return jobs back to queue, so affects the throughput.

My previous suggestion with user-to-worker mapping is the simplest if you still want to use Bull. You just need to decide how to up/down scale, i.e. handle situations when number of workers changes.

**Comment by JanYork** [comment]
Is it still not possible to implement FIFO for multiple processes? Can I manually get the Job, or make it so that only one message is processed at a time in the case of multiple identical consumers, and the next one starts after the processing is completed?

**Comment by manast** [comment]
@JanYork this can be achieved with BullMQ Pro by defining a group with max concurrency 1: https://docs.bullmq.io/bullmq-pro/groups/concurrency

**Comment by JanYork** [comment]
> @JanYork this can be achieved with BullMQ Pro by defining a group with max concurrency 1: https://docs.bullmq.io/bullmq-pro/groups/concurrency

Thank you, but I have implemented the sequential consumption of multiple workers. It can keep the queue in order no matter how many workers there are in a distributed manner. This is what I did. It should be OK, right?

```js
limiter: {
max: 1,
duration: 5000,
}
```

**Comment by JanYork** [comment]
> > @JanYork this can be achieved with BullMQ Pro by defining a group with max concurrency 1: https://docs.bullmq.io/bullmq-pro/groups/concurrency
> 
> Thank you, but I have implemented the sequential consumption of multiple workers. It can keep the queue in order no matter how many workers there are in a distributed manner. This is what I did. It should be OK, right?
> 
> ```js
> limiter: {
> max: 1,
> duration: 5000,
> }
> ```

This will ensure that all messages in this queue are consumed sequentially until the previous task is completed before starting the next one.

**Comment by manast** [comment]
This will work as long as the job never takes more than 5 seconds.

**Comment by JanYork** [comment]
> This will work as long as the job never takes more than 5 seconds.

hi, excuse me, it's like this: if the queue is directly configured for flow limiting (set concurrency max to 1), then different job_id their consumption can't be concurrent, I want to make the tasks with the same job_id in the queue are serial without affecting the consumption of the tasks with other job_id.

Is this doable?

**Comment by JanYork** [comment]
> > This will work as long as the job never takes more than 5 seconds.
> 
> hi, excuse me, it's like this: if the queue is directly configured for flow limiting (set concurrency max to 1), then different job_id their consumption can't be concurrent, I want to make the tasks with the same job_id in the queue are serial without affecting the consumption of the tasks with other job_id.
> 
> Is this doable?

I've tried to implement this requirement by creating a queue for each job_id, but this doesn't seem to scale my business dynamically.
