### ISSUE TITLE
Question: Cluster vs. Sandboxed processes

### ISSUE THREAD

**Issue by oavanruiten** [OptimalBits/bull#1590]
## Description
I came across the following documentation: https://github.com/OptimalBits/bull#cluster-support

It mentions that from 3.2.0 and above it is recommended to use threaded processors.

I am currently using sandboxed processes. Should I consider using a cluster on top or instead of these sandboxed processors and why?

## Bull version
3.10.0

**Comment by marshalys** [comment]
sandboxed processes is threaded processors, see:
https://github.com/OptimalBits/bull/pull/689
