### ISSUE TITLE
Question: adding task to offline queue before first connection to Redis

### ISSUE THREAD

**Issue by TheOptimisticFactory** [OptimalBits/bull#1593]
Hi,

I have been trying to figure out how offline queue works so that tasks would be silently added into a queue while Redis is getting started (or rebooted). This behavior as well as the reconnection mechanism works as expected as long as Bull successfully connected to Redis once.

But in the event of Redis being offline at startup, it throws an error despite having offline queues enabled. 

I couldn't figure out if there is any way to slience this error and still have tasks waiting for when Redis is gonna be online.

Kind regards.

**Comment by stansv** [comment]
This is not directly related to Bull, as offline queues is ioredis feature https://github.com/luin/ioredis#offline-queue
