### ISSUE TITLE
Missing lock for job finished

### ISSUE THREAD

**Issue by ElvisYang** [OptimalBits/bull#1594]
It actually a question here: 

We are facing "Missing lock for job ${jobId} finished" error when the job is running about 2 hours. it is very stable for us to reproduce. is there some idea why this happen? redis key deleted or job timeout?

**Comment by stansv** [comment]
See https://github.com/OptimalBits/bull/issues/1591

**Comment by ElvisYang** [comment]
@stansv this is really what I want, Thanks and I will try it

**Comment by stansv** [comment]
@ElvisYang great, hope this would be helpful.
