### ISSUE TITLE
Code inside process doesn't get executed

### ISSUE THREAD

**Issue by ankitjena** [OptimalBits/bull#1597]
## Description
I'm using bull to do a get request to a url, which provides a response sometimes later. But due to some reason my code inside process doesn't get executed at all.

## Minimal, Working Test code to reproduce the issue.
```
var requestQueue = new Queue('decrypt text', 'process.env.REDIS_URL')
  console.log('queue created')
  requestQueue.process(async (job, done) => {
    console.log('job started')    //this does not get logged
    const response = await axios.post('https://pirate-encrypter.factset.io/decrypt', {
      text: req.body.text
    })
    const decryptedText = Object.values(response.data)[0]
    client.set('decryptedtext', decryptedText)
    done()
  })
```
#### Output
`queue created`

Only output

## Bull version
3.12.1

**Comment by facejiong** [comment]
my code sometimes got executed,i do not know why

**Comment by ankitjena** [comment]
You have to add the job to the queue before processing. I was missing that. @facejiong might be your case

**Comment by timussharma** [comment]
Same Issue I am Getting

**Comment by timussharma** [comment]
@ankitjena
