### ISSUE TITLE
queue.clean doesn't delete job logs

### ISSUE THREAD

**Issue by tomgrossman** [OptimalBits/bull#1599]
## Description
`queue.clean()` doesn't delete job logs.
looking at the `cleanJobsInSet-1.lua` script, it removes the jobs from the set list with `LREM` or `ZREM`, and deletes the job itself with `DEL`, but it doesn't remove the logs.
need to add in the end:

```lua
local logKey = jobKey .. ":logs"
redis.call("DEL", logKey)
```

## Bull version
3.11.0

**Comment by gabegorelick** [comment]
I think this can be closed now that 3.13.0 is out.
