### ISSUE TITLE
Docs: job.progress allows anything

### ISSUE THREAD

**Issue by smaznet** [OptimalBits/bull#1604]
## Description
in [reference](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#jobprogress) page said `job.progress` allows a number between 0 and 100
but actually it also allows passing object and other things

**Comment by ganeshcse2991** [comment]
Added Number type check to the Job Progress field

https://github.com/OptimalBits/bull/pull/1607

**Comment by manast** [comment]
Corrected now.
