### ISSUE TITLE
Poison messages at Job level and Data level

### ISSUE THREAD

**Issue by adame21** [OptimalBits/bull#1606]
Hi,
I've been using this lib for a while, recently something new started to happen.

I'm getting 2 different types of "poison messages":

1. Where job's data is an empty object as in:
````javascript
job.data //{}
````
and I'm sure I didn't add a message like this.
I'm able to handle these as they still have the job metadata itself.
I'm trying to use job.discard() to get rid of these, good idea?

2. Where job itself is NULL.
I'm lost about this one.
It crashes my Bull Arena UI, I cant remove it or view it properly.
And most of all I don't know what is the reason for this.
Once again, I'm sure i wasn't adding a message like this, I don't even know how that would be possible.
Just to be clear - I can't use things like job.discard() or job.moveToFailed() since job ITSELF is NULL.

Is there a pattern to handle these correctly (best practice) ?
Is there a way to avoid these? especially 2
Are there known reasons or bad practices that could generate these?
Am I missing something obvious? I couldn't find any related issue.

Thanks :)

**Comment by stansv** [comment]
Normally Bull doesn't produce jobs with empty data/any kind of "null"s in Redis, so I can only suggest to search for bugs in your code more thoroughly.. in 1st case, make sure you're not providing a promise object as job data when adding new job to queue.

**Comment by adame21** [comment]
Hi,
Then there's definitely something fishy in my code. I'll look into it.
Are there any hints or common mistakes for 2nd case?
Also for 1st case I am sure I always add data synchronously never a promise, any other leads you could point me to?

I appreciate the reply and am not expecting you to debug my code haha just if you ever ran into this before i'd be happy for a hint.

Thanks!

**Comment by stansv** [comment]
I can only suggest to use some Redis client to investigate queue data structures there to find which jobs are getting corrupted

**Comment by adame21** [comment]
Got it, ill look into it. 
thanks
