### ISSUE TITLE
Question about properly failing async jobs

### ISSUE THREAD

**Issue by adame21** [OptimalBits/bull#1609]
Hi,

I have a pretty small and quick question.

Let's say I'm running async jobs in my worker (queue.process), and i'm passing it (job,done)
So in case the job is done i simply call done()
If the job failed, what would be the correct way to handle this?
1. to use manually job.moveToFailed()
2. throwing an error - would that somehow let the queue know the job should be failed? (my whole process is covered in try-catch)
3. secret option number 3 I dont realize?

I've read the documentation, but I couldn't find a clear pattern to this, I'm sorry if its a silly question or obvious in the documentation.

Thanks for this amazing lib.

**Comment by stansv** [comment]
The "secret option" is to pass error object as first arg of done() function.

https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueprocess

**Comment by adame21** [comment]
Understood.
Thank you very much.
