### ISSUE TITLE
Is that normal to create 3 redis connections for 1 queue?

### ISSUE THREAD

**Issue by misterjt** [OptimalBits/bull#161]
I just want to know will it be hard for redis to serve 2000 queues?
For example, kue uses only 4 connection for all queues.

**Comment by albertjan** [comment]
Because bull depends on a blocking call for job signaling you need atleast 2 connections per queue. Otherwise you wouldn't be able to send jobs. The third client is used to receive messages about new jobs and delayed jobs.

**Comment by misterjt** [comment]
Ok, i dont mind. 
Just want to know, is that hard for redis to keep 6000 connections (2000 queues, 2 queue per 1000 users)?

**Comment by albertjan** [comment]
You'll need a propper server but there's no reason why redis can't do it. :smile:

**Comment by adityabansod** [comment]
I've recently had problems with ETIMEOUTs with my connection count goes >2200 (or so). My guess is it's the number of blocking connections that bull keeps open.

Has anybody had a simliar issue?
