### ISSUE TITLE
Force random processing instead of FIFO/LIFO?

### ISSUE THREAD

**Issue by Niek** [OptimalBits/bull#1612]
## Description

As far as I can see it's only possible to process jobs in a FIFO or LIFO manner. In our use case we'd like to process all jobs (that have the same prioritization) in a random order. Is that possible?

One workaround I thought of is using a random priority range when adding the job. Is there any other "proper" way of doing this?

**Comment by stansv** [comment]
Can you please explain a bit more you case. e.g. why you want to process jobs randomly? Bull is a queue-based job engine so jobs are processed always in order determined by their positions in queue. There's no way to change this.

**Comment by Niek** [comment]
The use case is: each hour an big amount of jobs will be queued. Instead of running these in sequential order (FIFO/LIFO), I'd prefer them to be processed randomly so they are consumed at a rand point during the hour. I guess the best way would be to make one queue per priority and then choosing a random priority value (range 0 - maxint) - but I was wondering if there would be a more elegant solution.

**Comment by stansv** [comment]
Or you can try to collect jobs data in memory array, shuffle it and do `queue.add()` in random order.

**Comment by Niek** [comment]
OK - let me close this issue, I'll work around it.
