### ISSUE TITLE
Jobs fail randomly without erroring

### ISSUE THREAD

**Issue by 1valdis** [OptimalBits/bull#1614]
Hello. I use bull 3.11.0. In one of my environments, I started seeing some really strange behaviour of my queues. I have some 20 queues and their jobs fail randomly without emitting "error" or "stalled" or "failed" events on the queue. That's how it looks in the logs. First "waiting" handler, second "cleaned" handler. This happens for nearly every other job.
```
2020-01-14T09:05:42.365Z - info: checkEvent: A Job event_1475 is waiting to be processed as soon as a worker is idling
2020-01-14T09:05:45.372Z - info: checkEvent: Cleaned 1 failed jobs with IDs: event_1475
```
I've set breakpoints to worker function start and it actually doesn't even get called when this happens.
I added a backoff to see if it can be retried on such error, when creating a job:
```
      backoff: {
        type: 'fixed',
        delay: 5000,
      },
      attempts: 3,
```
But this added retries only if there was actual error in a worker. In this case, it didn't change anything, since the worker simply isn't called. What's strange is that on 2 other environments everything works correctly. Any help?

**Comment by stansv** [comment]
Hello! How this "cleaned" handler is triggered? Can you please check `failedReason` field in job key (the value of job key is Redis hashtable, for example, `bull:my-queue:1234`)?

**Comment by 1valdis** [comment]
@stansv So in the end we swapped our AWS ElastiCache instance to another fresh one, that has completely the same configuration as previous. The problem went away. What exactly happened is still a mistery...

**Comment by stansv** [comment]
@1valdis I suppose this is the same as https://github.com/OptimalBits/bull/issues/1499
