### ISSUE TITLE
Error: Missing lock for job 1 finished, when do a graceful shutdown

### ISSUE THREAD

**Issue by oh-frontend1** [OptimalBits/bull#1615]
## Description
When queue is processing a long job, and I do a graceful shutdown  using `await q.close()`, and queue wait for job done as expected.

But, in Redis, job still on `active` list, and have `failedReason: Missing lock for job 1 finished`.

I have dug into the `bull` code and found that `queue.close()` will call `queue._clearTimers()`, so it cannot call `extendLock` anymore!

Is it intentional or just a bug?
## Minimal, Working Test code to reproduce the issue.
```js
const Bluebird = require('bluebird');
const Queue = require('bull');

const q = new Queue('test');

(async () => {
  q.process(async (job) => {
    console.log('Job start!');
    await Bluebird.delay(30 * 1000);
    console.log('Job done!');
  });

  await q.add({ some: 'job' });

  // Wait for job added
  await Bluebird.delay(100);

  console.log('Do an graceful shutdown');
  await q.close();
  console.log('Bye!');
})();
```

Output
```
Job start!
Do an graceful shutdown
Job done!
Bye!
```
## Bull version
3.12.1

**Comment by stansv** [comment]
Hi, looks like this is a rare corner case and can be reproduced only if job has delay of 30s and delay between `add()` and `close()` is about 100ms.

**Comment by oh-frontend1** [comment]
@stansv The problem also occur if I set delay to 10'000ms.

The problem is if some jobs longer than `lockDuration`, and we call `Queue.close()` before `lockDuration - lockRenewTime`, so queue will stop all timer upon close, and it cannot renew lock before lock Time-to-live end.

**Comment by oh-frontend1** [comment]
Maybe this `clearTimers` block should move below `pause`  block?
https://github.com/OptimalBits/bull/blob/081b37f620e5d94c96ca299674fdf581a8f8ed19/lib/queue.js#L547

**Comment by oh-frontend1** [comment]
So in my case, I just need to call `await queue.pause(true)` before `await queue.close()` so the timer won't stop before any job finished.

This code should fix my issue
```js
const Bluebird = require('bluebird');
const Queue = require('bull');

const q = new Queue('test');

(async () => {
  q.process(async (job) => {
    console.log('Job start!');
    await Bluebird.delay(30 * 1000);
    console.log('Job done!');
  });

  await q.add({ some: 'job' });

  // Wait for job added
  await Bluebird.delay(100);

  console.log('Do an graceful shutdown');
  await q.pause(true); // <----   added line
  await q.close();
  console.log('Bye!');
})();
```
