### ISSUE TITLE
Slow delay in first job after server start

### ISSUE THREAD

**Issue by shaunwarman** [OptimalBits/bull#1617]
## Description
I'm noticing that without any options out of the box that I'm seeing what looks to be a solid 10 second delay before my bull worker process acts on the job in the queue.

* Bull startup first job
    * **10 second delay** <-- not sure where this is coming from
    * queue active - 1579197240068
    * 6 bull based redis connections (3 client, 3 subscriber) - 3 queues
    * sending email - 1579197229548
    * queue completed - 1579197229548
* Jobs thereafter
    * add job - 1579197892741
    * queue waiting
    * queue active - 1579197892741
    * sending email - 1579197892741
    * queue completed - 1579197892741
    * queue drained

```
// Server started and running for many minutes

[bull] ⬤  debug     queue active { queue:

[bull]   job:
[bull]    { opts:
[bull]       { attempts: 1,
[bull]         delay: 0,
[bull]         timestamp: 1579198519664,
[bull]         backoff: undefined },
[bull]      name: '__default__',
[bull]      data: { template: 'verify', message: [Object], locals: [Object] },
[bull]      _progress: 0,
[bull]      delay: 0,
[bull]      timestamp: 1579198519664,
[bull]      stacktrace: [],
[bull]      returnvalue: null,
[bull]      attemptsMade: 0,
[bull]      id: '27',
[bull]      processedOn: 1579198527228,
[bull]      failedReason: undefined }

[bull] ⬤  debug     creating bull client { type: 'client',
[bull] ⬤  debug     creating bull client { type: 'subscriber',
[bull] ⬤  debug     creating bull client { type: 'client',
[bull] ⬤  debug     creating bull client { type: 'subscriber',
[bull] ⬤  debug     creating bull client { type: 'client',
[bull] ⬤  debug     creating bull client { type: 'subscriber',

[bull] ⬤  debug     redis connection established { description: '127.0.0.1:6379',
[bull] ⬤  debug     redis connection established { description: '127.0.0.1:6379',
[bull] ⬤  debug     redis connection established { description: '127.0.0.1:6379',
[bull] ⬤  debug     redis connection established { description: '127.0.0.1:6379',
[bull] ⬤  debug     redis connection established { description: '127.0.0.1:6379',
[bull] ⬤  debug     redis connection established { description: '127.0.0.1:6379',

[bull] ⬤  debug     queue drained { queue:

[bull] ⬤  debug     queue completed { queue:

[bull]   job:
[bull]    { opts:
[bull]       { attempts: 1,
[bull]         delay: 0,
[bull]         timestamp: 1579198519664,
[bull]         backoff: undefined },
[bull]      name: '__default__',
[bull]      data: { template: 'verify', message: [Object], locals: [Object] },
[bull]      _progress: 0,
[bull]      delay: 0,
[bull]      timestamp: 1579198519664,
[bull]      stacktrace: [],
[bull]      returnvalue: 0,
[bull]      attemptsMade: 0,
[bull]      id: '27',
[bull]      processedOn: 1579198527228,
[bull]      failedReason: undefined,
[bull]      finishedOn: 1579198541749 }
```

I'm having a tough time debugging this lingering startup issue. I also see from here that sometimes jobs just get stuck and never go into active state until the server is restarted.

## Bull version
^3.0.0

**Comment by manast** [comment]
The only circumstance that such a delay would exist is if the queue has 1 job that has started processing, you close the queue and start the queue without any other jobs waiting for process. Then the queue will wait for the job to get stalled and then restart it.
There are no known issues about jobs got stuck or similar, despite old issues about it, there is no code case that can demonstrate it really exists.

**Comment by shaunwarman** [comment]
Thanks @manast !

I'm still doing some digging to isolate some of the issues with our current setup. You can see that [setup here](https://github.com/ladjs/lad.sh#install). Feel free to use this as a reference app to debug what others may be seeing, but haven't been able to share. There are some docs on how to easily set that up as well. You can see on start, you can create a dummy account which adds a job on to the queue for email. There's a delay of about 10 seconds (which I'm still trying to figure out right now) and all the bull logging is in console.

**Comment by niftylettuce** [comment]
@manast 	would gladly tip you for your time over PayPal in helping us to resolve this issue

**Comment by niftylettuce** [comment]
Still a pretty huge issue for us, would appreciate any help.

**Comment by niftylettuce** [comment]
For what it's worth, these are all individual processors like:

`processor.js`:

```js
module.exports = async job => {
  console.log('job', job);
  await Promise.resolve();
}
```

**Comment by niftylettuce** [comment]
Also @manast 	here's some more context - you can see we `empty()` before `add()` when bull first boots up (using `@ladjs/bull`):

```js
const Bull = require('@ladjs/bull');
const Graceful = require('@ladjs/graceful');
const pSeries = require('p-series');

const config = require('./config');
const queues = require('./queues');
const logger = require('./helpers/logger');

const bull = new Bull({
  logger,
  queues,
  queue: {
    prefix: `bull_${config.env}`
  }
});

if (!module.parent) {
  const graceful = new Graceful({
    bulls: [bull],
    logger
  });

  (async () => {
    try {
      const vanityDomains = bull.queues.get('vanity-domains');
      await pSeries([() => vanityDomains.empty(), () => vanityDomains.add()]);

      const translateMarkdown = bull.queues.get('translate-markdown');
      await pSeries([
        () => translateMarkdown.empty(),
        () => translateMarkdown.add()
      ]);

      const translatePhrases = bull.queues.get('translate-phrases');
      await pSeries([
        () => translatePhrases.empty(),
        () => translatePhrases.add()
      ]);

      await Promise.all([bull.start(), graceful.listen()]);

      if (process.send) process.send('ready');
      logger.info('Lad job scheduler started');
    } catch (err) {
      logger.error(err);
      // eslint-disable-next-line unicorn/no-process-exit
      process.exit(1);
    }
  })();
}

module.exports = bull;
```

**Comment by manast** [comment]
I would gladly help but you really need to create a minimal use case that demonstrate the issue in bull without any third party dependencies...
