### ISSUE TITLE
Master process not killed

### ISSUE THREAD

**Issue by JSRossiter** [OptimalBits/bull#1623]
## Description
I've just noticed that I have a large build up of orphaned master processes `.../bin/node .../node_modules/bull/lib/process/master.js`

I use pm2 to run the below file which loads a few sandboxed process workers, I want to be able to kill all the workers in response to certain errors and allow pm2 to restart everything. 

My guess is that  `process.exit(1);` isn't triggering the child processes to be killed, would `process.kill(process.pid, "SIGINT");` result in the correct behaviour?

## Example code

```javascript
const path = require('path');
const Queue = require('bull');

const handleError = async error => {
  if (String(error).includes('BAD_ERROR')) {
    process.exit(1);
  }
};

const startTask = async (task, repeatOpts) => {
  const queue = new Queue(task, process.env.BULL_REDIS_URL);
  queue.process(path.join(__dirname, 'tasks', `${task}.js`));
  queue.add(undefined, { repeat: repeatOpts });
  queue.on('stalled', handleError);
  queue.on('error', handleError);
};

startTask('myTask', { every: 30000 });
```

## Bull version
3.12.1

**Comment by stansv** [comment]
You exit current process but children doesn't receive any signals, so remain running as orphans. Your handleError callback should be aware of any queues created by startTask, I can suggest to store all queue instances in some global array, but generally this is not a good design until you do not control how many times startTask is called.
In handleError, call close method on each queue (with doNotWaitJobs = true) and await for all close promises, only then do process.exit().

**Comment by JSRossiter** [comment]
Thanks! That seems to be working well now.

Incidentally, doNotWaitJobs is missing from the documentation (not that it would have helped me here) https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueclose

**Comment by fzn0x** [comment]
> You exit current process but children doesn't receive any signals, so keep running as orphans. Your handleError callback should be aware of any queues created by startTask, I can suggest to store all queue instances in some global array, but generally this is not a good design until you do not control how many times startTask is called. In handleError, call close method on each queue (with doNotWaitJobs = true) and await for all close promises, only then do process.exit().

It might seems unrelated but your comment solve my issue when calling done and the queue is calling the event `.on('completed')` but the queue does not stopping at all.

So I did this and the application can stop!

```js
queue.on('completed', async (job) => {
    await queue.close(true);
});
```
