### ISSUE TITLE
"Unlimited" Concurrency / Never-ending jobs

### ISSUE THREAD

**Issue by itsUnsmart** [OptimalBits/bull#1625]
Hello, 

I currently have a setup where I can run jobs just fine, however, I wanted to have a job that is basically never-ending. When I try to change it to never call the done callback it will never process any other requests. I know there is an option to have concurrency set, however, I want the concurrency to just be however many jobs exist, and if a new job gets added I want the concurrency to cover that as well. I could not find anything about doing this, I was curious if there was a way to do this?

Thanks.

**Comment by stansv** [comment]
What's an advantage to use bull for constantly-running jobs with unlimited concurrency? This can be implemented easily on node.js without any libraries at all.. Bull is a redis-based queue in the first place.

**Comment by dobesv** [comment]
If you want unlimited concurrency just set the concurrency to a very high number.

However, as @stansv said, you just want some long running jobs just spawn them off, no need to use bull at all.
