### ISSUE TITLE
How to get jobs by Queue Insertion time ?

### ISSUE THREAD

**Issue by AsifArko** [OptimalBits/bull#1626]
If there's any way to get jobs by the insert time range ?

**Comment by stansv** [comment]
Bull does not provide such functionality.

Redis structure is not optimized to query by timestamp, you can try to create your own index (using `ioredis` for example as Redis client).

Or, if you have generated job IDs (default behavior): i.e. 1, 2, 3 etc, and you know first job key is for example `bull:queue:1` and last job key is `bull:queue:1000` (meaning last job have id 1000), implying timestamp grows with this id, you can write fast binary search to find earliest job A with timestamp >= start time of your range and latest job B with timestamp <= end time of range, finally you just query all jobs between A and B.
