### ISSUE TITLE
ERR max number of clients reached

### ISSUE THREAD

**Issue by tugan** [OptimalBits/bull#163]
Hi, 

do you have any suggestion avoiding the following error?   when our transaction count increase we are getting the error 

thanks in advance 

/var/app/current/node_modules/bull/node_modules/redis/index.js:575
                throw callback_err;
                      ^
Error: Ready check failed: ERR max number of clients reached
    at RedisClient.on_info_cmd (/var/app/current/node_modules/bull/node_modules/redis/index.js:380:35)
    at Command.<anonymous> (/var/app/current/node_modules/bull/node_modules/redis/index.js:430:14)
    at bound (domain.js:254:14)
    at Command.runBound (domain.js:267:12)
    at RedisClient.return_error (/var/app/current/node_modules/bull/node_modules/redis/index.js:571:25)
    at ReplyParser.<anonymous> (/var/app/current/node_modules/bull/node_modules/redis/index.js:317:18)
    at ReplyParser.emit (events.js:107:17)
    at ReplyParser.send_error (/var/app/current/node_modules/bull/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/var/app/current/node_modules/bull/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/var/app/current/node_modules/bull/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/var/app/current/node_modules/bull/node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by albertjan** [comment]
We've had this issue when bull instances weren't getting cleaned up. You can ask redis for a [CLIENT LIST](http://redis.io/commands/client-list). So you can see what all these clients are doing.

**Comment by manast** [comment]
seems unrelated to bull. Will close.

**Comment by PaulGrimshaw** [comment]
We are also getting this error after a few days.  As far as i can tell there is nothing unusual about our setup:

```
export const startQueueWorker = async (config: ServerConfig) => {
    for (const jobDefinition of config.activeJobs) {
        const options = {
            limiter: jobDefinition.limiter
        }

        const queue = new Queue(`${config.jobQueuePrefix}${jobDefinition.name}`, config.redisConnectionString, options)

        queue.process(config.numberOfProcessors, path.join(__dirname, "jobs", jobDefinition.type, `${jobDefinition.type}.js`))

        const logger = initialiseLogger({
            componentType: "job",
            component: jobDefinition.name,
            client: process.env.CLIENT
        }, config.loggers)

        logger("info", `Started watching queue`)

        queue
            .on("error", (err) => {
                logger("error", err)
            })
            .on('failed', (job, err) => {
                logger("error", err)
            })
            .on('progress', (job, progress) => {
                logger(progress.level || "info", R.dissoc("level", progress))
            })
            .on("completed", () => {
                logger("info", `${jobDefinition.name} completed`)
            })

    }
}
```

**Comment by manast** [comment]
the question here is, what the max amount of connections that accept your redis provider, and how many queue workers are you actually spawning, consider 3 connections per worker.

**Comment by PaulGrimshaw** [comment]
I only have 3 queues, so would assume its 9 connections.  Redis is default docker image, which has a max connection limit of 10,000 connections.  It's hard to troubleshoot and find out what is going wrong, as all i pass to Bull is the connection string and Bull handles all the connection connects / disconnects etc.

**Comment by manast** [comment]
Can you create a minimum reproducible example code that reproduces the issue?

**Comment by wayne530** [comment]
@manast I somewhat disagree that this isn't a bull issue. (1) You create an unbounded number of connections that is a function of the number of queues; (2) You provide no way for end users to use their own Redis clients (that might provide connection pooling, for example). Would it be possible to revisit this? Writing a simple connection pool for ioredis should not be too difficult and it would allow end users to specify a connection limit that is known to be below the server limit and thus in theory, we should never have this issue.

**Comment by leodisarli** [comment]
Hey guys, i was having the same problem here, and fix with two simple things:
1) Every time you create a queue object to push to queue, close the queue object after pushing with queue.close(); command.
2) Reutilizing connections on my consumers like described in the [doc](https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#reusing-redis-connections) 

something like that:

```
var {REDIS_URL} = process.env

var Redis = require('ioredis')
var client = new Redis(REDIS_URL);
var subscriber = new Redis(REDIS_URL);

var opts = {
  createClient: function (type) {
    switch (type) {
      case 'client':
        return client;
      case 'subscriber':
        return subscriber;
      case 'bclient':
        return new Redis(REDIS_URL);
      default:
        throw new Error('Unexpected connection type: ', type);
    }
  }
}
```

var queueFoo = new Queue('foobar', opts);
var queueQux = new Queue('quxbaz', opts);

After that, no more max clients errors! I hope this help you!

Cheers!

P.S: this is not applicable in BullMQ v4+, only in stantard Bull (thanks to @codegsaini )

**Comment by bilalesi** [comment]
hi guys, i have the same issue, 
i use bull and it's worked perfectly in my machine but when i deploy to heroku, i have this error 
`ReplyError: ERR max number of clients reached
2021-01-04T00:46:36.973075+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:193:12)
2021-01-04T00:46:36.973146+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:303:14)`

i have three (03) queues connecting to the same REDIS ( from heroku addons)
and one of the queues has two jobs with diffrent concurrency 
i try to remove the concurrency but nothing worked
so what's the solution, please the project is in final -delivery mode

**Comment by manast** [comment]
@bilalesi first of all, you need to understand that depending on which Heroku instance there are more or less connections available. Secondly, you should figure out how many connections you need for the amount of queues, workers, etc that you are using. Finally, you may also be able to reuse some of the connections https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#reusing-redis-connections

**Comment by bilalesi** [comment]
Thank you @manast for quick reply, how I can calculate the total number of connections,

And for reuse of connection is it the same as connection.duplicate() in bullmq??

**Comment by greyhands2** [comment]
@bilalesi per worker it is 3 connections

**Comment by rubengmurray** [comment]
After having the same issue, and implementing the suggested pattern, I now get this error on startup:

```
(node:94975) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Redis]. Use emitter.setMaxListeners() to increase limit
```

**Comment by rubengmurray** [comment]
> @rubengmurray that is a rather silly NodeJS warning that can safely be ignored. Every time you have more than 11 listeners it will write that warning. You can also increase the number of listeners with emitter.setMaxListeners() to get rid of it.

All looking good since I implemented https://github.com/OptimalBits/bull/issues/163#issuecomment-632303117. Nice one.

**Comment by codegsaini** [comment]
Little late, but if anyone is still facing the issue of max client reached (I had this issue with both postgres (with prisma ORM) and node-redis), just remember not to perform db queries inside the short-lived worker created by BullMQ, because each worker will create its own client, which will exhaust db. So just do heavy task inside worker thread and get the result once the job is finished and perform db operation in the main thread.
Also, I used Piscina library to manage workers pool with BullMQ.

The suggestions by @leodisarli (nice explanation) are no longer applicable in BullMQ v4+

Example code:
```
//piscinaPool.js
import path from "path";
import { fileURLToPath } from "url";
import Piscina from "piscina";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROCESS_WORKER_PATH = path.resolve(__dirname, "./processData.js"); // do all heavy task inside processData.js but no db operation

const piscinaPool = new Piscina({
  filename: PROCESS_WORKER_PATH,
  maxThreads: 4,
});

export default piscinaPool;
```

```
//worker.js
const executeJob = async (job) => {
  const abortController = new AbortController();
  const timeout = setTimeout(() => {
    abortController.abort();
  }, 10 * 60 * 1000);

  const data = job?.data;
  try {
    const result = await piscinaPool.run(data, {
      signal: abortController.signal,
    });
    await onJobCompleted(data, result);
    return result;
  } catch (err) {
    await customErrorFunc(err, job);
    throw err;
  } finally {
    clearTimeout(timeout);
  }
};

const worker= new BullWorker("name", executeJob, {
  connection: redisClient,
  concurrency: 2,
});

worker.on("failed", (job, err) => {
  logger.error(`[Job ${job.id}] failed: ${err.message}`);
});

async function gracefulShutdown() {
  await worker.close();
  await prisma.$disconnect();
  await redisClient.quit();
}

process.on("SIGINT", gracefulShutdown);
process.on("SIGTERM", gracefulShutdown);

export default worker;
```

```
//processData.js
export default async (workerData) => {
  const { var1, var2 } = workerData;
  // Do heavy task in background thread
  return true;
};
```
