### ISSUE TITLE
Handling lost connection to Redis and automatic reconnection

### ISSUE THREAD

**Issue by adame21** [OptimalBits/bull#1632]
Hi,
I've been looking over the references and a bit into the actual code for the lib, and I couldn't find where reconnecting is configured.

Will the client try to reconnect on lost connection by default?

If documentation about this exists could you point me in the right direction?

If no to both, can you tell a simple way to configure re-connection upon lost connection?

Thanks :)

**Comment by mritzco** [comment]
It reconnects by itself, no need to worry.

For some kind of Queues re-connection might be an issue (repeating ones), you can add these arguments to the Redis connection string / params:
?enableReadyCheck=false&maxRetriesPerRequest=null

Source https://github.com/OptimalBits/bull/issues/890
