### ISSUE TITLE
Question: How does getJobs() work?

### ISSUE THREAD

**Issue by matthiasfeist** [OptimalBits/bull#1637]
Hi.

I have a question about https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queuegetjobs GetJobs().

The documentation is a bit unclear on this method. 
1) Can I get a number of jobs from a certain queue with this method? Like the next 10 that are scheduled for execution? 
2) If I get the jobs with this method, are they automatically set as "active" or can I set them to "active" to signal that I am processing those jobs now?

Background to my question: I have jobs on a Queue but an API which allows me to do batch requests. So my idea was to grab 10 jobs from the queue with getJobs() and then process them with a single API requests and then update the 10 queue jobs programatically

**Comment by pampanelson** [comment]
I can't get jobs by this method even.
for example:
queue.add('jobname',jobData,{jobId:'jobId'});

queue.getJobs(['jobname']) should back an array has job instance,
but I got a []

**Comment by manast** [comment]
@pampanelson you cannot get jobs by 'jobname', only by status, the documentation should rename "types" to "status" to make it more clear, sorry for the confusion.
@matthiasfeist your approach could work. How did it go?

**Comment by sherifelkelesh** [comment]
@manast I'm trying to use getJobs() using this 
`await this.queue.add('bull-auto-clean', { queue: this.queue }); // run once a day at 22:00
      const jobs = await this.queue.getJobs(['acitve']);`
and I always get an empty array? any thoughts?
