### ISSUE TITLE
Why do we use redis LISTs for wait and active queues?

### ISSUE THREAD

**Issue by kulbirsaini** [OptimalBits/bull#164]
Is there a specific reason for this decision? Will it not be better to use `ZSET` instead? That'll definitely make lookups easier without interfering with any core functionality.

**Comment by albertjan** [comment]
BRLPOPLPUSH basically

**Comment by kulbirsaini** [comment]
Thanks @albertjan. BTW is there a place gittter/irc where you guys hangout?

**Comment by albertjan** [comment]
@kulbirsaini no :smile: @manast good idea to add a chat somewhere?
