### ISSUE TITLE
Create a scheduled job

### ISSUE THREAD

**Issue by bargald** [OptimalBits/bull#1642]
## Create a scheduled job

I didn't find a straight forward way in the docs to create a scheduled job to run in a specific date.
For instance, in Agenda.js you can schedule `job.schedule(Date);`

Am I missing something?

this feature is usefull for billing customers.

thanks.

## Bull version
latest

**Comment by gabegorelick** [comment]
See https://github.com/OptimalBits/bull/issues/1648
