### ISSUE TITLE
Duplicate processing of jobs when there are two node background processes listening to same queue

### ISSUE THREAD

**Issue by rahulwinzo** [OptimalBits/bull#1643]
Hi,

I'm new to bull.js. I've written a simple processor to process the job in my queue. I ran two separate processes in different docker containers. I noticed that as soon as I add the job in the queue, both the containers pick that job for processing. I'm not sure if this is the issue or there's some implementation failure on my side.

I've attached the files showing logs of the two containers.

![bulljs-image](https://user-images.githubusercontent.com/37581350/74150733-8dd66280-4c30-11ea-8841-bf5d4a71b1de.png)

Bull version - 3.12.1

**Comment by balexandre** [comment]
you will need to specify that you want only to take 1 job and to mark that job as taken ...

I never tried to containerize the solution, I just create a worked that I can create more instances and the simpler code is:

```javascript
// concurrency: Bull will then call your handler in parallel respecting this maximum value.
queue.process(concurrency: number, callback: <function || string>)
```

sith that info, try to process one job at a time, like:

```javascript
queue.process(1, async () => { ... })
```

that will tell that you only want to take 1 job at a time and by taking it, it will mark as "processing" and the 2nd worker will not get it.

**Comment by vasu-winzo** [comment]
Hi @balexandre, 

We have used the following approach to register a processor. From the documentation :  
`
// Single process:
queue.process('/path/to/my/processor.js');
`
This is same as: 
`queue.process(1, '/path/to/my/processor.js');`

I think that this is a race condition issue. Workers from both containers start processing the issue at the same instant(as can be seen from the timestamp in the logs).

**Comment by manast** [comment]
@vasu-winzo there is no such race condition. Workers will work in parallel processing jobs as fast as they can never processing the same job in different workers at the same time, those are the guarantees bull offers. The screenshot you pasted above is not enough to understand what is going on, but If I have to guess, you are just pasting the result of the "complete" global event in two different processes, which as expected will show the same data on both.
