### ISSUE TITLE
how to run a  job at specific dateTime?

### ISSUE THREAD

**Issue by Divine1** [OptimalBits/bull#1648]
i can see repeat based scheduling via bull.
```
  paymentsQueue.add(paymentsData, {repeat: {cron: '15 3 * * *'}});
```

- How to add a job to the queue that can run at a specific datetime/future datetime for example `2020-02-20 11:15 pm`?

i'm looking for options like this. is it available in bull?
```
  paymentsQueue.add(paymentsData, {immediate: {cron: '15 3 * * *'}});
  paymentsQueue.add(paymentsData, {runonce: {cron: '15 3 * * *'}});
```

**Comment by gabegorelick** [comment]
See the `delay` option in https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd. It takes the number of milliseconds to wait before processing a job. If you have a specific date that you want a job to be processed, you just have to do some math to calculate the number of milliseconds that is from now.

**Comment by priya0607jain** [comment]
I am trying to process a job at specific date and time. But it does not seems to work even after setting up the delay option. The job run immediately. Can you help out with the solution?

**Comment by Divine1** [comment]
@priya0607jain  if you are using mongodb in backend, i would recommend checking out [agenda npm module](https://www.npmjs.com/package/agenda), its easy to use imo.

**Comment by priya0607jain** [comment]
@Divine1 Does it support start and end date-time?

**Comment by nsssayom** [comment]
> See the `delay` option in https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd. It takes the number of milliseconds to wait before processing a job. If you have a specific date that you want a job to be processed, you just have to do some math to calculate the number of milliseconds that is from now.

This can't be a very good developer experience for a library that is this developed.

**Comment by manast** [comment]
@nsssayom I guess that depends on your level of laziness, if doing a subtraction is a lot of work for you then yes.

**Comment by nsssayom** [comment]
@manast The whole point of using a library is that productive 'laziness', I guess!

**Comment by acodercat** [comment]
This feature is very important.

**Comment by manast** [comment]
@acodercat just add a job with a ```delay = desiredTime - Date.now()```

**Comment by coopbri** [comment]
> @manast The whole point of using a library is that productive 'laziness', I guess!

I do agree with @nsssayom here. With that being said, it's relatively straightforward to implement an abstraction function that does the calculation described here for you (just pass a desired time in). Agenda is a nice alternative with cleaner DX for scheduled date/time jobs, however as of writing this comment, the most recent commit was a few months ago and many issues and PRs go stale without response. My advocation is to stick with BullMQ and abstract the differential calculation.

**Comment by nivapo95** [comment]
I agree that an option for a time-stamp schedule is required, although there are alternatives like agenda, bull runs on redis and not mongodb so it would be better to implement this feature in bull than using agenda in my case.

Will be waiting for a future update on this

**Comment by manast** [comment]
@nivapo95 you just add a delayed job with ```desiredTimestamp - Date.now()``` that will be way faster than waiting for a feature that we will not implement any time soon.

**Comment by nivapo95** [comment]
> @nivapo95 you just add a delayed job with `desiredTimestamp - Date.now()` that will be way faster than waiting for a feature that we will not implement any time soon.

That is what I did.
My main use is to schedule future tasks to run, and less the "queue" part.
Do you know if there is a limit to the time in future that I can set the jobs for?
Does anyone encountered any issues when using bull primarily for future tasks (up to 6 months in the future)?

**Comment by manast** [comment]
The limit like several thousands years in the future, I do not remember but for all practical purposes there is no limit.

**Comment by elhananjair** [comment]
I wanted to process I added to the queue every day at some specific time, and I don't think `desiredTimestamp - Date.now()` does the job. Is it possible to use some `cron` libraries with bullmq?

**Comment by manast** [comment]
@elhananjair why is not making the job?

**Comment by elhananjair** [comment]
> @elhananjair why is not making the job?

Because, I don't think delaying works like scheduling libraries, running that function always at a specific time.

**Comment by manast** [comment]
If you delay it the amount of ms from now to the desired time it will be processed at the desired time, what is not working about this approach?

**Comment by elhananjair** [comment]
ow okay, that works actually in my case I want to run the function every day repeatedly

**Comment by manast** [comment]
You know you can use repeatable jobs right? https://docs.bullmq.io/guide/jobs/repeatable

**Comment by elhananjair** [comment]
> You know you can use repeatable jobs right? https://docs.bullmq.io/guide/jobs/repeatable

oh, thanks a lot, I had no idea about that feature, but would only add `repeat` option work to start the job at a specified time? or do I need to add a delay for the first run?

I have something like this:
```
const queue = new Queue('sendEmail', {
    connection: {
        host: 'localhost',
        port: 6379
    }
});
queue.add('sendEmail', {func: 'allSubscribes'}, {
    repeat: { pattern: '0 32 2 * * *',}})
const worker = new Worker('sendEmail',  job => {
    console.log(job.data)
}, {
    connection: {
        host: 'localhost',
        port: 6379
    }
})
```

**Comment by manast** [comment]
You can use two queues for this, one where you put delayed jobs, and when the delayed job is executed it creates a new repeatable job in a different queue.

**Comment by elhananjair** [comment]
Do you mean something like this? I am not new to queue'ing staff

```
const q1 = new Queue('myqueue', {
    connection: {
        host: 'localhost',
        port: 6379
    }
});

const q2 = new Queue('myqueue', {
    connection: {
        host: 'localhost',
        port: 6379
    }
});


await q1.add('sendEmail', { foo: 'bar' }, { delay: 5000 });
await q2.add('sendEmail', { qux: 'baz' },  {repeat: { pattern: '0 32 2 * * *',}});
 
 
const worker = new Worker('myqueue', async job => {
    console.log(job.data);
}, {
    connection: {
        host: 'localhost',
        port: 6379
    }
});



```
I thought that I could add a job to the queue specifying `delay` and `repeat` options at once, I was thinking of just adding a job as simple as this:

```
   await q1.add('sendEmail', { foo: 'bar' }, {
       delay: 5000,
       repeat: {  pattern: '0 32 2 * * *' }
});
```

**Comment by manast** [comment]
@elhananjair No. Use 2 different queues. In your example you are using 1 queue. If you are new to Bull, please start with the guide https://docs.bullmq.io/ and some tutorials: https://blog.taskforce.sh/

**Comment by elhananjair** [comment]
@manast  ok thank you so much I will check the documentation and the blog you have shared.
