### ISSUE TITLE
Resuming job from last failed instance

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [OptimalBits/bull#1649]
Hello,

I am building a module in node which uploads multiple images to server in background. The problem is if there's any validation fail or any issue in any image, the job fails. So I need to know if there's any way that we can restart the job from the last failed instance. For example, if 50 images are uploaded, and first 20 are uploaded successfully and the 21st fails with any kind of error either from code or from redis, how could I restart the job from 21st only, as currently the job restarts again from the first one, and the images are duplicated.

Thank you.

**Comment by manast** [comment]
I will close this issue as the question is not related to Bull itself but how to write a job that fulfil some external requirements.
