### ISSUE TITLE
"Waiting Jobs" are being processed at start, while "Active Jobs" are exisiting

### ISSUE THREAD

**Issue by Imbuedhush** [OptimalBits/bull#1651]
Hello
I have implemented this logic.
When server is starting all Queues are initialized:
1. Server creates new Queue() for which value in my array, everything is ok
2. Sets processors for every queue instance with and adds handlers for events completed, error, failed; So if there any any incompleted jobs - bull can process them(job requires special functions, that are becoming available after setting of processor)

After server restart, if there any jobs that are incompleted - queue begin to process them.
after 1st start - concurrency is 150 in bull-board
after restart - concurrency is 300
after some time - concurrency is 150
by concurrency i meant active in  bull-board

just checked - after each restart getJobCounts() return previous active count +150
i think bull waits for all active to be done, and then everything is going good with 150 concurrency

**Comment by Imbuedhush** [comment]
after some code analysis i can say:
1. concurrency isn't duplicated
2. new active jobs just added to the pool with previous active jobs(created before shutdown)
3. kinda **error** is in code of Queue.prototype.getNextJob in queue.js:
`this.bclient.brpoplpush(this.keys.wait, this.keys.active, this.settings.drainDelay)...`
actually it's not an error.

Anyway, i'd like to request an improvement of logic:
if there is active jobs in redis and queue initializing use `this.bclient.brpoplpush(this.keys.active)`
if no active jobs in redis and queue initializing use `this.bclient.brpoplpush(this.keys.wait, this.settings.drainDelay)`

**Comment by manast** [comment]
This is how bull handles "stalled" jobs since you restarted the workers before they completed the job. I suggest you dig a bit more in the documentation and older issues since this is documented and quite long to explain again in this issue.
