### ISSUE TITLE
Unable to see sandboxed worker log messages

### ISSUE THREAD

**Issue by sureshdsk** [OptimalBits/bull#1655]
I am running concurrent sandbox mode worker. like below

worker.js
`
queue.process(3, path.resolve(process.cwd(), 'worker', 'processJob'));
`

Any console.log messages written inside processJob is not visible in my pm2 console. 
Is there any way to get log messages from sandbox workers?

**Comment by suchakraborty** [comment]
There is a log method within the job.
**Documentation:**
* https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#joblog
* How to access it from the queue https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queuegetjoblogs 
* Behaviour: https://github.com/OptimalBits/bull/blob/1898b5a5b2a8e70d3bc5aaa85097cdf521b52bc9/test/test_job.js#L511-L528 shows that the job logs are available as long as the jobs are not removed.

If you are using a UI on top, it too probably has provision for showing these logs. e.g. bull worker: https://github.com/hans-lizihan/bull-master/blob/c7953706edb6b1a56c482f4455bc3f959936ed41/client/pages/Job.jsx#L297-L311

**Comment by MikeSpock** [comment]
I would like to reinstate this issue. If the handler function that digests a job calls other functions in the codebase (functions that are also used outside the job itself), and have console.log-s, they are invisible for the job logs. And cannot be seen in the process's console either.
This is a problem, and it would be good if the job runner would overload locally the console.logs and use the job logger instead, automatically. 

The only temporary solution is to pass a log argument (that defaults to console.log) to all functions that the job handler calls, but then it must be implemented to all functions that they call. So it is a dirty and ugly hotfix for this issue. 

It would be important to find a good solution for this issue.

**Comment by dchapkine** [comment]
I think it is a major issue as well, we need to be able to see and store other logger messages along with logs produced by job.log... we can not possibly patch every single library or custom code out there to use job.log instead...

If there is any option to configure this ?
I did not find anything about it in the docs
