### ISSUE TITLE
Is it possible to export the details of all the jobs that has been processed in the queue in an excel file?

### ISSUE THREAD

**Issue by tanimasarkhel** [OptimalBits/bull#1656]

**Comment by gabegorelick** [comment]
Listen for queue events and construct a CSV file?

See https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#global-events

**Comment by manast** [comment]
or just get all the completed jobs and create the CSV from the data.

**Comment by manast** [comment]
Closing since there are means to perform the requested operation using current apis.
