### ISSUE TITLE
When concurrency=1, second job does not wait for first job to finish

### ISSUE THREAD

**Issue by rivernews** [OptimalBits/bull#1661]
## Description

I have two queues, one is called cronjob queue, the other is scraper job queue. At the time my server starts, I created a job in Cronjob, it will dispatch 2 scraper jobs into scraper job queue. What I want is to have scraper job queue execute one job at a time.

I set concurrency to 1 when setting up scraper job queue's `process` function. Nevertheless, after scraper job 1 and scraper job 2 added by cronjob's process, I see job 1 and job 2 become active almost the same time, then complete together as well.

I'm using the sandboxed process approach by the way.

### Initialize queues

```typescript
// cronjob/queue.ts
export const cronjobQueue = new Bull<any>(
    'cronjobQueue',
    {
        redis: redisConnectionConfig
    }
);

const concurrency = 1;
cronjobQueue.process(concurrency, processFileName);

// entry point
cronjobQueue.add({});
```

```typescript
// scraperJob/queue.ts
export const scraperJobQueue = new Bull<number>(
    'scraperJobQueue',
    {
        redis: redisConnectionConfig
    }
);

const concurrency = 1;
scraperJobQueue.process(concurrency, processFileName);
```

### Process functions

```typescript
// cronjob/process.ts

module.exports = function (job) {
    return Promise.all([
        scraperJobQueue.getWaitingCount(),
        scraperJobQueue.getDelayedCount(),
        scraperJobQueue.getPausedCount(),
        scraperJobQueue.getActiveCount(),
    ]).then(([waiting, delayed, pause, active]) => {
        if (waiting || delayed || paused || active) {
            return Promise.reject('cronjob skip');
        }
        return Promise.resolve();
    }).then(async() => {
        const orgList = [1, 2];
        for (const org of orgList) {
            const job = await scraperJobQueue.add(org);
            console.log(`added scraper job ${job.id}`);
        }
        return Promise.resolve('OK');
    }).catch(error => Promise.reject(error));
}
```

```typescript
// scraperJob/process.ts
module.exports = function (job) {
return new Promise((resolve, reject) => {
        try {
            setTimeout(() => {
                resolve('times up!');
            }, 5000);
        } catch (error) {
            reject(error);
        }
        
    })
} 
```

## Bull version

I'm using Bull = `^3.13.0`.

## Additional information

The log is like below:

```
org job 1 waiting
cronjob added scraper job 1
org job 1 active
org job 2 waiting
cronjob added scraper job 2
cronjob finish dispatching jobs [ '1', '2' ]
total of jobs 2
org job 2 active <--- become active even if job 1 hasn't finished yet
```

I simplified other code part that is unlikely to be relevant, but the entire code base [could be found in this link](https://github.com/rivernews/slack-middleware-server/tree/67c4b8aa8e4530e6dc9d3fb2bf53aefe669487dc/src/services/jobQueue/gdOrgReviewRenewal), where the two queues and their process functions are defined. 

If you find that actual code in project contains too many unrelevant stuff, I also created a standalone test directory [at here](https://github.com/rivernews/slack-middleware-server/tree/67c4b8aa8e4530e6dc9d3fb2bf53aefe669487dc/src/services/jobQueue/test), where you will change `redisConnectionConfig` to your redis server first, then run `ts-node index.ts` and observe the log to reproduce the issue. You'll see the log `job 2 active` is produced before the log `job 1 completed, result: times up!`, which shows that job 2 does not wait for job 1 to finish.

I tried specifying a job type name at `.process()`, but that doesn't change the result. I'm wondering if there's something that I'm missing, because I don't see much issues on google related to my issue here. Every help is appreciated! Thanks.

**Comment by manast** [comment]
There are no known issues with concurrency. Most probably you have more than one worker running at the same time, remember that concurrency is per worker, not global.
Regarding your test code, it would be better if you can reduce it even more to the minimum that reproduces the issue, I see a lot of async calls in the worker, etc, that should not be relevant for the issue.

**Comment by rivernews** [comment]
Well, I was using `nodemon --exec ts-node index.ts` to run my express server on my laptop terminal, 
about the number of worker, maybe `nodemon` is spawning 2 workers for auto reload. But I'll have to research about this for `nodemon`.
For test code - my apologies! I currently went for extra logics to restrict job queues to single concurrency using `.getWaitingCount` and other count functions so now that's working. I'll close this issue. If I get more insights between nodemon &  bull and still encounter unexpected behavior I'll re-open this issue and give a minimal test case.

**Comment by rivernews** [comment]
Just want to add what I end up doing in case someone runs into similar issue where concurrency isn't as expected.  

e.g. you set concurrency as 1 for a queue, but you still see 2 active job of that queue running at the same time, after you add two jobs in a row.

You have to be careful if you are using the sandbox process way to run your process function.

First of all, when people say "worker", it means an entirely new process like `node index.js` - Bull isn't able to create such new process.

What Bull can do is spawning child processes. This is Bull's concurrency. When you use `someQueue.process(processorName 2, fileName)`, it will create up to 2 child processes (sandbox process), each running one job.

The problem comes when you want to add jobs in another job. Say you have a supervisor job which will add a job. So you define two queues, `supervisorQueue` and `jobQueue`, and create those queues in master process (e.g. for `node index.js`, that is inside `index.js`; or your express server ). You define both to have concurrency of 1 by `supervisorQueue.process('supervisor', 1, './supervisorProcess.js')` and `jobQueue.process('job', 1, './jobrProcess.js')`.

Your supervisor process function running in sandbox process will add a job - to do this, you need `jobQueue`. But note that processes cannot share variables or resources. So you'll have to re-create `jobQueue` in your supervisor sandbox process. Some gotchas here: when you re-create `jobQueue`, if you also run `jobQueue.process('job', 1, './jobrProcess.js')` anywhere in supervisor's sandbox process, **that concurrency will stack up so `jobrProcess` end up with concurrency of 2**.

This mistake is especially easy to make when you are re-creating queues because you want to do something to a queue (either add job, or get job counts, etc) in another job.

To solve this issue, you need to ensure that `Queue.process(...)` is run only once across all processes. Usually this mean to only register processor function in your master process (the process you run `node index.js`). After ensuring this, the concurrency should now be correct and only 1 active job is run at a time.

**Comment by ChechoCZ** [comment]
Even running Queue.process in the index.js and setting concurrency to 1, I get the same result... It starts the second process before finishing the first one. :(

**Comment by manast** [comment]
@ChechoCZ most likely you are not returning a correct promise in your processor function.

**Comment by rivernews** [comment]
@ChechoCZ  You may want to double check and be careful when initiating the queue object (need to consider both - when running as master process, and when running as child process).

In a nut shell, every time the same `Queue.process(1, ...)` is executed in any process, as long as the processes are sharing the same redis db, the concurrency gets pile up. Are you using sandbox process, and the file where your put process function contains reference to `Queue`? If so, it's likely that the child process imports `Queue` again, which in turn initializes `Queue` and run `Queue.process(1, ...)`, which will increment `Queue`'s concurrency again. 

It could be confusing, but the flow is like this (assuming you have other things config correctly as @manast described):
1. You bootstrap your app by `node index.js`, which is the master process. Here you mentioned you initialize `Queue ` and runs `Queue.process(1, ...)`. So far, `Queue` has concurrency of 1 (this concurrency config is stored on redis).
1. You add a job. I assume that you're using sandbox process way. Then the master process will spawn a child process to run your process function.
1. Child process is created to run your job. **Note that child process does not share any javascript variables with master process, this means the `Queue` you initialized in master process does not count at all**. The child process will initialize all javascript variables from scratch. This is crucial.
1. Since you mentioned you put `Queue.process` in `index.js`, I assume you always run `Queue.process` right after `new Bull(...)`. Now in your child process, `Queue` is not initialized yet, so it will run both `new Bull(...)` and `Queue.process`. Here, `Queue`'s concurrency got incremented, this config update is written to redis, and now it has concurrency of 2.

I made some assumptions here so it might not be the case for you, but hopefully it could solve your issue. Also this is my understanding of how Bull works across processes but it could be wrong. If anyone found the behavior mentioned here is incorrect please kindly point out, I'd love to know!
