### ISSUE TITLE
Question: How can I figure out the number of processor watching a queue?

### ISSUE THREAD

**Issue by sexygeoff** [OptimalBits/bull#1665]
Hi, how can I figure out the number of processor watching a queue?

**Comment by gabegorelick** [comment]
If you look at the implementation of `Queue.prototype.process`, you can see it calls [`setHandler`](https://github.com/OptimalBits/bull/blob/0b7a73a6de028a27c1888bd7c8b7aa6b5ab19312/lib/queue.js#L625). This tracks processors in a `handlers` object. So `Object.values(queue.handlers).length` should give you the number of processors for `queue`.
