### ISSUE TITLE
defaultJobOptions not working with attempts

### ISSUE THREAD

**Issue by germansokolov13** [OptimalBits/bull#1666]
## Description
`attempts` option should make job retry after failure. It works fine when specifying it per job. However it doesn't work when specified per queue via `defaultJobOptions`.

The reference says that I can pass it with my Queue constructor and it has the same type as JobOpts. So it should work:
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queue

Not a big deal because I can still specify it per job but wastes some time for debugging.
## Minimal, Working Test code to reproduce the issue.
```JS
const Queue = require('bull');

const myQueue = new Queue('some_queue', null, {
  defaultJobOptions: {
    attempts: 3,
    backoff: 1000,
  },
});

myQueue.process(async job => {
  console.log('I exec');
  throw new Error('All is bad');
});

myQueue.add({ foo: 'bar' });
```
It should emit `I exec` to termital three times, not once. It does emit it three time if I move jobOpts to the `add` method
## Bull version
3.13.0

**Comment by Brigadier1-9** [comment]
Make it your second param, not third. I’m doing this and it works.

**Comment by germansokolov13** [comment]
@Brigadier1-9 That's strange. Especially given that RateLimiter options seem to work fine in third param. The docs say that limiter and defaultJobOptions go to the same param, third. The second is an url(to Redis instance). Anyway, this contradicts docs and typings.

**Comment by Brigadier1-9** [comment]
Specifically, this is what I am doing:
```
const DEFAULT_JOB_OPTIONS={
    attempts: 3,
    backoff: {
        type: 'fixed',
        delay: 100
    }
  };

let q=new Queue('TestQueue',  {redis: 'redis://localhost'  ,defaultJobOptions: DEFAULT_JOB_OPTIONS} );

let r=await q.add({msg: 'hello world'});

```
then r.opts.attempts is '3' and (sure enough) three attempts are made.

However, you're absolutely correct of course. The docs, and even the constructor in queue.js, say that if the second param is a string then the third is the opts.  The constructor starts off with sorting it out straight away by injecting the redis string into the opts:

```
  if (_.isString(url)) {
    opts = _.extend(
      {},
      {
        redis: redisOptsFromUrl(url)
      },
      opts
    );
  } else {
    opts = url;
  }
```
.. and when I sit down and try it it works for me with a redis string as the second param and the rest of the opts in the third:

```
    let q=new Queue('TestQueue',  'redis://localhost'  , { defaultJobOptions: DEFAULT_JOB_OPTIONS } );

```
- so you may have something else going on here.

**Comment by rohitkhatri** [comment]
I'm also facing the same issue, It's not overriding default attempts while adding job to the queue, any solution?

**Comment by Gabriel-Mbugua** [comment]
I'm experiencing the same issue. I'm trying to make reties 0 but I'm running into the same issue.

`const queue = new Queue('queue', process.env.REDIS_URL,{
  limiter: {
    max: 20_000,
    duration: 300_000 
  },
  defaultJobOptions: {
    attempts: 0, // no retires allowed
    timeout: 300000 // job considered stalled after 300 seconds
  },
})`

**Comment by vapaternina** [comment]
Same here

```js
sendInvoiceNotification: new Queue(
      config.queues.sendInvoiceNotification,
      config.redis.url,
      {
        // The retry configuration had to be added
        // here because the queue is called nowhere
        // in the backend, but from an AWS Lambda
        defaultJobOptions: {
          removeOnComplete: true,
          attempts: 3,
          backoff: 3600000
        }
      }
    ),
```
