### ISSUE TITLE
How to clean a queue including delayed jobs that are waiting to be retried

### ISSUE THREAD

**Issue by tamlyn** [OptimalBits/bull#1667]
## Description

For compliance reasons I need to delete all jobs in the queues at a certain time each day. But I'm having trouble deleting jobs that have failed and are waiting to be retried. The problem is that in the first 30 seconds after failing the job is still locked and I have to call `releaseLock` before cleaning the queue. But after 30 seconds the lock expires and calls to `releaseLock` fail. 

I don't really understand why the locks work this way. It seems that the lock should be released as soon as the job fails, not after a 30 second delay. 

How can I tell if a job is locked before trying to unlock it? Or is there a better way to achieve what I want?

## Minimal, Working Test code to reproduce the issue.

```
const Bull = require('bull');

const queue = new Bull('test');
queue.process((job) => Promise.reject(`Fail job ${job.id}`));
const job = queue.add({ foo: 'bar' }, { attempts: 10, backoff: 60000 });

// this doesn't delete the job because it is still locked
setTimeout(() => queue.clean(0, 'delayed'), 5000);

// this would work if the job was still locked 
// but as the lock expired after 30 seconds, it also fails 
setTimeout(async () => {
  await job.releaseLock();
  queue.clean(0, 'delayed');
}, 35000);

```

## Bull version

3.12.1

**Comment by wenq1** [comment]
setting GracePeriod might help

**Comment by manast** [comment]
The new obliterate method should do what you want: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueobliterate
