### ISSUE TITLE
Job being processed not in the same node process in which it was added.

### ISSUE THREAD

**Issue by akramali86** [OptimalBits/bull#1669]
## Description
Hi. i'm finding that if i have multiple instances of my app running with a queue and if i add a job in one instance of my app it gets randomly processed in any of the apps. Is this intended behaviour? Thank you.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
Two express servers running using the below code, one on port `3000` and another on `3001`.

```javascript
const express = require('express');
const Queue = require('bull');

const queue = new Queue('queue');
const PORT = process.env.PORT ? parseInt(process.env.PORT, 10) : 3000;

queue.process(async function(job, done) {
    console.log('job received from process', job.data.processId);
    console.log('job processing on ', process.pid);
    setTimeout(() => {
        done();
    }, 5000)
})

const app = express();
app.get('/queue', function(req, res) {
    queue.add({ processId: process.pid });
    res.json({ message: 'ok'});
});

app.listen(PORT, () => console.log(`Listening on port ${PORT}`));
```
Console output:
<img width="298" alt="Screenshot 2020-03-09 at 17 48 23" src="https://user-images.githubusercontent.com/6383270/76242224-38d93c80-622e-11ea-8159-b57a993e5ee4.png">

## Bull version
^3.13.0

**Comment by germansokolov13** [comment]
That's how message queues usually work in general. Queue is an inter-process and inter-node comunication tool to begin with. But maybe there might be tools or configuration for that
