### ISSUE TITLE
Unable to Override the Job Id while adding the job to queue.

### ISSUE THREAD

**Issue by brahmeshwar** [OptimalBits/bull#1670]
## Description
I want to create a Job with my own unique JobId, I have followed the documentation when I am trying to add a job in the queue, Job is created with the JobId, not with Id which is passed in the opts.
## 
 const jobData = { x, y, z };
  const opts = {
    repeat: {
      cron: '0 */1 * * *',
    },
    jobId: '12345',
  };
s = reIndexQueue.add(jobData, opts);
####When I am printing the "s"  below  is the result. Please resolve the issue ASAP.

Job {
  opts:
   { repeat: { count: 1, cron: '0 */1 * * *', jobId: '12345' },
     jobId: 'repeat:743e7cca433a517adef9de1521e8d7f4:1583911800000',
     delay: 1616465,
     timestamp: 1583910183535,
     prevMillis: 1583911800000,
     attempts: 1,
     backoff: undefined },
  name: '__default__',
  queue:
   Queue {
     name: 'reIndex',
     token: '7a466d86-5244-42a8-8aee-02d56efcbacc',
     keyPrefix: 'bull',
     clients: [ [Redis], [Redis], [Redis] ],
     clientInitialized: true,
     _initializing: Promise { undefined },
     handlers: { __default__: [Function] },
     processing: [ [Promise] ],
     retrieving: 0,
     drained: true,
     settings:
      { lockDuration: 30000,
        stalledInterval: 30000,
        maxStalledCount: 1,
        guardInterval: 5000,
        retryProcessDelay: 5000,
        drainDelay: 5,
        backoffStrategies: {},
        lockRenewTime: 15000 },
     _events: [Object: null prototype] { error: [Function] },
     _eventsCount: 1,
     timers: TimerManager { idle: true, listeners: [], timers: {} },
     moveUnlockedJobsToWait: [Function: bound ],
     processJob: [Function: bound ],
     getJobFromId: [Function: bound ],
     keys:
      { '': 'bull:reIndex:',
        active: 'bull:reIndex:active',
        wait: 'bull:reIndex:wait',
        waiting: 'bull:reIndex:waiting',
        paused: 'bull:reIndex:paused',
        resumed: 'bull:reIndex:resumed',
        'meta-paused': 'bull:reIndex:meta-paused',
        id: 'bull:reIndex:id',
        delayed: 'bull:reIndex:delayed',
        priority: 'bull:reIndex:priority',
        'stalled-check': 'bull:reIndex:stalled-check',
        completed: 'bull:reIndex:completed',
        failed: 'bull:reIndex:failed',
        stalled: 'bull:reIndex:stalled',
        repeat: 'bull:reIndex:repeat',
        limiter: 'bull:reIndex:limiter',
        drained: 'bull:reIndex:drained',
        progress: 'bull:reIndex:progress' },
     delayedTimestamp: 1583911800000.0024,
     _initializingProcess: Promise { null },
     errorRetryTimer: {},
     subscriberInitialized: true,
     registeredEvents: { delayed: [Promise] },
     delayTimer:
      Timeout {
        _called: false,
        _idleTimeout: 5000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 112949,
        _onTimeout: [Function],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(unrefed)]: false,
        [Symbol(asyncId)]: 10763,
        [Symbol(triggerId)]: 0 },
     bclientInitialized: true,
     moveUnlockedJobsToWaitInterval:
      Timeout {
        _called: true,
        _idleTimeout: 30000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 97929,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: 30000,
        _destroyed: false,
        [Symbol(unrefed)]: false,
        [Symbol(asyncId)]: 202,
        [Symbol(triggerId)]: 0 } },
  data: { domainId: '97112609', campaignId: '1', variantId: '0' },
  _progress: 0,
  delay: 1616465,
  timestamp: 1583910183535,
  stacktrace: [],
  returnvalue: null,
  attemptsMade: 0,
  toKey: [Function: wrapper],
  id: 'repeat:743e7cca433a517adef9de1521e8d7f4:1583911800000' }

**Comment by manast** [comment]
repeatable jobs do use the jobId internally to generate every repetition jobId but it cannot use the same Id for all the repetitions.

**Comment by brahmeshwar** [comment]
> ## Description
> I want to create a Job with my own unique JobId, I have followed the documentation when I am trying to add a job in the queue, Job is created with the JobId, not with Id which is passed in the opts.
> 
> const jobData = { x, y, z };
> const opts = {
> repeat: {
> cron: '0 */1 * * *',
> },
> jobId: '12345',
> };
> s = reIndexQueue.add(jobData, opts);
> ####When I am printing the "s" below is the result. Please resolve the issue ASAP.
> 
> Job {
> opts:
> { repeat: { count: 1, cron: '0 */1 * * *', jobId: '12345' },
> jobId: 'repeat:743e7cca433a517adef9de1521e8d7f4:1583911800000',
> delay: 1616465,
> timestamp: 1583910183535,
> prevMillis: 1583911800000,
> attempts: 1,
> backoff: undefined },
> name: '**default**',
> queue:
> Queue {
> name: 'reIndex',
> token: '7a466d86-5244-42a8-8aee-02d56efcbacc',
> keyPrefix: 'bull',
> clients: [ [Redis], [Redis], [Redis] ],
> clientInitialized: true,
> _initializing: Promise { undefined },
> handlers: { **default**: [Function] },
> processing: [ [Promise] ],
> retrieving: 0,
> drained: true,
> settings:
> { lockDuration: 30000,
> stalledInterval: 30000,
> maxStalledCount: 1,
> guardInterval: 5000,
> retryProcessDelay: 5000,
> drainDelay: 5,
> backoffStrategies: {},
> lockRenewTime: 15000 },
> _events: [Object: null prototype] { error: [Function] },
> _eventsCount: 1,
> timers: TimerManager { idle: true, listeners: [], timers: {} },
> moveUnlockedJobsToWait: [Function: bound ],
> processJob: [Function: bound ],
> getJobFromId: [Function: bound ],
> keys:
> { '': 'bull:reIndex:',
> active: 'bull:reIndex:active',
> wait: 'bull:reIndex:wait',
> waiting: 'bull:reIndex:waiting',
> paused: 'bull:reIndex:paused',
> resumed: 'bull:reIndex:resumed',
> 'meta-paused': 'bull:reIndex:meta-paused',
> id: 'bull:reIndex:id',
> delayed: 'bull:reIndex:delayed',
> priority: 'bull:reIndex:priority',
> 'stalled-check': 'bull:reIndex:stalled-check',
> completed: 'bull:reIndex:completed',
> failed: 'bull:reIndex:failed',
> stalled: 'bull:reIndex:stalled',
> repeat: 'bull:reIndex:repeat',
> limiter: 'bull:reIndex:limiter',
> drained: 'bull:reIndex:drained',
> progress: 'bull:reIndex:progress' },
> delayedTimestamp: 1583911800000.0024,
> _initializingProcess: Promise { null },
> errorRetryTimer: {},
> subscriberInitialized: true,
> registeredEvents: { delayed: [Promise] },
> delayTimer:
> Timeout {
> _called: false,
> _idleTimeout: 5000,
> _idlePrev: [TimersList],
> _idleNext: [TimersList],
> _idleStart: 112949,
> _onTimeout: [Function],
> _timerArgs: undefined,
> _repeat: null,
> _destroyed: false,
> [Symbol(unrefed)]: false,
> [Symbol(asyncId)]: 10763,
> [Symbol(triggerId)]: 0 },
> bclientInitialized: true,
> moveUnlockedJobsToWaitInterval:
> Timeout {
> _called: true,
> _idleTimeout: 30000,
> _idlePrev: [TimersList],
> _idleNext: [TimersList],
> _idleStart: 97929,
> _onTimeout: [Function: bound ],
> _timerArgs: undefined,
> _repeat: 30000,
> _destroyed: false,
> [Symbol(unrefed)]: false,
> [Symbol(asyncId)]: 202,
> [Symbol(triggerId)]: 0 } },
> data: { domainId: '97112609', campaignId: '1', variantId: '0' },
> _progress: 0,
> delay: 1616465,
> timestamp: 1583910183535,
> stacktrace: [],
> returnvalue: null,
> attemptsMade: 0,
> toKey: [Function: wrapper],
> id: 'repeat:743e7cca433a517adef9de1521e8d7f4:1583911800000' }

Sir, then If I want to update the CRON frequency of the job then, how to make it? Could you please help me with this.
