### ISSUE TITLE
Change CRON frequency for the repeatable jobs

### ISSUE THREAD

**Issue by brahmeshwar** [OptimalBits/bull#1671]
## I have a query regarding the issue no. #1670 1670

Thanks for the quick reply, As, you replied to the issue which I have raised. As you said the jobId is custom one for repeatable jobs and all the jobIds are not according to my fashion, If I want to change the CRON frequency of the repeatable job which is in the queue, Can u please guide me on how to proceed.

**Comment by Jageen** [comment]
Tips: 
When you decide to change cronjob frequency it implies that your future jobs are invalidated so,
1] Delete old one using [queueremoverepeatable](https://github.com/OptimalBits/bull/blob/HEAD/REFERENCE.md#queueremoverepeatable)
2] Create new one with new cronjob frequencies :) using [add](https://github.com/OptimalBits/bull/blob/HEAD/REFERENCE.md#queueremoverepeatable)
