### ISSUE TITLE
Remove repeatable jobs does not remove the next repeatable job

### ISSUE THREAD

**Issue by KidkArolis** [OptimalBits/bull#1676]
Here's my queue state in redis after adding repeatable jobs to the queue:

```
127.0.0.1:6379> keys *
1) "hmns:dev:bull:events:repeat"
2) "hmns:dev:bull:events:repeat:b5230d67db4ca2b571297e5f6cc5db8d:1584370800000"
3) "hmns:dev:bull:events:repeat:ba0b04b62c1854a6669fea27137765a9:1584369000000"
4) "hmns:dev:bull:events:delayed"
5) "hmns:dev:bull:events:stalled-check"
6) "hmns:dev:bull:events:id"
127.0.0.1:6379> zrange hmns:dev:bull:events:repeat 0 100
1) "clean::::30 * * * *"
2) "kick::::0 * * * *"
```

And now I run:

```js
for (const repeatable of await queue.getRepeatableJobs()) {
  await queue.removeRepeatableByKey(repeatable.key)
}
```

And the state is updated to:

```
127.0.0.1:6379> keys *
1) "hmns:dev:bull:events:repeat:b5230d67db4ca2b571297e5f6cc5db8d:1584370800000"
2) "hmns:dev:bull:events:repeat:ba0b04b62c1854a6669fea27137765a9:1584369000000"
3) "hmns:dev:bull:events:delayed"
4) "hmns:dev:bull:events:stalled-check"
5) "hmns:dev:bull:events:id"
```

As you can see, the `hmns:dev:bull:events:repeat` has been removed, but the 2 `repeat` jobs aren't. I'm not sure this is the intended behaviour and what side effects this could cause.

Seems to be related to how the repeatJobId is being generated without millis here: https://github.com/OptimalBits/bull/blob/ec8ad57ecc6bd111097fb341be955fa68356e221/lib/repeatable.js#L103

**Comment by manast** [comment]
this is the intended behaviour, it will remove the "meta" job that keeps the jobs repeating, not delete the jobs themselves.

**Comment by Guidanz-Kishore** [comment]
> this is the intended behaviour, it will remove the "meta" job that keeps the jobs repeating, not delete the jobs themselves.

Does that mean the job will repeat again? I also tried using removeRepeatableByKey and in the bull dashboard, i can still see the job in "Delayed" list.

**Comment by manast** [comment]
@Guidanz-Kishore which version are you using? when deleting with removeRepeatableByKey, assuming you provided the correct key, it will delete both the meta and the current delayed job that has not yet been executed.

**Comment by Guidanz-Kishore** [comment]
Bull version - 3.18.0
bull-board version - 0.9.0
Redis version - 6.0.8
I am using getRepeatableJobs() to get the list of repeatable jobs. From that, i am getting the key that needs to be passed as parameter to removeRepeatableByKey(). But even after that. the job is still shown in the bull dashboard. Here is the code snippet for the function. Kindly let me know if you want any further details. 

const removeRepeatable = (jobId) => {
	return new Promise(async(resolve, reject) => {
		try {
			const job = await reportQueue.getRepeatableJobs(0, -1, false);
			const repeatableJob = job.find(element => {
				if (element !== null && element.id === jobId) {
					return element;
				}
				return {};
			});
			if (repeatableJob === null || repeatableJob === undefined || Object.keys(repeatableJob).length === 0) {
				log.info(`------------Report with jobId= ${jobId} is not scheduled yet.---------`);
				resolve(true);
			} else {
				log.info(`------------Schdule removed for jobId=${jobId}------------`);
				console.log('repeatableJob', repeatableJob);
				await reportQueue.removeRepeatableByKey(repeatableJob.key);
				const job2 = await reportQueue.getRepeatableJobs(0, -1, false);
				console.log('job2', job2);//Shows empty array since the job is already removed. 
				resolve(true);
			}
		} catch (error) {
			log.error('queueAdd---------removeRepeatable()---------------Error in removeRepeatable()------', error);
			reject(error);
		}
	});
};

**Comment by manast** [comment]
@Guidanz-Kishore can you provide a screenshot from the dashboard where you see the repeatable job?

**Comment by Guidanz-Kishore** [comment]
![Screenshot from 2020-10-26 18-21-47](https://user-images.githubusercontent.com/54881818/97174509-34ab6080-17b8-11eb-8738-1a25c05056e6.png)

**Comment by Guidanz-Kishore** [comment]
This is taken after i removed the job using removeRepeatableByKey(). I used to remove the job from bull using job.remove() previously. But the issue i am facing is that, it is really inconsistent in removing the job. Sometimes it is getting successfully removed and sometimes it is not. Let me know if you want any additional information. Thanks...

**Comment by Guidanz-Kishore** [comment]
@manast did I miss anything from my end?

**Comment by manast** [comment]
@Guidanz-Kishore no, there was an issue, it is fixed in the PR above. I will release soon.

**Comment by Guidanz-Kishore** [comment]
Great. Thank you very much for the support @manast.

**Comment by manast** [comment]
@Guidanz-Kishore please check the new release 3.18.1.

**Comment by Guidanz-Kishore** [comment]
Sure. Will check it out. Thanks

**Comment by SowmiyaJeevanandham** [comment]
iam using bullmq version of 5.8.4 i treid to remove the job using removeRepeatableByKey but still the job in redis exist 
  if (repeatableJobs.length > 0) {
                    try {
                        for (const job of repeatableJobs) {
                            console.log('Current repeatable configs: ', job, null, 2);
                            removeJobRes = await denseQueue.removeRepeatableByKey(job.key);
                            console.log(`Removed job with key: ${job.key} - Result: ${removeJobRes}`);
                        }
                    } catch (error: any) {
                        logger.error(`Function: stopBackup, removeRepeatableByKey has error: ${error.message}`);
                        throw new Error("Job is not deleted in redis");
                    }                    
                } else {
                    logger.info('Function: stopBackup, No repeatable jobs found to remove.');
                }
                
                console.log("-----------pafter job remove:", await denseQueue.getRepeatableJobs(), removeJobRes);
