### ISSUE TITLE
LUA script leads to OOM error and Redis failover

### ISSUE THREAD

**Issue by JoHuang** [OptimalBits/bull#1681]
## Description
I'm using Bull on Redislab cloud service, I got support team's message:

> We have seen some issues with your current LUA usage, one of the challenges with LUA script is that it may get Redis stuck and that can lead to downtime and data loss.

I simply use a queue for scheduling job like the code below.

the detail performance graph provided by Redislab:
<img width="1440" alt="Screenshot 2020-03-22 08 29 22" src="https://user-images.githubusercontent.com/4118159/77379749-6c7e9f80-6db4-11ea-9c09-b01a67d7da71.png">
<img width="1006" alt="Screen Shot 2020-03-24 at 9 44 26 AM" src="https://user-images.githubusercontent.com/4118159/77379767-7a342500-6db4-11ea-87d1-0672f4c59abd.png">

There are around 80 container instances with the same code running.
About 4000 delay jobs may be in the queue.

I have no LUA knowledge or how bull use Redis, please help. 
Any options I can set to help?
Or I just need to upgrade the resource?
Thanks

## Minimal, Working Test code to reproduce the issue.
```js
"use strict";
const REDIS_DB_HOST = process.env.REDIS_DB_HOST || "";
const REDIS_DB_PWD  = process.env.REDIS_DB_PWD  || "";
const Queue = require("bull");

const queueName = `the-scheduler`;
const [HOST,PORT] = REDIS_DB_HOST.split(":");
const schedulerQueue = new Queue(queueName, {
    redis: {
        port: PORT,
        host: HOST,
        password: REDIS_DB_PWD
    }
});

let uniqueCallback = null;
schedulerQueue.process( (job, done) => {
    if (uniqueCallback) {
        uniqueCallback(job.data);
    }
    done();
});

class Scheduler {
    static setScheduleProcess( callback ) {
        uniqueCallback = callback;
    }
    static async setSchedule(key, data, miliseconds, callback) {
        if (!uniqueCallback) {
            uniqueCallback = callback;
        }

        try {
            let job = await schedulerQueue.getJob(key);
            if (job) {
                await job.remove();
            }
    
            job = await schedulerQueue.add( data, {
                delay : miliseconds,
                attempts : 1,
                timeout : 10 * 1000,
                jobId : key,
                removeOnComplete : true,
                removeOnFail : true,
            });
        }
        catch (e) {
            
        }

    }
}

module.exports = Scheduler;
```

## Bull version
3.12.1

**Comment by manast** [comment]
OOM stands for Out out Memory, so it seems like the redis instance run out of memory.
On the charts you pasted there is no one showing memory consumption, but it seems like your only choice is either to increase the memory size of the redis instance or delete old jobs, in Bull you can setup a maximum amount of old jobs to keep, that usually does the trick.

**Comment by jdgriffith** [comment]
What is the config option for deleting old jobs?
