### ISSUE TITLE
migrating from kue - question

### ISSUE THREAD

**Issue by ProximalPod** [OptimalBits/bull#1682]
I have a pretty big codebase running a patched up version of kue and I'm evaluating switching to a solution that is still being maintained.

I read on the description about the "at least once" working strategy and that could be troublesome for our use case. However it'd seem to me that if I set maxStalledCount to 0, I'd eliminate the case in which the jobs could run more than once. I understand that they could potentially not run at all, but in my case it's preferable. Am I correct in assuming that setting maxStalledCount to 0 is enough to eliminate possible duplication?
Thanks!

**Comment by manast** [comment]
yes, with maxStalledCount 0 it will run with "at most once" semantics, but normally exactly once, only on edge cases when a worker fails for some reason some jobs will never complete, however they will fail eventually so you can keep track of them.
