### ISSUE TITLE
Jobs failed : job stalled more than allowable limit

### ISSUE THREAD

**Issue by Juanperezc** [OptimalBits/bull#1685]
## Description

Hello, I have had the following problem for a long time, I am managing a process queue for emails and approximately 1000 emails are sent daily, it happens to me a lot that in the email queue the processes remain active and after a while they fail due to

`
job stalled more than allowable limit
--

Try to increment the maxStalled variable times and the problem still persists

I have to restart the failed jobs at least 20 times a day and after a while processes them all
`
## Minimal, Working Test code to reproduce the issue.

I handle these events for each queue and the mail queue has 5 processes

```js
const handleFailure = (job, err) => {
  console.log(job)
  if (job.attemptsMade >= job.opts.attempts) {
    console.error(
      `Job failures above threshold in ${job.queue.name} for: ${JSON.stringify(
        job.data
      )}`,
      err
    );
    job.failed();
    job.remove();
    return null;
  }
  console.error(
    `Job in ${job.queue.name} failed for: ${job.queue.name} with ${
      err.message
    }. ${job.opts.attempts - job.attemptsMade} attempts left`
  );
};

const handleCompleted = job => {
  console.log(
    `Job in ${job.queue.name} completed for: ${job.queue.name}`
  );
  if (job){
  job.completed();
  job.remove();
}
};
/*  const handleWaiting = job => {
  job.waiting();
  console.log(`Job in ${job.queue.name} waiting for: ${job.queue.name}`)
}  */

const handleStalled = job => {
  /* job.delayed(); */
  console.log(`Job in ${job.queue.name} stalled for: ${job.queue.name}`)
 /*  logger.info(
    `Job in ${job.queue.name} stalled for: ${job.queue.name}`
  ); */
};
```
## Bull version
3.12.1

**Comment by pengdafu** [comment]
I hava same problem

**Comment by richardyang-dev** [comment]
I have same problem. My issue is even worse. Once this happens to one job, all subsequent jobs that are added to the same queue will fail with the same dreadful  and mysterious "job stalled more than allowable limit".

**Comment by manast** [comment]
All the code above is basically ignoring that the methods returns promises so if the same pattern is used inside a bull processor it will not work.

**Comment by MFawzy-mismar** [comment]
this happened to me because I was adding a custom back off strategy in the publish options, and I didn't define it in the queue settings
