### ISSUE TITLE
rate limit and max concurrency jobs not working properly

### ISSUE THREAD

**Issue by sibelius** [OptimalBits/bull#1687]
## Description

I'd like to limit the number of jobs run by a single bull pod (docker image running instance)

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

I have a single queue, defined like this:

```jsx
export const queues = {
  DEFAULT: new Queue('DEFAULT', REDIS_HOST, {
    limiter: {
      max: 25,
      duration: 60000, // 1 minute
    },
  }),
};
```

I have job handler for each name (named job),  I define them like this:

```jsx
queue.process('name',  1, jobHandler);
queue.process('anotherName',  1, anotherJobHandler);
```

I set the concurrency to be `1`

I create a new job like this:

```jsx
queue.add(type, payload, params)
```

I'm using bull-arena (https://github.com/bee-queue/arena) to visualize and debug jobs execution

After creating many jobs (900 jobs), I get 100 jobs running in parallel

how can we limit to run only 1 named job in parallel?

## Bull version
3.13.0

**Comment by manast** [comment]
can you please provide a complete testable case so that I can reproduce it ?

**Comment by cfey** [comment]
I got the same problem :/
I explicitly set the concurrency to 1 and still the consumer get's invoked multiple times instead of taking jobs one by one

**Comment by cfey** [comment]
I tried to create a local environment on which this happens, unfortunately it's only occurring on our servers on heroku :/

**Comment by cfey** [comment]
@manast I was able to reproduce this behaviour
it seems like, when creating the consumer and calling this `queue.process(jobName, 1, jobHandler);`  needs to be handled with an `await` statement
I created multiple named jobs and consumers on the same queue, when I added `AWAIT queue.process(jobName, 1, jobHandler);` my issue was resolved
I created a small example, it's written in TS

```
import * as Bull from 'bull';
import config from '../config';

(async () => {
  try {
    const queueName = 'notification';
    const jobNames = {
      foo: 'foo',
      bar: 'bar',
    }

    const queue: Bull.Queue = new Bull(queueName, {
      redis: config.env.REDISCLOUD_URL,
    });


    const sender = {

      send: async (id): Promise<void> => {
        console.log('send', id);

        await queue.add(jobNames.foo, {
            type: jobNames.foo,
            sessionId: id,
          },
        );
      },
    };

    const consumer = {
      foo: async (job: any): Promise<void> => {
        const message = job.data;
        const log = (...params) => {
          console.log(`session ID: ${message.sessionId} |`, ...params);
        };
        log('start');

        const promise = new Promise((resolve) => {
          setTimeout(resolve, 2000);
        });

        await promise;

        log('end');
      },

      bar: async (job: any): Promise<void> => {
        const message = job.data;

        console.log('bar', message);
      },
    };
    console.log('Start');
    queue.process(jobNames.foo, 1, consumer.foo);
    queue.process(jobNames.bar, 1, consumer.bar);
    console.log('consumer started')


    const promises: any = [];
    for (let i = 0; i < 10; i++) {
      promises.push(sender.send(i));
    }
    await Promise.all(promises);

    console.log('End');

  } catch (err) {
    console.log('err', err);
  }
})();
```
When you run this code, there will always be 2 concurrent handling on the jobs
when you add `await` in front of the `queue.process....` then it's one by one

**Comment by manast** [comment]
@cfey that is the expected behaviour since you are defining process 2 times, each with concurrency 1 so total concurrency 2. You can read more in this thread: https://github.com/OptimalBits/bull/issues/1113

**Comment by cfey** [comment]
@manast thanks for the clarification
after reading the thread, it makes a lot of sense to move the concurrency option to the queue creation 😅
