### ISSUE TITLE
Many jobs stuck in the waiting list 

### ISSUE THREAD

**Issue by vancelin** [OptimalBits/bull#1690]
## Description

Hello there,

I have two functions, one is schedule.js, which can periodically add jobs to the queue. ProcessQueue.js has been running since the beginning, in response to the consumption queue.

My question is, after running for a period of time, sometimes a lot of work is stuck in the waiting list. So I'm trying to check the status of the workers when running each schedule, there are one or zero idle workers, is this the point? Because I have to restart npm to start consuming the queue every time.

If the key is that there are no idle workers, what should I do? If not, is there any problem?

thanks!

schedule.js
```
  async enqueueTasks() {
      try {
     
      const transactionHashQueue = new Bull('transactionHash', { redis: this.config.redis.bull });
      const scheduleWorker = await transactionHashQueue.getWorkers();
      console.log(scheduleWorker);
      // get data array from database
      const allTransactionHashs = await this.ctx.service.eventTracker.getAllTransactionHashs(0);

      await Promise.all(
        allTransactionHashs.map(async t => {
          const obj = {
            attempts: 3,  
            jobId:  t.transactionHash
          };
          await transactionHashQueue.add('__default__', t, obj);
        })
      );

      await transactionHashQueue.close();
    } catch (err) {
      this.logger.error('enqueueTasks', err);
    }
  }
```
processQueue.js
```
  async processQueue() {
    const transactionHashQueue = new Bull('transactionHash', { redis: this.config.redis.bull });
    transactionHashQueue.process(async (job, done) => {

      try {
          const transactionHash = job.data.transactionHash;
          if (transactionHash) {
            updateDB();
            done();
          }
      } catch (err)
        this.logger.error('processQueue', err);
      }
    }); 
  }
```

**worker status**
```
scheduleWorker =  [ { id: '5',
    addr: '172.28.0.4:52336',
    fd: '8',
    name: 'transactionHash',
    age: '98988',
    idle: '1',
    flags: 'N',
    db: '0',
    sub: '0',
    psub: '0',
    multi: '-1',
    qbuf: '0',
    'qbuf-free': '0',
    obl: '0',
    oll: '0',
    omem: '0',
    events: 'r',
    cmd: 'evalsha' } ]
```

## Bull version

3.13.0

**Comment by pengdafu** [comment]
I have the same problem

**Comment by damcorp** [comment]
I have the same problem too. sometimes it just stuck when I add thousands of jobs. it just stuck until i restart them

**Comment by manast** [comment]
This code is incorrect: 
```ts
 async processQueue() {
    const transactionHashQueue = new Bull('transactionHash', { redis: this.config.redis.bull });
    transactionHashQueue.process(async (job, done) => {

      try {
          const transactionHash = job.data.transactionHash;
          if (transactionHash) {
            updateDB();
            done();
          }
      } catch (err)
        this.logger.error('processQueue', err);
      }
    }); 
  }
```

Basically when you throw an exception you will just log the error but never finish the processing, therefore the worker will be busy forever doing nothing.

**Comment by manast** [comment]
@pengdafu & @damcorp please provide code that reproduces the issue. There is no known issue in Bull where jobs gets "stuck", this is most probably a problem in your own code.

**Comment by manast** [comment]
```ts
transactionHashQueue.process(async (job) => {
          const transactionHash = job.data.transactionHash;
          if (transactionHash) {
            await updateDB();
          }
    }); 
```

**Comment by manast** [comment]
or shorter:
```ts
transactionHashQueue.process(async (job) => job.data.transactionHash && updateDB());
```

**Comment by nivapo95** [comment]
I have the same issue and can not find a solution online.
Even if it's an issue in our code and not on bull, it is not clear what is the cause for the issue and there is no documentation on what makes the jobs get stuck in the "waiting" queue.

I will share insights once I'll figure this out.

**Comment by manast** [comment]
@nivapo95 this is documented. You either need to use done or return a promise (or define the processor with async), but NOT use both done and promise.
If possible migrate to BullMQ where the done callback is removed so this confusion cannot happen anymore.

**Comment by caycewilliams** [comment]
@manast In nest js, even when returning, some of my jobs seem to get stuck in waiting forever, not a clue why, restarting the server makes them go through just fine

**Comment by manast** [comment]
@caycewilliams maybe the worker has lost its connection with Redis.

**Comment by manast** [comment]
This may be useful for you even if it is for BullMQ: https://docs.bullmq.io/guide/going-to-production#automatic-reconnections
