### ISSUE TITLE
Async task initiated by one server, is blocked by another connected server who has syntax errors on their queue processing code

### ISSUE THREAD

**Issue by PeriGK** [OptimalBits/bull#1696]
## Description

I am using bull in order to send emails in the background. I have a processor file as instructed in your documentation. Nothing fancy. It works like a charm, bar this time I am reporting.

We are two people working on the server-side, from different physical areas (no common IP).

I have triggered an email job, I saw the new entry in my Redis. But the email never arrived.
Curious I went down to the stacktrace to inspect.

The error was like ```/home/your_colleagues_home/<your_colleagues_relative_path> has the following error:```

The error was pure js syntax error, nothing big, and when we fixed it, we were back to working state.

My questions are:

We both had open servers at this time, but he was doing nothing to trigger emails. 
We both have access in Redis with the same key. So at that moment, there was an open channel for both of us to the Redis db.

### What was happening (and we verified it in a pair programming session) was:

I trigger the email, **he gets an error on his console about mail processing**. I am suspecting that there is some kind of logic that expects to get a "success" response from all nodejs "clients" to proceed. When the syntax error was fixed, the emails just went through, of course, as mentioned above.

What I would expect? When I trigger the email, it will be send unless the process fail on my server only.

Is this a misconfig on my side? Is this something you can look into?

Happy to answer any follow-up questions.

Thanks,
P.

## Bull version
3.13

**Comment by manast** [comment]
I am not sure I understand entirely your use case, but the way bull works is based on round robin among the available workers, so if you have 2 workers, every each time a job is processed it will be processed alternating by one of them. If one of the workers has a javascript error or other bug that makes the job fail, then the job will fail... you need to make sure that all the workers are running the same code to avoid strange cases.

**Comment by PeriGK** [comment]
@manast Thank you for clean explanation and prompt response. My case was that one of the node servers had syntax errors which were causing the process to stop. So that explains my problem and its solution.

Out of technical curiosity, what is the rationale of this technical decision?

**Comment by manast** [comment]
I cannot imagine any other way to do it?

**Comment by PeriGK** [comment]
Yes, that is a valid reason of course :)

I just haven't experienced a similar phenomenon in other queue technologies I have used, so I thought that came out as an attempt to mitigate something specific.

Cheers
