### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by AlaRuba** [OptimalBits/bull#170]
Error: Cannot define a handler more than once per Queue instance

I am using a master-slave model, and I get it when my worker threads try to call Queue.process on my global Queue.

Thanks, sorry I couldn't find it in the documentation.

**Comment by albertjan** [comment]
You're calling `queue.process` more than once. The idea is that "start" the queue by calling process and you do that only once. The function you give as a parameter to process is called the handler. It handles job.

**Comment by AlaRuba** [comment]
Thanks
