### ISSUE TITLE
Drained event called multiple times?

### ISSUE THREAD

**Issue by GeorgeWillaman** [OptimalBits/bull#1700]
Hi,
I noticed that the drained event seems to be firing off multiple times even though it's only binded once. It's exactly like issue #1092 (which never got an answer relating to the multiple firings)

```
scrapeQueue.on('drained', () => {
  // Sheet Processed
  console.log(`${currentSheet-1} drained - Continuing to next sheet`);
  feed(currentSheet); // Process the next sheet
});
```

Is there a reason for this to be occurring, and if so a workaround?

**Comment by manast** [comment]
It supposed to fire every time the queue drains, do you have a test case where this does not hold?

**Comment by GeorgeWillaman** [comment]
Yep. I'm not at my computer at the minute, but I'll provide some more of my code tomorrow morning :)

**Comment by GeorgeWillaman** [comment]
Actually I'm able to send over some code right now. 
```
const feed = async (sheetId) => {
  const contacts = (
    await axios.get(`http://xxx.xxx.xxx.xx:3000/A/A_${sheetId}.json`)
  ).data;
  await _.forOwn(contacts, async (contact) => {
    proxies = await rotate(proxies);
    await scrapeQueue.add({
      name: contact.name,
      proxy: proxies[0],
      attempt: 1,
    }, {
      removeOnComplete: true,
      removeOnFailed: true,
    });
  });
  console.log(`Sheet #${currentSheet} | Adding ${contacts.length} items to queue!`);
  currentSheet++;
};
feed(currentSheet);

scrapeQueue.process(
  20,
  `${__dirname}/processor.js`,
);
```
etc...
 
It's strange, as for the first sheet (as well as the following) the drain event fires multiple times. Specifically, the first sheet fires _drained_ twice, which ends up calling feed() twice, which keeps on repeating.

**Comment by GeorgeWillaman** [comment]
Update: Decreased concurrency to 5 and it doesn't fire drained multiple times, so it works as planned. Any idea why it wouldn't work w/ a higher concurrency value?
