### ISSUE TITLE
Override job data if ID is already existing

### ISSUE THREAD

**Issue by emaxters** [OptimalBits/bull#1704]
Is there a way to update a job when adding (Queue#add) if the Job ID is already exists.
As per the docs, it says it will be not added if the ID is already there, in that case we have to check whether the ID is already exists when creating a job. Instead it will be helpful if there is an option to override the data if the ID is already exists, or create a new job.

**Comment by manast** [comment]
You can use the job.update method: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#jobupdate

**Comment by emaxters** [comment]
@manast  Will this create a new job if the ID not exists?

**Comment by shubhddn01** [comment]
@manast  I am unable to use update function, can you just help me out? Also please let me know if i can get boolean for the requested jobId already exist. Thanks in advance.

**Comment by manast** [comment]
@shubhddn01 what is not working with the update function?
Regarding existing jobs, you can get the job and if it exists it will be returned...
