### ISSUE TITLE
Update the status of completed Job

### ISSUE THREAD

**Issue by emaxters** [OptimalBits/bull#1708]
## Description
We have a task which has several lifecycle events (Pending, Processing, Queued, Sent, Completed, etc.). In each state we add a job to the Queue and update the database on queue process. For example if we have 1million tasks, there may be 5 million jobs in the queue.
To reduce the number of jobs, we have added a patch to create a JobId for each unique task, and if a job is already existing with that ID we update the same job with the new lifecycle status.

We use `Queue.getJob` to check whether the job is already exists and `Job.update` to update the new status.

The issue is, when we updating the job, sometime the previous job is getting processed and completes. And hence, the updated Job is not getting processed. Is there a way to update the Job status also when updating the job. So that, if it is already completed, it will be created again.

**Comment by manast** [comment]
I am afraid what you are asking is not possible to do with bull.
