### ISSUE TITLE
Queue executes itself.

### ISSUE THREAD

**Issue by misterjt** [OptimalBits/bull#171]
var Queue = require('bull');
var qu=Queue('JUSTTEST');
for(var i=0;i<10000;i++)qu.add({n:i});
qu.count().then(console.log) // 6872
qu.count().then(console.log) // 6210
qu.count().then(console.log) // 5059 
........
........
No handler defined. Is this normal?

**Comment by manast** [comment]
it does not seem to be normal. I have to investigate this.

**Comment by albertjan** [comment]
```js
  var Queue = require('bull');
  var qu=Queue('JUSTTEST');
  for(var i=0;i<10000;i++)
    qu.add({n:i});
  
  setTimeout(function(){
    qu.count().then(console.log);
  }, 5000);
```

says 10000 after 5 seconds

**Comment by manast** [comment]
seems there is no issue here so I will close.
