### ISSUE TITLE
[question] How do I test if my task has added another job to the queue?

### ISSUE THREAD

**Issue by jerrythomas** [OptimalBits/bull#1711]
## Description
I have two tasks and task `one`, processes some data and passes it on to task 'two. How do I test that task `two` has been added to the queue?

## Minimal, Working Test code to reproduce the issue.
Sample code with functionality

```js
const Queue = require('bull');
const Redis = require('ioredis');

const taskQ = new Queue('tasks', { connection: new Redis() });

function handlerOne(job, done){
  console.log('one', job.data, job.opts)
  taskQ.add('two', {x: job.data.x+10})
  done()

}

function handlerTwo(job, done){
  console.log('two', job.data, job.opts)
  done()
}

taskQ.process('one', handlerOne);
taskQ.process('two', handlerTwo);

taskQ.add('one', {x: 1});
```
#### Tap tests to verify task works.

For testing, I am not adding the tasks to queue to test it. But this also means that I don't see a way to verify task addition.

```js
const {test} = require('tap');
const {taskQ , handlerOne, handlerTwo} = require('../queues.js');

test('task "One" works', (t) =>{
  t.plan(2);

  handlerOne({data:{x:1}}, (err, res) =>{
    t.error(err);
    t.same(res, {status:'ok'})
    // how do I test that task two has been added to queue?
    t.end()
  })
})

test('task "Two" works', (t) =>{
  t.plan(2);

  handlerTwo({data:{x:11}}, (err, res) =>{
    t.error(err);
    t.same(res, {status:'ok'})
    t.end()
  })
})
```
## Bull version
^3.13.0
## Additional information
I am using node-tap for tests
"tap": "^14.10.7"

**Comment by manast** [comment]
If you write your handler like this:
```ts

function handlerOne(job){
  console.log('one', job.data, job.opts)
  return taskQ.add('two', {x: job.data.x+10})
}
```

it is guaranteed that if the job one completed, job two has been added successfully to the second queue.

**Comment by jerrythomas** [comment]
Thanks @manast. Wouldn't that be true with the current code as well because the `done()` callback is only executed after the `taskQadd` statement?

What if I have a scenario where `handlerOne`, processing an array, filters or aggregates some data and at the end hands off individual items of the array to a different queue. So input contained 10 items, after processing it should be 5 and these 5 are handed off to a separate queue as 5 new tasks. How do I verify that 5 tasks were created?

Another scenario: Say if I expect 10 new tasks to be created in `Q2` and 5 in `Q3` as a result of `handlerOne`, is it possible to test this?

Is there a way to inspect tasks that were created?
