### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by 0xantman** [OptimalBits/bull#1713]
## Description
Actually i'am using Redis with Bee Queue and i would like to try Bull the problem is i'am unable to connect to my Digital Ocean Redis server.

I'am using node_redis 
`const client = redis.createClient(process.env.REDIS_DIGITAL_OCEAN)`

In Bee Queue this is working for me

```
const Queue = require('bee-queue')
const addQueue = new Queue('test', { redis: client, isWorker: false })
```

In Bull i tried this is not working

```
 const Queue = require('bull')
 const addQueue = new Queue('test', { client })
```
Or

```
const Queue = require('bull')
const addQueue = new Queue('test', client)
```
But it's not working i'am getting

> Error: connect ECONNREFUSED 127.0.0.1:6379

What i'am doing wrong ? thanks

## Bull version
"bull": "^3.13.0"

**Comment by manast** [comment]
You are not supposed to pass a redis instance, try this:

```ts
const addQueue = new Queue('test', process.env.REDIS_DIGITAL_OCEAN);
```

**Comment by manast** [comment]
btw, since you are new to Bull you may want to test the next major version of bull here: https://github.com/taskforcesh/bullmq

**Comment by 0xantman** [comment]
> You are not supposed to pass a redis instance, try this:
> 
> ```ts
> const addQueue = new Queue('test', process.env.REDIS_DIGITAL_OCEAN);
> ```
Thank you for your response i tried your solution but same problem here with Bull
```
{ Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
```
And the error with BullMQ 

`[ioredis] Unhandled error event: Error: read ECONNRESET`

**Comment by 0xantman** [comment]
Ok i think i have found the problem is the TLS certificate.
