### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by amtdevops** [OptimalBits/bull#1717]
Hi, 
We are using Bull in our project, and it was working good. In our project, we process large CSV files, and put jobs to Bull queue and queue process the domain from the job data and get domain details. It was working great but we noticed when our CSV data grows to say above 2 Million and process stoped and getting memory errors.

I tried to remove our logic, run the bull example code itself with more than 2 million jobs adding to queue and got the same issue. 

**I can see, its seems like ioredis error, I was running a cluster Redis in aws and have enough memory.** 

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x2d273b5dbe1d]
    1: StubFrame [pc: 0x2d273b5dd190]
Security context: 0x2ee7d161e6e9 <JSObject>
    2: toWritable [0x21ce1eb092a9] [/home/dibeesh/projects/bitdiscovery/suggestion-crawler/node_modules/ioredis/built/command.js:~149] [pc=0x2d273b5ee28f](this=0x05634a754da9 <Command map = 0x154182c53669>)
    3: /* anonymous */ [0x23ea54945231] [/home/dibeesh/projects/bitdiscovery/suggestion-crawler/node_modules/ioredi...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fa0c0 node::Abort() [node]

**Bull Version: 3.13.0**

```
var Queue = require('bull'),
    cluster = require('cluster');

var numWorkers = 8;
var queue = new Queue("test concurrent queue");

if(cluster.isMaster){
  for (var i = 0; i < numWorkers; i++) {
    cluster.fork();
  }

  cluster.on('online', function(worker) {
    // Lets create a few jobs for the queue workers
    for(var i=0; i< 2000000  ; i++){
      queue.add({foo: 'bar'});
    };
  });

  cluster.on('exit', function(worker, code, signal) {
    console.log('worker ' + worker.process.pid + ' died');
  });
}else{
  queue.process(function(job, jobDone){
    //console.log("Job done by worker", cluster.worker.id, job.id);
    jobDone();
  });
}
```

**Comment by manast** [comment]
I would suspect the problem lies in your call to queue.add where you are not waiting for the promise, so you are creating an immense amount of promises that are not ready and cannot be garbage collected. I recommend you only add jobs in chunks of maybe 1000 jobs per chunk and do not add the next chunk until the first is ready.

**Comment by amtdevops** [comment]
Thanks for the quick response. I tried bottleneck npm for adding chunks, I can see now memory looks good, seems like the process is executing slowly. Can you check following code, am I doing anything wrong?


```
const Bottleneck = require("bottleneck/es5");
const crawler = new Queue('crawler', {
  redis: connectRedis(),
  prefix: '{crawler}'

});
const limiter = new Bottleneck({
  datastore: "ioredis",
  clearDatastore: false,
  maxConcurrent: 1000, 
  minTime: 30,
  clientOptions: {
    host: config.api.redisHost,
    port: config.api.redisPort
  }
});
//Read stream data from CSV file and add each row in to queue for processing 
//Here I am using stream resume, because i need to process 1GB csv files 

processCSV: async (name, fileName) => {
  return new Promise((resolve, reject) => {
    let filePath = config.api.basePath + fileName;
    let numConcurrent = 0;
    let paused = false;
    const maxConcurrent = 1000;
    let stream = fs.createReadStream(filePath)
        .on('error', (error) => {
          // handle error
          console.log('error processing csv');
          reject(error);
        })
        .pipe(csv())
        .on('data', (row) => {
          function checkResume() {
            --numConcurrent;
            if (paused && numConcurrent < maxConcurrent) {
              stream.resume();
              paused = false;
            }
          }

          ++numConcurrent;
          limiter.schedule(() => workerIndex.createJob(config.api.crawlerQ, row))
           .then((result) => {
           checkResume();
           });
          if (numConcurrent >= maxConcurrent) {
            stream.pause();
            paused = true;
          }
        })
        .on('end', () => {
          console.log('stream processCSV end');
          resolve(filePath);
        })
  });

}
//Add job to Queue 
createJob: async (name, data) => { 
  const options = {
    removeOnComplete: true
  };
  return limiter.schedule(() => Queue.add(data, options))
      .then((result) => {
      });
}
//Process job from queue 
index.crawler.process('crawler', async job => {
  return hostNameCrawler(job.data); // Will do fetch api data and save in a file 

});
```

**Comment by manast** [comment]
it is better to accumulate a number of csv rows, for example 100 and then parallelize the add jobs call. And please check your promise handling, your code above has side effects.
```ts
await Promise.all( rows.map ( row => createJob(name, row) )
```

**Comment by amtdevops** [comment]
@manast manast. Your comment really helped, I was thinking about other queue services without knowing my mistake.  I will try the suggested way. If you don't mind could you let me know what is the side effects of promise handling in the above code?

**Comment by manast** [comment]
you are calling ```createJob(name, row).then(checkResume, checkResume)``` without awaiting for it so it will execute the if before it is really done...

**Comment by amtdevops** [comment]
Noticed. Thanks.
