### ISSUE TITLE
API for pulling data

### ISSUE THREAD

**Issue by btmdave** [OptimalBits/bull#172]
This is an idea for bull, a convenient feature in Kue is the ability to pull data, any plans to add methods such as:

```
var videoQueue = Queue('video transcoding', 6379, '127.0.0.1');

videoQueue.getActive(fn);
videoQueue.getQueued(fn);
videoQueue.getFailed(fn);
videoQueue.getCompleted(fn);
videoQueue.getPaused(fn);
```

**Comment by manast** [comment]
those methods actually exist already, but for some reason not yet documented:
https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L601
