### ISSUE TITLE
Queue Discovery for Microservices

### ISSUE THREAD

**Issue by cjancsar** [OptimalBits/bull#1724]
##  Description

My queue is defined and named on a service. I have multiple queues across multiple services. I would like to capture ALL events across all queues on all services so that I can create a centralized results backend service. I don't want to have to share / hard-code the decentralized queue names onto my centralized results backend service, but want to **dynamically discover queues that exist on a specific redis instance on this service.**.

I have reviewed the queue function public and private methods and do not see any discovery logic. I have also briefly looked through ioredis and do not see this logic. Does anyone have any ideas?

**Alternatively, is there a way to monitor all queue events without targeting a specific queue?**

My main issue is, that if a monitor events I also then need to look up the triggering job in a specific queue.

## Pseudo code
Looking for something like this?

```
    const queues = Queue.discoverQueues(connectionDetails)
```

**Comment by ccollie** [comment]
An example:

https://github.com/UpHabit/bull_exporter/blob/master/src/metricCollector.ts#L79
