### ISSUE TITLE
[Enhancement] Update ioredis version to 4.17.1 to enable Redis 6 authentication support

### ISSUE THREAD

**Issue by asyrique** [OptimalBits/bull#1740]
## Description
ioredis has released version 4.17.1 with support for passing in `username` in addition to `password` in the redis configuration, to support Redis 6 ACLs (https://github.com/luin/ioredis/blob/master/Changelog.md#4171-2020-05-16).

Would be nice to have the ioredis version in bull updated to 4.17.1

## Bull version
v3.14.0

Thanks.

**Comment by manast** [comment]
Closing since we have upgraded ioredis some time ago.
