### ISSUE TITLE
A repeatable job with "cron" string and "startDate" value doesn't run at startDate and only at next cron's iteration

### ISSUE THREAD

**Issue by mamax2015** [OptimalBits/bull#1743]
I'm adding a job with a cron string for every minute execution and a start date
But the first run executed at the next minute after the start date.

const Bull = require('bull');

const redisOptions = {
  redis: {
    host: 'redis',
    port: '6379'
  }
}

const queue = new Bull('queueName', redisOptions);
queue.add(
  { someInfo: 'someInfo' },
  {
    repeat: {
      startDate: '2020-05-19T14:00:00',
      cron: '*/1 * * * *'
    }
  }
);

Bull version 3.14.0

**Comment by priya0607jain** [comment]
@mamax2015 Hi. Did you solved your issue? I am also facing the same.

**Comment by dbettini** [comment]
Yes, `startDate` does nothing for me. I basically have the same example as @mamax2015 , and put `startDate` 5 minutes in the future, but the job starts immediately and gets repeated every minute.

**Comment by manast** [comment]
The jobs are repeated at the intersection of ```startDate```  and the cron expression, in other words it will repeat honouring the cron expression *after* the given ```startDate```.
