### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by niftylettuce** [OptimalBits/bull#1749]

**Comment by manast** [comment]
I could read this message in the email notification. Seems to me like you feel a bit frustrated for some reason I do not understand. Bull is being used by thousands of people in production, but it is important to understand what guarantees and limitations you will get from Bull and Redis. All solutions will have different sets of guarantees and limitations and you need to work your way around that. If you have reproducible bugs I am more than happy to work on fixes for them.

**Comment by niftylettuce** [comment]
I appreciate your prompt reply, it is comforting 😄
