### ISSUE TITLE
Sequential parallel queues - Question

### ISSUE THREAD

**Issue by atullal** [OptimalBits/bull#1752]
## Implementing many sequential queue which are parallel to each other
Hi,
For my use case I need to implement many parallel queue which will contain jobs which needs to run in sequence. The jobs would be small and not very resource intensive, what is the best way to implement this with bull.js and if it is even possible.

![Screenshot 2020-05-27 at 6 08 09 PM](https://user-images.githubusercontent.com/10924368/83020744-8eabcc80-a046-11ea-9c56-5d7b379f12fa.png)

PS - Using Nest js, solution in that would be great otherwise, node js will do.

**Comment by manast** [comment]
There is nothing fundamentally wrong in scaling queues horizontally as in your diagram, however it may be complicated to handle from admin point of view if you have an unbound number of queues. It will also be difficult to visualize with current UIs. Finally it may be problematic if "n" becomes too large since you may run out of connections to redis.

**Comment by atullal** [comment]
Thanks for the reply, I plan to create queues on demand and destroy queue when it is drained of jobs. Having an overlord queue to manage creation and deletion of queue as well as managing the number of queues "n" could be a solution here. This type of implementation should be okay with bull, right?

**Comment by EmanuelAguilar74** [comment]
> Thanks for the reply, I plan to create queues on demand and destroy queue when it is drained of jobs. Having an overlord queue to manage creation and deletion of queues as well as managing the number of queues "n" could be a solution here. This type of implementation should be okay with bull, right?
can you share your insights about your implementation? how scalable is this?

**Comment by n1ru4l** [comment]
@stale no

**Comment by manast** [comment]
Currently I do not have a solution for these kind of requirements in plain javascript, as a Redis module I have one on the writeboard, but I know modules are problematic since not everybody is able to use them.
