### ISSUE TITLE
What's the proper way to get job's results using micro services ?

### ISSUE THREAD

**Issue by sundowndev** [OptimalBits/bull#1754]
Hi, I've been working on a implementation of Bull in one of my projects and I was wondering, when the worker service lives on another machine than the API in a micro service architecture, what's the proper way to get job's result from the API ?

Is it the event pattern ? How does it work when scaling ?
Is it HTTP call from the worker to API ?

Thanks

**Comment by EmanuelAguilar74** [comment]
the API initialize the worker or something? 
your api is awaiting for a response? if so maybe you dont need a queue, you should try this https://threads.js.org/

**Comment by sundowndev** [comment]
@EmanuelAguilar74 Yes the API initialize the worker's API in order to add jobs to queues. Queues are defined by the worker itself. So the API is the producer, the worker service is the consumer. But sometimes the API needs the job's response in order to perform some actions, and the worker does not lives in the same repository, it doesn't have access to the DB ORM.

- Is it recommended to put the worker code base in the same repository of the API ?
- What's the recommended way to send job response to the API ?

I don't think threads.js follows my needs but thanks.

**Comment by manast** [comment]
@sundowndev the most robust way is to use another queue for passing back the results to the api, call it for example "response" queue. The api can define workers listening to this response queue and act accordingly.
https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#returning-job-completions
