### ISSUE TITLE
Creating queues dynamically feels kinda wrong...

### ISSUE THREAD

**Issue by EmanuelAguilar74** [OptimalBits/bull#1756]
## Description
Im trying to implement a queue to handle sending of messages to whatsapp, so i need to create this queues dinamically so i cant await for the whatsapp status callback before sending the next message. Also this need to work concurrently...

I've used this code to reuses the connections.

![image](https://user-images.githubusercontent.com/11521955/83319874-7c818800-a218-11ea-8f46-2762ceb57a45.png)

The problem is that every new queue append new listeners so i decided to remove them every time.
Is this the right way? o there is a parameter for this?

**Comment by fjeddy** [comment]
Why do you need to make new dynamic queues?

**Comment by EmanuelAguilar74** [comment]
> Why do you need to make new dynamic queues?

If $phone1 sends 3 consecutives messages, its ok to send one and  await for its status callback, for then send the next one.
But $phone2 or $phone3 should not wait...
The real problem here is that the whatsapp brokers dont have a queue of messages and messages are sent simultaneously, so they arrive in the wrong order.
