### ISSUE TITLE
How to lock queue between several node.js processes?

### ISSUE THREAD

**Issue by yury-kozlov** [OptimalBits/bull#1759]
Hi, I'm new here, and I'm trying to figure out how to set up bull, so that a repeated job of the same queue can be executed only on one instance of nodejs application at a time. Meaning if I run 2 instances of node.js app, when a job is being handled by app1, the second app will not start processing a new job from the same queue.
1) Is it possible to define some kind of distributed lock between multiple instances for a given queue ?
2) What would be the setup in this case ?

I tried to use "concurrency" parameter of 1, but when I stopped in debugger in app1, I see that app2 actually outputs about handling the job:
```
  const queue = new Bull('my-scheduled-task');
  const job = await queue.add('my-job', { foo: 'bar' }, { repeat: { every: 10000 },
      removeOnComplete: true });
  queue.process('my-job', 1, async (job) => {
    // debugger here
    console.log('handling...');
    return Promise.resolve();
  });
```

Thanks!

**Comment by manast** [comment]
If you have more than one worker then they can run jobs in parallel. If it is a repeatable job, the same instance of the job will only run in parallel if the time it takes to process the job is longer than the repetion interval.

**Comment by yury-kozlov** [comment]
> If it is a repeatable job, the same instance of the job will only run in parallel if the time it takes to process the job is longer than the repetion interval

Do I understand right that if repetition is 10 sec, and job is being handled on app1 for say 12 sec (and haven't yet completed), then app2 will start this job in parallel ?
Is it possible to prevent this ? 
I only need one job at the same time, even if it takes longer to process it.

**Comment by manast** [comment]
then you need to implement a separate mechanism on top of bull.
