### ISSUE TITLE
Not all jobs go into queue

### ISSUE THREAD

**Issue by DmitryOlkhovoi** [OptimalBits/bull#1761]
## Description

I add jobs like that 
```
            items.map((item: any) => {
                return this.queue.add(item, {
                    repeat: {
                        every,
                    },
                    removeOnComplete: 100,
                });
            });
```
This results in adding one job with the first one item as data.

If I remove this setting
```
repeat: {
    every,
 },
```
- all jobs are creating

Is it a bug? How I can add several repeatable jobs?

## Bull version
latest

**Comment by manast** [comment]
you can only have 1 repeatable job with a given ```every``` parameter, it is a current limitation in bull.

**Comment by DmitryOlkhovoi** [comment]
@manast within a particular queue? Can I have multiple repeatable jobs in different queues?

**Comment by manast** [comment]
yes
