### ISSUE TITLE
Builtin backoff strategies not explained in documentation

### ISSUE THREAD

**Issue by sundowndev** [OptimalBits/bull#1762]
## Description

Builtin backoff strategies "fixed" and "exponential" are mentioned in the docs but not explained, what those strategies are doing ? Can it be combined with `attempts` option ?

Thanks

**Comment by manast** [comment]
yes attempts can be used with backoff strategies.

**Comment by sundowndev** [comment]
>Builtin backoff strategies "fixed" and "exponential" are mentioned in the docs but not explained, what those strategies are doing ?

**Comment by tnolet** [comment]
Trying to figure out too how backoff's work. They do not seem to do anything.
The code below just does two attempts right after each other. No backoff.
```js
 queue.add({ data }, {
    timeout: 10000,
    attempts: 2,
    removeOnComplete: true,
    removeOnFail: true,
    backoff: {
      type: 'fixed',
      delay: 5000 // ms
    }
  })
```

**Comment by manast** [comment]
Until the documentation is up to date I recommend you to check the tests for reference: https://github.com/taskforcesh/bullmq/blob/master/src/test/test_worker.ts#L1058

**Comment by sundowndev** [comment]
@tnolet I currently use fixed backoff with delay in production and it works well:

 ```
 queue.add({ data }, {
    attempts: 5,
    backoff: {
      type: 'fixed',
      delay: 30000, // 30s
    }
  })
```

5 attempts with 30sec between each try. I still don't know what's the difference between fixed and exponential tho.

**Comment by mythio** [comment]
Suppose your worker throws error, and the job fails, does removeOnFail: false, keep the job in the queue?
I have 
```
queue.add({ data }, {
    removeOnComplete: true,
    removeOnFail: false,
  })
```
It removes the jobs whatsoever.

**Comment by manast** [comment]
@mythio please do not ask unrelated questions in the issues. You have already asked the same thing in three different places.
