### ISSUE TITLE
Express middleware function to queue a whole API request

### ISSUE THREAD

**Issue by jellohouse** [OptimalBits/bull#1765]
I got very close to an elegant solution like this:

```
var myQ = new Queue('myQ');
myQ.on('global:completed', function(job, jobResult) {
  console.log('done job:', job);
});

app.post('/api/v1/test', function(req, res, next) {
    myQ.process(function(job, done){
      req.myQjobDone = done;
      next();
    });
    myQ.add({anything: 'does not really matter'});
  }), 
  ....,
  someRandom.middleware(), 
  ....,
  function(req, res) {
    // and here inside my final function I could simply call anywhere:
    req.myQjobDone();
    // this would then allow the next request/job in the queue to go through
  });
}
```

However this only worked when I hit this endpoint once, if I hit it again I got an error from bull saying that you cannot redefine the process... how unfortunate eh!

This would really be a nice way to queue entire requests to a rest API.

Anyone has or sees a solution for something like this?

**Comment by jellohouse** [comment]
You can't redefine the q process but you can redefine the q 'on' progress.
So I solved by doing a something like this:
```
let globalDoneCB = new Map();
var myQ = new Queue('myQ');
myQ.on('global:completed', function(job, jobResult) {
  console.log('done job:', job);
  globalDoneCB.delete(jobID);
});
myQ.process(function(job, done){
   globalDoneCB.set(job.id, done);
   job.progress(1);
});
app.post('/api/v1/test', function(req, res, next) {
  myQ.add({anything: 'does not really matter'});
  myQ.on('progress', function(job, progress){
    if (progress == 1) {
      req.myQjobDone = globalDoneCB.get(job.id);
      next();
    }
  });
},
...,
finalFunction);
```

**Comment by manast** [comment]
registering a listener for every call is going to end bad...

**Comment by jellohouse** [comment]
Yes you are absolutely right! 
I put a console log inside the on('progress') event, and every time I hit that endpoint the there's one more log than the previous time..
So I will move things around for now and implement my queue later in the code.

The reason I want it right from the start is that I'm using the multer middleware for uploading files, and I would like my queue to start before multer even starts saving the file to disk.

**Comment by bitrecipe** [comment]
@jellohouse rather than saving whole request object inside the queue, you can save request in an object as key value pair such as { randomJobId: requestObject },
I dont know whether it is usefull for you, below sample snippet
```
let someQueue = new Queue('someQueue');

let reqRes = {};

someQueue.on('global:completed', function(job, jobResult) {
    console.log('done job:', job);
});

someQueue.process(function(job, done){
    console.log("process job");
    let { req, res } = reqRes[job.id];
    res.send("done"); // dont forget to send response back
    delete reqRes[job.id]; // delete it after the use
    done();
});

app.post('/api/v1/test', function(req, res) {
    someQueue.add({anything: 'does not really matter'}).then((job) => {
        reqRes[job.id] = { req, res };
    });            
});
```
remeber reqRes is in the current process memory, so don't let it grow indefinitely it will eat up your memory
