### ISSUE TITLE
Running Bull on Production environment

### ISSUE THREAD

**Issue by SEdilson** [OptimalBits/bull#1767]
I'm trying to run bull at AWS Elastic Beanstalk but I'm getting the following error: 

```
Command execution completed on all instances. Summary: [Successful: 0, TimedOut: 1]
```

Here's the code I used to run bull:

```
container_commands:		
   02-build:		
     command: |		
       cd /var/app/current		
       sudo npm run queue		
     leader_only: false		
     ignoreErrors: false
```

When I run at dev environment it works but once I try to run at production doesn't work. What can I do to make it work on production environment?

**Comment by manast** [comment]
Please refer to beanstalk documentation since this issue is not bull related.
