### ISSUE TITLE
Replace ioredis with redis package

### ISSUE THREAD

**Issue by SokratisVidros** [OptimalBits/bull#1773]
## Description

Has any tried to use redis package instead of ioredis with Bull.js? I am facing some weird connectivity issues between Redis and our K8s apps so I thought I could give it a try.

Thanks.

**Comment by manast** [comment]
redis was replaced by ioredis some years ago since it was better maintained. If you can find a connectivity issue depending on ioredis I am quite positive the team at ioredis will look into it.

**Comment by SokratisVidros** [comment]
Thanks a lot @manast

**Comment by BatuhanW** [comment]
We have connectivity issue trying to use Elasticache with encryption in-transit.

I saw many similar issues from different libraries, none of them seems to solved my problem. It just timeouts while trying to connect. I triple checked sg ids, and inside the k8s pod, we have tcp connection to redis, but while startin the application it just timeouts.

https://github.com/luin/ioredis/issues/1042#issuecomment-575642093
https://github.com/luin/ioredis/issues/837#issuecomment-484523707
https://github.com/OptimalBits/bull/issues/2217
https://github.com/luin/ioredis/issues/664#issuecomment-410324534
