### ISSUE TITLE
Detach .process listener

### ISSUE THREAD

**Issue by mythio** [OptimalBits/bull#1776]
1. How to detach `Queue.process()` listener? I want to process n jobs, and then detach. Once I trigger this operation, the operation should resume. However due to lack of (unupdated) docs, this has been really hard to figure out.
2. What happened to Queue.getNextJob()??

**Comment by gabegorelick** [comment]
> How to detach Queue.process() listener?

If there's only 1 processor on this queue object, or you want to stop all of them, then `queue.pause(true)` should work. The `isLocal` flag tells bull to only stop this worker, but leave any others running. See https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queuepause.

I believe stopping a specific processor function is a feature request, but I can't find the issue now.

> What happened to Queue.getNextJob()??

Do you mean https://github.com/OptimalBits/bull/issues/1152?

**Comment by mythio** [comment]
Yes that helped! Thanks! And yes i mean #1152. I believe there are many more functions missing in the docs, I hope they are updated soon, Thanks again!
