### ISSUE TITLE
Can't set port when using redis.

### ISSUE THREAD

**Issue by dattp** [OptimalBits/bull#1777]
#### I cannot set port when using redis.
* code
`
const userQueue = new Queue(CONSTANT.QUEUE_NHA_TRUONG, {
  redis: {
    host: localhost,
    port: 10779
  }
})
`

* I want to set the `port = 10779` but when I start the server I get the error `Error: Redis connection to localhost: 6379 failed`

* Why does the log say that port `6379` is not port `10779` as I have configured!
* thankyou!

**Comment by manast** [comment]
I am not sure what you are doing but specifying the port works. In your code above your specification of localhost is not valid syntax.
