### ISSUE TITLE
Adding job from another language (php,perl,Ruby etc)

### ISSUE THREAD

**Issue by amit777** [OptimalBits/bull#1783]
We rolled our own simple queue system with Redis and have components in different languages that can push jobs into the queue. Is there a documented or recommended way to do this with bull?

**Comment by manast** [comment]
The easiest way right now is to pick the "addJob" lua script and try to use it from the other languages...

**Comment by suchakraborty** [comment]
I was using express and bull-master - so my solution was to expose an API by adding an endpoint in each queue `/<queue>/add` that takes the JSON from POST body as job data to that queue. So as long as I can form a JSON and send an HTTP POST - I can add a job.

**Comment by gabegorelick** [comment]
This comes up a lot:
https://github.com/OptimalBits/bull/issues/323
https://github.com/OptimalBits/bull/issues/573
https://github.com/OptimalBits/bull/issues/918
https://github.com/OptimalBits/bull/issues/1040
https://github.com/OptimalBits/bull/issues/1261
https://github.com/OptimalBits/bull/issues/1373

**Comment by manast** [comment]
I have almost completed a redis module that implements Bull/BullMQ which besides being much better it will of course work from any languange that has a redis client available. Stay tuned!

**Comment by dphaener** [comment]
Anyone here still needing to push jobs to Bull from another language, check this out: https://github.com/bitfinexcom/caron. I have this running next to my Node service and am easily able to push items onto a Redis list, which is then popped from Redis by caron and then enqueued for the Bull workers.

**Comment by RodolfoSilva** [comment]
pump

**Comment by hellojukay** [comment]
Any news on this?

**Comment by manast** [comment]
@hellojukay from which language would you like to interoperate with Bull?

**Comment by hellojukay** [comment]
@manast I want to consume job  from golang.

**Comment by manast** [comment]
We are planing something for early next year, but short-term consuming jobs from a different language is quite hard. You would need to port some of the code in Bull that handles jobs consumptions, easiest pattern would be consuming manually like this: https://docs.bullmq.io/patterns/manually-fetching-jobs

**Comment by manast** [comment]
Btw, development for this feature will happen here: https://github.com/taskforcesh/bullmq-redis
