### ISSUE TITLE
Retrying active jobs after power failure

### ISSUE THREAD

**Issue by meammeiam** [OptimalBits/bull#1784]
## Description

I am using bullmq.

If a job is being processed and there is a power failure or if the worker process is shutdown while processing a job, when power is restored or the worker process is restarted then the job gets stuck as active. It never fails if there is a power failure and is never retried when power is restored. I tried using the timeout option, but that didn't fail the job after power was restored. Is there a setting I am missing or is there some other way to restart a job still active after a power failure?

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

Add a job to a queue and process it using setTimeout and while in the setTimeout promise turn the power off or stop the worker process and then restore power or restart the worker process:

//job options
jobOpts = {
            "attempts": 2,
            "timeout": 10 * 1000,
            "delay": 0,
            "backoff": {
                "type": "exponential",
                "delay": 100
            }
        }

//function to process job
processJob: function(job) {
        return new Promise(function (resolve, reject) {
            //test await
            setTimeout(() => {
                try {
                    return resolve();
                } catch(err) {
                    return reject (err);
                };
            }, 5000)
        });
    },

//worker used to process job
const worker = new bullmq.Worker(key, async job => {
    if (job.name === 'my-job') {
        console.log('processing: ' + job.name);
        return processJob(job);
    }
}, { connection });

## Bull version
"bullmq": "1.8.13"

**Comment by manast** [comment]
@C0rellana there are no known issues with stalled jobs in the described scenario. If you are able to write a reproducible test case please post a new issue and we will look into it.
