### ISSUE TITLE
Retry a failed job until the job completes successfully or number of attempts made has exceeded.

### ISSUE THREAD

**Issue by amitpareek49** [OptimalBits/bull#1785]
#939  Description
I am trying to use run a job and insert it to the queue. In certain cases if the job fails, then is it possible to retry immediately (before processing the new messages in the queue) until the job completes successfully? 

When i try to retry a failed job, the job runs but if there are messages added to the queue they are processed before the current job is complete. I am not sure if there is an existing feature for this kind of use case. If yes, then it would be great if you could provide link of the documentation/ articles.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

const queue = new Queue(<queuename>, 'redis://localhost:6379');
queue.add(1, { jobId: 1, toFail: true });
queue.add(2, { jobId: 2 });
queue.add(3, { jobId: 3 });

queue.process(async job => {
    let count = 0;
    return new Promise((resolve, reject) => {
        let inter = setInterval(() => {
            count++;
            if(count > 5) {
                clearInterval(inter);
                if(job.opts.toFail && job.attemptsMade <= 2) {
                    reject('Failed')
                } else {
                    resolve('Finished');
                }
            }
        }, 1000);
    });
});

queue.on('completed', (job, result) => {
    console.log(`Completed Job ${job.id} done. Time is: ${new Date().toGMTString()}. Result is ${result}`)
});

queue.on('failed', (job, result) => {
    console.log(`Failed Job ${job.id} done. Time is: ${new Date().toGMTString()}. Result is ${result}`);
    //retry the job again
   job.retry();
});
## Bull version
3.14.0

## Additional information
The feature that I am looking for is that instead of adding the failed job back to end of the queue. Is it possible to add the job back to the front of the queue.

**Comment by manast** [comment]
It is adding it to the front of the queue, however the retry is not atomical so some job may lurk in before it manages to reprocess the failed job.

**Comment by amitpareek49** [comment]
Thanks @manast for your response. Do you suggest any alternative solution for handling the above use case?
