### ISSUE TITLE
Neither `startDate` nor `delay` works for starting a repeatable job sometime in the future

### ISSUE THREAD

**Issue by dbettini** [OptimalBits/bull#1786]
## Description

The idea is to start a repeatable job sometime in the future, defined by a provided date. After that moment, the job should execute and keep repeating according to the provided cron.

## Minimal, Working Test code to reproduce the issue.
I have tried two approaches, using `startDate` and `delay`:
```
const cron = '*/1 * * * *'; // Repeat each minute
const startDate = new Date(Date.now() + 3 * 60 * 1000); // 3 minutes from now

// 1
queue.add({ job: 'data' }, { repeat:  { cron, startDate }});
//2
queue.add({ job: 'data' }, { repeat:  { cron }, delay: startDate - Date.now() });
```
In both cases, the job runs immediately at the start of the next minute and repeats each minute afterwards. `startDate` and `delay` are both completely ignored.

## Bull version
bull@3.15.0

## Additional information
I know this can be solved by using `setTimeout`, but then the job is not actually scheduled, it is not in Redis or gettable using `getRepeatableRuns`. Is there another way to do this which I'm not seeing?

**Comment by manast** [comment]
If you test that exact code in a brand new queue, does it still not work? Because I am seeing this behaviour on existing queues, where startDate was already set to some value, and since you currently cannot update a given repeatable job options it will not work as you expect.

**Comment by dbettini** [comment]
Hm. I tried manually deleting all bull records bound to this queue from Redis, and it does indeed work correctly. However, I don't understand why it didn't work before, because before I ran the code shown above I always did:
```
const jobs = await queue.getRepeatableJobs();
await jobs.map(j=>queue.removeRepeatableByKey(j.key))
```
Also, I tried ``await jobs.map(j=>j.remove())`, but for some reason it says `j.remove is not a function`, although it is documented [here](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#jobremove), and looking at `[getRepeatableJobs](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queuegetrepeatablejobs)` it does say that it returns an array of Job instances, but that may be a documentation issue.

**Comment by manast** [comment]
yes, the text is correct, but the signature is incorrect, it does not return jobs, it returns the configurations.

**Comment by manast** [comment]
I am aware it is a bit confusing that the startDate does not get updated when you add the exact same repeatable job, this happens because if the repeatable job already exists then it is not replaced by the new one just ignored, not sure how to solve this without some large changes in the design.

**Comment by dbettini** [comment]
I am aware of that, but if I use `removeRepeatableByKey` and remove all repeatable jobs, shouldn't adding it with a new `startDate` to the queue after that work as expected?

**Comment by manast** [comment]
yes, that should work.

**Comment by dbettini** [comment]
It does not. After removing everything from Redis manually and starting the script, everything works fine. However, if a job was scheduled, restarting the script (which clears all repeatable jobs before adding) results in jobs firing immediately, as if the previous job was not removed. Looking at their ids, here's what I found by logging all job lists at startup, after using `removeRepeatableByKey` on all repeatable jobs, after `add`, and in `process`:
1. When everything's empty, all lists are empty
2. After adding a job with `startDate` of 3 minutes in the future, it appears as repeatable and delayed, where `repeatable.next = prefix + job.id`. 
3. In the process function, that job is listed as active, and now a new job is created and delayed. Let's call it **firstJob**. Now, `repeatable.next = prefix + firstJob.id`
After this, I kill the server, start it up again, and:
4. On startup, we have the state from point 3
5. After the script starts, it calls `await Promise.all(jobs.map(j=>queue.removeRepeatableByKey(j.key)));`. This empties repeatable, but the delayed list still contains our job. I would expect it was removed, but even if it's not, I thought this should just execute once and that's it, since repeatable list is empty.
6. I add the job, again using a `startDate` of 3 minutes in the future. Let's call this job **secondJob**. Now, we have one entry in repeatable, for secondJob, but two in delayed, one for firstJob and secondJob. So, our only repeatable entry is mapped to secondJob's id `repeatable.next = prefix + secondJob.id`
7. Now, firstJob, that has no entry in repeatable, is processed. **This is where unexpected things occur**. 
- firstJob is now found in the active list, which is expected. However, **a new entry (thirdJob) also exists in delayed list, even though there was no repeatable job for firstJob, since it was removed.**
- the existing repeatable job, whose next was pointing to the secondJob, **now points to thirdJob** `repeatable.next = prefix + thirdJob.id`

**Comment by manast** [comment]
Regarding: 
> After the script starts, it calls await Promise.all(jobs.map(j=>queue.removeRepeatableByKey(j.key)));. This empties repeatable, but the delayed list still contains our job. I would expect it was removed, but even if it's not, I thought this should just execute once and that's it, since repeatable list is empty.

I recall having fixed an issue where the jobs where not removed from the delay set, I will look into it again.

**Comment by oavanruiten** [comment]
If possible, try using removeRepeatable.

removeRepeatableByKey does not delete delayed job at the moment as mentioned here:
https://github.com/OptimalBits/bull/issues/1277#issuecomment-534939664

Maybe it should, as the difference in behaviour is not expected...

**Comment by dbettini** [comment]
@oavanruiten thanks! I definitely expected those two methods to have the same behavior, so I didn't even test it. It does seem like it should be the case. I hope that, if authors decide to do it for consistency, they keep `removeRepeatable` behavior. @manast any thoughts on that?
Also, looking at [removeRepeatable](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueremoverepeatable), seems repeatOpts need to be exactly the same as when creating the job. But I don't store startDate anywhere, so it seems I'll have to first use getRepeatableJobs to get all jobs, and then maybe find it by name there, which is really not the best way to do it...

**Comment by oavanruiten** [comment]
@dbettini You are right about the repeatOpts. I store these opts to remove the repeatable job later on. Looping over the getRepeatableJobs should work, but is indeed far from ideal.

**Comment by kodeine** [comment]
is there any update on this? I am setting up a job id of my own but it seems i cant remove it with the job id.

Also, `startDate` and `delay` either can be used right? I want to start the cron from future date.

**Comment by manast** [comment]
@kodeine the way to currently remove a repeatable job is using these two methods: removeRepeatable and removeRepeatableByKey: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueremoverepeatable
Regarding ```startDate``` it should work as expected.  Delay cannot be combined currently with repeatable jobs though.

**Comment by kodeine** [comment]
@manast so the initial run will be after start date as well right? I want the initial execution to be on the start date.

**Comment by manast** [comment]
@kodeine that should work yes.

**Comment by andreaspapazois** [comment]
So should are the following the following `repeatOptions`:
```
repeat: { every: FOUR_MIN_IN_MILLIS, startDate: Date.now() + ONE_MIN_IN_MILLIS }
```
...enough to do the job, i.e. starting after 1 minute repeat the job every 4 minutes?
