### ISSUE TITLE
Uncaught TypeError: uuid is not a function

### ISSUE THREAD

**Issue by dienhoa** [OptimalBits/bull#1787]
###  Description
I got error **Uncaught TypeError: uuid is not a function** when create a new Bull. I found in bull/lib/queue.js import and use uuid as below

```
const uuid = require('uuid');
this.token = uuid();
```
Which I think it is a deprecated version of uuid.

In the current documentation of uuid, I found we should include the version when calling. https://github.com/uuidjs/uuid . For example: 

```
import { v4 as uuidv4 } from 'uuid';
uuidv4(); // ⇨ '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'
```

This issue is reported elsewhere you can found it here: https://github.com/alexa/skill-sample-nodejs-smarthome-switch/issues/9

**Comment by joebowbeer** [comment]
Bull depends on uuid@3.4.0

**Comment by manast** [comment]
I am not sure I understand what is the issue here. You are importing uuid in your own application and get an error, how is that related to bull?

**Comment by dienhoa** [comment]
I think I misunderstand how the dependencies in TypeScript works. I think each dependency control their own dependency. I will try to downgrade uuid and check if my code works. Thanks for your help :D

**Comment by dienhoa** [comment]
Sorry for bothering, I downgrade uuid in my own application that fix the problem
