### ISSUE TITLE
How to work separate process path with TS file extension?

### ISSUE THREAD

**Issue by igortupini** [OptimalBits/bull#1793]
## Description
When I set a path like `../jobs/foo.ts` when working with **ts-node** everything works just fine.
But after compiling with TSC the TS extension is not valid anymore.

I could make conditional paths for production build and development but that doesn't seem appropriate.
I did a workaround exporting the `__filename` variable from the job file and using it as a path on the process.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
```javascript
queue.process(../jobs/foo.ts)
```
Workaround:

job file
```javascript
export default (job: Job) => {
  return Promise.resolve('foobar')
}

export const fooPath= __filename
```
queue file
```javascript
import { fooPath } from '../jobs/foo'

queue.process(fooPath)
```
## Bull version
3.15.0

**Comment by AntonioNtV** [comment]
Trying using babel to compile the code.
It worked for me.

**Comment by manast** [comment]
As there are workarounds and I feel this problem falls outside of Bull scope I will close this issue.
