### ISSUE TITLE
Jobs getting stuck under small load

### ISSUE THREAD

**Issue by evanhuang8** [OptimalBits/bull#180]
I have been very interested in replacing `kue` with `bull` and I have been doing some testing, however, I keep running into the problem of jobs getting stuck.

### Scripts

So my simply setup has two scripts, one is `scheduler` and the other one is `worker`

`scheduler`:

```coffeescript
#!/usr/bin/env coffee

fs = require 'fs'
bull = require 'bull'
matador = require 'bull-ui/app'
co = require 'co'
Q = require 'q'

credentials = JSON.parse fs.readFileSync './credentials.json', 'utf8'

redisHost = credentials.redisHost
redisPort = credentials.redisPort
redisPass = credentials.redisPass
redisDBNumber = credentials.redisDBNumber

queue = bull 'test', redisPort, redisHost

app = matador
  redis:
    host: redisHost
    port: redisPort
    password: redisPass

sleep = (duration) ->
  deferred = Q.defer()
  setTimeout ->
    deferred.resolve()
    return
  , duration
  return deferred.promise

co ->

  for i in [0...100]
    job = yield queue.add {}, 
      delay: 10 * 1000
    console.log "Job #{job.jobId} scheduled"

  yield sleep 1000

  for i in [0...10]
    for j in [0...10]
      job = yield queue.add {}, 
        delay: 8 * 1000
      console.log "Job #{job.jobId} scheduled"
    yield sleep 1000

  return

.catch (err) ->

  console.log err

  return
```

Using a bit of ES6 generator logic here, so bare with me.

`worker`:

```coffeescript
#!/usr/bin/env coffee

fs = require 'fs'
bull = require 'bull'
co = require 'co'
Q = require 'q'

credentials = JSON.parse fs.readFileSync './credentials.json', 'utf8'

redisHost = credentials.redisHost
redisPort = credentials.redisPort
redisPass = credentials.redisPass
redisDBNumber = credentials.redisDBNumber

queue = bull 'test', redisPort, redisHost

queue.process (job, done) ->
  console.log "Job #{job.jobId} is processed!"
  done()
  return

queue.on 'error', (err) ->
  console.log err
  return
```

### Test runs

I am using iojs v2.5.0, tested with both redis 2.8.19 and 3.0.3. I flush redis before every run.

So when I run the scheduler first, and wait till all the jobs are scheduled, and then run the worker, then all jobs will go to completion.

If I remove the delay settings from the jobs, then everything seems fine - all jobs are processed.

When I run the worker and the scheduler at the same time - in other words, let the worker process as the scheduler goes, only a fraction of the jobs will be processed (ranging between 5 - 50 jobs out of the 200 jobs scheduled). Once the processing stops, no matter how long I wait, the jobs are stuck in the delayed state.

I suspect there is something going on with how the delayed jobs are setup, any insights?

**Comment by albertjan** [comment]
Could you paste the compiled scripts in a gist? My brain doesn't compute coffeescript :smile:. This will also give me a change to try it out myself. This sounds pretty serious.

**Comment by evanhuang8** [comment]
Yep, here you go:

https://gist.github.com/evanhuang8/e85f76e486eaeefc9e87

On a side note, is the option to use a different db number on redis going to be supported any time soon?

**Comment by albertjan** [comment]
you can already. just specify an option hash as a second argument like: 

```js
new Queue('bananas', {
  host: 'bla',
  port: 6379,
  DB: 1
});
```

**Comment by albertjan** [comment]
they show up as stuck on matador?

**Comment by evanhuang8** [comment]
Yep. I also checked the queue itself using `redis-commander` and they are stuck in the `delayed` list

**Comment by albertjan** [comment]
confirmed

**Comment by albertjan** [comment]
Ok somehow because the jobs are so close together the `setTimeout` that triggers the next run is not getting called. If you add this:

```js
  setInterval(function() {
    queue.client.publishAsync(queue.toKey('delayed'), Date.now() - 1000);
  }, 100);
```
is should complete eventually

**Comment by albertjan** [comment]
I will try and look for a fix tomorrow. @manast do you have any insights?

**Comment by manast** [comment]
I agree it is a serious issue. But what I do not understand is how can the jobs end on the delayed set if they are normal non-delayed jobs? they should just stay in the wait list until its their turn to be processed. Seems a straightforward case, I have to debug it, but its too late now...

**Comment by evanhuang8** [comment]
@manast sorry I think I compiled the version which I tested with non-delay jobs, see the original post which uses delayed jobs

**Comment by albertjan** [comment]
No it only happens with jobs with a delay. The gist doesn't include the delay.

**Comment by albertjan** [comment]
Here's a gist sans fancyness @manast :smile: https://gist.github.com/albertjan/79bba680f624980c8f0c

**Comment by manast** [comment]
seems like the only way delay jobs can get stuck is if the delayTimer does not fire anymore, but I cannot see in the code at least how that could happen. Maybe if nextDelayedJob would be very large, but seems unlikely to me...

**Comment by albertjan** [comment]
Ok I've fiddled with it a little more and it __only__ happens when the worker and scheduler are on different processes.

**Comment by evanhuang8** [comment]
This is super weird - something to do with the redis commands?

**Comment by manast** [comment]
@albertjan how do you easily test the use case using different processes?

**Comment by albertjan** [comment]
I just tested it and it appears to work :smile: 

to test:

```sh
git clone git@gist.github.com:79bba680f624980c8f0c.git
npm install
node worker.js & node scheduler.js 
```

**Comment by evanhuang8** [comment]
Yep just tried and it works for me too.

**Comment by evanhuang8** [comment]
When will the fix be published on `npm`?

**Comment by btmdave** [comment]
Would this to be related to non-delayed jobs also that are queued very quickly? In come instances I'm noticing that some queued jobs when done quickly stay queued and aren't processed until the server processing jobs is restarted.

**Comment by evanhuang8** [comment]
At a glance I don't think non-delayed jobs would be affected by this issue, since they are directly pushed into the `wait` list, and then the processing function does a `brpushlpop` on the list, which should be atomic.

Any chance you can reproduce the problem?

**Comment by btmdave** [comment]
Thanks, trying to reproduce now, if it happens I'll dig into redis and see what we have

**Comment by manast** [comment]
I think that the only way a job can get stuck is if something unexpected happens in the active list. When a queue starts it always checks if there are stuck jobs on the active list, and process them if they are not locked.

**Comment by evanhuang8** [comment]
This issue from `kue` maybe related: https://github.com/Automattic/kue/issues/514]

**Comment by manast** [comment]
not really since the design of Kue is quite different from bull, just the API is similar.

**Comment by btmdave** [comment]
I haven't been able to reproduce this, this was probably a fluke and possibly not even related to bull.  If it happens again, i'll investigate further.
