### ISSUE TITLE
queue.empty() doesn't seem to work

### ISSUE THREAD

**Issue by duxiaobu** [OptimalBits/bull#1805]
I define this way, but the queue is not cleared. These tasks still exist in Reids, which leads to the unsuccessful addition of subsequent repeated tasks sometimes. I don't know if there is any problem with the code. Please help anyone who knows to answer it. Thank you very much.
This is my code:

```ts
@Module({
  imports: [QueueModule.forRoot(QueueName.UserPortrait, options)],
  providers: [UserPortraitProcessor]
})
export class UserPortraitModule {
  constructor(@InjectQueue(QueueName.UserPortrait) private readonly queue: Queue) {
    console.log("----------------->init start");
    this.queue
      .empty()
      .then(() => this.queue.add(null, { repeat: { cron: "*/5 * * * *" } }))
      .catch(e => logger.error(e));
  }
}
```

**Comment by manast** [comment]
In order to remove repeatable jobs reliably you need to use one of these two methods:
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueremoverepeatable
or https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueremoverepeatablebykey

**Comment by duxiaobu** [comment]
> In order to remove repeatable jobs reliably you need to use one of these two methods:
> https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueremoverepeatable
> or https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueremoverepeatablebykey
Thanks for the answer, but it doesn't seem to work
@Module({
  imports: [QueueModule.forRoot(QueueName.UserPortrait, options)],
  providers: [UserPortraitProcessor]
})
export class UserPortraitModule {
  constructor(@InjectQueue(QueueName.UserPortrait) private readonly queue: Queue) {
    console.log("----------------->init start");
    this.queue
      .removeRepeatable(QueueName.UserPortrait, { cron: "*/5 * * * *" })
      .then(() => this.queue.add(null, { repeat: { cron: "*/5 * * * *" } }))
      .catch(e => logger.error(e));
  }
}

**Comment by duxiaobu** [comment]
queue.clean () this method is useful, but it can only clear tasks in one state. If you want to clear all tasks, you have to call multiple times
