### ISSUE TITLE
What's the difference between queue.process(5, '/path/to/my/processor.js'); and queue.process('/path/to/my/processor.js'); if '/path/to/my/processor.js'  can have only one exported function?

### ISSUE THREAD

**Issue by DemGiran** [OptimalBits/bull#1808]
I just don't understand how concurrency is used in here? I tried to look for examples but unfortunately I couldn't find any examples that leverage sandboxed processes with concurrency

**Comment by DemGiran** [comment]
I just don't understand how concurrency is used in here? I tried to look for examples but unfortunately I couldn't find any examples that leverage sandboxed processes with concurrency

**Comment by DemGiran** [comment]
is this project active?

**Comment by GabrielCastro** [comment]
Hi @DemGiran;

All the examples should be the same if you're using sandboxed processes or not.
In both scenarios the concurrency limit limits the total number of jobs from that queue that may be running at the same time. (With sandboxes that effectively is the number of processes that will be spawned). Either way each queue & job-name pair can only have 1 function.
