### ISSUE TITLE
Is there a way to check whether Queue.add({..., jobId: ...}) added a job, or it was a no-op because if this jobId being there already?

### ISSUE THREAD

**Issue by dko-slapdash** [OptimalBits/bull#1810]
Hi.

I couldn't find a way to figure out if an add() call resulted into a scheduling of the new job, or it was completely skipped since a job with such jobId being in the queue already. Can it be returned or checked somehow?

One way would be to call Queue.getJob() prior to .add(), but then it would be race-prone still.

**Comment by manast** [comment]
If it is ignored no waiting event will be emitted but I am not sure that will help you...

**Comment by dko-slapdash** [comment]
Yep, it will unlikely help - one can't wait on a "never emitted event". So there is no robust way then, right?
