### ISSUE TITLE
Set failedReason on a failed job? (Question)

### ISSUE THREAD

**Issue by BE-CH** [OptimalBits/bull#1811]
## Description
Is it possible to set the failed reason, when a job fails? I am using bull-board (0.9.0) for monitoring.

I tried doing the following, but it doesn't seem to work. At least its not updated on the bull-boad.
```
referralQueue.on('failed', function(job, orderError){

  job.failedReason = "This is a test";

});
```

## Bull version
3.16.0

**Comment by manast** [comment]
The failed reason is set when the job fails in the processor:

```ts
referralQueue.process( async () => {
   throw new Error("This will be the failed reason");
})
```
