### ISSUE TITLE
Question regarding guardInterval documentation

### ISSUE THREAD

**Issue by oavanruiten** [OptimalBits/bull#1812]
Hi,

The documentation states that "when running multiple concurrent workers with delayed tasks, the default value of guardInterval will cause spikes on network bandwidth, cpu usage and memory usage. Each concurrent worker will run the delayed job watchdog."

Does concurrent workers mean different machines that create a Queue object or are we talking about the concurrency set when using the queue.process function (sandboxed processes) as well? 

For example: 
I have 3 workers running on different machines with each a queue concurrency value of 12.

Do I have to set my guardInterval to 5000 * 3 or 5000 * 3 * 12?

**Comment by manast** [comment]
No, it is per worker not per concurrency setting. So with 3 workers the guard interval will just be run 3 times during the specified guardInterval value.

**Comment by oavanruiten** [comment]
Alright, thanks @manast
