### ISSUE TITLE
Pause-> Retry failed-> Resume leads to retried waiting jobs getting stuck.

### ISSUE THREAD

**Issue by suchakraborty** [OptimalBits/bull#1813]
I shall add details later, but these are the steps that reproduced the issue twice:

I had a queue that was processing 2 jobs at a time. There were, say 5 failed jobs and 10 jobs in 'Waiting' state.  
1. Pause the queue and wait for currently processing jobs to complete.
Result:  10 jobs go from 'Waiting' to 'Paused' state.
2. Retry failed jobs
Result: 2 jobs start being processed, remaining 3 jobs of the 5 go to 'Waiting' state. 10 jobs remain in 'Paused' state.
3. Unpause the queue:
Expected: There should be 10 + 3 = 13 jobs in 'Waiting' state.
Actual: There are 10 jobs in 'Waiting' state. The original 3 retried jobs are in a stuck state. 

I am using Bull Master, that shows a 'Stuck' state if I access the job by ID.
Unfortunately there appears to be no direct way to find these Stuck jobs so I may restart them/reschedule them - which would have been a workaround. :(

## Bull version
3.14.0

**Comment by manast** [comment]
If you could represent this issue as a test case I can look into it right away.
