### ISSUE TITLE
blpop on read replica

### ISSUE THREAD

**Issue by chaffeqa** [OptimalBits/bull#1821]
## Description

Curious if you know if we can point the `blclient` redis connection to a read only redis instance.

Specifically, we use Elasticache with read/write replica (non cluster mode), amazon says that supports pubsub onto the reader, but curious about `blpop` since its not tech a read

**Comment by manast** [comment]
we use https://redis.io/commands/brpoplpush, which requires write, so it will not work.

**Comment by chaffeqa** [comment]
yep read that, sry meant ot update this, thx for the quick response!

FYI to those who may stumble on this, we **are** using the `reader` for the `subscription` client.

in looking into that implementation it looks safe since it only subscribes to pubsub, which IS supported on `reader` EC
