### ISSUE TITLE
delayed jobs are not picked up because of one job processing failed with error: job stalled more than allowable limit; 

### ISSUE THREAD

**Issue by richardyang-dev** [OptimalBits/bull#1822]
Bull version  3.13.0
node version: 14.3.0
I have a few queues. One queue is holding delayed jobs. Each queue is running on its own child process But once a delayed job failed to be processed for unknown reason (got  "job stalled more than allowable limit" message), subsequent delayed jobs added into the queue would all fail with this  "job stalled more than allowable limit" message, even the system is pretty much idling. This can be fixed by restarting the node application.  After the app is restarted, then the jobs added into this queue will be processed until a job fails with this error again. Then all subsequent jobs will be stalled again.

I have this setting in my queue:
myQueue.LOCK_RENEW_TIME = 120 * 1000; //2 mins
my job delay period is also 2 mins.
The jobs in this queue is not cpu intensive and is light weighted. 
However I do notice that the number of  redis connections (aws elasticCache) gradually increases and does not come down which indicates there are some connection leakings. However the total number of connections is still relative low (300). The max allowed on aws side is 60k.

Could you help me understand that why one staled job could cause other jobs added into the same queue later not to be processed and failed. 

The pseudo code in the processor:

module.exports = function (job) {
    logger.info("processing a job with myjob=" + job.id);
    mycontroller.processNewJob(job.data, function (error, result) {
        if (error) {
            logger.error("Error in processing myjob job.jobId=" + job.id, error);
            return Promise.resolve({'job_processed': 'false'});
        } else {
            return Promise.resolve({'job_processed': 'true'});
        }

    });

I am puzzled that based on log, I don't even see this code got invoked as I don't see this log entry from this line:
 logger.info("processing a job with myjob=" + job.id);
But the all jobs in this queue are marked as failed with "job stalled more than allowable limit" regardless.
How could this be possible?

Please help as I am running out of idea. Is there config on this queue I can do? For example LOCK_RENEW_TIME I set is too long, etc?

Thanks in advance.

Richard

**Comment by richardyang-dev** [comment]
I did sometimes got error from bull's code such as:

error uncaughtException: child.off is not a function
TypeError: child.off is not a function
    at ChildProcess.onMessageHandler (/app/node_modules/bull/lib/process/child-pool.js:113:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by manast** [comment]
Firstly I recommend you that you upgrade to latest version of Bull. 
Secondly, I would figure out why the connections are increasing, maybe you are instantiating some Queue everytime a job is processed? or maybe you have dangling workers around.

Delayed jobs are processed like any other job, they are just put back into the main queue list when the time to processed them has come. If you are getting stalled jobs then some worker is actually stalled, either consuming all the CPU or some other problem. 
You can start by creating a small minimal version of your code and then add features until the problem arises, then you know what is causing it.

**Comment by richardyang-dev** [comment]
Thanks for your prompt reply. I think the increased connection is caused by some my own code outside Bull as I also have code to directly connect to the redis (not using Bull) mainly for data caching. I use ioredis and redis from npm. I don't create a new queue for each job. But when processing a job, if I get an error such as network issue,  I do generate a new job with same content into the queue.

 I have the queue's LOCK_RENEW_TIME set as 2 mins but the default lockDuration is 30 seconds. Could this be part of the problem? I am not clear what the LOCK_RENEW_TIME does. Should I use default value for LOCK_RENEW_TIME? How does this value (along with lockDuration) work?

Second, do you know what the error from Bull codebase means:
error uncaughtException: child.off is not a function
TypeError: child.off is not a function
at ChildProcess.onMessageHandler (/app/node_modules/bull/lib/process/child-pool.js:113:15)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at emit (internal/child_process.js:772:12)
at _combinedTickCallback (internal/process/next_tick.js:141:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by manast** [comment]
> The most interesting observation is that a job can be marked as failed even I don't see it is picked up for processing from the queue. How could this possible?
it is not possible, something else is happening.

> I have the queue's LOCK_RENEW_TIME set as 2 mins but the default lockDuration is 30 seconds. Could this be part of the problem? I am not clear what the LOCK_RENEW_TIME does. Should I use default value for LOCK_RENEW_TIME? How does this value (along with lockDuration) work?
You should never need to change this values as they are safe for all well constructed processors. As long as you do not keep nodejs event loop busy for 30 seconds you will be fine. Since you are using sandboxed processors then it is even more irrelevant.
Do you have monitoring data for the CPUs running the queues? are they up to 100%?

> 
> Second, do you know what the error from Bull codebase means:
> error uncaughtException: child.off is not a function
> TypeError: child.off is not a function
> at ChildProcess.onMessageHandler (/app/node_modules/bull/lib/process/child-pool.js:113:15)
> at emitTwo (events.js:126:13)
> at ChildProcess.emit (events.js:214:7)
> at emit (internal/child_process.js:772:12)
> at _combinedTickCallback (internal/process/next_tick.js:141:11)
> at process._tickDomainCallback (internal/process/next_tick.js:218:9)
That should never happen either, I do not understand how it can happen, but please run the latest version of Bull.

**Comment by richardyang-dev** [comment]
I have to make a correction regarding the Bull version I am using.
I think I am using the latest version  "3.18.0" in our testing env where this problem occurs.
In my package.json (I don't have the package-lock file checked in), I have the dependency specified as  "bull": "^3.13.0"
So the npm should have already grabbed the latest minor version 3.18. Is there is any way to print out the Bull's version during queue initialization call?

I looked at the aws container (we use ecs managed fargate containers) cpu profile and see the cpu has never exceeded 10% (most of the time it is on 5%). Memory usage is also very low. The redis cpu and memory usages are also very very low.

Here are a couple of things I want to bring to your attention in case they are relevant to this issue.

First, I call the job processor (sandboxed) like this:
myQueue.process("myJobType", 2, path.join(__dirname, '/myProcessor.js')); 
As you can see I have 2 threads for this job. Should I just use 1? what multiple threads would buy me: better performance? 

Second: myProcessor.js  is written this way:

module.exports = function (job) {
    logger.info("processing a job with Job=" + job.id);
    myController.processNewJob(job.data, function (error, result) {
        if (error) {
            logger.error("Error in processing  job.jobId=" + job.id, error);
            return Promise.resolve({'job_processed': 'false'});
        } else {
            return Promise.resolve({'job_processed': 'true'});
        }


    });

}

Here is my processNewJob function: It does two independent steps:
function processNewJob(jobData, callback){
      action1(jobData, function (er, res) {
        if(er){
            logger.error("action1 failed");
        }
        //---------notice I don't have a callback for action1. action1 could take long time to finish---------------
    });
   action2(jobData, function(e,r){
       callback(e,r); //---------notice I only callback for action2 -----
   })
}

I am wondering if the way processNewJob is written could be the problem.
My intention is that I don't really care about the result of action1. I just invoke it and forget about it. But I do care about action2 and make a callback out of it.
My question is that if I use sandboxed job processor, after action2 is done and makes a callback, will the thread be terminated? If so, what would happen to the action1 which could still be running with this worker thread?

**Comment by richardyang-dev** [comment]
I also noticed from the log that new QUEUE(...) gets called multiple times. I export the queue object and use "require" to import this queue object and I have only one nodejs server running with cluster disabled. I am not sure why the new QUEUE() get called so many times. I don't explicitly close it and that is why I have so many redis connections left over?
Do you know why it gets called so many times? Is it called for each job processed? 
If I could not figure out why it gets called many times, how do I close the connection?

**Comment by manast** [comment]
your code is not correct. You are mixing promise based with callback based code and you are not handling the responses correctly.

**Comment by richardyang-dev** [comment]
Thanks. ok, I will fix the mix of callback and promise.
Could you answer my last question about why new QUEUE() gets called everytime a job is processed? If so, is there way to share the same redis connection? How and where I should call myQueue.close()? If I close it, will it establish a new connection for the next job?

**Comment by manast** [comment]
> Could you answer my last question about why new QUEUE() gets called everytime a job is processed? If so, is there way to share the same redis connection? How and where I should call myQueue.close()? If I close it, will it establish a new connection for the next job?

I do not know what you mean, can you provide some code please?

**Comment by yangju** [comment]
So it turns out that running the processor as in-process instead of sandboxed fixed my issue without any other code change. 
So for now I am just leaving the code running as in process.
However, even with this, I still see the redis connection going up everytime I process a job. The number of connections does not go down until I restart the app server. 
I managed to test this from my localhost and I changed my processor code like this based on your suggestion (not :to use a mix of callback and Promise):

myQueue.process("myNamedQueue", function (job, done) {
        logger.info("processing a job in non-sandbox with job=" + job.id);
        myController.processNewJob(job.data, function (error, result) {
           
            if (error) {
              done(new Error('Error in processing job'));
            } else {
                done();
            }
        });
    });
Do you see problem in this new code? However, the redis connection is not released after the done() is called. I see that the number of connection keeps going up with each job processed. Where should I clean up the connection? Does the myQueue.process() reuses the same connection or always create a new one? This is not very clean in your project documentation. Please clarify.
Thanks.

Richard

**Comment by manast** [comment]
Connections are created when you instantiate a queue, is independent on how many jobs you process. If the connection count is increasing, then you are instantiating new queues without closing them.
Regarding sandboxed processes, you need to return promises, it does not support the "done" callback.

**Comment by richardyang-dev** [comment]
I have updated my code to use promise (not callback) for sandboxed processor. Sandboxed processor, although it seems to work fine, always throws below error for each job processed:
uncaughtException: child.off is not a function
TypeError: child.off is not a function
    at ChildProcess.onMessageHandler (/app/node_modules/bull/lib/process/child-pool.js:113:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

As a result, I switched back to in-process job processor and no issue is found so far. I also replaced npm redis with npm ioredis and connection leaking issue is also solved.

I'd switch back to sandboxed processor as it has many advantages. But at this time, I am not feeling very comfortable. It could still be my own coding issue, but I just don't know if there is a potential bug in the library.

Thanks for your help Manuel. If you find something for above error or other advice, please let me know.

**Comment by sibelius** [comment]
manually fetching jobs would improve this ? https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#manually-fetching-jobs

**Comment by manast** [comment]
Check the ```maxStalledCount``` in the advanced queue settings: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queue
If I were you I would try to find out why the jobs are stalled in the first place, too much CPU usage under long time?

**Comment by richardyang-dev** [comment]
Sorry for the late comments. I am not using sandboxed processors (run the processor in a separate process) anymore, as it just caused many issues, not just the staled job issue (which I still cannot figure out), but also other issues too. Since I ran the job in the main thread, for more than a year in production, I never had any problem with jobs (we have many different types of jobs, including scheduled jobs). But since we deploy our application using aws fargate in containers, we can easily scale in and scale out based on load, so the single thread constraint of node application is not a problem for us, as there would be more node instances standing up if needed.
The other solution would be using node cluster mode which can take advantage of hardware's multiple cpus.
Sorry this does not help the staled job issue. I apologize.
