### ISSUE TITLE
The job get processed multiple times by a single processor registered to the channel

### ISSUE THREAD

**Issue by akashwmp** [OptimalBits/bull#1824]
We got a very weird scenario in which if we publish one job in a queue, it's getting processed multiple times with a gap of few secs between them. The expected behavior should be that once a job has been received by the consumer or subscriber, it should be gone from the channel and should be processed again. We are facing this issue when running a single server instance and got a Redis cloud service.  May be multiple workers of a processor simultaneously process the same job again. 

We are also immediately returning the Promise.resolve() or done () call but still, the issue is persistent.

**Comment by manast** [comment]
you need to provide some code that reproduces the issue so that I can help you figure out the problem.

**Comment by akashwmp** [comment]
@manast Thank you for the quick response. Here is a code snippet of our current implementation : 
**Producer level or pushing a job into the queue**
`
const publishToQueue = (queueName, queueMsg, opt = { attempts: 4, backoff: { type: 'fixed', delay: 100 },removeOnComplete: true,removeOnFail:true }) => {
	let opts = {
		createClient: function () {
			return ioRedisClient;
		}
	};
	let queue = new Queue(queueName, opts);
	queue.add(queueMsg, opt);
};`
Here we have written a common wrapper function for pushing the job in the queue and we are using this particular functionality across different modules.

**Consumer-level or Subscriber**
`class worker {
	createQueue(name) {
		var opts = {
			createClient: function (type) {
				switch (type) {
				case 'client':
					return client;
				case 'subscriber':
					return subscriber;
				default:
					return new Redis(REDIS_URL);
				}
			}
		};
		return new Queue(name, opts);
	}
	subscribe() {
		let ConsumerQueue = this.createQueue('xyz-queue');
		ConsumerQueue.process(QueueProcessor); // path to queue processor written in other file
	}
}`

**QueueProcessor.js**
`module.exports = async (job) => {
	let queueData = job.data;
	// Check if processor queue contains job data
	if(Object.keys(queueData).length) {
		let state = await job.getState();
		if (state === 'completed') {
			return Promise.resolve();
		}
	        processData(queueData); // function to process queue data
		return Promise.resolve();
	} else {
		console.error(queue received bad or empty job data' + job.id);
	}
};`

Here the job is published into the queue for once but getting processed multiple times by the attached processor. We are using the AWS Redis elastic cache. This behavior is persistent if we run one docker instance or multiple docker instances of the worker module. The consumer or subscriber module is independent of the producer and both are connected to the same Redis instance.

**Comment by manast** [comment]
I see many errors in this code:
1) you create a new queue instance everytime to add a job, this leaves dangling connections to redis and its leaking resources.
2) same problem when registering a processor, you should do this once, not everytime sombody calls subscriber.
3) you are not returning the result of ```processData(queueData)``` which I assume is an async function, so you will get jobs that are marked as completed but still processing stuff, this will end in a lot of undesired side effects.

**Comment by akashwmp** [comment]
Hi @manast, Thanks for the valuable feedback. 
As per the 3 points mentioned from your side : 

1. I understood the first point regarding the new instance every time when I'm adding a new job. Maybe I need to take the opts value which I'm passing out of the publish queue function and defined it once into the global reference.

2. While registering the processor, the subscriber method called only once when the container lifts up. It doesn't call every time but still, if one container lifts up it will successfully register all the processor to the queue but when another node instance comes up, it is not able to register its a processor to existing queue and somehow all the job start moving into a waiting state. But if restarts or crash the container, all the waiting or unprocessed jobs get processed.

3.processData(queue data) is an asynchronous function, after passing the job data to this function we immediately return Promise.resolve() or done(). so that we don't' need to hold the job processing for too long and processing should be done on the node js part.  So, should we need to return the result after processing the whole logic as the function has got a long processing time ( approx 3-4 mins )?

4. One more weird behavior which I found was, queues work fine for some time, everything looks fine and working and suddenly queue starts moving into the unprocessed state and the number goes on to 1000-1200 jobs in the unprocessed state like the snapshot below
1279) "bull:queue-xyz:1997"
1280) "bull:queue-xyz:1983"
1281) "bull:queue-xyz:1499"
1282) "bull:queue-xyz:1568"
1283) "bull:queue-xyz:1487"
1284) "bull:queue-xyz:1043"
and so on......this again get resolved if we restart the container instance.

I haven't used the bull queue library extensively, so maybe I'm missing something on my part or doing something wrong but I'm facing this issue very frequently now.

**Comment by manast** [comment]
I do not have time to comment all your points but regarding this: 
> 3.processData(queue data) is an asynchronous function, after passing the job data to this function we immediately return Promise.resolve() or done(). so that we don't' need to hold the job processing for too long and processing should be done on the node js part. So, should we need to return the result after processing the whole logic as the function has got a long processing time ( approx 3-4 mins )?

If you do not return the promise, how are errors handled? If you returned a promise bull will detect the failure, and you will have the opportunity to understand the error and even retry the job if necessary.

Regarding point 4 it is most likely an issue in your current codebase.

**Comment by akashwmp** [comment]
ok @manast, I will look into this again with your valuable inputs and get back to you, if i found some issue in the same.
