### ISSUE TITLE
Queue doesn't throw error if Redis not found

### ISSUE THREAD

**Issue by kamal0808** [OptimalBits/bull#1827]
## Description
When you create a queue with Redis by giving a REDIS URL, it doesn't give out any error if the REDIS URL 
has no valid redis connection. The only way to check if a queue is ready in such a case is by `queue.isReady()` function, which
will give an error because there's no queue to begin with.

It wouldn't be much of an issue if the process would gracefully exit in absence of a valid Redis connection, but it doesn't.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
The below code will never exit if the Redis url has no valid redis connection
```
let queue;
try {
  const bull = require('bull');
  queue = new bull('my-queue', redis://redis-not-present:6379);
}
catch(error) {
  console.log('I should be printed if redis is down', error);
}
finally {
  if(queue)
    await queue.close(); //unreachable code
}
```

## Bull version
"bull": "3.12.1",

## Additional information
node v12

**Comment by manast** [comment]
That would be impossible since a constructor is by JS design synchronous. One wait to detect connection errors is:
```js
    queue.isReady().then(
      () => {
        done(new Error('Did not fail connecting to invalid redis instance'));
      },
      err => {
        expect(err.code).to.be.eql('ECONNREFUSED');
        queue.close().then(done, done);
      }
    );
```
you can also attach an 'error' listener to the queue to listen for all errors:
```js
queue.on('error',(err) => { ... });
```

**Comment by sukhpreet-rupeek** [comment]
In this scenario , isReady() is not  throwing error though i have invalid redis connection url. instead its running the .then() block code.
