### ISSUE TITLE
[Question] Is there way to remove delayed jobs from a queue using jobName/jobId?

### ISSUE THREAD

**Issue by hemantreddy** [OptimalBits/bull#1829]
## Description
I am trying to remove a delayed job but don't seem to find any method for it. So far I have only come across `removeRepeatable`.

## Bull version
3.14.0

## Additional information
This is how I am adding a delayed job to an existing queue
`const newJob = await this.quizScheduleQueue.add(
                    jobName,
                   payload,
                    { delay, removeOnComplete: true }
 )`

**Comment by manast** [comment]
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#jobremove

**Comment by hemantreddy** [comment]
Thank you for time!
