### ISSUE TITLE
Where are you able to find the redis keys on each job object? 

### ISSUE THREAD

**Issue by lovgrandma** [OptimalBits/bull#1830]
## Description
I am using bull on my nodejs application and I am wondering what is the key name for me to locate the key on redis? When I run `keys *` on redis-cli it shows bull job records that are never removed even though on bull it says there are 0 jobs. I am trying to run a simple `redisclient.del(jobId)` in my application at the end of each process but I cannot find the redis key name on the job object when a log it. I am not trying to destroy all matching redis jobs.

**Comment by lovgrandma** [comment]
I have discovered a solution to run at the end of a process. Can help with reducing bull job clutter on redis.

// Cleanly deletes redis record
const deleteRedisRecord = async (job) => {
    const searchQuery = "*:video transcoding:" + job.id;
    redisclient.keys(searchQuery, (err, reply) => {
        reply.forEach((el, i) => {
            redisclient.del(reply[i]);
        })
    })
}

**Comment by manast** [comment]
I am not sure I understand, what is the issue you are reporting? If it is how to delete jobs there are both APIs for it, or settings to just remove all completed/failed jobs.

**Comment by lovgrandma** [comment]
> I am not sure I understand, what is the issue you are reporting? If it is how to delete jobs there are both APIs for it, or settings to just remove all completed/failed jobs.

The issue is that records for completed/failed jobs do not get deleted from redis when you specify (removeOnComplete: true, removeOnFail: true) as options and they still do not delete if you run moveToCompleted() or moveToFailed() on a job at the end of a process. I was trying to figure out if there was a straight forward way of deleting these unneeded redis records. The code that I use there is sufficient for the time being.

**Comment by yongzhang** [comment]
I'm also curious about this topic, I don't know why this issue was closed, I have a a large number of keys with format `myqueue-name:id` in redis, I don't know what they are and how to clean up.
