### ISSUE TITLE
prefix option is owerwrite by keyPrefix of redis options

### ISSUE THREAD

**Issue by zyf0330** [OptimalBits/bull#1832]
## Description
Queue#prefix option is overwrite by keyPrefix in redisOpts
#### (An easy to reproduce test case will dramatically decrease the resolution time.)
set prefix option and redis keyPrefix option at the same time, keyPrefix is effect.
## Bull version
3.14.0

**Comment by manast** [comment]
This works actually as design. Redis opts has a preference over standard prefix option.

**Comment by zyf0330** [comment]
Maybe it should be doced.
