### ISSUE TITLE
Does Bull suits my use case?

### ISSUE THREAD

**Issue by thelinuxlich** [OptimalBits/bull#184]
I have a web analytics application which delegates all tracking to a cluster of background workers using nanomsg. Thinking about adding persistence, but does Bull behaves nice with a heavy load?

**Comment by arihantdaga** [comment]
Hello,
I was trying to switch from agenda to Bull. In my use case i have a smart home solution provider where users are able to create multiple schedules and scenes for their home appliances. I was wondering if Bull is suitable in my use case where i'll be having 10,000s of scheduled jobs. Everyday. and these jobs needs to be persistent, even if redis crashed or something happened to the bull, when it wakes up again, will it pick up the stuffs where it left ? 
Can somebody please help me with these queries..

**Comment by manast** [comment]
It will work reliably but you probably will need to have some tooling to keep track of all this jobs. Also it may be good to segment the jobs in different queues, so that you do not have all 10k scheduled jobs in the same queue.
