### ISSUE TITLE
Redis cluster Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by apoorvans** [OptimalBits/bull#1840]
## Description
Seeing connection error in the logs continuously when connecting to a redis cluster running in kubernetes. I used a prefix when creating the queue.
`new Queue("thequeuename", { connection: redis(), prefix: "{myqueueprefix}" })`

where redis() is:
`import Redis from 'ioredis';
export default function redis() {
    return new Redis.Cluster(config, { enableReadyCheck: true });
}`

Don't know where to start looking. There was no trouble connecting to a single redis instance in local or stage env (also in k8s).

## Bull version
1.9.0

**Comment by FAL-22** [comment]
same issue here. connecting to kubernetes
