### ISSUE TITLE
How to move job from Completed to Waiting or Failed?

### ISSUE THREAD

**Issue by marcodali** [OptimalBits/bull#1842]
<img width="537" alt="Screen Shot 2020-08-30 at 23 22 55" src="https://user-images.githubusercontent.com/70110654/91682638-d5aecf80-eb17-11ea-992c-b7feb33234fa.png">

I have some jobs on the **Completed** state, but I need to move them to **Waiting** or **Failed** state.
How can I accomplish this?

**Comment by manast** [comment]
Currently completed jobs cannot be moved back to wait or failed.
