### ISSUE TITLE
Dynamically controlling job

### ISSUE THREAD

**Issue by keerthij** [OptimalBits/bull#1849]
I'm using this bull queue to schedule jobs with delay. I'm running this job repeatedly with 1 min delay. This job notifies parents once the job is completed. The parent process schedules the same job again after 1 min delay. I'm not using repeat option provided in Bull to do this as the job execution time will vary based on the amount of data it needs to process. Now, I've a need to run that job immediately when there is an event from client. So, if already a job with same job id is scheduled then I want to run it immediately or if already running then I want ro stop it and run it again immediately from the begining. I don't want to run another new job paralley as the processor is computationally intensive and there would be many jobs paralley with different job id. I want only one job running at the same time for each job id.  I would like to understand how this can be implemented using Bull. Please let me know your inputs.

**Comment by manast** [comment]
If you know the job id you can use ```job.promote()``` to put the job back into the queue and execute it as soon as there is a free worker. Also remember that if you provide custom job ids, if there is already a job in the queue with the same id that job will not be added to the queue and just be ignored.
