### ISSUE TITLE
Change from node_redis to ioredis

### ISSUE THREAD

**Issue by thelinuxlich** [OptimalBits/bull#185]
So it can support Redis 3 cluster

**Comment by evanhuang8** [comment]
Are the APIs for ioredis mostly the same as the node_redis client? If so this should be very easy

**Comment by thelinuxlich** [comment]
Yeah
https://github.com/luin/ioredis/wiki/Migrating-from-node_redis

**Comment by evanhuang8** [comment]
Would you want to do it? Seems like it should be a small task, though more testing is required.

**Comment by thelinuxlich** [comment]
There is a PR from @nodesocket that addresses this but he closed it, I wonder what happened

**Comment by manast** [comment]
ioredis seems like a great project, but it will take some job to make the porting, its not just a drop in replacement...

**Comment by kulbirsaini** [comment]
I have filed a PR #188 with initial changes. Please review.
