### ISSUE TITLE
Queue delay not working properly

### ISSUE THREAD

**Issue by JensDebergh** [OptimalBits/bull#1850]
Hey there!

I'm bumping into an issue while queueing tasks.

## Description

When scheduling a task to be performed from withing another task, the delay property does not work. Any idea why this is happening?

```
// Queues
defaultQueue.process(JobName.QUEUE_INTAKE_NOTIFICATIONS, queueIntakeNotifications).catch(console.error);
defaultQueue.process(JobName.SEND_INTAKE_NOTIFICATIONS, sendIntakeNotifications).catch(console.error);

// Job 1
const queueIntakeNotifications = async (job: Bull.Job<QueueIntakeNotificationData>, done: DoneCallback) => {
    const now = moment();
    const notificationTime = now.clone().minute(Math.ceil(now.minute() / 15) * 15).second(0).format('HH:mm');
    defaultQueue
        .add(JobName.SEND_INTAKE_NOTIFICATIONS, {}, { delay: 20000 })
        .catch(console.error);
    done();
};

// Job 2
const sendIntakeNotifications = async (job: Bull.Job<SendIntakeNotification>, done: DoneCallback) => {
    console.log('SENDING PUSH NOTIFICATIONS TO USER');
    done();
};
```

The problem here is that `sendIntakeNotifications` gets executed 2 times. Once when it is pushed on the queue and once when the delay has been passed.

Any help in the right direction would be great!

Kind regards
Jens

**Comment by manast** [comment]
The code for the first processor is incorrect, you should write your processors like this:
```ts
const queueIntakeNotifications = async ( async (job: Bull.Job<QueueIntakeNotificationData>) => {
    const now = moment();
    const notificationTime = now.clone().minute(Math.ceil(now.minute() / 15) * 15).second(0).format('HH:mm');
    await defaultQueue
        .add(JobName.SEND_INTAKE_NOTIFICATIONS, {}, { delay: 20000 });
};
```

I wrote the above for clarity, but it can also be written like this since you only have 1 async call:
```ts
const queueIntakeNotifications = async ( (job: Bull.Job<QueueIntakeNotificationData>) => {
    const now = moment();
    const notificationTime = now.clone().minute(Math.ceil(now.minute() / 15) * 15).second(0).format('HH:mm');
    return defaultQueue
        .add(JobName.SEND_INTAKE_NOTIFICATIONS, {}, { delay: 20000 });
};
```

**Comment by manast** [comment]
Let me know if it works better

**Comment by JensDebergh** [comment]
@manast My original code does not have the async call.

```
const queueIntakeNotifications = async (job: Bull.Job<QueueIntakeNotificationData>) => {
    const now = moment();
    const notificationTime = now.clone().minute(Math.ceil(now.minute() / 15) * 15).second(0).format('HH:mm');

    defaultQueue.add(JobName.SEND_INTAKE_NOTIFICATIONS, {}, { delay: 20000 }).catch(console.error);
};
```

Sending:

```
const sendIntakeNotifications = async (job: Bull.Job<SendIntakeNotification>) => {
    console.log('SENDING INTAKE NOTIFICATION');
};
```

SENDING INTAKE NOTIFICATION is logged 2 times again. Do i have to explicitly return something from the async call? If nothing is provided a `Promise<void>` would be returned.

**Comment by manast** [comment]
you still need to return the promise.
I am quite sure this is an issue with your code, if you provide a simpler case that reproduces it that I can run easily I can look into it.

**Comment by manast** [comment]
to make it clear, you need to return the result of this call ```defaultQueue.add(JobName.SEND_INTAKE_NOTIFICATIONS, {}, { delay: 20000 }).catch(console.error);``` for two reasons:
1) Because otherwise you are not handling possible errors of that async call.
2) Because you want to wait for that async operation to complete so that when the job is complete no dangling async operations are still running.

**Comment by JensDebergh** [comment]
@manast Sorry to bother you again. But I don't seem to get why i need to return the the actual side job creation. If they fail thats ok in this instance. Can't I just return `true / false` from the main job?

<img width="1440" alt="Screenshot 2020-09-07 at 16 25 13" src="https://user-images.githubusercontent.com/6651506/92397405-12398700-f127-11ea-8295-1e348c22d74c.png">


Result:

<img width="223" alt="Screenshot 2020-09-07 at 16 29 24" src="https://user-images.githubusercontent.com/6651506/92397583-575db900-f127-11ea-95a0-6bcf177cfa7c.png">


Can't seem to figure out what I am doing wrong since this isn't actually explained in the docs.

**Comment by manast** [comment]
you do not need to return the result from add, you can also await and return something else. The point is that you cannot just ignore the result from add. From the code above I cannot spot anything wrong, if you can write a simpler one file test that reproduces the issue I can look into it.

**Comment by JensDebergh** [comment]
@manast We've found the problem. The queuing indeed works properly. What you are seeing in the image above is "old queued" jobs being processed where the delay already has been passed. 

That's why it seems it is instant.

Sorry for the confusion and thank you for your help!
