### ISSUE TITLE
TypeError: queue.getNextJob is not a function

### ISSUE THREAD

**Issue by tballantyne** [OptimalBits/bull#1851]
## Description
Getting a `TypeError: queue.getNextJob is not a function`

## Minimal, Working Test code to reproduce the issue.

    const { Queue } = require('bullmq');

    const queue = new Queue('test_case_queue');

    async function getJob(){
    	try {
    		const job = await queue.getNextJob();
    	} catch(err) { 
    		console.log(err)
    	}
    }

    getJob();

## Bull version
bullmq 1.9.0

## Additional information
Working from these docs -
https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#manually-fetching-jobs

**Comment by manast** [comment]
This is the Bull repo, BullMQ does not support getNextJob().
