### ISSUE TITLE
TypeError: queue.client.moveToActive is not a function using manual pattern

### ISSUE THREAD

**Issue by tballantyne** [OptimalBits/bull#1852]
###  Description
Getting a `TypeError: queue.client.moveToActive is not a function` when trying to consume a job off the queue using the manual pattern - `queue.getNextJob()`

    TypeError: queue.client.moveToActive is not a function
    at Object.moveToActive (/.../node_modules/bull/lib/scripts.js:89:25)
    at Queue.moveToActive (/.../node_modules/bull/lib/queue.js:1142:18)
    at /.../node_modules/bull/lib/queue.js:1126:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getJob (/.../server/manualConsumer.js:7:15)

## Minimal, Working Test code to reproduce the issue.
    const Queue = require('bull');

    const queue = new Queue('test_queue');

    async function getJob(){
    	try {
    		const job = await queue.getNextJob();
    		console.log(job.data);
    	} catch(err) { 
    		console.log(err)
    	}
    }
    getJob();

## Bull version
3.18.0

**Comment by manast** [comment]
This will work if you wait for the queue to be ready after instantiating it:
```js
const queue = new Queue('test_queue');
await queue.isReady();
```

**Comment by tballantyne** [comment]
Bingo. Yes that works! Thanks.
