### ISSUE TITLE
Repeatable jobs 'every': wrong behavior

### ISSUE THREAD

**Issue by xrip** [OptimalBits/bull#1853]
## Description
Repeatable jobs with "_every_" parameter works wrong or have confusing documentation.

When i create job with ```{ repeat: { every: 15 * 1000 } }``` params
i expect the job would be fired every 15 seconds since job created. 
E.g. if it's created at 15:34:07 the job would run at 15:34:22, then 15:34:37 and so on. 
But actually it would run at 15:34:15, 15:34:30, 15:34:45

## Minimal, Working Test code to reproduce the issue.
```JS
const Queue = require('bull');

const myqueue = new Queue('q');

console.log(new Date, '- Adding job');

(async () => {
    // Repeat every 15 seconds
    const myJob = await myqueue.add(
        { foo: 'bar' },
        {
            jobId: 'every_15_seconds',
            repeat: {
                every: 15 * 1000,
            },
        },
    );

    myqueue.process(function(job, done) {
        console.log(new Date, '- Running job');

        done();
    });
})();
/*
Excepted result:
2020-09-14T16:28:08.884Z - Adding job
2020-09-14T16:28:23.020Z - Running job
2020-09-14T16:28:38.015Z - Running job
2020-09-14T16:28:53.008Z - Running job

Actual result:
2020-09-14T16:28:08.884Z - Adding job
2020-09-14T16:28:15.020Z - Running job
2020-09-14T16:28:30.015Z - Running job
2020-09-14T16:28:45.008Z - Running job

Looks like it runs every 15 seconds since day start, not the startDate nor time, when job was added.
 */
```

## Bull version
3.18.0

**Comment by xrip** [comment]
Example updatet to be more relevant.

**Comment by manast** [comment]
This works as designed, here you can find some background: https://github.com/OptimalBits/bull/issues/1239

**Comment by wiput1999** [comment]
I'm expecting this result too. How to config for this expected result?

**Comment by xrip** [comment]
I've solve this by adding delayed job and reading new job when processing current job.
Works like i want. But it's not durable.
