### ISSUE TITLE
TypeError - child.off is not a function

### ISSUE THREAD

**Issue by tsebas** [OptimalBits/bull#1854]
## Description
Getting type error when using the sandboxed processor.
```
error: TypeError - child.off is not a function stack_trace=TypeError: child.off is not a function
    at ChildProcess.onMessageHandler (/data/node_modules/bull/lib/process/child-pool.js:113:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```
Interestingly after the error is thrown, the job still get's processed:
```
127.0.0.1:6379> hgetall workers_test:1
 1) "name"
 2) "__default__"
 3) "data"
 4) "{}"
 5) "opts"
 6) "{\"attempts\":1,\"delay\":0,\"timestamp\":1599815285997}"
 7) "timestamp"
 8) "1599815285997"
 9) "delay"
10) "0"
11) "priority"
12) "0"
13) "processedOn"
14) "1599815286044"
15) "returnvalue"
16) "{}"
17) "finishedOn"
18) "1599815286144"
```

After processing that one job though, queue.process seems like it resolves as the process stops. If I comment out the offending line for example, the job is processed correctly and the main process stays running.

## Minimal, Working Test code to reproduce the issue.
file1.js
```
const bull = require('bull');
const q = bull('workers_test');
q.process(`file2.js`);

q.add({});
```
file2.js
```
module.exports = job => {
  return Promise.resolve({});
}
```
## Bull version
3.18.0

**Comment by sontono** [comment]
+1

**Comment by gabegorelick** [comment]
What version of Node.js are you running? `emitter.off` was added in Node 10. 

Offending code is https://github.com/OptimalBits/bull/blob/06b511a5c376da553236e63f217d12cbfbbaeb97/lib/process/child-pool.js#L113
