### ISSUE TITLE
Does Bull support horizontal scaling?

### ISSUE THREAD

**Issue by akashwmp** [OptimalBits/bull#1856]
Hi @manast,
I"m using bull queue in a microservices architecture under a distributed system. So I got one query whether bull queue supports horizontal scaling because I feel if multiple instances of Nodejs instances running on different machines then they each have got their own bull queue instance. So in a pub sub-model, each bull queue consumer running on different instances will process the message multiple times.

so is that the limitation of the bull queue library?

**Comment by rosslavery** [comment]
Each worker connects to a common redis instance and claims (locks) a job to prevent the same job being claimed by multiple workers.

In our experience Bull scales very well horizontally with very little effort. We process around 200,000 jobs daily with an horizontally autoscaled worker pool.

**Comment by hynra** [comment]
Do you mean Round Robin? As long as each worker is connected to the same Redis instance, they will get a different job. That is explained in their documentation: https://docs.bullmq.io/
> You can have as many worker processes as you want, BullMQ will distribute the jobs across your workers in a round robin fashion.

**Comment by donaldduy-lb** [comment]
> Each worker connects to a common redis instance and claims (locks) a job to prevent the same job being claimed by multiple workers.
> 
> In our experience Bull scales very well horizontally with very little effort. We process around 200,000 jobs daily with a horizontally autoscaled worker pool.

@rosslavery Could you provide more information on how you've set up your horizontal scaling? I'm coming into an issue where my pods are being killed before a job completes. I thought this might be fine because I expected the job to retry (I've set it to 5 retries), but these interrupted jobs are never retried.

**Comment by manast** [comment]
@donaldduy-lb if the worker dies in the middle of the processing it will be considered a stalled job. maxStalledJobs setting is 1 by default, you may want to increase that.

**Comment by manast** [comment]
Going to close this issue since it has been answered.

**Comment by Spoutnik97** [comment]
> Each worker connects to a common redis instance and claims (locks) a job to prevent the same job being claimed by multiple workers.
> 
> In our experience Bull scales very well horizontally with very little effort. We process around 200,000 jobs daily with a horizontally autoscaled worker pool.

@rosslavery I am looking for a way to scale horizontally my bull workers. I am thinking to use kubernetes, and a custom script to fetch the queue length, but I am curious about your solution !

How did you scale your infrastructure ?
