### ISSUE TITLE
Task results get stored in redis forever

### ISSUE THREAD

**Issue by jbreckman** [OptimalBits/bull#1858]
I'm not totally positive how to show this, but my redis keeps getting clogged up with old bull messages.  

```
[
  [
    "name",
    "__default__"
  ],
  [
    "data",
    {
      "match": "Z3on_x44A",
      "requestId": "CN3Ibwi_f"
    }
  ],
  [
    "opts",
    {
      "attempts": 1,
      "delay": 0,
      "timestamp": 1600135798323
    }
  ],
  [
    "timestamp",
    "1600135798323"
  ],
  [
    "delay",
    "0"
  ],
  [
    "priority",
    "0"
  ],
  [
    "processedOn",
    "1600135798319"
  ],
  [
    "returnvalue",
    "null"
  ],
  [
    "finishedOn",
    "1600135800946"
  ]
]
```

There is no TTL on these messages and I can't find anything in the documentation as to how to consume them or how to make them not get created in the first place.

**Comment by manast** [comment]
Please take a look at job options ```removeOnComplete``` and ```removeOnFailed```:
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd

**Comment by jbreckman** [comment]
@manast oh - can't believe I didn't see this.  Thank you!
