### ISSUE TITLE
Closing connections when using redis-sentinel

### ISSUE THREAD

**Issue by adame21** [OptimalBits/bull#1859]
Hi,
So I'm using bull with redis-sentinel and I'm having trouble closing connections.

For the sake of a simple example lets say I have 3 apps

1. an API which is always connected and adds the jobs.
2. a worker that is always connected and process the jobs
3. another API to be able to do certain actions on the queue - this one is supposed to connect, do its thing, disconnect.

So heres an example snipper from 3:
Don't mind the crappy code.
````javascript
    var queueName = req.body.queueName;
    if (!queueName) {
        res.status(400);
        res.json({
            answer: "missing queue name"
        });
    }
    else {
        const queue = new Queue(queueName,
            {
                createClient: () => {
                    return new Redis(redisConfig)
                }
            });

        var allJobsArr = await queue.getJobs();
        const queue2 = new Queue(queueName, getVariableValue("REDIS_ADDRESS"));
        var allJobsArr2 = await queue2.getJobs();
        res.status(200);
        res.setHeader("content-type", "text/plain")
        res.send(JSON.stringify(allJobsArr.concat(allJobsArr2)));
        await queue.close();
        await queue2.close();
    }
````
So at the end im calling .close() for both queues, the normal one (queue2) closes successfuly, but it seems the ones connected to redis-sentinel aren't.

If its relevant its all running on Kubernetes env and connects to a redis-sentinel server located outside the kubernetes.

Am I misusing the library? 
Right now my only solution is to kill the process to force the connection to close.
What am I missing here?

And just to add - I'm running this 
````cmd
kubectl -n bin-lan get pods --no-headers|grep bullapi --color=never |awk '{print $1}'| xargs -i kubectl -n bin-lan exec -i {} -- netstat | grep tcp|grep redis|wc -l
````
And the result I'm getting right now for example is 252 connections, which is way too high to make sense.

Thanks :)

**Comment by manast** [comment]
If you create redis connections with ```ts
createClient: () => {
                    return new Redis(redisConfig)
                }
```
then you also need to free them yourself. Just store the connection and close it manually after closing the bull queue.

**Comment by adame21** [comment]
I feel silly now haha

Thanks a lot.
