### ISSUE TITLE
Custom options get overridden by default options when adding a job

### ISSUE THREAD

**Issue by keith666666** [OptimalBits/bull#1860]
## Issue
Custom options get overrided by default options when adding a job(add and addBulk).

## Affected versions
- v3.18.0
- v3.17.0
- v3.16.0

## Related code
https://github.com/OptimalBits/bull/blob/db070a5908ed9b0ba8bd669205a56dc8551d3480/lib/queue.js#L690

## Related commit
https://github.com/OptimalBits/bull/commit/ac2fc51c2b8f544a150b83e5969654f5af8de5f7

![image](https://user-images.githubusercontent.com/14068334/93325205-853eae00-f849-11ea-8a58-e9db050ca02d.png)

**Comment by rohitkhatri** [comment]
When this will be fixed, I'm facing issue regarding this

**Comment by manast** [comment]
closing since this has been fixed a while ago.
