### ISSUE TITLE
[question] manual dequeue or pop instead of static process function ?

### ISSUE THREAD

**Issue by itsTeknas** [OptimalBits/bull#1863]
I would like to manually pop or dequeue items from my queue depending on external events instead of having a static process function for my queue. 
I couldn't find any api that just gives the next job in line and blocks it for a visibility timeout.

Is this even a use case that bull is meant to solve or should i be looking at 
https://www.npmjs.com/package/rsmq or something ?

**Comment by manast** [comment]
Please check here: https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#manually-fetching-jobs
