### ISSUE TITLE
Get jobs with jobId containing string

### ISSUE THREAD

**Issue by eperezf** [OptimalBits/bull#1865]
## Description
Hi, I am working with an excel importing script and each row has a unique ID in the form of 12 random alphanumeric characters where the first 6 are always the same (example: ABC123XXXXXX) in that file, but different in other files. I wanted to easily associate each row with a job so I can see which rows fail to import, so I set the `jobId` the same as the ID of the row. 

Because several Excel files with different initial strings can be imported at the same time, I need to separate jobs from one file and another.

Is there any way of using `queue.getJobs()` but with a string pattern like it is used in `queue.removeJobs()`?

Like `queue.getJobs('ABC123*')`

I know I can do the sorting after getting the whole list but it would be nice if we can get a filtered list. 

Thanks!

**Comment by eperezf** [comment]
Maybe a temporary workaround can be creating a queue for each file, but I can have multiple files being uploaded at the same time. Would it be an issue creating and using several queues at the same time instead of just one for the same kind of job?

**Comment by manast** [comment]
Here is how I would do it. I would have one Queue for dividing the job in rows, and then one queue for the rows job. Then I would keep a counter for every excel file stored in a redis key. In the job that divides in rows I would set the counter, then in every job that process one row I will decrease the counter for that file, if the counter has reached zero I know the whole excel has been processed and I can notify the excel file is ready (maybe using another queue for that too who knows). 
If you do it like that then you can process as many excel files in parallel as you want and they will now conflict with each other. 

Note, the redis DECR command decrements and returns the result value so it is atomic, but there is a small hazard, if the last job for a excel fails directly after decrementing to zero you will miss to notify that the excel file is ready, so you your job should be able to retry and then the counter could go to negative so just consider that negative numbers also signals the document is completed and it should be all fine:
https://redis.io/commands/decr

**Comment by eperezf** [comment]
I don't know if I didn't explain myself correctly or I didn't understand your response, but I'm kind of lost. English is not my first language. Also it may be that I'm a complete noob at Redis. Just been using it with Bull.

I don't see how creating multiple queues for dividing the files into jobs and then processing the jobs solves my issue. 

My problem is the following:

- I save all the jobs (rows from an Excel file) in a single queue. 
- The ID of each job (row) depends on the user that uploaded it. 
- User 1 would have jobs (rows) with ID (USR001XXXXXX)
- User 2 would have jobs (rows) with ID (USR002XXXXXX)
- There can be multiple jobs in the same queue with IDs starting with either USR001 or USR002
- I want to get only the jobs from User 1
- So I should get all the jobs with ID starting with USR001

Is there any way of improving the `queue.getJobs()` function so that it can accept a string or a pattern? So you can search like `queue.getJobs('USR001*')` and it returns all the jobs that match that pattern.

**Comment by manast** [comment]
I suggested my approach to not need to do this step:

> I want to get only the jobs from User 1

Why would you like to do that in the first place?

**Comment by eperezf** [comment]
So the user can see which jobs failed and which ran without problem.

**Comment by manast** [comment]
coincidentally there is a PR open in BullMQ that does what you want: https://github.com/taskforcesh/bullmq/pull/277
