### ISSUE TITLE
Question/feature request: Get time since a job was added to the queue OR manually retried?

### ISSUE THREAD

**Issue by papandreou** [OptimalBits/bull#1867]
Hi!

In our setup we have some metrics and alerting around how long jobs spend in the queue before being processed so we can continuously fine-tune the number of workers. There's one scenario where we're having a bit of trouble coming up with the right number: A job that fails and some hours gets retried manually. In that case `processedOn` will be reset to `null` when the job gets retried, and `timestamp` still reflects the time where the job was first added to the queue.

At that point, is there any way to find out how long time the job has spent in the queue since it was manually retried? If the answer is no, I would be happy to open a PR that adds another timestamp to the job so it's possible. Just wanted to check first :)

**Comment by manast** [comment]
No, it is not possible, we would need in that case a "retriedOn" timestamp.

**Comment by papandreou** [comment]
Thanks for the quick reply! Opened a PR with that here: https://github.com/OptimalBits/bull/pull/1868/ 🤗
