### ISSUE TITLE
Job processing of all queues are stalled due to traffic in one queue

### ISSUE THREAD

**Issue by 0x61x** [OptimalBits/bull#1870]
# Description
I have multiple topics created on the fly. Jobs in each topic are very small but should be executed sequentially.

I'm trying to use Bull for this purpose but I'm facing a strange issue where if one queue has a lot of job insertion (not even a lot but continuous insertions too). 
The job processing is halted not for just that queue but for all the queues like the system is in a deadlock state and jobs continue to pile up.

## Minimal, Working Test code to reproduce the issue.
I was not able to reproduce the issue. I'm sharing my implementation.
```js
const q = new Bull(`packets:${id}`, { createClient: bullRedisClientFactory })
q.process(async job => {
   return pingHandler(job.data);
});

q.addBulk({ data, opts });
```
`bullRedisClientFactory` is the suggested function to reuse the connections.

`pingHandler` has some MongoDB and Redis calls. Is calling Redis inside the handler creating an issue?

I also tried using a loop to insert the data to avoid bulk queries, but no luck.

## Bull version
```js 
"bull": "^3.18.0"
```
## Additional information
I tried to run the processor function as a separate process but the behavior is the same.
Sometimes, restarting the process solves the issue and job processing starts even under traffic. Is there any issue with lock management with my implementation? 
I'm reaching out after trying significant times to understand and resolve the issue. Is something wrong with my implementation? Thanks in advance!

**Comment by manast** [comment]
I cannot see anything wrong with the code you posted, however this sounds more like an issue in your code. How much you call insert should not affect the workers that are consuming jobs, specially if they run in different processes.

**Comment by manast** [comment]
Btw, I recommend you that you cut down all the code and start with minimal example that works, then add features until you find the problem that causes your issue.

**Comment by 0x61x** [comment]
Thanks for your reply @manast 
I couldn't figure out the issue causing the bottleneck. I will try to figure out the issue in the future to understand more. For now, we have moved to apache Artemis, to support some other features like message-grouping as well.
