### ISSUE TITLE
Queue stop when a task calls done(error)

### ISSUE THREAD

**Issue by mritzco** [OptimalBits/bull#1874]
#  Description

Question:
Is it possible that some malformed errors cause the queue to get stalled?
Are there any rules of what an error can contain? 

### Context
One of our queues, all of them running as separate processes, stops processing if any of the tasks returns  `done (err)` 

- We don't know in advance the content of err.  Normally connectivity, NetSuite error or Slack error (so very rare).
- NS Errors can be a mix of strings, json sometimes

## Minimal, Working Test code to reproduce the issue.

```js
// This can be slackAPI or NetSuiteAPI
slackAPI.post(channel, msg, (err, data) => {
  if (err) { return done(err); }
});
```
The last error that caused the issue,
```js
{\"message\":\"connect ETIMEDOUT 54.211.89.16:443\",\"name\":\"Error\",\"stack\":\"Error: connect ETIMEDOUT 54.211.89.16:443\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)\",\"config\":{\"url\":\"https://slack.com/api/conversations.create\",\"method\":\"post\",\"data\":\"{\\\"name\\\":\\\"lloyd_20704\\\"}\",\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Authorization\":\"Bearer SOME_TOKEN\",\"Content-Type\":\"application/json;charset=utf-8\",\"charset\":\"utf-8\",\"User-Agent\":\"axios/0.19.0\",\"Content-Length\":22},\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1},\"code\":\"ETIMEDOUT\"}
```

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
Perhaps return the sample JSON from a processor

## Bull version
3.11.0

**Comment by manast** [comment]
If you are using a separate processor you need to return a promise instead of using the done callback. Not sure what is exactly happening in this case though, it should have thrown an exception telling that "done" is undefined. Can you share more of your processor code or similar code that would reproduce the issue?

**Comment by mritzco** [comment]
Sure, I'll prepare some minimal code and see if the issue actually replicates.
Thanks

**Comment by mritzco** [comment]
Hi, 
I've been unable to prepare the case. I'll switch all code to Promises first and if the problem keeps happening I'll reopen the issue with some sample code.
Thanks a lot for your help.
