### ISSUE TITLE
Issues with rate limiter

### ISSUE THREAD

**Issue by SrividhyaB** [OptimalBits/bull#1875]
## Description
Rate limits don't get applied properly when jobs are added to the queue at a rate greater than the rate limit of the queue continuously.
I think there is some problem with the delay with which the jobs are pushed to the delayed queue while there are many jobs also getting added to the queue.

If I run a script first to add 200 jobs to the queue with a rate limit of 50 jobs/min and then start a script to process these jobs, rate limiter works fine. But while it is processings jobs in the queue, if I add a lot more jobs, the rate limiter doesn't work as expected.

Problems:

1. Rate limit is not obeyed when there is a consistent inflow of jobs to the queue at a rate higher than the limit. It usually processes jobs lesser than the limit configured.
2. Sometimes the jobs are processed out of order.

Trial 1: Reproduces out of order 

Ran a script to add jobs to a queue.
**Rate limit is 2 requests/ per min.**

Output: 

Min:seconds => id of the job scheduled

```

41:12 => 1
41:12 => 2
41:12 => 3
41:12 => 4
42:50 => 5
42:50 => 6 
42:50 => 7
42:50 => 8
43:50 => 9
43:50 => 10
43:50 => 11
43:50 => 12
43:51 => 13
43:51 => 14
43:51 => 15
43:51 => 16
43:52 => 17
43:52 => 18
43:52 => 19
43:52 => 20
44:34 => 21
44:34 => 22
44:34 => 23
44:34 => 24
46:27 => 25
46:27 => 26
46:27 => 27
46:27 => 28
51:29 => 29
51:29 => 30
51:29 => 31
51:29 => 32
```
Ran another script to process jobs from the queue

Min:seconds => id of the job processed

```
41:12 => 1
41:12 => 2
42:12 => 3
42:45 => 4
43:12 => 5
43:45 => 6
44:18 => 7 // NOTE: job with id 8 doesnt get picked.
45:18 => 9
45:51 => 10 
46:24 => 11
47:30 => 13
48:3 => 14
48:36 => 15
48:54 => 8
49:36 => 16
49:42 => 17
50:36 => 12
50:48 => 19
51:36 => 18
52:6 => 20
52:36 => 21
53:0 => 22
```

Trail 2: Reproduces rate limit not being obeyed

**Rate limit is 5 requests/ per min.**

Min:seconds => id of the job scheduled

```
23:34 => 1
23:34 => 2
23:34 => 3
23:34 => 4
23:34 => 5
23:34 => 6
23:34 => 7
23:34 => 8
23:34 => 9
23:34 => 10
27:32 => 11
27:32 => 12
27:32 => 13
27:32 => 14
27:32 => 15
27:32 => 16
27:32 => 17
27:32 => 18
27:32 => 19
27:32 => 20
28:50 => 21
28:50 => 22
28:50 => 23
28:50 => 24
28:50 => 25
28:50 => 26
28:50 => 27
28:50 => 28
28:50 => 29
28:50 => 30
31:15 => 31
31:15 => 32
31:15 => 33
31:15 => 34
31:15 => 35
31:15 => 36
31:15 => 37
31:15 => 38
31:15 => 39
31:15 => 40
33:1 => 41
33:1 => 42
33:1 => 43
33:1 => 44
33:1 => 45
33:1 => 46
33:1 => 47
33:1 => 48
33:1 => 49
33:1 => 50
```

Min: seconds => id of the job processed

```
23:36 => 1
23:37 => 2
23:37 => 3
23:37 => 4
23:37 => 5
24:36 => 6
24:50 => 7
25:3 => 8
25:16 => 9
25:29 => 10
27:32 => 11
27:32 => 12
27:32 => 13
27:32 => 14
27:32 => 15
28:32 => 16
28:45 => 17 // NOTE: 5 jobs should have been processed in this window but it has not been processed. Note that right around this time, we added a lot of jobs to the queue
30:12 => 21
30:25 => 22
30:38 => 23
30:51 => 24
30:56 => 18
31:12 => 25
34:11 => 33
34:12 => 28
34:24 => 34
34:24 => 29
34:36 => 30
35:11 => 35
35:13 => 20
35:17 => 38
35:23 => 36
35:25 => 31
36:11 => 39
36:23 => 26
36:35 => 19
36:45 => 41
36:47 => 40
37:11 => 37
37:23 => 27
37:23 => 32
37:58 => 42
38:12 => 43
38:25 => 44
38:38 => 45
38:51 => 46
39:4 => 47
39:18 => 48
39:31 => 49
39:44 => 50
```

Script to add jobs:
```
var Queue = require('bull');
const queue = new Queue("queue_1", {
    defaultJobOptions: {
        removeOnComplete: true,
        removeOnFail: true,
    },
    limiter: {
        duration: 60000,
        max: 2,
    }
});

(async function () {
   for (let i=0; i < 4; i++) {
      var currentdate = new Date();  
      const job = await queue.add({data: {a: Math.random().toString(36).substring(7)}, accountId: "1"}); 
      console.log(currentdate.getMinutes() + ":" + currentdate.getSeconds() + " => " + job.id) 
   }
    await queue.close();
})();
```

Script to process jobs:
```
var Queue = require('bull');
const queue = new Queue("queue_1", {
    defaultJobOptions: {
        removeOnComplete: true,
        removeOnFail: true,
    },
    limiter: {
        duration: 60000,
        max: 2,
    }
});

queue.process(1, async (job, done) => {
    var currentdate = new Date();
    console.log(currentdate.getMinutes() + ":" + currentdate.getSeconds() + " => " + job.id) 
    done();
});
```

## Bull version

Version: 3.18.0

## Additional information

The issue is also reproducible in scenarios like:

The rate limit is set to 200/min and 400 jobs/min are consistently added to the queue.

**Comment by manast** [comment]
Thanks for a thorough description. First, regarding the out of order. This is actually a known issue, I tried to make it as good as possible with the current design in this PR https://github.com/OptimalBits/bull/pull/1816 however it is still a best effort endeavour, we cannot guarantee the order at all times. A new design is needed for this were rate limiter is not based on delayed jobs, but I am not sure when I will be able to implement it. 
Regarding not obeying the rate limit, I am a bit unsure what you mean after looking at your data, do you mean that it is processing more jobs than it should or less than it should, and if it is less, how much less?

**Comment by SrividhyaB** [comment]
Thank you @manast for clarifying on out of order. 

I mean it is processing a lesser number of jobs than the rate limit configured. 

In the above data I have mentioned, let us take the trail 2: Rate limit is 5 requests/ per min.

This is the the output of job processed

```
23:36 => 1
23:37 => 2
23:37 => 3
23:37 => 4
23:37 => 5 // Rate limit is obeyed. 5 jobs in 23rd minute
24:36 => 6
24:50 => 7
25:3 => 8
25:16 => 9
25:29 => 10  // Rate limit is obeyed. 5 jobs in next one minute
27:32 => 11
27:32 => 12
27:32 => 13
27:32 => 14
27:32 => 15 // Rate limit is obeyed. 5 jobs in next one minute
28:32 => 16
28:45 => 17 // NOTE: 5 jobs should have been processed in this window but it has not been processed. Note that right around this time, we added a lot of jobs to the queue
30:12 => 21
30:25 => 22
```

Between 27:32 to 28:32, it should have processed 5 jobs. 
Again it should have processed 5 jobs between 28:32 and 29:32
But it has processed only 2 jobs at 28th minute and no jobs are processed at 29th minute. 

I have run these scripts multiple times. It always processes a lesser number of jobs than the rate limit configured while new jobs keep getting added to the queue. I think the delay value computed is a higher value than it should be so jobs get processed slowly. I'm still trying to understand the code of delay computation.

I'm not able to quantify how much less because there is no fixed pattern to it that I could find yet.

**Comment by SrividhyaB** [comment]
@manast Is there a design doc on the new approach for rate-limiting? I would also like to contribute.

**Comment by manast** [comment]
The code for rate limiting is basically this, I put extra comments in order to make it more clear:

```lua
  -- -- key for storing rate limited jobs
  -- When a job has been previously rate limited it should be part of this set
  -- if the job is back here means that the delay time for this job has passed and now we should
  -- be able to process it again.
  local limitedSetKey = rateLimiterKey .. ":limited"
  local delay = 0
  
  -- -- Check if job was already limited
  local isLimited = rcall("SISMEMBER", limitedSetKey, jobId);

  if isLimited == 1 then
     -- Remove from limited zset since we are going to try to process it
     rcall("SREM", limitedSetKey, jobId)
     rcall("HDEL", limiterIndexTable, jobId)
   else
     -- If not, check if there are any limited jobs
     -- If the job has not been rate limited, we should check if there are rate limited jobs, because if that
     -- is the case we do not want to process this job, just calculate a delay for it and put it to "sleep".
     local numLimitedJobs = rcall("SCARD", limitedSetKey)

     if numLimitedJobs > 0 then
       -- Note, add some slack to compensate for drift.
       -- Could this slack be the reason for much less jobs to process? Experimenting with this slack actually shows that you can get more or less out of order jobs, i.e. the larger the slack the less out of order.
       delay = ((numLimitedJobs * ARGV[7] * 1.1) /  maxJobs) + tonumber(rcall("PTTL", rateLimiterKey))
     end
  end

  local jobCounter = tonumber(rcall("INCR", rateLimiterKey))
  
  -- check if rate limit hit
  if (delay == 0) and (jobCounter > maxJobs) then
     -- Seems like there are no current rated limited jobs, but the jobCounter has exceeded the number of jobs for this unit of time so we need to rate limit this job.
    local exceedingJobs = jobCounter - maxJobs
    delay = tonumber(rcall("PTTL", rateLimiterKey)) + ((exceedingJobs - 1) * ARGV[7]) / maxJobs
  elseif jobCounter == 1 then
    rcall("PEXPIRE", rateLimiterKey, ARGV[7])
  end
```

**Comment by manast** [comment]
ultimately what I want is implement the rate limiting using a separated ZSET where all the rate limited jobs are placed and consumed in order, however this is quite challenging to introduce in current bull design, so I am exploring implementing this functionality in a Redis Module instead.

**Comment by SrividhyaB** [comment]
@manast Thanks a ton for the detailed comments. 

Could the issue be with the jobCounter? The jobCounter (":limiter" redis key) is incremented irrespective of whether a job is processed or rate limited. 

Let us take this case:

Rate limit is set to 4 jobs/minute. 

We added 8 jobs to the queue at 0th min. 4 are processed immediately and 4 are added to the "limited" set

After a minute, jobCounter is reset to 0 (the key has expired).

Now the first job, lets name it "latelimited_job_1" in the set is picked up. Since it is an already rate limited job, delay won't be computed. So, delay = 0.

Right at this time, let us say we added 4 more jobs to the queue. Since we already have members in "limited" set, delay will be computed and jobCounter gets incremented by 4 (though all of these actually have only been rate-limited and not processed) and these jobs are scheduled with a delay.

Now "latelimited_job_1" is with delay = 0 but jobCounter > maxJobs condition is met. So a delay is computed and the job gets put to the delayed queue again. This also could cause jobs to be processed out of order. 

_Should we increment jobCounter only when the job is actually processed and not when it is rate limited?_

Code changes: 

```lua
  local jobCounter = tonumber(rcall("GET", rateLimiterKey)) // Change:: Get the count of jobs processed
  if(jobCounter == nil) then
    jobCounter = 0
  end
  -- check if rate limit hit
  if (delay == 0) and (jobCounter >= maxJobs) then
    local exceedingJobs = jobCounter - maxJobs
    delay = tonumber(rcall("PTTL", rateLimiterKey)) + ((exceedingJobs - 1) * ARGV[7]) / maxJobs
  elseif jobCounter == 0 then // Change::  First job to be processed in the rate limit window
    rcall("SET", rateLimiterKey, 0)
    rcall("PEXPIRE", rateLimiterKey, ARGV[7])
  end

  if delay > 0 then 
    local bounceBack = ARGV[8]
    if bounceBack == 'false' then
      local timestamp = delay + tonumber(ARGV[4])
      -- put job into delayed queue
      rcall("ZADD", KEYS[7], timestamp * 0x1000 + bit.band(jobCounter, 0xfff), jobId)
      rcall("PUBLISH", KEYS[7], timestamp)
      rcall("SADD", limitedSetKey, jobId)
      
      -- store index so that we can delete rate limited data
      rcall("HSET", limiterIndexTable, jobId, limitedSetKey)

    end

    -- remove from active queue
    rcall("LREM", KEYS[2], 1, jobId)
    return true
  else
    -- false indicates not rate limited
    tonumber(rcall("INCR", rateLimiterKey)) // Change:: increment only  when a job is not rate limited
    return false
  end
end
```

**Comment by manast** [comment]
thanks for your well thought analysis. 

> Now "latelimited_job_1" is with delay = 0 but jobCounter > maxJobs condition is met. So a delay is computed and the job gets put to the delayed queue again. This also could cause jobs to be processed out of order.

That cannot really happen since the lua script is always executed atomically. However, you are right in that jobs that have been rate limited keep incrementing the jobCounter, so I think that you are right in that it can introduce some hazards like the ones you are describing, specially that it will process less jobs than it should actually be allowed to.

It also looks like your small change actually would solve the problem safely. Did your tests work correctly after applying this patch?

**Comment by SrividhyaB** [comment]
Ah right! I missed that lua scripts are executed automatically. 
Yes, I have tested the patch and the rate limit is obeyed now.

**Comment by manast** [comment]
If you preparer a PR I will glad to merge it.

**Comment by SrividhyaB** [comment]
Raised a [PR](https://github.com/OptimalBits/bull/pull/1879). Can you please take a look at it? @manast

**Comment by Bazsi96** [comment]
Hi everybody! 

I have exactly the same problem. 
Has it been solved? 

Thanks!
Blaze!

**Comment by alkhachatryan** [comment]
The same in 2022

**Comment by manast** [comment]
@alkhachatryan what is the same in 2022?

**Comment by alkhachatryan** [comment]
@manast what @Bazsi96 wrote a year ago.
Detailed: rate limiter doesn't work. It's very good, that you're online right now. I'm going to create a new ticket for that and mention that here

**Comment by alkhachatryan** [comment]
@manast bro :) Help please or tell me to find out the issue and make a PR
