### ISSUE TITLE
How can I create only one producer in a kubernetes environment

### ISSUE THREAD

**Issue by grapevineai** [OptimalBits/bull#1876]
Bull's doc does a great job in explaining how to use the queues and how the workers easily connect to redis to wait for the next task.

The problem is for producer to be able to produce the job only once and make sure there is no duplicates in production especially in real cluster environment (such as kubernetes as opposed to nodejs cluster).

The problem I have is the following:

I have a listener in my app that listens to DB changes. For a specific change I send a job to Bull. Even though Bull makes sure not to create duplicated jobs, how can I make sure only one machine is listening to changes (and if it dies, another machine listens instead)? What is the best strategy to avoid conflicts when there are multiple servers running and the producer is a listener of an external source?

**Comment by manast** [comment]
If I understand your case correctly, the jobs that you add to the queue will processed only once independently on the number of consumers (workers) you have. So basically in the scenario you are describing it would just work, just add as many workers as you need to consume the job load at desired pace and everything will be processed accordingly.

**Comment by grapevineai** [comment]
Actually each job is a cron that will run periodically. I want to trigger them on start (check in my external DB to get all the jobs on startup) and continue to listen to changes of the DB if there is new job or if a job changed. It must be fault tolerant meaning that if the app restarts, it should keep all the jobs and restart listening on changes.

**Comment by grapevineai** [comment]
@manast Any suggestion or recommendation?

**Comment by manast** [comment]
I am not sure whats your exactly use-case here, so I do not know what to recommend 👍

**Comment by mistory** [comment]
@grapevineai I encountered the same problem, do you have a good solution

**Comment by manast** [comment]
@mistory what problem did you encounter exactly?

**Comment by grapevineai** [comment]
@mistory I have decided to use warlock (https://www.npmjs.com/package/node-redis-warlock) to lock only one instance to be the producer. You can give the lock a lifetime value so if the machine dies, another can take catch the lock.

**Comment by manast** [comment]
@grapevineai it is funny because according to the warlock's author (https://www.gosquared.com/blog/distributed-locks-using-redis) the lock mechanism he uses is exactly the same as Bull uses.

**Comment by grapevineai** [comment]
@manast yes but unfortunately Bull doesn’t integrate this feature with a timeout which compromises any use for this purpose. If your only producer dies, nothing can be done on Bull side to detect that.

**Comment by manast** [comment]
What do you mean your producer dies? Not sure what scenario is this, normally you control the producers, you add jobs to the queue and then the workers or consumers consumes the jobs. If a worker dies while processing a job then automatically another worker will pick that job up as soon as the lock on that job expires.
