### ISSUE TITLE
Error handling when Redis server disconnects

### ISSUE THREAD

**Issue by nervouscat** [OptimalBits/bull#1877]
Hello all,

I would like to see if there is any way to do error handling if Redis disconnects unexpectedly. I tried to test it with the event handlers, as well as try/catch, but none have worked... the only method that came close was to add 

**maxRetriesPerRequest: 0,
  enableReadyCheck: false**

```
const testQueue = new Queue('testJob',{redis: {port: REDIS_PORT, host: REDIS_HOST, password: REDIS_PASS, maxRetriesPerRequest: 0,
  enableReadyCheck: false}});
```

But was too slow in terms of getting the result with the below scenario:

```
async  redisTest(req, res) {
  try{
  counter +=1;
  const body =req.body;
  body.counter = counter;
  try{
    console.log('RUN JOB');
    var addOrchJob = await testQueue.add({ jobData: body});
    }
    catch(e){
      console.log(e);
      console.log(body);
    }
  res.send(true);
  }
  catch(e){
    console.log("HELLO",body);
    res.send(true);
  }
}
```

is there a way that i can check the redis connection swiftly in order to process the incoming data without the queue during disconnection?

Thank you in advance!

**Comment by manast** [comment]
You should be able to use the "error" event, so for example:
```js
testQueue.on('error', (err) => console.log(err));
```
