### ISSUE TITLE
seperate processes structure not working

### ISSUE THREAD

**Issue by ionush** [OptimalBits/bull#1878]
## Description

Not sure why the seperate processes design doesn't work with me. Help would be appreciated

```
import Bull from 'bull';

const emailQueue = new Bull('email-queue');

emailQueue.process(async (job) => {
...
});
```
this doesn't work
```
emailQueue.process('email processor', 1, __dirname + '/Email.ts');
```
I have tried with email.js/email.ts, doesn't seem to work. Without __dirname and processor file is not found

## Bull version
"bull": "^3.18.0"

**Comment by ionush** [comment]
updated comment to reflect another issue

**Comment by manast** [comment]
you should use plain javascript as your processor files.

**Comment by ionush** [comment]
I wrote above I tried that already. For clarity, here is the code:

```
require('dotenv').config();

module.exports = async function (job) {
  console.log('job');
  return 'complete';
}

**Comment by manast** [comment]
when you say "it does not work", what do you mean exactly?
Here there are some passing tests that you can use as the base to build your code:
https://github.com/OptimalBits/bull/blob/develop/test/test_sandboxed_process.js
