### ISSUE TITLE
Bug Report: Repeatable jobs first run very inconsistent when using every

### ISSUE THREAD

**Issue by jadkins89** [OptimalBits/bull#1881]
## Description
Repeatable jobs using `every` are scheduled much earlier than they are supposed to be on their initial run. The larger `every` is, the greater potential for a large discrepancy. 

The bug stems from [repeatable.js](https://github.com/OptimalBits/bull/blob/develop/lib/repeatable.js). `getNextMillis` does the following when `every` is a property of `opts`.
```javascript
if (opts.every) {
  return Math.floor(millis / opts.every) * opts.every + opts.every;
}
```
In our use cases we sometimes have `every` be 30+ days. `Math.floor` has the potential to cut off large chunks of that time. In a number of cases recently, jobs that were scheduled to repeat every 30 days, had their first run after only a few hours.

## Minimal, Working Test code to reproduce the issue.
This is completely variable to the current value of `Date.now()`. So lets assume `Date.now() = 1601671405052`. 

```javascript
const myJob = await queue.add({
  { foo: 'bar' },
  repeat: {
    every: 2592000000
  }
});

/*  
    {
       ...
       "delay": 184594948,
       "timestamp": 1601671405052,
       "prevMillis": 1601856000000
       ...
    }
*/
```

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
The delay for the job ran will come 240745052 ms early, or roughly 28 days early. Could this be simply fixed by adjusting the code to: 
```javascript
if (opts.every) {
  return millis + opts.every;
}
```
## Bull version
3.18.0
## Additional information
This appears to have been introduced fixing another [bug](https://github.com/OptimalBits/bull/commit/927550feb106adf98694cf65ccbeeb4b496c13a4#diff-d3883ab2d556ac46c7e74f083c2419dd).

**Comment by manast** [comment]
yes. The thing here is that repeatable jobs do not work as many people expect. The repetitions must happen at fixed points in time, the reason for it is so that we avoid duplicated jobs, since the repetition "slot" will get a determined jobId and there cannot be two identical jobIds in bull.
Anyway, I will revisit this once again to see if it is possible to use the startDate option as an anchor for all the repetitions.

**Comment by jadkins89** [comment]
@manast Thank you for the reply. Is there a work around that could more accurately schedule repeat jobs or should I consider using cron strings instead? So if I'm understanding correctly, duplicate repeat jobs of the same frequency were being created previously because there weren't any defined "slots" (some range between a multiple of the `every` prop)?

**Comment by manast** [comment]
a cron expression may work better for your use case, you can check which is the current month day, X, and then say you want to repeat every X day, you can try something like this:
"0 0 0 6 * *" At 12:00 AM, on day 6 of the month (https://crontab.cronhub.io/)
You can use ```Queue#getRepeatableJobs``` and then inspect the "next" field of the repeatable job to check the next iteration is correct.

**Comment by jadkins89** [comment]
Yeah, it works for certain situations where I want to set up a repeating job weekly / monthly but converting jobs that occur every 2 or 5 days for instance is not possible to get just right. Would something like this solve the duplicate issue? I obviously don't have a feel for your entire code base but would like to help resolve this.
```javascript
    if (opts.every) {
      let anchor = millis;
      if (opts.startDate) {
        anchor = new Date(opts.startDate).getTime();
        if (anchor < millis) {
          anchor = anchor + Math.floor((millis - anchor) / opt.every) * opts.every;
        }
      } else if (!opts.startDate) {
        anchor = Math.floor(anchor / opts.every) * opts.every;
      }
      return anchor + opts.every;
    }
```

**Comment by Zikoel** [comment]
> yes. The thing here is that repeatable jobs do not work as many people expect. The repetitions must happen at fixed points in time, the reason for it is so that we avoid duplicated jobs, since the repetition "slot" will get a determined jobId and there cannot be two identical jobIds in bull.

If I understand well the job id is related to the repeat value? Why not find another way to create a deterministic id and why we need a deterministic id ?

**Comment by manast** [comment]
@Zikoel because we want to avoid duplicated jobs for a given repetition, there could be hundreds of workers concurrently and this is a mechanism that avoids duplication... I am open for solutions that are better than this if anyone can come up with one.

**Comment by tsebas** [comment]
@manast I understand having a single job per repetition. However, you don't guarantee that a single spawned job is running, correct? I.e., if I setup the job to repeat every 5 seconds, and each job takes 6 seconds to run, before the first job finished a second job will start. Unless I'm mistaken, this is the behaviour I'm seeing.

Is there a way of actually guaranteeing that only a single job runs at once? Or in other words, that even though it is supposed to repeat every 5 seconds, because these is a job running, it waits for it to finish?

**Comment by manast** [comment]
@tsebas no, that would be a new functionality, like non-overlapping jobs. Implementation is quite straightforward, instead of adding the next repetition when the job starts you add it when it completes/fails.
