### ISSUE TITLE
Polluting redis `keys *` with repeatable cron jobs

### ISSUE THREAD

**Issue by malisetti** [OptimalBits/bull#1885]
## Description
Adding a job like the below one keeps the hashes like below. These are the completed timestamps.

```
32) "bull:custom-scheduler:repeat:428fe129cbec4a3677104fe532d238eb:1603174800000"
33) "bull:custom-scheduler:repeat:428fe129cbec4a3677104fe532d238eb:1603175520000"
34) "bull:custom-scheduler:repeat:428fe129cbec4a3677104fe532d238eb:1603177200000"
35) "bull:custom-scheduler:repeat:428fe129cbec4a3677104fe532d238eb:1603176960000"
36) "bull:custom-scheduler:repeat:428fe129cbec4a3677104fe532d238eb:1603176360000"
37) "bull:custom-scheduler:repeat:428fe129cbec4a3677104fe532d238eb:1603176720000"
38) "bull:custom-scheduler:repeat:428fe129cbec4a3677104fe532d238eb:1603178640000"
39) "bull:custom-scheduler:repeat:428fe129cbec4a3677104fe532d238eb:1603177080000"
40) "bull:custom-scheduler:repeat:428fe129cbec4a3677104fe532d238eb:1603175160000"
```

## Minimal, Working Test code to reproduce the issue.
Add a job like below
```
await customSchedulerQueue.add(null, {
        jobId: 'csq',
        removeOnComplete: true,
        timeout: 10000,
        repeat: { cron: '*/2 * * * *' },
    });
```
## Bull version
latest

## Additional information
How to tell bull to remove these ?

**Comment by manast** [comment]
It is working, example:
```js
'use strict';

const Queue = require('bull');

const queue = new Queue('repeater');

queue.process(async function(job) {
  console.log('processing at', new Date(), job.id);
});

queue.add(
  { job: 'data' },
  { jobId: 'test', removeOnComplete: true, repeat: { cron: '*/3 * * * * *' } }
);
```

Gives:
![image](https://user-images.githubusercontent.com/95200/96563547-5a210180-12c2-11eb-9963-7ea8d28b8499.png)

**Comment by malisetti** [comment]
If we don't have `timeout` in job options and if the queue.process takes more time like 30seconds then we will have lot of keys in redis as mentioned.

**Comment by manast** [comment]
can you publish a test case as mine above that reproduces it?

**Comment by malisetti** [comment]
it works as expected. thanks. when we dont have removeOnComplete what happens to those keys in redis ?

**Comment by malisetti** [comment]
```
'use strict';

const Queue = require('bull');

const queue = new Queue('repeater');

queue.process(async function(job) {
setTimeout(() => {
        console.log('processing at', new Date(), job.id);
            done(new Error('error from eq'));
        }, 50000);
});

queue.add(
  { job: 'data' },
  { jobId: 'test', removeOnComplete: true, repeat: { cron: '*/2 * * * * *' } }
);
```

this is leaving bull:repeater:repeat:* hashes in redis.

**Comment by manast** [comment]
yes, but the jobs are failing since you are calling "done" which is not defined...

**Comment by manast** [comment]
put "removeOnFail" option if you want to get rid of the failed jobs too, although I recommend to keep them so that you can debug why they failed.

**Comment by malisetti** [comment]
added `done` to callback of process.

**Comment by manast** [comment]
ok, but since repeatable jobs have a higher frequency than the time it takes to process them they are just being queued up. So you need to have a worker that is faster than the frequency if you do not want this to happen.
