### ISSUE TITLE
Suggestions for horizontal scaling

### ISSUE THREAD

**Issue by Guidanz-Kishore** [OptimalBits/bull#1886]
## Description
I have a queue that needs to be process using sandboxing. The job is more of CPU oriented that uses Puppeteer/headless browser to take screenshots. So, each job takes about a minute to get over. I need to know how sandboxed processors work since I am not getting enough examples. My question is if we are going for sandboxed approach, do we need to fork the process separately inorder to create different process or bull will take care of the scaling work? Using the below code, i am trying to process the job. I want this jobReceiver.js to scale horizontally. As of now, i am running it only once. Do i need to manually run jobReceiver.js as many times as i want? or I would like to know whether i am using sandboxing feature in a proper manner. Please correct me if i am wrong. Thanks in advance. Let me know if you require any addition info regarding this. 
## Minimal, Working Test code to reproduce the issue.
jobReceiver.js
```js
const receiverQueue = new Queue('reportQueue', config.REDIS_SERVER_URL);
const processGenerateQueue = (job) => {
	return new Promise((resolve, reject) => {
		log.info('-------------------Job received for generate funtion---------------', job.data);
		const { authorization, url } = job.data.data;
		const header = {
			Accept           : 'application/json',
			'Content-Type'   : 'application/json',
			'Accept-Encoding': 'gzip',
			authorization    : authorization
		};
		axios({
			method : 'get',
			url    : url,
			headers: header,
		}).then((result) => {
			resolve(result.data.data);
		}).catch((error) => {
			reject(error);
		});
	});
};

receiverQueue.process('generate', 3, processGenerateQueue);
```

## Bull version
6.0.6

**Comment by manast** [comment]
The example above is not for sandoxed processors, you need to put your processor inside a separate .js file as described in the documentation. The concurrency factor will determine how many separate node processes bull will spawn to process the jobs.
You can of course scale horizontally by adding more workers in different machines, and so on.

**Comment by Guidanz-Kishore** [comment]
> The example above is not for sandoxed processors, you need to put your processor inside a separate .js file as described in the documentation. The concurrency factor will determine how many separate node processes bull will spawn to process the jobs.
> You can of course scale horizontally by adding more workers in different machines, and so on.

Wow. That was fast. Thank you so much for the reply @manast. Will check it out.
