### ISSUE TITLE
Move job to active state

### ISSUE THREAD

**Issue by mayuuh** [OptimalBits/bull#1887]
Is there any way we can move any job to Active state?

I want to manually move job to active state.

**Comment by manast** [comment]
You can only move the jobs to the active state that are in the tip of the queue.

**Comment by mayuuh** [comment]
I am trying to update status of that job manually.

Example:
I am calling external API in my process function. But not waiting for it to complete.
I have created another API where my job will update the status.

Like right now I am using two methods.
moveToCompleted and moveToFailed

But until I update status it should be in active status. 

So is there any way?

```
newQueue.process('*', function (job, jobDone) {
                    try {
                        //external API call
                        jobDone(null, "Job Executed");
                    }
}
```

**Comment by manast** [comment]
I am not sure I understand you use case, but you should not ignore the result of the asynchronous api call.

**Comment by mayuuh** [comment]
Is there any method like moveToActive?
