### ISSUE TITLE
Inconsistency in job removal from the bull queue 

### ISSUE THREAD

**Issue by Guidanz-Kishore** [OptimalBits/bull#1888]
## Description
Hi. I am trying to remove a repeatable job from my queue. But often, the scheduled job is not getting removed from the queue even after calling job.remove( ). I would like to know whether i am making any mistakes in removing the repeatable job because if failure to remove the jobs always happens, i can understand that there is some issue with my code. But, the failure case is so inconsistent. I have read in the documentation that we can use removeRepeatable(). But i just wanted to know what mistake i am making in this and the reason for the inconsistency. Thanks in advance
#### (An easy to reproduce test case will dramatically decrease the resolution time.)
```js
const removeRepeatable = (jobId) => {
	return new Promise(async(resolve, reject) => {
		try {
			const jobs = await reportQueue.getJobs();
			const job = jobs.find(element => {
				if (element !== null && element.opts.repeat?.jobId === jobId) {
					return element;
				}
			});
			if (job === null || job === undefined || job.length === 0) {
				log.info(`------------Report with jobId= ${jobId} is not scheduled yet.---------`);
			} else {
				log.info(`------------Schdule removed for jobId=${jobId}------------`);
				await job.remove();
			}
			resolve(true);
		} catch (error) {
			log.error('queueAdd---------removeRepeatable()---------------Error in removeRepeatable()------', error);
			reject(error);
		}
	});
};
```
## Bull version
6.0.8

**Comment by manast** [comment]
You must use either ```removeRepeatable``` or ```removeRepeatableByKey```, thats the only way to correctly remove a repeatable job: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueremoverepeatable
You may need to use this function to get all the repeatable jobs: ```Queue#getRepeatableJobs```

**Comment by Guidanz-Kishore** [comment]
Sure. Thank you so much for the reply. Will check it out.
