### ISSUE TITLE
Any reason why takeLock() / releaseLock() is not part of bull documentation?

### ISSUE THREAD

**Issue by jmargieh** [OptimalBits/bull#1889]

**Comment by manast** [comment]
Because they are private methods.

**Comment by jmargieh** [comment]
@manast Thanks for the quick answer.
So If I'm running multiple nodeJS instances and I'd like to be certain that only one worker and no other queue worker can process it, how do I do that?

Thanks in advance.

**Comment by manast** [comment]
@jmargieh that is handled automatically by the library. Every worker will lock the job and keep it locked until it completes (or fails).

**Comment by jmargieh** [comment]
Great, thank you so much!
