### ISSUE TITLE
Queue#add timeout option not failing a timed-out job

### ISSUE THREAD

**Issue by stevenjmarsh** [OptimalBits/bull#1895]
## Description

I am using bull to manage handling requests for image processing. The processes are CPU intensive, and can take up to several minutes to complete.

In some cases the process may crash, and is not able to call `done()` or throw an error. When this happens, I need the job to timeout, and have the state set to 'failed', so that I can do some clean up and keep the queue clean. The job should not be run again or reattempted.

I have set the job timeout option, but the crashed jobs do not timeout.

QUESTION:

> If timeout is set, do other queue settings such as 'lockDuration' or 'stalledInterval' effect whether the timeout occurs or not?

> Or, maybe a better way to ask, what minimal / basic settings need to be set to have a crashed job timeout and be shown as failed in the queue?
 
If there is different / better pattern I should be following, feel free to point that out as well.

## Minimal, Working Test code to reproduce the issue.

My code is based on the [Heroku backgrounds job example](https://devcenter.heroku.com/articles/node-redis-workers).

I set up the queue with the following options...
```
  const workQueue = new Queue("work", REDIS_URL, {
    settings: {
      lockDuration: 5 * 60 * 1000,   // lock for 5 minutes, prevent other workers from starting on it
      stalledInterval: 0,            // do not check for stalled jobs
    },
  });
```

I set the job timeout...
```
const job = await workQueue.add({ imageUrl }, { timeout: 4 * 60 * 1000 });
```

Note, I am using [throng v4.0.0](https://github.com/hunterloftis/throng) for the worker processes.

## Bull version

* bull v3.18.00

## Additional information

Thanks for providing the bull package. It is a very useful and effective package. It was really quite easy to get background processing up and running.

**Comment by manast** [comment]
I do not recommend you to modify the standard values for lock duration and stalled interval. If a job crashes, it will not be able to renew the lock and bull will consider the job stalled and move that job back to the wait list or fail it if has already stalled more than maxStalledCount (defaults to 1). So in your case just configure maxStalledCount to 0 and the job will fail instead. Btw, if your worker is very CPU intensive it may stall also since node event loop will not get a chance to run and the lock will not renew, to avoid that either use a sandboxed processor or divide the processing of the work in very small job increments.

**Comment by stevenjmarsh** [comment]
Thanks @manast , I will try those adjustments and let you know if that worked. And thanks for the fast response.

**Comment by stevenjmarsh** [comment]
setting maxStalledCount to 0 and not setting any value for stalledInterval worked, thanks!

I did need to increase the lockDuration (to 5 minutes), as my job looked as if it was timing out (even with the job timeout set  to 5 minutes).

**Comment by stevenjmarsh** [comment]
That worked, I am closing the issue. Thanks!

Steven Marsh
https://www.linkedin.com/in/stevenjmarsh
sjm.atl@gmail.com
678-361-6311
