### ISSUE TITLE
Repeatable jobs very miliseconds is incorrect time

### ISSUE THREAD

**Issue by tructhienbui** [OptimalBits/bull#1896]
Let say i have a job with schedule every 5 minutes, this will means that the job will run at 0/10/15/20/25... every hour.
Let say if current time is 05:23 AM, then i add a job with schedule above, then it will executed at 05:25 AM not 05:28 AM as expected.

**Comment by manast** [comment]
This has been discussed many times before. It works as designed, we cannot have a distributed repeatable job at an arbitrary time. Time is divided in slots and only at that slots the jobs will be executed.
