### ISSUE TITLE
`completed` and `failed` should be zsets, not sets

### ISSUE THREAD

**Issue by evanhuang8** [OptimalBits/bull#190]
What's the reasoning for using sets instead of lists for `completed` and `failed` jobs? By using sets for the two categories, it will not be safe or optimal to fetch jobs from the two, especially for management purposes. As of now, `getCompleted` and `getFailed` will result in the whole set being fetched, which can potentially result in slow performance and even crash the queue if the sets are too big. 

By using `clean`, I suppose the two sets can be kept in reasonable size, but there are use cases where jobs should be kept in the queue indefinitely, for records or other purposes. As far as I know, we are not doing any set operations on the two, so why don't we just use lists instead?

**Comment by manast** [comment]
The rationale was that it was much faster to check if a job had failed or completed by having them on sets. I do not remember anymore why I did it like this. This is an old (and probably wrong) design decision that maybe does not hold anymore. We can just save the state on the job itself and that would be even faster.

**Comment by evanhuang8** [comment]
I see, I think it's still necessary to keep them in a set then. Thinking more about searching/monitoring, it might be good to maintain a list along side with the set?

**Comment by manast** [comment]
I think the best solution is to keep the elements in a ZSET instead with the jobId or the timestamp as score. Then we get the best of two worlds. We can check in O(1) if a job is in a given set, and we can also return the elements in ranges to support pagination, etc.
