### ISSUE TITLE
Know when job is completed (Node.js, Express, Bull, Heroku)

### ISSUE THREAD

**Issue by AustinHatem** [OptimalBits/bull#1901]
I have a node server that has a convert to Mp4 feature. This process could take awhile ~20-30 seconds so im using Bull to manage this process.

I am confused on how to tell my frontend that the process is completed. My Express code looks like this:

```
router.post('/downloadMp4', async (req, res) => {
let job = await mp4Queue.add({data:req.body.data});

mp4Queue.on('global:completed', function(job, result) {
    res.json({ id: job.id, downloadPath: result });
});
```
The job will get called and the process will finish but since it takes longer than 30 seconds, heroku will time out this api call. So how can I know when the process is finished if this api call keeps timing out? Is there something I'm missing?

**Comment by manast** [comment]
The idea of using a queue for long tasks is that you post the task and then return immediately. I guess you are updating the database as last step in your job, and only use the completed event for notifying the clients. What you need to do in this case is to implement either a websocket or similar realtime communication and push the notification to relevant clients. This can become complicated so you can save some time with a solution like https://pusher.com/ or similar...

**Comment by AustinHatem** [comment]
Ok makes sense, thank you! So to make sure I understand basically I'm just going to give the job to the queue -> respond to the user -> let the queue perform the task then post the completion to a database -> push the notification of completion to relevant clients?

Thanks again so much, I'm kind of new to queues.

**Comment by manast** [comment]
@AustinHatem yeah you got it.
