### ISSUE TITLE
Do we really need to use done()

### ISSUE THREAD

**Issue by pgonzaleznetwork** [OptimalBits/bull#1902]
## Description

The official docs state that we must use done() to signal that a job has completed. However, my app does NOT use done() and instead uses async await and simply returns a value when the job is done, for example

## Minimal, Working Test code to reproduce the issue.

```
workQueue.process(maxJobsPerWorker, async (job) => {

    let {jobType} = job.data;

    let result = '';

    switch(jobType) {
        case 'LIST_METADATA':
          result = await jobs.listMetadataJob(job);
            break;
        case 'DEPENDENCIES':
          result = await jobs.dependencyJob(job);
            break;
        case 'USAGE':
          result = await jobs.usageJob(job);
            break;
    }

    // A job can return values that will be stored in Redis as JSON
    return result;
  });
```

This works 100% of the time and it is the example provided by Heroku as well https://github.com/heroku-examples/node-workers-example/blob/main/worker.js

## Question

Is this a supported way of completing a job?

**Comment by manast** [comment]
It does not say you MUST use done, you can use it but it is easier/better to return a promise.

**Comment by oded-regev** [comment]
Hi @pgonzaleznetwork , I noticed that when `done()` is not called, redis gets polluted with keys (bull generates a key per job which never gets clean..). see https://github.com/OptimalBits/bull/issues/261

**Comment by manast** [comment]
@oded-regev that issue is very old and there are ways to remove jobs after completion/failure, please check the documentation. And calling "done" is definetely not needed, just make sure you return a valid promise.

**Comment by oded-regev** [comment]
thank you @manast, for some reason my redis is full with keys of type: `bull:pathways_full_import_production:1189` (something like 10k keys). I don't understand why they were not clean.. do you have any idea how I should have handle it properly?
