### ISSUE TITLE
finished function race condition

### ISSUE THREAD

**Issue by Heartz66** [OptimalBits/bull#1906]
```
var serverId = '6fe48ab4-cc0c-42a5-91af-917202574cf3';

var jobData = {
    serverId: serverId
};

var jobOptions = {
    jobId: serverId,
    removeOnComplete: true,
    removeOnFail: true
};

queue.getQueue('example-queue').add(jobData, jobOptions)
    .then((job) => {
        return job.finished();
    })
    .then(() => {
        console.log('Job completed!');
    });

queue.getQueue('example-queue').process((job) => {
    return new Promise((resolve, reject) => {
        return resolve();
    });
});
```

The code above could result in a race condition because the `finished` function will register events to detect completion/failure of a job once the `finished` function is triggered. Since the job won't enter the `completed` or `failed` state (due to `removeOnComplete` set to `true`), the script to obtain the state of the job will not do anything. If the job is completed before the events to listen to the completion/failure state are initialized, the `finished` function will never resolve.

A way to solve this is by informing the `add` function of the queue to register the `global`/`failed` events before sending the job to the Redis server somehow.

I understand this can easily be solved by setting the `removeOnComplete` variable to a positive integer, but I need the `jobId` to avoid duplicates inside the queue (and allow people to add items to the queue with the same `jobId` once completed/failed) so this won't be an option for me.

https://github.com/OptimalBits/bull/blob/71df921351bb65ea2cf019e7d9a1095d8e6314ff/lib/job.js#L444

**Comment by mattcollier** [comment]
This is with bull@3.19.0 released earlier today.

Here is a minimal example that will fail in short order:  https://gist.github.com/mattcollier/3f78a3e108f29650ad2c3e97885c2cee

**Comment by manast** [comment]
This could be a bug that has been fixed already since as far as I can tell, the completed/failed event are published regardless of the settings in removeOnComplete/Fail.
Create a new issue if this is not the case with code that demonstrates the issue.
