### ISSUE TITLE
Local Queue.pause on a queue with multiple named .process handlers does not wait for tasks to complete

### ISSUE THREAD

**Issue by jasrusable** [OptimalBits/bull#1907]
##  Description
Issuing a local pause (`queue.pause(true)`) on a queue with multiple named `.process` handlers does not wait for tasks to complete as expected as per the documentation:
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queuepause
`If doNotWaitActive is true, pause will not wait for any active jobs to finish before resolving. Otherwise, pause will wait for active jobs to finish. See Queue#whenCurrentJobsFinished for more information.`

## Minimal, Working Test code to reproduce the issue.
```
import Queue from "bull";

const queue = new Queue("my-queue");

queue.process("a", async (job, done) => {
  console.log("starting to process task");
  await new Promise((resolve) => {
    setTimeout(() => {
      console.log("processing task complete");
      resolve();
    }, 5000);
  });
  done();
});

queue.process("b", async (job, done) => {
  console.log("starting to process task");
  await new Promise((resolve) => {
    setTimeout(() => {
      console.log("processing task complete");
      resolve();
    }, 5000);
  });
  done();
});

process.on("SIGINT", async () => {
  await queue.pause(true);
  console.log("exiting");
  process.exit(0);
});

queue.add("a", {});
```
The output from the code above is:
```
starting to process task
(Issue ctrl+c)
exiting
```
The _expected_ output from the code above is:
```
starting to process task
(Issue ctrl+c)
processing task complete
exiting
```

## Bull version
3.18.1

**Comment by rosslavery** [comment]
May not be related but I don't believe you should be mixing completion approaches inside your job code. You're calling done and also returning a promise.

No need to call done or even have it as a param if your processor returns a promise.
