### ISSUE TITLE
Delayed Job Never gets called with getNextJob

### ISSUE THREAD

**Issue by lukepolo** [OptimalBits/bull#1908]
# Description
I am using `getNextJob` and it never picks up the delayed job.

![image](https://user-images.githubusercontent.com/2066668/99606602-13651b00-29d8-11eb-9fce-c21d93a0f6b6.png)

## Minimal, Working Test code to reproduce the issue.

```js
const Redis = require('ioredis');
const BullClient = require('bull');

const redisOptions = {
  db: 0,
  prefix: '{qumulex}',
  port: 6379,
  host: 'localhost',
};

let redisConnection;
const bullOptions = {
  createClient: type => {
    try {
      switch (type) {
        case 'bclient':
          return new Redis(redisOptions);
        default:
          if (!redisConnection) {
            redisConnection = new Redis(redisOptions);
          }
          return redisConnection;
      }
    } catch (error) {
      logger.error('Unable to connect to redis', error.message);
      throw error;
    }
  },
};

const queue = new BullClient('cloud', bullOptions);

async function start() {
  await queue.add(
    {},
    {
      // "attempts": 1,
      delay: 1000,
      // "timeout": 20000,
      // "jobId": "gateway-place",
    },
  );

  async function getNextJob() {
    const job = await queue.getNextJob();
    console.info(`JOB:`, job);

    await getNextJob();
  }
  await getNextJob();
}

start();

```

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
Run `node test` , you should it never picks up the delayed job.

Use the Bull Dashboard to help see delayed not being processed. 

## Bull version
3.11.0

## Additional information
I also have the same problem when I do a rate limiter (once it gets to the delayed queue it never pops to the active queue)

*UPDATE* : i found that using `queue.process` does seem to work, but I had to remove `createClient` function to make it work. Not sure why that is. 

Let me know what else I can do help you

**Comment by lukepolo** [comment]
Making this ticket active, I can re-test with the newest versions.

**Comment by manast** [comment]
@lukepolo there are big changes the issue is still there but please confirm and if so I can take a look at it.
