### ISSUE TITLE
Suggestion - default removeOnComplete to true

### ISSUE THREAD

**Issue by bennyKY** [OptimalBits/bull#1909]
Hi, we had a huge problem in our production systems that our Redis exploded because it was full with completed messages.
Yes, the fact that messages stays in the Redis after being processed exists in the documentation somewhere. But someone can miss it (like we did) and then the Redis was full and messages were sent and our production crushed :(.

Therefore, my suggestion is to set `removeOnComplete` to true be default.

**Comment by manast** [comment]
I am afraid that is not possible at this point since it would be a breaking change that could also be missed by current users and delete data they are counting on. What we can do it document it better if current documentation is not explicit enough about it.

**Comment by fib-at-isobar** [comment]
Hello @manast,
we've run into the exactly same issue.
Could you maybe create a separate section in the docs regarding this? To show few strategies maybe with code examples?

Currently I've changed the queue following:
```
  const workQueue = new Queue('work', process.env.REDIS_URL, {
    prefix: '{myQueue}',
    defaultJobOptions: {
      removeOnComplete: removeOnComplete, // = 50000
      removeOnFail: removeOnFail, // = 3000
      stackTraceLimit: stackTraceLimit // = 30
    }
  });
```
But I can see over 60K jobs in the Queue - is this to be expected?

**Comment by rosslavery** [comment]
We simply have a scheduled job that runs daily that purges completed jobs older than a certain number of days.

**Comment by fib-at-isobar** [comment]
Hello @rosslavery,
but this is something you've set up yourselves (but a good one!). I was thinking about inbuilt solutions :)

**Comment by manast** [comment]
@fib-at-isobar if the setting is indeed ```removeOnComplete = 50000``` then no more than 50k jobs will be kept in the queue. If you see more then the setting has probably the wrong value.

**Comment by fib-at-isobar** [comment]
Hello @manast,
Thanks for the explanation, but it does not seem to work for us. I've hardcoded the values and it still keeps all values in the Redis.
Code is as in my previous comment, but values are hardcoded. bull@3.20.0

**Comment by manast** [comment]
@fib-at-isobar write a simple test case that demonstrates the issue and I can take a look at it.

**Comment by sn00pyd0g3** [comment]
It is strongly recommended to remind users of the settings in the document.

**Comment by manast** [comment]
Closing this since the issue as it is suggest will not be fixed.

**Comment by fib-at-isobar** [comment]
Hello,
we've managed to find the issue. I haven't realised that I put the job options on the side of worker (`queue.process`). It must be used on the insertion into the queue (so `queue.add()`). Hope it helps somebody!

**Comment by cleytonb** [comment]
Hi,

I just got the same problem in my production server affecting several systems of my company.  And still, when I look at the documentation I can't see a BIG WARNING about this. (which seems to be absolutely necessary)...
