### ISSUE TITLE
Configuration defect

### ISSUE THREAD

**Issue by wdh-1025** [OptimalBits/bull#1916]
defaultJobOptions overrides the opts of Queue.prototype.add

``` code
Queue.prototype.add = function(name, data, opts) {
  if (typeof name !== 'string') {
    opts = data;
    data = name;
    name = Job.DEFAULT_JOB_NAME;
  }
  opts = { ...opts, ...this.defaultJobOptions };

  opts.jobId = jobIdForGroup(this.limiter, opts, data);

  if (opts.repeat) {
    return this.isReady().then(() => {
      return this.nextRepeatableJob(name, data, opts, true);
    });
  } else {
    return Job.create(this, name, data, opts);
  }
};
```

**Comment by swayam18** [comment]
There is a PR to fix this here: https://github.com/OptimalBits/bull/issues/1904

You can use bull 3.15.x for now as a temporary workaround

**Comment by mathewcst** [comment]
Is there and update on this?

I'm using v3.20.0 and this `await Queue.add('myCustomQueue',{id: 1,},{repeat: { every: 10000},})` doesn't work. It don't get the job custom opts that I'm passing on.
