### ISSUE TITLE
Is it possible to use same handler for different named jobs ?

### ISSUE THREAD

**Issue by zbarinov** [OptimalBits/bull#1919]
I need to implement the following scenario:

```
bull.process('/path/to/worker.js');
//...
bull.add('job_1', payload);
//...
bull.add('job_2', payload);
```

somewhere in the worker:
```
module.exports = async (job) => {
  switch (job.name) {
     case 'job_1':
         return job1Worker();
    case 'job_2':
        return job2Worker();
    default:
       //do nothing
  }
}
```

Is that possible ?
How do I keep just one processor running ? As I can see a different processor is run for each job type added to query, like for `job_1` and `job_2` there will be to running processes.

**Comment by zbarinov** [comment]
@manast thanks for the fast response.
job1Worker and job2Worker are implemented exactly the same as normal worker is implemented:

```
// job2Worker
module.exports = async () => {
  // do async calls with await here
}
```

But in my case. I got 2 `/bull/lib/process/master.js` processes after those 2 jobs handled. And 2 processes keep running. 
If there will be another `bull.add('job3', payload)` call there will be 3 processes running even after job is completed.

Is there anything I do wrong ?

**Comment by manast** [comment]
Impossible to say if you are doing something wrong, I would need a complete example that reproduces the issue.

**Comment by zbarinov** [comment]
Got the problem! I just recognized, that I used `bull.add` in the worker, like

```
// job2Worker
module.exports = async (job) => {
  // do async calls with await here
  bull.add();
}
```

It causes Bull loaded twice in different processes!
And my initial question turned out into: 

Is there any way to add new jobs from processor in this case ?
As I can see better way is to use events, like on `completed` event.

**Comment by zbarinov** [comment]
I have solved this by moving processors to a different module, so that they are not loaded twice.
Thank you!
