### ISSUE TITLE
Horizontal scaling and concurrency

### ISSUE THREAD

**Issue by rimiti** [OptimalBits/bull#1922]
Hello,

> Before everything, thank you for package. 🙏

**Context**

My worker instance is auto-scalable (replica created automatically depending on CPU & Memory usage) to handle lots of jobs to process. For a specific queue we would like to have a concurrency of 100 STRICT processors spread out for all instances.

For example: 
- If there is 1 replica (or node) is running, active jobs (concurrency: 100) should be equal to 100.
- If there are 2 replica (or node) is running, active jobs (concurrency: 100) should be equal to 100 and **NOT 200**.

**Question:**

How can I force bull to ONLY have a concurrency of 100 processors **spread out** on my X nodes instead of 100 by nodes ? 

Thanks a lot,

**Comment by manast** [comment]
That is not possible currently, since every worker's concurrency is independent.

**Comment by rimiti** [comment]
@manast It's what I saw after doing some tests in my infrastructure.

Thank you for your confirmation.
