### ISSUE TITLE
Please provide example in documentation for returning binary data

### ISSUE THREAD

**Issue by jfix** [OptimalBits/bull#1923]
I'm sure what I am trying to do is a common thing, but unfortunately I could not find any indication as to how to solve it via the documentation. I asked my question on StackOverflow (here: https://stackoverflow.com/questions/64837262/how-to-return-a-generated-image-with-bull-js-queue), but have not received a response. Hence this request to add information to the documentation.

My use case is this: I want to create screenshots of parts of a page. For technical reasons, it cannot be done on the client-side, so I need puppeteer on the server.

As I'm running this on Heroku, I have the additional restriction of a quite small timeout window. Heroku recommends therefore to implement a queueing system based on bull.js and use worker processes for longer-running tasks as explained here.

My question is: on the client side, how can I get the generated image? I guess ideally I'd like to be able to make a GET request to my API which would return the image from the job, but I don't know how to pass the image object, or where it would be stored in the meantime. I am not sure that the job's `data` object is meant for this purpose, I'd be grateful for confirmation.

A more complete code example can be found in my original question on StackOverflow, but for the generic question where to store a potentially large binary object for the consumer to retrieve it at some stage, no code seems necessary.

**Comment by manast** [comment]
Currently you cannot store binary data in bull, only JSON objects. The best practice here is to store the image in a different store and only keep metadata in bull.

**Comment by jfix** [comment]
Thanks for the answer. Just for theory's sake: if I encoded the image (or other data) as a base64 string, would that work? Are there any size limitations for object values in Redis?

**Comment by manast** [comment]
I think the limitation is 512Mb, so it will work.
