### ISSUE TITLE
setMaxListeners ignores provided value and uses default 10

### ISSUE THREAD

**Issue by zxxc** [OptimalBits/bull#1924]
## Description
When I applying setMaxListeners on the queue
queue.setMaxListeners(24);
I still see the `(node:39480) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Redis]. Use emitter.setMaxListeners() to increase limit`

## Minimal, Working Test code to reproduce the issue.
queue = new Bull(queueName, { redis, settings: { maxStalledCount: 2 } });
queue.setMaxListeners(24);
Than start 
```
queue.process('A',..)
queue.process('B',..)
queue.process('C',..)
``` 11+ times (I have 24)

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

## Bull version
    "bull": "^3.20.0",
## Additional information

I think the issue is that bull is updating setMaxListeners on queue object but using inside of the code different object to getMaxListeners:
https://github.com/OptimalBits/bull/blob/71df921351bb65ea2cf019e7d9a1095d8e6314ff/lib/utils.js#L31

So warning gets generated after I subscribe 11+ listeners and my value 24 is ignored

**Comment by zxxc** [comment]
My workaround for this issue is to (typescript):
```
(queue as any).client.setMaxListeners((queue as any).client.getMaxListeners() + 24);
```

**Comment by mandaputtra** [comment]
I also get this, Where do you put that code? On start of your app?
