### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by sokolandia** [OptimalBits/bull#1928]
## Description
About 90% of jobs fail before even beginning with the message 
```
'Error: socket hang up\n' +
        '    at ChildProcess.msgHandler (/app/node_modules/bull/lib/process/sandbox.js:25:27)\n' +
        '    at ChildProcess.emit (events.js:203:13)\n' +
        '    at emit (internal/child_process.js:876:12)\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:77:11)',
```
#### (An easy to reproduce test case will dramatically decrease the resolution time.)
```
const queue = new Queue('node-processing', process.env.REDIS_URL);
queue.process(2, path.resolve('dist/node-processing.js'));

# then in my request handler
queue.add({}, {jobId: 'my_unique_id', attempts: 15});
```

And a job will have 15 error messages like this in its job.stacktrace. I tried different concurrencies but after a couple of minutes jobs start to fail at about 90% rate.
## Bull version
"bull": "^3.13.0"

**Comment by Pipo93** [comment]
@sokolandia how did you resolve this issue?

**Comment by dmarczydlo** [comment]
@sokolandia or @Pipo93 any update here? I have the same issue.
