### ISSUE TITLE
Selecting a different database?

### ISSUE THREAD

**Issue by ghost** [OptimalBits/bull#194]
The documentation doesn't say how to select a database that isn't the default one (0 on my system). It seems one just has to pass "DB: n" with the rest of the options, but I had to look at the code to know that; the docs at https://github.com/NodeRedis/node_redis do not say that.

**Comment by KazeNoKoe** [comment]
For those that may come here looking for this, the correct syntax is:

new Queue('queueName', {redis: {host: 'redisHost', port: 'redisPort', DB: numRedisDB}})

**Comment by evanhuang8** [comment]
Yeah the doc needs to be updated
