### ISSUE TITLE
Problem on ioredis inside bull queue

### ISSUE THREAD

**Issue by olivinesguerra** [OptimalBits/bull#1945]
## Description

I tried connecting bull queue on ELASTIC CACHE REDIS on AWS. But it it always sending me the timeout connection error.

But when I tried using ioredis alone it works fine

1. Redis declaration -> this works fine

 const redis = new Redis({
    port: process.env.REDIS_PORT,
    host: process.env.REDIS_HOST
 }); 

2. Bull Queue Declaration -> this does'nt work. I think there is a problem on ioredis inside bull queue. But when I run it on local docker and local redis server inside docker-compose.yml it works fine.

sampleQueue = new Queue(
    'sample-queue', 
    {
      redis: {
        port: process.env.REDIS_PORT, 
        host: process.env.REDIS_HOST,
        connectTimeout: 30000,
        enableReadyCheck: true,
        lazyConnect: true
    }
});

REDIS_PORT and REDIS_HOST is the same value. 

Please help thanks.

****

**Comment by manast** [comment]
The code you are showing looks ok, there must be some issue with either your env variables that are not correct or that you do not have proper permissions to connect to your elasticache instance.

**Comment by olivinesguerra** [comment]
Actually I tested the connection from elasticache using ioredis and it works. And the environment variable on both declaration is the same. But the first one works but the second declaration is not. 

@manast any thoughts?

**Comment by olivinesguerra** [comment]
also why closed? based from the guideline. I checked the simpler implementation and it works and on the bull queue declaration is not. So it seems that there is a problem on the ioredis inside bull?

**Comment by manast** [comment]
@olivinesguerra no, there is no problem with ioredis inside bull sorry... there must be something else in your code environment that is wrong. It is closed because there is nothing more actionable to do here.

**Comment by railsfactory-sivamanikandan** [comment]
@olivinesguerra Facing same issue. Did you found any solution ?

**Comment by manast** [comment]
If you are using the option ```lazyConnect: true``` that may be the issue. For some reason it is not compatible with Bull.

**Comment by chkp-idoma** [comment]
I have to join to @Tinadim request. 
I just spent 3 hours trying to understand why my configuration is not working, I have debugged entire queue.js file :( 
and finally found that the "lazyConnect": true was the issue - preventing me from using the queue.

@manast please add this one to the docs somewhere so other ppl will not need to struggle :)
BTW thanks for this remarkable project.
