### ISSUE TITLE
Rate limiter (BounceBack) is not working as expected

### ISSUE THREAD

**Issue by fr1sk** [OptimalBits/bull#1946]
## Main issue:
I have a simple queue that is responsible for delegating the task from the main API to the microservice. When I use `bounceBack: true` as a rate limiter option, the job is not added to the queue if the limit is already hit.

## Reproduce:
Use those rate limiter options for any queue:
```
  max: 3,
  duration: 10000,
  bounceBack: false,
```
when `bounceBack` is set to false, the job is added to the delay state, which is ok. But when I set `bounceBack` to true, I expect that job will be in the waiting state, but the job is never added.

## Bull version:
3.13.0

## Additional:
Nest version: 6.11.5

**Comment by manast** [comment]
A couple of things, first we would need a complete test case (as code that we can copy/paste and run as is) that reproduces the issue, secondly you should try to reproduce it with the latest version of Bull. Thanks.

**Comment by Drieger** [comment]
I got the same problem. And it seems related to https://github.com/OptimalBits/bull/issues/2082
