### ISSUE TITLE
BRPOPLPUSH ReplyError: READONLY You can't write against a read only replica

### ISSUE THREAD

**Issue by rogereiddir** [OptimalBits/bull#1947]
## Description
i get this error in the logs any one have any ideas

## Bull version
3.20.0
## Additional information

![image](https://user-images.githubusercontent.com/20645030/103593717-e1136c80-4ef6-11eb-8f8a-ab0040ff1197.png)

**Comment by gabegorelick** [comment]
Bull can't use readonly Redis instances. Try connecting to the master Redis instance.

**Comment by rogereiddir** [comment]
i think that's what i'm doing , @gabegorelick  can you give soime code on how to do that using bull

**Comment by gabegorelick** [comment]
The second parameter to the `Queue` constructor is a URL to the Redis instance. Make sure you pass the correct URL. See https://github.com/OptimalBits/bull/blob/06b511a5c376da553236e63f217d12cbfbbaeb97/REFERENCE.md#queue for more info.

**Comment by rogereiddir** [comment]
@gabegorelick  this how set the Queue constructor

 ```
let queue =  new Queue(
      String(id),
      {
        limiter:{
          max:2000,
          duration:10000
        },
        redis:{
          host:'127.0.0.1',
          port:6379
        },
        settings:{
          maxStalledCount:0,
          stalledInterval:0
        }
      }
    )
```

**Comment by huberzeljko** [comment]
Hey @rogereiddir, did you manage to fix this? Got this error (using AWS Elasticache) so I'm trying to figure out what happened (it happened only once in lifetime so I'm not if it was something internal on the AWS that caused it like master being down, or is it some wrong configuration).

**Comment by notsapinho** [comment]
Same error on Contabo VPS.
```

[Server] READONLY You can't write against a read only replica. script: 8f55ae4a3be429c6d38c5d5db3e80edf89197b64, on @user_script:41.
      ├- ReplyError: READONLY You can't write against a read only replica. script: 8f55ae4a3be429c6d38c5d5db3e80edf89197b64, on @user_script:41.
      ├-     at parseError (/app/apps/server/node_modules/redis-parser/lib/parser.js:179:12)
      ├-     at parseType (/app/apps/server/node_modules/redis-parser/lib/parser.js:302:14)
      └- ExceptionsHandler

```

**Comment by minhnhat-dev** [comment]
I got same issue on EC2 instance use bull library @nestjs/bull handle multithread, please help me

**Comment by Lasang3012** [comment]
> I got same issue on EC2 instance use bull library @nestjs/bull handle multithread, please help me :(
> 
> [Server] READONLY You can't write against a read only replica. script: 8f55ae4a3be429c6d38c5d5db3e80edf89197b64, on @user_script:41. ├- ReplyError: READONLY You can't write against a read only replica. script: 8f55ae4a3be429c6d38c5d5db3e80edf89197b64, on @user_script:41. ├- at parseError (/app/apps/server/node_modules/redis-parser/lib/parser.js:179:12) ├- at parseType (/app/apps/server/node_modules/redis-parser/lib/parser.js:302:14) └- ExceptionsHandler

Are you solved this problem? I also got same issue :(

**Comment by minhnhat-dev** [comment]
@all I've already resolve this problem, We can exec into container running redis or into redis cli and set `CONFIG SET "slave-read-only" "no"`
- Issue detail: https://stackoverflow.com/questions/58132649/how-to-make-redis-slave-read-only-in-redis-v2-4-6?fbclid=IwAR3XXuJmiaBw2GsQCj0Fr_ayrOT0LeCg5UFJpxgNTD87875C1O764LxFTIQ

**Comment by fr13nd230** [comment]
@ALL how can we force it though to be always a master because I am facing same issue with BullMQ!

**Comment by manast** [comment]
@fr13nd230 normally you choose to what node connect to when creating your IORedis instance.
