### ISSUE TITLE
How do I retrieve a queue created in another file to add a job? (Without polluting global namespace)

### ISSUE THREAD

**Issue by stephanoparaskeva** [OptimalBits/bull#1949]
### Incorrect:
```ts
const queue = new Queue('PAYMENTS_QUEUE', { connection: { host: 'localhost', port: 6379 } });
export default queue
```

### Desired
```ts
(() => {
  new Queue('PAYMENTS_QUEUE', { connection: { host: 'localhost', port: 6379 } });
})()

(() => {
  const queue = getQueue(PAYMENTS_QUEUE)
  queue.add('MAKE_PAYMENT', { to: 1 })
})()
```

**Comment by manast** [comment]
I am not sure what your issue is, you just use the same name of the queue that you want to refer to.

**Comment by gabegorelick** [comment]
Is the issue that instantiating a queue object has side effects (like creating connections to Redis) so you don't want that to happen when the module is imported? 

The way I've dealt with that in the past is with something like this:
```js
let queue;

module.exports = () => {
  if (!queue) {  queue = new Queue(); }
  return queue;
};
```

Then you're not polluting the global namespace, just your module-local one.
