### ISSUE TITLE
Atomic?

### ISSUE THREAD

**Issue by blacksonic** [OptimalBits/bull#195]
What are the pros cons compared to kue? We are using kue but has a lot of problem when a server restarts during job executions. It leaves us in a broken state, jobs stuck.

**Comment by evanhuang8** [comment]
I recently switched from `kue` to `bull`, and I have been having a good experience. `bull` is designed with atomicity in mind, and the key operations such as fetching job to process and promote jobs are done via commands like `brpoplpush` and LUA scripts to ensure such. 

As for jobs stuck, I believe `bull` handles it well, check out the `processStalledJob` method in the `queue.js`, and there are tests against it as well.

**Comment by blacksonic** [comment]
Thanks we will give it a try
