### ISSUE TITLE
How to reuse the connection in a processor file?

### ISSUE THREAD

**Issue by niksmac** [OptimalBits/bull#1955]
## Description

Inside my processor file I want to run a `scanStream` and delete multiple keys from the same server, where bull is running. Is there a connection variable I can reuse in the processor? 

## Minimal, Working Test code to reproduce the issue.

```javascript 
let Redis = require('ioredis')
const redis = new Redis(process.env.REDIS_CONN)

module.exports = function(args, done) {
    let stream = redis.scanStream({
        match: args.data.keyPattern
    })
    stream.on('data', function(keys) {
        if (keys.length) {
            let pipeline = redis.pipeline()
            keys.forEach(function(key) {
                pipeline.unlink(key)
            })
            pipeline.exec()
        }
    })
    stream.on('end', function() {
        done()
    })
}
``` 

This is what I tried. Is it possible to get rid of ioredis and do this `scanStream`

## Bull version
3.20.0

**Comment by gielow** [comment]
Hi,

If I understood your question correctly you want a factory for the client.
Mind that in my example I'm using processors.
```
const client = new Redis(cachehost);
const subscriber = new Redis(cachehost);
const bclient = new Redis(cachehost);

const queue = new Queue(
    value.id,
    {
      createClient: function (type) {
        switch (type) {
          case 'client':
            return client;
          case 'subscriber':
            return subscriber;
          case 'bclient':
            return bclient;
          default:
            throw new Error('Unexpected connection type: ', type);
        }
      },
      defaultJobOptions: {
        removeOnComplete: true,
        removeOnFail: true,
      },
      prefix: value.id
    }
  );
```

**Comment by vinioliveira** [comment]
@gielow  I got stuck on a "similar" issue just because I was using the same connection for all of the three types, I'm moving back from bullmq just because we need support to Redis 4. There we used to pass the same connection to workers and queue. 
Do you know if that's is expected ? should I have three different connections and if so you mind pointing me in the right direction to understand why is that?

**Comment by gielow** [comment]
@vinioliveira I had 3 different connections because I had some memory leak issues. Inspecting I suspect that the leak issue was being caused by Redis client. Having different connections would allow me to inspect which part of the connection and framework was leaking.
