### ISSUE TITLE
addBulk upper limit of jobs

### ISSUE THREAD

**Issue by tadejstanic** [OptimalBits/bull#1960]
I'd like to ask if there are any upper limits on the number of jobs that are added through the `addBulk` method? How this method affect Redis's performance?

**Comment by rosslavery** [comment]
Not a direct answer but I posted a similar question here https://github.com/OptimalBits/bull/issues/1929

My understanding is that it uses a redis transaction and should be more performant but unclear on any upper limit.

**Comment by tadejstanic** [comment]
Thx. Now, I find it a bit clearer.
