### ISSUE TITLE
Doesn't parse redis url correctly

### ISSUE THREAD

**Issue by endor** [OptimalBits/bull#1969]
I would expect something like this to work correctly:

```
new Bull("myname", "rediss://authtoken@myhost:myport");
```

because that is something that `ioredis` also supports. 

There are currently two problems, as far as I can see:

1. `redisOptsFromUrl` doesn't take the TLS part of the url into account and it's just dropped.
2. The authtoken parsing is broken, because it assumes there's always a username.

**Comment by bowenbowensun** [comment]
What is your workaround to use Bull with TLS? I, too, am trying to support TLS which is required by Heroku Redis. So far has no luck.

**Comment by manast** [comment]
@bowenbowensun try with this:
```js
 const queue = new Queue('myQueue', {
    redis: {
      password: "**********************",
      host:  "myherokuhost",
      port: 443,
      tls: {
        servername: "myherokuhost",
      },
    },
  }})
```

let me know if it does not work for you.

**Comment by bowenbowensun** [comment]
@manast Thanks a lot. I was able to add another option 'rejectUnauthorized: false' to get it working. According to stackOverflow, the certificate made by this connection is self-signed. I wander how it works to get the certificate(public key) signed by a Certificate Authority. Who would be the Certificate Authority here? The Heroku Redis server?

**Comment by jkepps** [comment]
@manast Is there a reason why passing the redis url with a username and password isn't supported? When used with redis v5? ioredis parses the url just fine on it's own, but when i pass the same URL to the bull config I get `The server returned "wrong number of arguments for 'auth' command". You are probably passing both username and password to Redis version 5 or below. You should only pass the 'password' option for Redis version 5 and under.`

This works:
```ts
new BullQueue<T>(name, {
    prefix: QUEUE_PREFIX,
    redis: {
      maxRetriesPerRequest: 100,
      host: process.env.REDIS_HOST,
      port: +(process.env.REDIS_PORT ?? 6379),
      password: process.env.REDIS_PASSWORD,
    },
    ...options,
  })
```
but this does not
```ts
new BullQueue<T>(name, process.env.REDIS_URL, {
    prefix: QUEUE_PREFIX,
    redis: { maxRetriesPerRequest: 100 },
    ...options,
  })
```
where `REDIS_URL` is `redis://<username>:<password>@<host>:<port>`

**Comment by manast** [comment]
The code that handles redis options was wrote originally for "node-redis", and now this code is a bit messy so even though this is an inconvenience there are no plans to improve it, specially because in BullMQ this is all much nicer (https://github.com/taskforcesh/bullmq) and where the most efforts are spend in improving these kind of annoyances.
