### ISSUE TITLE
Advanced rate limiter

### ISSUE THREAD

**Issue by gilshallem** [OptimalBits/bull#1975]
Hi, 
I'm building a website scraper. 
I use different proxies to scrape the website so I need to define a rate of x requests per minute per proxy.
The only way I can think of is implementing a queue per proxy.
is there a better way?
in addition, some of the requests need to happen from a specific proxy, yet some can be called from any proxy so this solution will not work.

Thank you for the awesome library!

**Comment by gilshallem** [comment]
maybe if there is a way for the processor to bounce back the job manually?

**Comment by manast** [comment]
You can try the groupKey option in the rate limiter: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queue
"  groupKey?: string; // allows grouping of jobs with the specified key from the data object passed to the Queue#add (ex. "network.handle")
"

**Comment by refo** [comment]
> Hi,
> I'm building a website scraper.
> I use different proxies to scrape the website so I need to define a rate of x requests per minute per proxy.
> The only way I can think of is implementing a queue per proxy.
> is there a better way?
> in addition, some of the requests need to happen from a specific proxy, yet some can be called from any proxy so this solution will not work.
> 
> Thank you for the awesome library!

Did you manage to group jobs per proxy without adding a queue per proxy?
