### ISSUE TITLE
How to check if a job is completed or failed?

### ISSUE THREAD

**Issue by imns** [OptimalBits/bull#198]
If I query a job like so:
```
myQueue.getJob(jobId).then(function(job) { ... });
```
How do I tell if the job is completed or failed?  It seems like the bull-ui project does this, but after looking at the code it's a lot of boilerplate for what seems simple.

**Comment by evanhuang8** [comment]
There are several methods on the job itself that are not documented:

`job.isCompleted()`
`job.isFailed()`
...
`job.getState()`

See: https://github.com/OptimalBits/bull/blob/master/lib/job.js#L216

**Comment by imns** [comment]
Ah, nice.  You should really add these to the documentation.
