### ISSUE TITLE
Make job counters always correct

### ISSUE THREAD

**Issue by Skryabind** [OptimalBits/bull#1981]
Hi!
Queue has a method **getJobCounts**, which returns job counters. But there is one moment - to get correct number of completed or failed jobs you shoud turn both **removeOnComplete** and **removeOnFail** to false.
I have many jobs and I don't need to store completed jobs in redis so I set removeOnComplete and removeOnFail to true, and now getJobCounts always returns 0 in completed and failed jobs.
It would be great if counters will always be correct ragardless of other parameters.

P.S. For monitoring purposes I made my own counters using events 'completed' and 'failed', but it'll be more comfortable if bulljs will counts jobs itself.

**Comment by xmflsct** [comment]
Same question here, counter now returns 0.

**Comment by manast** [comment]
getJobCounts only returns the current jobs in the different status such as completed/failed. What you are asking would be a new statistic module. I will mark this as a feature request.

**Comment by SidSethi** [comment]
@manast just want to confirm that this feature has not been implemented? would love ability to track completed jobs count without preserving entire job state. I understand if this is not a trivial task, but figured i'd ask 🙂

**Comment by manast** [comment]
This is in fact implemented: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queuegetmetrics
But you need to enable it first, check the metrics object: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queue

**Comment by SidSethi** [comment]
ah perfect @manast i'll look into this, thanks!!
