### ISSUE TITLE
Does it support to send message in transaction together with other redis operation?

### ISSUE THREAD

**Issue by mortyccp** [OptimalBits/bull#1985]
#### (An easy to reproduce test case will dramatically decrease the resolution time.)

I am implementing https://microservices.io/patterns/data/transactional-outbox.html with redis and would like to know can this library send message in a transaction?

**Comment by BigsonLvrocha** [comment]
Hey, I also have a use case for sending message with other redis operation,
Maybe this is a case of being able to generate the raw commands in other to pass to `.multi()` function?

**Comment by manast** [comment]
I think in general this would only be useful for the "add" operation. In any case, we are not adding new features to Bull. There is a higher chance to get this functionality in [BullMQ](https://github.com/taskforcesh/bullmq).
