### ISSUE TITLE
Empty queues message check latency is ~500ms

### ISSUE THREAD

**Issue by plakk2020** [OptimalBits/bull#1988]
## Description
My code has multiple bull queues. The process resumes a queue, checks for messages, if none pauses the queue and resumes the next queue.

When there are messages in the queue, there is no latency. But when the queues are empty I see a latency of ~500ms, even though drainDelay is 5ms.

Does the queue.pause() invoke redisClientDisconnect() which has a promise timeout of 500ms, when the queue is empty?

## Bull version
3.18.0
## Additional information
The pause and resume queue is local

**Comment by manast** [comment]
> Does the queue.pause() invoke redisClientDisconnect() which has a promise timeout of 500ms, when the queue is empty?

no, it does not.

**Comment by manast** [comment]
btw, in your case it seems more appropriate to use https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#manually-fetching-jobs

**Comment by plakk2020** [comment]
> > Does the queue.pause() invoke redisClientDisconnect() which has a promise timeout of 500ms, when the queue is empty?
> 
> no, it does not.

queue.pause() does invoke whenCurrentJobsFinished() and this has redisClientDisconnect() call. But I am not sure what is the client value in pTimeout()

**Comment by plakk2020** [comment]
> btw, in your case it seems more appropriate to use https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#manually-fetching-jobs

I will take a look at this

**Comment by manast** [comment]
> queue.pause() does invoke whenCurrentJobsFinished() and this has redisClientDisconnect() call. But I am not sure what is the client value in pTimeout()

that is if you do a local pause, is that what you want?

**Comment by plakk2020** [comment]
> > queue.pause() does invoke whenCurrentJobsFinished() and this has redisClientDisconnect() call. But I am not sure what is the client value in pTimeout()
> 
> that is if you do a local pause, is that what you want?

Yes. The worker process rotates through the multiple bull queues pausing and resuming locally to check if there are any messages. As I want the process to work on a single message at a time.

When the queues are empty, I see the 500ms latency but not when there are messages in the queue.

**Comment by manast** [comment]
when the queue is empty it establishes a blocking connection which needs to be broken when you pause. This is kind of works as designed, so probably will not be fixed...

**Comment by plakk2020** [comment]
Thank you for the clarification.
