### ISSUE TITLE
feature suggestion: working with batches of jobs

### ISSUE THREAD

**Issue by andrisi** [OptimalBits/bull#1991]
Use case: I need to execute a job for each day of of a month. Lets say calculate something. I'd have 10 workers. When it's busy, the jobs would get done slowly perhaps 1-2 workers picking them, but if it's less crowded, each worker would pick jobs, so it would get done quickly. So the question is: how do I get a notification when all jobs in the batch are done? Perhaps add a batch id to all jobs and query the queue if any left? But this is something BullMQ could do more efficiently and in a generic way. Perhaps by adding a batch id and then listening to a batch-completed event? I'd be hapy to discuss. Thanks. @mseld @manast #751 might be related.

**Comment by andrisi** [comment]
I don't find any other refrences to it, but the getJobCounts() doc says "Returns the job counts for each type specified or every list/set in the queue by default." - what list/set is this referring to?

**Comment by manast** [comment]
> I don't find any other refrences to it, but the getJobCounts() doc says "Returns the job counts for each type specified or every list/set in the queue by default." - what list/set is this referring to?

Please check this documentation: https://docs.bullmq.io/guide/jobs/getters let me know if there is more information missing.

**Comment by manast** [comment]
Batches where we wait for a batch to be filled is a bit tricky (if possible at all) to implement on top of redis using lua script unless we use polling, which becomes really challenging if we have a distributed system with workers. This is one of the features that are possible with BullMQ as a redis module though: https://blog.taskforce.sh/bullmq-redis-module/

**Comment by andrisi** [comment]
Just to clarify: I don't require workers to work on batches of jobs as one. I'd just need to get a notification when the last from a set of jobs complete. Perhaps a counter per set? Sorry if this was clear before, I just thought using the word batch wasn't a good idea, nor referring to issue 751. Thanks for the replies, I'll look into them.

**Comment by manast** [comment]
Ok, then this has been discussed here: https://github.com/OptimalBits/bull/issues/340
I would love to implement it soon, but not sure when I can find a time slot to do it.

**Comment by andrisi** [comment]
I think my proposal is simpler to implement, but could be used in place of your parent/child one. It would just be more work on the client side. What would be needed is just a counter per set id and then an event when it gets to 0.

**Comment by manast** [comment]
A counter is useful if you add all the jobs at the same time so that you can guarantee they are all in the queue when the counter is initialized. Since we support adding a batch already atomically, an easy addition would be to set a counter for that batch. However, events are not reliable, so it must be notified in a different way, probably a "meta" job that includes the results of all the jobs from a given batch...
Another thing is the terminology, since the term batch is also used as in having a number of jobs that are consumed at once, in one batch.

**Comment by andrisi** [comment]
For now I add a redis sets under a key like 'jobgroup:[group id]' containing IDs of jobs belonging to a group. This way I can add jobs later (or later then the first one gets completed). Then I remove the IDs as jobs are completed (by listening to an event) and when the set gets empty I emit a group-completed event. But it's a bit shaky I guess and you'd better do it when adding jobs to a queue or when marking them as complete. And in lua, with no race conditions between removing/adding ids to the set and then asking for the set's item count. For me the set seems better then a counter because I can't be sure there is only one listener to completed events, but if this is part of BullMQ you could do the same things as you do for other tasks.

**Comment by manast** [comment]
Ok, so in theory the same group could emit the "group-completed" event more than once, if you for example happen to add a new job to a group that has already been completed?

**Comment by andrisi** [comment]
Yes. In my case this was a side effect of me handling adding jobs one by one and using a zero-delay dummy worker. In realistic scenarios or when you add jobs in on call (there is such, right) then there would be only one group-completed event. Or (as a reqirement of mine) if you add new jobs to the group in a worker before it completes (when you need to retry something with another method for example). Otherwise this rare happening would just count as two groups with the same id.

**Comment by andrisi** [comment]
https://docs.bullmq.io/guide/jobs/flows thanks!

**Comment by andrisi** [comment]
@manast do the options passed to FlowProducer.add() apply to children or I need to set the opts property of each job separately? Like the attempts/backoff ones.

**Comment by manast** [comment]
@andrisi the opts must be per job.
