### ISSUE TITLE
Avoid null stalled event when another worker completes the job

### ISSUE THREAD

**Issue by alexburke-peakon** [OptimalBits/bull#1993]
## Description
In production we are seeing the `stalled` event being emitted with a null job - the code doing the emit is here: https://github.com/OptimalBits/bull/blob/v3.20.1/lib/queue.js#L954. Our analysis suggests that, in the case of multiple independent worker processes, a job may stall on one worker (which proceeds to try to report it) but another worker may retry and complete the job by the time the asynchronous `getJobById()` call is made. This causes `null` to be returned as the job and subsequently emitted.

## Bull version
3.20.0

## Additional information
In the case of this race occurring and the job being null, our feeling is that the stalled event should not be emitted since the job was completed. If the job failed, it would be emitted separately as a failure so there shouldn't be a loss of information by adding such protection. We will submit a PR to address this issue for your consideration :)

**Comment by manast** [comment]
Thanks, I wrote a small comment about it. Actually we probably should not send the events in JS space but directly from the lua script itself, faster and also avoids this hazard altogether...

**Comment by alexjeffburke** [comment]
This issue was addressed by the merge of https://github.com/OptimalBits/bull/pull/1994 - seems I managed to input the fixed issue number wrong.

**Comment by alexburke-peakon** [comment]
This issue was addressed by the merge of #1994 - seems I managed to input the fixed issue number wrong.
