### ISSUE TITLE
Subsequent jobs not being added after the first

### ISSUE THREAD

**Issue by davedodea** [OptimalBits/bull#2000]
## Description
I have a Node/Express application that allows users to make a POST with fields in the request body: `name, url, and interval`.
- The above fields are then passed to `queue.add`.
- The processing function responsible makes a request to the specified `url`, at the specified `interval` and logs the response.

The issue is that the first call I make will create a job and process it OK. 
However, if I call it again with new data, no further job(s) is created in Redis.

```js
// The portion of the API controller responsible for creating the job.
...
const data = {
    url: req.body.url, //'https://google.com'
  };
const options = {
    delay: 1000, 
    attempts: 2,
    repeat: { cron: `*/${req.body.interval} * * * *` }, //'*/1 * * * *'
  };
await httpQueue.add(data, options);
...
```

## Bull version
3.21.1

**Comment by manast** [comment]
Please isolate the case without any express code and reproducible so we can take a look at it.

**Comment by davedodea** [comment]
Please see the following simple extraction, `bull.js` which adds new jobs and processes the queue.


```js
const Queue = require('bull');
const redisConn = require('./lib/redisConn');
const request = require('request');

const httpQueue = new Queue('last-login', redisConn);

httpQueue.process(async (job, done) => {
  const { url } = job.data;
  request(url, { json: true }, (err, res) => {
    if (err) {
      done();
      return console.log(err);
    }
    console.log('LOG: Checking ', url);
    console.log('LOG: Res: ', res.statusCode);
    done();
  });
});

const http = async (req, res, next) => {
  // SWitch this out to pass the URL from a new Monitor
  // i.e. https://google.com etc.
  const options = {
    attempts: 2,
    repeat: {
      every: 3000,
      limit: 100,
    },
  };
  httpQueue.add({ url: 'https://google.com' }, options);
};

http();


```

As mentioned previously, if I run, i.e. with: `nodemon bull.js` I will get, as expected:
```bash
LOG: Checking  https://google.com
LOG: Res:  200
```

However, if I change the URL where I do `httpQueue.add` to:
`httpQueue.add({ url: 'https://microsoft.com' }, options);` , that new job is not added to Redis.

To be clear, I would expect to now see output from 2 jobs, similar to:

```bash
LOG: Checking  https://google.com
LOG: Res:  200

LOG: Checking  https://microsoft.com
LOG: Res:  200
```

**Comment by manast** [comment]
ok. This is because "repeat" works a bit awkward. You need to either change the repeat object or to provide a unique jobId, otherwise the second repeatable job is considered same as the first one and just ignored.

**Comment by davedodea** [comment]
Ok, thanks - can you point me in the direction of the relevant docs where this is stated?

**Comment by manast** [comment]
Check in the Repeatable section: https://optimalbits.github.io/bull/

**Comment by davedodea** [comment]
Thanks for the assistance @manast - appreciate your time 👍
