### ISSUE TITLE
bull add to many master.js to memory 

### ISSUE THREAD

**Issue by koiszzz** [OptimalBits/bull#2002]
## Description
I have an project which use bull to manage list of http request. While job processing , node_modules/bull/lib/process/master.js will add to memory and dosen't realease. Is there has some way to debug it ?  
## Bull version
v 3.20.0

**Comment by manast** [comment]
Please provide reproducible code that demonstrates the issue so that we can look into it.

**Comment by koiszzz** [comment]
I have test in my temp project. here is the [link](https://github.com/koiszzz/bull-test).
It seems that bull doesn't release process when job done while using `Task.process('taskNane', filePath);`

**Comment by manast** [comment]
@koiszzz no, the processes are not released after every job, a process is reused for all the jobs within a given concurrency factor. if you have concurrency 10, then there will always be 10 processes running.

**Comment by koiszzz** [comment]
And now project some times the server will consume all memory, how to advoid this? Or It there some way to close the master.js process? @manast

**Comment by manast** [comment]
@koiszzz they should not keep growing but keep at a static proportional to your concurrency factor. What is your concurrency factor?

**Comment by koiszzz** [comment]
I have an B/S server. Customers use browser to info server do some heavy job. Some times many customers create that job at the same time

**Comment by manast** [comment]
@koiszzz the amount of jobs is not important, only the amount of workers and concurrency factor for every worker.

**Comment by manast** [comment]
@koiszzz btw, I took a look at your test repo. The code LGTM. How do you conclude the processes are growing indefinitely, can you help me test it?

**Comment by koiszzz** [comment]
cause that in my production server, the number of processes is much more than the concurrency defined in code.  After I reproduce the problem in test  , I will send message to you. Thx @manast .

**Comment by koiszzz** [comment]
hi @manast . I have update my test project. It seems that when I start another job in some job , It will create a brand new master.js and server never reuse it. just clone the project and run it , then broswer localhost:3000/add several times, you will see.

**Comment by manast** [comment]
@koiszzz the bug is in your code. You are creating new processors everytime a new child process is created and that creates an infinite loop every time you process a child job new processes are created:
https://github.com/koiszzz/bull-test/blob/main/routes/processes/childJob.js#L1

**Comment by koiszzz** [comment]
What's the right way to do when I want to start a new job while previous job done ? @manast

**Comment by manast** [comment]
you are asking the wrong question. The problem is that inside your new process you are defining new bull.process functions, and for every new function you define you are creating new process that in turn ... yeah it never ends.

**Comment by koiszzz** [comment]
After re-reading the REFERENCE.md , I found that I have used the process.js as a wrong way. Thx for replying . @manast
