### ISSUE TITLE
Can't Override jobId on Recurring Jobs

### ISSUE THREAD

**Issue by wbw20** [OptimalBits/bull#2006]
Thank you for your work on this library.

## Description
I am trying to override the `jobId` of a recurring job, but it seems to be ignored in favor of the default Bull-generated id.

Here is a script which demonstrates what I am talking about:

```
const Queue = require('bull')

const main = async () => {
  const testQueue = new Queue('test-queue', 'localhost')

  testQueue.process((job, done) => {
    console.log(`Currently running ${job.data.name}`)
    done()
  })

  const task1 = await testQueue.add({
    name: 'First task'
  }, {
    jobId: 'task-id-1',
    repeat: {
      every: 5000,
    },
  })

  const task2 = await testQueue.add({
    name: 'Second task'
  }, {
    jobId: 'task-id-2',
    repeat: {
      every: 5000,
    },
  })

  console.log(`task1.id: ${task1.id}`)
  console.log(`task2.id: ${task2.id}`)
}

main()
```

When I run this, I get the following output:

```
$ node ./bull-demo.js
task1.id: repeat:654889975bd1723571a66668fc01dfb5:1616857940000
task2.id: repeat:4169ce9b504a730ad4d1308810e05a9c:1616857940000
Currently running First task
Currently running Second task
...
```

I would have expected to see my custom ids in the output instead of the default Bull-generated ids. Please let me know if this is a real bug or if I am using the API incorrectly. Thank you!

## Bull version
3.22.0

**Comment by manast** [comment]
The jobId you provide is used to generate the repeat id, but every repetition needs to have a unique id, otherwise there would not be any repetitions at all since job ids must be unique and trying to add two jobs with the same id results in the second job to be ignored.

**Comment by wbw20** [comment]
I see. So you are saying that recurring jobs with custom ids is simply not supported by design?

**Comment by seelts** [comment]
I have the exact same issue.
I want to have a job with the specific id so that I can find it later and update it's data.
