### ISSUE TITLE
Using bull with ioredis?

### ISSUE THREAD

**Issue by talaltoukan** [OptimalBits/bull#2008]
I saw [this](https://github.com/OptimalBits/bull/issues/1406#issuecomment-518838620) comment on another issue, and since I'm using ioredis with bull I was wondering what this refers to. Why is ioredis incompatible with bull?

**Comment by manast** [comment]
This is supposed to work now with the latest versions of redis. Did you encounter any issues?

**Comment by talaltoukan** [comment]
No I didn't, I just wanted to confirm. Thanks!
