### ISSUE TITLE
Redis client promisification performance issues

### ISSUE THREAD

**Issue by nathanmarks** [OptimalBits/bull#201]
In the readme you mention queues are cheap -- unfortunately not cheap enough.

Promisification via bluebird is very expensive CPU wise (even more so with `Promise.promisifyAll`), making initializing queues an expensive operation

Basically, initializing queues on the fly is not possible with any significant number of users creating queues simultaneously. Have you considered wrapping the functions you use in a simple promise such as:

```javascript
return new Promise((resolve, reject) => {
  redisClient.hgetall(key, (err, obj) => err ? reject(err) : resolve(obj));
});
```

**Comment by manast** [comment]
not sure that will be much faster than promisifyAll, but something to consider is using https://github.com/luin/ioredis which may be faster for the use case you propose.

**Comment by nathanmarks** [comment]
@manast The main issue is how it creates the promisified API, see the CPU use here:

![image](https://cloud.githubusercontent.com/assets/4420103/11023882/d06b6eb4-8651-11e5-91be-7bd0601e57aa.png)

**Comment by nathanmarks** [comment]
@manast Check this comment -- https://github.com/petkaantonov/bluebird/pull/245#issuecomment-47161322

**Comment by nathanmarks** [comment]
@manast I noticed my CPU spike when add a lot of queues in quick succession -- this is what prompted my investigation. 

I found that comment and took a look at the bluebird code. The performance issue is due to how Bluebird evaluates the passed in functions and created a new function.

**Comment by manast** [comment]
In that case I think the best option is to use ioredis which is faster than node redis and has already a promised based api...

**Comment by nathanmarks** [comment]
@manast I'll see if I can find some time to put a PR together.

Side question -- do you ever use es6+babel for JS?

**Comment by manast** [comment]
nope. The only language that compiles to javascript that I have used (and quite extensively) is typescript...

**Comment by manast** [comment]
there have been some efforts to port to ioredis, not completely successfull though, check the PRs

**Comment by nathanmarks** [comment]
Might have a go if I get some time.

Are the tests thorough enough to confirm a working ioredis implementation?
