### ISSUE TITLE
Completed jobs are not removed

### ISSUE THREAD

**Issue by FigaCZ** [OptimalBits/bull#2017]
## Description

I have a simple queue

```
const pdfQueue = new Queue('prod-pdf', {
    redis: redisConf,
    limiter: {
        max: 3,
        duration: 60000
    }});

pdfQueue.on('error', function (error) {
    console.log(error);
});

```

I am createing job like this

```
queue.pdfQueue.add('pdfGeneration', new PdfJob(appointment.id), {
                    attempts: 10,
                    backoff: 60000,
                    lifo: true,
                    removeOnComplete: true,
                    removeOnFail: true
                });
```

Unfortunatelly completed jobs hangs in Redis.

BULL-REPL | bull.prod-pdf> stats

| (index)        | Values           |
| ------------- |-------------:|
| waiting     | 0 |
| active     | 0  | 
| completed | 3013  | 
| failed     | 0|
| delayed     | 0 |
| paused     | 0 |

## Bull version
3.22.1

Is this issue or my mistake?

**Comment by manast** [comment]
probably a mistake... this functionality is stable and covered by unit tests.

**Comment by ctrlaltdylan** [comment]
Cleared jobs are not removed automatically.

I'm using the bull admin dashboard to clear completed jobs through a web GUI.

However I'm trying to automate this with the `Queue.clear()` function.

I've tried `queueName.clear(0, 'completed');` but it's not taking any effect on the queues at all.

Would love to cron job this to remove successfully completed jobs on a schedule because the completed job data eventually maxes out the disk space on Redis.

**Comment by manast** [comment]
We have several unit tests that check for remove on complete and they are all passing, if you can write a test that does not pass then I can look into it: https://github.com/OptimalBits/bull/blob/develop/test/test_queue.js#L455

**Comment by hrasekj** [comment]
My guess is, FigaCZ is creating multiple named jobs on the same queue.

```
pdfQueue.add('pdfGeneration', new PdfJob(appointment.id), {
                    attempts: 10,
                    backoff: 60000,
                    lifo: true,
                    removeOnComplete: true,
                    removeOnFail: true
                });

pdfQueue.add('secondPdfGeneration', new PdfJob(appointment.id));
```

The `secondPdfGeneration` job have different options, without `removeOnComplete`, so they stuck up in redis.

I had similar problem when i configured `defaultJobOptions` on consumer instance of Bull queue.

**Comment by gielow** [comment]
I think you need to pass these options while creating the Queue itself, not while adding the job.

const queue = new Queue(
    'my-queue-name',
    {
      createClient: function (type) {
        switch (type) {
          case 'client':
            return client;
          case 'subscriber':
            return subscriber;
          case 'bclient':
            return bclient;
          default:
            throw new Error('Unexpected connection type: ', type);
        }
      },
      defaultJobOptions: {
        removeOnComplete: true,
        removeOnFail: true,
      },
    }
  );

**Comment by sibelius** [comment]
is there a command to remove completed jobs manually?

**Comment by olivierlacan** [comment]
I would expect this to be configurable by default, so that after a specific period of time or a specified limit, auto-clearing of completed jobs would occur so that the Redis instance isn't filled to max capacity by keeping unnecessary completed jobs forever.

**Comment by manast** [comment]
@olivierlacan the poster code looks like this:
```
queue.pdfQueue.add('pdfGeneration', new PdfJob(appointment.id), {
                    attempts: 10,
                    backoff: 60000,
                    lifo: true,
                    removeOnComplete: true,
                    removeOnFail: true
                });
```

i.e. it is enabling removeOnComplete, therefore the issue is not reproducible, unless proven the contrary with a test case.
