### ISSUE TITLE
getJobLogs pagination reversed

### ISSUE THREAD

**Issue by tjhiggins** [OptimalBits/bull#2031]
## Description
Implementing a UI over the bull job logs and noticed that the log pagination is reversed. I'm not sure if this is intentional, but its certainly confusing and makes implementation difficult when trying to paginate or live log stream. 

## Minimal, Working Test code to reproduce the issue.

This is a simple example that illustrates the problem.
```ts
job.log('Page 1');
job.log('Page 2');
job.log('Page 3');

// actual
queue.getJobLogs(job.id, 0, 0) === { count: 3, logs: ['Page 3'] }
queue.getJobLogs(job.id, 1, 1) === { count: 3, logs: ['Page 2'] }
queue.getJobLogs(job.id, 2, 2) === { count: 3, logs: ['Page 1'] }

queue.getJobLogs(job.id, 0, 1) === { count: 3, logs: ['Page 2', 'Page 3'] }

// expected
queue.getJobLogs(job.id, 0, 0) === { count: 3, logs: ['Page 1'] }
queue.getJobLogs(job.id, 1, 1) === { count: 3, logs: ['Page 2'] }
queue.getJobLogs(job.id, 2, 2) === { count: 3, logs: ['Page 3'] }

queue.getJobLogs(job.id, 0, 1) === { count: 3, logs: ['Page 1', 'Page 2'] }
```

## Bull version
v3.22.4

**Comment by manast** [comment]
Actually I do not remember if it was intentional or not, but yes it should not be reversed.

**Comment by manast** [comment]
yes, I think the rationale was that often times you are interested in the newest logs and you browse backwards in time. So I think the solution to support both cases (as it works now and streaming logs), would be to add an "asc" parameter as we have in the other getters, by default would be false, and passing true will provide the functionality you are requesting.

**Comment by tjhiggins** [comment]
@manast I'm fine with updating, but what do you think about this comment?
https://github.com/taskforcesh/bullmq/pull/538/files#r633169826

I'd tech be a breaking change, but if the default behavior is truly descending then we should fix the existing logic.

**Comment by manast** [comment]
In my comment here https://github.com/taskforcesh/bullmq/pull/538#issuecomment-842097788 I wrote that I think ASC should be default since current one is actually ASC (f you call the API without start, end params), so that would probably the less "breaking change", since it is not documented the expected order anyway.
