### ISSUE TITLE
Package exports for '/app/node_modules/uuid' do not define a valid '.' target

### ISSUE THREAD

**Issue by ldco2016** [OptimalBits/bull#2032]
I needed to implement BullJS into my project. I have a microservice called expiration that utilizes BullJS to publish an event when an order is expired:

    import Queue from 'bull';
    
    interface Payload {
      orderId: string;
    }
    
    const expirationQueue = new Queue<Payload>('order:expiration', {
      redis: {
        host: process.env.REDIS_HOST,
      },
    });
    
    expirationQueue.process(async (job) => {
      console.log(
        'I want to publish an expiration:complete event for orderId',
        job.data.orderId
      );
    });
    
    export { expirationQueue };

My service was always connected to NATS and running well, until I integrated the above like so:

    import { Listener, OrderCreatedEvent, Subjects } from '@dc_microurb/common';
    import { Message } from 'node-nats-streaming';
    import { queueGroupName } from './queue-group-name';
    import { expirationQueue } from '../../queues/expiration-queue';
    
    export class OrderCreatedListener extends Listener<OrderCreatedEvent> {
      subject: Subjects.OrderCreated = Subjects.OrderCreated;
      queueGroupName = queueGroupName;
    
      async onMessage(data: OrderCreatedEvent['data'], msg: Message) {
        await expirationQueue.add({
          orderId: data.id,
        });
    
        msg.ack();
      }
    }

Now I continue to get the following error with this service:

> [expiration-depl-9645c9f7d-q4xk9 expiration] Error: Package exports
> for '/app/node_modules/uuid' do not define a valid '.' target
> [expiration-depl-9645c9f7d-q4xk9 expiration]     at
> resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
> [expiration-depl-9645c9f7d-q4xk9 expiration]     at applyExports
> (internal/modules/cjs/loader.js:459:14)
> [expiration-depl-9645c9f7d-q4xk9 expiration]     at resolveExports
> (internal/modules/cjs/loader.js:508:12)
> [expiration-depl-9645c9f7d-q4xk9 expiration]     at
> Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
> [expiration-depl-9645c9f7d-q4xk9 expiration]     at
> Function.Module._resolveFilename
> (internal/modules/cjs/loader.js:879:27)
> [expiration-depl-9645c9f7d-q4xk9 expiration]     at
> Function.Module._load (internal/modules/cjs/loader.js:785:27)
> [expiration-depl-9645c9f7d-q4xk9 expiration]     at Module.require
> (internal/modules/cjs/loader.js:956:19)
> [expiration-depl-9645c9f7d-q4xk9 expiration]     at require
> (internal/modules/cjs/helpers.js:74:18)
> [expiration-depl-9645c9f7d-q4xk9 expiration]     at Object.<anonymous>
> (/app/node_modules/bull/lib/timer-manager.js:4:14)
> [expiration-depl-9645c9f7d-q4xk9 expiration]     at Module._compile
> (internal/modules/cjs/loader.js:1063:30)
> [expiration-depl-9645c9f7d-q4xk9 expiration] [nodemon] app crashed -
> waiting for file changes before starting...

This is my first time using BullJS, not sure if there is an issue with this version or whats going on.

I upgraded BullJS to the latest version, but that did not resolve the issue.

**Comment by manast** [comment]
I have no idea what causes that error, most probably not bull related. Try to isolate and simplify until you can corner the issue.

**Comment by ldco2016** [comment]
@manast , I know when I remove this:

```
await expirationQueue.add({
      orderId: data.id,
    });
```

from `onMessage()` the error goes away and I get my events from this service console logging.
