### ISSUE TITLE
bull:queue:stalled redis key meaning

### ISSUE THREAD

**Issue by m7x333** [OptimalBits/bull#2049]
## Description
constantly noticed bull:queue:stalled redis key with some already finished jobs ids.
this key live about several second after all jobs in this queue was processed and then disappear.
we didn't notices any stalled job errors.
out workers need about 30 sec per job to process.
also following options a used:
```
lockDuration: 300000, maxStalledCount: 0
```

please explain what bull:queue:stalled actually mean?

## Bull version
3.22.0

**Comment by manast** [comment]
https://github.com/optimalbits/bull#important-notes

**Comment by m7x333** [comment]
hello, thank you for response but from notes above not clear what bull:queue:stalled redis key actually mean, we didn't notice stalled errors but constantly see bull:queue:stalled filed with some random finished job ids. could you provide some info how this key work please?

**Comment by manast** [comment]
The stalled key is used internally for implementing the stalled jobs mechanism. It is not useful to know about it as user of the library.
