### ISSUE TITLE
experiencing an unreasonably long time to add new jobs

### ISSUE THREAD

**Issue by alxyuu** [OptimalBits/bull#2054]
## Description

Occasionally, I will see extremely long times for jobs to be processed. The job seems to be stuck on the producing side rather than the processor side, since the job does not even show up when looking through bull-board. In addition, traces from our API producer show extremely long redis evalsha1 spans:
![image](https://user-images.githubusercontent.com/98154/119861830-7088de80-bedd-11eb-8509-554c5e9696be.png)

The behavior seems to be that certain job additions won't succeed until another job is added. Upon adding another job, the processor picks up a job within milliseconds which is to be expected, but it is a previously queued job. Often this results in dozens of jobs getting stuck during addition. The issue is resolved when restarting my API producer, but any jobs that were not successfully added are lost. This seems to happen both under load and when the API and processor are largely idle, and I don't see any spikes in memory or cpu in either my api instances or my redis nodes that would point to a performance bottleneck.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

Unfortunately I was unable to replicate this issue in a demo application

## Bull version

3.20.0

## Additional information

bull-board: 1.2.0
ioredis: 4.18.0
elasticache redis: 6.0.5
elasticache nodes: cache.t3.small, multi-az, 1 primary and 1 replica
api environment: elasticbeanstalk, multi-docker, node

**Comment by manast** [comment]
This is most likely an issue in user code. Adding jobs is a very simple call to a LUA script. In your case if I had to guess, the connection to Redis has been probably lost or something. Make sure that you have correct listeners to error events and that you are logging all exceptions produced by your service and maybe you can find the issue.

**Comment by alxyuu** [comment]
Hi @manast, I have added additional logging in both reconnectOnError for ioredis as well as queue.on('error', ...), but have not received any notable errors outside of `NOSCRIPT No matching script. Please use EVAL.` from ioredis, which I believe is expected. Is there anywhere else errors could be emitted from?

For reference, this is how I create the queues:

```
type QueueMap = Record<Queue, BullQueue.Queue>;

const IGNORED_ERRORS = new Set([
  'NOSCRIPT No matching script. Please use EVAL.',
]);

const buildQueues = (): QueueMap => {
  const options: BullQueue.QueueOptions = {
    createClient: () => {
      return new Redis(Configuration.redisUrl, {
        reconnectOnError(err) {
          if (!IGNORED_ERRORS.has(err.message)) {
            createLogger().child({ type: 'Redis Client' }).error(err);
          }
          return false;
        },
      });
    },
    defaultJobOptions: {
      removeOnComplete: 1000,
      removeOnFail: 1000,
      attempts: 10,
    },
  };

  const newQueues = {
    [Queue.CHAT]: new BullQueue('chat', options),
    [Queue.MEDIA]: new BullQueue('media', options),
  };

  Object.keys(newQueues).forEach((queueName: Queue) => {
    const queue = newQueues[queueName];
    queue.on('error', (err) => {
      createLogger().child({ type: 'Job Queue', queue: queueName }).error(err);
    });
  });

  return newQueues;
};
```

I am also using encryption in transit in elasticache, so url is a `rediss://` url if that might have any impact on job creation times.

**Comment by manast** [comment]
In theory the NOSCRIPT error should not happen anymore in the latest release: https://github.com/OptimalBits/bull/issues/1445
could you try to see if it makes any difference?

**Comment by alxyuu** [comment]
Hi @manast, I still receive the NOSCRIPT errors -- 3 when the server starts up (presumably from the client, bclient, and subscriber) and 1 on the first (not subsequent) job add and 1 on the first (not subsequent) job completion.

bull: 3.22.8
ioredis: 4.27.5

That being said, it doesn't seem like NOSCRIPT itself is causing any issues. Here is an example of a job I am adding, which seems fairly standard:

```
queues[Queue.MEDIA].add('scan-media', { mediaId: 'cb304ec9-a58f-4654-b74e-2d3bf50b392e' })
```

**Comment by manast** [comment]
My experience with elasticache has always been pretty good, but never use cluster mode, just a main instance with replication. I do not think encryption is the cause of this, since I have been using it everywhere else without any issues.

**Comment by alxyuu** [comment]
some combination of scheduling instances to be replaced every 24 hours and increasing the elasticache size to cache.t3.small seems to have abated the issue, hard to tell which though. it's possible the fact that the redis instances were replaced during the size upgrade also helped.
