### ISSUE TITLE
How to remove erring repeatable jobs?

### ISSUE THREAD

**Issue by vansham-gortnm** [OptimalBits/bull#2055]
## Description

I have a repeatable job that has the cron parameters set to `'* * * * * *'`.  Now let's say the consumer is throwing an error every time it repeats. But I need to remove it from the queue entirely. If I try to use the `jobId` of the failed repeatable job it doesn't stop the recurring because I suppose the `jobId` of every repeated job is different. I try to supply my own `jobId` when I add the job for the first time but again it doesn't work and that `jobId` somehow goes into `job.opts.repeat`

I tried using `removeRepeatable` but it doesn't work. I passed it the name of the `named job` and the `job.opts.repeat` passed to the original job.

Please keep in mind, this issue is on our production application.

## Bull version
3.22.6

**Comment by Jageen** [comment]
Can you give more information like,
from where you are calling  `removeRepeatable` ? 
Asking because If it is calling from job it self might not work.

**Comment by vansham-gortnm** [comment]
I am calling it in the `global:failed` event.

I haven't tried `removeRepeatableByKey` as for now, we are not maintaining the key of the parent job.

**Comment by manast** [comment]
Does this work:

```ts
opts = { jobId: 'random', repeat: { cron: '* * * * * *' }, delay: 500 };

queue.add('create', {}, opts);

queue.on('global:fail', (jobId, err) => {
    await this.queue.removeRepeatable('create', opts);
}
```

doesn't it?

**Comment by vansham-gortnm** [comment]
@manast  Yeah it does! Thanks a lot!
