### ISSUE TITLE
Adding jobs to the queue from within a consumer!

### ISSUE THREAD

**Issue by vansham-gortnm** [OptimalBits/bull#2062]
## Description

@manast  How does bulljs exactly behave when we try to add new jobs to the queue from within the consumer of that queue? In my opinion, the new jobs should wait but they kinda start executing concurrently from what I see.

```
const queue = new Queue('team_delete', 'rediss://something@something', {})

queue.process('render', (job) => {
    // something     
}

queue.process('create', (job) => {
    // something     
    queue.add('render', {/* some data*/ })
}
```

**Comment by manast** [comment]
They are queued as any other job. Your code on the other hand is wrong, it should be like this:
```js
queue.process('create', (job) => {
    // something     
    return queue.add('render', {/* some data*/ })
}
```

**Comment by vansham-gortnm** [comment]
But, the thing is, when I do this - 

```
const queue = new Queue('team_delete', 'rediss://something@something', {})

queue.process('render', (job) => {
    // something     
}

queue.process('create', (job) => {
    // something     
    queue.add('render', {/* some data*/ })
}
```

Why does the new job start executing right away without waiting for the current job to finish?
And what if I really wanted to insert a new job in the middle of the consumer function?

**Comment by manast** [comment]
> Why does the new job start executing right away without waiting for the current job to finish?

I doubt it. The job will finish very fast (since it is not waiting for queue.add to complete), and then the new job will be processed.
