### ISSUE TITLE
Rate Limiting and Multiple Node Instances

### ISSUE THREAD

**Issue by ShawnPavel** [OptimalBits/bull#2068]
## Description
I have a bull queue that I use to make HTTP requests to a rate limited endpoint. This works great when I'm only running one instance of the process. However, if I run multiple instances I hit the rate limit due to both processes attempting to execute up to the set limit.

Any help with this would be greatly appreciated.

## Bull version
3.19.0

## Additional information

I create the queue like so:

```ts
const queue = new Queue(queueName, {
    "defaultJobOptions": {
        "removeOnComplete": 1000,
        "removeOnFail": 1000
    },
    "settings": {
        "guardInterval": 1000000,
        "lockDuration": 30000,
        "stalledInterval": 30000,
        "maxStalledCount": 1,
        "retryProcessDelay": 5000,
        "drainDelay": 5,
        "backoffStrategies": {},
        "lockRenewTime": 15000
    },
    "limiter": {
        "max": 3,
        "duration": 1000
    }
});

queue.process((job: Job) =>  this.makeHttpRequest(job) );
```

If I run my node process it works great. But if I run two node processes simultaneously (separate cli windows) both processes will attempt to execute 3 times per second (6 total) instead of spanning them over 2 seconds. They share the same local Redis instance.

**Comment by manast** [comment]
The rate limiter is independent on the number of workers you have. If that is not the case it would be a bug so you are welcome to provide a test case that reproduces it.

**Comment by ShawnPavel** [comment]
Hey manast, I did some more testing and was not able to reproduce with a simple example.
