### ISSUE TITLE
Does Bull suits for game with rooms?

### ISSUE THREAD

**Issue by Aliance** [OptimalBits/bull#207]
Everybody hello!

I have an easy game where users combined into rooms (for example, 10 people per room). In each room I have an entity I called *state*. Each state has a timeout about 30 seconds. States loops in sequence. I tried your Bull and it works. But I want to clarify is it okay?

For each room I have its own Queue object (in docs there were said that it's okay), so I can pause states in only one room, for example.

**Comment by manast** [comment]
For this kind of discussion please use our gitter room.
