### ISSUE TITLE
Recommended approach for handling database connections in separate processes

### ISSUE THREAD

**Issue by amehta-plume** [OptimalBits/bull#2070]
## Description

My use case is as follows - I have a NestJS application which has the need to repeatedly poll an API and update the state of a database based on the response of that API. I am using NestJS bull https://www.npmjs.com/package/@nestjs/bull for this to have a separate process to handle this task. 

The problem I am facing is that, as it is a separate process, I have no access to things like database connections, which are part of the parent application process.

Is there a way to add support for this? Or is there a way I can go about handling this myself? I would prefer to not create separate connections for each process that ends up running.

## Minimal, Working Test code to reproduce the issue.

NestJS service that is the entrypoint to adding things to the queue
```
import { Injectable, Inject } from '@nestjs/common';
import { SomeService } from './someservice.service'; // I'D LIKE TO BE ABLE TO ACCESS THIS SERVICE IN THE PROCESS FUNCTION. THIS CONTAINS DATABASE DEPENDENCIES
import { Queue } from 'bull';
const QueueBull = require('bull');
import { InjectQueue } from '@nestjs/bull';
import { createConnection, getConnection, getConnectionManager } from 'typeorm';

@Injectable()
export class QueuemanagerService {
  constructor(
    @Inject(SomeService)
    private readonly lteLocationService: LteLocationService,
    @InjectQueue('status')
    private readonly queue: Queue,
  ) {}

  async enqueue(locationId: string) {
    await this.queue.add('statusProcessing', {
      locationId,
    },
    {
      delay: 3000,
      removeOnComplete: true,
      repeat: {
        cron: '* * * * *',
        limit: 2
      },
     }
    );
  }
```
The separate process function
```
import { DoneCallback, Job } from 'bull';
import { Logger } from '@nestjs/common';
import { createConnection, getConnection, getConnectionManager } from 'typeorm';
import { SomeService } from 'someservice.service';

const sleep = (waitTimeInMs) => new Promise(resolve => setTimeout(resolve, waitTimeInMs));

// IS THERE ANY WAY FOR ME TO INJECT SomeService INTO THE PROCESS? MAYBE BY WRAPPING THIS FUNCTION?
export default async function (job: Job, cb: DoneCallback): Promise<void> {
  // the only way for me to do anything here is create a new connection
  const logger: Logger = new Logger('test');
  sleep(10000);
  cb(null, 'It works');
}
```

## Bull version
3.22.8

## Additional information
If there is no way to get around this, what would be the recommended approach here? 

I came across this example https://github.com/cgarnier/nestjs-bull-example - is this the recommended approach? Seems like what that does is running the process worker not as a "separate process" from the same application, but instead an entirely separate application itself.

**Comment by manast** [comment]
Why are you so concerned about creating a new connection for every process? unless you have a huge amount of concurrency this should never be a problem. Remember, processes are reused for every job, only concurrency determines the amount of parallel processes open at any given time.
