### ISSUE TITLE
Workers stop processing jobs - zombies

### ISSUE THREAD

**Issue by JVMartin** [OptimalBits/bull#2072]
I have been running Bull in production Kubernetes HPA setups, processing tens of millions of jobs per day.

Fairly regularly (at least once or twice a month), all of the workers in the entire system (for instance, while the HPA is set to 5 replicas) will just go silent at the same time. No errors, no resource consumption issues, no apparent memory leaks or issues of any kind. They just stop processing jobs, and the jobs back up in Redis indefinitely, until we manually delete / recycle all of the pods. Then jobs are processed again as normal.

Looks like this:
![image](https://user-images.githubusercontent.com/4450814/122590661-b5a0bc00-d016-11eb-8016-9cdc930f0c40.png)

This is, obviously, a huge problem that makes Bull unreliable in production systems. And it's one that's happening to several people I've spoken to using Bull in production systems. Another comment on the same issue here: https://github.com/OptimalBits/bull/issues/925#issuecomment-431319435

My hope had been that this only happens to super old pods, so I implemented daily pod recycling. But it happens regardless of how fresh the pods are.

We either need to address the underlying issue, or we need _some possible_ mechanism for implementing a health check on the workers so they can immediately be recycled if they are no longer processing jobs, but there are jobs backing up in the queue.

I have no idea where to begin on either of these problems, so I highly appreciate any insights or advice you can give me on either remediation path.

I'm going to spend some time attempting to implement a Kubernetes deployment health check that would identify and recycle silent pods, but again I'm not sure how exactly this would work. Maybe it would maintain a timestamp of the last time a job was processed by this particular worker, then look at Redis to see how many jobs were there, and if the jobs were over a certain threshold, and the timestamp was a certain distance in the past, it would return a failure response to indicate the pod was no longer healthy.

**Comment by rosslavery** [comment]
Just to say we had a similar issue on a very similar configuration (GKE + Memorystore). We haven't had it happen in quite a while and I honestly don't remember what changed to fix it. For us though the underlying cause was the Bull .lua scripts failing when Redis would start throwing:
`BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.`

At that point we had to basically nuke the Redis contents.

We've also toyed with various methods for worker health checks in similar ways you were imagining. We tried polling the completed queue and waiting queue 3 times, and comparing the completed count each time. If the number never increased we considered the worker dead and would SIGTERM it. That wasn't the entirety of the code but yeah, that was the general approach.

**Comment by manast** [comment]
@JVMartin One thing to look is to check if the workers are actually connected to Redis or if they may have lost connection (that would explain why they do not continue processing jobs). You can use redis CLIENT LIST command for some low level output (https://redis.io/commands/client-list), and/or also use the getWorkers api in the Queue class: https://github.com/OptimalBits/bull/blob/edfbd163991c212dd6548875c22f2745f897ae28/lib/worker.js#L23

**Comment by manast** [comment]
Basically what is most likely happening is that the workers are loosing the connection to redis and unable to reconnect for some reason (or exhausted all the reconnection attempts, check ioredis documentation for this), also make sure you have error listeners correctly setup on the workers so that you may not miss some error that could explain this behaviour.

**Comment by JVMartin** [comment]
@rosslavery Thanks for taking the time to share your story, I'm glad you got it resolved. I have set up similar health checks, which I'll document below.

@manast Thank you for the suggestions. I will play around with `.getWorkers()` and see if I can use it to strengthen our health checks.

To anyone who is curious, here is how I implemented working health checks.. however, this only works for systems where ALL workers are processing at least 1 job every N minutes, and there are no "lulls" in the system. If there is a lull, workers will be considered zombies and killed, when in reality there are simply no jobs to process.

Luckily, in our systems, usually there are thousands of jobs per minute so this is a good enough setup for us.

We are using NestJS with Terminus-based health checks https://docs.nestjs.com/recipes/terminus

First, I implement a HealthTrackerService for job processors:
```typescript
import { Injectable } from '@nestjs/common';

/**
 * A simple service that keeps track of the last time we processed a job.
 * Used by the worker health check system to ensure that a worker is killed if
 * it stops processing jobs.
 *
 * See:
 * https://github.com/OptimalBits/bull/issues/2072
 */
@Injectable()
export class HealthTrackerService {
  private lastProcessed: Date;

  constructor() {
    this.lastProcessed = new Date();
  }

  public markJobProcessedNow(): void {
    this.lastProcessed = new Date();
  }

  public getLastProcessed(): Date {
    return this.lastProcessed;
  }
}
```

Next, I inject it into our base processor class, so that every time a job is processed, the "lastProcessed" in-memory timestamp is updated:
```typescript
import { Job } from 'bull';
import { Logger } from 'pino';

import { HealthTrackerService } from '../services/health-tracker.service';

export abstract class BaseProcessor<JobType> {
  protected constructor(
    protected readonly logger: Logger,
    protected readonly healthTrackerService: HealthTrackerService,
  ) {}

  public abstract async doProcess(job: Job<JobType>): Promise<void>;

  public async wrappedDoProcess(job: Job<JobType>): Promise<void> {
    this.healthTrackerService.markJobProcessedNow();

    await this.doProcess(job);
  }
}
```

Now I can create a Terminus-compatible "worker" health indicator service:
```typescript
import { Injectable } from '@nestjs/common';
import { HealthIndicator, HealthIndicatorResult } from '@nestjs/terminus';
import * as moment from 'moment';

import { HealthTrackerService } from '../../queues/services/health-tracker.service';

@Injectable()
export class WorkerHealthIndicatorService extends HealthIndicator {
  constructor(private readonly healthTrackerService: HealthTrackerService) {
    super();
  }

  public async check(key: string): Promise<HealthIndicatorResult> {
    const lastProcessed = moment.utc(this.healthTrackerService.getLastProcessed());
    const minutesAgo = moment.utc().diff(lastProcessed, 'minutes');

    const isHealthy = minutesAgo < 5;

    return super.getStatus(key, isHealthy, { message: `Last processed a job ${minutesAgo} minutes ago.` });
  }
}
```

In this case, we just mark the worker unhealthy if it has not processed any jobs in 5 minutes.

Finally, we implement a Terminus-standard HealthController specifically for workers:
```typescript
import { BeforeApplicationShutdown, Controller, Get, HttpException } from '@nestjs/common';
import { HealthCheck, HealthCheckService, HttpHealthIndicator, TypeOrmHealthIndicator } from '@nestjs/terminus';
import { InjectPinoLogger } from 'nestjs-pino/dist';
import { Logger } from 'pino';

import { sleep } from '../../shared/utils/misc';
import { WorkerHealthIndicatorService } from '../services/worker-health-indicator.service';

@Controller()
export class HealthController implements BeforeApplicationShutdown {
  private shuttingDown: boolean = false;

  constructor(
    private readonly health: HealthCheckService,
    private readonly http: HttpHealthIndicator,
    private readonly typeOrm: TypeOrmHealthIndicator,
    private readonly worker: WorkerHealthIndicatorService,
    @InjectPinoLogger(HealthController.name)
    private readonly logger: Logger,
  ) {}

  async beforeApplicationShutdown(signal?: string): Promise<void> {
    this.logger.info(`Received signal ${signal}; failing readiness checks.`);

    this.shuttingDown = true;

    // Give us time to be marked as un-ready by Kubernetes, and respond to
    // all currently processing jobs.
    await sleep(15 * 1000);
  }

  @Get('health/liveness')
  @HealthCheck()
  public liveness() {
    return this.health.check([
      () => this.http.pingCheck('http', 'https://google.com', { timeout: 1000 }),
      () => this.typeOrm.pingCheck('database'),
      () => this.worker.check('worker'),
    ]);
  }

  @Get('health/readiness')
  public readiness() {
    if (this.shuttingDown) {
      throw new HttpException('Not ready for new traffic', 500);
    }

    return { status: 'ok' };
  }
}
```

**Comment by manast** [comment]
Thanks for the workaround. My two cents here is that it is important to emphasise this solution is a workaround and the underlying problem has not been identified, i.e., why do the workers in this particular setup stop processing jobs. As mentioned above my bet would be on some kind of hidden connection error to redis.

**Comment by DocX** [comment]
+1 Happened to us just today. No logs, no errors, etc. just stopped processing jobs. Restarting the worker solved it.

+1 Having some easy way to "ping" specific worker. Perhaps `Queue.start()` could return some UUID identifier of the worker, then we could have something like `Queue.ping(workerUUID, timeout) => Promise<boolean>`. It could be implemented as job in the queue with some special marking to separate it from "users" jobs and process it internally in the Bull queue?

**Comment by manast** [comment]
@DocX do you have listeners attached to the worker instance listening for the "error" event?

**Comment by DocX** [comment]
We did not have. We will add it and will see if this issue happens again, what was the error.

**Comment by dtboy1995** [comment]
+1 Happened to us every day. No logs, no errors, etc. just stopped processing jobs. Restarting the app solved it.

**Comment by manast** [comment]
@dtboy1995 there is no point in reopening if there is no way to reproduce it...
