### ISSUE TITLE
Bull using not cleaning up set causing huge memory usage

### ISSUE THREAD

**Issue by hisabimbola** [OptimalBits/bull#2074]
## Description
We are using bull queue and a fast processing jobs. We noticed that there is a key "wait:added" that is running into gigs of data of us. I feel like this is not been cleaned up.

I wonder if this is a known issue and how to clean it up or avoid the build up
## Bull version
3.22.8

**Comment by manast** [comment]
What kind of data is inside that key? reason I am asking is that such key is not used by bull...

**Comment by manast** [comment]
oh sorry, it is actually used by the rate limiter system. You are using the rate limiter right?

**Comment by hisabimbola** [comment]
@manast, no we're not using rate limiter... is it enabled by default?

**Comment by manast** [comment]
Sorry, I was mistaken by a comment in the source code... I am looking into this now.

**Comment by manast** [comment]
I could only find one place where bull is actually writing to a key "added", which is in the "reprocess" lua script used by "retry", I will remove this code since it is obsolete must be something that has hanged around from older versions, however that could barely explain your case unless you are using "retry" massively, are you?

**Comment by hisabimbola** [comment]
Yes, we are massively retrying jobs (usually 1-5 times but we could retry up to 200 times for some jobs). We fail early and as could have jobs that could not get the resource lock and this situation happens a lot for us.

Is there any negatively impact of this approach?

**Comment by manast** [comment]
no, but it would explain the issue :)

**Comment by hisabimbola** [comment]
As a quick fix for now, can we just delete the key or is it used anywhere?

**Comment by manast** [comment]
yes you can delete it, and a new release is coming that do not create that key anymore so you can upgrade in a couple of minutes.

**Comment by hisabimbola** [comment]
Thanks a lot for the fast response and quick fix @manast  🙏🏾 🙇🏾 ❤️
