### ISSUE TITLE
survey for how much someone will pay is collecting bad data

### ISSUE THREAD

**Issue by evilbuck** [OptimalBits/bull#2076]
You're asking how much someone will pay for a course. You're guaranteed to get bad data. Put up a split test that actually charges for a future course. (You can choose to immediately void the charge). This will be more accurate. Right now, your conversion numbers will be much higher than if you actually charged, and you'll see results of a higher dollar amount because people answer more positively when there isn't any skin in the game.
Test my theory and redirect after the submission with a purchase page with the dollar amount they selected. See how many buy for exactly what they said they would purchase for.

My 2 cents. Good luck.

**Comment by manast** [comment]
Thanks for the feedback. You are correct in what you are saying. So in what you propose I would get a lower boundary and the real number would be somewhere in between since paying for a non existing course will for sure convert much less than one that you can get right away.

**Comment by evilbuck** [comment]
You might get a lower number than if the course is already available. There are so many other factors to purchasing decisions and human purchasing behavior; it doesn't always follow reason. Especially for us engineer minded folk that are more analytical. It's more emotion that determines your conversion. Availability of the product when you purchase is only one variable. Think of how many people waited in line for a Tesla model 3 or more recently a F150 Lightning truck even though it's release is a year or more out.
The marketing materials that at show what the product might be like will likely be enough for most people to make a purchasing decision. Especially if you offer a refund anytime before the actual course is released or acquired. 

At the end of the day, you really just want to find out what someone will be willing to spend on the course. The only way to do that is to ask them to spend the money. Kickstarter campaigns prove this, and they don't offer refunds.

There are so many ways to approach this, but I'd start with creating a minimal amount of mockups and videos before developing the product, then create multiple price points and see what converts best to hit that sweet spot of margin and volume. I'd sell it as a coming soon with limited seats and free upgrades to revisions to the course. Anyone that paid a higher price than you end up selling it for (during the split test), just refund the difference to keep them happy customers. Everyone that underpaid, you send them a nice email explaining that you're raising your prices, but they get to keep their discounted product. They'll be happy.
Just get creative on how to sell it before it's finished. You won't need to lie to anyone. Just show your vision with as little effort as possible in order to sell it, mockups and or short promo videos etc.... Offer it as limited seating. Pre-sales. Definitely have a funnel too. Collect the email and info before asking for payment. You can always email them later with lower pricing for those that bail out on the payment step. It's just more data to find your pricing. 
The beauty is that you can do as little or as much as you want. If you wanted to redirect to a sales page after your current form, you could do that. It just won't be as precise as when you get your product together.

**Comment by manast** [comment]
Wow. Thanks for the detailed response, really helpful.
