### ISSUE TITLE
Job is being dropped when bounceBack set to true with rate limit

### ISSUE THREAD

**Issue by nguyenvudao** [OptimalBits/bull#2082]
## Description
I want to use the rate limit and keep the order of the job so I think the order would not be messed up if we keep it in a waiting queue.
The problem is that if the queue reaches a limitation, there is no job added to the waiting queue but saved into Redis.

## Minimal, Working Test code to reproduce the issue.
```

import BullQueueExample from 'bull';
  
const queue = new BullQueueExample('queue_1', {
    limiter: {
      duration: 600000,
      max: 2,
      bounceBack: true,
    },
  });

(async function () {
    for (let i = 0; i < 100; i++) {
      await queue.add({ data: { a: Math.random().toString(36).substring(7) }, accountId: '1' });
    }
  })().catch(console.error);

  queue
    .process(1, async (job) => {
      console.log('JOB HERE: ', job.data);
    })
    .catch(console.error);

```
And the result is:

```
JOB HERE:  { data: { a: '97larr' }, accountId: '1' }
JOB HERE:  { data: { a: 'txho2o' }, accountId: '1' }
```

## Bull version
3.22.9
## Additional information
OS: MacOS 15.5
Redis: 6.2.1

**Comment by joaoschaab** [comment]
Same here +1

**Comment by Drieger** [comment]
I'm facing the same problem using this options.

**Comment by nguyenvudao** [comment]
This issue won't be fixed. We have to accept it guys.

**Comment by thevan-beincom** [comment]
+1

**Comment by manast** [comment]
You should upgrade to BullMQ as the rate limiter works much more accurately than in Bull.
