### ISSUE TITLE
Besides a done() function, job processors should also support promises.

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#21]
Bull should support returning promises in the processor callbacks besides a simple done function.

**Comment by diffalot** [comment]
I think this is a great idea, and I'd be happy to help test it out, so I'll be following this thread.

For me, it'll come in very handy with a scraper I'm writing where I want to run a single queue that scrapes with phantomjs but uses a different javascript payload with each level of the scrape (i.e. scrape google trends for each country, then scrape search results in each country for that trend) just by passing the name of the payload and it's options in the job data.

here's a quick suggestion about how I'd eventually like my code to look (though I'd be happy with something else entirely):

```javascript
      scrapeQueue.add({
        payload: 'getLatestTrends',
        payloadOptions: {
          country: country
        },
        logMessage: 'get latest trends for '+ country.name,
      })
      .then(function(added){
        added.completed
        .then(function(results){
          scrapeQueue.add({
          payload: 'getSearchResults',
          payloadOptions: {
            country: country
            trend: results.trendName
          },
          logMessage: 'get links for '+ results.trendName +' in '+ country.name,
        });
      });
```

**Comment by manast** [comment]
I think this kind of use cases are actually becoming more and more common. It is in fact some kind of distributed state machine, you have states and workers that can be working on different states in parallel. 
The example code you posted illustrates the problem, but it would not really work in practice. 
I am thinking on a solution that would be built on top of bull, and that will requires several queues, where every queue represents a state in the distributed state machine. Not sure when I will have a prototype ready though...

**Comment by diffalot** [comment]
After playing with it some more (and switching to sending to a message queue from the processing queue, as you recommend in the readme), I see exactly why my previous suggestion won't work: there's no guarantee that the program that adds the job to the queue will be the one to further process the data returned by the queue's processor, in fact, doing so would be a bad design.

Thanks for even reading my suggestion 😝

**Comment by manast** [comment]
And thats exactly why we need a distributed state machine on top of a persistent queue system like bull, so that we can have different processes working on different states all in parallel and with the guarantee that if there is at least one process online the machine will continue to work and move forward.

**Comment by manast** [comment]
This has been fixed for some time ago.
