### ISSUE TITLE
queue.process() - concurrency incorrect

### ISSUE THREAD

**Issue by alucky4eg** [OptimalBits/bull#2108]
## Description
queue.process('name', concurrency) - concurrency stacks up for all queue.

why do not use limiter here? this setting is the same with limiter.max

## Minimal, Working Test code to reproduce the issue.
```ts
import Bull from 'bull';
import { EQueue } from '../../interfaces';

const p = async job => {
  console.log(`[${job.id}] STARTED ${job.data}`);
  await new Promise(resolve => setTimeout(resolve, 5_000));
  console.log(`[${job.id}] FINISHED ${job.data}`);
  return;
};

(async () => {
  const options: Bull.QueueOptions = {
    limiter: {
      max: 100,
      duration: 1000,
      bounceBack: false,
    },
  };
  const queue = new Bull(EQueue.system, options);

  queue.process('test', 5, p);
  queue.process('test1', 100, p);

  const actions = [];
  for (let i = 0; i < 100; i++)
    actions.push(i);

  await queue.addBulk(actions.map(_ => ({ name: 'test', data: _ })));
})();
```

## Bull version
3.26.0

## Additional information
i think this property should affect only process, not all queue

**Comment by manast** [comment]
This is the intended behaviour even if it feels unnatural, there are no plans to change it for the time being: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueprocess
