### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:6379 when using: new Queue('my-queue', {redis: 'redis://redis:6379'})

### ISSUE THREAD

**Issue by stage88** [OptimalBits/bull#2116]
## Description

I think this change here https://github.com/OptimalBits/bull/commit/2a295691b88318ff64beaa7b83e03487854a7fe4#diff-afa7a0a70da4b0fa42349adcdb862c6f079f980b4051ca651d929290f34a29c7L280 has broken the ability to connect using:
```
const queue = new Queue('my-queue', {redis: 'redis://redis:6379', ...otherOptsHere});
```

I have upgraded from 3.22.11 to 3.26.0 and now I get Error: connect ECONNREFUSED 127.0.0.1:6379.

Anyway, I've updated my code to use:
```
const queue = new Queue('my-queue', 'redis://redis:6379', otherOptsHere);
``` 

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

Upgrade from 3.22.11 to 3.26.0 

## Bull version
3.26.0

**Comment by F3WS** [comment]
I hit this problem using redis on heroku so I'm not sure if their solution will help you but it may, it involves adding the following tls object to the options:

`const queue = new Queue('my-queue', process.env.REDIS_URL, {
  redis: { tls: { rejectUnauthorized: false } },
})`

Refs:
https://help.heroku.com/HC0F8CUS/redis-connection-issues
https://devcenter.heroku.com/articles/heroku-redis#connecting-in-node-js

**Comment by F3WS** [comment]
I hit this problem using redis on heroku so I'm not sure if their solution will help you but it may, it involves adding the following tls object to the options:

`const queue = new Queue('my-queue', process.env.REDIS_URL, { redis: { tls: { rejectUnauthorized: false } }, })`

Refs:
https://help.heroku.com/HC0F8CUS/redis-connection-issues
https://devcenter.heroku.com/articles/heroku-redis#connecting-in-node-js

**Comment by manast** [comment]
No, the problem seems to be a fix that has actually created a breaking change, I am looking into it now.

**Comment by manast** [comment]
@stage88 actually after studying this a bit more, even though the previous version worked, it was undocumented and not really supported, i.e. sending a string with redis options attached to it, even if possible to do with javascript it is not a good pattern. I could not find any such example in Bull's documentation either, so I am going to close this issue now.

**Comment by stage88** [comment]
All good thanks @manast, it was an easy fix. I think my opts where leftover when I migrated from Kue.
