### ISSUE TITLE
Queue cannot be created with redis config as string

### ISSUE THREAD

**Issue by ales-albert-kilbergr** [OptimalBits/bull#2118]
## Description

Queue object cannot be created with `options.redis` as string any more. Which has been possible in version `3.23.0` 

## Minimal, Working Test code to reproduce the issue.
The change causing the change of behavior lays here:

https://github.com/OptimalBits/bull/compare/v3.23.3...v3.25.0 in `Queue.js` line 280

![Screenshot 2021-07-28 110242](https://user-images.githubusercontent.com/79090159/127297707-4c153c66-4fb8-4862-9534-55b194dbcddf.png)

The `@types/bull` library declares `redis` property as: `Redis.RedisOptions | string | undefined;` but the `Queue.js:280` by using `_.assign(...)` breaks the string into an object. The difference between both versions (3.23.0 - 3.25.0) looks then like this:

```
//@v3.23.0
redis://@foo:6379

//@v3.25.0
{
      '0': 'r',
      '1': 'e',
      '2': 'd',
      '3': 'i',
      '4': 's',
      '5': ':',
      '6': '/',
      '7': '/',
      '8': '@',
      '9': 'f',
      '10': 'o',
      '11': 'o',
      '12': ':',
      '13': '6',
      '14': '3',
      '15': '7',
      '16': '9',
      connectionName: 'bull:dGVzdFF1ZXVl'
    }

```

## Bull version
3.23.0 vs 3.25.0

**Comment by ales-albert-kilbergr** [comment]
[https://github.com/nestjs/bull/issues/869](url)

**Comment by manast** [comment]
This was actually an undocumented feature that should not be possible in the first place, please see this: https://github.com/OptimalBits/bull/issues/2116
But if there are external llibraries depending on bull that use this approach it may be worth fixing it.

**Comment by eliotik** [comment]
Not only external libraries can be a problem but how do you suppose to split url provisioned to environment to host, port, password, username?

**Comment by manast** [comment]
@eliotik you just pass the "host" option like you do in ioredis: https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options

**Comment by manast** [comment]
@eliotik or well, maybe I do not understand what you mean... you can either pass the url as a string and/or you pass an options object with whatever options you need. What you cannot do is passing a string with options attached to it, which imho seems like an antipattern to me.

**Comment by eliotik** [comment]
> @eliotik you just pass the "host" option like you do in ioredis: https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options

not exactly. `host` is url where redis is located, like `boomboom.com`.
what you actually use is a fully loaded parametrized url:
`redis://username:yourfancypassword@host:port/dbid`
so you cannot just take this string and define it as a value for `host`, or you can? :)

**Comment by manast** [comment]
@eliotik I think you are misunderstanding the issue. You can still do:  ```new Queue(queueName, 'redis://username:yourfancypassword@host:port/dbid', otherRedisOpts);```
