### ISSUE TITLE
Queue dosen't continue

### ISSUE THREAD

**Issue by mateuszbrylski** [OptimalBits/bull#212]
Hi!

I add over 2000 objects in a queue and sometime the queue stops without any feedback. I tried to restart the server but this don't help. Have you any idea?

Cheers

**Comment by manast** [comment]
with so little information we cannot give you any valuable feedback...

**Comment by mateuszbrylski** [comment]
I have a Little Server who imports Data to mongodb. The Data comes from csv files but this works. 
I dont know what Informations do you need ..

**Comment by mateuszbrylski** [comment]
Ok - I try to import data from csv files this works also fine. The data are also added in the queue and the queue also starts to work, however, stops after seconds again and then nothing passes it also gives no errors or something else.

**Comment by misterjt** [comment]
The same problem.

**Comment by jacobespersen** [comment]
+1

**Comment by manast** [comment]
I will close this since there is not enough information to start an investigation or bugfix, reopen if needed.
