### ISSUE TITLE
Place delayed jobs at the end of the waiting list

### ISSUE THREAD

**Issue by kietheros** [OptimalBits/bull#2128]
## Description
I have a queue with rate limiter

    limiter: {
        max: 5,
        duration: 10000,
        groupKey: 'sourceId'
    }

    // add 20 jobs with sourceId 'Z'
    for (let i = 0; i < 20; i++) {
        await queue.add({
            sourceId: 'Z'
        }, {
            jobId: `Z:${i+1}`
        });
    }
    
    // add 100 jobs with sourceId 'A', 'B', 'C', 'D', 'E'
    for (let i = 0; i < 20; i++) {
        let sourceIds = ['A', 'B', 'C', 'D', 'E'];
        for (let j = 0; j < 5; j++) {
            const sourceId = sourceIds[j];
            await queue.add({
                    sourceId: sourceId
                }, {
                    jobId: `${sourceId}:${i+1}`,
                });
        }
    }
    
    queue.process(1, async (job) => {
        logger.debug('Start job', job.id);
        await sleep(2000); // sleep 2s
        logger.debug('Finish job', job.id);
    });

Because of rate limiter, some jobs of source Z are moved into delayed queue. After amount of time,  jobs of source `Z` are placed at the beginning of waiting list. The beginning of waiting list here is the left side, so 'Z' jobs will not be processed as soon as the worker is idle.

I have read docs
>  a delayed job will not be processed directly, instead it will be placed **at the beginning of the waiting list** and processed as soon as a worker is idle.

I wonder that these jobs have to be placed at the *end of the waiting list (right side) to be processed as soon as a worker is idle*. ???
Could anyone explain me about this problem ? Thanks !
## Bull version
3.27.0

**Comment by kietheros** [comment]
@manast 
Might I take a moment of your time to ask a small question !!!

In above test case, why delayed jobs are placed at the left of waiting list, and will not be processed immediately, because workers pop jobs from the right of waiting list.

However, docs says:
> a delayed job will not be processed directly, instead it will be placed at the **beginning of the waiting list and processed as soon as** a worker is idle.

**Comment by manast** [comment]
When a delayed job is moved back to the wait list it is placed to the head of the list, i.e. it will be next to be processed... of course if other delayed jobs are moved to the wait list after the first one then they will move the first one back in the queue.
