### ISSUE TITLE
Delayed jobs are moved back to the left of wait list instead of the right as in docs

### ISSUE THREAD

**Issue by kietheros** [OptimalBits/bull#2131]
#### (An easy to reproduce test case will dramatically decrease the resolution time.)
Here is minimal test code

        async function sleep(time) {
            return new Promise(r => {
                setTimeout(() => r(), time);
            });
        }
    
        const queue = new Bull('queue', 'redis://127.0.0.1:6379', {
            limiter: {
                max: 1,
                duration: 4000,
                groupKey: 'sourceId'
            }
        });
        // add jobs, each job takes 2s to complete
        
        // 1. add 10 jobs with sourceId 'Z', they will hit rate limit (4 seconds / 1 job)
        for (let i = 0; i < 10; i++) {
            await queue.add({sourceId: 'Z'}, {jobId: `Z:${i+1}`});
        }
    
        // 2. add 50 jobs with sourceId 'A', 'B', 'C', 'D', 'E', they will be arranged in order not to hit rate limit
        for (let i = 0; i < 10; i++) {
            await queue.add({sourceId: 'A'}, {jobId: `A:${i+1}`});
            await queue.add({sourceId: 'B'}, {jobId: `B:${i+1}`});
            await queue.add({sourceId: 'C'}, {jobId: `C:${i+1}`});
            await queue.add({sourceId: 'D'}, {jobId: `D:${i+1}`});
            await queue.add({sourceId: 'E'}, {jobId: `E:${i+1}`});
        }
    
        // worker, a job takes 2 seconds to complete
        queue.process(1, async (job) => {
            console.log(new Date().toLocaleString(), 'Start job', job.id);
            await sleep(2000);
        });

**Results:**
>8/10/2021, 6:45:12 PM Start job Z:1:Z
8/10/2021, 6:45:14 PM Start job A:1:A
8/10/2021, 6:45:16 PM Start job B:1:B
............................................................
8/10/2021, 6:46:44 PM Start job A:10:A
8/10/2021, 6:46:46 PM Start job B:10:B
8/10/2021, 6:46:48 PM Start job C:10:C
8/10/2021, 6:46:50 PM Start job D:10:D
8/10/2021, 6:46:52 PM Start job E:10:E
8/10/2021, 6:46:54 PM Start job Z:2:Z
8/10/2021, 6:46:58 PM Start job Z:8:Z
8/10/2021, 6:47:02 PM Start job Z:5:Z
8/10/2021, 6:47:06 PM Start job Z:3:Z
8/10/2021, 6:47:10 PM Start job Z:10:Z
8/10/2021, 6:47:14 PM Start job Z:9:Z
8/10/2021, 6:47:18 PM Start job Z:4:Z
8/10/2021, 6:47:22 PM Start job Z:6:Z
8/10/2021, 6:47:26 PM Start job Z:7:Z

**Z:2 -> Z:10 are processed after other type of jobs.**

**My expectation:**
Z jobs are added before 'A', ..., 'E' jobs. If they hit rate limit, after amount of time (4 seconds or some time), they should be processed again by worker.

When checking in redis, I found that delayed jobs are moved back to the left of wait list, so they are always processed after other jobs.

## Bull version
3.27.0

**Comment by manast** [comment]
The results seems correct to me. Since A-E jobs are not rate limited they will be processed than the rate limited jobs, not sure if I am missing something.

**Comment by manast** [comment]
However I am seeing that we are using LPUSH for delayed jobs: https://github.com/OptimalBits/bull/blob/develop/lib/commands/updateDelaySet-6.lua#L45
I will take a look into this...

**Comment by JohnWalshTempus** [comment]
Seconding this issue - I see the following in some code I'm running:
```
// Jobs are ordered by timestamp not priority - presumably incorrectly
<queue>.getJobs(["delayed"])
<queue>.getDelayed()


// Jobs are ordered by priority - presumably correctly
<queue>.getJobs(["waiting"])
<queue>.getWaiting()
```

I was planning to selectively promote a set number of jobs, but there's no way to ensure I'm promoting the most prioritized items

**Comment by manast** [comment]
@JohnWalshTempus that is correct. Delayed jobs are reinserted into the wait list according to their delayed argument. However depending on the priority they will be re-inserted at different positions.
