### ISSUE TITLE
Update/Change priority of jobs in queue.

### ISSUE THREAD

**Issue by jurampark22** [OptimalBits/bull#2159]
Hi there,

We're using bull as job scheduler and want to have feature like updating/changing priority of jobs which are already enqueued in  queue. I looked up existing issues but failed to find a any good solution.

One thing I'm going to try is accessing and updating native redis collection values but want to check if there's better way.

Thanks in advance!

**Comment by rezonant** [comment]
This would be great for me as well. Seems update() on Job would be better called updateData()

**Comment by vyushin** [comment]
The same question.
I have some thoughts:
To change priority we can remove the job from queue and then add new one (with new options)
BUT:
Before remove job we have to check job status. If the job already running we shouldn't remove because it can cause data corruption

**Comment by manast** [comment]
Updating a job's priority would need an atomic Lua script, however, it is unlikely a feature like this would land on Bull, as we are aiming at only bug fixing where new features have a higher chance to be implemented in BullMQ.
