### ISSUE TITLE
A good way to test against repetitive tasks against time

### ISSUE THREAD

**Issue by evanhuang8** [OptimalBits/bull#216]
Not a bug/issue, just wondering if anyone using `bull` has been doing testing for long-running, repetitive tasks.

For example, say I have a task that's designed to schedule itself everyday for the next day and then do something only on Tuesdays and Thursdays every week. Ideally I would be able to write a test that somehow simulates time and see how the task behaves as time goes on.

Are there any good ways to somehow control the time and make the queue thinks that it has hit certain time in the future?

**Comment by albertjan** [comment]
I remember using timecop for this kind of thing in ruby. There's an implementation in js: https://github.com/vesln/timekeeper

**Comment by evanhuang8** [comment]
Thanks for the note. Ended up using `sinon`'s `useFakeTimers`, works OK but I am hitting weird cases where some jobs are fired before their due date when I set the time, not sure if there is a bug in `bull` itself or just the quirkiness from faking time
