### ISSUE TITLE
Parallel jobs running concurrently 

### ISSUE THREAD

**Issue by CedricHadjian** [OptimalBits/bull#2162]
I came across this package today in the morning and I loved its features. I'm working on a software that should run async tasks in parallel using proxies, i.e each proxy would be a job and these proxies would be working on bots and making separate async calls. What do you recommend I look into? We are also planning on using taskforce.js, what are the main differences between taskforce.js and bull-board?

**Comment by manast** [comment]
Maybe you can get some inspiration and examples on real use cases here: https://blog.taskforce.sh/
