### ISSUE TITLE
How to Timeout a long running job in bull.

### ISSUE THREAD

**Issue by fusai19** [OptimalBits/bull#2166]
I have scheduled to run Fibonacci computation. I want to timeout the Job after 5 seconds if larger input data is given to compute fibonacci sequence. (I have considered fibonacci computation as an example, trying to stop a heavy job after "x" seconds.)

Basically, is there any way to stop a running job if it is not finished after "x" seconds.

I have tried to set timeout option when adding queue data, but looks like it did not work. 

Any help would be really great.

**Comment by cincodenada** [comment]
This question is probably better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/bull.js), but you are probably looking for the `timeout` option [as documented in the `add` method](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd).

**Comment by cincodenada** [comment]
Hey, following up here, I realized I made a bad assumption - the `timeout` option doesn't actually stop the job, it just marks it as failed. It's impossible for Bull to proactively stop a non-sandboxed job, and it doesn't seem to be implemented for sandboxed jobs.

I've opened a PR to be more explicit about this in the Reference doc, you can read my proposed changes here for a couple suggestions about how to accomplish this: https://github.com/OptimalBits/bull/blob/ee40daa01d552779c880d9fbfa6b844eb127abe5/REFERENCE.md#timeout-implementation

**Comment by fusai19** [comment]
Thank you @cincodenada for suggestions.
