### ISSUE TITLE
`moveToFailed` gives me `Missing lock for job failed` error

### ISSUE THREAD

**Issue by olegkalyta** [OptimalBits/bull#2170]
## Description
I have a task that takes 10-15 minutes to complete. 
1. Task goes to queue and becomes active
2. At some point in time, I need either to fail it or delete it.
I call `moveToFailed` or `clean` and both of them give me `Missing lock for job failed` error.

**Comment by ohad-cycode** [comment]
Any update on this issue?

**Comment by manast** [comment]
@ohad-cycode you just call moveToFailed with ignoreLock to true and it should work, doesn't it?
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#jobMoveToFailed

**Comment by manast** [comment]
@ohad-cycode you just call moveToFailed with ignoreLock to true and it should work, doesn't it?
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#jobMoveToFailed
