### ISSUE TITLE
queue.process doesn't get executed.

### ISSUE THREAD

**Issue by Sander1801** [OptimalBits/bull#2171]
## Description
queue.process is never getting executed in the example provided by Bull. The cluster module works fine.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
Using the example provided by Bull.

const Queue = require('bull');
const cluster = require('cluster');

const numWorkers = 8;
const queue = new Queue('test concurrent queue');

if (cluster.isMaster) {
    for (let i = 0; i < numWorkers; i++) {
        cluster.fork();
    }

    cluster.on('online', function (worker) {
        // Let's create a few jobs for the queue workers
        for (let i = 0; i < 500; i++) {
            queue.add({ foo: 'bar' });
        };
    });

    cluster.on('exit', function (worker, code, signal) {
        console.log('worker ' + worker.process.pid + ' died');
    });
} 
else {
    console.log("Lol")
    queue.process(function (job, jobDone) {
        console.log("Lol222")
        console.log('Job done by worker', cluster.worker.id, job.id);
        jobDone();
    });
}

## Bull version
Newest version.

## Additional information
Please, fix your documentation if I'm doing something wrong!

**Comment by manast** [comment]
The code works perfectly:
```ts
const Queue = require("bull");
const cluster = require("cluster");

const numWorkers = 8;
const queue = new Queue("test concurrent queue");

if (cluster.isMaster) {
  for (let i = 0; i < numWorkers; i++) {
    cluster.fork();
  }

  cluster.on("online", function (worker) {
    // Let's create a few jobs for the queue workers
    for (let i = 0; i < 500; i++) {
      queue.add({ foo: "bar" });
    }
  });

  cluster.on("exit", function (worker, code, signal) {
    console.log("worker " + worker.process.pid + " died");
  });
} else {
  queue.process(function (job, jobDone) {
    console.log("Job done by worker", cluster.worker.id, job.id);
    jobDone();
  });
}
```

```bash
$ node 2171.js
Job done by worker 1 1
Job done by worker 1 2
Job done by worker 1 3
Job done by worker 1 4
Job done by worker 1 5
Job done by worker 1 10
Job done by worker 3 8
Job done by worker 2 7
Job done by worker 5 6
Job done by worker 6 9
Job done by worker 1 13
Job done by worker 5 17
Job done by worker 2 16
Job done by worker 3 15
Job done by worker 6 18
Job done by worker 4 11
Job done by worker 1 19
Job done by worker 8 12
Job done by worker 3 22
Job done by worker 2 20
Job done by worker 5 21
Job done by worker 6 23
Job done by worker 7 14
Job done by worker 1 24
Job done by worker 4 25
Job done by worker 8 26
Job done by worker 2 30
Job done by worker 5 28
Job done by worker 3 29
```
