### ISSUE TITLE
Error: Missing lock for job with multiple node processes

### ISSUE THREAD

**Issue by enricodeleo** [OptimalBits/bull#2175]
## Description
I run two instances of bull workers on two different servers sharing the same Redis instance. Apparently, every job added is ran twice and often it produces "Error: Missing lock for job " error. I wonder if it is a known issue and if I can still get parallel instances consuming the same queue balancing workloads or I have to stick on a single bull instance. Can you please give me an hint?

## Bull version
3.29.2

**Comment by jericopulvera** [comment]
> ## Description
> I run two instances of bull workers on two different servers sharing the same Redis instance. Apparently, every job added is ran twice and often it produces "Error: Missing lock for job " error. I wonder if it is a known issue and if I can still get parallel instances consuming the same queue balancing workloads or I have to stick on a single bull instance. Can you please give me an hint?
> 
> ## Bull version
> 3.29.2

We are currently encountering this issue. Have you resolved it?
