### ISSUE TITLE
Error: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by hienlh** [OptimalBits/bull#2178]
## Description
I'm stucking with this issue in my Production server. When adding a job to queue, sometimes It throws an error "Cannot read property 'id' of undefined", I was using Bull Board to retry several times and it's work. I have double-checked my code and logging, so this exception is not from my code.

```
TypeError: Cannot read property 'id' of undefined
    at PayrollService.sendSystemEmailWithQueue (/app/dist/modules/payroll/payroll.service.js:60:106)
    at handlers.<computed> (/app/node_modules/bull/lib/queue.js:663:42)
    at Queue.processJob (/app/node_modules/bull/lib/queue.js:1098:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Bull version
I'm using **node v12.20.1**, **@nestjs/bull ^0.4.1**, **Redis 6.0.5**. I have tried both 0.4.1 and 0.3.1, but same issue.

**Comment by manast** [comment]
But according to your call stack the error *is* from your own code:
```
    at PayrollService.sendSystemEmailWithQueue (/app/dist/modules/payroll/payroll.service.js:60:106)
```

**Comment by manast** [comment]
I recommend you go to this file and check what is going on at line 60: ```/app/dist/modules/payroll/payroll.service.js```

**Comment by hienlh** [comment]
I have checked all file in trace but nothing positive, that's reason why I posted here to get some helps
![image](https://user-images.githubusercontent.com/36977998/137244635-d65da359-dc72-411e-8063-de2a27961b38.png)

**Comment by hienlh** [comment]
Yes, that is the same, you can see this is file in server.
![CleanShot 2021-10-14 at 11 01 30](https://user-images.githubusercontent.com/36977998/137249696-b2ffe45f-21f8-4836-8677-42ec8bcad73d.png)

**Comment by cincodenada** [comment]
I notice in your screenshot your job function seems to be both using a `done` callback and returning a promise. I don't know if this is related to you issue or not, but it should only be doing one or the other - either use a regular function and call `done()`, or return a promise, but not both.

**Comment by manast** [comment]
@cincodenada thanks for your reply. I will close now since there is no more response from the poster.
