### ISSUE TITLE
Job stalls and retries despite timeout

### ISSUE THREAD

**Issue by vonba** [OptimalBits/bull#2182]
## Description

Lengthy upload jobs running ~10 minutes stall and are retried after 30 seconds (the default timeout), even though the upload is still active and timeout was set to 10 minutes. If I set it to 10 milliseconds they immediately stall, so it is taking the timeout into account. As far as I can see from the code this is a simple `setInterval()` call, so I shouldn't be hitting any limit here.

## Minimal, Working Test code to reproduce the issue.

In web server process:

```
    const jobOpts = {
        attempts: 1,
        timeout: 10 * 60 * 1000, // 10 minutes
    }
    const job = await workQueue.add({playerId, requestFile: req.file, requestBody: req.body}, jobOpts)
    workQueue.on('global:stalled', function (job) {
        console.log(`Job ${job} stalled`)
    })

```
In worker process:

```
  workQueue.process(maxJobsPerWorker, async (job, done) => {      
    console.log('Accepting upload job...', job.id)
    console.log(await workQueue.getJob(job.id))
    const { data } = job
    newVideo = await uploadToBucket({
        playerId: data.playerId, 
        requestBody: data.requestBody, 
        requestFile: data.requestFile,
        progress: (progressValue) => job.progress(progressValue),
    })
    done(null, newVideo)
  });
}
```

Notes:
In the console I am seeing "Accepting upload job..." and the following options for the job:

```
Job {
      opts: {
      attempts: 1,
      timeout: 600000,
      delay: 0,
      timestamp: 1634753060062,
      backoff: undefined
    }, 
    ...
}
```

It looks to me like the timeout should be set 10 minutes (600000 ms). Despite this, after 30 seconds I am seeing the `stalled` event and the job being accepted a second time.

## Bull version
3.29.3

## Additional information

The two processes are running on Heroku.

**Comment by cincodenada** [comment]
It sounds like Bull is unable to [renew the job lock](https://github.com/OptimalBits/bull#important-notes) - have you reviewed the suggestions there? It doesn't sound like the job is dying, but is `uploadToBucket()` heavy/synchronous enough that it could be hanging the event loop for 30 seconds?

The example you gave is running in a single process, have you tried using sandboxed processes instead (see the "separate process" section of [Queue#process()](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueprocess)? You could also try adjusting the parameters mentioned in "Advanced Settings" in the [Queue docs](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queue), but as mentioned there use caution.

I haven't tested this, but I believe you can set `maxStalledCount` to 0 to disable retrying stalled jobs, although that's more of a workaround than anything.

**Comment by vonba** [comment]
@cincodenada thank you for your comments. What I'm reading in the link you sent makes sense, except that the task is not CPU intensive (it is uploading to an S3 bucket). So I don't quite understand how the lock would fail to renew since neither of the two conditions are fulfilled (not crashed and not CPU intensive).

I am already running the upload code in a separate worker process like I describe above. Or did I misunderstand what you meant by single process?

**Comment by cincodenada** [comment]
Yeah, I'm unsure what could be causing the problem if it's just uploading to S3. A couple debugging steps that my yield helpful info:
 - Could you try you setting a listener for the `lock-extension-failed` event, to see if that occurs just before the job stalls? That will also give you an `err` object that may be useful in debugging.
 - Just to narrow things down, if you replace the upload with some sort of delay (e.g. https://www.npmjs.com/package/delay) do you still get the stalls? That would determine if it's something about the workload, or if there's something going wrong elsewhere in the system. 

As for the processes: there is an additional level of process isolation available - as-is, your worker process is still doing two things: processing the job, and communicating with the Redis queue to fetch and update the jobs. You can run just the processing part in a separate node process - my apologies, on second read the docs I linked to don't actually explain that very well and need to be updated. Fortunately, there's a good how-to on it in the [Separate Processes section](https://github.com/OptimalBits/bull#separate-processes) of the main README instead.

I'm curious as to what's going wrong here, but setting up processors as separate processes may sidestep the issue - it eliminates contention over the node event loop, as the queue logic is isolated from the worker logic.

**Comment by vonba** [comment]
Thanks for your continued input here.

Since my original post I unfortunately had to move on from Bull because I had to deliver the project. I found that I was able to perform the tasks with the same amount of code by just spawning a worker process to take care of the upload.

If I remember correctly, in the end it actually didn't even seem possible to let a Heroku child process handle the upload since it doesn't have access to the file system where the file was uploaded, and since sending the whole file as part of the job data isn't possible unless it's tiny. Using Bull is still the approach officially recommended by Heroku. But this is a Heroku issue.

Realistically it'll be a while before I can go back and investigate with my original code with this new info. Apologies and hope this issue can be resolved some other way, unless you just want to close it.

**Comment by manast** [comment]
If I have to guess, the processor is not returning a promise, I have seen similar issues before due to this miss. Since it is probably using streams for uploading the file it is possible promises are not being handled correctly here. Anyway, closing since it is not an issue anymore.
