### ISSUE TITLE
Crashed childprocess in sandbox could crash the main process

### ISSUE THREAD

**Issue by leric** [OptimalBits/bull#2183]
I've got a uncaughtException crashed the bull worker process.
```
Error: write EPIPE\\n    at ChildProcess.target._send (internal/child_process.js:839:20)\\n    
	at ChildProcess.target.send (internal/child_process.js:710:19)\\n    
	at /code/node_modules/bull/lib/process/sandbox.js:12:13\\n    
	at runMicrotasks (\u003canonymous\u003e)\\n    
	at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

traceback to this line of code: 
 https://github.com/OptimalBits/bull/blob/2618a2ed1d1bc528254f299dd10f4b6216a2f41d/lib/process/sandbox.js#L12

In the reference of this send function, it need a callback  function to handle error, or it will throw it out:

https://nodejs.org/dist/latest-v14.x/docs/api/child_process.html#child_process_subprocess_send_message_sendhandle_options_callback

**Comment by manast** [comment]
We will conduct an investigation.
