### ISSUE TITLE
Event subscriber clients won't reconnect / Jobs and events won't get triggered

### ISSUE THREAD

**Issue by Xairoo** [OptimalBits/bull#2187]
Event subscriber clients won't reconnect after a timeout when redis removes the client based on `tcp-keepalive` setting (default is 300 seconds).

This is only related to a remote redis connection. Locally it works.

Bull uses 3 redis connections:
- client
- subscriber
- bclient

When you run into this problem, you'll miss 1 or 2 clients (typically 2). The missing clients are required for `yourQueue.on()` and `yourQueue.process()`. So you won't receive events:
- new jobs `yourQueue.process()`
- progress updates `yourQueue.on()`

### Reproduce

I'm still testing this, don't have much time right now, will update this if there is an easier/better way.

- Use a remote redis server
- Cut your uplink for at least 300 seconds (`tcp-keepalive` value) or put your system to sleep/hibernate
  - You can reduce this time when you reduce the `tcp-keepalive` value on your redis server

**Not sure, still testing it**: Looks like when you remove your network cable from your PC or disable the network card, blocking the port or so, the disconnect event will be triggered, so it will reconnect automatically. In other words: **Prevent the disconnect event** to reproduce this problem.

The redis client lists `CLIENT LIST` (or just use [RedisInsight](https://docs.redis.com/latest/ri/installing/) as a GUI) will show you all connected clients.

After start:
![Screenshot 2021-10-25 at 08-37-22 Client List RedisInsight](https://user-images.githubusercontent.com/731894/138646395-5b1d1df5-8739-4bd4-aab4-94c6cc182c89.png)

After close/reconnect:
![Screenshot 2021-10-25 at 08-37-29 Client List RedisInsight](https://user-images.githubusercontent.com/731894/138646389-0cf78e22-a6c6-4abe-a3af-750a60e47735.png)

This could be related to https://github.com/OptimalBits/bull/issues/1873.

I am still testing it, but it looks like pinging the server from each client restarts the connection:

```
setInterval(function () {
  yourQueue.clients.forEach((client) => {
    client.ping();
  });
}, 10000);
```

**Comment by manast** [comment]
I agree that enableReadyCheck shouldn't matter, however without it the reconnection will not work, I have tested it extensively.

**Comment by manast** [comment]
> In a large production scenario it would be really difficult to check all the connected, btw. the missing clients (subscribers!) to find the reason why the jobs are stuck.
> But a step would be checking the job in redis. If they get added, than the subscriber must be disconnected. What else should it be?

In general you should not use the events other than for non critical notifications, since in the case of a disconnect you will loose events, so you cannot rely on them for bookkeeping.

**Comment by Xairoo** [comment]
> In general you should not use the events other than for non critical notifications, since in the case of a disconnect you will loose events, so you cannot rely on them for bookkeeping.

Totally. In my (bad) case the bull worker does his work, but the event (on complete and so on) is finally received and handled by an other instance (socket.io) that will send some data to the user and the most important part is to store  data from the received job in MongoDB.

I have done this to save connections. That wasn't a good idea.

The worker should handle the events directly and must store data to the DB. In general within the event loop before the job is completed. To handle also DB problems.

Sometimes we cannot see the forest for the trees.

Thanks! =)

**Comment by alolis** [comment]
> > In a large production scenario it would be really difficult to check all the connected, btw. the missing clients (subscribers!) to find the reason why the jobs are stuck.
> > But a step would be checking the job in redis. If they get added, than the subscriber must be disconnected. What else should it be?
> 
> In general you should not use the events other than for non critical notifications, since in the case of a disconnect you will loose events, so you cannot rely on them for bookkeeping.

I use the events for bookkeeping as well. After the change in #1873 I assume this is not a problem and the events WILL fire after re-connect or am I wrong?

**Comment by manast** [comment]
> After the change in #1873 Is it safe to assume this is not a problem and the events WILL fire after re-connect or am I wrong?

They should. But you can also verify it to be 100% sure :)
