### ISSUE TITLE
how to prevent job stalled more than allowed limit to break other jobs

### ISSUE THREAD

**Issue by daniloab** [OptimalBits/bull#2188]
## Description
We are facing a known problem with the bull. When a job in the queue fails for the above reason, the other jobs in the queue also fail.

Is there any way to prevent the queue from working? Is it a problem related to Redis as mentioned here https://github.com/OptimalBits/bull/issues/1399?

references
- https://github.com/OptimalBits/bull/issues/1822
- https://github.com/OptimalBits/bull/issues/1685
- https://github.com/OptimalBits/bull/issues/1399

## Bull version
bull@3.29.3

**Comment by daniloab** [comment]
@manast 

Here is the implementation example https://github.com/daniloab/bull-staled

There is two tobs:
- send_message
- delayed

The `send_mesage` has an implementation that makes the while getting in a infinite loop and returns the error of this issue.

So, this error breaks the whole queue and the delayed jobs don't get triggered.

I want to know if can I make our job flow to be more robust to get this errors and *dont* the remaining jobs in the queue.

**Comment by manast** [comment]
@daniloab you should provide a minimal test code, unfortunatelly we cannot provide support for a complete repo like this. You should be able to write a standalone test case that you can post here that reproduces the issue.

**Comment by geekravi92** [comment]
@daniloab, did you get any way out? I'm also facing similar issue as yours.

**Comment by manast** [comment]
@geekravi92 stalled jobs should not affect other jobs, if you have some simple test case that shows this is not true we can look deeper into it, but please create a new issue.

**Comment by SirPhemmiey** [comment]
it's 2023 and i'm still facing this issue, any update on this please?

**Comment by codesjedi** [comment]
Any update here? We're still facing this issue.

**Comment by manast** [comment]
@codesjedi the thing is, there is no issue, you can find information on the reasons why this happens if you search a bit.

**Comment by wangkunmeng** [comment]
I used the following solution to solve it。

```ts    
async onQueueFailed(job: Job, err: Error) {
        // stalled重试失败的job不会自动删除
        if (err.message === 'job stalled more than allowable limit') {
            await job.remove().catch(err => {
               console.error(`jobId: ${job.id} remove error: ${err.message}`, err.stack);
            });
        }
    }
```

**Comment by eldimious** [comment]
Any idea why this issue take place or how can we solve it? Should we just need to use above workaround? Cause in my case even if i use `removeOnComplete: true` and `removeOnFail: true` for some reason some jobs remains on stalled status without removed from redis with message: `job stalled more than allowable limit` (I do use custom jobid which is the same and repeats every x mnts )

**Comment by manast** [comment]
@eldimious you are probably killing the workers while they are processing jobs too often. Job's get stalled when your workers start a job and they do not manage to renew the job lock. This is documented in several places.

**Comment by manast** [comment]
If for some reason the workers are not being closed gracefully one way to mitigate this error is to increase the number of allowed attempts for stalled jobs.

**Comment by pushkarsingh32** [comment]
Its 2024 I am still facing the same issue ;_;

Anyone got any working solutions?

> I used the following solution to solve it。
> 
> ```ts
> async onQueueFailed(job: Job, err: Error) {
>         // stalled重试失败的job不会自动删除
>         if (err.message === 'job stalled more than allowable limit') {
>             await job.remove().catch(err => {
>                console.error(`jobId: ${job.id} remove error: ${err.message}`, err.stack);
>             });
>         }
>     }
> ```

**Comment by manast** [comment]
@pushkarsingh32 it is 2024, and still we did not get a simple code snippet that reproduces the issue...

**Comment by manast** [comment]
Btw, in 2024 you should also try to use the newer and more stable BullMQ: https://github.com/taskforcesh/bullmq

**Comment by pushkarsingh32** [comment]
> @pushkarsingh32 it is 2024, and still we did not get a simple code snippet that reproduces the issue...

I dont know man what do you need. 

the code is working 50% of the time so I dont think there is any issue from my side. 

I know you will again say give me reproducible code but there is not any. It happens randomly. 

I am sharing pices here any way. 
Code stack: Nextjs javascript, supabase, tailwindcss 
Using instrumental nextjs hook 

Instrumentation file 
`export const register = async () => {
    if (process.env.NEXT_RUNTIME === 'nodejs') {
        const { Worker } = await import('bullmq');
        const { redisConnection } = await import('./lib/Jobs/Redis/redis');
        const { articleWorkerHandler } = await import('./lib/Jobs/Workers/articleWorkerHandler');
        const { createClient } = await import('@supabase/supabase-js');

        const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SDFADS_SERVICE_ROLE_KEY;
        const supabaseUrl = process?.env?.NEXT_PUBLIC_SUPABASE_URL;
        const supabase = createClient(supabaseUrl, SUPABASE_SERVICE_ROLE_KEY);

        const articleWorkerOptions = {
            connection: redisConnection,
            concurrency: 1,
            removeOnComplete: { count: 100 },
            removeOnFail: { count: 500 },
            lockDuration: 300000, // 5 minutes
            stalledInterval: 30000, // 30 seconds
            maxStalledCount: 1,
        };

        const articleWorker = new Worker('articleQueue', articleWorkerHandler, articleWorkerOptions);

        // Handle completion for articleWorker
        articleWorker.on('completed', (job) => {
            console.log(`articleWorkerHandler Job completed with result ${job.id}`);
        });

        // Handle failures for articleWorker
        articleWorker.on('failed', async (job, err) => {
            console.error(`articleWorkerHandler Job failed with error ${err.message} for ${job.id}`);
            console.error(`Stack trace: ${err.stack}`);

            try {
                const articleId = job.data.articleId; // Assuming the job data contains the articleId
                const { error } = await supabase
                    .from('article_queue')
                    .update({
                        status: 'failed',
                        statusDetails: `Error: ${err.message}`,
                        updatedAt: new Date().toISOString()
                    })
                    .eq('id', articleId);

                if (error) {
                    console.error(`Failed to update database for failed job ${job.id}: ${error.message}`);
                } else {
                    console.log(`Successfully updated database for failed job ${job.id}`);
                }
            } catch (dbError) {
                console.error(`Error updating database for failed job ${job.id}: ${dbError.message}`);
            }
        });

        articleWorker.on('error', (err) => {
            console.error(`articleWorker encountered an error: ${err.message}`);
            console.error(`Stack trace: ${err.stack}`);
        });

        // Graceful shutdown
        process.on('SIGTERM', async () => {
            console.log('SIGTERM received, closing worker...');
            await articleWorker.close();
        });
    }
};`

Article Queue file 

`import { Queue } from 'bullmq';
import { redisConnection } from '../Redis/redis';

const articleQueue = new Queue('articleQueue', {
    connection: redisConnection,
    defaultJobOptions: {
        attempts: 3,
        backoff: {
            type: 'exponential',
            delay: 1000,
        },
    },
});

export { articleQueue };
`

This is how worker handler extracts data 

`export const articleWorkerHandler = async (job) => {
    let { articleId, allParams, projectId } = job.data;
    console.info(`\n\n*************I am processing the job with id ${job.id} & articleId ${articleId}*************`);`
    
    This is how jobs are added to the queue
    
    `    const articleId = uuidv4();
        let articleSettingClone = { ...articleSetting, targetKeyword: target };

        let singleArticleQueueData = {
            id: articleId,
            user_id: userId,
            config: articleSettingClone,
            status: 'queued',
            updatedAt: new Date().toISOString(),
            project_id: projectId,
            project_name: otherParams.projectName,
        };
        articleQueueData.push(singleArticleQueueData);

        const job = await articleQueue.add('generateArticle', {
            allParams: { ...otherParams, targetKeyword: target },
            articleId,
            projectId,
        },
            {
                attempts: 3,
                backoff: {
                    type: 'exponential',
                    delay: 1000,
                },
            },
        );`
        
        Thanks

**Comment by pushkarsingh32** [comment]
> Btw, in 2024 you should also try to use the newer and more stable BullMQ: https://github.com/taskforcesh/bullmq

using this version only

**Comment by manast** [comment]
I am not saying that the issue is in your code. What I am saying is that in order for us to have a chance to fix this issue we need a code that reproduces it. The code you pasted I cannot use to reproduce it for instance.

**Comment by pushkarsingh32** [comment]
Just checked it out, No examples repo for Nextjs. Any plans for that? Thanks

**Comment by manast** [comment]
> Just checked it out, No examples repo for Nextjs. Any plans for that? Thanks

Not sure what you mean actually. Now that I see your source code I see you are indeed using BullMQ, so we are on the wrong repo. There are many articles on the net explaining how to use BullMQ with NextJS. If you have a concrete issue will BullMQ, please report it on the proper repo. I am locking this issue now as there are no actions to take and it is just creating confusion.
