### ISSUE TITLE
"attempts" option is unclear

### ISSUE THREAD

**Issue by matteocontrini** [OptimalBits/bull#219]
The [documentation](https://github.com/OptimalBits/bull#add) for `queue.add` says that `attempts` is the

> number of attempts to retry if the job fails

but looking at #191 and at some parts of the source code, I'm not sure.

Is the `attemps` option the total number of attempts for a job (including the first one), or the number of max retries after the first one failed?

**Comment by evanhuang8** [comment]
It's the total number of attempts, not the max retries: if attempts is set to 3, it means the job will be at most processed (attempt to process) 3 times.

We can clear that up in the documentation.

**Comment by slidenerd** [comment]
One question I was looking for and could not find, what do you set the value of attempts for if you want to retry infinitely?
