### ISSUE TITLE
cluster exist event 

### ISSUE THREAD

**Issue by OliverwengFiltered** [OptimalBits/bull#2196]
After upgrading to v4, it seems the console keeps printing out the `Bull: worker died, restarting ....` every second. Which means the cluster getting exit event all the time. 

Any insights? 

Below is the code I'm using for the bull service server.

```javascript
if (cluster.isMaster) {
    const cpuNumber = require('os').cpus().length;
    for (let i = 0; i < cpuNumber; i++) {
        cluster.fork();
    }
    cluster.on('exit', function (worker, code, signal) {
        console.log('Bull: worker %d died (%s). restarting...', worker.process.pid, signal || code);
        cluster.fork();
    });
} else {
    const Queue = require('bull');
    const redisOptions = require('../../redis');
    const testQueue = new Queue('tabsTracking', redisOptions);
    testQueue.process(5, path.join(__dirname, 'testQueue.js'));
}
```

**Comment by manast** [comment]
There are breaking changes https://github.com/OptimalBits/bull/blob/develop/CHANGELOG.md#400-2021-10-27
Just remove the cluster part and you will see the error in the console.

**Comment by OliverwengFiltered** [comment]
thanks, @manast
