### ISSUE TITLE
Is it possible to repeat a job every 30 days from a given start date?

### ISSUE THREAD

**Issue by jkepps** [OptimalBits/bull#2197]
## Description
I would like to repeat a job every 30 days at 3:15PM. Is this possible with the repeat config?
I assumed passing a repeat config with a `startDate` of `2021-10-25T00:00:00Z` and the cron string `15 15 */30 * *` would mean that the first job would process on `2021-11-24T15:15:00Z`, but now I'm wondering if I am misunderstanding how the repeat configuration works.

**Comment by jkepps** [comment]
Ah okay this makes sense now. I appreciate your explanation @cincodenada! 

Unfortunately we were looking to have a job get process on a 30 day cadence from a given start date. Sounds like that isn't actually possible so we found a different solution. I'll close out the issue.

**Comment by cincodenada** [comment]
Ah, yeah, I don't think that's possible with the repeat specification, unfortunately. There is the `every` option which would give you a strict 30-day cadence, but it would have to start at a time that is some whole number of 30-day periods from the Unix epoch, which I imagine is not helpful (I don't think `every` is particularly intended for cadences more than a day or so). Glad you were able to find a different solution, thanks for asking!
