### ISSUE TITLE
Compatible with Next.js

### ISSUE THREAD

**Issue by martinblampied** [OptimalBits/bull#2206]
Are there issues running bull on next.js ? The below hangs on testqueue.add()

```
import Bull from 'bull';
import redis from '../../../lib/redis';

export default async (req, res) => {

    const testqueue = new Bull('testqueue', redis)
    const job = await testqueue.add({ foo: 'http://example.com/video1.mov' });

    console.log("written")
    return res.status(200).json({
        status: 'Ok',
        data: "written"
    });
}
```

**Comment by martinblampied** [comment]
@manast Thanks. Config seems fine. I can user ioredis to `client.set('foo', 'bar');` with out issue. Are you aware of any public examples or repos where I can see nextjs + bull integration?

Thanks for tip on moving code out of handler, yep would move it to a startup script once I got it working.

**Comment by martinblampied** [comment]
Finally got this working. For anyone else with this issue I had to add `tls: {}`.

```
var testqueue = new Bull('testqueue', {
    redis: {port: [port], host: '[host]', password: '[password]', tls: {}}
});
```

**Comment by oyatek** [comment]
@manast I need help too. Please explain how Bull can be used in NextJS / BlitzJs apps. 

I'm using it in BlitzJS app (framework built on top NextJS)  and I thought I'm doing it right until I started receiving some weird errors (Missing process handler for job type __default__) and then I checked redis clients list and found there are more than 50 connections (I don't have that many queues).

Please tell me where I'm wrong:
1. I've created an API endpoint (https://site.com/api/bull/start) that has:
```
const mailsQ = new Queue("mails")
mailsQ.process(mailSendHandlerFunction)
```
I start the script manually 1 single time after I restart the server. The queues are instantiated. 
Then, in another API endpoint I'm doing this: 
```
const mailsQ = new Queue("mails")
mailsQ.add({to: user@mail.com, message: "foo"})
```

Is it the correct way of using Bull? Looks like it's wrong to instantiate Queues in 2 different API endpoints? Should everything be done in 1 single file? Should I pass 1 single Queue instance between all files? 

Another question is - the project is still in dev mode and I restart the server very often. Queue handlers also change and I need to have a way to restart bull. I have tried .obliterate a year or more ago and for some reason, it didn't completely clean everything out so I have found a more bulletproof method on Github using terminal:
```
redis-cli --scan --pattern bull:* | xargs redis-cli  del
```
I was thinking it's 100% working method but yesterday after checking redis, I found that redis still has many connected bull clients (more than 50), and some new key:value pairs continue to appear in Redis even after full cleaning. Looks like there are some background Bull processes that are always working even when my node App is shut down. I can't seem to find a way to completely turn off bull and restart it from the scratch - please let me know how can I do that? I Googled a few hours yesterday but couldn't find a way.

Thank you!

**Comment by manast** [comment]
Every time you can ```new Queue``` you can potentially create up to 3 connections to Redis. This is no different any other database, you connect outside of your API handlers or you will create loads of connections.

**Comment by oyatek** [comment]
Thank you, I have rewritten the Queues-related code completely to make sure that I'm using only 1 instance of every Queue across the NextJS application. Now everything works exactly as expected, except for some strange behavior of the `.obliterate` method but maybe it's my misunderstanding again. I'll do more research, and if I don't find a solution I will create a separate topic.

**Comment by qlereboursBS** [comment]
Please note that the `tls: {}` doesn't seem to be working anymore and seems to break the connection with Redis. At least when I tried with this option, it was not working, when it was without it.
