### ISSUE TITLE
returned promise from .process()

### ISSUE THREAD

**Issue by yonivy** [OptimalBits/bull#221]
I need to have a thin wrapper to `bull` to hide my `add`ing logic and some other knick-knacks (I have multiple modules adding and getting from the queue)

I'm using bull as more of a `priority message queue` so I want my wrapper to be something along the lines of:

    module.exports = {
        add: function() { // my logic and then queue.add(...)},
        get: function() { // return the next job as a promise }    
    }

and I want my `worker`'s as

    myBullWrapper.get().then(function(job) {
        // here I have the job and my worker can do whatever
    })

Well I couldn't quite get it to work. Is it a possibility or should I think of a different idea?

**Comment by manast** [comment]
did you manage to get your issue resolved? if not, please reopen with more details.
