### ISSUE TITLE
Guarantee sequential processing of jobs

### ISSUE THREAD

**Issue by georgios-tsoumas** [OptimalBits/bull#2211]
I would like to send multiple messages to multiple users using multiple workers. Each user must get the messages in a **specific order**. Obviously there is no guarantee that prioritizing the jobs will not mess the actual order of the messages delivered (network, process lag etc). 

**Workaround 1**. Use a rate limiter and set `userid` as the `groupKey` with a limit of 1. But I'd rather use the limiter only to limit the rate of messages per second for different reasons.

**Workaround 2**. Send multiple messages per worker, but this defeats the purpose of having a rate limiter (each job should send 1 message in order for the RateLimiter to make sense, otherwise I will violate the service's constraints for RPS). 

**Is there some other way that I miss which guarantees sequential processing of certain jobs, using multiple workers? For example sharding?**

**Comment by manast** [comment]
Interestingly we just got the same request in a discussion in BullMQ: https://github.com/taskforcesh/bullmq/discussions/433#discussioncomment-1628082

I am not sure how popular a feature like this would be, but the way groups keys work with rate limiting would certainly make such feature impossible to implement in Bull. However in BullMQ Pro we have a new implementation of groups that could include a feature like this. I will mark this issue as a potential feature, and if there is enough interest we will implement it.

**Comment by manast** [comment]
| Assign that job to the worker with the result of the mod operation as its index.

Thats not trivial to do, besides you are assuming there is only one worker running at any given time... as soon as you have more than one (the most common scenario), it will not give you any sequentiality guarantee.

**Comment by georgios-tsoumas** [comment]
I mean something like this:
![bull](https://user-images.githubusercontent.com/69189659/141492286-9f06302a-6856-4f1e-ae85-f2d0ce83da05.png)
This will guarantee sequential messages. But I guess that distribution of jobs is not possible right? It would mean that workers wait until there is an appropriate job for each...

**Comment by manast** [comment]
The workers pull jobs from the queue, you are proposing that the queue distribute the jobs among the workers which is not possible in Bull's architecture.

**Comment by georgios-tsoumas** [comment]
Yeah it makes sense. Thanks for clearing that up, I'll probably wait until that feature is implemented, since I have a workaround for now. Great library. Helped a ton.
