### ISSUE TITLE
Missing global event for delayed jobs

### ISSUE THREAD

**Issue by bastibeckr** [OptimalBits/bull#2212]
## The event "global:delayed" will not fire
I have a working installation of Bull where jobs are created and processed. 
On a different server, I want to monitor this queue. So I need to listen to "global:*"-events to get notified when a job fails, completes, etc. This works for every state (global:waiting, global:failed, global:completed) _except_ "global:delayed".

As mentioned in #1410

## Minimal, Working Test code to reproduce the issue.

The first snippet creates new delayed jobs.

```javascript
/**
 * create-job.js - create new jobs for the queue
 */

const Queue = require('bull')
const { config } = require('process')

const myQueue = new Queue(config.queueName, { redis: config.redis })

/**
 * Add a new job with a delay
 *
 * @param   {Object}  data  Job metadata
 *
 */
function addJob (data) {
  myQueue.add({ ...data }, { delay: 2000, attempts: 10, backoff: { type: 'exponential', delay: 1000 } }).then(job => {
    console.log('Added a job with a delay: %o', job)
  }).catch(e => {
    console.error('Could not add a job: %o', e)
    throw e
  })
}

module.exports = addJob
```
The second snippet runs on a different machine and wants notifications about changes in the Queue.
```javascript
/**
 * consumer.js - for creating a job monitoring ui on a different server
 */

const Queue = require('bull')
const { config } = require('process')

const myQueue = new Queue(config.queueName, { redis: config.redis })

/**
 * Hook into EventEmitter's emit method, log all emitted events.
 *
 * @param   {EventEmitter}  emitter
 *
 */
function logOnEmit (emitter) {
  const oldEmit = emitter.emit
  emitter.emit = function () {
    const emitArgs = arguments
    console.log('Event : %o', emitArgs)
    oldEmit.apply(emitter, emitArgs)
  }
}

logOnEmit(myQueue)

module.exports = myQueue
```

When I call ``addJob``, a Job is created and will be _delayed_ instantly. 
I would expect to get a notification in the consumer.js because "global:delayed" should be fired.

Any other global events (like global:progress, global:waiting, global:completed, etc) will be logged in the consumer.js running on a different machine.

Thanks a lot for reading and maintaining this!

**Comment by manast** [comment]
I tried to implement this, but unfortunatelly it is quite a lot of job. The delay event has never been available in Bull, however it is available in BullMQ, so if you really need this feature the only I can offer you is to upgrade to BullMQ.
