### ISSUE TITLE
Timing issues when running "high frequency" on AWS ElastiCache Cluster

### ISSUE THREAD

**Issue by schw4rzlicht** [OptimalBits/bull#2216]
## Description

Not really sure whether this can be categorized as a bug or more a question or cry for help 😬 

We are running a job that should read out a counter, reset it and emit the value every 500 ms. We are using an AWS ElastiCache with Cluster mode on. We are currently using 1 shard and 1 replica (so 2 nodes in total).

On top, we are using Nest.js, so therefore we use their bull module.

The job we are running of course is a repeatable job which is set to run every 500 ms. Locally, using https://github.com/Grokzen/docker-redis-cluster, everything works as expected. On the AWS cluster it's a whole different story: Jobs are run every 10-20 seconds, the `every` config option is very unreliable. I figured that this might be due to Redis cluster not guaranteeing strict consistency, so I tested it with non-clustered ElastiCache with a single node. Everything works fine with that configuration.

Also everything works fine when running a task, let's say, every 30 or 60 seconds, no matter if clustered or not.

Is there anything that I can do to make it work in our environment? Are "high frequency" jobs even a valid use-case for bull? I really like the way, bull works, but that issue chases me for almost two weeks now and somehow nobody else seemed to have experienced something similar.

## Minimal, Working Test code to reproduce the issue.

`producer.ts`:
```typescript
const stageId = "abc";
const reactionName = "heartEmoji";

queue.add(
    "reaction",
    {
        stage: stageId,
        reaction: reactionName,
    },
    {
        jobId: `reaction:${stageId}:${reactionName}`,
        repeat: {
            every: 500,
        },
        removeOnComplete: true,
        removeOnFail: true,
    },
);
```

`processor.ts`:
```typescript
@Processor("stageJobs")
export class StageJobsProcessor {
    constructor(
        @InjectQueue("stageJobs") private readonly stageJobsQueue: Queue,
    ) {}

    @Process("reaction")
    reaction(job: Job<{ stage: string; reaction: string }>): Promise<void> {
        // Get counter, reset counter, emit counter, nothing too fancy here
    }
}
```

The queue is initialized with
```typescript
{
    name: "stageJobs",
    prefix: "{stageJobs}",
    settings: {
        drainDelay: 0.5,
    },
}
```

## Bull version

4.1.0 as peer dependency by @nestjs/bull

**Comment by manast** [comment]
So did it work properly without cluster or not?, I am not sure I understood that part. Cluster is a but tricky and even though Bull theoretically works on a cluster setup it does not take any advantage of it, a given queue content will always be stored in the same node. A good setup is one primary and one replica in non cluster mode, then you get high availability and maximum performance. 
There is nothing actually preventing high frequency repetitions even though it is an unusual case as you suspected.

**Comment by manast** [comment]
Btw,  you should not need to change the "drainDelay" setting. The default one works well for kind of all cases.

**Comment by schw4rzlicht** [comment]
> So did it work properly without cluster or not?, I am not sure I understood that part.

Yes, it did. Single node works, cluster doesn't.

> Btw, you should not need to change the "drainDelay" setting. The default one works well for kind of all cases.

We noticed that the default of 5 seconds would actually delay the execution by 5 seconds locally 🤔

**Comment by manast** [comment]
> We noticed that the default of 5 seconds would actually delay the execution by 5 seconds locally 🤔

Can you write a simple test snippet that reproduces that? because that definitely should not happen. That time is the time the blocking connection is waiting for jobs to be available in the queue, reducing it just increases the polling interval.

**Comment by schw4rzlicht** [comment]
Okay, so I started writing the test snippet when I noticed that this might be a case of RTFM, but anyway it could help as a reference for people who might experience the same thing in the future.

What I didn't show you is how I initialized the Bull module:
```typescript
BullModule.forRootAsync({
    imports: [RedisModule],
    inject: ["BullRedisProvider"],
    useFactory: (redisProvider: RedisProvider) => ({
        createClient: () => redisProvider.getRedisClusterClient(),
    }),
}),
```

And as you can see, I totally ignored the arguments that `createClient` provides. The `RedisProvider` is there to manage connections and what it did until now was to always return the same connection. Which is contrary to the docs, which state:

> When type is client or subscriber you can return the same connection for multiple queues, which can reduce the number of connections you open to the redis server. Bull does not close or disconnect these connections when queues are closed, so if you need to have your app do a graceful shutdown, you will need to keep references to these Redis connections somewhere and disconnect them after you shut down all the queues.
>
> The bclient connection however is a "blocking client" and is used to wait for new jobs on a single queue at a time. For this reason it cannot be shared and a new connection should be returned each time.

And this *must* be the reason for the strange behavior we had b/c after I started providing appropriate clients, everything works now.

Sorry for the trouble and thanks for your help!

**Comment by manast** [comment]
Another alternative is to use BullMQ, which handles connections better: https://github.com/taskforcesh/bullmq

**Comment by schw4rzlicht** [comment]
We will definitely do this once Nest.js has a stable integration.
