### ISSUE TITLE
Handle results from promises from seprate processors

### ISSUE THREAD

**Issue by shamonshan** [OptimalBits/bull#2220]
## Description

I am trying to implement a queue as a separate processor

    imageProcessQueue.process(__dirname+'/process-queue.js');

In `process-queue.js` i m handling 

    module.exports = async function (job) {
    
      //some jobs 
      return Promise.resolve({status:"completed"});
    }

But on  the queue `completed` event I can't read the results from the promise which I return from the processor

    imageProcessQueue.on('completed', function (job, result) {
      // can see this output
      console.log('completed')
      //never logs anything always empty 
     //should log  {status:"completed"}
      console.log(result)
    })

Bull version :4.1.1

**Comment by manast** [comment]
Strange, we have a test case that cover this: https://github.com/OptimalBits/bull/blob/develop/test/test_sandboxed_process.js#L38

**Comment by shamonshan** [comment]
But if i return a normal statement `ie return {status:"completed"}`  that i can see in the completed event

**Comment by manast** [comment]
Since you are using "async" already, then what you are returning is a promise not the value of the promise.

**Comment by shamonshan** [comment]
Ahh shit, I forgot about the `async` keyword, now it getting the expected result. 
Thanks for the point, One more question is it necessary to do a  resolve or reject to mark the job as complete??

**Comment by manast** [comment]
Not needed.

**Comment by manast** [comment]
I mean, you need to return a promise, either using async or a promise from a promise chain or whatever.

**Comment by shamonshan** [comment]
```
module.exports = function (job) {
    ProcessImage(job.data,(err,result)=>{
                 if(result){
                    return Promise.resolve({ status:"success" });
                 }
            });
    }
}
```
But the above implementation the  `completed` event is not giving any data

**Comment by manast** [comment]
Because you are not returning any promise. The promise that you are returning is for the callback in ProcessImage...

**Comment by manast** [comment]
The code should be like this:
```ts
module.exports = function (job) {
  return new Promise((resolve, reject) => {
    ProcessImage(job.data, (err, result) => {
      if (err) {
        reject(err);
      } else {
        resolve({ status: "success" });
      }
    });
  });
};
```

**Comment by shamonshan** [comment]
Thanks now its working
