### ISSUE TITLE
Bull queue limiter not complying to limits

### ISSUE THREAD

**Issue by inevolin** [OptimalBits/bull#2221]
## Description
I have a Bull queue and a queue limiter to process max 10 jobs per 10 seconds - but this isn't working properly (with more than one worker).
```js
    this.submitCredentialQueue = new Bull("submit-credential-queue", config.get("redis"), {
      limiter: { max: 10, duration: 10 * 1000 }, // max 10 jobs in 10 seconds
    });
```
As you can see on the screenshot, it sometimes has over 10 active jobs:
![image](https://user-images.githubusercontent.com/53948000/143442172-0d5483df-7aa7-467d-ac9f-12b9c28e5dda.png)

I don't have this problem when using only one worker. So I'm assuming the queue limiter is not "global".

Any clues or suggestions?

## Bull version
"bull": "^4.1.0"

**Comment by manast** [comment]
The limiter is global. However, the number of active jobs is not a good indication here because if the jobs take a long time to process then new jobs will be allowed to be processed since the limiter is applied when fetching the jobs from the wait status.

**Comment by inevolin** [comment]
thanks @manast 
how can we then prevent jobs from going into "active" state, because right now they are not obeying the limiter's settings. Our constraint is to allow new jobs to start when other jobs have actually "finished" (wrt the 10jobs per 10sec window).

**Comment by manast** [comment]
The jobs obey the limit, the workers will not start more than 10 jobs per second which is the most common scenario, which in average will result in 10 jobs completed per second.
