### ISSUE TITLE
Promise Rejection: undefined upon queue.close()

### ISSUE THREAD

**Issue by georgios-tsoumas** [OptimalBits/bull#2222]
## Description
Upon calling `Bull.close()` right after calling `Bull.process()` a promise rejection occurs.
## Reproduce
```javascript
import Bull from "bull";

const queue = new Bull('experiment');
queue.process(() => {
    console.log('nothing here');
});
queue.close();
```
Although, we can wait a bit before calling `queue.close()`:
```javascript
setTimeout(() => {
    queue.close();
}, 100);
```
Then no promise rejection occurs.

Also I noticed that adding `await Bull.isReady()` in between `Bull.close()` and `Bull.process()` still produces the error.
## Bull version
4.1.1
## Additional information
Could it be that something is not done initializing (?)
**ioredis: 4.27.0**

**Comment by manast** [comment]
You must listen to errors: 
```ts
queue.on("error", (err) => {});
```

can you try again with that listener please?

**Comment by georgios-tsoumas** [comment]
Yeah. I think `error` event doesn't fire at all:
```javascript
// index.js
import Bull from "bull";

console.log('Starting experiment');

const queue = new Bull('experiment');
queue.on("error", (err) => {
    console.log('I fire?');
    console.log(err);
});
queue.process(() => {
    console.log('nothing here');
});
queue.close()
.then(() => {
    console.log('Seems this fires');
})
.catch(err => {
    console.log(err);
});

console.log('Finished experiment');
```

Btw, `.catch()` doesn't catch anything here which I think is normal, since the problem is not related to `close()` itself. The output of the above code is this:

```
> node index.js

Starting experiment
Finished experiment
(node:8390) UnhandledPromiseRejectionWarning: undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8390) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8390) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Seems this fires
```

Got redis on metal (Redis server v=6.0.11 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=83fe9b039c768864), Pop!_OS 21.04

**Comment by georgios-tsoumas** [comment]
Some more info, redis monitor when running the immediate Bull.close() outputs just this:
```
1637948855.027945 [0 127.0.0.1:35404] "info"
```
I was curious enough myself to see where in the stack this error occurs. It's on `redisClientDisconnect(client)` when `client.status` is set to `connecting` at `client.quit()`. 

(I have to admit tho, that kind of javascript debugging is only a bit better than debugging a Game Boy debugger)
