### ISSUE TITLE
How to use  @OnQueueCompleted in nestjs?

### ISSUE THREAD

**Issue by littleKitchen** [OptimalBits/bull#2225]
I want to combine the Bull and Postmarks to send the email.
So, I put the postmarks code in the Bull consumer part, and I want to send a message to Kafka topic under  @OnQueueCompleted decorator.

Here is my code:
  @OnQueueCompleted()
  onComplete(job: Job, result: any) {
    console.log(result)
    this.kfk.emit('Notification', {
      MessageID: result['MessageID'],
    });
  }

somehow, this code will call the producer again which is not what I want.

**Comment by manast** [comment]
Please for nestjs related issues post them on the nestjs repo.
