### ISSUE TITLE
Jobs finishing simultaneously, can't listen to the last job of the queue

### ISSUE THREAD

**Issue by hubertdp** [OptimalBits/bull#2228]
I run a queue on a worker.

I would like to inform the UI about the fact that there are no more jobs left.

The problem I have is that two jobs often finish at the same time having the UI / listener getting twice the information that there are no more jobs left.

In my worker I add jobs like this:
```javascript
const fetchUserQueue = new Queue('fetch-user', REDIS_URL);

const maxJobsPerWorker = 1;

fetchUserQueue.process(maxJobsPerWorker, async (job) => {
  const username = job.data.username;

  console.log(`fetching user ${username}`);
});
```

I listen to the `global:completed` event on my web app and check that there are no more jobs using `.getJobCounts()`:
```javascript
fetchUserQueue.on('global:completed', async (jobId) => {
  const jobCounts = await fetchUserQueue.getJobCounts();

  const jobsLeftCount = jobCounts.waiting + jobCounts.delayed + jobCounts.active;

  if(jobsLeftCount === 0) {
    console.log('LAST JOB! queue completed no jobs left "fetch-user"');
  } else {
    console.log(`${jobsLeftCount} jobs left "fetch-user"`);
  }
});
```

I get the `LAST JOB` log twice, as if the two last jobs both see that there are no more jobs left.

**Comment by manast** [comment]
Maybe you can use the "drained" event instead, that is triggered when the wait list is gets empty.

**Comment by hubertdp** [comment]
@manast Thank you very much for quickly pointing that out!

I ended up with the drained event combined with a few milliseconds wait, because the notification about the drained event was sometimes emitted before the last job. I guess it could be because of the socket event then.

Anyways I ended up with this kind of code:
```javascript
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

fetchUserQueue.on('global:drained', async () => {
  await sleep(10);

  console.log('LAST JOB! queue drained no jobs left "fetch-user"');
  // emitting using socket.io
});
```
