### ISSUE TITLE
"Dymanic" event listener?

### ISSUE THREAD

**Issue by hubertdp** [OptimalBits/bull#2229]
Is there a way to setup just one listener to all queue events?

Something like the code below, that is not explicitely having `global:completed` but using `event` inside of the arrow funciton, to deal with all the events.

```javascript
queue.on(event, () => {
  // do something depending on the value of "event"
});
```

**Comment by manast** [comment]
No sorry, this is currently not possible.

**Comment by hubertdp** [comment]
@manast Ok!

Thank you for this great repo by the way!
