### ISSUE TITLE
UnhandledPromiseRejectionWarning "client.on is not a function"

### ISSUE THREAD

**Issue by dbronin** [OptimalBits/bull#2238]
## Description
I apologize for the somewhat vague issue, but if I knew exactly what was causing it, I would be more specific and could provide code to reproduce.

The issue is this:
- if the redis instance runs out of memory, for example, I disconnect the client and subscriber, disconnect from all queues, etc. (proper cleanup).
- somewhere in all of this, bull creates an UnhandledPromiseRejectionWarning "client.on is not a function" from lib/queue line 145

My question is this: how do I either prevent this from happening or catch this?

I am happy to try to clarify in any way that I can. Thank you in advance for your help.

## Bull version
Version: 3.29.3

**Comment by manast** [comment]
There is not so much to go for here, could you at least provide the callstack produced by the exception?

**Comment by dbronin** [comment]
@manast thank you for the quick response. I guess it really all boils down to really strange things happening when redis returns any type of terminating error, like max connections exceeded or out of memory (oom).

The stack for client.on is not a function:

UnhandledPromiseRejectionWarning: TypeError: client.on is not a function
    at /Users/dimon/Documents/Code/Facilitron/Website/facilitron/node_modules/bull/lib/queue.js:145:12
    at Queue.<anonymous> (/Users/dimon/Documents/Code/Facilitron/Website/facilitron/node_modules/bull/lib/queue.js:292:14)
    at /Users/dimon/Documents/Code/Facilitron/Website/facilitron/node_modules/bull/lib/queue.js:871:38
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

So, ultimately, maybe we can go about this another way: what is the best way to handle such terminating redis errors, assuming that connections are reused and there is a client and subscriber.

Thank you.

**Comment by manast** [comment]
Which version of bull is this? I wondering because in the latest version at least there is no "client.on" on line 145 in queue.js.

**Comment by dbronin** [comment]
this is Version: 3.29.3

**Comment by manast** [comment]
Please try the latest and provide a complete test case that reproduces the issue.

**Comment by dbronin** [comment]
@manast there are breaking changes in 4.x from 3.x, right? Are those only in the redis connection options? Thanks

**Comment by manast** [comment]
The breaking changes are always documented there: https://github.com/OptimalBits/bull/blob/develop/CHANGELOG.md

**Comment by dbronin** [comment]
@manast that is great - looks like the breaking changes are in fact only in the redis opts. Thanks

**Comment by dbronin** [comment]
all is good - I went through and cleaned up a bunch of code that dealt with an infinite loop issue that existed in 3.8.x and now, since that issue was resolved some time ago, in 3.29.3 I can handle redis errors the way they were originally supposed to be handled. @manast Thanks for your help
