### ISSUE TITLE
Properly terminate all jobs and queues on redis disconnect

### ISSUE THREAD

**Issue by dbronin** [OptimalBits/bull#2239]
## Description
Can someone tell me please how to properly end/close all queues and jobs when redis disconnects? 

Problem:
I have been using queue.close(), but, if we ask bull to check on a job (as in through job.finished()), it throws an "UnhandledPromiseRejectionWarning: Error: Connection is closed" from lib/job line 541
Is there perhaps another way to handle this?

Thank you.

## Bull version
Version 3.29.3

**Comment by manast** [comment]
Pause the queue first, wait for all jobs to complete, then close it.

**Comment by dbronin** [comment]
@manast this is not possible when the redis connection is no longer available and connection to redis is no longer possible, right? Or will simply pausing the queue allow it to work through the queue even though the connection is closed?

**Comment by manast** [comment]
Well, there is a local pause, but yes if you do not have a connection to Redis then it becomes kind of impossible to finalize a running job without error.

**Comment by dbronin** [comment]
the problem is that this also creates an infinite loop :(

**Comment by dbronin** [comment]
@manast so no way to handle this gracefully? Thanks

**Comment by dbronin** [comment]
all is good - I went through and cleaned up a bunch of code that dealt with an infinite loop issue that existed in 3.8.x and now, since that issue was resolved some time ago, in 3.29.3 I can handle redis errors the way they were originally supposed to be handled. @manast Thanks for your help
