### ISSUE TITLE
Using queue.process during test prevent jest from exiting

### ISSUE THREAD

**Issue by palumbamboo** [OptimalBits/bull#2244]
## Description

If `queue.process` appears at least once in the code executed during the tests, then jest does not exit one second after the test run has completed. 

If i put `await` in front of `queue.process(...)`, nothing happens. The code blocks on this instruction until Jest raises error for time expire.

I've tried several solutions, but none seems to work:
- `queue.close()`
- `queue.process` with/without async, promises or done callback
- `queue.clean()`
- `queue.obliterate()`
- increase jest waiting time
- decrease bull lock duration
- use `--detectOpenHandles` -> with this option jest never exits at all

Every queue event callback (like `closed`, `cleaned`, `drained`, ...) is correctly fired. Jobs are correctly executed. Everything with Bull seems to work fine. The only problem is with `queue.process(...)` method.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
```javascript
import Queue from 'bull'

describe('simple-test', () => {
  it('breaking-process-test', async () => {
    const queue = new Queue('test-queue')

    queue.process((job, done) => done())
    await queue.add({data: 'hello world'})

    expect(1).toBeTruthy()

    await queue.close()
  })
})
```
![image](https://user-images.githubusercontent.com/27193082/147769482-66278ca2-9b9c-4b40-a7b2-6a0d959be225.png)

## Bull version

^4.2.0

## Additional information

NodeJs Version: 14.18.1
Jest Version: ^27.4.5

**Comment by longhoangwkm** [comment]
I got it too

**Comment by oyatek** [comment]
me too :(

**Comment by ExtremelySunnyYK** [comment]
same here

**Comment by manast** [comment]
I think BullMQ supports Jest now, but unless somebody provides a PR with a fix for Bull this issue will most likely remain unresolved.

**Comment by melalj** [comment]
Any update on this?

**Comment by rohit-uf** [comment]
Also got this error.
running with the *--detectOpenHandles*  pinpoints to the following location in code

```
node_modules/ioredis/built/connectors/StandaloneConnector.js:44:21
```
![image](https://github.com/OptimalBits/bull/assets/103091956/36e83091-fcd9-478c-8b06-3914431daf41)

**Comment by GorlikItsMe** [comment]
DId someone find solution?
