### ISSUE TITLE
Large Network Bandwidth consumed with no tasks being processed

### ISSUE THREAD

**Issue by slavivanov** [OptimalBits/bull#2247]
## Description
Hello, we've been using Bull as our primary job queue and I'm very happy with it.
Usually, our load is spiky, and we automatically scale Bull workers based on the number of waiting tasks in the queue, in order to process the jobs in an acceptable time. When there are no jobs pending there are 10 active workers, with up to 200-300 concurrent workers if needed.

As that scaling happens AWS throttles requests to the Redis instance because of exceeding the bandwidth limit of the Redis instance. Not sure if it matters, but there is a failover replica too.

Interestingly, even without any jobs, increasing the number of workers to 200-500, produces a large spike in the bandwidth.
As noted in other issues, I've tried setting the guardInterval to a large number (up to 1000s), but this makes no difference in terms of bandwidth. Total bandwidth consumed is up to 2-3 GB per minute.
<img width="333" alt="Screenshot 2022-01-06 at 18 07 26" src="https://user-images.githubusercontent.com/713329/148414705-f4d9f775-df63-4429-ad01-1c67a0c68714.png">

The queue that I'm testing on is almost empty. Although, there is another queue on a different DB on the same server, I don't think it makes a difference.
<img width="1016" alt="Screenshot 2022-01-06 at 18 25 31" src="https://user-images.githubusercontent.com/713329/148415627-17b41d4a-6342-4d0e-b1cc-9675bc3ac082.png">

So my question is if **I'm missing something obvious here and if not, what can I try to figure this?**
Thanks!

## Bull version
3.29.2

**Comment by manast** [comment]
Workers do timeout their blocking connections based on the option ```settings.drainDelay``` with default value 5 (5 seconds). This means that every 5 seconds every worker will emit a ```BRPOPLPUSH``` command, which requires a minimal amount of bandwidth. So 2-3Gb per minute with just idling workers sounds like an insane amount of data. One thing you could do to figure out the reason for this is to issue a ```MONITOR``` command using ```redis-cli```, which will show you all the commands issued to Redis. On an idling scenario, there would be the ```BRPOPLPUSH``` commands and some other commands that check for stalled jobs and delayed jobs, but these are executed very seldom, so it should not be possible they generate so much traffic. Please keep us informed of your findings, I just came back from the holidays so I will be more responsive from now on.

**Comment by slavivanov** [comment]
Thanks for the response. I'll play around with it in the next couple of days, and try to see what I find out.

**Comment by slavivanov** [comment]
So I spent quite some time on this and have a working hypothesis on this.
While I'm no Bull/Redis expert, it seems that the issue stems from having a large number of workers and having delayed tasks at the same time. This leads to quite a few published Redis messages about the delay queue which are sent to all workers accounting for the traffic spikes.
The solution for me was to move to BullMQ where we can have only a couple of Queue Scheduler handlers taking care of the delayed queue, and a bunch of regular workers which can be scaled as needed.

**Comment by slavivanov** [comment]
I can consider this closed for me, hope it helps anyone else.
