### ISSUE TITLE
Stop retry jobs

### ISSUE THREAD

**Issue by ericrv01** [OptimalBits/bull#2248]
## Description
Hello,
My jobs are designed to autoretry in case of failure, but in certain circumstances I don't want the task to be retried but I would like to identify easily there is the problem (for instance, a task had a bad value).
Currently, I discard the task but it stays in completed queue, and it's not easy to identify there is a problem.
If I fail the task (with done(err)) the task goes to failed queue, and it's good, but retries to execute, and I don't want that.

Is there a way to do it ?

Thanks

**Comment by manast** [comment]
Hmm, not really possible currently I think. I was thinking about possibly having a custom backoff strategy that based on the error it would retry or not, unfortunately the custom stragegies do not allow you to skip the retry. Another option would be to enhance the Job.update method to allow updating the options of the job, such as the retry settings...

**Comment by Jack-Walter-Smith** [comment]
🆙 
It'd super useful to have such functionality. For example, my job is making request and receives 404, it doesn't matter how many requests it will make - it will receive 404 on each retry. So I'd like to handle errors and not retry in some cases

**Comment by manast** [comment]
For new features it is better to request them on the BullMQ repo: https://github.com/taskforcesh/bullmq

**Comment by whiterqbbit** [comment]
`job.attemptsMade = job.opts.attempts` within the job worked for me.

**Comment by AsfandSaddiqui** [comment]
If you want to stop job retry you just have to throw an error exception `throw new UnrecoverableError('Unrecoverable')`
