### ISSUE TITLE
gee, thanks

### ISSUE THREAD

**Issue by johncmunson** [OptimalBits/bull#2250]
Breaking changes in a patch release is always fun. Love it.

bull@3.15.1
<img width="395" alt="Screen Shot 2022-01-08 at 2 16 55 PM" src="https://user-images.githubusercontent.com/19480078/148658791-411ed461-1b1b-441f-8bae-7b4dc8438312.png">

bull@3.15.7
<img width="453" alt="Screen Shot 2022-01-08 at 2 17 54 PM" src="https://user-images.githubusercontent.com/19480078/148658802-1975ca57-a33a-46d5-8f10-769319a3a93e.png">

**Comment by manast** [comment]
Are you reporting this on the right repo? there are no such versions in Bull, moreover, there are no type definitions in bull either.

In any case, I guess nobody is infallible? we all try our best but sometimes mistakes happen, it is not as this was done intentionally to break things...

**Comment by johncmunson** [comment]
@manast you're correct, I should've raised these concerns over at [@types/bull](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bull). Regardless, sorry for being such a dick.
