### ISSUE TITLE
Named queue processor with concurrency 0 starts with 2nd job before 1st is completed

### ISSUE THREAD

**Issue by Twisterking** [OptimalBits/bull#2252]
Some facts:

- I have a queue called `workerQueue`
- I use named processors called `default` to process jobs added to the `default` named "queue"
- There should be NO concurrency, the jobs in the "default queue" should be processed in series

```
workerQueue.process('default', 0, async (job) => {
	// get some stuff from my job.data
	return myFunctionReturningAPromise(myData);
});
```

I also have a nice function which I use to add to my "default queue":
```
export async function addToDefaultQueue(method, ...params) {
  const job = await workerQueue.add('default', { method, params }, { removeOnComplete: true });
  return job;
}
```

### The problem is now:

While the "default queue" is currently processing a pretty complicated job taking up to 2 minutes, I start pushing more jobs into my queue using my `addToDefaultQueue` function. This works beautifully!
BUT: While this job is **not yet finished**, the queue suddenly starts working on the 2nd job I just pushed into the queue! **It should not do that!**

I even tried to use all the global events like `waiting`, `active`, `stalled`, `progress` and `completed` - I can't find any errors! bull-queue definitely correctly thinks, that the first job is not yet completed - so why is it starting to work on the 2nd job if the concurrency is set to `0`?

Thanks for your help in advance!

**Comment by Twisterking** [comment]
I also played around with the very simplest setup I could think of now!
It really seems to me that the `concurrency` setting of `queue.process()` is completely broken.

If I completely leave it as standard (and just do `workerQueue.process('default', function (job) { ... })`), the concurrency seems to be **3**!
With the concurrency set to **0** (`workerQueue.process('default', 0, function (job) { ... })`), the ACTUAL concurrency seems to be **2**!
With the concurrency set to **1** (`workerQueue.process('default', 1, function (job) { ... })`), the ACTUAL concurrency seems to be **3**!
With the concurrency set to **2** (`workerQueue.process('default', 2, function (job) { ... })`), the ACTUAL concurrency seems to be **4**!
... and so on ...

WTF? Am I completely stupid or is this setting just broken and there is no way to have NO concurrency?!

**Comment by rosslavery** [comment]
This is working as designed even if it's unintuitive and often undesirable. See the notes on how concurrency stacks for named jobs in the docs here:

https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueprocess

There are some solutions you can implement to ensure that the total concurrency is 1. E.g. for each named job processor you add to the queue, set the concurrency to 1 for the first, and to 0 for all remaining (1 + 0 + 0 + 0).

**Comment by manast** [comment]
Or even easier just do not use named processors at all :) They do not give any additional features other than slightly more convenient when writing your processors.

**Comment by fogine** [comment]
> E.g. for each named job processor you add to the queue, set the concurrency to 1 for the first, and to 0 for all remaining (1 + 0 + 0 + 0).

@manast  could you elaborate? If I have 7 named processors, can I somehow ensure single concurrency despite default behavior stacking up concurrency for each additional named processor?

**Comment by fogine** [comment]
Uh, oh, weird behavior but it saved my day, as I really needed to get around concurrency stacking up...
In other worlds when you have several named processors:

```javascript
workerQueue.process('nam1', function (job) { ... }));
workerQueue.process('nam2', function (job) { ... }));
workerQueue.process('nam3', function (job) { ... }));
```
for the above example you get concurrency of 3 as documentation states. If you need to have always conccurency concurrency of 1 you can do this:

```javascript
workerQueue.process('nam1', 1, function (job) { ... }));
workerQueue.process('nam2', 0, function (job) { ... }));
workerQueue.process('nam3', 0, function (job) { ... }));
```

By settings conccurency=1 to only one named processor while setting concurrendy=0 to any other named processor.. Queue concurrency will be 1 and even named jobs with concurrency=0 will keep processing its jobs!!

**Comment by Twisterking** [comment]
Question about the newer **BullMQ** version: https://docs.bullmq.io/guide/workers/concurrency

How does the concurrency behave there? I still need something link this:

I just have ONE queue just called `queue`. This single queue consists of several named workers, where a named worker called `default` should have a concurrency of e.g. `10`, while another worker called `in-series` only has a concurrency of `1`.
So whatever is handled by the first worker can handle up to 10 jobs in parallel, while the second worker only does jobs in series. Obviously the concurrencies MUST NOT STACK - I do NOT want a general concurrency of `11`, but `10` and `1` separately.

How can I achieve this? Do I need a setup of **2 separate queues** or can this achieved with a single queue?
Thank you!

**Comment by manast** [comment]
@Twisterking the first thing to understand is that  concurrency is per Worker instance, if you need a global max concurrency factor you will need something like max group concurrency in the Pro version (https://docs.bullmq.io/bullmq-pro/groups/concurrency). Furthermore, in BullMQ there is no concept of concurrency for "named" processors (actually this feature did not exist in legacy Bull either). So in you case it seems like the best is to have separate queues for every kind of job that requires different concurrency factors.
