### ISSUE TITLE
queue.getRepeatableJobs() not returning valid Repeatable Job configurations

### ISSUE THREAD

**Issue by a-mitrovic-codefleet** [OptimalBits/bull#2255]
## Description
I added one repeatable job in my queue, but when I call queue.getRepeatableJobs(), it does not return correct informations (cron, tz, etc.).

## Minimal, Working Test code to reproduce the issue.
```
updateStatisticsQueue.add(`statisticsType-1`, { statisticsType }, {
            attempts: 1200,
            backoff: 30000,
            removeOnComplete: true,
            repeat: {
                cron: '1 0 0 * * *',
                tz: 'UTC'
            }
        });

const repeatableJobs = await updateStatisticsQueue.getRepeatableJobs();

console.log(repeatableJobs);
//output:
[
  {
    key: 'statisticsType-1:1fa6a7b0-356d-44d4-9b69-fba587f9c00a:1::UTC:1 0 0 * * *',
    name: 'statisticsType-1',
    id: '1fa6a7b0-356d-44d4-9b69-fba587f9c00a',
    endDate: 1,
    tz: null,
    cron: 'UTC',
    every: null,
    next: 1642204801000
  }
]
```

## Bull version
3.29.3

## Additional information
Node v14.17.0

**Comment by manast** [comment]
I tried this and could not reproduce it, furthermore, we have tests that cover this scenario and they are passing. Tested on version 4.2.1 but we had those same tests in 3.x too: https://github.com/OptimalBits/bull/blob/develop/test/test_repeat.js#L105
