### ISSUE TITLE
How Redis Sentinel work with Bull queue (using NestJS)

### ISSUE THREAD

**Issue by littleKitchen** [OptimalBits/bull#2257]
## Description
I am working on a NestJs project using Bull queue. Here is the code I am using to connect Redis, and it works well.
Now, I need to switch to using Redis Sentinel. I searched online, but I could not find an appropriate tutorial.
I appreciate any help you can provide.
## Minimal, Working Test code to reproduce the issue.
```
BullModule.registerQueueAsync(
      {
        name: 'test',
        imports: [ConfigModule],
        useFactory: async (configService: ConfigService) => ({
          redis: {
            host: configService.get('REDIS_ADDR'),
            port: configService.get('REDIS_PORT'),
          },
        }),
        inject: [ConfigService],
      }
)

```
## Bull version
 3.29.3
## Additional information
nodejs 15.12.2

**Comment by manast** [comment]
Since Bull uses IORedis you should just pass the options IORedis expects for the sentinels configuration as explained here: https://github.com/luin/ioredis#sentinel
