### ISSUE TITLE
All jobs going into failed queue

### ISSUE THREAD

**Issue by milesrichardson** [OptimalBits/bull#226]
For some reason, every job I run goes into the failed queue, even when I call Done() without Error()

The stacktrace of every job in the failed queue looks like this:

     4) "Error: Finished job 761136
        at maybeWrapAsError (/home/ubuntu/..../node_modules/bull/node_modules/bluebird/js/main/util.js:68:12)
        at /home/ubuntu/..../node_modules/bull/node_modules/bluebird/js/main/promise_resolver.js:41:50
        at /home/ubuntu/..../helpers/job-queues.js:122:11
        at IncomingMessage.<anonymous> (/home/ubuntu/..../node_modules/node-parse-api/lib/Parse.js:442:17)
        at emitNone (events.js:72:20)
        at IncomingMessage.emit (events.js:166:7)
        at endReadableNT (_stream_readable.js:903:12)
        at doNTCallback2 (node.js:439:9)
        at process._tickDomainCallback (node.js:394:17)"

I am using the `Parse.Promise` library, perhaps that could be causing problems?

Example `process` (with private features of the code obfuscated)

  myQueue.process(function(job, done) {

    sleep.usleep(100000); // .1 seconds

    // Start with a trivial resolved promise
    var startPromise = Parse.Promise.as(true);
    startPromise.then(function() {
        if (...) {
          ...
          return Parse.Promise.as({
            key1: val1,
            key2: val2
          });
        } else if (job.data.anonKey) {
          return parseHelper.anonMethod(job.data.anonKey, job.data.anonKey2);
        } else {
          return new Parse.Promise.error('Missing arguments');
        }

    }).then(function(result) {

        var MyParse = require('node-parse-api').Parse;
        var myApp = new MyParse('securekey', 'securekey');
    
        myApp.insert('ClassName', {
          'key1': ...,
          'key2': {
            __type: 'Pointer',
            className: 'Key',
            objectId: result.anonKey
          }
        }, function (err, response) {
          if (err) {
            console.log(err);
            done(Error(err));
            return;
          }
            done('Finished job ' + job.jobId);
        });
    });
    });

Is there anything obviously wrong with this method of calling `done()` ?

**Comment by manast** [comment]
you should provide a minimal process function that reproduces the error so that we can test it and find what it is wrong with it.

**Comment by sam1360** [comment]
Not sure if you figured it out, but my guess is that

`done('Finished job + job.jobId);`
should be
`done(null, 'Finished job + job.jobId);`

**Comment by manast** [comment]
stupid me, I didn't see it either :)

**Comment by milesrichardson** [comment]
Thank you @sam1360 ! :)
