### ISSUE TITLE
ELASTICACHE & BULL Production environment

### ISSUE THREAD

**Issue by marius-softup** [OptimalBits/bull#2260]
I know that have been some posts about elasticache & bull configuration but none of them solves the issue.
Please can someone make an elasticache & bull config for us?
What is wrong with my config?

const auctionQueue = new Queue('auction', {
  prefix: '{auctioncluster}',
  createClient: () =>
    new Redis.Cluster(
      [
        {
          port: process.env.REDIS_PORT,
          host: process.env.REDIS_HOST,
        },
      ],
      {
        enableReadyCheck: false,
        maxRetriesPerRequest: 0,
      }
    ),
});

**Comment by marius-softup** [comment]
const Redis = require('ioredis');

**Comment by manast** [comment]
Can you please explain what is the issue you are having?

**Comment by marius-softup** [comment]
This configuration did not connect elasticache with bull.js
I tried a new one only with Redis: { host, port } and it looks like it is working.
I will close this issue, but I recommend you to have a look at why there is so difficult to connect bull with elasticache
We needed also that prefix thing.
Thank you!

**Comment by aporwal18** [comment]
@marius-softup - Can you guide what was your final config for createClient? and did you face the Moved error?

**Comment by navarrojava** [comment]
+1
