### ISSUE TITLE
bull is not supporting the cron expression "30 9 * * 5L"

### ISSUE THREAD

**Issue by hardikverma24** [OptimalBits/bull#2261]
bull is not supporting cron expression "30 9 * * 5L"

Bull is using cron-parser internally. cron-parser currently is on version 4.2.1, but bull is still using the old 2.13.1 version which does not support the expression "30 9 * * 5L".  The version of cron-parser is outdated and needs an update.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

Bull version - 3.16.0

**Comment by manast** [comment]
Ok, so just upgrading that dependency should to it...
