### ISSUE TITLE
Feature Request : Notification Icons next to Queues

### ISSUE THREAD

**Issue by selected-pixel-jameson** [OptimalBits/bull#2267]
Would it be possible to put a count or at least an indicator next to the different queues when they have an active job in them? I find that jobs in a different queue that are active can often go unnoticed. 

Thank you!

![Screen Shot 2022-01-22 at 1 28 18 PM](https://user-images.githubusercontent.com/28204537/150652895-40384d12-cb32-4f6a-bca1-85ca95e8c283.png)

**Comment by manast** [comment]
Wrong repo...

**Comment by selected-pixel-jameson** [comment]
Oops. Sorry.
