### ISSUE TITLE
PriorityQueue has no method 'clean'

### ISSUE THREAD

**Issue by julianfresco** [OptimalBits/bull#227]
I have a [code snippet](https://github.com/julianfresco/Bull-Queue-Scratch-Pad/blob/master/priorityQueue/clean.js) that I use to test the features of Bull, and while running the `clean` method on a priorityQueue, I get the following error:

    $ node clean
    /{...}/priorityQueue/clean.js:11
    helloWorldQueue.clean(0, 'completed');
                    ^
    TypeError: Object [object Object] has no method 'clean'
        at Object.<anonymous> (/{...}/priorityQueue/clean.js:11:17)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:929:3

Where with the normal Queue constructor, I get this output:

    $ node clean
    Cleaned {#} completed jobs
    Cleaned {#} waiting jobs
    Cleaned {#} active jobs
    Cleaned {#} delayed jobs
    Cleaned {#} failed jobs

**Comment by manast** [comment]
that may be a missing feature actually

**Comment by julianfresco** [comment]
Is 'being able to clean a PriorityQueue' enqueued to become a feature (see what I did there?), or was there some reason it was excluded?

**Comment by ryan-sandy** [comment]
Nope. I just totally missed the Priority Queue when I added the clean method.

**Comment by ryan-sandy** [comment]
Submitted a pull request #231 that adds these methods.

**Comment by julianfresco** [comment]
Awesome, thank you @ryan-sandy
