### ISSUE TITLE
Internal Server Error when trying to load arena to check the jobs

### ISSUE THREAD

**Issue by amanthegreatone** [OptimalBits/bull#2270]
## Description
Getting internal server error when trying to load arena to check jobs 

<img width="1280" alt="Screenshot 2022-01-24 at 6 01 51 PM" src="https://user-images.githubusercontent.com/24354452/150784342-3386aa24-cd41-402b-9352-13ff2c6b1940.png">

```
SyntaxError: Unexpected token o in JSON at position 1
at JSON.parse (<anonymous>)
at Function.Job.fromJSON (/home/apps/insite-server/node_modules/bull/lib/job.js:585:21)
at Job.fromId (/home/apps/insite-server/node_modules/bull/lib/job.js:145:41)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)


error: "Internal server error"

message: "Unexpected token o in JSON at position 1"
```

We have 20 different background jobs and it is a bit difficult to troubleshoot which job is giving this issue. Appreciate if we can get some insights into how to go about debugging this.

## Bull version
3.22

## Additional information
"@bull-board/api": "^3.9.0",
"@bull-board/express": "^3.9.0",

**Comment by manast** [comment]
Wrong repo...

**Comment by amanthegreatone** [comment]
it is an error in bull

**Comment by amanthegreatone** [comment]
`node_modules/bull/lib/job.js:585:21` this is where the error is happening in the bull library

**Comment by manast** [comment]
If there is an issue with Bull then create a test case that demonstrates with code the issue. If a third-party application triggers an issue I cannot help you in investigating that.
