### ISSUE TITLE
Missing job data when using enableAutoPipelining with ioredis

### ISSUE THREAD

**Issue by admidelu** [OptimalBits/bull#2276]
Hey, wanted to leave a note on an issue with bull & custom ioredis settings as I couldn't find any leads searching for this:
when using {
enableAutoPipelining: true,
maxRetriesPerRequest: null
}
on the worker nodes redis connections, on high load, some jobs kept failing due to having an empty job {data: {}} object. The jobs were verified to be properly populated when added to queue & had the data when pulled using getJobs(). Worse, after failing due to missing job data, the empty job data was persisted in the queue, retrying the jobs would be impossible. This was a real hassle, but disabling those ioredis settings completely solved this issue.

**Comment by manast** [comment]
Can you provide a test case that actually reproduces this behavior?
