### ISSUE TITLE
moveToComplete

### ISSUE THREAD

**Issue by kmescharikov** [OptimalBits/bull#2277]
## Description
When I use moveToComplete function inside promise.all for a >5000 jobs, half of this jobs pass and stay to the 'active' state, but all of this pass to 'completed' state

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
```
    const CronQueue = new Queue('cron');
    await fillQueue(CronQueue);
    const jobs = await CronQueue.getJobs();
    console.error(await CronQueue.getJobCounts());
    await Promise.all(jobs.map((j) => j.moveToCompleted(null, true, false)));
    console.error(await CronQueue.getJobCounts());
    
    function fillQueue(queue) {
  const jobs = [];
  for (let i = 0; i < 40001; i++) {
    jobs.push({ name: `job_${i}`, data: { i } });
  }
  return queue.addBulk(jobs);
}
```

## Bull version
4.2.1

**Comment by manast** [comment]
Can you complete the test code with what you get and what you expect?

**Comment by kmescharikov** [comment]
bit later please

**Comment by kmescharikov** [comment]
A bit better example
```javascript
const Queue = require('bull');
const { equal } = require('assert');

(async () => {
  try {
    const CronQueue = new Queue('cron');
    await fillQueue(CronQueue);
    const jobs = await CronQueue.getJobs();
    const preCompleteCounts = await CronQueue.getJobCounts();
    console.log(preCompleteCounts);
    await Promise.all(jobs.map((j) => j.moveToCompleted(null, true, false)));
    const postCompleteCounts = await CronQueue.getJobCounts();
    console.log(postCompleteCounts);
    equal(postCompleteCounts.waiting, 0, 'Waiting state should be empty.');
    equal(postCompleteCounts.active, 0, 'Active state should be empty.');
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
})();

function fillQueue(queue) {
  const jobs = [];
  for (let i = 0; i < 40001; i++) {
    jobs.push({ name: `job_${i}`, data: { i } });
  }
  return queue.addBulk(jobs);
}
```

**Comment by manast** [comment]
The reason is that in ```moveToCompleted``` you are passing "false" as the third parameter "notFetch", which is by the way the default value, meaning that it will fetch the next job and move it to active to avoid an extra roundtrip to Redis. Normally, you want to move jobs to the active state and then move them from active to completed or failed. I recommend you to study this pattern: https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#manually-fetching-jobs

**Comment by kmescharikov** [comment]
I don't understand. In my case periodically I need to get from the queue around 40 000 jobs, after processing these jobs I wanna mark them as completed. But with notFetch parameter or without it I have half of the jobs in the active state after "moveToComplete" calling on each of them.

**Comment by manast** [comment]
You are not using this library correctly. Jobs must go from wait to active to completed/failed. There are many examples and documentation you can follow to make it work as it is designed.

**Comment by kmescharikov** [comment]
Okay! I will explain what I mean:
Code for reproduce: 
```javascript
async function sequentialQueue() {
  const queue = new Queue('seq');

  for (let i = 0; i < 100; i++) await queue.add({ random_attr: 'random_value' });

  console.log({ afterAdd: await queue.getJobCounts() });

  for (let i = 0; i < 100; i++) await queue.getNextJob();

  console.log({ afterGetNextJob: await queue.getJobCounts() });

  const jobs = await queue.getJobs();

  for (const job of jobs) await job.moveToCompleted('succeeded', true);

  console.log({ afterMoveToCompleted: await queue.getJobCounts() });
}

async function batchQueue() {
  const queue = new Queue('batch');

  for (let i = 0; i < 100; i++) {
    await queue.add({ random_attr: 'random_value' + '_' + i });
  }
  console.log({ afterAdd: await queue.getJobCounts() });

  const jobs = await queue.getJobs();

  console.log({ afterGetJobs: await queue.getJobCounts() });

  for (const job of jobs) await job.moveToCompleted('succeeded', true);

  console.log({ afterMoveToCompleted: await queue.getJobCounts() });
}
```

When you running sequentialQueue func you will receive in console next one:
```javascript
{
  afterAdd: {
    waiting: 100,
    active: 0,
    completed: 0,
    failed: 0,
    delayed: 0,
    paused: 0
  }
}
{
  afterGetNextJob: {
    waiting: 0,
    active: 100,
    completed: 0,
    failed: 0,
    delayed: 0,
    paused: 0
  }
}
{
  afterMoveToCompleted: {
    waiting: 0,
    active: 0,
    completed: 100,
    failed: 0,
    delayed: 0,
    paused: 0
  }
}
```

2. When your run batchQueue func you will receive in console next one:

```
{
  afterAdd: {
    waiting: 100,
    active: 0,
    completed: 0,
    failed: 0,
    delayed: 0,
    paused: 0
  }
}
{
  afterGetJobs: {
    waiting: 100,
    active: 0,
    completed: 0,
    failed: 0,
    delayed: 0,
    paused: 0
  }
}
{
  afterMoveToCompleted: {
    waiting: 0,
    active: 50,
    completed: 100,
    failed: 0,
    delayed: 0,
    paused: 0
  }
}

```

How can your explain this? why do we see such a difference? Don't you think it's because getNextJob always makes a job active, while getJobs doesn't? However, this does not explain to us why we end up with 100 completed tasks and 50 active tasks.

**Comment by manast** [comment]
For manually processing jobs you need to use this pattern: https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#manually-fetching-jobs
As mentioned before, start from existing examples and build on top of that. The expectations you have for the methods you are using are not correct, that's why you get these "unexpected" results.
If you are new to Bull I recommend you to use BullMQ which has also better documentation: https://docs.bullmq.io/
