### ISSUE TITLE
job name gets overwritten with __default__

### ISSUE THREAD

**Issue by plus-** [OptimalBits/bull#2290]
## Description

After adding the job to the queue the name is overwritten

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

```
await queue.add('name', { hello: 'world' }, { jobId: 'job-default' })
const job = await queue.getJob('job-default')
 expect(job!.name).toBe('name')
```

>     expect(received).toBe(expected) // Object.is equality
> 
>     Expected: "name"
>     Received: "__default__"
> 

## Bull version
    "bull": "4.5.3",

**Comment by manast** [comment]
This is working correctly, are you sure you are testing the same code that you are pasting here?

**Comment by plus-** [comment]
this is a mistake in my unit test, I was reusing an existing queue with a different configuration because it was already in the redis. 

Please ignore this issue.
