### ISSUE TITLE
How execute one job per time

### ISSUE THREAD

**Issue by russosalv** [OptimalBits/bull#2293]
hi how i can execute one job per time?
i'm trying with concurrency = 1 and 
`limiter: {
	max: 1,
        duration: 125,
},`

but i'm not able to obtain that processor iterate one job per time

can you help pls?

**Comment by luozuzhu** [comment]
```
  repeat: {
      limit: 1
  }
```

**Comment by manast** [comment]
@russosalv With one worker and concurrency one only one job will be processed at a time, you do not need any limiter option nor repeat. If it is not working please paste a short example code that reproduces it.

**Comment by soylomass** [comment]
@manast Is there a way to run one job at a time when using multiple workers? I define concurrency 1, but then there can be as many jobs as running at a time as workers there are.

**Comment by manast** [comment]
@soylomass  The concurrency is per worker, so as you mentioned it will execute in parallel as many jobs as workers you have. Global concurrency is actually a quite complex problem to solve, so currently we only offer it on the Pro version of BullMQ: https://docs.bullmq.io/bullmq-pro/groups/concurrency
