### ISSUE TITLE
removeOnComplete and removeOnFail options not respected

### ISSUE THREAD

**Issue by ctrlaltdylan** [OptimalBits/bull#2294]
## Description

`removeOnComplete` and `removeOnFail`  job options not respected.

Screencast to show job options while the queue is paused. Then showing the redis data and then resuming the queue.

After the queue is resumed, the job data disappears.

https://cln.sh/SyqWGD

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

```javascript
queue.add(
{
   test: 123
},
{
    removeOnComplete: false,
    removeOnFail: false,
    jobId: <your unique ID here, I use UUIDs with namespacing>
}
);
```
## Bull version
v4.5.0

## Additional information

Using Upstash as a Redis provider, ECS as a worker processor.

**Comment by manast** [comment]
Unfortunately, you are using upstash that for the moment is not compatible with Bull nor BullMQ: 
https://github.com/upstash/issues/issues/17
You are welcome to vote for this issue so that they increase its priority...

**Comment by ctrlaltdylan** [comment]
Confirmed working like a charm off of Upstash! Amazing.

**Comment by manast** [comment]
Yeah, we are going to raise an exception, since documentation alone is not enough https://github.com/OptimalBits/bull/issues/2296
