### ISSUE TITLE
Warn users that Bull is not compatible with Upstash

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#2296]
Due to the recent popularity of https://upstash.com as a Redis hosting service, we are starting to get reports of people trying Bull and getting all kinds of weird behaviors. Currently, the way Upstash is implemented is not compatible with Bull. Hopefully, in the future, it will be, but for now, we should throw an error when using a host using the upstash domain so that users do not use the library as it will not work.

I created this issue in the Upstash repo to give visibility to this problem and so that everybody can track its resolution: https://github.com/upstash/issues/issues/18

**Comment by ProCode47** [comment]
@manast Thank you for this sir

Actually Bull doesn't send an specific error .. for me it just didn't work and kept throwing 
`TypeError: handler.bind is not a function`

I was going in circles until I stumbled across this and yes, I'm using Upstash 

so the question I'm asking right now is which redis hosting provider is compatible bull (preferably that has a free plan like Upstash)

**Comment by manast** [comment]
@ProCode47 all Redis providers are supported, Upstash is the exception because they are not 100% compatible with Redis.

**Comment by nastari** [comment]
Humm, interesting to know.. now everything is explained

**Comment by enesakar** [comment]
@manast we updated upstash so it is compatible with bull anymore. you can close this.

I can not say the same for bullmq but hoping you replace redis-stream with pub-sub for the breaking functionality there.

**Comment by manast** [comment]
Bull should be now supported by Upstash, and BullMQ will be in the future when we replace streams by PubSub or if upstash implements streams: https://github.com/upstash/issues/issues/18
