### ISSUE TITLE
question: How to dynamically update the rate Limit of one queue?

### ISSUE THREAD

**Issue by Lp-Francois** [OptimalBits/bull#2298]
## Description

There is 1 queue processing.

One job is querying data on an external API. This API has a rate limit that is **unknown**. It could be 30 req/s in the morning and 100 req/s in the afternoon. 
We are only aware of it when the API is returning a **rate limit error code 429.**

The best solution would be to dynamically reduce [the rate limiter option of the queue](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queue) when getting rate limited. Is it possible?

As in NestJS, we pass the options to the queue when creating the BullQ module, I am not sure it is possible without having to restart the whole application.

## Bull version

Using the NestJS implementation:

```
"@nestjs/bull": "^0.4.2",
"bull": "^4.5.1",
```

## Additional information

The current implementation is to try to adapt the queue to the rate limit is the following:
If we get rate limited, we throw an error in the job to try later. And a listener on queue failures is pausing the queue for x minutes. But as the rate limit of the API is pretty random, it is not a good solution.

```js
  @OnQueueFailed()
  async onQueueFailed(job: Job, error: Error) {
    this.logger.warn(`QueueFailed with job ${job.name}: ${error.message}`, QueriesConsumer.name);

    if(error?.message?.includes('Request failed with status code 429')) {
      await this.service.pauseAPIQueriesQueue();
      await this.service.resumeAPIQueriesQueue(true /* means we wait for 5min before resuming the queue*/);
    }
  }
```

We use NestJS in Kubernetes. So we could maybe keep track of the current rateLimit in a config file (emptyDir), and when getting rate limited, we reduce the variable in the config file and restart the application to re-recreate the queue. with the lower rate limit.

What do you think?

**Comment by devadathanmb** [comment]
Did you find any way to do this?

**Comment by MegaSpaceHamlet** [comment]
Apparently this is only possible in BullMQ. 

[How-To Guide](https://blog.taskforce.sh/rate-limit-recipes-in-nodejs-using-bullmq/)

**Comment by devadathanmb** [comment]
> Apparently this is only possible in BullMQ.
> 
> [How-To Guide](https://blog.taskforce.sh/rate-limit-recipes-in-nodejs-using-bullmq/)

Alright. Thanks a lot
