### ISSUE TITLE
Stacktrace is undefined in failed jobs

### ISSUE THREAD

**Issue by avermeil** [OptimalBits/bull#230]
Hi!

When jobs fail, the `stacktrace` field in the job hash in redis stays "undefined". It looks to me like this is the fault of a line in the lua script on line 404 of `job.js`, which overwrites the `stacktrace` field with a value coming from the argument `context`, which isn't defined when `_moveToSet()` is called by `moveToFailed()`.

Since the `stacktrace` field is already set by `_saveAttempt()`, just commenting out the that line of the lua script seems to fix it:

`//redis.call("HSET", KEYS[3], "stacktrace", ARGV[1])`

 But I might be missing something.

Any ideas on what is going on here?

**Comment by jozsi** [comment]
+1

**Comment by nibblesnbits** [comment]
I've noticed the same thing. I'm trying to figure out a good clean solution.  I'll try to get a PR in this weekend.
