### ISSUE TITLE
[Question] Reference docs and types

### ISSUE THREAD

**Issue by johnnyasantoss** [OptimalBits/bull#2323]
I see that you are keeping all the documentation and reference updated! That's great and show a lot of effort being made to make sure devs onboard well on the project.
Thinking about developer experience and onboarding/documentation efforts would not be better to maintain a global `types.d.ts` file with the interfaces so that people importing this package onto their projects (TS and JS) get auto intellisense and with this reducing the need to open a question on the repo (or on the @types/bull repo)? This would allow backlinks from the documentation to the types file and ease understanding.

Example: the [Reference docs on the Queue obj](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queue) has a lot of interfaces that could be put together to form the `types.d.ts` file, making it easier to know which fields go into the QueueOptions object instead of needing to go back to docs every time you forget the field name.

Does this make sense?

**Comment by manast** [comment]
I think it would be even better to move to BullMQ since it is written in typescript and provides all its goodies...
we are not going to invest a lot of time in more improvements in Bull other than stability fixes and minor features.
