### ISSUE TITLE
Intermittent queue addJob rejections "disconnected before secure TLS connection was established"

### ISSUE THREAD

**Issue by ctrlaltdylan** [OptimalBits/bull#2328]
## Description

Bull.js occasionally rejecting new jobs added to the queue. I have a dedicated service hosted on Amazon ECS that interfaces with Bull.js with Amazon managed Redis.

I send jobs to this service via an HTTP API.

Occasionally, jobs will be rejected with a mysterious TLS rejection:

```
Error: Client network socket disconnected before secure TLS connection was established
```

It's only happening intermittently, which is making me think that this is a configuration issue. I'm not sure if the blocked clients # in the Bull dashboard has something to do with it:

<img width="705" alt="CleanShot 2022-03-21 at 10 16 58@2x" src="https://user-images.githubusercontent.com/2694734/159280339-faa035b4-f75e-4e2b-87cb-b85b893c842e.png">

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

Sorry, it's a high volume intermittent failure on infrastructure, not something I can code up in an example.

## Bull version

`4.5.1`

## Additional information

Queue hosted on Amazon ECS with Fargate, Amazon Redis as the memory store.

**Comment by CassandraTrilus** [comment]
I'm having this issue as well. Queue hosted on Heroku with the heroku-redis add on. After processing some records in the queue it looks like the worker stops picking up jobs off of the queue. Restarting the worker seems to temporarily alleviate this. This happened once during the afternoon when I redeployed the app, after which 5 unprocessed jobs were immediately ran. I also manually restarted the workers a few minutes ago to get the last batch of records processed (3 more). Occasionally getting the TLS error as mentioned above which is what triggered the team to have us look at it.

**Comment by ctrlaltdylan** [comment]
@CassandraTrilus I tried `await`'ing the `Queue.add` call, and I was really really hoping that was it but no luck.

I'm wondering if there's some kind of non-Promise-ified callback within the Redis library or the `Queue.add` call, which is causing a race condition between your HTTP request processing and the job being added.

I'm using a serverless setup, but it sounds like you're using a regular Heroku dyno for your producer of Queue jobs?

**Comment by CassandraTrilus** [comment]
We are using a regular Heroku dyno - what's weird is that it's a difficult error to reproduce. I have two different stage apps using the same branch, same add ons, same bull version, etc, but only one is experiencing this issue. I also can't seem to figure out if people are having similar issues with Bullmq. I know that support for Bull is limited now and the recommendation for some issues posted here has been to move to Bullmq instead.

**Comment by ctrlaltdylan** [comment]
@CassandraTrilus good call, I think the Job's API is just about the same across both bull & bullmq, I might just try bullmq or downgrade bull, it's clearly a new bug and I never encountered this in bull v3.x.

**Comment by manast** [comment]
@CassandraTrilus when the workers stop processing new jobs, you can check if 1) there are active jobs, meaning the workers are stuck processing jobs and not completing them for some reason, 2) use the getWorkers() API  or redis CLIENT LIST command to see if there are any actual workers connected to Redis.

**Comment by ctrlaltdylan** [comment]
@manast what's your recommendation for avoiding this error on both processing and producing of jobs?

Should we somehow increase the number of connections or workers?

**Comment by manast** [comment]
I do not have any recommendation because I do not know why this happens for you...

**Comment by manast** [comment]
Btw, if you know about an older version of bull that did not exhibit this problem it would be useful to know it to try to narrow the code that produces it.

**Comment by ctrlaltdylan** [comment]
Just an update, in my case switching to `bullmq: 1.78.2` fixed the issue for me it appears.

Another silly mistake to check is to make sure you're `await`'ing every single `Queue.add` call, otherwise your HTTP API handler will close before the job is enqueued.

I'm still receiving this error on _processing_ but I attribute this to some async actions taking too long and the handlers just timing out, because of Vercel's timeout limits.

**Comment by manast** [comment]
@MarcusHSmith what issue are you having, and can you provide reproducible code?

**Comment by nicholasoxford** [comment]
Each time I ran into this issue, it's because I have hit my current heroku redis connection limit tier. Check out data.heroku.com and it will show you the number of connections being used. Each time upgrading the redis level has improved our situation.

**Comment by ctrlaltdylan** [comment]
Thanks for the tip!

I'm using Elasticache, I'll check my connection limits and share any
graphs. I hope it's something this simple.
