### ISSUE TITLE
Calling done(Error(), {some result})

### ISSUE THREAD

**Issue by sam1360** [OptimalBits/bull#233]
Wondering if it is possible to use done to create and error and result, and access both in the queue.on('failed') portion?

**Comment by manast** [comment]
hmm, ok, so some kind of part result that can be used for something. Problem is that the process function expects a promise, done is just for legacy code. Maybe you could return your own custom error object that includes a field with the part result...

**Comment by sam1360** [comment]
Yeah I think that would be my best bet. Thanks for the idea!
