### ISSUE TITLE
How do I prevent my job from being marked as stalled? I have changed the config but isn't working

### ISSUE THREAD

**Issue by SidSethi** [OptimalBits/bull#2332]
## Description

Hi! Would appreciate assistance here. I've looked over multiple other issues + docs to figure this out but no luck yet.

I have a bull queue which runs a repeatable job on some interval, where each job will take several minutes, if not much longer. I notice that each time the job gets marked as stalled shortly after starting - I think it has to do with the 30 sec default `lockDuration` per docs here https://github.com/OptimalBits/bull#important-notes.

I don't see where my job could be blocking the event loop, everything is done in promises, it does pretty much no heavy CPU work. Most of it is just axios requests + holding data in memory. What do I need to change?

I confirmed that my configs were correctly applied to the queue by logging out `this.stateMachineQueue.settings`:
```
{"lockDuration":3600000,"maxStalledCount":0,"stalledInterval":30000,"guardInterval":5000,"retryProcessDelay":5000,"drainDelay":5,"backoffStrategies":{},"lockRenewTime":5400000}
```
Note this reflects my config from below code.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

```
this.stateMachineQueue = new Queue(
  'state-machine',
  {
    redis: {
      port: <redisPort>,
      host: <redisHost>
    },
    defaultJobOptions: {
      removeOnComplete: true,
      removeOnFail: true
    },
    settings: {
      lockDuration: 3600000, // 1hr
      maxStalledCount: 0
    }
  }
)
```
```
this.stateMachineQueue.process(
  1 /** concurrency */,
  async (job) => {
    try {
      await this.processStateMachineOperation()
    } catch (e) {
      ...
    }
  }
)
```
```
this.stateMachineQueue.add(
  /** data */ { ... }
  /** opts */ { repeat: { every: 10000 } }
)
```

## Bull version

3.22.9

**Comment by manast** [comment]
There is no need to modify the ```lockDuration``` setting in general. Can you provide the complete code including the processor? you are probably not returning a promise correctly.

**Comment by SidSethi** [comment]
Sure, processor code below (also added to original post). I don't think there is any other relevant code.
```
this.stateMachineQueue.process(
  1 /** concurrency */,
  async (job, done) => {
    try {
      await this.processStateMachineOperation()
    } catch (e) {
      ...
    }

    done()
  }
)
```

And thank you for the very prompt response!

**Comment by manast** [comment]
Always the same issue... you are using async + done, just use one or the other not both.

**Comment by SidSethi** [comment]
Interesting - so I should just not call `done()` at the end of my processor?

Also, do you think this is the cause of my issue?

**Comment by manast** [comment]
If you are using promises then you should not use "done". And yes I think this is the cause of the issue.

**Comment by SidSethi** [comment]
Understood, this makes sense to me. I'll try it out now. But could you explain why you think it would cause the issue? It seems that the job gets marked as stalled while still inside the processor function, well before `done()` would ever have been called

**Comment by SidSethi** [comment]
I just tried this out, and still can see the job get marked as stalled

The new processor code is:
```
this.stateMachineQueue.process(
  1 /** concurrency */,
  async (job) => {
    try {
      await this.processStateMachineOperation()
    } catch (e) {
      ...
    }
  }
)
```

Does that look right?

**Comment by SidSethi** [comment]
Ok update! I've confirmed that `lockDuration` is almost exactly correlated with time for job to stall. I confirmed this by changing the job processor to just timeout for a substantial amount of time, modifying the `lockDuration` to different values, and observing that the `stalled` event was fired always within 30sec of the `lockDuration` value. I think this 30sec variance has something to do with the other settings fields - likely `lockRenewTime` or `stalledInterval`.

The interesting thing here is that if i set `maxStalledCount` to 0, then the job never stalls, regardless of `lockDuration` value. This is a bit surprising to me since `maxStalledCount` according to the description governs how many times a job will be re-processed once stalled, as opposed to the current behavior.

Would really appreciate any insight you can provide here! 🙏

**Comment by manast** [comment]
If ```maxStalledCount``` is 0 then the job will just fail when it stalls, instead of being picked-up again for processing.

That the ```lockDuration``` is correlated with time to stall makes sense if your processor is not working properly. 1) Either it crashes the process, or 2) it takes 100% of the CPU time.

Btw, you can write the process like this:

```ts
this.stateMachineQueue.process(
  1 /** concurrency */,
  async (job) => {
    return this.processStateMachineOperation();
  }
)
```
The question is, what is ```processStateMachineOperation``` doing? is it some heavy for-loop that hands nodejs event loop for a long time?

**Comment by SidSethi** [comment]
So I actually am totally fine with the job not being picked up for re-processing, bc its' a cron job anyway so I'm totally fine with the next run picking it up.

To your point, it doesn't seem to have anything to do with what my `processStateMachineOperation()` function does, because as I mentioned in my above msg, I was able to get the job to stall by just changing the task to do nothing except wait for some period of time longer than the `lockDuration`. The exact code is:

```
async processStateMachineOperation() {
    return new Promise((resolve) => setTimeout(resolve, 100000))
}
```

**Comment by manast** [comment]
> One confusing part about the job being re-processed after stalling is that the docs seem to indicate it will be re-processed from the beginning, but the behavior I've observed is that after the job gets marked as stalled, it simply continues processing from where it left off. Does that sound right?

That's impossible unless you created a processor with such capabilities.


> To your point, it doesn't seem to have anything to do with what my `processStateMachineOperation()` function does, because as I mentioned in my above msg, I was able to get the job to stall by just changing the task to do nothing except wait for some period of time longer than the `lockDuration`. The exact code is:
> 
> ```
> async processStateMachineOperation() {
>     return new Promise((resolve) => setTimeout(resolve, 100000))
> }
> ```

So please provide a test code that I can just run as-is and that demonstrates such behavior.

**Comment by ceroy-ak** [comment]
Taking the above example
@manast if I don't call done() like this then the "completed" event is not being fired.

```javascript
this.stateMachineQueue.process(
  1 /** concurrency */,
  async (job, done) => {
    return this.processStateMachineOperation().then(() => done(null));
  }
)
```

**Comment by SidSethi** [comment]
> Taking the above example @manast if I don't call done() like this then the "completed" event is not being fired.
> 
> ```js
> this.stateMachineQueue.process(
>   1 /** concurrency */,
>   async (job, done) => {
>     return this.processStateMachineOperation().then(() => done(null));
>   }
> )
> ```

@ceroy-ak , I confirmed locally that the `completed` event is fired with the code I shared above (reposted below), without `done`:
```
this.stateMachineQueue.process(
  1 /** concurrency */,
  async (job) => {
    return this.processStateMachineOperation();
  }
)
```

**Comment by SidSethi** [comment]
> > One confusing part about the job being re-processed after stalling is that the docs seem to indicate it will be re-processed from the beginning, but the behavior I've observed is that after the job gets marked as stalled, it simply continues processing from where it left off. Does that sound right?
> 
> That's impossible unless you created a processor with such capabilities.
> 
> > To your point, it doesn't seem to have anything to do with what my `processStateMachineOperation()` function does, because as I mentioned in my above msg, I was able to get the job to stall by just changing the task to do nothing except wait for some period of time longer than the `lockDuration`. The exact code is:
> > ```
> > async processStateMachineOperation() {
> >     return new Promise((resolve) => setTimeout(resolve, 100000))
> > }
> > ```
> 
> So please provide a test code that I can just run as-is and that demonstrates such behavior.

@manast to answer both your points, here is the test code that 1) becomes stalled then resumes processing from where it left off and 2) shows that even with nothing in the processor function, the job will become stalled

```
this.stateMachineQueue = new Queue(
  'state-machine',
  {
    redis: { ... },
    defaultJobOptions: {
      removeOnComplete: true,
      removeOnFail: true
    },
    settings: {
      lockDuration: 30,
      maxStalledCount: 1
    }
  }
)

this.stateMachineQueue.on('global:stalled', (job) => {
  this.logError(`stateMachineQueue Job Stalled - ID ${job.id}`)
})

this.stateMachineQueue.process(
  1 /** concurrency */,
  async (job) => {
    try {
      await this.processStateMachineOperation()
    } catch (e) {
      ...
    }
  }
)

this.stateMachineQueue.add(/** data */ { ... })

async processStateMachineOperation() {
  for (let i = 0; i < 20; i++) {
    this.logError(`SIDTEST processStateMachineOperation total duration ${i * 10} seconds; Starting another 10 sec wait now...`)
    await utils.timeout(10000, false)
  }

  return
}
```

Here is what I see in the logs:
```
...
SIDTEST processStateMachineOperation total duration 0 seconds; Starting another 10 sec wait now...
SIDTEST processStateMachineOperation total duration 10 seconds; Starting another 10 sec wait now...
stateMachineQueue Job Stalled - ID undefined
SIDTEST processStateMachineOperation total duration 20 seconds; Starting another 10 sec wait now...
SIDTEST processStateMachineOperation total duration 30 seconds; Starting another 10 sec wait now...
...
```

**Comment by manast** [comment]
First of all, why do you change the lockDuration setting to 30 milliseconds, what is your intent, basically that is going to create problems for any job lasting more than 30ms since the lock renewal interval is 15 seconds by default.

Secondly, the job stalls yes, but your code continues running, so nothing strange here either.

So other than having a wrong setting for lockDuration everything works as expected.

**Comment by SidSethi** [comment]
I simply set the `lockDuration` to 30sec to test if my code would stall without doing anything - you mentioned earlier that job will stall if:
> your processor is not working properly. 1) Either it crashes the process, or 2) it takes 100% of the CPU time.

My intent with the above example code was to show that the job stalls every time, despite doing nothing except waiting.


> Secondly, the job stalls yes, but your code continues running, so nothing strange here either.

Why do you say this is not strange? This seems to conflict with your earlier statement that this behavior should be impossible as a job that stalls will always be re-processed from the beginning.

> So other than having a wrong setting for lockDuration everything works as expected.

I'm also unclear about this since 30sec is the default value? I defined it just for explicitness in my code example.

**Comment by manast** [comment]
> I simply set the `lockDuration` to 30sec to test if my code would stall without doing anything - you mentioned earlier that job will stall if:

Yes, but you set the ```lockDuration``` to 30 *MILLISECONDS*.

> My intent with the above example code was to show that the job stalls every time, despite doing nothing except waiting.

Yes, since you config the ```lockDuration``` to 30 milliseconds...

> Why do you say this is not strange? I'm a bit confused since you mentioned earlier that this behavior should be impossible as a job that stalls will always be re-processed from the beginning.

This is the way javascript works... the job is stalled, but the code is still running.

> I'm also unclear about this since 30sec is the default value? I defined it just for explicitness in my code example.

You didn't, you set it to 30 milliseconds.

**Comment by manast** [comment]
I recommend you take some working examples from the tests and work your way from there: https://github.com/OptimalBits/bull/blob/develop/test/test_queue.js

**Comment by SidSethi** [comment]
> I recommend you take some working examples from the tests and work your way from there: https://github.com/OptimalBits/bull/blob/develop/test/test_queue.js

These are great, thanks for sharing @manast - I'll look through them!
