### ISSUE TITLE
how to remove an active job?

### ISSUE THREAD

**Issue by kaiomoreira-dev** [OptimalBits/bull#2335]
Hello everybody. I'm looking for a solution to remive a job that is active. Is there any way to do this with bull or bullmq?

**Comment by manast** [comment]
Currently it is not possible, but it is planned to be implemented on the Pro version only.

**Comment by kaiomoreira-dev** [comment]
Obrigado

**Comment by homerjam** [comment]
Why is this a pro feature 🤔
