### ISSUE TITLE
Urgent: update delayed set called with a timestamp in the future

### ISSUE THREAD

**Issue by evanhuang8** [OptimalBits/bull#234]
I recently ran into a situation where the `updateDelaySet` is called with a `delayTimestamp` in the future, which causes future jobs to run. I will try to write a simplified script to replicate the bug (can't really post the application code that I am working on).

I am still unclear about the root cause but one solution that can satisfy the promise that no delayed jobs are prematurely run is to simply set the `delayTimestamp` to `Date.now()` if the former is greater than latter. 

I will submit a pull request shortly, please merge. Thanks!

**Comment by manast** [comment]
please let us know the status of this.

**Comment by evanhuang8** [comment]
Actually I have submitted the PR, please check. Couldn't really write the script since I am out of town at the moment, but essentially I have a task that is scheduled to run immediately, which within it schedules a replicate of itself 30 days later. The second task, supposed to run 30 days later, somehow run immediately
