### ISSUE TITLE
Distinguishing between retryable errors and non-retryable errors

### ISSUE THREAD

**Issue by snawaz** [OptimalBits/bull#2342]
_I'm using `@nestjs/bull`, and  as most functionalities are provided by the underlying library &mdash; that is `bull`, I'm posting my question here._ 

As I'm using `Promise<>` as opposed to `done()`  in process job function, I can `throw` an error of any type &mdash;  `Error` or some user-defined type &mdash; and the job will be retried automatically by `bull` (and `@nestjs/bull`). That is cool, as long as the error I encountered is a **retryable** error.  

However, how are we suppose to handle errors which are **non-retryable**? In this case, I want `bull` to permanently remove such jobs from the queue. Calling `job.discard()` seems to work, or simply do not throw any error at all (i.e _pretend_ that job has completed successfully). This approach does not seem good enough to me, as it requires a paradigm-shift. If retry can be done without calling `job.retry()`, I guess no-retry should be done without calling `job.discard()` as well. That'd be a consistent and less confusing approach.

In the absence of a consistent approach, I'd suggest `bull` to define an exception of type `UnrecoverableError` that can be thrown by the users of `bull` and `bull` can decide accordingly whether to retry or not. If this makes sense, I can implement this functionality and create a PR.

**Comment by roggervalf** [comment]
hi @snawaz, this is currently supported by bullmq, not in bull, as reference you can check this https://github.com/taskforcesh/bullmq/pull/1074

**Comment by snawaz** [comment]
> hi @snawaz, this is currently supported by bullmq, not in bull, as reference you can check this [taskforcesh/bullmq#1074](https://github.com/taskforcesh/bullmq/pull/1074)

Yes. I've seen that already. I wish `bull` supports the same, not necessarily the same way. I'm using `@nestjs/bull` (which internally uses `bull`), so I hope this feature is supported.

**Comment by manast** [comment]
@snawaz If the users moved to BullMQ we would not need to maintain it anymore, so the question is not why we maintain 2 projects, is why not everybody only uses 1 of them. Some background here: https://medium.com/@rockstudillo/beta-release-of-bullmq-4-0-867960aec51

**Comment by snawaz** [comment]
> @snawaz If the users moved to BullMQ we would not need to maintain Bull anymore, so the question is not why we maintain 2 projects, is why not everybody only uses 1 of them. Some background here: [medium.com/@rockstudillo/beta-release-of-bullmq-4-0-867960aec51](https://medium.com/@rockstudillo/beta-release-of-bullmq-4-0-867960aec51)

Thanks. I was not aware of these things. I'll plan to switch to `bullmq`. There seems to be a `@nestjs/bullmq` module as well.

Closing this issue
