### ISSUE TITLE
[question] What happens if I add multiple named jobs with same name?

### ISSUE THREAD

**Issue by trsh** [OptimalBits/bull#2356]
For example

```
await transcoderQueue.add('image', { input: 'myimagefile' });
await transcoderQueue.add('image', { input: 'myimagefile2' });
```

and have 1 processor 

```
transcoderQueue.process('image', processImage);
```

will the second one overwrite the first if its not yet processed? Or will they nicely run in row - 1 and then second?

**Comment by manast** [comment]
They will nicely run in row, but I guess you already discovered it :)
