### ISSUE TITLE
Can't achieve 1 concurrency even after explicitly setting it to 1!

### ISSUE THREAD

**Issue by yagnesh-s-crest** [OptimalBits/bull#2360]
## Description
I do understand that understanding bull's concurrency might be a little confusing at first but as far as I understood, calling `.process` at the Queue level will increase all over concurrency to 1 by default and if there are explicit values set on a process like `.process('named_job', 5, worker)` then it'll increase overall queue's concurrency by 5.
Now my use case involves strict 1 concurrency thus I've split all my named jobs(making around 23 queues) to become individual queues themselves so I assume that my final concurrency should be only one!

## Desired output
I think that only 1 job should be active if the concurrency value is only 1 on that queue

## Current output
I'm getting 3x jobs active at a time always! Please look at the screenshot below
[![3-concurrency.png](https://i.postimg.cc/cJsZwyNS/3-concurrency.png)](https://postimg.cc/k2hkPH41)

## Minimal, Working Test code to reproduce the issue.
```javascript
// Queue file
const Queue = require('bull')
const { worker }  = require('../../workers')
const { addJobIntoQueue, executeWorkerWithLogs } = require('../../utils/queue.utils.js')
const { REDIS_URL } = process.env

const queue = new Queue('queue_name', {
  redis: REDIS_URL,
})

queue.process(1, (job) => executeWorkerWithLogs(job, worker.workerFunction))

// below method will be used at other places to push jobs into the queue using util function!
const schedule = async (data, options) => await addJobIntoQueue(queue, { ...data, action: 'some value' }, options)

module.exports = {
  schedule,
  queue,
}

// Utils file
// ...
const addJobIntoQueue = async (queue, data, options = {}) => {
  // some business logic
  await queue.add(data, options)
}

const executeWorkerWithLogs = async (job, worker) => {
  try {
    // something async thing like DB calls that I'd like to perform for each job but is not part of business logic (aka worker logic)
    await worker(job)
    // something async thing which I'd like to perform after a worker has finished
  } catch (error) {
    // something async thing which I'd like to use if the above code throws an error
    throw error // throw the same error from here so that bull can fail that job automatically!
  }
}
// ...

```

**Comment by manast** [comment]
The concurrency factor is per worker, maybe you have more than one worker running in parallel?
Btw, given a guarantee like having a max concurrency for a queue is not trivial, so we offer this functionality in the Pro version: https://docs.bullmq.io/bullmq-pro/groups/concurrency Also the PRO version supports groups which maybe aligns better with your requirements.

**Comment by yagnesh-s-crest** [comment]
> The concurrency factor is per worker, maybe you have more than one worker running in parallel? 
@manast, I'm using forking so I have 1x master and 2x worker cluster, so is that a reason for being a total of 3x concurrency?

**Comment by yagnesh-s-crest** [comment]
> Also the PRO version supports groups which maybe aligns better with your requirements.

Also, we're planning to move to Bull MQ Pro on upcoming days anyway but we're going through a strict timeline so, for now, we're going to use Bull for around a month or so!

**Comment by manast** [comment]
> @manast, I'm using forking so I have 1x master and 2x worker cluster, so is that a reason for being a total of 3x concurrency?

Yes, every running instance will process jobs with concurrency factor 1 as you specified, so in total, in your case, it would be 3.

**Comment by yagnesh-s-crest** [comment]
Thanks, @manast for pointing it out, I'll change it to only listen on the master cluster so that I can have the assurance of it only running at 1 concurrency!
I'm glad to close this issue as I think it's not Bull's issue at all!
