### ISSUE TITLE
400 Error with ZADD command when adding to the Queue

### ISSUE THREAD

**Issue by ypotnuru** [OptimalBits/bull#2366]
## 400 Error with ZADD command when adding to the Queue with AWS Redis Cluster Mode Enabled.
I'm trying to connect bull queue on ELASTIC CACHE REDIS on AWS with cluster mode enabled . 
It works well for sometime and suddenly it starts giving 400 Error with ZADD command ,  when i try to add an item to the queue . I have configured the prefix with in "{ }" curly brackets as suggested in the Patterns section .  

## Additional information
using the following configurations 

enableReadyCheck: false,
maxRetriesPerRequest: null

**Comment by manast** [comment]
@ypotnuru what is 400 error and who is giving it?

**Comment by ypotnuru** [comment]
@manast  I see the bull is throwing the 400 error intermittently when i tried to add a new item to the queue , error thrown is in the below format.

{
command = "zadd"
arguments = "{myprefix}myqueue"
}

how ever , this seems to be resolved and working fine ,  after i configured "createClient" in the bull options along with the prefix explicitly for clustered redis
