### ISSUE TITLE
How to wait until job is done by retries and don't try to run other jobs

### ISSUE THREAD

**Issue by skliarovartem** [OptimalBits/bull#2367]
I need to wait until current job will be done and don't run jobs which are after current one.
When I `throw new Error('test')` current job(`job1`) will try to be executed again, because I set `backoff` and `attempts` and it is working, I can see how system is trying to execute `job1` again and again. But if in this time I will crate new job(`job2`), it will executes immediately and will not wait for `job1`.
I need don't execute `job2` until I call `job1.done();`

**Comment by skliarovartem** [comment]
I thought is is one the main ideas about queues be able to run jobs sequentially, one by one...

**Comment by manast** [comment]
No, one of the main ideas for distributed queues is to be able to process as many jobs as possible in a reliable manner. The Pro version however allows limiting the concurrency per group to 1: https://docs.bullmq.io/bullmq-pro/groups/concurrency
