### ISSUE TITLE
Are there any guides/docs on production setup?

### ISSUE THREAD

**Issue by aristofun** [OptimalBits/bull#2369]
Where can I find the docs explaining the production cluster setup for bull? 

For example, it's not clear how exactly Bull producers and consumers interact with Redis in edge cases, how automatic recovery from process crashes works, how to setup persistence etc.

Appreciate any help.

**Comment by aristofun** [comment]
Also it's not clear what this phrase means 

> NOTE: From version 3.2.0 and above it is recommended to use threaded processors instead.

**Comment by manast** [comment]
You just need to setup a production Redis instance as provided by so many hosting companies. Btw, if you are new to Bull, why not start using the newest version? https://github.com/taskforcesh/bullmq
