### ISSUE TITLE
How to set 'attempts' and 'Backof'f on a queue globally

### ISSUE THREAD

**Issue by pravin-d** [OptimalBits/bull#237]
I have 2 node instances. One push a task(send Email) and other consumes it. The email config and all the email related stuff is present on the consumer. I was thinking it would make sense to keep the retry config also on the consumer. So I'm looking for a way to set the number of retries, backoff delay etc on the queue globally, i.e without using queue.add() api. Is it possible ?

**Comment by evanhuang8** [comment]
Are you referring to like a default setting kind of thing? Because the retry and backoff are indeed carried globally (as part of the job's data). If you want a default setting, you can just do that in your application

**Comment by pravin-d** [comment]
Retry and backoff are added using queue.add() API. queue.add will be called from a producer Nodejs instance. I wanted to know if there is a way to set the retry and backoff on queue on the consumer side, i.e where queue.process() is called from..

**Comment by evanhuang8** [comment]
Ah got it.

Currently there isn't a way to do it, other than you manually reschedule the job in the consumer's processing functions. Technically all consumers can schedule jobs as well, so it shouldn't be a big problem
