### ISSUE TITLE
Node.JS Heap out of memory due to PromiseReaction is retaining lots of memory

### ISSUE THREAD

**Issue by yagnesh-s-crest** [OptimalBits/bull#2370]
## Description
I have around 30x queues for different tasks and there is one individual worker logic that is being listened to in each queue. There is one middleware function that gets executed before and after the worker logic.

The main issue is that once I start pushing the bulk of jobs into one queue (10000 jobs), I'm only processing one job at a time (1x strict concurrency for queue) and somehow memory heap raises drastically that it crosses 2 GB heap limit. So I thought to collect a dump for it and I've found out that **PromiseFulfillReactionJobTask** and **PromiseReaction** tasks are consuming a lot of memory triggering the crash. Please refer to the screenshots below

1.  Before pushing jobs into queue!
![image](https://user-images.githubusercontent.com/99706987/172344831-8232608f-bbb2-4caa-a1a7-1910018b0755.png)
2.  During pushing jobs into the queue (Few queues are pushed from 10000)
![image](https://user-images.githubusercontent.com/99706987/172345586-d39b6f17-52c9-4b54-82ef-992087a20b72.png)
3.  Summary of heap snapshot before pushing jobs
![image](https://user-images.githubusercontent.com/99706987/172345819-ae959be1-fb65-486b-9449-51eeaaba3b43.png)
4.  Summary of heap snapshot after a few jobs have been pushed (worker started in the background)
![image](https://user-images.githubusercontent.com/99706987/172346411-cc87715f-f96c-4d2e-a57f-0f284199fd7c.png)
![image](https://user-images.githubusercontent.com/99706987/172346514-1cf56d62-6168-46e3-8c4b-230f2df2c8ec.png)

## Minimal, Working Test code to reproduce the issue.
I'm very well aware that this issue might be not reproducible at all but still, I'll share some minimal implementation so that it might make sense!

P.S. I'm not a very genius when it comes to memory debugging. Spent a few hours getting myself familiarized with the following stuff. In case heap snapshot is needed, I have it saved locally!

- Queue file
``` javascript
const Queue = require('bull')
const { importWorker } = require('../../workers')
const { addJobIntoQueue, executeWorkerWithLogs } = require('../../utils/queue.utils.js')
const { REDIS_URL } = process.env

const queue = new Queue(
  `import_something_from_somewhere`,
  {
    redis: REDIS_URL,
  },
)

queue.process(1, (job) =>
  executeWorkerWithLogs(job, importWorker.importSomethingFromSomewhere),
)

const schedule = async (data, options) =>
  await addJobIntoQueue(queue, { ...data, action: 'import' }, options)

module.exports = {
  schedule,
  queue,
}
```

- Import Worker
``` javascript
// ... some other queue's workers
const importSomethingFromSomewhere= async (job) => {
  const ProductService = require('../../services/product')
  const productService = new ProductService()
  // some business logic with await to make sure that no promises are missed
}
// some other queue's worker and module.exports
```

- Queue utils
``` javascript
// ... some other utils method
const addJobIntoQueue = async (queue, data, options = {}) => {
  const { jobId, module } = data
  if (!jobId || !module) throw Error('You must specify jobId and module to create a job')
  const jobModifiedName= 'modified and derived job name'
  if (jobIndex === '1') {
    io.emit(message.SOME_SOCKET_EVENT, { name: jobModifiedName})
  }
  delete options.totalJobs
  await queue.add(data, options)
}

const executeWorkerWithLogs = async (job, worker, isPermanent) => {
  try {
    await jobStarted(job, isPermanent) // in progress status - middleware hook to do something before executing worker logic (Bull's JOB will have active status)
    await worker(job)
    isPermanent ? await permanentJobCompleted(job) : await jobCompleted(job) // complete status - middleware hook to do something after executing worker logic - mimicking job complete (Bull's JOB will have active status)
    throw error // this will trigger Bull's job to be completed
  } catch (error) {
    isPermanent ? await permanentJobFailed(job, error) : await jobFailed(job, error) // fail status - middleware hook to do something on error - mimicking job failed (Bull's JOB will have active status)
    throw error // this will trigger Bull's job to be failed
  }
}
// some other queue's worker and module.exports
```

## Additional information
Everything might seem usual except the last `executeWorkerWithLogs`, The reason we have done can be justified by my previous issues. Issue number [2360](https://github.com/OptimalBits/bull/issues/2360) and [2358](https://github.com/OptimalBits/bull/issues/2358)

**Comment by manast** [comment]
The way to move forward with an issue like this is by providing an example code that clearly shows the memory is actually rising and that somebody else can also run with minimum effort. This example must be clean from all stuff that is not relevant to the test itself to eliminate external causes, and not like the example code you posted.
