### ISSUE TITLE
why is queue.close() too slow.. and why is it not empty?

### ISSUE THREAD

**Issue by snawaz** [OptimalBits/bull#2372]
`queue.close()` takes almost `0.5 secs` to complete and debugging further, I found that `line #1269` is being slow (inside `whenCurrentJobsFinished` which is being called by `.close()`).

https://github.com/OptimalBits/bull/blob/5649689531feef18956175e0db638592664279d3/lib/queue.js#L1265-L1270

I splitted the line to measure the time elapsed as follows:

```javascript
const t1 = new Date().getTime();
await Promise.all(this.processing);  
console.log("elapsed: ", (new Date().getTime() - t1)/1000);  // this reports almost 0.5 seconds!
return forcedReconnection;
```

Interestingly, my service does not add any job to the queue, yet `this.processing.length` is `4`. Why is it not  `0`?

I"m using `v3.22.0` but this code has not changed since then. Not sure if the other part of codebase makes this efficient in the recent version. I'm planning to use `bullmq` (`nestjs/bullmq`) instead. Just want to know if this slowness is known and acceptable?

**Comment by manast** [comment]
```Worker.close()``` by default waits for current active jobs to complete.  As for your specific case: isolate in the smallest possible case that you can write to reproduce the issue and we can look into it.

**Comment by snawaz** [comment]
> `Worker.close()` by default waits for current active jobs to complete. 

Yes. I have understood that myself. But the question is, why are there jobs to begin with?  I expect the queues to be empty, because I did not add any jobs to the queues. 

Also, what jobs are there? I tried to print `job` in `processJob()` and all of the jobs are `undefined` and returns immediately as `Promise.resolve()`. In that case, even if there are jobs which are `undefined`, and returns immediately, why is it taking `0.5s` then? That is so strange! 

> As for your specific case: isolate in the smallest possible case that you can write to reproduce the issue and we can look into it.

My backend is written in `nestjs` and it's huge. I can still try to write a small program to reproduce the issue.

**Comment by manast** [comment]
As mentioned, isolate in a minimal case, if it is a bug in Bull then we can look into it, otherwise, it may be due to your or nestjs specific code.

**Comment by snawaz** [comment]
> As mentioned, isolate in a minimal case, if it is a bug in Bull then we can look into it, otherwise, it may be due to your or nestjs specific code.

This code reproduces the `queue.close()` being too slow:

```javascript
const Queue = require('bull');

const time = () => new Date().getTime() / 1000;

async function closeBeingSlowIssue() {
  const videoQueue = new Queue('video transcoding', 'redis://127.0.0.1:6379');

  const t1 = time();

  await videoQueue.close();

  console.log("time elapsed: ", time() - t1); // logs almost 0.5s
}

closeBeingSlowIssue();
```

I have created this repo (https://github.com/snawaz/bull-close) which you can use to run it yourself.

**Comment by snawaz** [comment]
OK. Investigating further, I found that this is the code (from `redisClientDisconnect()`)  that takes too much than necessary when closing the queue:

https://github.com/OptimalBits/bull/blob/41ec58ef2233074fc1403d448270cd2122741fe1/lib/queue.js#L546-L553

Can we use smaller values than `500`? 

BTW, why this `0.5s` is a problem is because each test is a clean start and shutdown of the service. So if there are 15 queues only in my service, then each test will take `15 * 0.5 = 7.5s` to close the queues only, and then if there are 200 tests,  almost **25 mins** (`200 * 7.5 = 1500s`) would take to close the queues + running time of the tests. 200 tests are not many, so increasing the number of tests slows down the tests further.

For that reason, `.close()` needs to be quick.. ideally less than `0.05s` latency.

**Comment by manast** [comment]
This is the results I get when running your test above:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/95200/173278596-2ece4e87-b028-48bb-a369-c00d9ea4aab3.png">

Btw, we close the queues in every test for the bull test suite and we do not get this issue 🤔

**Comment by snawaz** [comment]
> These are the results I get when running your test above:  <...>
> 
> Btw, we close the queues in every test for the bull test suite and we do not get this issue 🤔

Thanks for sharing the results you get on your system. That's indeed interesting.

Could you please also try running the code **without** running _any_ Redis instance at all? I've tried both scenarios, with or without Redis instance. I get the same results.

**Comment by snawaz** [comment]
@manast 

> These are the results I get when running your test above:  <...>
> 
> Btw, we close the queues in every test for the bull test suite and we do not get this issue 🤔

Thanks for sharing the results you get on your system. That's indeed interesting.

Could you please also try running the code **without** running _any_ Redis instance at all? I've tried both scenarios, with or without Redis instance. I get the same results.

**Comment by manast** [comment]
If there is no instance at all then timing changes as the client will spend time timing out from a nonexisting redis hosst.

**Comment by snawaz** [comment]
> If there is no instance at all then timing changes as the client will spend time timing out from a nonexisting redis host.

That makes sense.

I further investigated. Now I found the issue. The code shared above isn't enough to reproduce the problem. Here is the change. The comment explains what exactly is happening and what causes the delay! 

<img width="957" alt="image" src="https://user-images.githubusercontent.com/1185906/173690501-7317f5f2-ebb8-4ddf-b4ff-dfe3552223ed.png">

See the commit: https://github.com/snawaz/bull-close/commit/d812f4cd846791764d302d400991f0e3f6da0403

Please note that the call `videoQueue.getNextJob()` does not necessarily have to make sense. But in the real scenario, at some point, `queue.bclient` will be initialized and `queue.bclientInitialized` will be `true`  and so on.

**Comment by snawaz** [comment]
I think one fix could be this..

replacing this pattern:

```javascript
//
// Force reconnection of blocking connection to abort blocking redis call immediately.
//
const forcedReconnection = redisClientDisconnect(this.bclient).then(() => {
   return this.bclient.connect();
});
```
with this pattern:

```javascript
void redisClientDisconnect(this.bclient); // no await here
this.bclient = <create-new-client-with-new-connection>;
```

I mean why do we need to wait for `redisClientDisconnect()` to complete before _reconnecting_ ? I guess that is why because we use the same client? What if we recreate the client itself? That at least will run the slow-step `redisClientDisconnect()` in the background. 

Please let me know your thoughts. If acceptable, I might create a PR for this. 🤔
