### ISSUE TITLE
Using AWS Elasticache Redis

### ISSUE THREAD

**Issue by jkevinturado** [OptimalBits/bull#2374]
Hi,

Do you support AWS Elasticache Redis?

I am using Bull 4.8.3 and BullMQ 1.85.3 for our NodeJS project, I was using a free redis database before. Now I'm using AWS Elasticache as our redis DB. But it seems they provide us a connection endpoint string meaning No username and password, and the default port is using 6379 and it is not working.

Here's the code for connection: 

```
const fileProcessQueue = new Queue('file', {
  connection: {
    host: '******************.vpce.amazonaws.com',
    port: 6379,
}
});
```

Any advice for using AWS Elasticache in Bull?

**Comment by manast** [comment]
What errors are you getting? you are aware you need to configure proper security groups in order to access your elasticache and that it is not possible to access it outside of aws?

**Comment by manast** [comment]
You can just try to connect using redis-cli first, if it does Bull will also connect.

**Comment by jkevinturado** [comment]
So we tried to connect to redis-cli unfortunately it says "Connection refused" no more further details are provided in the terminal, We will try to configure it in AWS.

![redis cli not connecting to aws](https://user-images.githubusercontent.com/42071552/173335409-ad11a0d7-a7cc-4975-99f8-62baf8f1c3b9.JPG)

But it does support AWS Elasticache,  right?

**Comment by manast** [comment]
> But it does support AWS Elasticache, right?

Sure, but you need to properly configure VPC and SGs, as with any app using elasticache in AWS.

**Comment by jkevinturado** [comment]
Hi, 

My app is now working we have done some configuration in AWS Elasticache. 

Thank you so much for the help

**Comment by yetanotherse** [comment]
@jkevinturado Could you please share the config changes you made in AWS elasticache. We too are unable to use it with bull queue.

**Comment by jkevinturado** [comment]
> @jkevinturado Could you please share the config changes you made in AWS elasticache. We too are unable to use it with bull queue.

Hi,

Sorry but I am not the in-charge in the configuration in AWS.

**Comment by McNidday** [comment]
> @jkevinturado Could you please share the config changes you made in AWS elasticache. We too are unable to use it with bull queue.

I know this might be comming in late, but i had to deal with the same issue for a whole 24 hours approximately changing security groups and whatnot, then i figured it out by accident. If you are using a direct url i.e 
`new Queue("SomeQueueName", "redis://127.0.0.1:6379")`
Then you might go ahead and initialize the same queue in elasticache environment like so. Assuming you already have your primary endpoint from your redis elasticache cluster:
`new Queue("SomeQueueName", "clustername.gr7c90.ng.0987.use2.cache.amazonaws.com:6379")`
Which will actually throw an error and fail to connect. To solve that issue go ahead and append "redis://" at the start of the endpoint, like so:
`new Queue("SomeQueueName", "redis://clustername.gr7c90.ng.0987.use2.cache.amazonaws.com:6379")`
I am not absolutely sure if it will work with a config object, but it worked out in url format. I hope you find this healpful, cheers 🍻

**Comment by han-code-4-fun** [comment]
@McNidday  I cannot believe this is my case. :sob:

**Comment by pranay-battu** [comment]
@McNidday , I am getting moved {hash} ip:port error, where I am trying to connect to redis cluster.

can you provide code snippet which works for redis cluster. I tried in many ways but it is not working at all.

**Comment by manast** [comment]
@pranay-battu are you following these instructions? https://docs.bullmq.io/bull/patterns/redis-cluster
Furthermore, I do recommend you do not create your elasticache in cluster mode, just one main and one replica is super reliable.

**Comment by pranay-battu** [comment]
@manast, yes created a prefix
tried these (example snippets)

method: 1
const Bull = require('bull');
const bullQueue = new Bull('queueA', {
  prefix: '{queueA}',
  redis: {
    host: process.env.REDIS_HOST,
    port: process.env.REDIS_PORT
  }
});


.........
giving error in cluster mode (error: MOVED hash ip:port) - 1 shard 2 nodes (1 master and 1 replica)
this is
method2:
const redisIoClient = new Redis.Cluster([
   {
       host: process.env.REDIS_HOST,
       port: process.env.REDIS_PORT
    }
])

const Bull = require('bull');
const bullQueue = new Bull('queueA', {
  prefix: '{queueA}',
  createClient: () => redisIoClient
});

this is crashing the application at start itself

**Comment by thegartrell** [comment]
I'm using AWS Elasticache 7.1 serverless with encryption. I spent a couple hours on this and wanted to save others the trouble since I couldn't find great documentation on this.

"ElastiCache Serverless is only accessible using Redis clients that support the Redis cluster mode protocol." ([AWS Docs](https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/wwe-troubleshooting.html#wwe-troubleshooting.connection))

So I ended up using the following setup in typescript:

```ts
import Queue from 'bull';
import { Cluster, RedisOptions, ClusterOptions, ClusterNode } from 'ioredis';

type MyJob = {
  whatever: string;
};

const clusterNodes: ClusterNode[] = [
  {
    host: process.env.REDIS_HOST,
    port: 6379,
  },
];

const clusterOptions: ClusterOptions = {
  redisOptions: {
    tls: {
      host: process.env.REDIS_HOST,
      port: 6379,
    },
  },
};

export const myQueue = new Queue<MyJob>('MyJobQueue', {
  createClient: function (_type: string, _redisOptions: RedisOptions) {
    return new Cluster(clusterNodes, clusterOptions);
  },
  prefix: '{my-queue}'
});
```

My `process.env.REDIS_HOST` is formatted like this: "clustername.w8at3v3r.ng.1234.use2.cache.amazonaws.com" with no "redis://" or "rediss://" at the beginning.
