### ISSUE TITLE
Missing process handler for job type JOB_NAME

### ISSUE THREAD

**Issue by vitor-l** [OptimalBits/bull#2377]
## Description
Hi, I'm having some trouble with NestJS + Bull. As mentioned here (https://github.com/nestjs/bull/issues/924#issuecomment-924748971), I'm opening the issue in this repository.

The context is: I have two microservices connected in a Docker network. One service adds the job to the queue and the other manipulates it. Every action on the first service generates a named job. So, in a specific scenario, the processor on the second service moves the job to failed, so it can be retried x amount of times (in my case x = 3).

The problem is: for some strange reason, a lot of time the job fails to retry because the process (in my case, 'new-job') couldn't be found, but sometimes if I try again, it works normally (the process is found and the job starts as a retry). Can someone help me? I have tried a lot of configurations for the root and queue, but none worked.

## Minimal, Working Test code to reproduce the issue.
``` typescript
    // Configs for first service
    BullModule.forRootAsync(BULL_ROOT_NAME_CONFIG, {
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => ({
        redis: {
          host: configService.get('integration.redisHost'),
          port: configService.get('integration.redisPort'),
        },
        defaultJobOptions: {
          attempts: configService.get('integration.redisMaxRetryTimes'),
          backoff: configService.get('integration.redisTimeout'),
        },
        settings: {
          lockDuration: 60000,
          maxStalledCount: 0,
        },
      }),
      inject: [ConfigService],
    }),
    
    BullModule.registerQueue({
      configKey: BULL_ROOT_NAME_CONFIG,
      name: BULL_QUEUE_NAME,
    }),

    // Adding the job to the queue
    export class SomeService {
        constructor(
        // ...other params
        @InjectQueue(BULL_QUEUE_NAME) private namedQueue: Queue,
        ) {}
    
        async someFunction(
        // ...some params
        ) {
            // ...some code
            this.namedQueue.add('new-job', {
                // ...jobData
            }),
        }
    }

    // Configs for the second service are exactly the same from the first service

    // Consuming the job
    @Processor(BULL_QUEUE_NAME)
    export class AnotherService {
      constructor(
        @InjectQueue(BULL_QUEUE_NAME) private namedQueue: Queue,
      ) {}
    
      @Process('new-job')
      async handleNewJob(job: Job) {
        // ...code to handle the consumed job
      }
    }
```

## Bull version
"@nestjs/bull": "^0.5.5"
"bull": "^4.8.3"

**Comment by lucassgomes** [comment]
Same issue here!

**Comment by vitor-l** [comment]
I've made some changes in the root configuration and maybe I found the problem. Now, my configuration looks like this:

``` typescript
BullModule.forRootAsync(BULL_ROOT_NAME_CONFIG, {
  imports: [ConfigModule],
  useFactory: async (configService: ConfigService) => ({
    redis: {
      host: configService.get('integration.redisHost'),
      port: configService.get('integration.redisPort'),
    },
    defaultJobOptions: {
      backoff: configService.get('integration.redisTimeout'),
      attempts: configService.get('integration.redisMaxRetryTimes'),
      removeOnComplete: true,
      removeOnFail: true,
    },
  }),
  inject: [ConfigService],
}),
```

I think that the problem is: when the job fails, It is consired both failed and completed. So, It is "removed twice". If I remove one of the options, It works fine.

**Comment by manast** [comment]
> a lot of time the job fails to retry because the process (in my case, 'new-job') couldn't be found, but sometimes if I try again, it works normally (the process is found and the job starts as a retry).

I do not understand what you mean by "couldn't be found".

Also I am not familiar to nestjs so if you are able to write a test case in plain js with Bull, I can look deeper into it.

**Comment by vitor-l** [comment]
@manast, "couldn't be found" is literally the error. Basically, if I have manipulations that only happen on completed jobs, they will also happen on failed jobs. For example, if I want to remove jobs that have been moved to completed status, automatically when a job fails, it will be removed, because it is considered a completed job.

In my opinion, failed jobs should not be considered completed or Bull should have another status, like "successful" or something like that

**Comment by manast** [comment]
Failed jobs are not considered completed. I still do not grasp what is the issue here, the best is if you could provide a test case in plain Bull code so we can look into it.
