### ISSUE TITLE
Global listeners trigger on all service instances/pods 

### ISSUE THREAD

**Issue by PetrShchukin** [OptimalBits/bull#2378]
We use micro-service architecture and have our services on k8s. There's some issues with global listeners. For example, let's say there's a service A with 10 pods and there's a request that puts a job into a queue. Service B has 10 pods as well and waiting for a job to pick up. Thanks to the job lock because only one pod picks it up. Now when the job on the service B is finished we want to add data in a DB via service A. In the service A we use a global listener onComplete. But the problem that all 10 pods got that event and starting executing their code at the same time. 

I understand that this is an "expected" behavior, as emitting an event has nothing to do with locking a job, but in that case it means that global events is not going to work at all in this architecture. What I can think of is to create another job from service B "onJobComplete" which is going to be picked up by the service A, but it doesn't look as a proper way of doing it. Is there's any suggestions?

**Comment by manast** [comment]
Yes, the proper way to do it is to use a different queue for sending "onJobComplete" messages to another service, that is the most robust way to implement an scenario like this.

**Comment by manast** [comment]
In fact it is mentioned in the patterns section: https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#returning-job-completions

**Comment by PetrShchukin** [comment]
Makes sense, thanks!
