### ISSUE TITLE
Add support for keeping only a given number of completed or failed tasks.

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#24]
To save memory, it should be possible to restrict the max number of saved completed or failed jobs in Redis.
This can be easily achieved using ZSET with a timestamp instead of standard SETS. As long as all the clocks of the queue instances are more or less synchronized everything should work fine.

**Comment by haganbt** [comment]
Thanks very much for implementing, really useful.

**Comment by seriousben** [comment]
:+1:

**Comment by seriousben** [comment]
Can we put this back on the priority, to have a configurable max number of completed/failed jobs to keep?

**Comment by manast** [comment]
I think that the way to do this is implementing a circular list one for completed and one for failed, so that everytime a job is completed or failed it is added to the circular list and at the same time the job getting out of the list is removed from the completed or failed set.

**Comment by manast** [comment]
Will close. This can be implemented at the client side.
