### ISSUE TITLE
Implement MULTI operations as LUA scripts.

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#240]
In order to create atomic operations we are using the MULTI command. The problem is that this command requires a roundtrip to the redis server for every command as well as for the MULTI and EXEC commands. This increases the latency by a factor of at least 4x and 1x for every extra command. By using a precached LUA script we can perform the same atomic operation much faster.

**Comment by manast** [comment]
fixed in https://github.com/OptimalBits/bull/tree/v1.0.0-rc

**Comment by joe-at-startupmedia** [comment]
Is there any docs on how to implement/configure this?

**Comment by manast** [comment]
@joe-at-startupmedia how do you mean? this is an internal improvement in bull, nothing that end users needs to configure.

**Comment by joe-at-startupmedia** [comment]
I recently opened a new issue that is related to this inquiry. The utilization of native multi/exec commands are not supported in the redis clustering middleware I am using so I need a way of bypassing that functionality.

**Comment by manast** [comment]
i.e. the ```saveAttempt``` needs to be performed in every one of the "move" scripts used in moveToFinished.

**Comment by joe-at-startupmedia** [comment]
I hear you that the need to override native multi/exec support is less common and that it would take lower priority over other issues. This is the output result of where the multi/exec calls are made and subsequently fail due to lack of support.
```
  ioredis:redis queue command[0] -> multi() +12ms
  ioredis:redis queue command[0] -> llen(bull:subscriptionStaticUrls:wait) +2ms
  ioredis:redis queue command[0] -> llen(bull:subscriptionStaticUrls:active) +0ms
  ioredis:redis queue command[0] -> zcard(bull:subscriptionStaticUrls:completed) +0ms
  ioredis:redis queue command[0] -> zcard(bull:subscriptionStaticUrls:failed) +0ms
  ioredis:redis queue command[0] -> zcard(bull:subscriptionStaticUrls:delayed) +1ms
  ioredis:redis queue command[0] -> exec() +0ms
  ioredis:redis status[159.203.151.158:22122]: connecting -> connect +13ms
```

Changing:

```
Queue.prototype.multi = function(){
  return this.client.multi({});
};
```

To

```
Queue.prototype.multi = function(){
  return this.client.multi({ pipeline: true });
};
```

Does *not* seem to resolve the issue. I got `pipeline true` from the following:

https://github.com/luin/ioredis/blob/master/lib/transaction.js#L21

**Comment by joe-at-startupmedia** [comment]
I was able to resolve the exact issue in another library by using the node_redis client `batch` function. https://github.com/arjunmehta/node-georedis/issues/4

**Comment by joe-at-startupmedia** [comment]
It appears this application is using pub/sub which is also unsupported by Twemproxy so at this point there is no need to look into this issue any further for my use case. Thanks for the response nonetheless.
