### ISSUE TITLE
KeepJob Options (age) not working as expected

### ISSUE THREAD

**Issue by JoJ123** [OptimalBits/bull#2401]
## Description
KeepJob Options not working as expected. Job is not removed from the system after X seconds.
When you add another Job with a different ID, the "old" Job get's removed.

## Minimal, Working Test code to reproduce the issue.
```typescript
import Bull from "bull";

const myFirstQueue = new Bull('test-age');

myFirstQueue.process(async (job) => {
    console.log('Process Job', job.id);
});

myFirstQueue.on('completed', async (job) => {
    console.log('Completed Job', job.id);
});

async function test() {
    const job = await myFirstQueue.add({
        foo: 'bar'
    }, {
        removeOnFail: { age: 5 },
        removeOnComplete: { age: 5 },
        jobId: 1,
    });
    console.log('Added Job', job.id);
}

test();
```
#### (An easy to reproduce test case will dramatically decrease the resolution time.)
In my Redis Keys, I still see the Job with the ID 1 even after 1 minute.
![image](https://user-images.githubusercontent.com/38938791/179500722-f330d398-40c9-4f9f-8245-d2ee60b09f93.png)
After adding a Job with a different ID, the previous one will be removed:
![image](https://user-images.githubusercontent.com/38938791/179501023-e597adc3-a7d1-463e-a80f-2173850ddb38.png)

## Bull version
4.8.4

**Comment by manast** [comment]
The jobs are removed lazily as new jobs are completed/failed. The same way as Redis implements the EXPIRE command btw... so this works as designed.

**Comment by manast** [comment]
A job is not only in one key, it is also tracked in the completed/failed set.

**Comment by stouch** [comment]
> The jobs are removed lazily as new jobs are completed/failed. The same way as Redis implements the EXPIRE command btw... so this works as designed.

So if I have a job "A", with a `removeOnComplete: { age: 5 }`, and 10 seconds later I want to check it is well deleted so I do `myFirstQueue.find( "A" )` well this is going to return true... While I was expecting to be false. 
So I can't create a new job "A" even 10 or 1 hour later, just because Redis is lazy ?

**Comment by manast** [comment]
I do not think it is a good practice to rely on the auto job removal functionality to schedule jobs, why not use the "delay" functionality instead?
