### ISSUE TITLE
Cannot connect to remote redis url

### ISSUE THREAD

**Issue by bingomanatee** [OptimalBits/bull#2402]
## Cannot connect to remote redis instance

I am using BullModule in nest.js. 

when I connect to a local redis it works:

    const REDIS = {
      host: 'localhost', 
    };

    @Module({
      imports: [
        TaskTypesModule,
        TasksModule,
        ScheduleModule.forRoot(),
        BullModule.forRoot({
          // @ts-ignore
          redis: REDIS,
        }),
      ],
      controllers: [AppController],
      providers: [AppService, PrismaService],
    })
    export class AppModule {}

But when I connect to a remote system 

    const REDIS = {
      host: process.env.REDIS_ENDPOINT,
      port: process.env.REDIS_PORT,
      password: process.env.REDIS_PASSWORD,
    };

with env file

    REDIS_USERNAME=default
    REDIS_PASSWORD=p----------------------S
    REDIS_ENDPOINT=redis-1xxxxx4.c261.us-east-1-4.ec2.cloud.redislabs.com
    REDIS_PORT=1xxxxx4

it doesn't write to the redis queue; 

So - bottom line - how to configure the redis node for a remote connection in Bull? what is the proper way to format a remote redis URL?

## Bull version

    "@nestjs/bull": "^0.6.0",
    "bull": "^4.8.4",

## Additional information

by way of comparison, I can connect via redisight:

 ! [1](https://i.stack.imgur.com/VYuvU.png)

**Comment by manast** [comment]
Seems like this is a NestJS related issue, please check in their issues if something similar is asked there. I am sure this is just some small configuration error.
