### ISSUE TITLE
jobId same name  Different  add queue

### ISSUE THREAD

**Issue by ValueLan** [OptimalBits/bull#2404]
## Minimal, Working Test code to reproduce the issue.
`
queue.add('nameAAA', {  }, {
        removeOnComplete: true,
        removeOnFail: true,
        jobId: 1
      });

queue.add('nameBBB', {  }, {
        removeOnComplete: true,
        removeOnFail: true,
        jobId: 1
});  // I hope different names should be added success, But add fail. I can give jobId add pre, But it's too much trouble
`

**Comment by manast** [comment]
What is the issue exactly?

**Comment by ValueLan** [comment]
Queue add same jobId but different name , only add a job.
Name like db table name ,  Id like db table id.
Different table add same jobId should add tow jobs.

**Comment by manast** [comment]
By design jobs with the same Id as existing jobs in the queue are ignored.

**Comment by ValueLan** [comment]
The function feels better if you use name + jobId to distinguish tasks.
