### ISSUE TITLE
Job is immediately moved from Active to Waiting on Development Server only

### ISSUE THREAD

**Issue by selected-pixel-jameson** [OptimalBits/bull#2407]
## Description
I have a queue that I'm sending a job to. The job works fine on my local servers, but when I try to run it in my development environment the job immediately goes from Active to Waiting. The progress continues to update while waiting, but ultimately once it finishes it just is flagged as failed.

This is my code.

**Workers.js**
```

const { Sema } = require('async-sema')
const s = new Sema(500, { capacity: 500000 })

const pgIssueIndexQueue = new Queue('pgIssueIndexQueue', { redis: config.jobsRedis })
pgIssueIndexQueue.process('pg-issue-index', 1, async (job) => {
  return SearchIndexService.reindexIssues(null, null, job)
})

```

**SearchIndexService.reindexIssues**
```
module.exports.reindexIssues = async (id, issues, job) => {
  issues = issues || (await queries.issues.issueIndex(id))  //  ~200,000 records come back here

  let count = 0
  let percentage = 0

  const promises = issues.map(async issue => {
    await s.acquire()
    try {
      percentage = Math.round((count / issues.length) * 100)
      if (job) {
        job.progress(percentage)
      }
      count++

      return await this.updateELSIndex(issue.id)
    } catch (error) {
      console.log('ERROR', error)
    } finally {
      s.release()
    }
  })
  return await Promise.all(promises)
}

```

## Bull version
4.5.4

## Additional information
I'm using @bull-board/express for a front-end UI. Which is where I see the job being transitioned from active to waiting.

**Comment by selected-pixel-jameson** [comment]
If I add  `settings: { stalledInterval: 0, maxStalledCount: 0 } }` when creating the queue this problem does not seem to arise. 

```
const pgIssueIndexQueue = new Queue('pgIssueIndexQueue', { redis: config.jobsRedis, settings: { stalledInterval: 0, maxStalledCount: 0 } })
```

**Comment by manast** [comment]
From what you write it seems like the jobs are being stalled and moved back to wait. For a job to stall, by default, it must process for at least 30 seconds and not manage to renew the job lock. So either you are changing the default settings (you most likely wont need to do it), or your jobs run longer than 30 seconds and are VERY CPU intensive so that the workers cannot renew the locks.

**Comment by romick101** [comment]
Seems like I got this error reproduced too with sandbox processors and repeated jobs on bull 4.8.2.
If I create the queue with empty settings, add repeated job to it and promote the job from the dashboard the job goes to `waiting` and console.log in the processor is not called. 
Queue creation: 
```
    console.log(queueName, this.queueOptions.settings)    // daily-forecast-refresh-queue {}
    const queue = new Bull(queueName, this.queueOptions)
    
    console.log(jobName, processorPath) // daily-forecast-refresh /usr/src/app/src/domains/meteoFarm/meteoFarmQueue/processors/dailyForecast.processor.js
    queue.process(jobName, processorPath)
```
Adding job: 
```
    this.queue.add(jobName, job, {
      repeat: { cron: '*/4 * * * *' },
    })
```
![image](https://user-images.githubusercontent.com/11228060/185482724-c9acdce9-6ef1-4517-8b88-bae10d4d41a2.png)

If I add `settings: { stalledInterval: 0, maxStalledCount: 0 } }` however the job goes to `active` and creates another repeat as intended. 
This only happens on aws instance, on my laptop with both settings job is processed normally. Both environments have everything running in docker. 


Once while restarting the app I managed to get the consumer called with empty setting and the job was progressing while remaining in `waiting` tab, however I was not able to reproduce this again. 

![Screenshot 2022-08-18 at 22 27 46](https://user-images.githubusercontent.com/11228060/185478273-3b5111fd-75b9-4413-9031-748d3febe627.png)

**Comment by selected-pixel-jameson** [comment]
I ended up having to increase the instance and parse the larger job out into much smaller jobs. There are instances where the "smaller" jobs are still pretty long and this same thing will happen still in that case.

**Comment by selected-pixel-jameson** [comment]
> From what you write it seems like the jobs are being stalled and moved back to wait. For a job to stall, by default, it must process for at least 30 seconds and not manage to renew the job lock. So either you are changing the default settings (you most likely wont need to do it), or your jobs run longer than 30 seconds and are VERY CPU intensive so that the workers cannot renew the locks.

I'm still running into this issue on my development environment. I have no made any changes to the defaults. I've changed the instance size to a 8 vCPU's and 32GB memory and the CPU is not going higher then 10% at any point.  I've also tried to batch the process into smaller jobs on different queues as much as possible. 

Any other possible suggestions?

**Comment by manast** [comment]
If you can produce a test that shows this behaviour I could look into it in more detail.
