### ISSUE TITLE
React/NextJS : Error: Error initializing Lua scripts

### ISSUE THREAD

**Issue by DemonFangs** [OptimalBits/bull#2409]
Trying to compile by nextjs app, but keep getting this lua error. 
```
Error: Error initializing Lua scripts
    at eval (webpack-internal:///(api)/../apps/node_modules/bull/lib/queue.js:158:30)
```
 I would prefer not to add any webpack config as that would lead to a path of thorns later on

### Additional Info
I'm using the default redis package and not the ioredis one as shown in all the examples. Would that be an issue? Can I not just pass an existing redis instance like `RedisClient`/`Commander` to bull for it to work?

**Comment by manast** [comment]
You will need to add a step to copy the lua scripts from Bull to the target directory.

**Comment by DemonFangs** [comment]
Could you elaborate a little on where the Lua files are and what you mean by target directory?

**Comment by manast** [comment]
When you start bull it must be able to find these lua files: https://github.com/OptimalBits/bull/tree/develop/lib/commands
So if you are using a compiler/bundler as webpack you need to make sure it copies it to the correct place, whatever it may be in your build.
