### ISSUE TITLE
How many times is a job retried based on the attempts we declare when adding a job in queue?

### ISSUE THREAD

**Issue by sanyaldips93** [OptimalBits/bull#2419]
Hi

I have experimenting with the 'attempts' option while adding a job to a queue for sometime now. As per my understanding from bull documentation, the job is retried as many times as declared while adding after it has failed. So when we declare attempts : 3, the job should be tried 1+3(fresh attempts + reattempts) times if we consider it has been failing all the time.

BullMQ documentation : https://docs.bullmq.io/guide/retrying-failing-jobs
However, in the bull docs it says something different : https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd

Could you please clarify how many times will a job get retried if attempt is 'n' ? and will those attempts include the fresh attempt as well?

**Comment by manast** [comment]
I am confused, what is the issue exactly? Did it not work as stated in the documentation?

**Comment by sanyaldips93** [comment]
@manast The two documentations suggest quite the opposite idea. I wanted to understand and confirm if the number of attempts would include the fresh attempt and the attempts post failure as well?

For example : if the number of attempts were defined 3, would that indicate 1 fresh attempt and 2 retry attempts?

**Comment by bugs181** [comment]
It's all in the wording. "retry" for example does not count the first because the first is actually the job. The docs are also very specific about WHEN to "retry".

> When a processor throws an exception, the worker will catch it and move the job to the failed set. But sometimes, it may be desirable to retry a failed job.

This means, the job is "retried" WHEN the job throws an exception. When a job fails, the job is moved into the failed set and "retried" up to `n` times.
