### ISSUE TITLE
How to limit concurrent workers count?

### ISSUE THREAD

**Issue by iBat** [OptimalBits/bull#242]
I have long job queue (1000+). But I want to have only 1 (or any other number of my choice) concurrent worker for this queue (workers returns Promises). I figured that I needed the first argument Queue##process for this. But it seems that this has no effect. As before, start a large number of processes.

**Comment by manast** [comment]
can you paste an example process function here that exhibits the behaviour you mentioned?

**Comment by namlook** [comment]
I suppose @iBat wants something like this: https://github.com/Automattic/kue#processing-concurrency

**Comment by iBat** [comment]
That's my fault. I made funny error in process function
`queue.process(1, job => {
    return updatePlayers(job.data.id, server).then(.....).fail(....);
});`
Yes `fail` instead of `catch` (damn jQuery habit). Because of this updatePlayers process starts and right after this process function throws an error and new job starts. Btw `.on('failed', ...)` event not emits in this case.
Sorry for disturb.
