### ISSUE TITLE
For a job running for hours long, after the job is completed, queue continues to show process status: in progress.

### ISSUE THREAD

**Issue by Meraj-Kazi** [OptimalBits/bull#2420]
## Description

I'm using  @nestjs/bull package. My total backend is built with NestJS.

For a job running for hours long, after the job is completed, queue continues to show process status: in prpgress. It doesn't happen for short time process. During the process, we only pull data from various sources. Sometime we pull data for last 15 days, sometimes last 15 months. The problem occurs during long period. The job runs for almost 8-9 hours and then instead of completing, it restarts pulling data from the start_date. I checked the job progress status, it remains in "in progress".

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

In `something.service.ts` file, queue is used like this,

```
.
.
.
constructor(
...
    @InjectQueue('some-queue')
    private queue: Queue,
  ) {}
.
.
.
public async someData(someDto: SomeDto): Promise<any> {
}
const job = await this.queue.add(
      'some-data-fetch',
      {
        monthsArray,
        clientId,
        reportId: ID,
      },
      { removeOnComplete: true },
    );

return {
      status: HttpStatus.OK,
      message: `${return_message}, ID: ${ID}`,
    };

```

In `something.consumer.ts` file, I kept it like this,

```
.
.
.
@Processor('some-queue')
.
.
.
@Process('some-data-fetch')
async someDataFetch(job: Job<unknown>) {

// We fetch some data for a given timeline 
.
.
.
// We process the data and create csv 
.
.
.
// We upload the csv and generate url and save it in database 

}


```

## Bull version
"bull": "^4.8.3",

**Comment by manast** [comment]
The information you provide is not sufficient to reproduce the issue nor to make any analysis. Try to add more logging to the workers so that you can get an idea what is going on with this long running job, if it breaks, why and where.

**Comment by Meraj-Kazi** [comment]
@manast  
Another thing I need to know, will there be problem if my background task needs several hours to complete? In my case, 
My consumer gets a timeline and fetch data within that timeline from different sources. 

If I give a time line of 2 months/6 months, there's usually no problem. the data are stored in a csv in the end, and it usually remains under 10 mb in size. But if I give a timeline of 12 months or more, final csv size becomes almost 15-20 mb depending on the data sources. It takes almost 2-3 hours to pull 12 months of data usually. BUT then the consumer never stops. the timeline is split into months, so after itearting through the monthsArray, it starts again instead of the process getting completed. 

Is there any issue with the lockDuration? 
What's the best practice for background process which takes several hours to complete?

**Comment by manast** [comment]
The best is to break down long jobs into smaller ones, so if the job fails you keep the job done already.

**Comment by bugs181** [comment]
> @manast Another thing I need to know, will there be problem if my background task needs several hours to complete? 

I can tell you from my experience of working with Bull for 2+ years, I have jobs that run several hours long up to weeks long and have never had an issue. The time it takes for a job to complete or fail is of no importance to Bull.

As others have suggested, add some logging to your worker to get an idea of what's going on under the hood. To implement this just use `job.log(message)`. I personally set up Event hooks inside the `.process()` functiion like so:

```js
someQueue.process(function(job, done) {
  EventHandler.on('log', (message) => job.log(message))`
})
```
