### ISSUE TITLE
No way to look up repeating job by id

### ISSUE THREAD

**Issue by kibertoad** [OptimalBits/bull#2437]
## Description

Currently system generates job ids for repeatable jobs using this algorithm:
```
  function getRepeatJobId(name, jobId, nextMillis, namespace) {
    return 'repeat:' + md5(name + jobId + namespace) + ':' + nextMillis;
  }
```

This makes it rather difficult to find this job later on.

## Minimal, Working Test code to reproduce the issue.

```js
const queue = Bull('testQueue2', { redis: redisOptions })

// this will not work correctly
// actual id will be something like "repeat:5e9c2508887181084e10fa8906336314:1664744571000"
const existingJob = await queue.getJob('recurring-job-id')
if (existingJob) {
  return
}

queue.add('job name', {}, {
  repeat: { every: 500 },            
  jobId: 'recurring-job-id', // wish I could find job by this later
})
```

## Bull version
4.10.0

## Additional information

I realize that jobId needs to be unique for Bull to work, which is why it's autogenerated. It would be great, however, to be able to look up jobs using a combination of non-unique constant identifier and (optional) status. Then it would be possible to find active instance of a specific repeatable job. API suggestion:

```js
const queue = Bull('testQueue2', { redis: redisOptions })

// this should work correctly as referenceId will be preserved across multiple instances of a recurring job
const existingJob = await queue.getJobByReferenceId({referenceId: 'recurring-job-reference-id', statuses: ['active']})
if (existingJob) {
  return
}

queue.add('job name', {}, {
  repeat: { every: 500 },            
  jobId: 'whatever', // it will be overriden anyway, we don't care
  referenceId: 'recurring-job-reference-id'
})
```

**Comment by kibertoad** [comment]
@manast If you approve this proposal, I can work on a PR for this improvement.

**Comment by kibertoad** [comment]
@manast Sorry for pinging you again, but this is a blocking thing for us. Would be great to get your comment on whether such PR would be accepted, to avoid wasting effort.

**Comment by manast** [comment]
If I understand this correctly, what you want is to get the last iteration of the repeatable job right?

**Comment by kibertoad** [comment]
@manast Yup!
