### ISSUE TITLE
Can't set delay to greater than 24 days

### ISSUE THREAD

**Issue by laoshanlung** [OptimalBits/bull#244]
It seems that when you set the delay to more than 24 days, the job gets executed immediately. 

I take a look at the test https://github.com/OptimalBits/bull/blob/master/test/test_queue.js#L869, and change delay to `24*30*3600*1000` (30 days), the test still passes immediately which is weird

Btw, the expect statement seems to be wrong (I am not sure, but I think it should be `expect().to.be(true)`)

**Comment by manast** [comment]
@laoshanlung will need to take a look into it.
