### ISSUE TITLE
Unexpected behavior when creating queue with same name

### ISSUE THREAD

**Issue by trsh** [OptimalBits/bull#2442]
## Description

As I understood from previous discussions, when you use same name for queue, `new Bull` should pick up an existing queue from Redis. However it rather creates parallel one and executes jobs inside in parallel in a weird manner. 

I think this is very crucial to work properly, as keeping separate register to store pointers to queues in memory is not a good solution (server restarts, etc.)

## Minimal, Working Test code to reproduce the issue.
```typescript
import Bull, { Job } from 'bull';
import Redis from 'ioredis';
import { JobOptions } from 'bull';
import { Redis as RedisType } from 'ioredis';

const REDIS_URL = "redis://localhost:6379";

export const defaultJobOptions: JobOptions = {
    attempts: 1,
    priority: 1,
    timeout: 15000,
    removeOnComplete: true,
    removeOnFail: true,
};

var client: RedisType;
var subscriber: RedisType;

function init() {
    client = new Redis(REDIS_URL);
    subscriber = new Redis(REDIS_URL, {
        maxRetriesPerRequest: null,
        enableReadyCheck: false,
    });
}


async function someJob() {
    var t = Date.now();
    console.warn(t, 1);
    await new Promise(r => setTimeout(r, 2000));
    console.warn(t, 2);
    return null;
}

function createQueue(name: string): Bull.Queue {
    const redisUrl = REDIS_URL;

    const queue = new Bull(name, {
        createClient(type) {
            switch (type) {
                case 'client':
                    return client;
                case 'subscriber':
                    return subscriber;
                default:
                    return new Redis(redisUrl, {
                        maxRetriesPerRequest: null,
                        enableReadyCheck: false,
                    });
            }
        }
    });

    queue.process('process', 1, async (job: Job<any>) => {
        await job.progress(0);

        let esResult: any = undefined;

        try {
            esResult = await someJob();
        } catch (err: any) {
            console.error(err);
        }

        console.warn("Process complete");
        await job.progress(100);
        return Promise.resolve(esResult);
    });

    queue.on('completed', function (job: Job<any>, _result) {
        console.warn("Process complete event");
    });

    return queue;
}



async function runAll() {
    init();
    createQueue("superQueue_1");
    const q = createQueue("superQueue_1");
    await q.add('process', {}, defaultJobOptions);
    await q.add('process', {}, defaultJobOptions);
}

runAll();
```

### Expected results:

1665417494777 1
1665417494777 2
Process complete
Process complete event
1665417496793 1
1665417496793 2
Process complete
Process complete event

### Actual results:

1665416995463 1
1665416995464 1
1665416995463 2
Process complete
1665416995464 2
Process complete
Process complete event
Process complete even

## Bull version

4.10.0

## Additional information

Nope

**Comment by manast** [comment]
You are getting the correct results. In your code you create 2 instances of the Queue with a process function defined, therefore you will have 2 workers and they will consume in parallel. Instantiate only one and it will only process max one job in parallel.

**Comment by trsh** [comment]
> You are getting the correct results. In your code you create 2 instances of the Queue with a process function defined, therefore you will have 2 workers and they will consume in parallel. Instantiate only one and it will only process max one job in parallel.

I am aware that I created 2 instances of queue with same name. That was on purpose to highlight the issue/problem. Because as I mentioned in description, the pointer to the queue instance can get lost (node instance restarted, logic issues, etc.). And then to pickup one the same queue all I have, is it's name. But when I do, the parallel thing starts.

**Comment by trsh** [comment]
Or its like?:

```
const queue = new Bull(lostQueueName);
if(!queue.processDefined){
   // only then add .process
}
```

but I see no such option.

**Comment by manast** [comment]
I really do not understand your issue. You instantiate a queue by its queue name, then you define the process function and concurrency that's all. If the service restarts the queue will continue processing jobs from that queue, etc.

**Comment by trsh** [comment]
> I really do not understand your issue. You instantiate a queue by its queue name, then you define the process function and concurrency that's all. If the service restarts the queue will continue processing jobs from that queue, etc.

In ideal world yes. You keep perfect track of created queues. Store them in memory for access and checking if one by name already exists. Never create same. When service restarts wiped, you recreate the queues on bootup, store again to continue your processing. 

But when you work in a team, and the project is large scale and you have this function `createQueue(name)`, it can mistakenly called twice or more with same name (like in the example), because simply wicked logic that doesn't do needed checks or/and there is other wicked logic that wipes the memory with queue instances. And then everything goes bananas.

All I would need is something like:

```
const queue = new Bull(lostQueueName, ...);
if(!queue.processDefined || hasWroker){
   // only then add .process etc
}else{
  // do nothing, just use this queue, it has already worker etc attached
}
```

**Comment by trsh** [comment]
Tho I probably missed this [``](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queuegetworkers.
Maybe it will do. Will check tomorrow.

**Comment by manast** [comment]
> In ideal world yes. You keep perfect track of created queues. Store them in memory for access and checking if one by name already exists. Never create same. When service restarts wiped, you recreate the queues on bootup, store again to continue your processing.

Either you are overcomplicating things or you may not understand what this library offers. This is a distributed queue system, the most standard use case is to have dozens of workers, with maybe thousands of jobs processing in parallel.
I think you may have a completely different set of expectations regarding what this library offers, and I am really struggling to understand what you want to accomplish and your issue. Please understand this library is used by thousands of companies in production every day; there is no fundamental design issue or anything like that as you seem to imply, please try to make an effort to understand what the library provides, and if it does not suit your use case please move along.
