### ISSUE TITLE
[Question] Is there a way to auto-scale a a redis Cluster vertically when all a traffic is coming from a single queue ? 

### ISSUE THREAD

**Issue by dani-sandu** [OptimalBits/bull#2443]
Hello ,
I'm using bull in an application that has multiple queues , every queue has a rate limit that is pretty low. ( 80-120 jobs per second)
At the moment as a redis solution I'm using an ElasticCache cluster enabled on aws . For each queue I spawned a shard and I made sure that the keyslot for every queue hashtag is landing on the assigned shard . 
In order to use resources more efficiently and adapt the infrastructure to the traffic I'm getting , I want to define an auto-scaling policy that would spawn more shards when needed . 
The only problem that I have is if all the traffic comes on a single queue , because of the hashtag the queue is going to use a single shard , even if the auto-scaling policy would spawn more , and eventually because of the rate limit it could run out of memory . 
**Do you know of an existent workout for this situation ?**
I was thinking about creating dynamic queues when the number of waiting jobs is above a certain limit , or just create some queues that would just store the jobs if the number of waiting jobs in the main queue is above a threshold, then move them back in the main queue . 
Thank you !

**Comment by manast** [comment]
If you have a single queue, then having a cluster is of no benefit, instead, you can run with a single instance + a failover instance for availability. Enable removeOnComplete/Failed with sensible settings, so that you only keep a relatively low number of jobs after they are completed. You can set monitors for memory usage in Elasticache if I am not mistaken, and you can increase memory if needed. I think the largest instance is something like 300+Gb RAM, so it should not be a problem :)

**Comment by dani-sandu** [comment]
Hello ,
I'm already using removeOnComplete and I have over 15 queues at the moment , And the scenario I mentioned above could happen to any of the queues, it's happening for jobs with waiting status , the workers could process only 80-120 jobs per seconds because of the rate limit, and there could be thousands of jobs piling in in per seconds in a queue ,  so the shard could run out of memory . 
I have alerting systems in place . But I want to create a solution that would react to the load without too much intervention . 
I wanted to check with you guys if there are any fancy solution to handle this case , or any workaround that I'm missing . 
But I guess routing the jobs to "storage queues" when the number of waiting jobs in a queue is above a threshold  would be the way to go. 
Thank you so much for your response ! 😄
