### ISSUE TITLE
Sandboxed Process is not Respecting Concurrency Value

### ISSUE THREAD

**Issue by selected-pixel-jameson** [OptimalBits/bull#2446]
## Description

When using a sandboxed process it appears as if the concurrency is not being respected. 

```
const fullImportWorker = path.resolve(__dirname, 'bulkImportSeries.js')
fullImportSeriesQueue.process('bulk-import-series', 1, fullImportWorker)
```

This is the only place I'm referencing `fullImportSeriesQueue.process` and I'm setting the concurrency to 1. But when I pass in multiple jobs they all immediately become active.  Reiterating the fact that I understand that the concurrency of named jobs stacks. 

bulkImportSEries.js
```
module.exports = async (job) => {
  return dummyTest()
}

async function dummyTest () {
  await delay(10000)
  return 'OK'
}

function delay (waitTime) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(true)
    }, waitTime)
  })
}

```

## Bull version
4.10.0

**Comment by manast** [comment]
Why don't you write a much simpler test, like a dummy processor that waits 3 seconds, and see if it really processes more than 1 in parallel? If you can show that is the case we can look deeper into it.

**Comment by selected-pixel-jameson** [comment]
@manast  Ok. Thank you. I updated my initial request.

**Comment by selected-pixel-jameson** [comment]
@manast I resolve this issue. I was referencing my file that actually instantiated all of the workers within the sandboxed file.
`const Workers = require('.')`

So every request was creating all new processes, thus adding on to the concurrency count because the job is named. 

😮‍💨. Sorry for wasting your time.
