### ISSUE TITLE
queue.close throws timeout error

### ISSUE THREAD

**Issue by ranshemt** [OptimalBits/bull#2448]
## Description

calling queue.close throws timeout error.
I was able to debug and identify `await queue.close()` as the source of the issue.

here is a callstack it it helps.

**<anonymous> (/usr/src/app/node_modules/bull/lib/queue.js:539)
redisClientDisconnect (/usr/src/app/node_modules/bull/lib/queue.js:533)
Object.<anonymous>.Queue.whenCurrentJobsFinished (/usr/src/app/node_modules/bull/lib/queue.js:1319)
<anonymous> (/usr/src/app/node_modules/bull/lib/queue.js:854)
processTicksAndRejections (<node_internals>/internal/process/task_queues.js:95)
Promise.then (Unknown Source:0)
Object.<anonymous>.Queue.pause (/usr/src/app/node_modules/bull/lib/queue.js:832)
<anonymous> (/usr/src/app/node_modules/bull/lib/queue.js:579)
processTicksAndRejections (<node_internals>/internal/process/task_queues.js:95)
Promise.then (Unknown Source:0)
Object.<anonymous>.Queue.close (/usr/src/app/node_modules/bull/lib/queue.js:579)
releaseApp (/home/XX/XXX/XX/XX/test/utils.ts:52)**

the log:

 console.error
    TimeoutError: Promise timed out after 500 milliseconds
        at Timeout._onTimeout (/usr/src/app/node_modules/bull/lib/p-timeout.js:56:50)
        at listOnTimeout (internal/timers.js:557:17)
        at processTimers (internal/timers.js:500:7)

## Bull version
4.6.1

is this a known issue? not sure how can I provide an example to because it happens regardless of where in the code I call this.

**Comment by manast** [comment]
Do you have a test snippet that reproduces the issue?

**Comment by ranshemt** [comment]
> Do you have a test snippet that reproduces the issue?

no matter where in the code and how I write it, simply writing `await queue.close()` will cause this issue. Might be worth mentioning I'm using Bull with NestJS.

**Comment by manast** [comment]
We have a vast test suite and .close is used in every test, so it works. If you found a special case where it doesn't we need a snippet to reproduce it. If it only happens with NestJS then that's the repo where to report the issue.

**Comment by ranshemt** [comment]
> We have a vast test suite and .close is used in every test, so it works. If you found a special case where it doesn't we need a snippet to reproduce it. If it only happens with NestJS then that's the repo where to report the issue.

I will try to create a repo that reproduces the issue in the coming days. Thank you!

**Comment by ranshemt** [comment]
> We have a vast test suite and .close is used in every test, so it works. If you found a special case where it doesn't we need a snippet to reproduce it. If it only happens with NestJS then that's the repo where to report the issue.

Hello again,

I can confirm that the issue is the 500ms pTimeout set in queue.js file (in `redisClientDisconnect` function).
I am unable to provide a reproducible snippet/repo - but I have seen that in some scenarios the quit command `client.quit()` of ioredis might take almost 5 seconds. The pTimeout limits it to 500ms only.

I think the 500ms should be a configurable option and not hardcoded. Increasing the 500ms solved the issue.
