### ISSUE TITLE
global:completed can't get result

### ISSUE THREAD

**Issue by mingxin-yang** [OptimalBits/bull#2451]
## Description
~~~
emailQueue.on('global:completed',function(job, result){
  console.log("job",job)
  conosle.log("result", JSON.stringify(result))
})
~~~
this way can't get result.
~~~
emailQueue.on('completed',function(job, result){
  console.log("job",job)
  conosle.log("result", JSON.stringify(result))
  
})
~~~
this way can get result
## Bull version
v4.8.1

**Comment by manast** [comment]
Works as designed. For global events we do not want to send the job's data in every event as it will add a lot of overhead. You can use ```getJob``` to retrieve the job if needed: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queuegetjob
