### ISSUE TITLE
update LTS versions 

### ISSUE THREAD

**Issue by jimmywarting** [OptimalBits/bull#2452]
According to https://github.com/nodejs/Release v10 and v12 have ended it's support
Just wondering if you should be setting it to something like `[14.x, 16x, 18x]` instead...

https://github.com/OptimalBits/bull/blob/3e5f007b24c3f79fd0360134a989ac78049fb5bc/.github/workflows/node.js.yml#L24

**Comment by manast** [comment]
We can add 16.x but we will keep the older ones as there are still many users on older NodeJS versions.
