### ISSUE TITLE
Is it possible to modify the options of a repeatable job (configuration) while it's running?

### ISSUE THREAD

**Issue by maximedupre** [OptimalBits/bull#2454]
Let's say I have a repeatable job similar to this:

```
await queue.add(
    'superJob',
    {},
    {
        repeat: {
            every: minToMs(15),
            immediately: true,
        },
        jobId: id,
    },
);
```

Once the job is running (and/or a delayed job has been scheduled), is it possible to modify the `repeat` options of the repeatable job (or its repeatable job configuration), such that the next scheduled jobs will occur at a different frequency?

Or does this functionality not exist, and we need to destroy and recreate a repeatable job (configuration) if we want different repeat options for the same job?

Thanks 🙏

**Comment by vivek12345** [comment]
I have a similar request too. 
Created a job with some low timeout which moved it to failed state. I want to retry this job but alter the job options by setting the timeout to a higher value or removing it completely.

Is there an api that can help in this?
