### ISSUE TITLE
Missing process handler for job type

### ISSUE THREAD

**Issue by hellojukay** [OptimalBits/bull#2458]
I have two nest.js micro service,  one of the services is responsible for adding named jobs to the queue , this service has no Processor configured, it does not handle consumption at all. The other service is responsible for consuming named jobs from the same queue, but I see from the redis data that not all jobs are successfully consumed, some of them fail, the failedReason is "Missing process handler for job type"

![image](https://user-images.githubusercontent.com/10371891/198497520-fe91682e-d0fd-43fa-b647-8dc86cc77f53.png)

**Comment by hellojukay** [comment]
```
    "@nestjs/bull": "^0.3.1",
    "bull": "^4.10.1",
```

**Comment by manast** [comment]
Please search in the documentation how to work with named processors and its limitations.
