### ISSUE TITLE
'job.data' passed in to processor callback is sometimes empty.

### ISSUE THREAD

**Issue by tinytortoise-dev** [OptimalBits/bull#2461]
## Description
As in the title, `job.data` passed in to processor callback is an empty object though our code ALWAYS pass in an object with values. This happens ocassionally in production environment, not in local environment.

Here's high level overview of the code:

```
import Queue from 'bull';
const queue = new Queue('queue');

onHappenEvent = async (evt) => {
  const job = await toBullJob(evt); // this job object always looks like: `{ name: 'some-job', params: { ... }}`
  const opts = {
        timeout: 60 * 1000,
        attempts: 1,
        removeOnComplete: true,
        removeOnFail: true,
        delay: 5 * 60 * 1000,
  };
  await queue.add(job, opts);
};

const processorCb = async (job) => {
  console.log(job.data); // Most of the time the output is `{ name: 'some-job', params: { ... }}`, but `{}` sometimes...
  // do something
};
queue.process(1, processorCb);

```

Since we always pass in a nonempty object with values to `queue.add` function, we expect that `processorCb` is always passed in THAT nonempty object. Does anyone have an idea of the cause of this problem?

## Bull version
3.22.12

## Additional information
We have 3 Node instances in a production environment. All of them accesses to one Redis instance.

**Comment by manast** [comment]
Whats your maxmemory policy configuration in Redis?

**Comment by tinytortoise-dev** [comment]
@manast 
```
> config get maxmemory*
maxmemory
0
maxmemory-samples
5
maxmemory-policy
noeviction
```

**Comment by manast** [comment]
I have never heard about this issue before, and I cannot see how this would be possible unless you really are sending data in every event. Have you checked to put a log before adding the job to BullMQ to verify it really is always an object and not undefined?

**Comment by tinytortoise-dev** [comment]
When we see our code, there seems to be no room where we could pass in a non-object value to bull's `add` function, such as null or undefined.
But haven't verified it yet by actually logging the value, so we'll insert a logger and see the output.

**Comment by tinytortoise-dev** [comment]
@manast 
As a reference, this is the job object passed in to the processor function:
```
{
    "id": "38272958",
    "name": "__default__",
    "data": {}, // this is weirdly empty...
    "opts": {
        "attempts": 1,
        "delay": 0,
        "timestamp": 1668129039381
    },
    "progress": 0,
    "delay": null,
    "timestamp": null,
    "attemptsMade": 0,
    "stacktrace": [],
    "returnvalue": null,
    "finishedOn": null,
    "processedOn": 1668128992531
}
```

**Comment by roych98** [comment]
I don't see a reason to which job.data should be empty, unless whatever comes back from toBullJob(evt) has nothing within it's `data` object. Can you please

**Comment by tinytortoise-dev** [comment]
@roych98 

```
interface Evt {
    deviceId: number; // Id of device that caused the event
}

// get some data that's needed by processor from postgres and redis
const toBullJob = async (evt: Evt) => {
    const device = await myDb.deviceTable.getById(evt.deviceId);
    if (!device.otherParams) throw new Error();
    const deviceCache = await myRedis.deviceCache.getById(evt.deviceId);
    if (!deviceCache.evtHappenedAt) throw new Error();
    return {
        name: 'device_event_job',
        device: {
            id: evt.deviceId,
            evtHappendAt: parseInt(deviceCache.evtHappenedAt),
        },
        otherParams: device.otherParams
    }
}
```

NOTE: toBullJob is actually an async function(I've updated the original description)

**Comment by manast** [comment]
If that's the code, then I agree, it looks as if it should always be defined. But it is also quite straightforward in the Bull internals, so I don't know why this is happening to you. As mentioned, this is the first time we hear about data being empty, so there must be something special in your setup.

**Comment by hgeldenhuys** [comment]
I'm also getting this. I can confirm that data is being added after I add a job, but when it is picked up and processed, the data object is empty

**Comment by manast** [comment]
@hgeldenhuys it is quite unlikely that this is an issue with Bull.

**Comment by hgeldenhuys** [comment]
Hey @manast , where else would this be do you think? I'm using NestJS, I'm processing bureau files. It all worked well for about 40 files, until I started processing 2GB files, inside redis even the data attribute is gone: 
<img width="944" alt="image" src="https://github.com/OptimalBits/bull/assets/179999/54479c65-bdb0-441c-878d-1a61b95a5a33">

**Comment by hgeldenhuys** [comment]
> I'm also getting this. I can confirm that data is being added after I add a job, but when it is picked up and processed, the data object is empty

Not only data, but timestamp is also missing
![image](https://github.com/OptimalBits/bull/assets/179999/ee17df48-f0fc-4605-bf56-a9c07d8c01d5)

**Comment by hgeldenhuys** [comment]
This is speculative, but this might be related to Redis, at some point it's not available for a moment while swapping memory files, and all hell breaks loose. So Bull doesn't get the jobs properly back but overlays the failure attributes on top of an empty object. Maybe Bull should just check that the timestamp is available before assuming the job's object is okay?

**Comment by manast** [comment]
@hgeldenhuys it looks like the job has been removed while still being processed. Data can be removed by Redis if you do not have the correct maxmemory policy configured... I am not sure what you mean with 2Gb files but I hope you are not sending 2Gb as data to a job, that is not a very good idea for many reasons. https://docs.bullmq.io/guide/going-to-production#max-memory-policy

**Comment by hgeldenhuys** [comment]
> @hgeldenhuys it looks like the job has been removed while still being processed. Data can be removed by Redis if you do not have the correct maxmemory policy configured... I am not sure what you mean with 2Gb files but I hope you are not sending 2Gb as data to a job, that is not a very good idea for many reasons. https://docs.bullmq.io/guide/going-to-production#max-memory-policy

No, it was a 2GB file split in lines of data. The implication was just that I was pushing a lot more data through. I'll check out the max-memory-policy, but the missing timestamp results in a 1970 default date when you do you stall calculation, and then a false missing lock is raised, which is why many people think increasing the lock duration variables don't solve anything. This should be handled differently as it puts people on the wrong troubleshooting path, unless it could be documented.

I don't think the jobs are being deleted, because there are still a lot of intact jobs waiting, but as soon as they get processed the missing lock logic kicks in and hides the real issue (which is probably due to redis' memory swap)
