### ISSUE TITLE
RemoveRepeatable doesn't work anymore!

### ISSUE THREAD

**Issue by rileyai-dev** [OptimalBits/bull#2467]
## Description
Removing repeatable jobs doesn't work anymore. I use the same code I had for v1.x but now it fails. I am simply adding a repeatable job and remove it.

## Minimal, Working Test code to reproduce the issue.
This very basic example returns `false`. All you need to do is replace `connection` with your connection settings.
```.js
(async () => {
  const myQueue = new Queue('cron', connection).on('error', (err) => {
    logger.error(`myQueue - ${JSON.stringify(err)}`);
  });
  await myQueue.add(
    'id',
    {
      data: 'myData',
    },
    {
      attempts: 1,
      repeat: { cron: '07 12 * * 1-5', tz: 'America/New_York' },
    }
  );
  const removed = await myQueue.removeRepeatable('id', {
    cron: '07 12 * * 1-5',
    tz: 'America/New_York',
  });
  console.log(removed);
})();
```

## Bull version
3.2.1

**Comment by rileyai-dev** [comment]
Oh, just found out that `cron` was changed to `pattern`. The doc is not very explicit about `tz`.

**Comment by manast** [comment]
@rileyai-dev no, it has not changed to pattern, that is in BullMQ only. I happen to post wrong link in my first comment, but it is corrected now.

**Comment by rileyai-dev** [comment]
Got confused between bull and BullMQ, my bad!
