### ISSUE TITLE
Error: Could not remove 'waiting' job when  job.takeLock() is called

### ISSUE THREAD

**Issue by luoxzhg** [OptimalBits/bull#2468]
## Description
Error: Could not remove 'waiting' job when job.takeLock() is called. 
job.releaseLock() must be called before job.remove().

**Is it possible that job become 'active' between job.releaseLock() and job.remove()?**

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
```
const { setTimeout } = require('node:timers/promises');
const Bull = require('bull');

const taskQueue = new Bull('test')

taskQueue.process(1, async (job) => {
   await setTimeout(1000 * 60)
   return 'completed'
})


async function main() {
   await taskQueue.add({ name: 'test1' }, { jobId: 'test1' })
   await taskQueue.add({ name: 'test2' }, { jobId: 'test2' })
   await setTimeout(1000)
   const job2 = await taskQueue.getJob('test2')
   if (await job2.takeLock()) {
      if (await job2.isWaiting()) {
         await job2.remove()   // Error: Could not remove job test2
      }
      await job2.releaseLock()
   }
}

main()


```
## Bull version
v4.10.1

## Additional information
Error
```
*****/node_modules/bull/lib/job.js:470
        throw new Error('Could not remove job ' + job.id);
              ^

Error: Could not remove job test2
    at ******/node_modules/bull/lib/job.js:470:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (******/src/example.js:19:10)
```

**Comment by manast** [comment]
When a job is locked you are not allowed to remove it, you need to unlock it first.

**Comment by luoxzhg** [comment]
> Is it possible that job become 'active' between job.releaseLock() and job.remove()?

**Comment by manast** [comment]
@luoxzhg that question without more context cannot be answered-

**Comment by manast** [comment]
You could have a small loop that retries 3 or 4 times to handle edge cases. Removing locked jobs is not a good practice anyway, there is a reason there are locks after all.
