### ISSUE TITLE
Rate limiter doesn't work

### ISSUE THREAD

**Issue by zenwraight** [OptimalBits/bull#2480]
## Description
 I want to rate limit my workers, for example run 1 worker in 20 secs, so I am using the following code, but it doesn't seem to work.

`server.js`

```
const opts = {
  // redisOpts here will contain at least a property of
  // connectionName which will identify the queue based on its name
  createClient: function (type, redisOpts) {
    switch (type) {
      case "client":
        return client;
      case "subscriber":
        return subscriber;
      case "bclient":
        return new Redis({
          // some redis config
        }, redisOpts);
      default:
        throw new Error("Unexpected connection type: ", type);
    }
  },
};

let myQueue = new Queue('myQueue', opts, { 
  limiter: {
    max: 1,
    duration: 20000
  }
});

  for(let i=0; i<10; i++) {
    let job = await myQueue.add({
      number: i
    });
  }
```

`worker.js`

```

function start() {
  let myQueue = new Queue('myQueue', opts, {
    limiter: {
      max: 1,
      duration: 20000
    }
  });

  myQueue.process(maxJobsPerWorker, async (job) => {
    console.log("Running job number:- ", job.data.number);
    return { value: "This will be stored" };
  });
}

throng({ workers, start });
```

I am using a throng library.

Please help me with this issue, I am new to this library and any tips and pointer will be helpful.

Thanks :)

## Bull version
`^3.7.0`

**Comment by manast** [comment]
I do not know what "throng" is. Can you please post a simple test case without third-party dependencies?

**Comment by zenwraight** [comment]
@manast so throng is a nodejs cluster - https://www.npmjs.com/package/throng . It's supposed to make thing faster, so could that be an issue that because I have a clustered nodejs ecosystem, but I even tried by using 1 worker as well and it didn't work.

**Comment by zenwraight** [comment]
@manast  can you share a simple example of how to create a queue and then consume it from worker? I will scrape off throng and try that out.

**Comment by manast** [comment]
You can find many examples if look around a bit. I will close this issue for now if there is no issue in Bull.
