### ISSUE TITLE
Can't resolve 'fs/promises'

### ISSUE THREAD

**Issue by SevenOfPaul** [OptimalBits/bull#2484]
When I use the new Queue to create queue in nextjs .It will  report error with "Can't resolve 'fs/promises'". 
This is my error message.
![aecee298f04ab57e01f70383467470d](https://user-images.githubusercontent.com/83870824/204138999-d379de62-309f-43eb-8265-897daa8f6261.png)
And this is my friend error message.
![779170161867420250](https://user-images.githubusercontent.com/83870824/204138956-3a09b61d-6730-47f3-afe5-ad6a30a40bde.png)
My env picture.
![1669557623(1)](https://user-images.githubusercontent.com/83870824/204139230-1ce1986e-1d75-4766-be2d-19102726b6dc.png)
This is my file.
[file.zip](https://github.com/OptimalBits/bull/files/10098464/file.zip)

**Comment by manast** [comment]
Which version of Node are you using? please try with version 14 or 16

**Comment by SevenOfPaul** [comment]
Thanks I v found the error which is constructor in web environment. I v repaired that. Thanks again.
Environment
.&nbsp;
------------------

Chris&nbsp;Evans
***@***.***



&nbsp;




------------------&nbsp;Original message&nbsp;------------------
From: "Manuel Astudillo"; 
Sendtime: Monday, Nov 28, 2022 3:58 PM
To: "OptimalBits/bull"; 
Cc: "Chris ***@***.***>; "Author"; 
Subject: Re: [OptimalBits/bull] Can&#39;t resolve &#39;fs/promises&#39; (Issue #2484)





 
Which version of Node are you using? please try with version 14 or 16

**Comment by SevenOfPaul** [comment]
Thanks I v found the error which is constructor in web environment. I v repaired that. Thanks again.
