### ISSUE TITLE
Queue.add: return job immediately on empty queue

### ISSUE THREAD

**Issue by jeanfrancois8512** [OptimalBits/bull#2488]
## Description
When a queue is empty I want Queue.add to return a job immediately and not wait for job execution.

```
const queue = new Queue('the queue')

queue.process(async function(job) {
  // take from a few second to a few minute to execute
}

// when queue is empty, this will hang for a few second. 
// I need the job object but dont want to wait for the job to be done.
const job = await queue.add({test: 'test'})

// next I send the job id with other info so that a remote client  can callback to get job status
```
## Bull version
4.10.1

**Comment by manast** [comment]
```Queue.add``` always return a job independently on if there are jobs in the queue or not.

**Comment by jeanfrancois8512** [comment]
My question should probably be: does it wait for the job to complete before returning the job object when the queue is empty? If the answer is no, this is most likely my job doing too much and I should have it on a separate process.

Thanks for clarifying this

**Comment by manast** [comment]
Adding a job is a separate thing from processing the job, I am confused about your question, not sure what to say.
