### ISSUE TITLE
Bull queue is pulling data slowly upon increased load

### ISSUE THREAD

**Issue by Kasuhikdas** [OptimalBits/bull#2491]
When we push to bull queue a lot of data. Bull emittign data slowly.

I have a code that updates Database. The average time of doing that is 0.01-0.02 -sec.When I pushed around 100k data the 100k data processed very fast. But as i start pushing data upon reaching 10x data of 100k the processing became very slow. But the db update time stayed the same.Redis memory usage was at 30%. Ec2 cpu utilization started dropping and same for DB. It seems when redis has a lot of data then bull get and write is getting slower.  

4.10.2 (Latest NPM version)

Deployed on ec2 with 8gb ram 4 gb swap. Running nodejs to process data.

**Comment by manast** [comment]
This information is not enough for us to provide you with any help. You need to provide a complete case that we can run, without third party dependencies that demonstrates that there is an issue Bull that makes the processing slow.

**Comment by Kasuhikdas** [comment]
It can be reproduced with queue of 100k data and its processing time without any db call. If we push 1.5 million entries then we can check how much each 100k is taking to process. Then the time can compared.

**Comment by manast** [comment]
So please provide such a test case that we can run and verify.
