### ISSUE TITLE
Jobs showing completed without being Processed

### ISSUE THREAD

**Issue by dapo-earnipay** [OptimalBits/bull#2492]
## Description
I am fetching some records from my database to be added to a queue to be processed individually. For more context each of those records will be fired off to a http request, the records can range from a thousand to about 10k.  I can see the jobs added to the queue in the bull-board ui, but checking those fetched records, I found no trace of them ever being processed, yet they show up as being completed on bull-board dashboard.

    

## Minimal, Working Test code to reproduce the issue.
I added those jobs to the queue using this code 
```
Promise.all(
    goalsForToday.map(async (goal) => {
      await SavingsQueue.add("save", goal, {
        removeOnComplete: false,
      });
    })
  )
```
<img width="804" alt="Screenshot 2022-12-12 at 10 09 18" src="https://user-images.githubusercontent.com/105109463/207006028-1530f5a3-d90f-4686-ae67-f5ed8d539da7.png">

Here is a screenshot of the jobs in the completed state in bull-board. 
The #job-19 job ran successfully, but #job-18 didn't run at all, I found no trace of the issue or what went wrong or what could be happening, the job just didn't get processed and I just found it on the completed list. 

I came back later last night to manually try to fire the job that didn't run

<img width="581" alt="Screenshot 2022-12-12 at 10 19 01" src="https://user-images.githubusercontent.com/105109463/207007995-988b6067-b7d2-4ff8-a480-7ca625ee3f46.png">

## Bull version
4.8.5

## Additional information
This logic worked seamlessly on my local machine, I started getting this error when I deployed to AWS ECS

**Comment by manast** [comment]
You are not providing enough information to be able to give you any help. For instance, you should provide a code test case that does not work according to your expectations. Screenshots of a queue dashboard do not provide any useful information to us.

**Comment by dapo-earnipay** [comment]
Apologies @manast I finally figured out the issue, the production server was connected to the same redis instance as the staging server, I guess the jobs that were missing here were getting processed by the staging server, I corrected the connection details and its been working fine for the past 2 days
