### ISSUE TITLE
EventEmitter Memory Leak Warning

### ISSUE THREAD

**Issue by ehubbell** [OptimalBits/bull#2493]
## Bull version
- bull 4.1.0

## Additional information
- node v16.18.1

## Description

Sorry to bring up an issue that's been covered in other threads ([615](https://github.com/OptimalBits/bull/issues/615), [738](https://github.com/OptimalBits/bull/issues/738), [1494](https://github.com/OptimalBits/bull/issues/1494), [1924](https://github.com/OptimalBits/bull/issues/1924)), but I'm getting the following warning every time I start my server:

```
Possible EventEmitter memory leak detected. 11 error listeners added to [Redis]. Use emitter.setMaxListeners() to increase limit
Possible EventEmitter memory leak detected. 11 ready listeners added to [Redis]. Use emitter.setMaxListeners() to increase limit
Possible EventEmitter memory leak detected. 11 end listeners added to [Redis]. Use emitter.setMaxListeners() to increase limit
```

I tried adding the following at the entry point of my application:

```
import Events from 'events';
Events.defaultMaxListeners = 1000;
```

I also tried adding the following at queue instantiation:

```
import Bull from 'bull';
import { logError, logSuccess } from 'src/utils/loggers';

class AppQueue {
	queue: any;

	constructor(queueName) {
		this.queue = new Bull(`${queueName} Queue`, process.env.REDIS_URL);
		this.queue.setMaxListeners(1000);
		this.queue.on('completed', (job, result) => logSuccess(`${queueName} Queue: `, { job, result }));
		this.queue.on('error', (error) => logError(`${queueName} Queue: `, { error }));
	}
}

export { AppQueue };
```

The following queue (which inherits from the AppQueue & has 11 named processes) is the culprit:

```
class ActivityQueue extends AppQueue {
	queue: any;

	constructor() {
		super('Activity');
		this.queue.process('Bank', BankActivityJob.process);
		this.queue.process('Card', CardActivityJob.process);
                 ...
	}
``` 

Per the issues I shared above, I eventually landed on asynchronously adding each named process to the queue like so:

```
class ActivityQueue extends AppQueue {
	queue: any;

	constructor() {
		super('Activity');
		this.addProcess(this.queue, 'Bank', BankActivityJob.process)
		this.addProcess(this.queue, 'Card', CardActivityJob.process);
                 ...
	}

	async addProcess(queue, processName, method) {
		await timeout(50);
		queue.process(processName, method);
	}
```

Which worked but it feels kinda hacky and doesn't line up with the accepted answers. Is there a reason neither the `Events.defaultMaxListeners` property or the `this.queue.setMaxListeners()` method aren't working for me? 

Thanks so much!!
Eric

**Comment by manast** [comment]
Are you sure that you really are setting ```defaultMaxListeners``` on the same process that is giving you the warnings?

**Comment by ehubbell** [comment]
> Are you sure that you really are setting `defaultMaxListeners` on the same process that is giving you the warnings?

I believe I'm setting `defaultMaxListeners` across all event emitters, per the code I copied, which is located at the entry point of my application.

As a fallback, I tried `setMaxListeners` when the queue get's instantiated, assuming that would configure each individual emitter process, but that doesn't appear to work either.

I presume this has something to do with the disposable handlers mentioned [here](https://github.com/OptimalBits/bull/issues/1494#issuecomment-538771360) but IDK.

Here are the relevant [Node Docs](https://nodejs.org/api/events.html#eventsdefaultmaxlisteners) I've been reading as well.

**Comment by manast** [comment]
If you set the number of defaultMaxListeners to a higher value than the expected number of listeners and you still get this warning (unlikely), then it would be a bug in node (very unlikely) :).
You can also use BullMQ, there you do not have any named processors so you won't get this warning.

**Comment by ehubbell** [comment]
Agreed :) I'll inspect more closely and thanks for the BullMQ suggestion :)

**Comment by ehubbell** [comment]
As a follow up, it looks like previously I was either a) attempting to `setMaxListeners()` on the queue itself or set `defaultMaxListeners` on the global `eventEmitter` and didn't have success with either. 

Upon further inspection, applying `setMaxListeners` on the `redis` connection itself is a Bull-friendly way of handling the warning. Here's an example:

```
import Bull from 'bull';
import { logError, logSuccess } from 'src/utils/loggers';

class AppQueue {
	constructor(queueName) {
		this.queueName = queueName;
		this.queue = new Bull(`${queueName} Queue`, process.env.REDIS_URL, this.options);
		this.queue.clients[0].setMaxListeners(50);
	}

}
```

export { AppQueue };
