### ISSUE TITLE
How to check if bull queue exists even if there are no jobs inside

### ISSUE THREAD

**Issue by fr1sk** [OptimalBits/bull#2498]
## Description
As far as I understand using `new Bull('queue-name')` a new instance of the queue will be returned if `queue-name` doesn't exist and the existing one if the queue exists. 

Is there a way to just get the instance and not create a new one? 🤔 (eg. something like `Bull.get('queue-name')` which will return queue instance if `queue-name` exists or `null` if there is no queue with provided name)

## Bull version
latest

**Comment by manast** [comment]
I am not sure what you are asking here, but if what you want is to check if a queue exists you can just check the key in Redis: ```bull:myqueuename:id```
