### ISSUE TITLE
Update to node_redis 2.4.2

### ISSUE THREAD

**Issue by wearhere** [OptimalBits/bull#250]
There have been some breaking changes, but quite a number of performance improvements: https://github.com/NodeRedis/node_redis/blob/master/changelog.md

**Comment by manast** [comment]
I am working on a branch with a lot of performance improvements that will end on 1.0. I am just having some work to do on the unit testing, most things are broken right now.

**Comment by wearhere** [comment]
Neat, thanks!

**Comment by manast** [comment]
fixed in v0.7.2

**Comment by wearhere** [comment]
Terrific!
