### ISSUE TITLE
Promise returned by job.finished() never resolves

### ISSUE THREAD

**Issue by Viiprogrammer** [OptimalBits/bull#2504]
## Description

When I create job after some time (for exmaple 5 sec) with `removeOnComplete`, and that job done immediately, promise returned by `job.finished()` never resolves (Sometimes it still works, but the majority of unsuccessful)

## Minimal, Working Test code to reproduce the issue.
```js
const Queue = require('bull')
const queue = new Queue('123')

queue.process('*', async (job) => {
  console.log('Processing job: ', job.id)
  /*
    Returns 123 immediately, don't wait
    If waiting some time before resolves, works fine
  */
  return 123
})

queue.on('completed', (job) => {
  console.log('completed', job.id) // Works fine
})

queue.on('error', (err) => {
  console.log(err)
})

async function main () {
  await new Promise(r => setTimeout(r, 5000)) // If remove works fine
  const job = await queue.add('name', { some: 'data' }, {
    removeOnComplete: true // If false, works fine
  })
  const result = await job.finished() // Never resolves
  console.log('Success', result)
}

main()
```

## Bull version
bull@4.10.2 (from `npm list`)

## Additional information

Appears only if all 3 requirements are met:
1. There is a wait after the queue is created
2. `removeOnComplete:true`
3. `queue.process` returns without waiting

YouTube (maybe 480p): https://youtu.be/2Vjru_wqK-0
Google Drive (good quality): https://drive.google.com/file/d/1LW66JlLE7faWjM_A6cUeoZpS_1A5S2vY/view?usp=sharing

Screenshot: (works 1 of 6 tries)
![изображение](https://user-images.githubusercontent.com/17622604/209398421-ce0ddc21-fbca-491c-a033-63fbd37aa466.png)

**Comment by manast** [comment]
From what I can see, the job finishes before your call to ```finished```, as since you are using "removeOnComplete" the job is not there anymore, so ```finished``` has no way to know the job has finished (or existed in the first place).
In general you should not wait for jobs to complete: https://blog.taskforce.sh/do-not-wait-for-your-jobs-to-complete/ that will make your code more robust and avoid edge cases like this.

**Comment by Viiprogrammer** [comment]
> From what I can see, the job finishes before your call to `finished`, as since you are using "removeOnComplete" the job is not there anymore, so `finished` has no way to know the job has finished (or existed in the first place). In general you should not wait for jobs to complete: https://blog.taskforce.sh/do-not-wait-for-your-jobs-to-complete/ that will make your code more robust and avoid edge cases like this.

I also think so, but this is a rather floating problem, which is not entirely obvious, I did not find anything in the documentation about this :(

It seemed to me that despite removeOnComplete:true this is not quite correct behavior
