### ISSUE TITLE
Cannot get repeat count of job on typescript

### ISSUE THREAD

**Issue by sangwoo-seo** [OptimalBits/bull#2506]
## Description
I'm trying to handle jobs depends on repeat count and the job types doesn't seems to have `count` property.

It's possible to access by `job.opts.repeat['count']` but I'm not sure if this is recommended.

Why is this missing from the type?

## Bull version
4.10.0

**Comment by manast** [comment]
It is an internal field but I suppose we could expose it, any thoughts @roggervalf ?

**Comment by roggervalf** [comment]
I'm looking that in bullmq we are exposing that value https://github.com/taskforcesh/bullmq/blob/master/tests/test_repeat.ts#L575, it could be the same in bull
