### ISSUE TITLE
Limit the maximum number of job logs

### ISSUE THREAD

**Issue by CodyTseng** [OptimalBits/bull#2508]
## Description

I want to add logs to a repeatable job. Then I found that there is no way to limit the number of logs. I'm concerned that this will take up too much memory. I don't know if my worry is superfluous 😂

## Bull version

v4.10.1

**Comment by manast** [comment]
Sounds like a nice enhancement, however, we are not adding new features to Bull anymore, only fixing bugs. All new development is happening at (BullMQ)[https://github.com/taskforcesh/bullmq]

**Comment by CodyTseng** [comment]
Looks like I need to migrate to BullMQ 🤣 

I found a similar issue in BullMQ https://github.com/taskforcesh/bullmq/issues/1600. Should I close this issue?
