### ISSUE TITLE
Priority not respected when using limiter - How does priority work?

### ISSUE THREAD

**Issue by T0BiD** [OptimalBits/bull#2510]
## Description

I have the feeling that priorities either do not work as expected or my expectation on how it should be working is wrong.
My expectation: 
Assuming a queue with 10 waiting jobs, all with priority 5. Limiter set to 1 job in 3 seconds.
If I add a new job, with a priority < 5, it should be the very next job that's being processed.

That does not seem to be happening when adding jobs to the queue from within a job.

## Minimal, Working Test code to reproduce the issue.

```
const Queue = require('bull');
const prioQueue = new Queue('prioQueue', {
    limiter: {
        max: 1,
        duration: 3000
    },
    defaultJobOptions: {
        priority: 4,
        removeOnComplete: true
    }
});

prioQueue.process((job) => {
    let data = job.data;
    console.log('processing:', data, 'with prio', job.opts.priority);
    if (job.opts.priority > 1) {
        data.v = data.v + 1;
        console.log('creating new job with prio', job.opts.priority - 1);
        prioQueue.add(data, {
            priority: job.opts.priority - 1
        });
    }
    return Promise.resolve();
});

prioQueue.add({
    foo: 'bar',
    v: 1
});

prioQueue.add({
    x: 'y',
    v: 1
});

prioQueue.add({
    name: 'alice',
    v: 1
});
```

Result:  
```
processing: { foo: 'bar', v: 1 } with prio 4
creating new job with prio 3
processing: { foo: 'bar', v: 2 } with prio 3
creating new job with prio 2
processing: { x: 'y', v: 1 } with prio 4
creating new job with prio 3
processing: { name: 'alice', v: 1 } with prio 4
creating new job with prio 3
processing: { foo: 'bar', v: 3 } with prio 2
creating new job with prio 1
processing: { x: 'y', v: 2 } with prio 3
creating new job with prio 2
processing: { name: 'alice', v: 2 } with prio 3
creating new job with prio 2
processing: { foo: 'bar', v: 4 } with prio 1
processing: { x: 'y', v: 3 } with prio 2
creating new job with prio 1
processing: { name: 'alice', v: 3 } with prio 2
creating new job with prio 1
processing: { x: 'y', v: 4 } with prio 1
processing: { name: 'alice', v: 4 } with prio 1
```

We can see, that the prio 2 job (foo:bar) created in line 4 get's executed AFTER 2 prio 4 jobs (x:y & name:alice).  

I'd expect to see something like this, especially since we're only doing one job every 3 seconds:  
```
processing: { foo: 'bar', v: 1 } with prio 4
creating new job with prio 3
processing: { foo: 'bar', v: 2 } with prio 3
creating new job with prio 2
processing: { foo: 'bar', v: 3 } with prio 2
creating new job with prio 1
processing: { foo: 'bar', v: 4 } with prio 1
processing: { x: 'y', v: 1 } with prio 4
...
```

## Bull version
4.10.2

## Additional information
Is my understanding of priorities not correct?

**Comment by manast** [comment]
The way rate-limited jobs are implemented in Bull does not allow for priorities to be respected. I do not think we have a test case for BullMQ that proves this works either, but I think it could work, it could be that there are some edge cases where a job does not respect the priority but in general, I think it will. https://github.com/taskforcesh/bullmq
