### ISSUE TITLE
EventEmitter Memory Leak

### ISSUE THREAD

**Issue by Dragonizedpizza** [OptimalBits/bull#2511]
#### (An easy to reproduce test case will dramatically decrease the resolution time.)

Upon adding and removing about 6 jobs (with a 3 minute gap between addition and removal), I get 2 warnings - with the same message `(node:18665) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Commander]. Use emitter.setMaxListeners() to increase limit`.

![image](https://user-images.githubusercontent.com/70718540/210659457-24c1e198-b558-46d1-870c-6bac10ddc79a.png)

## Bull version

bullmq - ^1.86.4

**Comment by Dragonizedpizza** [comment]
oh sorry, wrong repo

**Comment by sandesh-bhoir** [comment]
@Dragonizedpizza what was the fix here?
