### ISSUE TITLE
Logs of Job are not removed even set removeOnCompleted

### ISSUE THREAD

**Issue by yusef-ho** [OptimalBits/bull#2515]
## Description
Hello, we are using bull in NestJS project.
And we have cronjob tasks were built on top of @nestjs/schedule. But we are start to scale up adding more instances of server, so we want no duplicated cronjob tasks running. So we are trying to using bull to solve the problem.

We notice that the logs of repeatableJob(s) were not removed even set removeOnCompleted: true
 Is this correct behavior? Or we need some other extra settings?

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
```ts
const jobId = 'payment-settled-check';
const cron = '*/15 * * * * *';
const cronJobAddedInQueue = await this.paymentCronJobQueue.add(PaymentJobQueueJobNameEnum.SETTLED_CHECK, {}, {
  jobId: jobId,
  repeat: {
    cron: cron,
  },
  removeOnComplete: true,
});
```

## Bull version
3.20.0

## Additional information
@nestjs/bull: 0.5.2

**Comment by manast** [comment]
What do you mean by "logs"?

**Comment by yusef-ho** [comment]
> What do you mean by "logs"?

keys like the pattern
bull:payment:repeat:d0d6457bb85249022c29e67b44f26948:1673347845000:logs
<img width="1834" alt="Screen Shot 2023-01-10 at 6 58 10 PM" src="https://user-images.githubusercontent.com/33569998/211533887-a26507db-d8e4-4d63-b924-8141bbe04f38.png">

we did use job.log in the processor, but we expect the log was removed when the job was removed

**Comment by manast** [comment]
You are using a very old version of Bull. The current one is 4.10.2, which is also used by the latest version of @nestjs/bull

**Comment by yusef-ho** [comment]
> You are using a very old version of Bull. The current one is 4.10.2, which is also used by the latest version of @nestjs/bull

Thanks @manast 
I did tried 4.10.2 yesterday. I found the reason is that i used job.log in the @OnQueueCompleted event listener.
I guess because the job was completed and removed. but logs still written and not be removed.
I'm closing this issue. thanks
