### ISSUE TITLE
Recurrent jobs (according to a cron specification)

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#252]
It should be possible to add jobs that will be processed according to some cron specification (once or multiple times)

**Comment by linux4kix** [comment]
I do this using the later module.  http://bunkat.github.io/later/

**Comment by matthewmueller** [comment]
+1, @linux4kix can you be a little more specific?

**Comment by linux4kix** [comment]
@matthewmueller Sure.

I am doing it the other way around.  I use later to parse the cron schedule of a job and use later.setInterval to add the job to my queue at the specified interval.  If you have to run the job immediately then you can use a priority queue. 

This is just a quick hack to demostrate.

```
        var cronSched = later.parse.cron(schedule); 
                                                                           
        var timer = later.setInterval(function() {      
            queue.add(data, opts);                     
            },                                          
            cronSched                                                      
        ); 
```

**Comment by manast** [comment]
So maybe I should document this as a pattern usage instead of adding it to bull, since it is so easy and clean to do anyways.

**Comment by linux4kix** [comment]
It would be easy enough to add a schedule job option and if it is set catch
it in _add and wrap it in a handler similar to this.  Although I don't know
if it is worth pulling in another dependency for this feature.  I think
either is acceptable.

**Comment by manast** [comment]
I would like to revisit this feature. Basically I think a cron like behaviour is quite useful, and the patten explained above would work, but it is limited to just one client controlling the crons, and it lacks robustness in the case of failure.
I would like to propose a feature that is scalable, i.e. you can have many workers configured according to a cron job, so if any dies, the cron jobs will continue working, and with at-most-once semantics, i.e, if workers die or new worker are launched, no more than one job that fullfils the cron specification is processed.
My idea is to create a special key for every cron that expires the next time a cron job is to be processed. All workers will try to create a new key according to the cron specification, but only one will succeed, the one that will add the job to the queue, the job can then be processed by any worker.

**Comment by manast** [comment]
Pseudocode:

1) define a repeatable job with ```queue.schedule(period, callback)```
2) check if schedule unique key exists.
  2a) if  key does *not* exist, create schedule key with expiration time ```next(period)``` add job to the queue as LIFO (so it starts as quickly as possible).
  2b) if key does exists, get its TTL and set a timer that ends after TTL (or a bit earlier to compensate for latency). When the timer expires go to 2.

Unless I am missing something, this would be a quite robust mechanism for repeatable jobs that survives worker crashes and also having many workers working in parallel.

**Comment by jamesjjk** [comment]
@manast unique keys (jobId) are a great way to control repeatable jobs in a more fault tolerent design (i.e. where you operate a cluster/sentinal setup)

**Comment by manast** [comment]
@jamesjjk yes, you are right. The solution I have in mind is based on the customIds feature already in bull.

**Comment by manast** [comment]
Here some scratchpad notes I had.
```js

// https://www.npmjs.com/package/cron-parser
// https://www.npmjs.com/package/human-interval

Queue.prototype.repeat = function(name, period, tz, handler){
  //

  // var millis = next(period).

  // var customId = queue + name (+ hash(period))
  // addDelayedJob(name, customId);
  // 
  // How to avoid missing jobs if time is too tight?
  // with one worker:
  //   save the timestamp where the job is supposed to be executed.
  //   use the saved timestamp to calculate the next scheduled job.

  // with several workers:
  // same as before. One worker will implicitly become the leader...

}
```

**Comment by jamesjjk** [comment]
@manast I am using a very similar approach, the main issue is with jobs that 'removeOnComplete' - which is not possible in combination with repeatable jobs.

**Comment by lpgeiger** [comment]
@manast Is this still targeted for 3.0?

> My idea is to create a special key for every cron that expires the next time a cron job is to be processed.

**Comment by manast** [comment]
This is almost implemented, I am writing tests now.

**Comment by lpgeiger** [comment]
@manast  great :) looking forward

**Comment by manast** [comment]
@jamesjjk removeOnComplete will work since for every repetition a new job is actually created. This has several advantages and fits well in bull's design.

**Comment by manast** [comment]
PR: https://github.com/OptimalBits/bull/pull/527
