### ISSUE TITLE
Feature: TTL for job waiting in the queue

### ISSUE THREAD

**Issue by royalpinto** [OptimalBits/bull#2522]
## Description
Would be nice to an option on job to set the TTL after which it will be remove from the queue if it cannot be picked by the worker by then.

A rough example would be: Job to send an OTP must be valid only for few seconds, after which should be auto cancelled/removed.

**Comment by royalpinto** [comment]
https://github.com/taskforcesh/bullmq/issues/301

**Comment by manast** [comment]
You can easily accomplish this functionality by checking the timestamp in the job and just discarding it or something:
```
const TTL = 30_000;
const worker = new Worker('test', {...}, (job) => {
  if((Date.now() - job.timestamp) > TTL){
    return;
  }
  ...
})
```

**Comment by antoniojtorres** [comment]
Thanks for the great package manast and team.

I can add my perspective as this feature would be useful for the project I'm working on. Our scenario one where we generate a daily list of tasks to perform, the list is ordered by priority with the most important things at the top, and goes down to things that are not mandatory, but that we can perform if the mandatory tasks finish early, and would be nice to collect the result such tasks. 

However, at recurring intervals, the mandatory tasks will get added back in and push the low priority stuff back.  This can apply to any scenario where it just isn't worth to even process a job after x amount of time and it's worthwhile to free the worker for something of higher priority.

Having a waiting TTL would provide a straight forward way to ensure that these stale jobs don't slowly balloon in size. 

The suggestion above my manast is workable, but would cause gaps in processing if there are thousands or more items that become stale. 

My question, is it possible to leverage an internal redis process to allow certain items to be expired out without performing a drain as suggested above? 

Thanks again.
