### ISSUE TITLE
[Question] Dynamic queues / Queue per user

### ISSUE THREAD

**Issue by cosydney** [OptimalBits/bull#2527]
## Description

Hey there, 

First of all thank you for proving such a useful tool. I've been using it in my project and Bull has been super helpful. 

I am looking for suggestions/ideas on how to improve our architecture for better efficiency. This is probably trivial but hopefully this will be helpful to other people!

- We handle 150k webhooks from GitHub and GitLab per day. Each of those webhooks corresponds to an organization in our database. 
- We have around 400 active organizations
- Today we have a dedicated queue for GitHub and a queue for GitLab. Each webhook event is added to one of the two queue and bull has a job.process function that handle what to do with it. 

The problem with this way of doing for me is that I get many errors and some of our event are super slow to get through. Much slower than not going through any queue at all.

So far I've considered creating dynamic queues for each organization, ([#issue 867](https://github.com/OptimalBits/bull/issues/867), or [#Issue 1567](https://github.com/OptimalBits/bull/issues/1567)) 

- Do you have any recommendations on handling this use case? Would you go for a Dynamic queue per user?
- Let me know if you see anything in my code that seem like a no go!

Thank you

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

Here is my code: 
```
// create-queue.js

function createQueue(name) {
  return new Queue(name, {
    redis: {
      opts: {
        createClient(type) {
          switch (type) {
            case 'client':
              return client;
            case 'subscriber':
              return subscriber;
            default:
              return new Redis(REDIS_URL);
          }
        },
      },
    },
  });
}
```

```
// github-queue.js

const webHookGitHubQueue = createQueue('webhooksGitHub');
const { handleGitHubIncomingWebHook } = require('./github-connect');

webHookGitHubQueue.process(async (job) => {
  const { webhook, event } = job.data;
  const { attemptsMade } = job;
  try {
    const res = await handleGitHubIncomingWebHook({
      webhook,
      event,
      attempts: attemptsMade,
    });
    return res;
  } catch (e) {
    const errorMessage = `Error handling github webhook, event: ${event}, webhook id: ${webhook.id}, ${e?.message}, ${e}`;
    throw new Error(errorMessage);
  }
});

webHookGitHubQueue.on('completed', (job, result) => {
  if (result.processed) {
    job.remove();
  } else {
    throw new Error("Didn't process GitHub webhook correctly", result);
  }
});

module.exports = {
  webHookGitHubQueue,
};
```

```
 // github-connect.js 
 
await webHookGitHubQueue.add(
    {
      webhook,
      event,
    },
    {
      jobId: webhook.id,
      delay: 0,
      attempts: 3,
      backoff: {
        type: 'exponential',
        delay: 1200,
      },
      removeOnComplete: {
        age: 24 * 3600, // keep up to 24 hour
        count: 1000, // keep up to 1000 jobs
      },
      removeOnFail: {
        age: 7 * 24 * 3600, // We keep failed job only for 7 days max
      },
    },
  );
  ```

## Bull version
4.10.2

**Comment by manast** [comment]
Thanks for your kind words. 

There are several problems with having several hundred queues. But basically, it becomes quite difficult to manage, both in code and even when debugging and monitoring.

Unfortunately, the requirement to have dynamic queues implemented as a core function in Bull is not as trivial as it may seem. Basically what you need is a potentially unbounded number of "virtual" queues (one per user for example), and then pick the jobs from these queues in a round-robin fashion. If on top of this, you add stuff like rate-limiting and constraints on the number of active jobs per queue, it becomes quite hard to implement.

Nevertheless, we implemented a feature like this in BullMQ Pro (paid version of BullMQ), we call it groups: https://docs.bullmq.io/bullmq-pro/groups.

**Comment by cosydney** [comment]
Thank you for responding so fast @manast. 

I'm considering switching to BullMQ. It's a budget for us right now as a bootstrap startup. If there is any other place you think we could optimize I'm all hears !

**Comment by samuelpares** [comment]
Hey @cosydney 
I'm having the same necessity.
Could you share what approach did you follow? 
Since the budget is a problem right now, I won't be able to use BullMQ Pro, so I'm going with several queues, one for user.

**Comment by tecoad** [comment]
I am very sad to hear that bullmq does that as a "pro" feature. 
I had same necessity and ended up by using Qstash, which at the ends does the same but is a pay as you go service.
1300 usd year for a startup is quite a lot.

**Comment by shrugs** [comment]
@tecoad can you expand on how you implemented the groups-style functionality within QStash?

**Comment by tecoad** [comment]
> @tecoad can you expand on how you implemented the groups-style functionality within QStash?

Thats basically default. 
There is no such a limitation in qstash, just adopt you unique name (ie. UserID) as your queue name then FIFO will be default

**Comment by manast** [comment]
@tecoad So how would that be different from using userId as your queue name in Bull?

**Comment by manast** [comment]
> I am very sad to hear that bullmq does that as a "pro" feature. I had same necessity and ended up by using Qstash, which at the ends does the same but is a pay as you go service. 1300 usd year for a startup is quite a lot.

The thing is, if you are a startup you probably don't need it, you will most likely be fine with our generous open-source version, this is most than enough if you do not have very large requirements. The day you succeed with your start-up and you really need the Pro version it will not be expensive at all considering the value it provides... at the end of the day we all need to make a living, even if we give a lot for free.

**Comment by manast** [comment]
Btw, and just as a reminder, we put most of our efforts in BullMQ, which is faster, more robust and has much more features than Bull: https://github.com/taskforcesh/bullmq

**Comment by tecoad** [comment]
> @tecoad So how would that be different from using userId as your queue name in Bull?

As far as i know, bullmq was not designed eu tb that use case in mind. 1. Ui makes impossible to find a queue. 2. Impossible to debug 3. No clear of bullmq was designed to have unlimited queues created at execution time. (I have search for it and seems not). 

I am definetely not saying that bullmq is a product not worth paying. Definitely not saying it. I use it in many of my projects and this is great.

But this is technology, and as it is the needs and requirements evolves overtime. So in that in mind, I do not agree that this is feature for only already grown companies. 
My discussing is that "1300 year or nothing" is not only damage for my company, but for yours. Which could be way more profitable targeting a broader market.  
I have solved it without bullmq. 
But I would be happy to pay for it if I could.

**Comment by manast** [comment]
@tecoad I do not understand your view on "it is 1300 or nothing"? I mean, you get tons of free open-source stuff, whereas the Pro features are basically not available anywhere else. There is nothing in BullMQ preventing you to have as many queues as you want. Not sure what you mean the UI makes it impossible to find a queue, which I U are you referring to?

The fact that you could build it without group support from the Pro version demonstrates that you did not need the groups functionality to begin with. Now, the actual price is still $995 per year, which is peanuts if you really need it. If you don’t need it, if it is a nice-to-have thing, then of course it is expensive.

Anyway, it is a moot discussion so let's leave it here.
