### ISSUE TITLE
[Question] what is the difference between error and failed event?

### ISSUE THREAD

**Issue by bmyun** [OptimalBits/bull#2528]
## Description
 - what is the diffrence?
 - when error occured on processing job, failed event is started but error event is empty.
 - Is the error handler not handled???

**Comment by kakasoo** [comment]
Same question...

**Comment by manast** [comment]
Error event is for stuff like redis connection errors. Failed is only for failed jobs.

**Comment by maitrungduc1410** [comment]
hi @manast does Bull auto retry "error" job?

let say during running there's lost in redis connection -> on error event fired, how can I retry failed jobs?
