### ISSUE TITLE
Calling `job.remove()` from 'completed' emits warning

### ISSUE THREAD

**Issue by wearhere** [OptimalBits/bull#253]
That warning is ["Warning: a promise was created in a handler but none were returned from it"](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it) and comes from Bluebird.

It occurs because doing this:

```js
queue.on('completed', function(job) {
  job.remove();
});
```

synchronously creates a promise within [this `then` callback](https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L605).

To fix this issue, that `then` callback should return `null` as described in [the Bluebird docs](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it).

**Comment by wearhere** [comment]
A temporary workaround is to call `job.remove()` after a timeout.

**Comment by manast** [comment]
good catch, I will fix this right away.

**Comment by wearhere** [comment]
Thanks for the quick response & fix @manast !
