### ISSUE TITLE
Worker is not picking up the new jobs when redis got restarted

### ISSUE THREAD

**Issue by gokul-moorthy** [OptimalBits/bull#2531]
I've tried the sample application where every five second message will be added to the queue. when I restarted the redis, worker is not picking up the latest jobs.

## Minimal, Working Test code to reproduce the issue.
Consumer:
```js
const { Worker } = require('bullmq');

const redis = {
    host: 'localhost',
    port: 6379,
    reconnectOnError: () => {
        console.log('====>>> trying to connect redis ');
        return 5000;
    }
};

const queueName = 'sample_queue';

const worker = new Worker(queueName, async job => {
  console.log(job.data);
}, {
    connection: redis
});

// Add Event Listeners
worker.on('completed', job => {
    console.log(`${job.id} has completed!`);
});

worker.on('failed', (job, err) => {
    console.log(`${job.id} has failed with ${err.message}`);
});

console.log('----------- Consumer listening -----------');
```

Publisher:
```js
const { Queue } = require('bullmq');

const redis = {
    host: 'localhost',
    port: 6379,
    reconnectOnError: (times) => {
        console.log('====>>> retrying ', times)
        return 5000;
    }
};

const queueName = 'sample_queue';

const queue = new Queue(queueName, redis);

async function init () {
    let dt = new Date();
    await queue.add('job1', {
        data: 'some data',
        date: dt
    });
    console.log('Published ----', dt);
}

// Start Publishing
setInterval(init, 5000);

// init();
console.log('---------------- Published ---------- ');
```

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
run  the above sample code. while execution restart your redis instance. in my case I'm running redis in docker.

## Bull version
"bullmq": "^3.5.11",

## Additional information
NodeJs - 16.16.0
Redis - 7.0.8 (standalone mode) docker without password.
WSL - Ubuntu

**Comment by manast** [comment]
I am going to be a bit grumpy here; this is working, I am 100% sure of it, it has been tested at length in all possible scenarios. Probably you are not waiting enough time, it can take up to 30 seconds before a job is considered stalled and is picked up by another worker.
