### ISSUE TITLE
Can we read queue data created by bullmq from python consumer

### ISSUE THREAD

**Issue by muhammad-omer-dev** [OptimalBits/bull#2532]
Hi,
I am currently running application in node.js and need to write python code for OCR services but for communication i am using Bullmq right now. I need to Publish data from Bullmq into queue and consume that data using Python Is this possible ?. Or any workaround for it ? Really need help on this.

**Comment by manast** [comment]
There may be a python version of [BullMQ](https://bullmq.io) this year, but no release date yet.

**Comment by manast** [comment]
https://bullmq.io/news/022023/python-package/
