### ISSUE TITLE
Specify in documentation which ACL rules to add to allow bull to work normally

### ISSUE THREAD

**Issue by soumitradev** [OptimalBits/bull#2534]
By default, I exclude all ACL rules, and then I add my own ACL rules as I go for security. Now, on adding bull I have to figure out which redis commands bull uses internally so I can add them individually to my ACL config. It would be really convenient if the exact ACL rules to add were mentioned somewhere in the docs.

I'm willing to add it to the docs and to the guide, it's just that I'm not too sure if the set of ACL rules I'm using cover every use case out there. (I am using Queues, and adding jobs to the queues using a priority).

If someone knows the exact set of commands and key patterns bull uses, I'd be happy to add it to the docs and guide.

P.S. Phenomenal work on the library, I really appreciate it <3

**Comment by manast** [comment]
I recommend you use Redis MONITOR command to see what is going on. It is not easy to gather the list of all used commands. I think it would be easier to allow the keys used by the queues than the commands...

**Comment by MartianH** [comment]
I actually second this, I am in the same boat right now. Especially since gathering a list of user commands can be done once.

**Comment by manast** [comment]
One possibility is to run a script with a regexp that finds all the calls to redis commands in the lua scripts.
