### ISSUE TITLE
Pause -> Retry failed -> Resume leads to retried waiting jobs getting stuck.

### ISSUE THREAD

**Issue by levysam** [OptimalBits/bull#2540]
## Description

these are the steps that reproduced the issue:

I had a queue that was processing 2 jobs at a time. There were, say 5 failed jobs and 10 jobs in 'Waiting' state.

I am using Bull Master, that shows a 'Stuck' state if I access the job by ID.
Unfortunately there appears to be no direct way to find these Stuck jobs so I may restart them/reschedule them - which would have been a workaround. :(

1. Pause the queue and wait for currently processing jobs to complete.
2. Result: 10 jobs go from 'Waiting' to 'Paused' state.
3. Retry failed jobs
4. Result: 2 jobs start being processed, remaining 3 jobs of the 5 go to 'Waiting' state.
5. 10 jobs remain in 'Paused' state.
6. Unpause the queue:
7. Expected: There should be 10 + 3 = 13 jobs in 'Waiting' state.
8. Actual: There are 10 jobs in 'Waiting' state. The original 3 retried jobs are in a stuck state.

you can reproduce the bug easily following the readme of this project: https://github.com/levysam/bull-bug-scripts

## Bull version
4.10.3

**Comment by manast** [comment]
There is a bug in that retry is not taking into consideration the queue status (waiting or paused).

**Comment by manast** [comment]
Fixed here https://github.com/OptimalBits/bull/pull/2549
