### ISSUE TITLE
QueueOptions docs mistake/confusion, and how to use an already-configured redis client?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [OptimalBits/bull#2551]
Hi,

I'm reading https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queue and the QueueOptions section has two parameters named "createClient", is that a mistake? One of them seems to indicate a function (it has an arrow in the type), and the other does not.

Related to this, I'd like to be able to provide an already-configured redis client instead of providing options for Bull to create the client with itself. Is this possible? It isn't clear from the docs.

**Comment by manast** [comment]
Thanks for the issue. I think for some reason the old property got duplicated, I have corrected it now. There is more information regarding reusing connections here: https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#reusing-redis-connections
If you are new to Bull though I would recommend that you use BullMQ instead: https://github.com/taskforcesh/bullmq
