### ISSUE TITLE
equest for Option to Remove Completed Tasks from Error List in bull Library

### ISSUE THREAD

**Issue by bueno12223** [OptimalBits/bull#2553]
I have encountered an issue while using the bull library where a task would fail multiple times and when it finally executes successfully, the task remains in the error list. This resulted in me trying to execute the task again and again as I was unaware that it wouldn't get removed upon completion.

It would be helpful if there was a way to configure a task to remove or not remove from the error list once it has a success status. This would provide better visibility of the remaining tasks that need to be executed and reduce the chance of duplicated work.

Please let me know if this feature can be added and if there is any other information I can provide to help. Thank you for your time and for maintaining the bull library.

**Comment by manast** [comment]
A task that succeeds does not go to the failed list, but to the complete list.
