### ISSUE TITLE
Throw error when failing to connect to Redis

### ISSUE THREAD

**Issue by daniellwdb** [OptimalBits/bull#2557]
## Description

I was looking for a simple queue library and found this one. I decided to quickly get started (or so I thought) so I jumped straight into the "Quick Guide". I saw:
```typescript
const videoQueue = new Queue('video transcoding', 'redis://127.0.0.1:6379');
const audioQueue = new Queue('audio transcoding', { redis: { port: 6379, host: '127.0.0.1', password: 'foobared' } }); // Specify Redis connection using object
const imageQueue = new Queue('image transcoding');
const pdfQueue = new Queue('pdf transcoding');
```
Which made me think "If I don't pass in any Redis credentials, it would store things in memory". I did not get any errors so I thought everything was fine. I spent 1 hour browsing issues, searching SO for "bull node queue add not working" and trying different environments. Then I asked for help from the community and I was pointed to:
```
Requirements: Bull requires a Redis version greater than or equal to 2.8.18.
```
My request is to please add some kind of error when the library fails to connect to Redis. If I did have a running codebase and Redis instance that would fail without me noticing I would be stuck wondering why some random `await queue.add` call in my codebase never resolves if I figure that is the issue in the first place

**Edit**
I figured eventually it does error:
```
MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
```
But I did not notice this since I was developing with nodemon and changed code while trying to get things to work. Maybe just some initial connection fail error would be nice to have

**Comment by manast** [comment]
I am sorry you wasted some time figure things out, but it is literally written on the description:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/95200/219977740-23c5ac3a-1e4b-431c-a110-5092ddfbd247.png">

In any case, of you are new to Bull you probably should start with [BullMQ](docs.bullmq.io) instead.
