### ISSUE TITLE
Integration with node-cron-expression

### ISSUE THREAD

**Issue by kbariotis** [OptimalBits/bull#2560]
Hi all, I've wrote [node-cron-expression](https://github.com/kbariotis/node-cron-expression) a while back, a small library to help with writing cron expressions in a declarative way.

I was wondering if you would be interested in integrating it in `bull` somehow or adding it to the docs? I'm happy to make a PR. 

Thank you and let me know of any thoughts

**Comment by manast** [comment]
We are not adding new features to Bull. However in BullMQ, it is possible to define custom repeat strategies, you are very welcome to write a blog post or something like that where you use your library to define a repeatable job and we will happily link it from bullmq.io or another suitable place. You can read more about repeat strategies here: https://docs.bullmq.io/guide/jobs/repeatable#repeat-strategy
