### ISSUE TITLE
How to change repeatable job payload (data)? 

### ISSUE THREAD

**Issue by ElFisherMan** [OptimalBits/bull#2564]
I want to use BullMQ as a scheduling solution for all our services. Meaning - each service can register a repeateable job with the following fields: ID, pattern (cron), data.
I would like to allow changing the data, while keeping the current scheduling.
AFAIK this is not possible in BullMQ (right?).
So the second best option - tell them to remove and re-add the reapeatable job with different data.
Having said that - I would like to have a check that checks if the data is different from the one configured for the repeatable job (with the same id and cron) and throw an error in such case.
Is this possible?

(When I call getRepeatableJobs, I only get the following fields (data is missing):
key, name, id, endDate, tz, pattern, next)

**Comment by manast** [comment]
I am closing this since it is a duplicated and in the wrong repo.
