### ISSUE TITLE
add support for ioredis tls connection

### ISSUE THREAD

**Issue by cliff0412** [OptimalBits/bull#2569]
## Description

i could not connect to redis with tls encryption
needs to support connect redis as below
new Redis("redis://:authpassword@127.0.0.1:6380/4", options);

**Comment by akovacspentalog** [comment]
You can use an existing tls connection with ioredis and pass it to bull.
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md

example:
`import Queue from 'bull';
import Redis, { RedisOptions } from 'ioredis';
const connection = new Redis(redisUrl, redisDefaultConfig); //here you can connect with tls
const createClient = (type: 'client' | 'subscriber' | 'bclient') => {
      switch (type) {
        case 'client':
          return client
        case 'subscriber':
          return client
        case 'bclient':
          return client;
        default:
          throw new Error('Redis error! Client not initialized properly');
      }
const exampleQueue = new Queue('exampleQueue', {
      createClient,
    });
`

**Comment by cliff0412** [comment]
but i am using @nestjs/bull, their code is as below
```
static forRootAsync(asyncBullConfig: SharedBullAsyncConfiguration): DynamicModule;
```
where they only accepts redis options other than a client

**Comment by cliff0412** [comment]
thanks for the reply. i am able to connect redis with tls by setting the createClient option. 
however, i encounter another problem 
```
Using a redis instance with enableReadyCheck or maxRetriesPerRequest for bclient/subscriber is not permitted
```

i will open a new issue regarding this
