### ISSUE TITLE
Bug: Error Redis is already connected, as a result nodejs crashes. 

### ISSUE THREAD

**Issue by mai1x9** [OptimalBits/bull#2574]
## Description
An unexpected error is thrown as shown below,
```
/home/ubuntu/awsimage/node_modules/ioredis/built/Redis.js:107
                reject(new Error("Redis is already connecting/connected"));
                       ^

Error: Redis is already connecting/connected
    at /home/ubuntu/awsimage/node_modules/ioredis/built/Redis.js:107:24
    at new Promise (<anonymous>)
    at EventEmitter.connect (/home/ubuntu/awsimage/node_modules/ioredis/built/Redis.js:103:25)
    at /home/ubuntu/awsimage/node_modules/bull/lib/queue.js:1340:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The error is rasied when `pause()` is used as shown below,
```
await imageProcessQueue.pause({
      isLocal: false, // The pause can be either global or local. 
      // If global, all workers in all queue instances for a given queue will be paused
      doNotWaitActive: true
    })
```
The above call to `pause()` is called multiple times, as consumer processes the events. Suddenly the above error has occured. 

**Queue declaration is shown as below,**
```
const imageProcessQueue = new Queue('imageprocess', {
  redis: {
    host: process.env.BULL_HOST,
    port: process.env.BULL_PORT
  },
  limiter: {
    max: 5000, // limit 5000 jobs per 1 second
    duration: 1000,
    groupKey: "orgid" // allows grouping of jobs with the specified 
    // key from the data object
  }
});
```

-----

## Minimal, Working Test code to reproduce the issue.
This is a part of large code base, the entire code cannot be shared, however the workflow is
- consumer processes the image from queue.
- And then pushes to aws s3 bucket.
- On AWS bucket ratelimit issues to slow down requests, the consumer calls `pause()`.
- As a result, some of the events for which slow down request occurred(in my case around 5-10 events executed `pause()`), it calls `pause()`
- Suddenly redis crashes. 

**I am suspecting is it due to multiple calls to `pause()` ?**

## Bull version
- **4.8.4**
- NOTE: Bull is used (not bullmq)

## Additional information
- NA

@manast

**Comment by mai1x9** [comment]
> I am suspecting is it due to multiple calls to `pause()` ?

Sorry, I have checked to wrap around try except for `pause()` as shown below,
```
try{
          await imageProcessQueue.pause({
            isLocal: false, // The pause can be either global or local. 
            // If global, all workers in all queue instances for a given queue will be paused
            doNotWaitActive: true
          })
        }catch(e){
          console.log("Error pausing: ", e)
          
        }
```
Looks like error is not at `pause()`. May be the other consumers or events are being processed or tried to pull from redis and redis connection might have been closed or something else ??

Also, when `pause()` used, looks like the code is blocked, because i could not see the console.log statements written after `pause()` call. Since `await ...pause()` used, is it blocking the code? How long does it block??

**Comment by manast** [comment]
Unfortunately, there is not much to go for us here without some snippet that reproduces the issue...

**Comment by manast** [comment]
I have no idea, I have never seen an error like this. Seems like the same IORedis instance is used twice for connecting to a Redis server.

**Comment by mai1x9** [comment]
Also, i am getting below error, for the job,
```
Failed: Job-382 Error: job stalled more than allowable limit
    at /home/ubuntu/awsimage/node_modules/bull/lib/queue.js:1017:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
   
```

Please allow me a day to make error reproducible code. I cannot share the current code base since it has lot of files interconnected. Will try to make simple code and share.

Thanks for the quick response.

@manast

**Comment by WaleedAshraf** [comment]
Also getting same error on queue.close()

"bull": "^3.5.2"
"ioredis": "5.0.0"


```
console.error
    Error: Redis is already connecting/connected
        at ...gateway/node_modules/ioredis/built/Redis.js:107:24
        at new Promise (<anonymous>)
        at EventEmitter.connect (...gateway/node_modules/ioredis/built/Redis.js:103:25)
        at ...gateway/node_modules/bull/lib/queue.js:815:26
        at processTicksAndRejections (node:internal/process/task_queues:96:5)

      at node_modules/bull/lib/queue.js:573:22
```

**Comment by mai1x9** [comment]
> Also getting same error on queue.close(true)
> 
> "bull": "^3.5.2" "ioredis": "5.0.0"
> 
> ```
> console.error
>     Error: Redis is already connecting/connected
>         at ...gateway/node_modules/ioredis/built/Redis.js:107:24
>         at new Promise (<anonymous>)
>         at EventEmitter.connect (...gateway/node_modules/ioredis/built/Redis.js:103:25)
>         at ...gateway/node_modules/bull/lib/queue.js:815:26
>         at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
>       at node_modules/bull/lib/queue.js:573:22
> ```
> 
> It seems it its from close(true) -> pause() -> bclient.connect()
> 
> Thats what causing the issue. maybe.
> 
> In pause method:
> 
> ```
>         if (doNotWaitActive) {
>           // Force reconnection of blocking connection to abort blocking redis call immediately.
>           return redisClientDisconnect(this.bclient).then(() =>
>             this.bclient.connect()
>           );
>         }
> ```
> 
> Also note, we are using ioredis in our project separately also.

@WaleedAshraf thanks for delataied info, although I haven't found time to reproduce the issue I suspected the primary root cause to be somewhere at pause resume calls. 

@manast Can you please suggest a fix for this? Any further information required I may try to reproduce it.

**Comment by mai1x9** [comment]
@manast for now I found a temporary fix. Instead of using bull inbuild pause resume, I have implemented my own logic to block the code by sleeping for `x` seconds and adding timestamp till when it should be sleeping, I names as lock release time stamp in ioredis. 

Other workers will access the lock release time. if `delta = lock release timestamp - current time > 0`, the workers will sleep for `delta` seconds. If key expires it anyway returns null and workers will continue as usual. 

Actually maintaining the lock release timeout is not required, let all workers throw the error and sleep for `x` seconds. The workers will resume work independent of the other workers. However I suspect we may end up in a situation for few workers where it will always get into sleep mode.

**Comment by manast** [comment]
@mai1x9 the question is, why are you using pause for rate limiting instead of using the rate limit?

**Comment by mai1x9** [comment]
> @mai1x9 the question is, why are you using pause for rate limiting instead of using the rate limit?

Rate limit feature is already in use. Pause is used to Halt the execution of tasks (that's what I believe). There might be situations let's day API requests hitting to a server and server sends 429. In that case there's no point for every consumer to put subsequent requests to server since they all return 429. Instead pausing the tasks till retry timeout will ensure that other consumers won't be hitting requests to server uncessarily.

I just given you an example of api requests. But in real life we would have many situations like when db goes offline and you do batch processing, you retry db connections so what's the point consumer trying to query or update db. It turns out to be a better option to halt the jobs till db connection is established.

and the list goes on.

**Comment by koplenov** [comment]
any news :?

**Comment by manast** [comment]
@koplenov nop. There will be no attempt to fix it unless we get a succinct reproducible test case. Otherwise you can use BullMQ where this issue has never been reported.
