### ISSUE TITLE
How to overwrite a queue's name completely in Bull 

### ISSUE THREAD

**Issue by Shahtaj-Khalid** [OptimalBits/bull#2579]
## Description

Hi, I like to know if there is any way I can overwrite complete queue name in Bull ? My use case is to overwrite the wait queue's name while adding the job in bull, I'll use that new queue to perform some operations  and then will write the data back in the actual wait queue which will be used by process method of Bull, to consume the jobs. The only option we seems to have available is to add a prefix in all queues, but I want to completely overwrite the queue name, while adding the job ONLY, consumer will still listen to the wait queue which will be created internally by bull.

USE Case example : 
- currently this is the wait queue in my case : `bull:jobs:wait` and it carries jobs ids.
- I want it to change it to this `t-bull:jobs:wait-<some hash>`, and it'll have the job ids now
- this queue `t-bull:jobs:wait-<some hash>` will be listened by some worker and it'll perform some operations/re-arrange job ids etc and will write the updated/re-arranged list of job ids back in `bull:jobs:wait` queue.

**NOTE** : I need to overwrite the `wait` Queue only.

Is this use case achievable ? can we overwrite any particular queue/key name in bull ? kindly let me know.

Thank you.

## Bull version
^4.10.2

**Comment by manast** [comment]
Renaming the keys that are used by Bull internally does not sound like a very good idea. Maybe it is better if you explain what you want to achieve at a higher level, I am quite sure there is a better solution than messing with Redis keys directly.

**Comment by Shahtaj-Khalid** [comment]
> Renaming the keys that are used by Bull internally does not sound like a very good idea. Maybe it is better if you explain what you want to achieve at a higher level, I am quite sure there is a better solution than messing with Redis keys directly.

Our use case is to prevent starvation of the jobs, we'll be using bull on a large scale, with multiple producers from different tenants emitting jobs in same queue and multiple consumers listening to the same queue as well. In order to avoid starvation/latency issues if one of the tenant produced so many jobs, jobs from other tenants can suffer. We have a service which perform round robbin algorithm on the jobs within any given queues (multiple source queues) and write them back in the final destination queue. For that, we need to overwrite the wait queue(while adding the job only), with our given source queues. And our service will write the data back in the main wait queue, which bull will be listening to. We just want to write the data in our given queue instead of the internally created wait queue, while adding the job.

**Comment by Shahtaj-Khalid** [comment]
> Renaming the keys that are used by Bull internally does not sound like a very good idea. Maybe it is better if you explain what you want to achieve at a higher level, I am quite sure there is a better solution than messing with Redis keys directly.

We can achieve this if we use the `addJob.lua` script directly as it takes keys as input, instead of using the `add` method exposed by bull (this will work as well), but I wanted to confirm if there is any way we can overwrite the queue name completely? If not, then will have to opt for using the script directly to add the job.

**Comment by Shahtaj-Khalid** [comment]
@manast Do you have any feedback on my use case and the solution I'm following ? kindly let me know.
thanks.

**Comment by manast** [comment]
This functionality is provided in the Pro version: https://docs.bullmq.io/bullmq-pro/groups
I do not think there is an easy way to implement such a feature on top of the current Bull I am afraid, the group's functionality is quite complex to get right actually...
