### ISSUE TITLE
Make brpoplpush and lock an atomic operation

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#258]
We have an hazard where while a job is being moved from wait to active, another worker may pick the job as being stalled since the worker that moved the job did not have time to create a lock. This hazard does not seem to be dangerous but it is a malfunction that should be avoided.

(related to #257 )

**Comment by manast** [comment]
this cannot be done properly due to redis limitations (we cannot use blocking commands in multi or lua scripts)

**Comment by wearhere** [comment]
What if the worker locked the job before changing its status?

**Comment by manast** [comment]
if we keep using brpoplpush it is not possible... we would need a polling mechanism, and we want to avoid that.

**Comment by bradvogel** [comment]
Addressed in https://github.com/OptimalBits/bull/pull/358/files

**Comment by bradvogel** [comment]
just fyi: I asked if this is supported in Redis 3.2. Unfortunately it is not: https://twitter.com/BradVogel/status/791189530548195328
