### ISSUE TITLE
Redis evalsha take too long to run

### ISSUE THREAD

**Issue by matheusf31** [OptimalBits/bull#2583]
## Description
I'm using the Queue delay job to run jobs after a time. I have a lot of jobs in delay (like 1000+). I use the newrelic to monitor my app and I see that redis evalsha is running too many time, where take somewhat 20 seconds...

![image](https://user-images.githubusercontent.com/45342938/233198257-39196e67-c884-4fcf-b2f8-80cc2afe806a.png)
![image](https://user-images.githubusercontent.com/45342938/233198573-7f418b10-ad93-4b78-a909-45b72b1df28a.png)

And in the AWS lightsail I have this in redis logs (with command monitor). A lot of logs per seconds:

![image](https://user-images.githubusercontent.com/45342938/233198734-abd792c9-8af5-4a9c-aee3-45e88efdb271.png)

I try to set `guardInterval` as 1000 seconds but nothing changes...

## Bull version
"bull": "^4.8.3",

**Comment by manast** [comment]
In general BullMQ is much more efficient than Bull, so I recommend you to upgrade if you can.
