### ISSUE TITLE
Why my code is not running the deleteArray(); function and not logging the array deleted how can I fix this issue with my I am trying to log in and run that function on the expiration time coming as a parameter 

### ISSUE THREAD

**Issue by xts-bit** [OptimalBits/bull#2593]
Why my code is not running the deleteArray(); function and not logging the array deleted how can I fix this issue with my I am trying to log in and run that function on the expiration time coming as a parameter 
```
import Queue from 'bull';

function scheduleDeleteUser(email, expirationTime) {
  const deleteUserQueue = new Queue('deleteUserQueue');

  deleteUserQueue.process(() => {
    deleteArray();
    console.log(' array deleted.');
  });

  deleteUserQueue.resume(); 

  const job = deleteUserQueue.add({ email }, {
    delay: expirationTime.getTime() - Date.now(),
  });

  console.log(`Job scheduled to run at ${expirationTime}.`);

  return job;
}

const email = 'email@gmail.com';
const now = new Date();
const futureTime = now.getTime() + 20000;
const expirationTime = new Date(futureTime);
console.log(expirationTime);
scheduleDeleteUser(email, expirationTime);
```

**Comment by manast** [comment]
The code you posted has a lot of issues, I recommend you start with working examples and build from there.  Since you are new to Bull please use BullMQ:  https://docs.bullmq.io/
Tons of tutorials with working code: https://blog.taskforce.sh/

**Comment by xts-bit** [comment]
@manast Can you please give me a code example? I just want to run a function on a  expiration time

**Comment by manast** [comment]
You got links with all the information you need.

**Comment by xts-bit** [comment]
@manast  nothing is working gpt is giving me a lot of useless solutions that are not working
