### ISSUE TITLE
Bounced jobs with custom jobId get stuck, can't be added again

### ISSUE THREAD

**Issue by nlochschmidt** [OptimalBits/bull#2594]
## Description

I noticed a surprising behavior of a rate limited queue with `bounceBack` set to `true` when re-using custom job ids. What I am observing is that a job that gets bounced is getting stuck and can't be rescheduled even after the rate limiting is over.

What seems to be happening is that the bounced job is removed from the `active` queue in [moveToActive-8.lua#L101](https://github.com/OptimalBits/bull/blob/909a07e27075a63b9ca178a3074b0b5c80d86355/lib/commands/moveToActive-8.lua#L101), but the job data is left in Redis. On attempting to re-add the job, it is simply checked whether the job key exists in Redis in [addJob-6.lua#L49](https://github.com/OptimalBits/bull/blob/909a07e27075a63b9ca178a3074b0b5c80d86355/lib/commands/addJob-6.lua#L49) and since it exists, nothing is done and the job isn't put into the waiting queue.

At that point the job is in no queue and therefore stuck, where I would expect the job to be getting processed. 

## Minimal, Working Test code to reproduce the issue.

```
  it('should allow process a previously bounced job with custom job id', async () => {
    const rateLimitDuration = 1000;

    const rateLimitedQueue = utils.buildQueue('test rate limiter', {
      limiter: {
        max: 1,
        duration: rateLimitDuration,
        bounceBack: true
      }
    });

    rateLimitedQueue.on('failed', e => {
      assert.fail(e);
    });

    rateLimitedQueue.process(() => {
      return Promise.resolve();
    });

    await Promise.all([
      rateLimitedQueue.add({}, {jobId: 'successful-job'}),
      rateLimitedQueue.add({}, {jobId: 'bounced-job'}),
    ]);

    await delay(rateLimitDuration + 10);

    const bouncedJob = await rateLimitedQueue.add({}, {jobId: 'bounced-job'});
    expect(await bouncedJob.getState()).to.be.oneOf(['waiting', 'active', 'completed']);

    await rateLimitedQueue.close();
  });
```

## Bull version
`4.10.4`

## Additional information

Likely related to  #1148, but I think this is still a gotcha in it's own right.

**Comment by manast** [comment]
Rate-limit in Bull leaves a lot to be desired. Honestly, I do not think I am going to dig in and investigate issues related to it since we have a much better implementation in BullMQ. If somebody wants to contribute to a fix then of course we will consider it.

**Comment by nlochschmidt** [comment]
That's fair and I am considering the switch to BullMQ for this part of the application I am working on. 

That said, if I would supply a fix I think the decision is whether to discard the job completely or do what has been outlined in #1182 and move the job back to waiting.

Do you have an opinion on this?

**Comment by nlochschmidt** [comment]
In case anyone finds this issue: We never got it to work and ended up moving to BullMQ.

**Comment by stevenolay** [comment]
> In case anyone finds this issue: We never got it to work and ended up moving to BullMQ.

Thanks! I figured bull was going to be EOL eventually and was going to miss out of these sort of bug fixes. Not surprised this wasn't remedied. Good to get confirmation from somewhen else.
