### ISSUE TITLE
job stalled more than allowable limit

### ISSUE THREAD

**Issue by TIME-GATE** [OptimalBits/bull#2601]
## job stalled more than allowable limit

HI,
Regarding `stalled`, the document explains that it is triggered only when event loop or processed crash cannot be called due to CPU intensive computing. In fact, when my job is in some high latency network strategy requests, if the execution time is greater than  `lockDuration`, it will also be marked as `stalled`. why is this? as a result of my testing, stalls are frequently generated and consumed as follows

![image](https://github.com/OptimalBits/bull/assets/16061625/82f5c770-0bf7-42ab-9422-b13665da2463)

**Comment by manast** [comment]
Jobs will not be stalled just because they take longer than ```lockDuration``` to process. If that is the case you are welcome to produce a test case that reproduces it.
