### ISSUE TITLE
how can I "fail" a job explicit?

### ISSUE THREAD

**Issue by sibelius** [OptimalBits/bull#2613]
## Description

We are using `await job.moveToFailed({ message: `error`}, true);` to move a job to failed state to trigger the exponential backoff retry policy, similar to this one https://blog.taskforce.sh/implementing-a-webhook-system-with-bullmq/

we were throwing an Error to fail the job, but we want to avoid doing this

<img width="491" alt="image" src="https://github.com/OptimalBits/bull/assets/2005841/43136978-a161-43cd-8006-d7176c693fd9">

moveToFailed is causing `missing id` for a job, and `Error: Missing process handler for job type __default__`

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

Just add `await job.moveToFailed({ message: `error`}, true);` to any job that was called with retry policy of attempts

## Bull version

"bull": "4.10.4",

## Additional information

we are using arena to debug

**Comment by manast** [comment]
I do not think this use case is supported in Bull, why don't you use BullMQ instead?

**Comment by sibelius** [comment]
we have a huge codebase using bull, we plan to migrate in the futuer
