### ISSUE TITLE
```Bull queue error: ReplyError: MOVED 4913 dev-.use2.cache.amazonaws.com:6379``` while connecting with adding and processing BULL queue

### ISSUE THREAD

**Issue by divysts** [OptimalBits/bull#2615]
I tried to run  BULL queue with aws redis cluster. But i am facing this error ```Bull queue error: ReplyError: MOVED 4913 dev-.use2.cache.amazonaws.com:6379``` while connecting with adding and processing BULL queue```<br>
I am using bull version:```"bull": "^4.10.4",``` ``` redis-Engine-version:7.0.7```

I have tried adding hash before prefix name and queue name.My attempt looks like this<br>
 ```const Queue=require('bull')
const testLayerQueue = new Queue('{my-queue}', {
    redis: {
      host: process.env.REDIS_HOST,
      port: 6379,
      password: process.env.REDIS_PWD, 
      tls: {
          servername: process.env.REDIS_HOST
        },
    },
    prefix: '{myapp}'  
  },{ settings: { lockDuration: lockDurationTime } });

**Comment by bartvanmiegem** [comment]
@divysts I'm facing the same issue. How have you fixed it?

**Comment by manast** [comment]
You need to use Redis.Cluster: https://stackoverflow.com/questions/64374113/replyerror-moved-error-after-connecting-to-redis-cluster-aws
