### ISSUE TITLE
Bug Report - High Memory Usage when Providing Float to Concurrency

### ISSUE THREAD

**Issue by abdeljalil09** [OptimalBits/bull#2619]
Description:
I encountered an issue while using the Bull.js module in Nest.js. When I provided a float value (5 / 2, which is 2.5) to the concurrency property in the processors configuration, I noticed a significant increase in memory usage.

Expected Behavior:
The concurrency value should be rounded to the nearest integer, as is the common practice in similar scenarios.

Steps to reproduce
Actual Results:
Upon providing 5 / 2 as the value for concurrency, the memory usage increases significantly, causing potential performance and stability issues.

Expected behavior
I would expect the concurrency value to be rounded to the nearest integer, resulting in a value of 3 in this case (Math.round(5 / 2)).

**Comment by manast** [comment]
I think it is better to throw an exception in this case actually.
