### ISSUE TITLE
BullMQ Sanboxed Processor Doesnt works with tsc

### ISSUE THREAD

**Issue by MrSharpp** [OptimalBits/bull#2621]
## Description
When using a typescript with bullmq, and running it with tsx, sanbox processor doesnt works.

## Minimal, Working Test code to reproduce the issue.
- worker.ts
```
const IORedis = require('ioredis')
const { Worker, Queue } = require('bullmq')
const path = require('path')

async function initQueueService() {
    const processFile = path.join(__dirname, 'job.js');

    await Q.addBulk([{ name: 1, data: {} }, { name: 2, data: {} }, { name: 3, data: {} }])

    const worker = new Worker("queue", processFile);

    worker.on('completed', () => console.log('completed'));
    worker.on('error', () => console.log('err'));
    worker.on('active', () => console.log('active'));
    worker.on('failed', err => {
        console.log(err);
    });
    worker.on('stalled', err => console.log('stalled'));
}

initQueueService()
```
- job.js
```
const fs = require('fs')
module.exports = async (job) => {
    job.log("Working from separated proccess")
    fs.writeFileSync('hello.txt', "sdfdsf")
    return Promise.resolve({ done: true })
}

```
#### (An easy to reproduce test case will dramatically decrease the resolution time.)
Run the file with tsx, it wont work. but if running the file with node. it works.

## Bull version
3.12.0

**Comment by manast** [comment]
Can you be more specific than "doesn't work"? and why do you mention .tsx in the title but then your example includes .ts ?

**Comment by MrSharpp** [comment]
@manast sorry, i meant typescript executor (tsx).
it doesn't work as my job.js is not executing and all jobs are getting stalled. but it works when i switch it to js file.
