### ISSUE TITLE
Allow done function to return error and return value object

### ISSUE THREAD

**Issue by efraimrodrigues** [OptimalBits/bull#2626]
## Description
I expected something like the following to fill in `returnValue` in the response. Would it be possible to achieve this?
```
const errors = [
  {
    title: "name",
    status: 422,
    source: '[0].name',
    code: 'number.base'
  }
];
done(new Error("Validation error while creating a user"), errors);
```
## Additional information
Please let me know if this can be achieved, but it seems that it's not possible to return an object in the `returnValue` prop if we're returning an error. This would be useful in use cases where we need more than a `failedReason` string. I know I can return it as an error message with `stringify`, but I'm not sure why it would not be possible to also use `returnValue` for details (e.g. form fields errors).

**Comment by manast** [comment]
This is not possible. I think it is good to keep returnValue as it is today, i.e. signaling that the job was completed without errors. Also, keep in mind that the processor will pick unhandled exceptions in your code and fail the job with the corresponding error object.
