### ISSUE TITLE
Is better to use `unlink` to remove jobs?

### ISSUE THREAD

**Issue by zxh326** [OptimalBits/bull#2628]
## Description

When my queue  defaultJobOptions changes from `removeOnComplete: false` to `removeOnComplete: true`, and there are a large number of completed jobs, the cleanup script will block the Redis process, causing it to not work. （We have other services using the same Redis.）

So, can we try using [UNLINK](https://redis.io/commands/unlink/) to clean up completed or any other state jobs?

This command is very similar to [DEL](https://redis.io/commands/del): it removes the specified keys. Just like [DEL](https://redis.io/commands/del) a key is ignored if it does not exist. However the command performs the actual memory reclaiming in a different thread, so it is not blocking, while [DEL](https://redis.io/commands/del) is. This is where the command name comes from: the command just unlinks the keys from the keyspace. The actual removal will happen later asynchronously.

**Comment by manast** [comment]
I am not sure UNLINK would yield better performance in this case, have you tried to change the Redis configuration to ```lazyfree-lazy-user-del yes``` so that you can test if it makes any difference? Note that you need at least Redis 6.0 for this to work: https://redis.io/docs/management/config-file/

If this does not help I would like to better understand your use case, normally you do not change often the ```removeOnComplete``` during the lifetime of a queue. If you want to remove jobs in the complete status you should use ```queue.clean(10000, "completed)```. Also, there are some performance improvements in BullMQ regarding deleting of jobs that may be beneficial for you if you can afford to upgrade.

**Comment by zxh326** [comment]
> I am not sure UNLINK would yield better performance in this case, have you tried to change the Redis configuration to `lazyfree-lazy-user-del yes` so that you can test if it makes any difference? Note that you need at least Redis 6.0 for this to work: https://redis.io/docs/management/config-file/
> 
> If this does not help I would like to better understand your use case, normally you do not change often the `removeOnComplete` during the lifetime of a queue. If you want to remove jobs in the complete status you should use `queue.clean(10000, "completed)`. Also, there are some performance improvements in BullMQ regarding deleting of jobs that may be beneficial for you if you can afford to upgrade.

`lazyfree-lazy-user-del yes` require Redis 6.0. I cannot use this feature.


My case is that I forgot to set the option `removeOnComplete: true` before the service went live. After going live, I found a lot of completed jobs, so I changed the configuration to `removeOnComplete: true`, which caused Redis to broken.

(may be set this option default is true is better)

**Comment by manast** [comment]
If it is default true then it will remove the jobs as they are completed so you should not get any issue.

**Comment by zxh326** [comment]
I'm not sure if frequent deletions will put pressure on Redis when the queue traffic is high.

**Comment by manast** [comment]
I will make some benchmarks.
