### ISSUE TITLE
CronRepeatOptions.repeat is wrongly enforcing declaration of the 'key' property in TS

### ISSUE THREAD

**Issue by reinert** [OptimalBits/bull#2642]
## Description
The 4.11 release, specifically the ([e4e6457](https://github.com/OptimalBits/bull/commit/e4e64572a3ad259d9cb90d5dec81e8565eeadca1)) commit, introduced a requirement in the `repeat` property of the `CronRepeatOptions` TS type to set a `readonly key` property. This is requiring us to declare the key property to add scheduled jobs. For example, if we try to add a job with the opts `{ repeat: { cron: "* * * * *" } }` the TS compiler will fail with the following message:

```
error TS2322: Type '{ cron: string; }' is not assignable to type '((CronRepeatOptions | EveryRepeatOptions) & { readonly key: string; }) | undefined'.
  Type '{ cron: string; }' is not assignable to type 'CronRepeatOptions & { readonly key: string; }'.
     Property 'key' is missing in type '{ cron: string; }' but required in type '{ readonly key: string; }'.
```

According to the documentation this property is not set by the user, but by Bull. So this type declaration should be modified to conform with the documentation.

## Minimal, Working Test code to reproduce the issue.
Try sending a scheduled job without the key property in TS and the compilation error will appear.

## Bull version
4.11

## Additional information
Introduced by this commit:
> **types**: add missing keys to repeat opts ([e4e6457](https://github.com/OptimalBits/bull/commit/e4e64572a3ad259d9cb90d5dec81e8565eeadca1))

**Comment by Addono** [comment]
From what I gather, the `key` is simply generated here:
https://github.com/OptimalBits/bull/blob/dab0d8266174f1d25ec914cff8450594d85db511/lib/repeatable.js#L41

Before it's set on the scheduled job: 
https://github.com/OptimalBits/bull/blob/dab0d8266174f1d25ec914cff8450594d85db511/lib/repeatable.js#L65

**Comment by KyleBrown-804** [comment]
Running into the same issue

**Comment by manast** [comment]
Le me know if the fix solves the issue.
