### ISSUE TITLE
`removeOnComplete` not working with only "age" key

### ISSUE THREAD

**Issue by jvcmanke** [OptimalBits/bull#2646]
## Description

I am currently running some tests to check if this library fits my use-case well, and I really like it so far.
However I am having trouble setting up the `removeOnComplete` feature with the `KeepJobs` option of `age`, it seems to not remove ever.

I have tested with the `removeOnComplete` option set to `true` and it is removed after completion as expected.

## Minimal, Working Test code to reproduce the issue.

I am running two separate processes one as a producer and one as the consumer:
```javascript
// producer.js
const Queue = require("bull");

const queue = new Queue("myqueue", "redis://....");

async function createJob() {
  const job = await queue.add(
    { message: "Hello" },
    { removeOnComplete: { age: 5 } }
  );
  console.log("Created!");

  const jobId = job.id;
  let count = 0;
  const intervalId = setInterval(async () => {
    const fetchedJob = await queue.getJob(jobId);
    if (fetchedJob) {
      console.log(
        count++,
        fetchedJob.id,
        fetchedJob.returnvalue,
        await fetchedJob.isCompleted()
      );
    } else {
      console.log(count++, "didn't find");
      clearInterval(intervalId);
    }
  }, 1000);
}

createJob();
```

```javascript
// consumer.js
const Queue = require("bull");

const queue = new Queue("myqueue", "redis://....");

function delay(ms) {
  return new Promise((resolve) => {
    setTimeout(() => resolve(), ms);
  });
}

console.log("Running...");
queue.process(async (job) => {
  console.log(job.data);

  await delay(3000);

  return { message: "World!" };
});
```

You can run them on a console with `node consumer.js` and `node producer.js` 

The idea here is:
- In the producer:
  - We add a message to the queue (with `removeOnComplete = { age: 5 }` );
  - Call a function every 1 second fetching the job via its ID;
  - Log some information (Job ID, Response, isCompleted);

- In the consumer:
  - We consume the message from the same queue;
  - Wait for 3 seconds;
  - Respond with a response object;

What I expected to see:
1. Send de message;
2. Find it with status not completed for around 3 seconds;
3. Find it with status completed and response for around 5 seconds;
4. Not find it anymore;

On the producer's console should result:
```
0 8 null false
1 8 null false
2 8 null false
3 8 { message: 'World!' } true
4 8 { message: 'World!' } true
5 8 { message: 'World!' } true
6 8 { message: 'World!' } true
7 8 { message: 'World!' } true
8 didn't find
```

However it keeps "finding" the Job indefinitelly.
```
0 8 null false
1 8 null false
2 8 null false
3 8 { message: 'World!' } true
4 8 { message: 'World!' } true
5 8 { message: 'World!' } true
6 8 { message: 'World!' } true
7 8 { message: 'World!' } true
8 8 { message: 'World!' } true
9 8 { message: 'World!' } true
10 8 { message: 'World!' } true
11 8 { message: 'World!' } true
12 8 { message: 'World!' } true
...
```
## Bull version

v4.11.3

**Comment by Jurajzovinec** [comment]
Just noting this feature is not working with `removeOnFail` in version Bull version `4.8.4`.

**Comment by manast** [comment]
We have tests for this feature here: 
https://github.com/OptimalBits/bull/blob/4d197e81771df115d6af3f2d66b3797ed680d97c/test/test_queue.js#L734

**Comment by philWeroad** [comment]
Guys also in the latest version (4.12.2) the `{age: x}` is not working.
The related redis key has no TTL.

At the moment, these configurations are equals, as `age` is not working
- removeOnFail: 50 (persist last 50 jobs)
- removeOnFail: { age: 1200, count: 50 }

The same issue can be found for the `removeOnComplete` configuration.

**Comment by manast** [comment]
As explained elsewhere, age is enforced lazily. Removing a job requires some bookkeeping, it is enough just setting TTL on a key.

**Comment by philWeroad** [comment]
@manast "it is enough just setting TTL on a key" how this can be done? Besides the "age" parameter I don't see anything else that could be used by bull to set the redis key ttl

**Comment by manast** [comment]
I did update the comment, I omitted NOT in the phrase.

**Comment by manast** [comment]
So TLDR; it is working as designed.  You can find some tests for this functionality here: https://github.com/OptimalBits/bull/blob/develop/test/test_queue.js#L751

**Comment by philWeroad** [comment]
@manast ok, so when the keys marked with `age` option are deleted? Should be called a bull method or something else?

**Comment by JSEvgeny** [comment]
Should this be re-opened? The issue is still there, setting up `removeOnComplete: { age: 60 }` doesn't work, only `removeOnComplete: true`

EDIT:

> They are deleted when new jobs are processed and the old ones have reached the maximum age.

So this won't work if you only have a few users testing new queue, other than that, the statement above is correct, so it kinda works😅

**Comment by manast** [comment]
It works lazily as mentioned in several places. If you need to remove all the data in a queue you should use the "obliterate" function: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueobliterate

**Comment by xtrinch** [comment]
@manast This should still be considered as an additional feature, to NOT work lazily as I do believe most people would expect this functionality to work that way

**Comment by manast** [comment]
@xtrinch if such new feature would be added it would be on BullMQ as Bull is only in maintenance mode now...

**Comment by manast** [comment]
> @manast This should still be considered as an additional feature, to NOT work lazily as I do believe most people would expect this functionality to work that way

BTW, to make it not lazily, in the sense that old jobs would automatically be removed would only work if you still had a worker instantiated and running. Most people could also believe that the jobs would just be removed automatically even without having a worker running in the background... there can be a lot of expectations but sometimes we must keep then in line with what is actually possible to achieve.

**Comment by xtrinch** [comment]
Yeah, ofcourse, when working on own implementation of non-lazy deletion one needs to keep a worker running too, I don't see how people could expect otherwise

**Comment by manast** [comment]
They do because they think BullMQ could use Redis TTL (https://redis.io/docs/latest/commands/expire/)
