### ISSUE TITLE
[BUG] Negative Assertions in event callbacks are swallowed

### ISSUE THREAD

**Issue by rook2pawn** [OptimalBits/bull#265]
```
  var assert = require('assert')
  var bull = require('bull')

  var q = bull('myqueue',6379,'localhost')
  q.process(function(job,done) {
    var data = job.data;
    done(null,{data:data})
  })
  q.on('completed', function(job,result) {
    console.log("complete job :", result)
    assert.ok(false)
    // some piece of promise logic doesn't resolve correctly and now the queue is unusable.
  })
  q.add({foo:'bar'})
```

The assertion assert.ok(false) should  throw AssertionError: false == true
but instead the queue literally dies without exposing an exception. This means you can't write assertions at all for test coverage either in the .process working function or any of the event callbacks.

**Comment by bradvogel** [comment]
This is happening because the exception is being silently swallowed here:
https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L567

If you change that line this (for debugging):
```
    .then(this.processJobs, function(err) {
      console.log('error!', err);
      this.processJobs();
    });
```

the error is reported.

The fix here is that the Promise chain should rethrow exceptions.
