### ISSUE TITLE
How do I update a processor function?

### ISSUE THREAD

**Issue by oyatek** [OptimalBits/bull#2651]
How do I update a processor function? As I can see, if I update the code of the processor function and restart the server, the Bull Queue still uses the old code of the processor. If I restart the queue-init function (by calling an API endpoint) a new instance of Bull starts (right?) and then I have 2 instances running in parallel - one is using old processor code, one is using the new code. How can have always only 1 instance of Bull running that uses the latest version of the processor function?

**Comment by 0xNima** [comment]
> How do I update a processor function? As I can see, if I update the code of the processor function and restart the server, the Bull Queue still uses the old code of the processor. If I restart the queue-init function (by calling an API endpoint) a new instance of Bull starts (right?) and then I have 2 instances running in parallel - one is using old processor code, one is using the new code. How can have always only 1 instance of Bull running that uses the latest version of the processor function?

I have the same issue. Spend two days to fix the bug that stems from this issue :|

**Comment by manast** [comment]
If you change the processor code then you need to update all the instances using the new code, this is not special for Bull, this is how any other platform works, including NodeJS.
