### ISSUE TITLE
stalledInterva set to 0, an error occurs

### ISSUE THREAD

**Issue by wangkunmeng** [OptimalBits/bull#2672]
## Description

```ts
import Bull from 'bull';
import { setTimeout } from 'timers/promises';
import { randomUUID } from 'crypto';
import moment from 'moment';

const queue = new Bull('running-stalled-job-' + randomUUID(), {
    redis: { port: 6379, host: '127.0.0.1' },
    defaultJobOptions: {
        attempts: 2,
        removeOnComplete: true,
        removeOnFail: true
    },
    settings: {
        lockRenewTime: 2500,
        lockDuration: 2500,
        stalledInterval: 0,
        maxStalledCount: 1
    }
});

queue.process((job) => {
    console.log(moment().format('HH:mm:ss'), JSON.stringify(job.toJSON()));
    return setTimeout(5000);
});

queue.add({ foo: randomUUID() });

```
![image](https://github.com/OptimalBits/bull/assets/17898858/6e47b567-47af-47ef-a1f2-4e204cdd3852)
![image](https://github.com/OptimalBits/bull/assets/17898858/0c0218a0-572c-46bf-a598-56029c4e018f)
![image](https://github.com/OptimalBits/bull/assets/17898858/a482ca35-c426-436a-ac4b-854611846a8a)
![image](https://github.com/OptimalBits/bull/assets/17898858/296774b2-653b-45bc-b88b-b2751717aa4e)

## Bull version
4.11

**Comment by manast** [comment]
We can thrown an exception here, but 0 will never be a valid setting for stalledInterval.

**Comment by arimgibson** [comment]
@manast it's listed in the documentation as 0 meaning it'll never check. That might be something to update; there's been several updates with confusion about that
