### ISSUE TITLE
A Date Object is converted to a string between producing and consuming

### ISSUE THREAD

**Issue by oguera** [OptimalBits/bull#2681]
## Description

The `Date` type changes between adding to the queue and consuming from the queue.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

I'm using nestjs with a default (from the docs) setup:

```
interface SomePayload {
   foo: Date
}

export class FooClass {
  constructor(@InjectQueue('queue-name') private someQue: Queue)

  someFunction(payload: SomePayload) {
      console.log(typeof payload.foo)
      // prints object
      someQue.add(payload)
  }
}
```

```
@Processor('queue-name')
export class QueueProcessor {
  @Process()
  processQueue(job: Job<SomePayload>) {
    console.log(typeof job.data.foo)
    // prints string
  }
}
```
## Bull version
"@nestjs/bull": "10.0.1"
"bull": "4.11.5",

## Additional information

I found a closed PR with the same problem here: https://github.com/OptimalBits/bull/pull/2501

**Comment by manast** [comment]
As the data is serialized using JSON, it is not possible to serialize it back to a date unfortunatelly. Try this:
```ts
JSON.parse(JSON.stringify(Date()))
```

**Comment by kevelopment** [comment]
But if the data is being serialized when a Job is written into the Queue, why shouldn't it be possible to de-serialize it when the Job is being picked up? 
i.e. the `JSON.parse(payload)` you suggested should be applied to the payload right before the `process` Callback is invoked. Is this just not intended by design or why exactly is it "not possible to serialize it back to a date"?

**Comment by manast** [comment]
JSON does not support dates, so it is not possible, unless we used a different serialization method.

**Comment by oguera** [comment]
@manast after researching the issue a bit i found the `reviver` parameter in `JSON.parse()`. It looks like this would be a good way to handle Dates better, what do you think about that?

Refs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#reviver

**Comment by manast** [comment]
If you know that a certain field will be a date, then you could easily handle the json parsed string representing a date, it does not provide a lot of value to expose the reviver callback. Also, we are not adding new features to Bull, as it has reached EOL.

**Comment by oguera** [comment]
Fair enough.

> Also, we are not adding new features to Bull, as it has reached EOL.

Can you point me to the point where this is announced? I can't find anything regarding this in the repo or documentation :(

**Comment by manast** [comment]
https://github.com/optimalbits/bull#-news-and-updates
