### ISSUE TITLE
Reusable redis connections with node-redis and not with ioredis package

### ISSUE THREAD

**Issue by P4yBill** [OptimalBits/bull#2690]
## Description
Hello! This is not an issue, its more like an informative question. 
We are currently using [node-redis](https://github.com/redis/node-redis) package in a project and not [ioredis](https://github.com/redis/ioredis).

I was [this](https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#reusing-redis-connections) pattern in docs for reusing redis connections but i have not found a way to do it with `node-redis` package. 
Is there a way that i can reuse redis connections with `node-redis` package?
## Bull version
3.29.3

**Comment by manast** [comment]
The differences between the Redis and IORedis packages are too large to make them interchangeable. So only IORedis is supported.
