### ISSUE TITLE
node_redis complaining about .end() call

### ISSUE THREAD

**Issue by nibblesnbits** [OptimalBits/bull#271]
When I call `close()` on my bull queues, I'm getting complaints from `node_redis` that the `end()` function without the `flush` parameter will throw soon.  After reading the docs, it seems passing `false` would be sufficient, but I'm curious what you think about the cleanest way to do this.  [This](https://github.com/NodeRedis/node_redis#clientendflush) bit from the docs suggests using `quit()` instead, but that waits for all requests to process.  I'll make the change if someone has a suggestion on which is best.

**Comment by manast** [comment]
This is actually a very interesting remark. It seems as quit is a much stabler way to close a redis connection, so I will make some experiments to see if I can make the unit tests more stable by using them.

**Comment by manast** [comment]
I made an improvement in a separate branch https://github.com/OptimalBits/bull/commit/c78a5d956cb56244d05fae39698d1901cdd1891c
Unfortunately unit tests are not passing so well...

**Comment by nibblesnbits** [comment]
I just ran the unit tests against just that branch without your changes and `node_redis` is losing its mind with deprecation warnings.  We've got a lot of work to do...

**Comment by manast** [comment]
I will look into those warning during the week, it seems as a good starting point to figure out why tests are failing so much. Btw, you are welcome to chat in gitter with the rest of the bull community: https://gitter.im/OptimalBits/bull?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by BridgeAR** [comment]
`end` should practically not be used at all in production, if you are not certain, that you do not care about any still running command. This function was meant for testing purposes and not for being used as the normal method to end the connection. If you use `end(false)` all still running commands are just ignored and the callback won't be called anymore. Only new commands after the function call are rejected.
Using `end(true)` is going to call the callback of all still running commands and rejecting them with a error that you did not wait for the reponse to return.

You might want to just add a stacktrace to the printed warnings on your local machine to find the origins of the calls faster (you can do so by inserting: `msg = msg + '\n' + new Error().stack.split('\n').splice(x).join('\n')` in the warn function, where x is the number of lines that you want to ski)p. Running mocha should print valuable stack traces in that case.

**Comment by manast** [comment]
fixed in https://github.com/OptimalBits/bull/tree/v1.0.0-rc
