### ISSUE TITLE
spawn timeout 

### ISSUE THREAD

**Issue by UROjQ6r80p** [OptimalBits/bull#2714]
Hi,

I've read that in bull behind the scenes `spawn` is used for sandboxed scripts, but spawned script is not terminated based on `timeout` option.
node.js since version 14 supports `timeout` natively for child processess, so can't it be used internally to completely terminate script?

https://nodejs.org/api/child_process.html#child_processspawncommand-args-options

**Comment by manast** [comment]
Even if it was possible, it would be quite an ungraceful way to close a processor I think. In any case we are not implementing new features in Bull, active development is on BullMQ: https://github.com/taskforcesh/bullmq
