### ISSUE TITLE
The 'settings.maxStalledCount' does not work

### ISSUE THREAD

**Issue by karimdavoodi** [OptimalBits/bull#2718]
## Description
Job re-start only one time in a stalled state. No matter what, you set it to `maxStalledCount`.
## Bull version
4.10.4

**Comment by manast** [comment]
Yes, it is used: https://github.com/OptimalBits/bull/blob/develop/lib/commands/moveStalledJobsToWait-7.lua#L14
And there are several tests for this setting, take a look at the test files.

**Comment by karimdavoodi** [comment]
Thank you for quick response,
Yes, it works. My environment had a wrong config!
I work with a same queue in two different containers, First container submits a job, Second one process the job. I was setting queue config in the first container and it did not work. Now I set it the worker container and it works.
