### ISSUE TITLE
Reusing redis connection for bull v4+, outdated doc?

### ISSUE THREAD

**Issue by DavideViolante** [OptimalBits/bull#2720]
## Description
Hello, I'd like to know if [this doc](https://github.com/OptimalBits/bull/blob/master/PATTERNS.md#reusing-redis-connections) is outdated because since bull v4 the breaking change says that these 2 redis options are now compulsory:
```
{
  maxRetriesPerRequest: null,
  enableReadyCheck: false
}
```
In the doc it just passes the `REDIS_URL` in the `new Redis()`. Does it need also the other 2 options?

## Bull version
4.12.2

**Comment by manast** [comment]
I think you may mixing Bull and BullMQ. The options you name are compulsory in BullMQ not in Bull.

**Comment by DavideViolante** [comment]
I'm quite confused. The doc I linked is bull, correct? bullmq is another repo?! The [release notes](https://github.com/OptimalBits/bull/releases?page=5) and [changelog](https://github.com/OptimalBits/bull/compare/v3.29.3...v4.0.0) are about this repo, not bullmq. The 4.0.0 breaking changes says, for bull:
`If redis opts are missing: { maxRetriesPerRequest: null, enableReadyCheck: false } then a exception will be thrown.`

**Comment by manast** [comment]
Ah ok, I forgot we also backported this requirement to Bull, sorry for the oversight. Most likely we will not update the docs as we are putting all our efforts on BullMQ these days though.

**Comment by DavideViolante** [comment]
I made a PR to update that file. I think it's totally safe to merge if the text is correct.
