### ISSUE TITLE
Strange job ID: 1e+8

### ISSUE THREAD

**Issue by kulakowka** [OptimalBits/bull#2745]
Hi all!
Here is a screenshot from our admin panel. Here you can see that one of the jobs has an ID that looks like **1e+8**; It's quite strange. I'm not sure if this somehow affects performance. I just decided to draw your attention.

<img width="479" alt="image" src="https://github.com/OptimalBits/bull/assets/557190/95256b7d-a180-4c93-b5c6-40f964bda541">

We create and process a huge number of jobs. And apparently they have reached some limit.

We use bull version:
```json
"bull": "^4.8.1",
```

**Comment by manast** [comment]
Maybe a bug in your admin panel?

**Comment by kulakowka** [comment]
Maybe. We use GraphQL on our backend. This is probably due to type casting. 

<img width="378" alt="image" src="https://github.com/OptimalBits/bull/assets/557190/a804715f-9734-4cde-b69b-1bfaa1a716e8">

This probably happens when the value is cast to a `String` type. Interesting behavior :) Looks like this is a problem on our side. Thanks for the help.
