### ISSUE TITLE
Bull parallel processing issue

### ISSUE THREAD

**Issue by devashishg** [OptimalBits/bull#2747]
There is one case we observed in our application, a job on parallel threads was removed and processed, and then on completion of the job, it was not deleted despite `removeOnComplete` being true.
- at `15:35:31.076` Job has been removed,
- at `15:35:31.098` Job process executed
- at `15:35:31.126` Job was completed. (job data received in callback was an empty object)

In the end, redis had these two keys
1. completed sorted set with this jobId,
2. Job Hash object with `{processedOn: 15:35:31.078, finishedOn: 15:35:31.099, returnvalue: {}}`

Now onwards all the jobs we try to add with the same jobId, it does not work.

Someone, please explain what went wrong here! 
doesn't the lock prevent these parallel executions?

**Comment by roggervalf** [comment]
Hi @devashishg, which version are you using?

**Comment by devashishg** [comment]
@roggervalf 
4.10.4

**Comment by manast** [comment]
@devashishg do you have a minimal example that reproduces the issue?
