### ISSUE TITLE
Memory Leaks With Large Queue

### ISSUE THREAD

**Issue by ghprod** [OptimalBits/bull#277]
Hi, 

I have some problem, my queue is huge, more than 8000 job, and each job making some HTTP request and parsing it (for single job, memory usage is little).. for beginning it consumes little memory, but then memory keeps increasing until my node app gets killed

I have no idea why its happen, is it normal with that large queue? Or maybe I need to do something to release some memory after the job completed? Maybe call `Queue.clean(10000)` ?

Below is my piece of code

```js
var adsListingQueue = Queue('adsListingQueue', config.redis.port, config.redis.host)

adsListingQueue.process(config.concurrency.getAdsListing, function (job, done) {
    var url = urijs(program.url)

    var page = job.data.page

    if (page > 1) {
        url.addQuery({
            page: page
        })
    }

    rp({
        uri: url.toString(),
        headers : {
            'User-Agent': randomUserAgent()
        },
        transform: function (body) {
            return cheerio.load(body)
        }
    })
        .then(function ($) {
            // just simple parsing with cheerio

            done()
        })
        .catch(function (err) {
            done(err)
        })
})

_.each(_.range(1, 500), function (item) {
    adsListingQueue.add({page: item})
})
```

And my vps spec is 2 core with 512 RAM

Thanks

**Comment by manast** [comment]
You are welcome to see if my patch resolved your problem.

**Comment by ghprod** [comment]
Hi @manast ..

Thanks for your updated ;)

Since you are not release yet, so  do i need to put something like this in my package.json?

```json
"dependencies": {
  "package": "git://github.com/username/package.git#commit"
}
```

Thanks

**Comment by ghprod** [comment]
I'm sorry, I'm forgotten to say that my app.js have two queues with same logic as above (Http Request > Parsing)

When I'm using only one queue, memory usage is pretty stable, but when two, then memory gets busted :(

Thanks

**Comment by manast** [comment]
you may be leaking memory on your own processing function.

**Comment by manast** [comment]
You can use this: https://github.com/lloyd/node-memwatch

**Comment by ghprod** [comment]
@manast yes seems like that :)

Thanks for your suggestion.. close this issue :)

:+1: 

Great job :100:
