### ISSUE TITLE
1.0.0-rc1: Queue.close() does not resolve

### ISSUE THREAD

**Issue by nibblesnbits** [OptimalBits/bull#278]
Demo:

``` js
"use strict";

const Queue = require("bull");
const process = require('process');

const resultQueue = Queue('testqueue', 6379, '');

function end() {
    return resultQueue.close().then(() => {
        process.exit(0);
    });
}

resultQueue.count().then(count => {
    console.log(count + ' jobs');
}).then(end)
.catch(err => {
    console.error(err.message, err);
    end();
});
```

I'm still trying to track down where/why, but it seems since 1.0.0-rc1, calling `close()` does not resolve, and causes this code to hang.  From following it a bit, the `close()` function (in this case) is now calling `pause()`, but this is the bit that never resolves.

**Comment by manast** [comment]
it works perfectly for me... Although I changed it to this (using node 0.12.12):
```javascript
const Queue = require("../");
const resultQueue = Queue('testqueue', 6379, '');

function end() {
    return resultQueue.close().then( function() {
        process.exit(0);
    });
}

resultQueue.count().then(function(count) {
    console.log(count + ' jobs');
}).then(end)
.catch( function(err) {
    console.error(err.message, err);
    end();
});
```

**Comment by nibblesnbits** [comment]
You're using 1.0.0-rc1 for this?  I just switched to node 0.12.12 and confirmed that bull version and your code above hangs for me still.  :(

On a side note, I'm not sure why your first line compiles: `const Queue = require("../");`
Is that because in your case that file is within the `bull` project?

**Comment by manast** [comment]
yes I am running it locally from the dev version of bull, you can try with master version to see if the issue is still there.

**Comment by nibblesnbits** [comment]
Just ran it from a freshly pulled master branch. Same problem.  I'll dig into it more and see what other info I can devise.
