### ISSUE TITLE
Possible leak, to be verified

### ISSUE THREAD

**Issue by MySidesTheyAreGone** [OptimalBits/bull#280]
I'm seeing my app occupy more and more memory over time while it (and Bull) is doing nothing at all. Queues have been started, but are empty. Nothing is being processed at all. So I ran node-inspector to try and see what's up and apparently more and more promises are being made over time:

![WAT](http://i.imgur.com/JHMqaAc.png)

So, from the bottom up; app.pluginRegistry.pipelines.reddit_messages is my own stuff. reddit_messages has a `queue`, which is a Bull instance:

```js
    try {
        this.queue = Queue(this.name, {redis: {host: config.redisHost, port: config.redisPort}});
        this.queue.process(1, (job) => this.process(job));
        this.queue.on('error', (e) => this.handleFatalError(new errors.DataPipeline(errPrefix, null, e)));
    } catch (e) {
        this.handleFatalError(new errors.DataPipeline(errPrefix, null, e));
        return;
    }

    this.queue.resume();
```

Not really doing anything strange that I can see. `this.process` hands a Promise back, but it's not being called because the app is just sitting there, idling.

Back to the node-inspector, we get to Bull's bclient, a command_queue that I know nothing about and then you can see this unbelievable chain of promises attached to each other by the rejection handler. Apparently, and I may be wrong, these chains just keep getting longer and longer. This would eventually eat up all of the memory (which it does). When I diff two consecutive heaps I see hundreds and hundreds of new promises every time.

I admit I may be in over my head since I'm kind of a noob, but the heap probably doesn't lie; and there's nothing I'm doing with bclient or anything internal to Bull. My app does have its own connection to redis, but for this test I took care to use the same version Bull uses. I promisify it in the same exact way Bull does. We use the same Bluebird version too.

Obviously you can't debug my app, but has any of you observed this behaviour before? Any idea might help me dig myself out of this ditch.

Thanks!

**Comment by manast** [comment]
Are you using the latest version (1.0.0-rc1) ? because we made a fix that should break that promise chain that you are experiencing.

**Comment by MySidesTheyAreGone** [comment]
Woah you're fast :) Yep, straight from the package.json: "version": "1.0.0-rc1". Bull doesn't have its own node_modules directory so we're sharing all of the dependencies too.

**Comment by manast** [comment]
ok, thats worrying, I will investigate this further, It believe the leak is in bull.

**Comment by MySidesTheyAreGone** [comment]
Thank you very much. Let me know if I can help in any way, although I'm in the Italian timezone so I'm going to collapse on the bed right now.

**Comment by MySidesTheyAreGone** [comment]
Minimal test case:

```js
var Queue = require('bull');

var test = new Queue('testq');
test.process(1, (job) => console.log(job.data));

test.resume();
```

With this it takes a little while; just wait a few minutes between snapshots and you'll see it happen. You don't need to put anything into the queue.

**Comment by MySidesTheyAreGone** [comment]
It looks like this promise chain is getting longer and longer and longer by calling itself within a handler (I mean `then`, not the error handler):

```js
Queue.prototype.processJobs = function(){
  var _this = this;

  if(this.closed){
    return this.closed;
  }

  return (this.paused || Promise.resolve())
    .then(this.getNextJob)
    .then(this.processJob)
    // Avoid https://github.com/OptimalBits/bull/issues/243
    .then(this.processJobs, function(err){
      console.error(err);
      return _this.processJobs;
    });
```

After the following modification (which may be horrible programming practice, remember as I said I'm a n00b) the memory seems to go up and down normally, although for some reason it breaks node-inspector (maybe I'm just doing something stupid):

```js
Queue.prototype.processJobs = function(){
  var _this = this;

  if(this.closed){
    return this.closed;
  }

  return (this.paused || Promise.resolve())
    .then(this.getNextJob)
    .then(this.processJob)
    // Avoid https://github.com/OptimalBits/bull/issues/243
    /*.then(this.processJobs, function(err){
      console.error(err);
      return _this.processJobs;
    });*/
    .then(function() {
        process.nextTick(_this.processJobs);
        return null;
    }, function(err){
      console.error(err);
      return _this.processJobs;
    });
};
```

I'm letting the app run and monitoring the memory usage with htop, but I'm not noticing any "leaks" so far. I've now started monitoring with syrupy, I'll let you know if it uncovers anything.

This may not be the correct solution and I may be doing something stupid by messing around with `nextTick` but hopefully I've saved you a little time!

**Comment by manast** [comment]
Yes, I implemented the nextTick solution yesterday but I could not verify it just yet that it worked. At lest performance wise the benchmark did not got affected by this change which is a good thing.

**Comment by MySidesTheyAreGone** [comment]
Oh I got the right spot? Nice, I'll monitor the app for an hour or so, let's see how it holds up.

**Comment by manast** [comment]
I have pushed my fix, similar to yours, if you can verify that the memory leak is gone I could make a new release.

**Comment by MySidesTheyAreGone** [comment]
Oh ok, I'll pull master and let you know later.

**Comment by MySidesTheyAreGone** [comment]
It's rock stable at ~82 MB, which is just fine. Works for me. And again thank you so much for being so quick.

**Comment by bradvogel** [comment]
This can be closed?

**Comment by MySidesTheyAreGone** [comment]
Works for me, but I though it would be better to let the mainteiners choose when to close it.
