### ISSUE TITLE
node_redis deprecation messages #2

### ISSUE THREAD

**Issue by kzima** [OptimalBits/bull#281]
I get bunch of depreciation messages when running Bull version 1.0.0-rc1.

node_redis: Deprecated: The SET command contains a "undefined" argument.
...
node_redis: Deprecated: The GET command contains a "undefined" argument.
...
node_redis: Deprecated: The DECRBY command contains a "undefined" argument.
...
node_redis: Deprecated: The INCRBY command contains a "undefined" argument.

Relates to #272

**Comment by manast** [comment]
Can you add some code that reproduces this? because an effort was made for 1.0.0.rc1 to fix all this issues, I have not been able to reproduce them since them.

**Comment by kzima** [comment]
I cleaned node_modules, restarted server and all errors are gone now. My mistake.
Good job!
