### ISSUE TITLE
[Error: Missing Job 13 when trying to move from active to completed]

### ISSUE THREAD

**Issue by MySidesTheyAreGone** [OptimalBits/bull#282]
I have a cleanup job running every 5 minutes. This is all it does:

```js
return Promise.all([
    this.queue.clean(0, 'completed'),
    this.queue.clean(0, 'failed')
]);
```

I don't have any other code that could possibly remove jobs. I'm running master because of that leak you fixed. Concurrency is 4.

Any idea what could be causing this error? If it doesn't look like I'm doing something wrong with `clean` I can try to isolate a test case.

**Comment by manast** [comment]
strange actually, as if the job would have been deleted before being moved to completed which should be impossible to happen...

**Comment by MySidesTheyAreGone** [comment]
Yeah that's what I thought. As long as the promise returned by my processing function resolves there shouldn't be any problem with the job workflow right? And I'm not deleting anything on my own. I'll try to find that test case, I don't think I'm giving you enough to figure this out.

**Comment by MySidesTheyAreGone** [comment]
I can't find a test case, for now I'm closing this.
