### ISSUE TITLE
node_redis throws depreciated EVALSHA error when restarting a Redis instance

### ISSUE THREAD

**Issue by bencooling** [OptimalBits/bull#286]
I'm getting the following error with Redis version 3.0.7 and 2.8.23.

I'm a little confused as what to expect from Bull if Redis becomes unavailable for any period of time; if I follow the steps listed below node_redis throws, the job isn't added into Redis and no failed event is fired by Bull?

1) Start Redis
2) Add a job
3) Stop Redis
4) Add a job
5) Restart Redis

```
node_redis: Deprecated: The EVALSHA command contains a argument of type OperationalError.
This is converted to "Error: NOSCRIPT No matching script. Please use EVAL." by using .toString() now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
{ [Error: ERR value is not an integer or out of range]
  cause: { [Error: ERR value is not an integer or out of range] command: 'EVALSHA', code: 'ERR' },
  isOperational: true,
  command: 'EVALSHA',
  code: 'ERR' }
```

**Comment by manast** [comment]
Regarding the warning with evalsha, I think this should be discussed with the node redis team, it is quite standard to try to use evalsha without knowing if the script is cached or not.
I am not sure what would be the correct behaviour if redis is unavailable, depends also how node redis handles it.

**Comment by bencooling** [comment]
Cool thanks.

**Comment by defunctzombie** [comment]
@manast @bencooling is there a workaround to this? Causes my node to fail on bootup (if redis isn't quite ready cause of docker-compose start order). Can I make Bull queue retry-connections?

**Comment by bencooling** [comment]
@defunctzombie I personally moved on to [Kue](https://github.com/Automattic/kue) as it doesn't have this problem. But to your issue of loading dependencies in docker-compose check out this thread [Docker Compose wait for container X before starting Y](http://stackoverflow.com/a/35170810/213435).

**Comment by manast** [comment]
@defunctzombie bull already retries, this is builtin in node-redis, but I think we introduced a bug when we implemented script caching, which seems to fail when redis is not online. I will mark this as a bug and fix it as soon as I can.
@bencooling kue is a great queue, but many users of bull (myself included obviously) have had issues with stalled queues that could only be fixed by manually removing jobs in redis, etc. Also the performance is much worse than bull, if thats something important for your usecase or not is a different story.

**Comment by defunctzombie** [comment]
I don't want to switch to kue as I too have experienced these issues in the past. My two gripes with bull so far are this startup/crash issue (would really like a workaround) and the double delivery of messages to my workers (this is more scary and I don't understand why it is happening).

**Comment by defunctzombie** [comment]
@manast is there a workaround for the EVALSHA issue?

**Comment by manast** [comment]
I am working on a fix.

**Comment by bencooling** [comment]
@manast Is there anywhere I can read up on these issues with Kue, the experiences of those who have more involvement in the area is invaluable to people like myself trying to make a decision on which project to adopt.

**Comment by manast** [comment]
You should be able to find it if you browse on kue issues. I had the link before but removed it because  I don't want to spread bad karma about other projects. Benchmarks you can find on the heavily bull based https://github.com/LewisJEllis/bee-queue. On bulls latest version we are at par with it.

**Comment by manast** [comment]
Btw, you could try ```queue.on('error', function(err) {})``` to see if the error can just be skipped without any harm for the queue.

**Comment by defunctzombie** [comment]
@manast I tried `queue.on('error'` as on the the first things but that didn't help as far as I could tell. Maybe it did and I didn't notice.
