### ISSUE TITLE
PriorityQueue.process does not support concurrency parameter

### ISSUE THREAD

**Issue by hulbert** [OptimalBits/bull#287]
This seems to be undocumented and I would assume its process method would behave the same, but it appears it does not take a concurrency parameter as the first argument like Queue#process does.

Happy to submit a PR with some guidance about direction—I am surprised it's not some sort of subclass?

**Comment by manast** [comment]
A priority queue in bull is composed of several standard queues. The concurrency is a new functionality in the standard queues and has not yet been implemented on the priority queues.

**Comment by ekristen** [comment]
Any idea if this will get implemented? I could really use concurrency on priority queues. Thanks.

**Comment by manast** [comment]
This function should not be so difficult to implement, its just a matter of passing the concurrency parameter to the underlying queues when instantiating a priority queue. So a PR for this would be welcomed :)

**Comment by emhagman** [comment]
@manast Any idea if this has been implemented or if I should submit a PR?

**Comment by manast** [comment]
the code for priority queue needs some extra love after so many changes on the standard queue. So please feel free to make improvements regarding concurrency. I can help you if you need hints or info.

**Comment by manast** [comment]
Priorities are now supported on the standard queue and the priority queue since been deprecated.
