### ISSUE TITLE
Stuck jobs in waiting list

### ISSUE THREAD

**Issue by igorissen** [OptimalBits/bull#288]
Hi,

I'm having a strange issue with some jobs stuck on the waiting list for a queue. I need to restart the worker to able to process all stuck jobs.

This is my process:

* receive a request to update a show information
* create a job with show ID
* when the job is done processing, it create multiple jobs to update all episodes of a show
* all jobs to update the episodes of the show are stuck

So after some hours I have 1000+ jobs stuck, waiting to be processed.

Any idea where to look at to fix this issue ?

```
nodejs: v5.10.1
redis: v3.0.7
bull: v1.0.0-rc1
```

**Comment by manast** [comment]
The best is if you can write a simple example that reproduces the issue... we have not any know issue about jobs being stuck otherwise.

**Comment by igorissen** [comment]
@manast I will try to reproduce this bug with the same data in a sample project.

**Comment by igorissen** [comment]
@manast I have not been able to reproduce the bug. I have created an [example](https://gist.github.com/igorissen/ecddcc49aa56ddd995556926410aa2b7).

Is the use of a single redis database (db0) with multiple applications (so multiple queues) can cause such problems ? I have 2 applications running on the same redis database on Compose.io with 6-10 queues by application (12-20 queues).

**Comment by manast** [comment]
Difficult to say, but I would start by rewriting the process functions to just use promises instead of mixing async, promises and nodejs callback style, so the process function will become something like:
```javascript
workerOne.process(2, function (job, done) {
  console.log("Processing job #" + job.jobId + " ----> " + JSON.stringify(job.data));
  return  trakt.shows.summary({ id: job.data.id }).then(function(data){
    console.log(JSON.stringify(data));
    return workerTwo.add(data);
  });
```

**Comment by igorissen** [comment]
Ok. First, I'll move each application in a different database and after I'll rewrite all process functions.
Thank you.

Is it possible to left this issue open ? Or if you close it can it be reopened later ?

**Comment by igorissen** [comment]
Hi @manast,

I think I found the problem. It's linked with this issue #90, #109.

This is the code that I used to create the job
```javascript
QueuesManager
  .createJob(
    Constants.QUEUES_NAMES.UPDATE_SHOW_EPISODES,
    { ids: traktShowData.ids, airs: traktShowData.airs},
    { attempts: 3, backoff: { type: "exponential", delay: "" + ms("1m") }, timeout: ms("5m") }
  )
  .then(function (job) { next(); })
  .error(function (err) { next(err); });
```

I added the `attempts` option because Trakt.tv service return often a `504` HTTP Code. When the issue happens, new jobs are stuck in a pending state.

```
APP:0>HGETALL bull:SERIST.Queue.UpdateShowEpisodes:8166
1) delay
2) 0
```

And for another job I got this

```
APP:0>HGETALL bull:SERIST.Queue.UpdateConfigurationFollowedShows:3759
1) attemptsMade
2) 1
3) delay
4) 0
5) stacktrace
6) ["ExpectedStatusCodeError: Expect 2xx HTTP status code, but received '504'\n    at /home/ubuntu/app/libs/apis/trakt.js:380:23\n    at nextTask (/home/ubuntu/app/node_modules/async/dist/async.js:6121:18)\n    at Request.<anonymous> (/home/ubuntu/app/node_modules/async/dist/async.js:6115:17)\n    at Request.<anonymous> (/home/ubuntu/app/node_modules/async/dist/async.js:307:31)\n    at Request._callback (/home/ubuntu/app/node_modules/async/dist/async.js:807:20)\n    at Request.self.callback (/home/ubuntu/app/node_modules/request/request.js:200:22)\n    at emitTwo (events.js:100:13)\n    at Request.emit (events.js:185:7)\n    at Request.<anonymous> (/home/ubuntu/app/node_modules/request/request.js:1067:10)\n    at emitOne (events.js:95:20)\n    at Request.emit (events.js:182:7)\n    at IncomingMessage.<anonymous> (/home/ubuntu/app/node_modules/request/request.js:988:12)\n    at emitNone (events.js:85:20)\n    at IncomingMessage.emit (events.js:179:7)\n    at endReadableNT (_stream_readable.js:913:12)\n    at _combinedTickCallback (node.js:383:13)\n    at process._tickDomainCallback (node.js:431:11)"]
```

Is there a way to remove automatically, using an event, the corrupted job ?

**Comment by manast** [comment]
@igorissen what is the status of this? are you still experience the issue with the latest versions of bull?

**Comment by igorissen** [comment]
Hi @manast,

I just saw, through [versioneye](https://www.versioneye.com/), that you've updated your lib. I still encounter this issue but it's rare. I have been using bull@1.0.0-rc1 until now.

Can you give me 2 weeks of testing with the bull@1.0.0 ?

After that if I don't encounter this issue I'll close it.

**Comment by MoreiraTv** [comment]
My jobs are stuck in the processing queue and are not resolved and when I restart the server it starts processing.

`import Queue from 'bull';
import redisConfig from '../../config/redis';

import * as jobs from '../jobs';

// console.log(redisConfig);

const queues = Object.values(jobs).map(job => ({
  bull: new Queue(job.key, redisConfig.redis),
  name: job.key,
  handle: job.handle,
  options: job.options,
}))

export default {
  queues,
  async add(name, data) {
    // console.log(this.queues)
    let queue = this.queues.find(queue => queue.name === name);
    // console.log("queue: ",queue)

    return queue.bull.add(data, queue.options);
  },
  async process() {

    let resultado = this.queues.forEach(async queue => {
      await queue.bull.process(queue.handle);
      queue.bull.on('failed', async (job, err) => {
        console.log('Job failed', job.name, job.data);
        console.log(err);
      });
    })
    return resultado
  }
};`

**Comment by manast** [comment]
@MoreiraTv my advice is to start with a simpler code and build your way up to a working solution.
