### ISSUE TITLE
Unhandled rejection TimeoutError thrown for grace full shutdown

### ISSUE THREAD

**Issue by zlanka** [OptimalBits/bull#289]
I have two scripts queue.js and process.js both running on the same server. queue.js will queue all the job request through cli which is as follows 

```
.....
var queue = Queue('queue', Config.redisPort, Config.redisHost);

if (options && options.job) {
    queue.add({command: options.job});
}

queue.close();
```

which throws the following execption after successfully adding to the queue and while closing

```
Unhandled rejection TimeoutError: Timed out while waiting for redis clients to close
    at afterTimeout (/.../node_modules/bull/node_modules/bluebird/js/release/timers.js:48:15)
    at timeoutTimeout [as _onTimeout] (/.../node_modules/bull/node_modules/bluebird/js/release/timers.js:75:13)
    at Timer.listOnTimeout (timers.js:93:15)
```

the other script  process.js which runs continuously and process the jobs is as follows 

```
.....
var queue = Queue('queue', config.redisPort, config.redisHost);

queue.process(function (job, done) {
    console.log(job.data);
    done();
});
```

if I use queue.close in second case it also throws the same exception. what is wrong with this code?

**Comment by doublerebel** [comment]
Hi @zlanka , the promise error handling has been improved in version 2.0.0.  Is this still an issue for you?
