### ISSUE TITLE
Redis file descriptors increases continuously

### ISSUE THREAD

**Issue by ali-bugdayci** [OptimalBits/bull#293]
We have been facing this for a long time actually. We automatically restart the processes currently. Is there any where that we have to close a descriptor?

When we check the redis ports open we see that it is increasing continuously.

Listing file descriptors using redis port 6379:

```
lsof -i -n -P | grep node | grep 6379

node    6102  bor   39u  IPv4 6127661      0t0  TCP 127.0.0.1:53536->127.0.0.1:6379 (ESTABLISHED)
node    6102  bor   40u  IPv4 6127662      0t0  TCP 127.0.0.1:53538->127.0.0.1:6379 (ESTABLISHED)
node    6102  bor   41u  IPv4 6127663      0t0  TCP 127.0.0.1:53540->127.0.0.1:6379 (ESTABLISHED)
node    6102  bor   42u  IPv4 6127664      0t0  TCP 127.0.0.1:53541->127.0.0.1:6379 (ESTABLISHED)
node    6102  bor   43u  IPv4 6127665      0t0  TCP 127.0.0.1:53542->127.0.0.1:6379 (ESTABLISHED)
node    6102  bor   44u  IPv4 6127666      0t0  TCP 127.0.0.1:53552->127.0.0.1:6379 (ESTABLISHED)
node    6102  bor   45u  IPv4 6127667      0t0  TCP 127.0.0.1:53553->127.0.0.1:6379 (ESTABLISHED)

```

Redis file descriptors opened:

```
 lsof -i -n -P | grep node | grep 6379 | wc -l
498
```

All file descriptors opened:

```
lsof -i -n -P | grep node | wc -l
577
```

**Comment by manast** [comment]
weird. Only three connections are created when instantiating Bull, so I wonder if this could not be a bug in node-redis?

**Comment by ali-bugdayci** [comment]
Thanks for fast response. Will try to create a demo app for it. 

Could there be a bug with the way you are using node-redis?

**Comment by nrempel** [comment]
I'm also, seeing something similar. I will try to create a minimal reproduction of the issue when I have time.

**Comment by manast** [comment]
closed due to lack of feedback.
