### ISSUE TITLE
Unable to create Queue from localhost without local redis

### ISSUE THREAD

**Issue by deepakmani** [OptimalBits/bull#301]
I am new to using Bull. I see that when I create Queue like so on a cloud provider,  
````
      var Queue 		                = require('bull');
	findEmailQueue 		= Queue("findEmail", "11279", "ec2-54-163-225-204.compute-1.amazonaws.com", {auth_pass: "ped0ib3jlrpu0m1varak18h111"});

````
This error is thrown
````
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1057:14)
````
If I run a redis-server, the Queue is created and works well.
Can you please suggest what might be causing this?

**Comment by manast** [comment]
Try using a number for the port instead of a string.

**Comment by deepakmani** [comment]
Thanks, but no luck.

**Comment by evanhuang8** [comment]
Are you sure you have the permission to access the remote redis from your local server? The EC2 security group might be blocking your traffic

**Comment by deepakmani** [comment]
Thanks for the reply.

The issue seems to be related to this:https://github.com/NodeRedis/node_redis/issues/1035

After bull was upgrade node_redis 2.6.2 I have not seen this issue again.

-Deepak
