### ISSUE TITLE
Creating queue from a redis url

### ISSUE THREAD

**Issue by rosendi** [OptimalBits/bull#306]
Is this an internal API? https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L67

Currently, I do something like this in order to create a queue from a redis url:

```
const { port, hostname, auth } = url.parse(process.env.REDIS_URL);

const queue = bull('id', port, hostname, { auth_pass: String(auth).split(':')[1] });
```

How can I just pass a redis url to Bull? Did I miss something?

**Comment by abacaj** [comment]
```
var Queue = require('bull');
Queue('queue-name', 6379, '192.168.33.10', {password: 'password'});
```
