### ISSUE TITLE
New jobs are not processed immediately if there are many stalled jobs to reprocess

### ISSUE THREAD

**Issue by chuym** [OptimalBits/bull#313]
This issue is the result of some stress testing I've been conducting.
Steps to reproduce:
1. Have thousands of stalled jobs in the queue 30k+
2. Have a queue that publishes new jobs every 1ms (a setInterval to publish a dummy job is enough)
3. Have some process that simulates some job (a timeout that takes ~50ms to finish is enough)
4. Jobs will pileup until all stalled jobs are finished up processing

Note that you must have the stalled jobs before running the queue, this only happens to a fresh queue that just started up.

This seems to be caused because `Queue#run` waits until `processStalledJobs` finishes processing, but it is an slow operation. On my machine it took roughly 8 minutes to clean the 30k jobs, during that time no jobs were processed.

**Comment by manast** [comment]
hmm. If a job has been stalled, wouldn't be reasonable that it is processed *before* other jobs in the queue? if so, this should not be a wrong behaviour.

**Comment by chuym** [comment]
> If a job has been stalled, wouldn't be reasonable that it is processed before other jobs in the queue?

Hmm it could be, but regardless, that is currently not the case. If there is a single stalled job, new jobs will be processed fine by an ongoing queue, so this means that there will be new jobs completed before the stuck job process. Bull doesn't pause processing because a job stalled. Note that this issue affects new queues connected to an instance with many stalled jobs.

> is processing a stalled job slower than a regular one?

No it isn't. Processing N jobs through process stalled jobs is slower than processing N regular jobs where N > 1. This is because stalled jobs are processed in serial, so if there are 30k jobs to process that take 150ms in average to complete it will take 75 minutes for a single `processStalledJobs` call to complete. However, in practice that time is lower because every 5s there will be a new `processStalledJobs` that will be reprocessing the stalled jobs

**Comment by manast** [comment]
So it means that instead of process the jobs it would be probably better to move the job to the wait queue in a LIFO fashion... by doing that the jobs will be processed all the same.

**Comment by chuym** [comment]
Yeah, you've mentioned about moving it out from active. It could either moved to `failed` or `wait`. However it may be a bit confusing, these jobs are not really explicitly failing so they shouldn't be on `failed`, nor they are in `wait` because currently that implies it is a new job.

Perhaps a new list named `stalled` ?

**Comment by manast** [comment]
seems to me that what we need is a lua script that is executed periodically doing the following:
- get max N active jobs starting from the end of the active list (the end should have the oldest jobs).
- check one by one if: a) they are stalled (not locked), b) they have reached their TTL (if any specified).
- If we have auto stalled jobs processing -> move job to wait as LIFO, otherwise move to the fail set with reason "stalled".
- If we have TTL defined, move to failed set and let auto-retry take over (if any).

**Comment by manast** [comment]
introducing a new list type will increase the degrees of freedom so to speak, making the code more complex. I would prefer to use existing mechanism as much as possible...

**Comment by manast** [comment]
its important to note that stalled jobs are produced by one of two circumstances: the worker dies for some reason, the workers event loop is kept busy for more than 5 seconds. These two situations can be considered bugs in the client code. On the other hand, jobs being timeout via a defined TTL is just a client code constraint for jobs that take too much time to complete.

**Comment by manast** [comment]
late here, Im gonna hit bed now...

**Comment by chuym** [comment]
> introducing a new list type will increase the degrees of freedom so to speak, making the code more complex. I would prefer to use existing mechanism as much as possible...

Yeah, pros and cons. It will make easier for a new user to see what's going on by looking at the code at the cost of making the whole queue more complex. However repurposing an existing mechanism comes with its own problems. I'll leave the design decision to you

**Comment by chuym** [comment]
I just upgraded to Bull 1.0 and this hit bad. Bull effectively stopped processing new jobs because there were some jobs that got stalled during the upgrade. These jobs take a significant amount of time and newly added jobs were being pilled up without processing because the Queue was processing one at a time. The only way to mitigate this is by throwing more parallel queues during this phase.

As nice as it is to ensure that stalled jobs process before any active jobs, the solution doesn't scale

**Comment by manast** [comment]
is this a problem just because processStalledJobs does not care about the concurrency setting?

**Comment by manast** [comment]
if that is the case, we should be able to resolve it easily by using map instead of each and the concurrency setting: http://bluebirdjs.com/docs/api/promise.map.html
On this line: 
https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L487

**Comment by manast** [comment]
(or moving stalled jobs to the wait queue which will then kick the same processing code as normal jobs).

**Comment by manast** [comment]
This issue should have been resolved in version 1.1.0.
