### ISSUE TITLE
Invalid options are stored in a job options property

### ISSUE THREAD

**Issue by xdc0** [OptimalBits/bull#315]
Any option passed to a Job is stored as a job option, even if it's unrecognized by Bull.

This is a minor issue, but Bull should probably filter out unknown options.

Interestingly, there are test cases that rely on Bull's ability for storing any option to pass: https://github.com/OptimalBits/bull/blob/master/test/test_job.js#L56 so I'm not sure if this is actually a feature.

**Comment by karthikiyengar** [comment]
I'd be happy to take this on given some guidance. 

There seem to be 3 locations where I could put the validation logic: queue.js (Queue.prototype.add), job.js (addJob), script.js (addJob).  What would be the most appropriate?

There seems to be no definition of the complete JobOptions interface. Should I just create an array for the check?

**Comment by manast** [comment]
The job options is described here: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd

However, I am nowadays not so inclined to add defensive code for checking input parameter types, instead the external tooling should take care of that, such as if using typescript definitions (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bull) or other means.

**Comment by manast** [comment]
Btw, the unit test that tests for this is definitively wrong, I will remove it.

**Comment by weeco** [comment]
@manast Are you still looking for a pull request to get that implemented? I am not so sure if you want to see this change or not. If not you could probably close this issue.

**Comment by manast** [comment]
as mentioned above I prefer typescript definitions, which I think we already have so this issue could be closed.

**Comment by weeco** [comment]
@manast Ok then I guess you can close this and the refenced issue. I will try to update the Typescript definitions asap
