### ISSUE TITLE
attemptsMade not incrementing for completed jobs

### ISSUE THREAD

**Issue by jozsi** [OptimalBits/bull#316]
Using version `0.7`, `job.attemptsMade` was being incremented for completed jobs as well. On version `1.0`, it looks like it's only incremented for failed jobs.

**Comment by ejarnutowski** [comment]
What's the outcome of this?  Is `attemptsMade` treated as if it were `failedAttemptsMade`?

**Comment by manast** [comment]
yeah, unfortunately this mistaken was done and as been kept like this for several versions.
