### ISSUE TITLE
Stalled jobs only checked at queue startup? 

### ISSUE THREAD

**Issue by lperrin** [OptimalBits/bull#32]
First of all, thanks for your work on bull. It's small, clean and the code is self-explanatory. Just what we want from such a critical piece of software :).

Anyway, it seems that the queue only checks for stalled jobs at startup. For us, this means that crashed jobs will only get unstuck after a worker restarts.

I'm not sure I follow you here. Can you elaborate on your intent ?

**Comment by manast** [comment]
timestamps are now part of the Job since they are used for the delayed functionality.
