### ISSUE TITLE
Non existent jobs are kept in failed state

### ISSUE THREAD

**Issue by chuym** [OptimalBits/bull#320]
There is a current condition where jobs are being kept in `failed` state, but the job doesn't exist anymore:

This is what I get when tapping into redis

```
myredishost> SSCAN bull:myQueue:failed 0
1) "3584"
2)  1) "2165600"
    2) "2175090"
    3) "2168716"
    4) "2176436"
    5) "2169695"
    6) "2174317"
    7) "2164073"
    8) "2166687"
    9) "2168803"
   10) "2167887"
myredishost> HGETALL bull:myQueue:2165600
(empty list or set)
```

The job is created with default options.

**Comment by chuym** [comment]
I wonder if there is an error being masked away because we are doing nothing with`moveToSet`

**Comment by manast** [comment]
Is this issue still happening in 1.2.0 ?

**Comment by chuym** [comment]
Not anymore, closing
