### ISSUE TITLE
Possible deadlock on Failed jobs

### ISSUE THREAD

**Issue by chuym** [OptimalBits/bull#322]
I'm noticing that several failed jobs remain locked.
Monitoring the TTL of the lock, I notice that it renews exactly at `LOCK_RENEW_TIME / 2`

The only place where such lock happens is in: https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L570

By inspecting the logic, I think there is a race condition that is causing a deadlock to take place:
1. A job starts being processed and a lock renew loop kicks off
2. A job fails and gets moved to `failed`
3. Just there, the lock renew function calls itself again and attempts to renew the lock
4. Before step 3 is completed, the timer is cleared by the `finally` clause in https://github.com/OptimalBits/bull/blob/27321806a95d07439412ffc666088cdd9ebadaa4/lib/queue.js#L627
5. The lock renew function completes and sets the timer again in https://github.com/OptimalBits/bull/blob/27321806a95d07439412ffc666088cdd9ebadaa4/lib/queue.js#L570

**Comment by manast** [comment]
Could this be fixed in 1.1.2 after improvements in stalled jobs or otherwise in master after @doublerebel improvements?

**Comment by manast** [comment]
As far as I can see the race condition is still there. I will try to find a solution for this.

**Comment by manast** [comment]
Since we are checking if the timer is stopped, this hazard should not exist anymore:
https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L684
I will re-open if not the case.
