### ISSUE TITLE
Client libraries

### ISSUE THREAD

**Issue by xogeny** [OptimalBits/bull#323]
I was wondering...are there Bull client libraries for other languages?  In particular, what I was interested in was using something like this for microservices like architectures where different services might be provided in different languages (_e.g.,_ GoLang, Java, Scala, _etc._).

I didn't see any sign that there are even unofficial client libraries for these platforms.  For the moment, I'm only interested in worker functionality but I could imagine scenarios where I might want to initiate jobs from those other languages as well (and have them executed by Node.js workers).  

Is there any documentation on how all this maps to the REDIS side so that someone could try and implement the identical protocols in other languages?

Thanks.

**Comment by chuym** [comment]
Most operations are done as redis LUA scripts `/lib/scripts.js` and my understanding is that the tendency is to move all operations as lua scripts eventually, so that should make it straightforward to implement libraries in other languages that work under the Bull scheme.

**Comment by manast** [comment]
There is actually an implementation in F# https://github.com/fsprojects/oxen
