### ISSUE TITLE
Queue#run fires a processStalledJobs loop when concurrency is 0

### ISSUE THREAD

**Issue by chuym** [OptimalBits/bull#327]
I noticed this with my use case, where the concurrency value is set through an environment variable, this way you can have a service running on many instances with configurable concurrency values on each of them. A simple way to prevent a worker from processing jobs is by setting concurrency to `0` when it's needed.

However, setting the concurrency value to 0 by calling `queue.process(0, myJobHandler)` has the side effect of always running a `processStalledJobs` loop, this means that a worker that is not intended to run any jobs will run jobs through the `processStalledJobs` loop, as a side note, `processStalledJobs` currently has a flaw where it also processes fresh jobs, not only stalled ones.

**Comment by chuym** [comment]
While I can argue that calling `Queue#process` with 0 concurrency is an anti-pattern, it should have tighter constraints, either explicitly throw when setting concurrency as a non positive integer value, or return early when `concurrency <= 0` so it doesn't do any process at all.

**Comment by manast** [comment]
can you provide more information regarding the issue in ```processStalledJobs```where it also processes fresh jobs?

**Comment by bradvogel** [comment]
It's the issue described here: https://github.com/OptimalBits/bull/pull/257. So `processStalledJobs` is actually processing fresh jobs quite a bit.

**Comment by bradvogel** [comment]
Fixed in https://github.com/OptimalBits/bull/pull/359

**Comment by doublerebel** [comment]
Looks like #359 was merged so this can be closed?
