### ISSUE TITLE
Jobs stuck in active

### ISSUE THREAD

**Issue by evanhuang8** [OptimalBits/bull#328]
I have been having this issue with my queues for 2-3 months now, basically, some job will get stuck in the `active` queue, and I only have 1 worker, hence jobs in the `wait` queue pile up. I have to constantly check the status of the queue and restart when it happens.

My question is, shouldn't the worker kill the stuck jobs, or at least try to move them to `failed` and continue to run other jobs?

**Comment by manast** [comment]
but what means stuck in this context? did the worker hang when processing the job? Because if that is the case I guess the worker is not able to process anything else, and since you only have one worker it will stop processing more jobs. To fix this it will be needed some kind of fibers or threads that can be killed if they take too much time to process a job...

**Comment by evanhuang8** [comment]
Stuck means there are the same 5 jobs in the `active` queue forever, and the `wait` queue keeps piling up.

Weird thing is that, if I restart the worker frequent enough (say if i restart it daily), it will run days without issues. On the flip side, if I just leave it alone, after 10-15 days or so the issue described will happen. I suspect maybe there is something with memory leak as well?

But yes, I do think it will be nice to have a dead letter queue sort of things

**Comment by manast** [comment]
But the stucked jobs, in which state are they? have they been completed?

**Comment by manast** [comment]
but then we cannot discard the the error is in your worker code that is not actually completing the job?

**Comment by evanhuang8** [comment]
It's possible, but I really doubt it, mainly because it will run days without hiccups, and the tasks are run quite frequently

**Comment by manast** [comment]
yes but I mean, if the job is left in the active state, it means it has never completed or failed, so your code maybe did not finalize for some reason.

**Comment by manast** [comment]
Close due to lack of feedback.

**Comment by munawwarhussain** [comment]
I am getting the same issue. I have added a job with repeat parameter the job stats in the active state and never gets repeated.
```
someQueue.add({
  'url': 'http://xyz.com'
},{repeat: '*/2 * * * *'});
```
this message is never getting processed, if I remove the repeat parameter the message is posted and processed.
