### ISSUE TITLE
rate limiting?

### ISSUE THREAD

**Issue by afrozl** [OptimalBits/bull#329]
Is it possible to limit a job (keyed on an argument) to only run x times a period? does bull have a plugin framework so commonly used functions can be shared across jobs?

**Comment by zoell** [comment]
I am also interested in this. Have you ever find a solution with bull or any other library?

**Comment by bradvogel** [comment]
Have you seen https://github.com/OptimalBits/bull/pull/335 that just got merged? You can give the job a unique key and a delay, so if you add a job with that same id that is currently queued, it won't do anything. So basically throttling. cc @pricj004

**Comment by manast** [comment]
Closing due to be a duplicate of #362
