### ISSUE TITLE
Redis dependency hidden

### ISSUE THREAD

**Issue by black-snow** [OptimalBits/bull#332]
*IMHO* you should be able to see at a first glance that a **redis server is required** in order for bull to work . *ATM* this info is hidden in the sentence *"Note that you need a redis version higher or equal than 2.8.11 for bull to work properly."* that looks more like an unimportant comment below the actual installation step(s).

*IMHO* the *install* section should rather look like this:

    # be sure to have redis installed on your machine
    # e. g. install redis on mac os using homebrew
    $ brew install redis

    $ npm install bull

I wanted to give bull a shot but I (currently) cannot ship redis with my app so bull is not an option. Sadly, I wasted some time because I didn't see that a redis server is required :|

**Comment by manast** [comment]
I think you are being a bit unfair. The title of the project says: A NodeJS persistent job and message queue based on Redis. In the Features it says "Robust design based on Redis", and finally on the first example you can see a connection to a redis database: ```var videoQueue = Queue('video transcoding', 6379, '127.0.0.1');
````
I don't want to be rude, but please do not complain on a project documentation if you actually failed to read it.

**Comment by black-snow** [comment]
This wasn't meant to be a complaint but rather an improvement to the docs.

*"Based on Redis"* does not imply that I need to have a Redis db set up and running. Redis could also be shipped with the project / be built-in. *"Based on the unreal enigne"* doesn't imply that I need to install the unreal engine (manually) before I can install the game.

Also pointing to the Redis install guide / docs would help.

Cheers
