### ISSUE TITLE
How to check the actually same job  

### ISSUE THREAD

**Issue by xihuanhh** [OptimalBits/bull#336]
hi, i just met this problem，i add a job to the queue and run it. then i stop the node process,
when i run the same code next time, i happened that the same job exec twice, i know the job was stored in the redis,it will be load from the redis and execute.
so the question is  how can i check the same job to avoid this situation when the queue start process jobs. thanks!

**Comment by manast** [comment]
This is the normal behaviour in bull. When the queue starts checks if there are stalled jobs and process them. But when a job is completed, it should never start it again. We had some edge cases in previous versions, but in 1.2.0 it is all fixed.
