### ISSUE TITLE
Counts of completed jobs?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [OptimalBits/bull#338]
Hi,

How do I get a count of finished jobs on a particular queue?

**Comment by bradvogel** [comment]
This should help: https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L717

**Comment by doublerebel** [comment]
@GeoffreyPlitt you can use [el-borracho-stats](https://github.com/nextorigin/el-borracho-stats), it will save stats in Redis in basically the same format as Sidekiq.  All it takes to use it, [is to initialize it with a Bull queue instance](https://github.com/nextorigin/el-borracho/blob/83931199a44ab09b846153b0b3e405379466cea1/helpers/job-creator.coffee#L19).  I have some docs coming soon, but feel free to post questions in the repo issues for el-borracho-stats.

**Comment by GeoffreyPlitt** [comment]
Cool, will check it out!
