### ISSUE TITLE
Queue.prototype.getWaiting() returns empty list if Queue is paused

### ISSUE THREAD

**Issue by Bersam** [OptimalBits/bull#342]
I need to get a list of all jobs currently in the queue. I have found Queue.prototype.getWaiting(). But it returns an empty list if the queue is paused.

**Comment by manast** [comment]
I think that is a bug, this is because pause works by renaming the waiting queue, and getWaiting probably do not consider it. It should be just a matter of checking if the queue is paused (check if the renamed queue is there, if so return that, otherwise return the normal waiting queue.
