### ISSUE TITLE
Cluster support? Use stand alone in production?

### ISSUE THREAD

**Issue by barczaG** [OptimalBits/bull#345]
Hello, 

I've seen there is PR about this topic but is it on the roadmap ? https://github.com/OptimalBits/bull/pull/188

My other question that is it safe to use stand alone deployment of redis in production mode?
Thanks!

**Comment by manast** [comment]
problem is that redis.io does not work so well with bull. In my test it was not as stable as node redis, so until node redis does not support cluster there is not so much I can do.

**Comment by doublerebel** [comment]
FWIW I've been using Bull in production with Redis Sentinel and [RedisHappy](https://github.com/mdevilliers/redishappy) and it works quite well.  Even without RedisHappy, Redis master/slave configuration is very stable -- it's the underlying infrastructure (backups, uptime) that I would worry about.
