### ISSUE TITLE
PriorityQueue Run 2-3 times more than Normal Queue

### ISSUE THREAD

**Issue by Bersam** [OptimalBits/bull#347]
I've notice that PriorityQueue run 2-3 times more than Normal Queue, depend on jobs in each queue.
I need priorityQueue to run one job per time.

**Comment by Bersam** [comment]
Seems Bull runs one job from each of 5 priortity level, in those case i've got multiple jobs in 2 or 3 levels. is it possible to force it to run only one job at time? no matter how many jobs are in each level or queue.

**Comment by manast** [comment]
I think the priority queue is a bit buggy currently, it should not run concurrent jobs unless you use the concurrent flag, it should run one job at a time in priority order, a different behaviour than this should be regarded as a bug.

**Comment by Bersam** [comment]
@manast I've written a script that reproduces this behavior. it seems multiple resume action makes this buggy result, I'm not sure and I'm trying to test more cases that occur in my application to find out what leads to this.
https://gist.github.com/Bersam/0a6138959ded1be332b1b12d857eefcd

**Comment by Bersam** [comment]
I believe this line causing problem.
https://github.com/OptimalBits/bull/blob/master/lib/priority-queue.js#L183
handler is true, and rerunning run function results in unwanted concurrency...

**Comment by manast** [comment]
From bull version 2.2.0, priority queues are implemented in a simpler and more efficient way, this issue should not exist anymore.
