### ISSUE TITLE
get local events

### ISSUE THREAD

**Issue by fiws** [OptimalBits/bull#350]
Hi,
is it currently possible to get failed, completed, started, etc … job events for a local process only?

**Comment by manast** [comment]
we have support for global events on master branch.

**Comment by fiws** [comment]
I know, but I'm specifically looking for **local** events only. 

I would like to log failures, but have a cluster of processes. If I use global events, the error will get logged multiple times.

**Comment by fiws** [comment]
So, i think with https://github.com/OptimalBits/bull/commit/d55ad1c8f44f86be9b4e9f4fa9a3fc8a16c6e02d I now get all events on all workers.
This is a pain to work with, since we now log all errors ⨉ number of workers.

That's also quite the breaking change. I don't see how this has gone through as a minor...

**Comment by bradvogel** [comment]
Agree. This should have been opt in or a v2.0 release.

**Comment by manast** [comment]
my fault. I always thought of local events as a limitation and not a feature. I will try to make a patch to maintain backwards compatibility and at the same time support for global events.

**Comment by manast** [comment]
fixed in disturbed: d983a4d5a144ee24c0b12b292315e990abea2aa3
