### ISSUE TITLE
Custom jobId

### ISSUE THREAD

**Issue by nickbradley** [OptimalBits/bull#351]
How can I check if a job is in the queue when using custom jobIds?

```
queue.add({}, {jobId: "abc"});
```

adds the job with `opts.jobId` set to `"abc"` but doesn't change `jobId`.

If I try to check if the job is queued using

```
queue.getJob("abc").then(function(val) => { 
  if (val) console.log("found job"); 
  else console.log("no job");
});
```

I get `"no job"`.

**Comment by spiritinlife** [comment]
If you are using latest Release v1.0.0 i believe it is not yet supported. The pr #335 although merged to master is not yet released.
I believe the problem here is that the Readme says that it is supported.
Not sure though cause i am new to bull :P

**Comment by manast** [comment]
This works since version 1.1.0
