### ISSUE TITLE
attempts option doesn't working in normal queue

### ISSUE THREAD

**Issue by Bersam** [OptimalBits/bull#353]
I've added attempts as an option to my jobs and I can confirm that it's recognized as it's filled in attempts in redis, but for each job that failed, it only do that job for once. (using normal queue)

[["attempts","5"],["delay","0"],["opts",{"priority":"critical","attempts":5}],["progress","0"],["data",{}],["attemptsMade","1"],["timestamp","1475909499776"],["stacktrace","[\"Error: reach end of source!\"]"],["returnvalue",""]]

it's not added to queue again, and it's not added to delayed job again. I've stayed for half hour but it doesn't seem to want to do that job again.

p.s. I've send priority option too, but queue is normal bull queue.

bull: ^1.0.0
redis: 3.0.6
node: v6.2.1

**Comment by manast** [comment]
thats weird, did you manage to get the test that checks for the attempts functionality to pass?
https://github.com/OptimalBits/bull/blob/master/test/test_queue.js#L1214

**Comment by manast** [comment]
closed due to lack of feedback.
