### ISSUE TITLE
Add a rate limiter so that the queue does not process more than N jobs per second.

### ISSUE THREAD

**Issue by aniruddha-chakraborty** [OptimalBits/bull#362]

**Comment by manast** [comment]
Do you mean a setting for the max number of jobs to process per second? (since the minimun is determined by the jobs complexity and the underlying performance of the queue, redis latency, etc).

**Comment by aniruddha-chakraborty** [comment]
Yes! exactly i was talking about max number of jobs to process per second. for example my sms api provider strictly said that they will NOT allow more than 10 sms request.

**Comment by manast** [comment]
It may be possible to implement a rate limiter following the patterns explained here: http://redis.io/commands/INCR

Also it is important to decide if the rate limiter is per queue or global (using redis it should be possible to make global as well).

**Comment by doublerebel** [comment]
Looks like this is a dupe of #329

**Comment by orecus** [comment]
This is exactly what I was hoping to se in Bull. I'm working on an application where being able to rate limit (x requests per x seconds) for each of my queues is needed. 

Looking forward to this functionality!

**Comment by ryanmills** [comment]
+1 for rate limiting number of jobs being executed concurrently

**Comment by weeco** [comment]
@manast I think this issue can be closed or is there something missing?

**Comment by manast** [comment]
This is indeed fixed since v3.1.0
