### ISSUE TITLE
Restart processing after crash or restart

### ISSUE THREAD

**Issue by prashaantt** [OptimalBits/bull#365]
I'm trying out bull and have been able to figure out most things, except how to auto-resume processing after the node process is shutdown. I would like to pick up from where the queue was just before the shutdown and begin processing/re-trying jobs that were queued from the old process, in addition of course to processing new jobs when they occur. Basically, something like this:

```js
queue.on("ready", () => {
    const count = queue.count(); // count of all jobs, whether new or old
    const jobs = queue.getJobs(); // all jobs
    if (jobs.length > 0) {
        jobs.forEach(job => process(job));
    }
})
```

I know the `getJobs` API doesn't exist (and `.count()` returns 0 at startup), but I'd like to do something like the above. How can I achieve this?

**Comment by manast** [comment]
you don't need to do anything, the queue will continue to process the jobs that were not completed before the process ended.

**Comment by prashaantt** [comment]
Great, and sorry for the bother. I looked at the tests and have been able to myself reproduce pending jobs being executed after restart. But I've not been able to make it retry failed jobs after restart. Am I still missing something?

**Comment by prashaantt** [comment]
Never mind, I got it. I was manually simulating the `job.retry()` upon each failure instead of using the built-in `attempts` and `backoff` options to get the feature automatically.
