### ISSUE TITLE
Concurrency ignored when the application is restarted

### ISSUE THREAD

**Issue by tomasgvivo** [OptimalBits/bull#366]
In my application, I have a Queue with concurrency 1.
If I create 2 jobs, one will be active an the other one will be waiting until the first one gets completed.
BUT if I restart the application (using forever), and I chech the status of the jobs, both jobs will be active.

(sorry for my bad english)

**Comment by bradvogel** [comment]
Assuming that you're restarting the queue process while it's processing the first job, then the job will become 'stalled'. PR https://github.com/OptimalBits/bull/pull/359 will fix this by putting the stuck job back in the wait queue, and concurrency will be be respected.

**Comment by manast** [comment]
fixed in #359
