### ISSUE TITLE
please make a new npm publish

### ISSUE THREAD

**Issue by xycloud** [OptimalBits/bull#368]
need feauture 'removeOnComplete', please make a new npm publish

**Comment by bradvogel** [comment]
Please add a changelog to the readme too

**Comment by manast** [comment]
sorry for the delay, we got a new family member this Thursday and I have been unable to do any work on this project. I will update as soon as I can fix some of the tests that are failing.

**Comment by bradvogel** [comment]
@manast Created a WIP changelog for 1.1.0 here: https://github.com/OptimalBits/bull/pull/369

**Comment by xycloud** [comment]
@manast congratulations : )

**Comment by rmeja** [comment]
I'm also waiting for this new release but I understand the situation. So let's be patient. :wink:
