### ISSUE TITLE
Jobs can be processed and left in the `wait` state

### ISSUE THREAD

**Issue by bradvogel** [OptimalBits/bull#370]
@manast Following the discussion in https://github.com/OptimalBits/bull/pull/359, I found a hazard that I think we should address before releasing a new version: a job can be processed an still left in wait. Here's how:

| Time | Process A | Process B |
| --- | --- | --- |
| 1 | In the regular Bull run loop of Process A, getNextJob moves a job from `wait` to `active` |  |
| 2 |  | In Process B, `moveUnlockedJobsToWait` happens to run and pick up the job in step 1, and moves it back to wait |
| 3 | Process A gets lock on the job (that is now in 'wait') and begins to process it | |

If there is no other process around to move the job back to `active` then Process A will complete the job and leave it in `wait`. This can lead to a data inconsistency.

**Comment by bradvogel** [comment]
To fix this, what if `takeLock` takes a parameter (perhaps `ensureActive`) to ensure that the job is in the active state? Then `processJob` would use that parameter - so it can only ever keep a lock while the job is in `active` - while other uses of the lock (eg `job.remove` is called) can acquire the lock in any state.

**Comment by manast** [comment]
I would need to check the code but is there any reason to allow locking a job that it is not in the active set? If now, then we can just have that constraint in takeLock, it could fail the same way it does when trying to get a lock on a already locked job...

**Comment by bradvogel** [comment]
`job.remove()` tries to get the lock before removing, and I assume we still want to be able to call `remove()` on jobs that aren't in the active queue

**Comment by bradvogel** [comment]
#371 describes a more dangerous case: a job can get double processed because a worker is allowed to take the lock while the job is in `completed`, cc @doublerebel

**Comment by doublerebel** [comment]
@bradvogel I think I understand how this could happen, do you have a test case to reproduce this issue?  It doesn't seem to be covered by the test suite.

Also is there a reason not to lock a job from leaving wait until failed/complete?  Rather than releasing the lock between the move to active and when processing starts.

**Comment by bradvogel** [comment]
I don't have a test case yet. It's a bit difficult to write since this is a subtle race condition. Your test case in https://github.com/OptimalBits/bull/issues/371#issuecomment-260158407 should cover it though.

We can't lock the job atomically while it's being moved from wait to active. We use the Redis operation `brpoplpush` to move the job, but due to redis limitations (described in https://github.com/OptimalBits/bull/issues/258), `brpoplpush` can't be used inside a lua script that we'd need to atomically lock it while moving.

We also don't want to lock the job in 'wait' (prior to the move) because that would require polling the wait queue to try to lock the first job. `brpoplpush` allows us to have a poll-free design.

**Comment by bradvogel** [comment]
https://github.com/OptimalBits/bull/pull/377

**Comment by doublerebel** [comment]
Ok, I was able to reliably reproduce this bug.  I have fixed this test case by creating a single atomic operation including the commands to check the active list, set the lock, and set the lockAcquired counter.
https://travis-ci.org/nextorigin/bull/builds/175582853

Still a bit more work to get the rest of the tests passing but major progress 👍

**Comment by bradvogel** [comment]
Sound great. File a PR (even if still a work in progress) so we can take a look.

**Comment by doublerebel** [comment]
@bradvogel Can do, filed as #379.
