### ISSUE TITLE
"Unexpected token u in JSON at position 0" while processing job

### ISSUE THREAD

**Issue by bradvogel** [OptimalBits/bull#371]
I'm noticing that some of our jobs are "corrupted" and the queue is throwing the following error when trying to process them:

```
Error processing job: SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at Function.Job.fromData (/Users/brad/dev/bull-queue/node_modules/bull/lib/job.js:418:33)
    at /Users/brad/dev/bull-queue/node_modules/bull/lib/job.js:68:18
    at tryCatcher (/Users/brad/dev/bull-queue/node_modules/bluebird/js/release/util.js:16:23)
```

In inspecting the job in redis using `hgetall bull:test:1` I can see that only `attemptsMade`, `stacktrace`, and `failedReason` keys are present in the job data.

This leads me to believe that a job failed (and `_saveAttempt` was called) _after_ the job data had been already removed - which can only happen if the job was completed by another worker. And the only way another worker could have completed it is if the first worker failed to renew the lock.

To fix this, what do you think about making `Job.prototype.moveToFailed` an atomic script that guarantees that we own the lock before moving the job. So if another worker picked up the job and it got double processed, we won't do farther damage by trying to move that completed job back to the delayed queue.

This is related to #273.

**Comment by manast** [comment]
we can implement the moveToFailed by just using the new move function (observer there are some todos related to it): https://github.com/OptimalBits/bull/blob/master/lib/scripts.js#L139
I am not sure how the job specific lock token would work, please elaborate a bit more.

**Comment by doublerebel** [comment]
Interesting, the fix in #275 also exists in #188, fixing the root of this bug may be necessary for the ioredis transition.

**Comment by bradvogel** [comment]
Commented in that PR (https://github.com/OptimalBits/bull/pull/188/files#r87665167). That code isn't necessary for moving to ioredis.

**Comment by doublerebel** [comment]
Thanks @bradvogel .  I've also noticed that in several of the test runs, the cluster [double-processes a job](https://travis-ci.org/nextorigin/bull/jobs/175246126#L503).  Perhaps that also is due to the lock issue you have described?

**Comment by bradvogel** [comment]
The only known situation in which a job can get double processed is if it's original worker doesn't renew the job lock (due to a crash or event loop stall). In this case the 'stalled' event gets emitted by the new worker that picks up that job.

If you have a 100% repro case where you see a job get double processed, can you see if the 'stalled' event is emitted?

**Comment by doublerebel** [comment]
I was able to create a repeatable case where the jobs are double processed, and the stalled event is not emitted.  Thanks for the heads up to check and make sure stalled was not the case.  Here is the test case, but the failure also exists in several of my past builds and in OptimalBits/bull master builds also.
https://travis-ci.org/nextorigin/bull/builds/175392452

As described in http://redis.io/commands/SET under **Patterns**, the recommended way to create a distributed lock is now the 'redlock' algorithm.  I implemented the algo and [it fixes the cluster test case](https://travis-ci.org/nextorigin/bull/builds/175401676), but I still have a little work to do to get the rest of the tests passing with the new lock logic.

Once I'm finished we should probably check how the redlock algo affects performance.  Right now there are many failed lock attempts but we are running jobs quickly in the tests, it may not be a noticeable performance hit in real-world situations.

**Comment by bradvogel** [comment]
Great find and test case! I checked out your code and verified this is another instance of https://github.com/OptimalBits/bull/issues/370

What's happening is that two workers are finding out about the same job at the same time via `getNextJob`. One worker is taking the lock, processing the job, and moving it to `completed` before the second worker can even try to get the lock. When the second worker finally gets around to trying to get the lock, the job is already in the `completed` state. But it processes it anyways since it got the lock.

#370 describes a lock being taken while the job is in the `wait` state, and this test demonstrates there's a much worse scenario where jobs can get processed from the `completed` state.

So the fix here is for the `takeLock` script to ensure the job is in the active queue prior to taking the lock. That will make sure jobs that are in `wait`, `completed`, or even removed from the queue altogether don't get double processed. Per the discussion in #370 though, takeLock probably needs to be parameterized to only require the job be in `active` when taking the lock while processing the job. There are other cases such as `job.remove()` that the job might be in a different state, but we still want to be able to lock it.

Feeling up for adding this functionality to `takeLock`? It'd solve the biggest non-atomicity issue in Bull right now.

**Comment by manast** [comment]
@doublerebel keep in mind that redlock is only needed when running redis as a cluster. If you only have one instance of redis, redlock is overkill. Maybe we should have two locking algos and only use redlock when needed.

**Comment by bradvogel** [comment]
Filed PR https://github.com/OptimalBits/bull/pull/377 to address the broken test in https://github.com/OptimalBits/bull/issues/371#issuecomment-260158407.

Though this issue should be kept open since `moveToFailed` still needs to be made atomic.

**Comment by bradvogel** [comment]
To be clear on what I think is happening here:
1. job begins being processed by consumer 1
1. consumer 1 is working slowly and fails to renew lock
1. job becomes "stalled"
1. consumer 2 picks up job
1. consumer 2 finishes job successfully, key is removed from redis and job queues (since it uses removeOnComplete:true)
1. consumer 1 tries to finish the job  and fail it (let's just say it failed for whatever reason - like email smtp server down). It doesn't have the lock but Job.prototype._saveAttempt writes the job key BACK with only the failed data, and pushes the job into the failed queue. Even though the job has been completed by another worker.
1. consumer X sees failed job, tries to process it, but it has partial data, and throws "SyntaxError: Unexpected token u in JSON at position 0"
1. job stays in redis in corrupted state, workers keep trying to process it and hit the exception

**Comment by bradvogel** [comment]
We're working on a PR by the way.
