### ISSUE TITLE
Processor stops working after long period of time

### ISSUE THREAD

**Issue by ShaneK** [OptimalBits/bull#38]
Whenever I leave my processor running all night (with no jobs) and the next morning I try to create a job, the job becomes "active" but never actually has any work done on it. If I add two jobs, the first one becomes active but nothing ever happens to it, and the second is always pending until I restart the processor.

Is there anything I can do about this?

**Comment by manast** [comment]
This seems to be fixed since no one has mentioned this for a while. comment so I can reopen it.

**Comment by neilkinnish** [comment]
I am experiencing this issue using compose.io : Possibly unhandled Error: Redis connection gone from end event.

**Comment by manast** [comment]
This issue could be related to another issue in node_redis: https://github.com/mranney/node_redis/issues/247

Seems like newer versions of the package have partially resolved it, I will upgrade and test.

**Comment by neilkinnish** [comment]
Ah yes makes sense, thanks for being so responsive as always.

**Comment by igorissen** [comment]
I'm getting this error message too. I'm using compose.io. Worked fine a few days ago and now I'm getting this error. What is the solution ?

I'm using `"bull": "^0.7.0"`

**Comment by manast** [comment]
we are using an old version of node redis. I tried to upgrade to the latest one but many unit tests are failing, probably some changes in the API.

**Comment by shahryargh** [comment]
I think, I am hitting this issue as well.

I reproduced it by turning my WiFi connection off on my dev machine. I have Bull worker and Redis running on the same machine.
I also have a retry strategy setup for Redis connection but the .process handlers are disabled once the connection goes down.

**Comment by manast** [comment]
@shahryargh please open a new issue with reproducible code so that we can have a chance to fix it. This issue has already been fixed and considered resolved and closed.
