### ISSUE TITLE
Stateless workaround?

### ISSUE THREAD

**Issue by overflowz** [OptimalBits/bull#381]
Hey! I'm trying to make bull queue stateless but having no idea how to.
Imagine a game, where timer starts and if user didn't do any action, delayed queue does it for him.

Let's say, User has 20 seconds to make a move, if within 20 seconds he does nothing, then queue should handle this. So there's few commands we'll need to use.

1) when we set up queue.
`Queue(game_id).add({ action: 'move' }, { delay: 20000, removeOnComplete: true });`

2) when we want to remove queue if user does the action.
`Queue(game_id).getJob(job_id).remove();`

3) and processing
```
Queue(game_id).process(function(job, done) {
  handle_job(job.data);
  return done();
});
```

So question is, I have to clean up those connections somehow (I can't set the Queue constructor state anywhere). Is there any way to do that?

Regards.

**Comment by manast** [comment]
I am not sure what you mean with connections, could you elaborate a bit more on your question?

**Comment by overflowz** [comment]
Sure! by default, constructor creates new redis client.
So if I do something like:

```
Queue(game_id).add(..)
Queue(game_id).getJob(..)
```

These two open two connections and in redis-cli monitor it shows up this (without processing):
```
1479134390.769057 [0 127.0.0.1:5074] "evalsha" "0b14d413279854aaf2eb414cd8ed6b9831dd348f" "4" "bull:TestQueue:delayed" "bull:TestQueue:active" "bull:TestQueue:wait" "bull:TestQueue:jobs" "bull:TestQueue:" "1479134390767"
1479134390.769057 [0 lua] "ZRANGE" "bull:TestQueue:delayed" "0" "0" "WITHSCORES"
1479134395.768343 [0 127.0.0.1:5074] "evalsha" "0b14d413279854aaf2eb414cd8ed6b9831dd348f" "4" "bull:TestQueue:delayed" "bull:TestQueue:active" "bull:TestQueue:wait" "bull:TestQueue:jobs" "bull:TestQueue:" "1479134395767"
1479134395.768343 [0 lua] "ZRANGE" "bull:TestQueue:delayed" "0" "0" "WITHSCORES"
```

which goes in loop. without having an actual instance of Queue, I can't make this messages to stop (because connections are still alive and they're doing it's job).

I'd like to apologize for my English and I'll try to pronounce the problem better with pseudocode.
I want something like this:

```
let q = Queue('TestQueue');
q.close(); // <-- this works fine, no more messages in redis-cli monitor.
```

```
Queue('TestQueue');
Queue('TestQueue').close(); // <-- this does not, I still see messages in redis-cli monitor.
```

**Comment by manast** [comment]
sorry, but that is not supported.
