### ISSUE TITLE
gracefully shutdown the queue when process be killed

### ISSUE THREAD

**Issue by xycloud** [OptimalBits/bull#382]
how to gracefully shutdown the queue when process is being killed or exit unexpected, any code?

**Comment by bradvogel** [comment]
Just this should work: `queue.pause(true /* Local */ ).then(() => process.exit(1))`

**Comment by bradvogel** [comment]
There might actually be a bug in it currently where it doesn't return. Let me know if it works for you.

**Comment by manast** [comment]
Closed due to lack of feedback.
