### ISSUE TITLE
Mocha as a deployment dependency.

### ISSUE THREAD

**Issue by gilr00y** [OptimalBits/bull#383]
Hi hi,
Is there a reason `mocha` is included in deployment `dependencies` as well as `devDependencies`(and at different versions)? If not I'm happy to PR.

**Comment by bradvogel** [comment]
Definitely a bug..

**Comment by manast** [comment]
fixed in https://github.com/OptimalBits/bull/commit/125c5638c1a908c094af04fc14f192d3f1923026
