### ISSUE TITLE
Broken constructor pattern from recent commit

### ISSUE THREAD

**Issue by gswalden** [OptimalBits/bull#384]
This commit https://github.com/OptimalBits/bull/commit/1f2d1bcba4993b1b38dc101b553e988523749c43 broke the alternative Queue constructor (from the README) `Queue(queueName, redisConnectionString, [redisOpts])`, as adding the `redisOpts` argument will cause `arguments.length === 3`, and which causes the later call to `redis.clientClient()` to break with `TypeError: Unknown type of connection in createClient()`.

I'm simply editing my code to get around this issue, but thought you should know!

**Comment by gswalden** [comment]
Example of break:
```js
const Queue = require('bull');
const myQueue = new Queue('q', 'redis://127.0.0.1', { keyPrefix: 'myQ' });
```

**Comment by manast** [comment]
thanks for the report and sorry for the mistake. It will be fixed asap.
