### ISSUE TITLE
Queue.add returns same jobId after consecutive calls

### ISSUE THREAD

**Issue by blacksonic** [OptimalBits/bull#385]
When calling ```Queue.add``` and logging the ```jobId``` in the returned Promise, it returns the same id within the same process. It caches the first one, but in the background it creates newer jobs, but the counter remains the same.

It can be experienced from version 1.1.0
Node version is 4.4.7

**Comment by manast** [comment]
could you please provide a small example code that reproduces this problem?

**Comment by blacksonic** [comment]
Seems like it is somewhere within our application, because on a brand new project it works...and we encounter it only during testing.

This sample works like a charm.
```
'use strict';

let Queue = require('bull');

let carQueue = new Queue('car', 6379, '127.0.0.1');

carQueue.on('completed', function(job, result){
  console.log(job.jobId + ' completed in ' + result.elapsed);
});

carQueue.process(function(job){
  console.log(job.jobId + ' processed');

  return Promise.resolve({ elapsed: Math.random() });
});

carQueue
  .add({ engine: 'V8' })
  .then((job) => {
    console.log(job.jobId);
    return carQueue.add({ engine: 'V6' });
  })
  .then((job) => {
    console.log(job.jobId);
  });
```

Just an idea: should the readme examples be transformed to use Promises instead of callbacks? It is not intentional, that the library can be used in a way i show in this short code snippet.

**Comment by manast** [comment]
Could it be that you are specifying a ```customId``` somewhere that is overriding the standard job id counter?

**Comment by blacksonic** [comment]
I see that sometimes the clock is stubbed with Sinon, maybe it breaks something.

**Comment by blacksonic** [comment]
Jobs never got to active state...cleaning up the queue before every test run resolved the issue.

**Comment by blacksonic** [comment]
Reopening it because it broke our production application also...same job ids everywhere.

**Comment by manast** [comment]
If you are not specifying a custom id, I cannot understand how you can get the same job id when you add new jobs. The script that ads a job atomically increases the job counter. What id are they receiving? 1 or some other random number?

**Comment by blacksonic** [comment]
Other random number.
And couldn't locate the commit to blame, because since https://github.com/OptimalBits/bull/commit/d55ad1c8f44f86be9b4e9f4fa9a3fc8a16c6e02d commit the code was completely broken until version 1.1.0 ... failing builds and broken code...no chance to checkout specific commits to install and test

**Comment by manast** [comment]
what does the job id counter has for value in your redis instance?, should be like this:
```bull:myqueuename:id```

**Comment by blacksonic** [comment]
The job is counter gets increased, it is correct, but the application is malfunctioning.

We are caching the instance of ```new Queue()``` for job creation, can this cause the problem?

**Comment by manast** [comment]
you need to be able to isolate the problem so that It can be reproduced, otherwise we cannot really do so much...

**Comment by manast** [comment]
This is the code that adds a job, maybe it gives you a hint:
https://github.com/OptimalBits/bull/blob/master/lib/scripts.js#L73-L140

**Comment by blacksonic** [comment]
@manast Found the issue: ```toJson``` method on the job modifies the input options object here https://github.com/OptimalBits/bull/blob/master/lib/job.js#L100 .
Which is a big problem, because it is the same ```options``` reference we give in when adding a new job item.

**Comment by blacksonic** [comment]
Here is the fix https://github.com/OptimalBits/bull/pull/386

**Comment by manast** [comment]
Good catch!
