### ISSUE TITLE
mention that data.jobId now is a String

### ISSUE THREAD

**Issue by fiws** [OptimalBits/bull#387]
`data.jobId` was a Number before v1.1.0.

This was a breaking change for us. 
You could describe that as an edge case, but imo this should at least be in the changelog.

**Comment by doublerebel** [comment]
Very likely could be my refactor that went into 2.0.0.

There is now a 1.1.3 release that may not have this issue for you, can you try it?

I think we should stay consistent with id as a number. I am working on a fix for 2.x today.

**Comment by bradvogel** [comment]
Can be closed. It was renamed to job.id anyways in 3.0
