### ISSUE TITLE
Improve priority queue

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#388]
Currently, the priority queue implementation is based on several bull queues. This implementation is both complex, low performant and difficult to maintain.
I am proposing an extension to the standard bull queue, where the jobs are added to the wait list in order. This will make the addJob a bit slower when using priority queues, but vastly bette and simpler than the current priority queue implementation.
I am thinking around the idea of keeping a zset with the current jobs and their priorities as scores. We can use [ZCOUNT](http://redis.io/commands/zcount) to decide at which index we should insert the new job using [LINSERT](http://redis.io/commands/linsert) to put the job in the correct position in the queue.
The extra job would be to keep the zset updated every time a job is moved from or to the wait queue, and do it so atomically. Performance wise, the LINSERT operation is O(N), and most ZSET operations are O(Log(N)), so although not being as fast as a pure priority queue, it would be quite acceptable considering the non-polling design, and its robustness.

**Comment by manast** [comment]
Update:
I have now a working prototype for the new priority queue. The code is much more simpler than before and does not require any extra queues or connections to redis. What is missing is different strategies as we had in the old implementation, for example exponential and square. Currently the strategy is that jobs with higher priority will be processed faster than jobs with lower priority. Not sure if I should add more strategies or release first what I have now...

**Comment by tinybug** [comment]
I'd love to try what you have now.😊

**Comment by manast** [comment]
https://github.com/OptimalBits/bull/pull/456

**Comment by manast** [comment]
I will merge it tonight if nobody complains...

**Comment by swayam18** [comment]
Any suggestions on what we could do if N is large? We noticed that a single LINSERT is taking 27ms (27000 microseconds) on average, because we have a few hundred thousand jobs in the queue.
