### ISSUE TITLE
TypeError: client.infoAsync is not a function

### ISSUE THREAD

**Issue by neofreko** [OptimalBits/bull#391]
Updating to `1.1.2` triggers the following error

```
8:56:42 PM worker.1 |  /Users/someproject/node_modules/bull/lib/queue.js:936
8:56:42 PM worker.1 |    return client.infoAsync().then(function(doc){
8:56:42 PM worker.1 |                  ^
8:56:42 PM worker.1 |  TypeError: client.infoAsync is not a function
8:56:42 PM worker.1 |      at getRedisVersion (/Users/someproject/node_modules/bull/lib/queue.js:936:17)
```

`master` has fixed this, which has `package.json` version `1.1.2`. But what getting pulled from npm still has `client.infoAsync` instead of `client.info`. More confusion, latest release were tagged with `1.1.1`.

**Comment by neofreko** [comment]
I was wrong. `master` still trigger similar issue:
```
TypeError: client.info(...).then is not a function
```
I reverted to bull@1.0.0 which does not have the aforementioned issue.

**Comment by manast** [comment]
When does this happen?

**Comment by neofreko** [comment]
It happens when I try to create new Queue

**Comment by manast** [comment]
so why are the tests passing?

**Comment by manast** [comment]
We have tests for instantiating the queue, and the call to infoAsync on 1.1.2 and info on master is working properly on these tests. So please if you can write a test case that I can use for reproducing the bug we can fix it afterwards.

**Comment by bradvogel** [comment]
Are you passing a redis instance to the constructor using createClient? If so, you'll have to pass an ioredis instance now.

**Comment by manast** [comment]
Will close this now, reopen if needed.
