### ISSUE TITLE
Support for Redis Sentinel

### ISSUE THREAD

**Issue by matylla** [OptimalBits/bull#396]
Hi there,

Now that `ioredis` is the default client in `bull` I think it would be a very good idea to support Redis Sentinel. Unfortunately the [current Redis config](https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L67) does not support Sentinel.

As I was digging through #379 (especially [this comment](https://github.com/OptimalBits/bull/pull/379#issuecomment-260675547)) I learned that you're worried that `bull` will loose lock guarantees during failover. While that might be true I personally think that High Availability is far more important than the risk of delivering a few messages twice because if Redis server goes down _no messages_ will be delivered.

I think the best approach to this would be to expose `client` property in the Queue config along with the current options for connecting to Redis. That way the user can decide if he wants to trade lock guarantees for high availability.

Redis Version 2.8.12 would need to be required for this to work properly.

One could create a new Queue like this:

````js
const Redis = require("ioredis");
const Queue = require("bull");

const connection = new Redis({
    sentinels: [{
        host: "host1",
        port: 26379
    },
    {
        host: "host2",
        port: 26379
    }],
    password: "redis-password",
    name: "my-master"
});

const videoQueue = Queue("video transcoding", {
    client: connection
});
````

This is really a cosmetic change to the connection method as `ioredis` handles Sentinels and failover.

**Comment by manast** [comment]
Although not properly documented, you can pass as redis options your own createClient function: https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L95-L103

regarding the lock, since we are using redlock, it should work pretty well with a redis cluster as well.

**Comment by matylla** [comment]
@manast thanks for pointing me to right direction. Just to verify: `createClient` needs to return Redis client, like so?

````js
const Redis = require("ioredis");
const Queue = require("bull");

const redisConfig = {
    sentinels: [{
        host: "host1",
        port: 26379
    },
    {
        host: "host2",
        port: 26379
    }],
    password: "redis-password",
    name: "my-master"
}

const videoQueue = Queue("video transcoding", {
    createClient: () => {
        return new Redis(redisConfig)
    }
});
````

**Comment by manast** [comment]
that should work, but I am noticing that the code handling that stinks a bit, so you may need to write it like this: 
```
Queue('foobar', 0, 0, myCreateClient);
```

**Comment by doublerebel** [comment]
@matylla You are quite right reading the tradeoff between Redis Sentinel and other types of Redis clustering, but Bull should support both now.  I was guessing that the common case for failover/cluster is Sentinel but I was hoping for some more user input before making a recommendation.  I use `createClient` option in the way **manast** describes, please give it a try with Sentinel and let us know your experience!

**Comment by matylla** [comment]
@manast @doublerebel Constructor mentioned by @manast seems to work as expected. Closing this ticket for now. I will update it once I'm done with initial failover tests. Thank you for your help.
