### ISSUE TITLE
RPC pattern possible?

### ISSUE THREAD

**Issue by floolean** [OptimalBits/bull#400]
I have one job which is composed of several sub-jobs. I want to control success or failure of the parent job inside the parent execution itself, i.e.:

- master job "media.generate" is created. 
- the function of the "media.generate" worker creates three temporary jobs, lets say "media.generate.image.{somereference}", "media.generate.sound.{somereference}" and  "media.generate.video.{somereference}", where "{somereference}" is a unique id
- "generate.media" then listens for "completed" and "failed" of those three jobs
- on another machine a worker is started by creating a queue that listens to "media.generate.image.*" pattern,  it executes the job and when completed or failed, the master job will be the only one getting the events and go on with its logic.

Do you think this scenario is possible with the current implementation?

Note: it would also be nice to wrap a promise around temporary queues.

**Comment by doublerebel** [comment]
> Note: it would also be nice to wrap a promise around temporary queues.

`queue.process` returns a promise that is resolved when the queue is closed.  There's an example [in the test case for 397](https://github.com/OptimalBits/bull/blob/c1b42a022fe69a150561c75449e23689687477ea/test/test_queue.js#L737).  A function could be attached to the job finished event, to close the queue if there are no more waiting or active jobs.

**Comment by NikosEfthias** [comment]
#474 please check this out im trying to implement something similar to rpc
