### ISSUE TITLE
Job.prototype.finished contains error in promise

### ISSUE THREAD

**Issue by jamesjjk** [OptimalBits/bull#402]
The promise returned from the finished will currently never complete if running multiple jobs in a queue. The problem lies in the conditionals encapsulated but the completed, failed events (pub sub) they should include removing the listeners and clearing the timer, the correct code should look more like the below:

Currently the code is:

```
if(job.jobId === _this.jobId){
            resolve();
          }
            removeListeners(); //ERROR WILL NOT RESOLVE IF EVENT IS FIRED
            clearInterval(interval); //ERROR WILL NOT RESOLVE IF EVENT IS FIRED
```

(Happy to commit a PR, awesome project btw!!)

```
return new Promise(function(resolve, reject){
    status(resolve, reject).then(function(finished){
      if(!finished){
        var interval;
        function onCompleted(job){
          if(job.jobId === _this.jobId){
            resolve();
            removeListeners();
            clearInterval(interval);
          }
        }

        function onFailed(job, err){
          if(job.jobId === _this.jobId){
            reject(err);
            removeListeners();
            clearInterval(interval);
          }
        }

        function removeListeners(){
          _this.queue.removeListener('completed', onCompleted);
          _this.queue.removeListener('failed', onFailed);
        }

        _this.queue.on('completed', onCompleted);
        _this.queue.on('failed', onFailed);

        //
        // Watchdog
        //
        interval = setInterval(function(){
          status(resolve, reject).then(function(finished){
            if(finished){
              removeListeners();
              clearInterval(interval );
            }
          })
        }, 5000);
      };
```

**Comment by jamesjjk** [comment]
@manast Would you accept a PR for the above issue?

**Comment by jamesjjk** [comment]
https://github.com/jamesjjk/bull/commit/22fc3ad488ca42dc43f898bfc65c0cde74db2f21

**Comment by jamesjjk** [comment]
@manast There seems to be another error in the conditionals. I think this may be related to the type conversion of jobId from INT to STRING. I checked the typeof values the conditionals are comparing in 
and noted that they differ, they would have to be both converted to string in order to get a truthy.

```
  console.log(typeof job.jobId, typeof _this.jobId); //outputs string number
```

Possible solutions, your thoughts?

```
function onCompleted(job){
          if(String(job.jobId) === String(_this.jobId)){
            resolve();
            removeListeners();
            clearInterval(interval);
          }
        }
```

**Comment by manast** [comment]
using '==' should be enough.

**Comment by jamesjjk** [comment]
@manast Would you not prefer to coerse the types first? rather then ==

**Comment by manast** [comment]
well its more explicit so I guess it is better to coerce.

**Comment by jamesjjk** [comment]
PR on its way. https://github.com/OptimalBits/bull/pull/405
