### ISSUE TITLE
PriorityQueue.getDelayed throws error

### ISSUE THREAD

**Issue by jamesjjk** [OptimalBits/bull#403]
PriorityQueue.getDelayed throws error. "this" in the genericGetter is undefined. There seems to be a scoping error when calling the genericGetter functions.

**Comment by manast** [comment]
yes, the priority queue is currently now well supported, thats why I created this issue: https://github.com/OptimalBits/bull/issues/388

**Comment by manast** [comment]
I may have time to resolve it during xmas...

**Comment by jamesjjk** [comment]
@manast Thanks! great work on Bull though, way more performant then Kue and a lot simpler then AMPQ equivalent solutions.

**Comment by manast** [comment]
A new pull request for the re-implementation of priority queues:
https://github.com/OptimalBits/bull/pull/456
