### ISSUE TITLE
How do I manage the redis space bull uses?

### ISSUE THREAD

**Issue by brandonmp** [OptimalBits/bull#411]
I've been running a bull queue w/ ~180k jobs for part of the last 24 hrs, but the space in my redis instance it consumes is only going up. here's the chart from my `redislabs` instance:

![image](https://cloud.githubusercontent.com/assets/14139991/21055154/4fad7638-bdfe-11e6-9aaa-7acee29a4b2c.png)

The 2 big spikes are when I added ~120k and ~60k jobs, and the flat spots are when the queue wasn't running.  The steep dropoff was when I turned off `replication` in `redis` to make more room.

Otherwise, as you can see, storage only goes up.

All jobs were added w/ this command: 

` myQueue.add({ imageID }, { removeOnComplete: true })`

And they're processed w/ this:

```
function processQueue() {
    var Queue = require('bull')
    var myQueue = Queue("myQueue", {
        redis: {
            port: 1234,
            host: "some.redis.instance"
        }
    })

    myQueue.process((job, done) => {
        let jobData = job.data
        doJob(jobData)
            .then(updateSqlDatabase)
            .then((err) => {
                if (err) {
                    throw err
                } else {
                    done()
                }
            })
            .catch(err => {
                log.error({ err })
                done(err)
            })
    })
    process.on('SIGINT', function () {
        console.log('Starting queue shutdown')
        myQueue.close().then(function () {
            console.log('Finished queue shutdown')
            process.exit(0)
        })
    })

}

```

I have 8 processes completing jobs in the queue, and the # of tasks in waiting is gradually declining. here's the current status from the `toureiro ui`:

![image](https://cloud.githubusercontent.com/assets/14139991/21055349/13f77ea8-bdff-11e6-87fe-de301f2c9c3f.png)

The 312 failed is expected, given the nature of the jobs, but it's been pretty static for awhile, so that's not what's chewing up space.

My `redislabs` instance is capped @ 100 MB, so I'd welcome any advice anyone has on making the queue more space-efficient :)

**Comment by doublerebel** [comment]
Once Redis has used memory, it tends not to free it but reserves it for future use.  There are some good notes [on the Redis website under Memory Optimization](https://redis.io/topics/memory-optimization):

>To store user keys, Redis allocates at most as much memory as the maxmemory setting enables (however there are small extra allocations possible).

> The exact value can be set in the configuration file or set later via CONFIG SET (see Using memory as an LRU cache for more info). There are a few things that should be noted about how Redis manages memory:

> Redis will not always free up (return) memory to the OS when keys are removed. This is not something special about Redis, but it is how most malloc() implementations work. For example if you fill an instance with 5GB worth of data, and then remove the equivalent of 2GB of data, the Resident Set Size (also known as the RSS, which is the number of memory pages consumed by the process) will probably still be around 5GB, even if Redis will claim that the user memory is around 3GB. This happens because the underlying allocator can't easily release the memory. For example often most of the removed keys were allocated in the same pages as the other keys that still exist.

**Comment by brandonmp** [comment]
Wow, that's great to know, thanks @doublerebel . That explains why my storage consumption isn't decreasing as I `done()` jobs, but I'm still left wondering why the consumption is steadily _growing_

**Comment by doublerebel** [comment]
I've always been able to leave my redis alone until actually receiving errors, the RSS memory reported by the OS does not have a direct relationship with the data stored in redis.  Have you received any memory-related errors from redis?

What is the output of `INFO memory` (the memory section of the INFO command)?

**Comment by brandonmp** [comment]
(closing b/c doesn't appear to be `bull`-related, but still interested in hearing others' thoughts

**Comment by sloops77** [comment]
hi brandon, we are also seeing unexpectedly high usage on redislabs. How does aws compare?

**Comment by jeltok** [comment]
Can it be related to https://github.com/OptimalBits/bull/issues/426 ?
