### ISSUE TITLE
Unable to renew nonexisting lock, crashes nodejs

### ISSUE THREAD

**Issue by yawhide** [OptimalBits/bull#413]
Hello,

Just starting playing with this library. I have a simple setup:
1) one process adds a job
2) a second process processes a job, calls jobDone in a setTimeout of randomly 1-5s, then when .on('completed') gets called, it re-adds the same job (so essentially creating an infinite loop of that specific job) _and_ adds a job to a third queue.
3) a third process processes the third queue just does some cpu intensive work (calls some zlib stuff). (this queue is just mainly just trying to be hard on the cpu to see if anything weird happens).
Sorry the setup is a bit confusing. I just wanted to say exactly what I am doing. I'll post some code if the lib crashes node again.

trying to repro, unsuccessful at the moment. 

I was there was an issue about this a week ago and it was resolved. but I guess it just happened again?

Here is the error.
```
/Users/work/bull/node_modules/bull/lib/scripts.js:314
      throw new Error('Unable to renew nonexisting lock');
      ^

Error: Unable to renew nonexisting lock
    at Object.takeLock (/Users/work/bull/node_modules/bull/lib/scripts.js:314:13)
    at Job.takeLock (/Users/work/bull/node_modules/bull/lib/job.js:127:18)
    at lockRenewer (/Users/work/bull/node_modules/bull/lib/queue.js:644:16)
    at Timeout.<anonymous> (/Users/work/bull/node_modules/bull/lib/timer-manager.js:80:5)
    at ontimeout (timers.js:372:18)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

### QA
- Is Bull being used with NodeJS cluster?
no
- How many concurrent workers are processing jobs?
able to repro with both 1 and many concurrent workers
- Does the error crash Bull, or do you just see it in the logs?
crashes bull
- Do any of these errors coincide with failed jobs?
no

**Comment by jamesjjk** [comment]
@yawhide Facing exactly the same problem. Again related to re-queing a previous job after it has been completed, this is an intermittent failure. May I ask are you using a custom job id?

**Comment by jamesjjk** [comment]
@yawhide https://github.com/OptimalBits/bull/issues/397 This seems to fix it.

**Comment by ryanmills** [comment]
+1 Receiving this error:

```
Error renewing lock LockError: Exceeded 0 attempts to lock the resource "bull:integrations-dev:93:lock".
Error: Unable to renew nonexisting lock at Object.scripts.takeLock (node_modules/bull/lib/scripts.js:314:13) at Job.takeLock 
(node_modules/bull/lib/job.js:127:18) at lockRenewer 
(node_modules/bull/lib/queue.js:644:16) at Timeout.<anonymous> 
(node_modules/bull/lib/timer-manager.js:80:5) at Timeout.ontimeout (timers.js:336:34)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5) '*** uncaughtException'
```

**Comment by blazindoritos** [comment]
This is the error I get:

`/<root>/node_modules/bull/lib/scripts.js:314
      throw new Error('Unable to renew nonexisting lock');
      ^

Error: Unable to renew nonexisting lock
    at Object.takeLock (/<root>/node_modules/bull/lib/scripts.js:314:13)
    at Job.takeLock (/<root>/node_modules/bull/lib/job.js:127:18)
    at lockRenewer (/<root>/node_modules/bull/lib/queue.js:644:16)
    at Timeout.<anonymous> (/<root>/node_modules/bull/lib/timer-manager.js:80:5)
    at ontimeout (timers.js:372:18)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)`

**Comment by prdn** [comment]
+1 happening to me too
```
Error renewing lock LockError: Exceeded 0 attempts to lock the resource "bull:production:93:lock".
```

**Comment by ryanmills** [comment]
Also receiving:

`Error: Unable to renew nonexisting lock at Object.scripts.takeLock (/node_modules/bull/lib/scripts.js:314:13)
    at Job.takeLock (/node_modules/bull/lib/job.js:127:18)
    at lockRenewer (/node_modules/bull/lib/queue.js:644:16)
    at Timeout.<anonymous> (/node_modules/bull/lib/timer-manager.js:80:5)
    at Timeout.ontimeout (timers.js:336:34)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5) '*** uncaughtException'`

**Comment by zekenie** [comment]
Throw my hat in here as well, I am having this error as well. The one thing that's complicating my setup is that I'm using the same redis connection for two purposes. One is for Bull, the other is a socket.io adapter so that my worker processes can essentially emit events to sent out by my http servers. Not sure if this is relevant.

**Comment by bradvogel** [comment]
The "Exceeded 0 attempts to lock the resource" issue is happening when running the unit tests for me. So this should be pretty easy to track down. @doublerebel could you help take a look?

**Comment by askdesigners** [comment]
Chiming in to say I get the same issue. Running redis in a DO droplet and running my 2 apps locally.

**Comment by manast** [comment]
seems like @doublerebel has left ut in the cold :). 
I will try to find some time to debug this, unfortunately I am on a very busy period right now.

**Comment by bradvogel** [comment]
I think we should consider reverting the ioredis and redlock work. I just don't see the benefit. We're still checking for locks inside of lua scripts (because we still need to), completely defeating the purpose of the redlock algorithm.

**Comment by manast** [comment]
The problem is that together with the ioredis we have many other improvements, for instance the unit tests run properly everytime now.

**Comment by manast** [comment]
So the question is how much work would it be to remove only redlock, or make it optional, and use the old locking mechanism.

**Comment by manast** [comment]
In any case, cheaper must be to analyze why this error happens and at least mitigate it so that the exeception is handled properly. I will try as soon as I can.

**Comment by askdesigners** [comment]
If it helps, I've noticed that this locking issue causes jobs to run twice on my remote redis server (digital ocean), but works properly when local... I assume that's what's causing it. i don't get this error locally. Is there some redis config that might be screwing with things?

**Comment by askdesigners** [comment]
Ok actually I've tracked my own issue down to renamed commands in the redis config file. The node-redis docs are really unclear on how to set those up in the library and I've probably done it wrong.

**Comment by raminious** [comment]
getting this error too

```
/bull-test/node_modules/bull/lib/scripts.js:289
      throw new Error('Unable to renew nonexisting lock');
      ^

Error: Unable to renew nonexisting lock
    at Object.takeLock (/Development/node/bull-test/node_modules/bull/lib/scripts.js:289:13)
    at Job.takeLock (/Development/node/bull-test/node_modules/bull/lib/job.js:128:18)
    at lockRenewer (/Development/node/bull-test/node_modules/bull/lib/queue.js:644:16)
    at Timeout.<anonymous> (/Development/node/bull-test/node_modules/bull/lib/timer-manager.js:80:5)
    at Timeout.ontimeout (timers.js:344:34)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by manast** [comment]
By fixing #441 I think I may also fixed this issue. It was a race condition when stopping the lock renewal timmer, where it was possible that the renewal was called even after the timmer was cleaned. I will make a new release very soon, great if you could verify that it solves your use cases.

**Comment by manast** [comment]
Please check if you still get this issue with version 2.1.2
