### ISSUE TITLE
LockError question

### ISSUE THREAD

**Issue by n3trino** [OptimalBits/bull#424]
I have a queue that is used to send apple push notification using [node-apn](https://github.com/node-apn/node-apn).

In the process function we are using concurrency like this:

```javascript
apnSandboxQueue.process(10, function(job, done) {
  let note = new apn.Notification();
  
//...Setting up note parameters

  apnSandboxService.send(note, job.data.devices)
    .then(function (result) {
      if (!_.isEmpty(result.failed)) {
        return gatherInvalidDeviceTokens(result.failed);
      } else {
        return Bluebird.resolve(true);
      }
    })
    .then(function(finshed) {
      done();
    })
    .catch(function (err) {
      done(err);
    });
});
```

If we send multiple requests to the queue we get this error:

`Error renewing lock LockError: Exceeded 0 attempts to lock the resource "bull:APN Sandbox Queue:170:lock".`

Also the queue has lock renew time set to 15sec `apnSandboxQueue.LOCK_RENEW_TIME = 15 * 1000; // 15sec` and runs in two instances (2 core CPU).

Can you please explain why we get this error? Also many times, jobs stuck to active state.

**Comment by manast** [comment]
@doublerebel do you have any hint why this could happen?

@n3trino btw, you do not need to use the ```done``` callback, you can just return the promised returned by ```apnSandboxService.send```

**Comment by n3trino** [comment]
@manast what does the **Error renewing lock LockError: Exceeded 0 attempts to lock the resource** means?

**Comment by n3trino** [comment]
@manast i found out why it leaves the jobs active. It has to do with node-apn and not bull itself.
