### ISSUE TITLE
Error: connect ETIMEDOUT, unusable stacktrace, redis conn params seem fine

### ISSUE THREAD

**Issue by GeoffreyPlitt** [OptimalBits/bull#427]
Hello,

I'm using Bull in a program that works fine for a while, and then we get these mystery errors from deep in your library. I've attached ```on('error', ...)``` handlers which don't seem to help, and the stacktraces below don't help either.

The redis connection string I'm providing works fine for everything else using it, and is not the issue.

----> Any help in how I can get more debug info, like stacktraces or something?

Error: connect ETIMEDOUT
3:56:34 PM prog.1  |      at Socket.<anonymous> (/Users/giro/prog/node_modules/ioredis/lib/redis.js:291:21)
3:56:34 PM prog.1  |      at Socket.g (events.js:286:16)
3:56:34 PM prog.1  |      at emitNone (events.js:86:13)
3:56:34 PM prog.1  |      at Socket.emit (events.js:185:7)
3:56:34 PM prog.1  |      at Socket._onTimeout (net.js:334:8)
3:56:34 PM prog.1  |      at tryOnTimeout (timers.js:232:11)
3:56:34 PM prog.1  |      at Timer.listOnTimeout (timers.js:202:5) errorno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'connect' }

**Comment by manast** [comment]
Have you got more info regarding this issue since you reported it?

**Comment by alecl** [comment]
@manast It would be handy to be able to attach handlers for ioredis events like error and reconnecting for example. I suspect there are cases where a Redis error can occur but it doesn't go into the Bull errors handler. I'm running into something like that that but having trouble repeating it enough to figure it out.

**Comment by manast** [comment]
@alecl you could do this by accessing the queue.client and queue.eclient ioredis instances.

**Comment by malixsys** [comment]
https://github.com/luin/ioredis/blob/master/lib/redis.js#L289
