### ISSUE TITLE
OOM command not allowed when used memory > maxmemory

### ISSUE THREAD

**Issue by GeoffreyPlitt** [OptimalBits/bull#433]
I'm getting an error I don't quite understand. My guess is that I need to upgrade the memory for Redis. Is that right?

  message: 'ERR Error running script (call to f_d5e879576feacc56627a3618fd6e20d53efe58de): @user_script:1: @user_script: 1: -OOM command not allowed when used memory > \'maxmemory\'.   ', 
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:    command:  
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:     { name: 'evalsha', 
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:       args:  
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:        [ 'd5e879576feacc56627a3618fd6e20d53efe58de', 
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:          '6', 
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:          'bull:elasticsearch_indexer:wait', 
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:          'bull:elasticsearch_indexer:paused', 
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:          'bull:elasticsearch_indexer:meta-paused', 
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:          'bull:elasticsearch_indexer:jobs', 
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:          'bull:elasticsearch_indexer:id', 
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:          'bull:elasticsearch_indexer:delayed', 
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:          'bull:elasticsearch_indexer:', 
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:          '', 
Jan 17 10:15:43 stardust-backend app/changes_enqueuer.1:          'data',

**Comment by GeoffreyPlitt** [comment]
Would cleaning queues resolve this?

**Comment by GeoffreyPlitt** [comment]
Also wondering if tasks are automatically cleared on completion, or if a huge amount of completed tasks build up in redis

**Comment by bradvogel** [comment]
You might be running into https://github.com/OptimalBits/bull/issues/426

**Comment by GeoffreyPlitt** [comment]
Thanks! Looks like exactly the same, I'll subscribe to #426.
