### ISSUE TITLE
Using fewer client connections?

### ISSUE THREAD

**Issue by woodardj** [OptimalBits/bull#439]
I get the rationale listed in issue #161 for why Bull uses three connections per queue, but this is becoming problematic for us as we have more and more dynos added to our infrastructure (we're running on Heroku), as with a priority queue in place we are rapidly hitting higher and higher tiers of Redis costs.

So I'm looking for ways to decrease our 'client connection' load.

We know for sure that some of our threads (web threads) will only be `.add`ing jobs to a queue (and occasionally re-trying fails), and our worker threads are doing both `.process` and sometimes also `.add`.

Is there any way we can instantiate a queue object, perhaps in our web threads, which doesn't require the 'locking' connection, nor the 'receive signals' connection?

**Comment by manast** [comment]
With the new priority queue implementation the number of connections will be reduced dramatically. It requires however a few days work, and I am quite busy at the moment, but it is high in the priority list: https://github.com/OptimalBits/bull/issues/388

**Comment by woodardj** [comment]
Oh rad, thanks @manast! Will this require a key schema change when upgrading? i.e., will we need to run workers in parallel to finish old jobs as we start working jobs from the new queue? Or will it be a seamless upgrade?

**Comment by manast** [comment]
I am afraid this will not be a backwards compatible upgrade from redis schema perspective, since we move from multiple queues to a single one.

**Comment by woodardj** [comment]
Thanks @manast — do you have a recommended upgrade path (we are currently on 1.1.3, so I guess this question applies to 2.x as well), since we can't run multiple npm package versions side by side, the upgraded version won't be able to work jobs off of the old queue.

**Comment by manast** [comment]
I guess that you will need to stop adding jobs until all are processed and then start the new queue. :)

**Comment by manast** [comment]
The pull request: https://github.com/OptimalBits/bull/pull/456

Basically I will keep the old priority queue as deprecated. With the new priority implementation you get a new option when adding jobs to a queue (priority), which inserts the job in the wait list at the proper slot so that higher priorities (highest will be 1, and decrease as the priority value decreases). The only feature missing so far is the possibility to select "strategies" for the queue, like exponential o square. These can be added later on, I do not think they are critical at this point.

**Comment by woodardj** [comment]
Thanks @manast ! Just getting around to implementing now — what is the default priority? I've changed all my 'criticals' to 1 and all my 'lows' to 5, but the new docs don't say what happens when priority isn't set.

**Comment by manast** [comment]
A job without priority (or priority 0) will be added as last element in the queue, so it can be considered to have infinity priority value so to speak.

**Comment by woodardj** [comment]
Got it — sorry to be a pest, I just want to make sure that I understand what will be happening.

With the new implementation, if my queue includes 100 high-importance tasks (p:0, with jobIDs 1-100, for example), then I cause two more tasks to be enqueued in Bull. One of which has p:0 (jobID 101), the other which has p:50 (jobID 102), what order do these new tasks go off, and when relative to the existing p:0 tasks?

**Comment by manast** [comment]
No. priority 0 is the same as not having any priority, so it ends last in the queue and executes last (unless you use lifo then it is the oposite). p:50 will be executed earlier that the others that have priority 0. Priority 0 is a special case, it is not a valid priority. You should use priorities 1 to MAX_INT, where 1 is highest priority and MAX_INT least.

**Comment by woodardj** [comment]
Sorry, I misspoke/mistyped. I mean p:1 in the question:

With the new implementation, if my queue includes 100 high-importance tasks (p:1, with jobIDs 1-100, for example), then I cause two more tasks to be enqueued in Bull. One of which has p:1 (jobID 101), the other which has p:50 (jobID 102), what order do these new tasks go off, and when relative to the existing p:1 tasks?

**Comment by manast** [comment]
in that case p:50 will be the last task, and jobId 101 will be next last.

**Comment by manast** [comment]
btw, we are a bit short in tests that only tests priorities, so feel welcome to write a test for that given scenario :)

**Comment by woodardj** [comment]
I can make a go of it, but am not super familiar with the environment. Will try. Thanks for building Bull!
