### ISSUE TITLE
[Question] How to best approach listing jobs ?

### ISSUE THREAD

**Issue by lipsumar** [OptimalBits/bull#440]
Hi there,

I'm surprised not to find a method such as `Queue.listJobs()` that would allow me to retrieve the current list of jobs (preferably along with their status).

Other queuing solutions also don't seem to provide this, so I'm wondering if I'm not on a very wrong path.

I'm aware of UIs to display the state of the queue, I'm using one, but here I simply want to give a feedback to my users about the state of the queue. So they can have an idea as when their job will be processed, and what is currently running.

Should I use the events and keep track of jobs myself ? But then what happens in case the app goes down ? Should I persist this list of jobs somewhere ? That doesn't seem the best approach either.

So here I am: is this a missing feature or should I view this problem differently ?

**Comment by manast** [comment]
In fact there are methods to list the jobs, unfortunately we have not been so good att documenting these methods, check this: https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L832-L854

**Comment by lipsumar** [comment]
Awesome! I'll do a PR soon for the docs

**Comment by fiws** [comment]
Those methods are very useful.
But is there a way to get the last x jobs ordered by date? I think this is the most common use case for Queue Dashboards

**Comment by manast** [comment]
@fiws that is not possible currently. If your queue is not very large you can of course do this client side. Otherwise a lua script would be more efficient, but redis is not really designed for this kind of queries on list, so it is not going to be very performant.

**Comment by manast** [comment]
We can now (version 3.0.0) get the jobs efficiently in all the states with ```start``` and ```end```arguments, which together with getting the counts for every state you can easily implement pagination.
