### ISSUE TITLE
Jobs waiting but not active

### ISSUE THREAD

**Issue by AlexSenchenko** [OptimalBits/bull#444]
Hi,

After deploying to server I see through Toureiro interface that 7 jobs in waiting state.
But I don't see that it became active. What can be the reason? May be need some trigger?

**Comment by manast** [comment]
The jobs are processed as they are added to the queue. Maybe the queue does not have a correct connection to redis.

**Comment by AlexSenchenko** [comment]
"bull": "2.1.1"
Well redis installed on same machine. Delay may be - but some times it takes 10-20 minutes or even run only from restart.

I saw from  `Toureiro` tool - that: 0 in Active - 0, Waiting - 7

How such behaviour can be tracked - any tips?

**Comment by manast** [comment]
Can you create a simple example that reproduces the issue?
