### ISSUE TITLE
Bluebird warning from bull constructor

### ISSUE THREAD

**Issue by wellcaffeinated** [OptimalBits/bull#445]
> Warning: a promise was created in a handler at internal/module.js:20:19 but was not returned from it, see http://goo.gl/rRqMUw
>  at new Promise (/.../node_modules/bluebird/js/release/promise.js:77:14)

Hi I can't silence this warning, but I've tracked it down to the bull constructor. When I comment out the call `bull( 'queue', config.redisURL )`, the warning disappears. Unfortunately the warning doesn't provide much information. But hopefully one of you can find the statement that's missing a `return null;`

**Comment by manast** [comment]
In which version of bull did you get this issue?

**Comment by wellcaffeinated** [comment]
3.10.3

**Comment by manast** [comment]
latest version is 2.1.2 ...

**Comment by wellcaffeinated** [comment]
Oops! I typed the wrong command to get the version (that's my npm version).
I'm using bull 2.1.2

**Comment by manast** [comment]
Could you please provide a small code snippet that reproduces this issue?

**Comment by wellcaffeinated** [comment]
False alarm.
Turns out it was in my code, however for some reason the error only showed up when I initialized bull. :/
