### ISSUE TITLE
Error processing job: SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by pine** [OptimalBits/bull#450]
Hello. I use this library.

I found this errors. Could not know how to solve?

```
Error processing job: SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at Function.Job.fromData (/home/ubuntu/project/Gabriel/node_modules/bull/lib/job.js:498:33)
    at /home/ubuntu/project/Gabriel/node_modules/bull/lib/job.js:63:18
    at tryCatcher (/home/ubuntu/project/Gabriel/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/project/Gabriel/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/ubuntu/project/Gabriel/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/ubuntu/project/Gabriel/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/ubuntu/project/Gabriel/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/ubuntu/project/Gabriel/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ubuntu/project/Gabriel/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ubuntu/project/Gabriel/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

```
$ node -v
v6.9.4

$ uname -a
Linux ip-172-31-30-203 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Thank you.

**Comment by manast** [comment]
Please provide an example that reproduces the bug and also in which version of bull you are getting it.

**Comment by pine** [comment]
The reproduction code is currently creating.

bull version is `2.1.2`.
And `Queue##count()` returns `0`, but the keys are left.

```
> keys *
 1) "bull:queue_7:44"
 2) "bull:queue_1:23"
 3) "bull:queue_0:completed"
 4) "bull:queue_3:905"
 5) "bull:queue_6:id"
 6) "bull:queue_1:id"
 7) "bull:queue_3:id"
 8) "bull:queue_1:30"
 9) "bull:queue_2:active"
10) "bull:queue_4:id"
11) "bull:queue_1:active"
12) "bull:queue_6:active"
13) "bull:queue_5:id"
14) "bull:queue_7:id"
15) "bull:queue_2:id"
16) "bull:queue_6:1036"
17) "bull:queue_3:26"
18) "bull:queue_4:active"
19) "bull:queue_1:29"
20) "bull:queue_1:26"
21) "bull:queue_7:active"
22) "bull:queue_4:132"
23) "bull:queue_0:id"
24) "bull:queue_3:1055"
25) "bull:queue_7:361"
26) "bull:queue_2:863"
27) "bull:queue_0:3428"
28) "bull:queue_0:active"
29) "bull:queue_1:32"
30) "bull:queue_1:34"
31) "bull:queue_3:active"
32) "bull:queue_0:613"
33) "bull:queue_3:6"
34) "bull:queue_4:298"
35) "bull:queue_4:690"
36) "bull:queue_0:577"
37) "bull:queue_0:523"
38) "bull:queue_1:25"
39) "bull:queue_7:1128"
40) "bull:queue_0:1190"
41) "bull:queue_4:140"
```

**Comment by jahraphael** [comment]
I encountered a similar problem on a project where I was using Bull. It occurred for me both in the 1.x and 2.x series. I ended up sticking to 1.x and patched `fromData` to no longer crash if it reads bad data from the queue. Instead it will drop the item and keep processing.

I have not tried to root-cause what is going on, so YMMV... but this is what I had done: https://github.com/jahraphael/bull/commit/dfe5d8e709014dcb6b525898c728b19390ef1118

**Comment by manast** [comment]
yes, whatever the underlying cause of this, it should not kill the process, just catch the error and report it.

**Comment by manast** [comment]
@If I put a ```throw Error()``` in ```Job.fromData``` the error is handled in the unit tests in version 2.1.2. I am wondering if you get this unhandled exception in an older versions of bull only?

**Comment by jahraphael** [comment]
I will try updating to 2.x in the project where I was having this problem and let it run on one of my production instances.

**Comment by jahraphael** [comment]
I let this ran for a bit today and noticed a lot of the original error message that pine mentioned. However, it looks like in 2.1.2 the process is not crashing, which is great!

The direct cause of the error above is that for some reason the job is that for some reason the data in the queue for that job is actually the string "undefined", which gives the above error when `JSON.parse` is called on it.

**Comment by manast** [comment]
@jahraphael yes. What i wondering is why the exception is not handled in the reporter code. Locally I cannot reproduce that unhandled exception, for example always throwing an error in the same place as the JSON.parse call.
