### ISSUE TITLE
Make variables setable

### ISSUE THREAD

**Issue by MatthD** [OptimalBits/bull#451]
Hello,

I found here that many people seems to have a lot of problem due to long time jobs.

I discover when I changed some varible to increase their timeout (+ other things) I won' have those problem anymore

I had to edited this file [Queue]( https://github.com/OptimalBits/bull/blob/master/lib/queue.js)

I setted the variable this way for my long jobs:

`CLIENT_CLOSE_TIMEOUT_MS = 60000;
 POLLING_INTERVAL = 60000;
 LOCK_RENEW_TIME = 60000;
 STALLED_JOB_CHECK_INTERVAL = 60000; 
`

Is it possible to make those variables options ?

**Comment by ryanmills** [comment]
+1 on ability to customize options including long job timeouts
