### ISSUE TITLE
failedReason and stacktrace not in Queue.on('failed') and on('error') not triggering

### ISSUE THREAD

**Issue by alecl** [OptimalBits/bull#453]
Seems like these should be there given there's interested in the failures if you're handling the failed event, no? If I call Queue.getJob these two fields are there.

Also, I was surprised that Queue.on('error') doesn't get triggered whether I throw an error inside process or pass an error object to the callback. Looking at the code seems this even is mainly for Redis connection errors and not job errors?

**Comment by manast** [comment]
when errors are thrown inside a process they are catched and the job is considered to have failed, this is by design. I agree that failedReason and probably stacktrace should also be available when a job has failed.

**Comment by alecl** [comment]
@manast Any chance failedReason and stacktrace can be added to the failed event in this upcoming release?

**Comment by manast** [comment]
It will need to go in the next release since the memory leak is a high prio issue that needs resolution.

**Comment by manast** [comment]
Actually, I am seeing that the event 'failed' is returning both the job and the error object that was thrown when the job failed. This error includes the "reason" and the stacktrace. Is it there any other thing you need?

**Comment by manast** [comment]
Please reopen if needed.

**Comment by alecl** [comment]
Confirmed. This is fine.
