### ISSUE TITLE
Help with retrying a failed job?

### ISSUE THREAD

**Issue by JohnWMay** [OptimalBits/bull#455]
Hello,

I am working with bull queues. I cannot figure out how to retry a failed job. I have job.retry() in the test_jobs.js file, but I can't get that to work, and don't see it in the code. I am also just starting to look at Promises. 

Will you please help me retry a failed job?

**Comment by manast** [comment]
Can you provide some test code that is not working?

**Comment by JohnWMay** [comment]
Yes, here is some:

This:
 
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//var Job = require('Job');
var Queue = require("bull");
var util = require("util");
var Promise = require("bluebird");
var myQueue = Queue("MyQueue");



myQueue.on('error', function(error) {
  // Error
  console.log("error event has error:"+error);
});
myQueue.on('ready', function(){
  console.log("queue is ready: ");

});

myQueue.on('active', function(job, jobPromise){
  // Job started
  // You can use jobPromise.cancel() to abort this job.
  console.log("job active: id: "+job.jobId);
  //console.log("queue.count: "+queue.count());
});

myQueue.on('completed', function(job, result){
  // Job completed with output result!
   console.log("job completed: id: "+job.jobId);
});

myQueue.on('failed', function(job, err){
  // Job failed with reason err!
   console.log("job failed: id: "+job.jobId + " with err?:"+err);
   myQueue.retryJob(job);
});


var init = function() {


    var jobError = new Error("Job Failed");
    myQueue.process(function(job, jobDone){
      console.log(" in process...");
      jobDone(jobError);
    });

      console.log(" adding data...");
    myQueue.add({foo: 'bar'});//.then(function(job){


};

init();

Yields this output:
[dev@localhost myFolder$ node mainExample.js 
 adding data...
queue is ready: 
 in process...
job failed: id: 44 with err?:Error: Job Failed
Possibly unhandled TypeError: undefined is not a function
    at Queue.<anonymous> (/home/dev/myFolder/mainExample.js:38:12)
    ...
    
    
    
    

And another attempt, is this:
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//var Job = require('Job');
var Queue = require("bull");
var util = require("util");
var Promise = require("bluebird");
var myQueue = Queue("MyQueue");



myQueue.on('error', function(error) {
  // Error
  console.log("error event has error:"+error);
});
myQueue.on('ready', function(){
  console.log("queue is ready: ");

});

myQueue.on('active', function(job, jobPromise){
  // Job started
  // You can use jobPromise.cancel() to abort this job.
  console.log("job active: id: "+job.jobId);
  //console.log("queue.count: "+queue.count());
});

myQueue.on('completed', function(job, result){
  // Job completed with output result!
   console.log("job completed: id: "+job.jobId);
});

myQueue.on('failed', function(job, err){
  // Job failed with reason err!
   console.log("job failed: id: "+job.jobId + " with err?:"+err);
   //myQueue.retryJob(job);
   job.retry();
});


var init = function() {


    var jobError = new Error("Job Failed");
    myQueue.process(function(job, jobDone){
      console.log(" in process...");
      jobDone(jobError);
    });

      console.log(" adding data...");
    myQueue.add({foo: 'bar'});//.then(function(job){


};

init();




which yields this output:
dev@localhost myFolder]$ node mainExample.js 
 adding data...
queue is ready: 
 in process...
job failed: id: 45 with err?:Error: Job Failed
Possibly unhandled TypeError: undefined is not a function
    at Queue.<anonymous> (/home/dev/myFolder/mainExample.js:39:8)
    at Queue.emit (events.js:110:17)
    
    
Also, it seems that my "Active" listener is not working in this example (although it is in other code we have).

I have also tried to get this to work, as I saw a coffeescript version in another commenter's entry:
setInterval(function () {
  myQueue.getFailed().then(function(jobs){
    return Promise.each(jobs, function(job) { 
       job.retry() 
      });
  });
}, 60 * 100);

I did see what to do with the Job##retry section of the API page, but was hoping to send back a doneCallback(err) in our code, and when the "failed" listener received this call, and the error is present, that it would retry the message, such as when a service the program needs is temporarily down or unreachable by HTTP request, and is returning HTTP 500 status errors, or request returns an err, and these are temporary conditions. It's a way that I'm hoping to use to keep our system from losing requests during reboots or network timeouts. If there's a better what to use the queues for that which you could advise, I'd be very grateful.

**Comment by manast** [comment]
Why can't you use the backoff option in the add job options?
```
backoff {Number|Object} Backoff setting for automatic retries if the job fails
```

**Comment by chiragpurohit71085** [comment]
When node server restarts 

attempts:5,
backoff: 50,

not working.

**Comment by manast** [comment]
@chiragpurohit71085 please provide a reproducible test case.
