### ISSUE TITLE
Multi Instance Concurrency

### ISSUE THREAD

**Issue by guischdi** [OptimalBits/bull#457]
### My setup
I have a multi instance application maintaining a bull job queue. All application instances off course use the same Redis instance. I configured bull to run a maximum number of 1 concurrent job. But this means that 1 job can be running concurrently PER INSTANCE of the application. So if I'm running two instances of the application, two jobs can be running in parallel.

### My usecase
What I want to have is only one job running in parallel. Because the performed operations of the job could possibly cause invalid data, if two jobs are concurrently updating the data.

### My questions
- Is it possible to define a concurrency over all application instances?
- If not: would it be possible to implement it in bull? 
- Or should the jobs implementation handle the global concurrency (for example by only starting the actual job operations after bulls `Queue.getActiveCount()` is less than 1)?

**Comment by guischdi** [comment]
Yes, we could handle it like this with only 1 worker process. But we want to have redundancy. In case one application instance dies, there should still be a worker to handle the jobs. Any solution for this?

**Comment by manast** [comment]
Ok, so it is more like a failover scenario than pure redundancy. I would say that the solution is to have a mechanism to quickly launch a new worker if one dies. Having more than one will always imply concurrency (besides redundancy).

**Comment by guischdi** [comment]
Ok. Thx. So a global concurrency is not possible with bull. My second question was, if it would be possible that this is a new feature of bull?

**Comment by manast** [comment]
probably not because it is really hard to implement a distributed system that works as a single instance, somehow it defeats the point if I understand your case correctly...

**Comment by deugene** [comment]
Hi. I had the same problem, so I made a module, named [oraq](https://www.npmjs.com/package/oraq) to handle per instance concurrency. And you can use in with bull and also like a separate queue manager.

Example:
```js
const Bull = require('bull');
const Oraq = require('oraq');

const connection = {
  port: 6379, 
  host: '127.0.0.1'
};
const queue = new Bull('firstBullQueue', {
  redis: connection
});
const limiter = new Limiter({
  connection,
  concurrency: 1
});

queue.on('error', console.error);
queue.on('failed', async (job, err) => {
  console.warn(`Job "${job.data.name}" failed with error "${err.message}"`);
});
queue.process(job => limiter.limit(runJob, {
  jobId: job.id,
  jobData: job,
  lifo: job.opts.lifo
}));
```

**Comment by LeonidEfremov** [comment]
Wrong `limiter` definition:
> const limiter = new Limiter({
>   connection,
>   concurrency: 1
> });

follow this interface

```javascript
  interface RateLimiter {
    /** Max numbers of jobs processed */
    max: number;
    /** Per duration in milliseconds */
    duration: number;
    /** When jobs get rate limited, they stay in the waiting queue and are not moved to the delayed queue */
    bounceBack?: boolean;
  }
```
