### ISSUE TITLE
support for async/await?

### ISSUE THREAD

**Issue by ianstormtaylor** [OptimalBits/bull#465]
Right now it seems like `async/await` is supported for use in `process()`, but if an `await`'d function throws an error, then the whole thing errors with:

```
(node:26602) Warning: a promise was created in a handler at /Users/Storm/dev/contentshq/workers/node_modules/bull/lib/queue.js:712:9 but was not returned from it, see http://goo.gl/rRqMUw
     at new Promise (/Users/Storm/dev/contentshq/workers/node_modules/bluebird/js/release/promise.js:79:10)

```

Am I doing something wrong, or is this a bug?

**Comment by manast** [comment]
Can you provide code that reproduces the error?

**Comment by manast** [comment]
I will take a look at it anyways, I want to understand the reason for the warning

**Comment by raminious** [comment]
@ianstormtaylor 
please change 
```
queue.process(async (job) => {
  throw new Error('error!')
})
```

to

```
queue.process(async function (job) {
  throw new Error('error!')
})
```
and check again.
I experienced this issue with babel.

**Comment by ianstormtaylor** [comment]
@raminious I'm not sure what you mean, did you mean to say "think" instead of "doubt"?

**Comment by raminious** [comment]
@ianstormtaylor I doubt it, because I'm not sure 100%.
Btw please see this  eslint-plugin-babel/issues/8 for more information

**Comment by LegNeato** [comment]
FWIW I am using bull with async/await and haven't seen any issues. Also using arrow functions
