### ISSUE TITLE
bug in keyprefix support

### ISSUE THREAD

**Issue by alecl** [OptimalBits/bull#466]
If I add a keyPrefix in the redis options the jobs are named correctly but the key prefix is doubled for the queues and other keys. I am trying to use a keyPrefix to have multiple non-production environments on the same redis server via a keyPrefix to distinguish them. I cannot use different database id's in redis as RedisLabs doesn't support that.

```
let queuedWeather = queue('queued weather', redisOptions.port,
  redisOptions.host,
  { keyPrefix: 'my-bull' });

queuedWeather.add(wJob1, { delay: 20000, attempts: 2, backoff: { type: 'exponential', delay: 3000 }, removeOnComplete });

queuedWeather.add(wJob2, { delay: 5000, attempts: 2, removeOnComplete });
```

**Redis Keys**
```
"my-bull:queued weather:1"
"my-bull:queued weather:2"
"my-bullmy-bull:queued weather:id"
"my-bullmy-bull:queued weather:active"
```

**Comment by manast** [comment]
Check this out: https://github.com/OptimalBits/bull/issues/305
There is a workaround for this, it was a bug introduced with the upgrade to ioredis.

**Comment by alecl** [comment]
I'm not sure I understand the workaround. I've tried both keyPrefix and prefix and the rest is the same.
