### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by n3trino** [OptimalBits/bull#467]
Hello i am using bull with node v6.9.1 and pm2 v.2.4.2. When i upgraded to latest bull version (2.2.3) i saw that memory usage went to 1.5Gb in a development server which most of the time is idle. I reverted bull to version 2.1.2 and the problem disappeared. 

Can you please let me know what you need from my side to find out why this happens?

**Comment by manast** [comment]
1.5Gb sounds like quite a lot. We had a memory leak that was fixed in 2.2.3. see this issue: https://github.com/OptimalBits/bull/issues/426
But this was a leak making the memory usage grow over time. How is your scenario? does the memory usage grow immediately when the queue starts? can you make a reproducible test for this?

**Comment by n3trino** [comment]
Same here the memory grows over time. I will try the 2.2.4 version and i will let you know

**Comment by manast** [comment]
can you write a minimal piece of code that reproduces this so that I can check it locally?

**Comment by n3trino** [comment]
@manast it will try so as i am not expert in nodejs. One interesting thing, the issue appears on v6.10.0 nodejs. I installed v7 nodejs and i think the problem disappeared.

**Comment by manast** [comment]
@n3trino that is really strange actually...

**Comment by n3trino** [comment]
@manast I managed to get memory heap snapshots. I couldn't figure out what's wrong. You can [downloaded them](https://www.dropbox.com/s/7z5jmhgz3vx41da/memoryheap.zip?dl=0) from here and maybe you can figure out.

**Comment by n3trino** [comment]
@manast did have a chance to see the memory heapshots? if so, did you figure out what wrong?

**Comment by manast** [comment]
I checked the snapshots but I could not get any valuable information. Best would be to get a minimal test case that reproduces the issue, so I can try to find where the root of the leak is.

**Comment by n3trino** [comment]
@manast i figure out that running my node app + bull in development environment it creates this high memory/cpu situation. In production environment it works like a charm. Is there anything special happening in Bull when it runs at development environment?

**Comment by manast** [comment]
There is nothing different that I am aware of, at least in bull's code.

**Comment by manast** [comment]
As far as I can see, there are no memory issues with latest version of bull (3.0.0). so I will close this issue for now. Reopen if needed.
