### ISSUE TITLE
DOCS: any benchmarks?

### ISSUE THREAD

**Issue by lpgeiger** [OptimalBits/bull#468]
I see an interesting claim about being the fastest queue. :) 
Here's the only benchmark I could find: https://github.com/LewisJEllis/bee-queue/issues/50
Would be nice to compare to Kue and Bee-queue. 

The latter has some benchmarks that seem out of date: https://github.com/LewisJEllis/bee-queue/tree/master/benchmark

**Comment by manast** [comment]
They are out of date, and where not updated after my request, but at least they do not claim being the fastest anymore :). I may add a benchmark that can be kept up-to-date to guarantee that the performance is not lost as we add/improve features un bull.

**Comment by keyscores** [comment]
As a suggestion you could take the benchmark code at bee-queue and run it
on your CI server after the unit tests are run. It would be a good way to
make profiling Bull's performance open to the community.

**Comment by lpgeiger** [comment]
@manast Any new here? Would be nice to see how you perform against Bee.

**Comment by manast** [comment]
It's coming soon, with the 3.0 release.
