### ISSUE TITLE
queue works only one time when used with another queue for dublex communication

### ISSUE THREAD

**Issue by NikosEfthias** [OptimalBits/bull#471]
i have a server and socket when user connects ws server opens a new queue to receive and another queue to send response back and on the api side one queue sends job to the socket server and waits for the reply then send the response to the user back. However this scenario works only once , when i send request second time it just hangs untill timeout
here is my socket server

```javascript
//socket.js
const io = require("socket.io")(3001);
const queue = require("bull");
io.on("connection", function (socket) {
	const q = socket.request["_query"];
	const id = q["id"];//get the id from the conn string
	console.log(id);//test
	const recv = queue(id);
	const notify = queue(id + "back");
	recv.process(function (job, done) {
		console.log(job.data);
		// setTimeout(function () {
			console.log(id+"back");
			notify.add({data:"job done",id:job.data.id});
			done();
		// }, 3000);
	})
});
```

```javascript
//api

router.post("/:id", function (req, res) {
	const uid = req.params.id;
	const corrId = uuid.v4();
	queue(uid).add({data: uid + "heydehdy", id: corrId});
	queue(uid + "back").process(function (msg, done) {
		if (msg.data.id == corrId) {
			console.log(uid + "back from api");
			res.send(msg.data);
			done()
		}
	});
});
```

**Comment by manast** [comment]
I am not sure what the problem could be, but in this case:
```js
queue(uid + "back").process(function (msg, done) {
		if (msg.data.id == corrId) {
			console.log(uid + "back from api");
			res.send(msg.data);
			done()
		}
	});
```
if *msg.data.id != corrId* the job will never be processed and the queue will not advance. Furthermore If you want to create a new queue per request I recommend you that you reuse the connection to  redis, you can find information on how to do that in the README.

**Comment by NikosEfthias** [comment]
@manast this is for just test purpose thats why i dont that much care about reusing connections here i especially did == rather than != because there has to be a spawner of every request and that should handle the done-reply .

There's one part i dont quite understand with the structure though, This structure i made works nice with event based aproach because all the event handlers are run in every event fire.But if this is recursive way re-triggered by the `done` its understandable that it wont work because i guess you have to lock at some point in order to prevent race condition over the same job and in that case the very processor that has been started for the first time will try to handle the situation however it will not sattissfy the if condition here.

**Comment by NikosEfthias** [comment]
for horizontal scaling nginx with iphash ensures that the same user will hit the same instance always so on that im totally relying on nginx and uuid @manast

**Comment by NikosEfthias** [comment]
@manast the problem was somehow if an error is thrown it didn't run the last catch statement of the promise so instead I have added catch after every pipeline and called the done and seems that fixed the problem.
