### ISSUE TITLE
queue processor doe not lock on multi connections

### ISSUE THREAD

**Issue by NikosEfthias** [OptimalBits/bull#474]
```js
io.on("connection", function (socket) {
	const q = socket.request["_query"];
	const id = q["id"];//get the id from the conn string
	console.log(id);//test
	const recv = queue(id);
	recv.process(function (job, done) {
		const notify = queue(job.data.replyTo);
		console.log(job.data);
		setTimeout(function () {
		console.log(job.data.replyTo);
		notify.add({data: "job done"});
		done();
		}, 3000);
	})
});
```

I have a code looks like this so for the same user `q["id"]` the queue should be processed only by one processor however if the user is connected from 2 tabs in the browser it starts to process 2 jobs at a time 
![](https://ww2.sinaimg.cn/large/006tNbRwgy1fe3q2rvx5fj31kw07gmzp.jpg)
as you can see in the photo there are 3 users connected and it processes 3 at a time instead of serializing them

**Comment by manast** [comment]
you seem to be using a queue per user. Queues are independent from each other and therefore executes in parallel.

**Comment by NikosEfthias** [comment]
is there any locking mechanism that I can implement such as `queue.isProcessing` or `queue.isLocked` in order to prevent the other processors

**Comment by manast** [comment]
The only way to guarantee order is having just one queue. Your alternatives are waiting till the named process function support is merged or that you define one large process function that “switches” behaviour depending on some job.data property that you define when adding jobs to the queue.

**Comment by NikosEfthias** [comment]
i found my way out by creating a local locks array if the id is already in there the process function is not run and i clean it up in the end of the queue or error

**Comment by NikosEfthias** [comment]
here is the pattern i used
```js
const io = require("socket.io")(3001);
const queue = require("bull");
const locks = [];
io.on("connection", function (socket) {
	const q = socket.request["_query"];
	const id = q["id"];//get the id from the conn string
	console.log(id);//test
	if (locks.indexOf(id) == -1) {
		locks.push(id);
		const recv = queue(id);
		recv.process(function (job, done) {
			const notify = queue(job.data.replyTo);
			console.log(job.data);
			setTimeout(function () {
				console.log(job.data.replyTo);
				notify.add({data: "job done"});
				done();
			}, 3000);
		})
		recv.on("completed", _ => {
			locks.splice(locks.indexOf(id), 1);
			recv.clean(500)
		})
	}
});
```

**Comment by manast** [comment]
instead of an array for locks I would suggest to use a object, since the current test (O(n)) can become slow if you have many clients...

**Comment by NikosEfthias** [comment]
I see, thank you now I'm upgrading array to an object.

**Comment by NikosEfthias** [comment]
before i made a similar task runner in series. I used redis lists to do tasks (`rpush and lpop`) in my code i was registering a processor with a global lock and on every request a new processor was checking whether an active processor is working on the queue at the moment if not it started processing otherwise it was just returning. So in my case i was checking queue status on every request  but in your case i noticed even if all the items have finished to be processed you still keep the same processor active and seems like kinda pinging it from add if i guess correct. In this case do you handle the disconnect or other error cases. i mean how can i make sure that there will be always a queue running ?

**Comment by NikosEfthias** [comment]
I asked this because I noticed that completed event is fired for every single item in the queue so, I cannot rely on that in order to remove the lock in the current scenario the lock is always on but is something happens with the processor will the bull make sure it continues processing or will it just stop ?

**Comment by manast** [comment]
it will work as long as there is a connection to redis, it will handle autoconnects automatically, etc.

**Comment by NikosEfthias** [comment]
i see. So can i assume that removing lock on error is safe ?

**Comment by manast** [comment]
you need to close the queue if you do not want to keep a redis connection for ever.

**Comment by NikosEfthias** [comment]
i have actually ever-lasting redis connections in my project so i dont think this might be an issue

**Comment by manast** [comment]
instead of calling clean on every complete event, use the removeOnComplete option when adding the job: https://github.com/OptimalBits/bull#add
