### ISSUE TITLE
in too frequent usage queue is handled from the middle

### ISSUE THREAD

**Issue by NikosEfthias** [OptimalBits/bull#477]
here i am making couple of requests 
![](https://ww1.sinaimg.cn/large/006tNbRwgy1fe3yxskruqj31kw0czdgw.jpg)
as you see it is handled nice in the beginning but after a while some requests just hand some others are handled instead then when it finishes its impossible to use bull anymore even if i delete the items from redis bull does not continue anymore

**Comment by manast** [comment]
Please provide reproducible code so that I can help you find the issue.
