### ISSUE TITLE
active priority job auto move to failed when restart worker

### ISSUE THREAD

**Issue by tinybug** [OptimalBits/bull#483]
If there is an active priority job in a queue, then I restart the worker one or two times when the job in active state, the job will move to failed,  and the worker's code doesn't run at all. You can reproduce this in the test_queue.js, comment the flush redis code before the test.

**Comment by manast** [comment]
Since the old queue code is deprecated (and removed) I will close this now. Please feel free to open it again if the issue still exists on 3.0.0
