### ISSUE TITLE
Improve README on instructions on how to create queues compatible with cluster

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#487]
Since we have many atomic operations that require to work on all the keys used by the queue, the only way to make a bull queue work on a clustered redis environment is to make sure every queue's keys are placed in the same node. It should be as simple as using as queue prefix ```{myprefix}``` instead of the standard ```bull```prefix:

https://redis.io/topics/cluster-spec#keys-hash-tags

**Comment by prafulliu** [comment]
hi, @manast 

`Queue(queueName: string, redisPort: number, redisHost: string, redisOpts?: RedisOpts): Queue`

you can set `prefix` in `redisOpts` with the `keyPrefix`

reference: 
1. https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options
2. https://github.com/OptimalBits/bull/blob/master/REFERENCE.md

**Comment by manast** [comment]
This is now documented in the patterns section.
