### ISSUE TITLE
Add Jobs with PHP, what is delayed "score" for?

### ISSUE THREAD

**Issue by mintzs** [OptimalBits/bull#492]
I've been using bull for a week now and came through the need to add jobs from my PHP server (Laravel framework). I wrote a simple class the actually works great (!) for regular and delayed jobs. I just have one lack of understanding at this time and think it might be problematic in some cases I haven't covered yet.

My question is: **what is the "score" for** in the Redis delayed set and how should I compute it?
Here's the class's code (see my TODO in the addToTargetQueue function).
I hope others can benefit from it as well!
Thanks :)

    class Bull
    {
        /**
         * @var
         */
        private $redis;

        public function __construct()
        {
            // init redis
            $this->redis = Redis::connection();
        }

        /**
         * @param $queue
         * @param $data
         * @param array $options https://github.com/OptimalBits/bull#add
         */
        public function add($queue, $data, $options = []){
            $hasCustomId = false;

            if (array_key_exists('jobId', $options)){
                $jobId = $options['jobId'];
                $hasCustomId = true;
            }
            else {
                $jobId = $this->allocateJobId($queue);
            }

            // default options
            $opts = [
                'jobId' => $jobId,
                'delay' => 0,
                'attempts' => 1
            ];

            // merge options
            $opts = array_merge($opts, $options);

            // start multi
            $this->redis->multi();

            // if custom id provided, increase id count
            if ($hasCustomId) {
                $this->redis->incr('bull:' . $queue . ':id');
            }

            // set job
            $this->redis->hMSet('bull:'.$queue.':'.$jobId, $this->getJobParams($data, $opts));

            // add to queue
            $this->addToTargetQueue($queue, $jobId, $opts);

            // execute multi
            $this->redis->exec();
        }

        function getJobParams($data, $opts){
            return [
                'returnvalue'=>'',
                'data'=>json_encode($data),
                'progress'=>0,
                'attempts'=>$opts['attempts'],
                'stacktrace'=>json_encode([]),
                'opts'=>json_encode($opts),
                'delay'=>$opts['delay'],
                'failedReason'=>'',
                'attemptsMade'=>0,
                'timestamp'=>time()
            ];
        }

        function addToTargetQueue($queue, $jobId, $opts){
            // "delayed" queue
            if ($opts['delay'] > 0) {
                $this->redis->zAdd('bull:'.$queue.':delayed', [$jobId => 0]); // TODO what is "score" for?
                return;
            }

            // default "wait" queue
            $this->redis->lPush('bull:'.$queue.':wait', $jobId);
        }

        function allocateJobId($queue){
            $this->redis->multi();
            $this->redis->get('bull:'.$queue.':id');
            $this->redis->incr('bull:'.$queue.':id');
            $res = $this->redis->exec();
            return $res[0] === null ? 0 : $res[0];
        }
    }

**Comment by manast** [comment]
The score is a timestamp, where the delayed job should be placed back in the queue and processed as quick as possible after that. There is a small twist to it though, since you could have several jobs placed in the same timestamp, we offset the timestamp with the job counter. You can see the lua code for this in this addJob (https://github.com/OptimalBits/bull/blob/atomic-move/lib/scripts/addJob.lua) script (note that this is the new addJob script for bull 3.0.0, but it is mostly the same as the code in 2.x). it occurs to me that you could just use this lua script in your php code as well, should make your life simpler :).

**Comment by mintzs** [comment]
@manast , Thanks for the quick response!
For the time being, I just translated the value calculation. I might integrate the lua script later on though.

This is the translation:
`(($params['timestamp'] + $params['delay']) * 0x1000) + ($jobCounter & 0xfff);`

**Comment by manast** [comment]
Great, I will close this issue now then.
