### ISSUE TITLE
count() and clean() a queue by job name?

### ISSUE THREAD

**Issue by ianstormtaylor** [OptimalBits/bull#494]
Hey @manast,

The new "job naming" functionality looks awesome! I'd like to use it myself to limit the number of queues created and move all of my workers onto a single queue that uses job naming instead, to reduce the number of connections. Looks very promising!

Is there a way to `count()` and `clean()` by job name? (Maybe `empty()` too?)

It seems like those are the missing pieces to be able to fully use the single-queue approach. Without them some things aren't possible. 

What do you think?

**Comment by manast** [comment]
It is possible to implement, but if the queue has many jobs it can become slow, because it requires to examine every job before it can be counted or cleaned. Seems like the current design is not really appropriate for these kinds of operations.

**Comment by ianstormtaylor** [comment]
Hmm damn. Maybe this is similar to the idea of "topics" that was brought up in another issue a while back? Except that instead of the topics being collections of queues, they'd be subsets of an existing queue.

I know nothing about Redis really, so this next part might not make sense...

Right I'm assuming the queues are using something like a `bull:{queue}` key for jobs. Would the architecture need to change to `bull:{queue}:{topic}` for that to be supported? Or would you then need to still have a connection for every topic to make that work?

I feel like the concept of "topics" inside of a single queue is powerful for code organization. And also in terms of reducing the amount of connections needed. The key is that they enable you to perform actions at a queue _or_ topic level.

**Comment by manast** [comment]
Well, if the issue is just the number of collections, with the new bull 3.x, every queue will require 2 connections, but you can reuse these 2 connections with as many queues as you want (as long as they are in the same process of course). 
Topics is a powerful concept, and it is related to stuff like parent-child relationships (https://github.com/OptimalBits/bull/issues/340). These features will be addressed after 3.x which will give us a better foundation than the 2.x branch which has grown a bit out of proportion.

**Comment by ianstormtaylor** [comment]
Gotcha, that makes total sense. For me it was a way to try to reduce connections while still maintaining the functionality of queues. But it sounds like 3.x with the shared connections will be much better for that! Thank you!

**Comment by xorbis** [comment]
Did you end up for a solution to count() jobs in a queue by they name?
I'm using NestJs Queue.
