### ISSUE TITLE
The callback does not always work

### ISSUE THREAD

**Issue by fredddy123** [OptimalBits/bull#500]
When I use 2.2.6 version, queues sometimes working wrong, callback doesn't calls.

**Comment by manast** [comment]
Can you provide an example that reproduces the issue?

**Comment by fredddy123** [comment]
Unfortunately, I can't. I can only assume, maybe it has something to do that redis is located in different server from servers which uses bull.

**Comment by manast** [comment]
Will have to close then. I will re-open if you can provide more information.
