### ISSUE TITLE
Emit global events from inside the lua scripts

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#501]
Currently we emit global events using an external module *disturbed*: https://www.npmjs.com/package/disturbed

This means that some operation, for example adding a job to the queue, is executed atomically via a lua script but the event is not emitted until the script has returned. Emitting the event inside the lua script itself has 2 advantages, firstly, it is a bit faster since a roundtrip to the redis instance is avoided, and secondly, it reduces a bit the chances for hazards, where at least we can guarantee that the event was emitted if the operation succeeded. It also makes the code more modular, since the events are actually emitted close to their context, instead of being emitted in an arbitrary place in javascript land.

**Comment by bradvogel** [comment]
+1

**Comment by bradvogel** [comment]
This will also solve a current bug where we're not checking the [job.moveToCompleted](https://github.com/OptimalBits/bull/blob/v3.0.0/lib/queue.js#L715) and [job.moveToFailed](https://github.com/OptimalBits/bull/blob/v3.0.0/lib/queue.js#L725) responses from the redis script, and emitting the 'completed' / 'failed' events anyway. This could cause two 'completed' events to get emitted for the same job.
