### ISSUE TITLE
Possible memory leak if too many process

### ISSUE THREAD

**Issue by kievechua** [OptimalBits/bull#503]
node: v6.9.5
bull: ^3.0.0-alpha.1
```
for (const name of lodash.range(11)) {
  bull.process(name.toString(), function ({ data }) {
    console.log('here')
  })
}
```

It will throw this error
`(node:83132) Warning: Possible EventEmitter memory leak detected. 11 resumed listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by manast** [comment]
yeah, I noticed myself, probably not a leak though, just that we use more listeners than the max setting. I will confirm it and increase the limit to avoid the warning in the future.

**Comment by ianstormtaylor** [comment]
I'm seeing this too, although I'm seeing it for `error` and `message` listeners, which I assume is still the same or a similar problem.

```
(node:15205) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15205) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15205) Warning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by manast** [comment]
are you seeing it in the latest alpha release as well?

**Comment by ianstormtaylor** [comment]
@manast oh nice I didn't realize that that fix was in the alpha! I haven't tried `3.x` yet because I wasn't sure what is changing, so I figured I'd play it safe until it's stable. (But no, this is from the non-alpha, so feel free to ignore!)

**Comment by weeco** [comment]
@manast  I just noticed that warning message again in Bull 3.3.0:

> (node:7572) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 global:completed listeners added. Use emitter.setMaxListeners() to increase limit
> (node:7572) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 global:failed listeners added. Use emitter.setMaxListeners() to increase limit

Might be a completely different cause though.

**Comment by manast** [comment]
cannot say without a code example

**Comment by mxstbr** [comment]
This is happening for me in `v3.3.1` when I create more than 11 queues with this code:

```JS
function createQueue(name) {
  const queue = new Queue(name);

  queue.on('stalled', job => {
    const message = `Job#${job.id} stalled, processing again.`;
  });
  return queue;
}
```

**Comment by manast** [comment]
@mxstbr just follow the hint you get from the warning :)
```
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 global:completed listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by mxstbr** [comment]
Yeah but how do I get the emitter in the first place? Is that a global variable in Node?!

**Comment by manast** [comment]
its global

**Comment by mxstbr** [comment]
Ohh that explains a lot, thanks @manast!

**Comment by mxstbr** [comment]
Getting "emitter is not defined" warnings. :confused:

**Comment by manast** [comment]
https://nodejs.org/api/events.html#events_eventemitter_defaultmaxlisteners

**Comment by mxstbr** [comment]
```JS
const emitter = new EventEmitter();
```

But I don't have access to the instance bull uses, that's what I'm saying, so I can't do this:

```JS
bullEmitter.setMaxLIsteners()
```

**Comment by manast** [comment]
```EventEmitter.setDefaultMaxListeners()```

**Comment by ritter** [comment]
Does not work in Node v6.11
> `EventEmitter.setDefaultMaxListeners()`

**Comment by manast** [comment]
sorry my bad, just use ```EventEmitter.defaultMaxListeners``` as explained in the URL above.

**Comment by ritter** [comment]
It's a property, not a method.
```
const EventEmitter = require( "events" );  
EventEmitter.defaultMaxListeners = 100;
```

**Comment by ritter** [comment]
thanks @manast

**Comment by mxstbr** [comment]
Oh that works, my bad. Thank you!

**Comment by niksmac** [comment]
Is it in current stable release?
