### ISSUE TITLE
Returning Job Completions

### ISSUE THREAD

**Issue by janober** [OptimalBits/bull#506]
Was wondering about the "Returning Job Completions" part in the documentation. It says a seconds queue should be used to get the job-results.

I started to use the queue-events "global:completed" and "global:failed" instead and check for the job ids. Is there a problem with doing it like that? Like is there for example no guarantee that this evens actually fire?

Thanks!

**Comment by manast** [comment]
The events are using pubsub, and therefore not reliable, specially in cases of disconnections. Using the pattern described is the best way to guarantee delivery, but also, if the receiver is offline when the job is processed it will get the result as soon as it starts next time.

**Comment by janober** [comment]
Ah ok. That explains it then.

Should maybe be mentioned in the event documentation just in case other people are not aware of it either.

Thanks a lot!
