### ISSUE TITLE
DOCS: done() and results.

### ISSUE THREAD

**Issue by lpgeiger** [OptimalBits/bull#522]
The docs could use some examples for the Queue.process and done() syntax. For example:

```` 
var count = 0

sendQueue.process(function(job, done){
    console.log("Received message", job.data.msg);
    
     if (count === 2) {
        // only returns a result after the second attempt
       done(null, job.data.msg)
     } else {
      // makes the process fail
       done('err', null)
     }
    count++
  });`

**Comment by manast** [comment]
Hmm, in the Quickstart section, the first example looks like this, is it not what you are after?
![image](https://cloud.githubusercontent.com/assets/95200/25682545/e2c13ce4-3058-11e7-94e7-b2958ba6c649.png)

**Comment by lpgeiger** [comment]
Ok now I see it. The API reference section could be more explicit. Thanks again.
