### ISSUE TITLE
Released version has code I cannot find in repository. 

### ISSUE THREAD

**Issue by emilsedgh** [OptimalBits/bull#525]
I started using bull a few days ago.

Today I finally started to deploy bull to production. Therefore, I needed to use redis connection strings.
The url string I was providing was being ignored. Therefore I started to debug bull.

I found the issue. The function `redisOptsFromUrl` was never being called.

So I started to browse the history to find the function. But I couldnt. It wasnt in the HEAD.

So checked out the commit 9f9a041 which apparently is the latest released version.

But the code installed by npm (on lib/queue.js) is even different than this revision.

So i cloned the repository and I cannot find the function `redisOptsFromUrl` _anywhere_ in history.

[This](https://pastebin.com/c23K0YQr) is the `lib/queue.js` installed by npm.
(MD5: `227d2b8f5711b3d294fb211bfccc0bc4`)

[This](https://github.com/OptimalBits/bull/blob/9f9a041702d15a5ca0a6560c51d1673d69a9419d/lib/queue.js) is the file that is supposed to be installed by npm.

**Comment by manast** [comment]
You are probably looking into the wrong branch: 
https://github.com/OptimalBits/bull/blob/v3.0.0/lib/queue.js#L81
https://github.com/OptimalBits/bull/blob/v3.0.0/lib/queue.js#L210
I recommend that you do not use the alpha versions for production, latest stable is 2.2.6.
