### ISSUE TITLE
[minor issue] Publish missing git tags

### ISSUE THREAD

**Issue by chuym** [OptimalBits/bull#532]
Looks like some tags are missing in the repo, particularly, the latest release as of now listed in npm is: `3.0.0-alpha.4` but this tag doesn't exist in the github remote: https://github.com/OptimalBits/bull/tree/v3.0.0-alpha.4

It would be handy to have it pushed to github to reference to the source directly in here or checking it out on a local repo.

**Comment by manast** [comment]
fixed, bu unfortunately the alpha 3 sha has been lost.
