### ISSUE TITLE
Docs: Changelog: add notes about Bull 3.0

### ISSUE THREAD

**Issue by bradvogel** [OptimalBits/bull#545]
I think we should collapse all the Bull 3.0 alpha releases in https://github.com/OptimalBits/bull/blob/master/CHANGELOG.md into one Bull 3.0 release with notes:
* Rewritten for rock-solid stability and performance: operations are now performed atomically!
* *BREAKING API CHANGES*:
  * `job.jobId` changed to `job.id` (for clarity)
  * The `ready` event was removed and replaced with `queue.isReady()` which returns a Promise
  * `failed` and `completed` sets are now Redis ZSETs. This means you must start over with a new empty, queue (if you do not, you'll get the error `WRONGTYPE Operation against a key holding the wrong kind of value`)

**Comment by marshall007** [comment]
@bradvogel another breaking change is `opts.createClient()`. I think it used to be `opts.redis.opts.createClient()`. This is currently wrong in the "patterns" documentation as I mentioned in https://github.com/OptimalBits/bull/pull/531#issuecomment-306916704.

**Comment by manast** [comment]
I think all this issues have been addressed already.
