### ISSUE TITLE
empty and close never resolve

### ISSUE THREAD

**Issue by thomasthiebaud** [OptimalBits/bull#554]
I have this kind of code

```js
const Queue = require('bull')

class Engine {
  constructor() {
    this.queue = new Queue()

    this.queue.on('error', err => console.error(err))

    this.onSuccess = (result) => {
      console.log(result)
      return this.queue.empty().then(() => this.queue.close())
    }

    this.queue.add([/*...*/], {
      removeOnComplete: true,
      removeOnFail: true,
    })
  }

  start () {
    this.queue.process((job, done) => {
      for(/*...*/) {
        if (end) {
          this.onSuccess(end)
        } else {
          this.queue.add(/*...*/)
        }
      }
      done()
    })
  }
}
```

My algo is working as expected, and `this.onSuccess` is called as expected with the correct result, but `this.queue.empty()` and `this.queue.close()` never resolve.

I tried to debug but I cannot catch an error using `this.queue.on('error, ...)` or using the `NODE_DEBUG=bull` environment variable.

Does someone already had this problem ?

**Comment by manast** [comment]
I cannot reproduce queue.empty not resolving. However, in the following code I need to call close with the ```doNotWaitJobs``` as true, since close is waiting for the current job to finish, and it will not resolve until that happens:
```
'use strict';
const Queue = require('../');

var queue = new Queue('asdf');

queue.on('error', err => console.error(err))

var onSuccess = (result) => {
  return queue.empty().then(() => queue.close(true));
}

queue.add({foo: 'bar'}, {
  removeOnComplete: true,
  removeOnFail: true,
});

queue.process((job, done) => {
  onSuccess().then(function(){
    console.log('done')
    done();
  });
});
```

**Comment by thomasthiebaud** [comment]
Thanks a lot for your answer. I will have a look this evening. 

Regarding the option `doNotWaitJobs`, maybe you should add it in the documentation [here](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueclose)
