### ISSUE TITLE
Should we use cache or storage mode?

### ISSUE THREAD

**Issue by mxstbr** [OptimalBits/bull#570]
We're using Compose for hosting Redis, and they offer a selection between [cache mode and storage mode](https://help.compose.com/docs/redis-cache-and-storage-modes):

> **"Storage" mode** [...] operates as a high-performance in-memory store optimized for performance and data safety and expanding through autoscaling as needed. As more data arrives in the database, so its use of RAM goes up.
>
> The **"Cache" mode** is the alternative. Here the auto-scaling is disabled and the Redis database does not expand. That means it gets to rely on Redis to evict items from memory depending on what eviction policy is selected. That policy is set in a configuration setting called `maxmemory-policy`.

To me it sounds like storage mode might be preferable with `bull` since we don't want Redis to just evict random jobs when running out of memory, is that correct?

**Comment by manast** [comment]
Yes, sounds like storage mode should work better. However there are ways to avoid a queue from growing in size indefinitely like removing completed/failed jobs, check the documentation for more info about this.

**Comment by mxstbr** [comment]
Thanks for the quick answer, it's working perfectly so far. Also thanks for making an awesome package!
