### ISSUE TITLE
Error on adding a repeat job

### ISSUE THREAD

**Issue by skyjia** [OptimalBits/bull#571]
Hi,
When I tried to add a repeat job with below codes, I got this error:

> ReplyError: ERR Error running script (call to f_404f0337c05abba3418247045244c0ea8c11c764): @enable_strict_lua:14: user_script:58: Script attempted to access unexisting global variable 'bit' 

```js
    const queue = new Queue(queueName, {
      redis: redisOps
    })

    const cron = '* * * * *'  // Every minute
    const jobData = {userId: 12345}
    queue.add(jobData, {repeat: {cron: cron}})
```

And I notice that `addJob-7.lua` use that global variable.

https://github.com/OptimalBits/bull/blob/402a1a4c82899d5e2c7ff82801a7eec4d8d29189/lib/commands/addJob-7.lua#L58

Versions:
- bull: ^3.0.0-rc.2
- redis: 2.8.17
- node: v8.1.0
- os: macOS 10.12.5

Please advise.

**Comment by manast** [comment]
Ok, it seems that version does not support the bitop library, I will fix bull so that it warns about it. from the redis site:
```bitop
The Lua Bit Operations Module adds bitwise operations on numbers. It is available for scripting in Redis since version 2.8.18.
```

**Comment by skyjia** [comment]
@manast This error has gone since I upgrade my Redis to v3.x.

Please update the README.md.  It says "Bull requires a Redis version greater than or equal to 2.8.11".  😃

**Comment by manast** [comment]
done!
