### ISSUE TITLE
bull/lib/queue.js:726:9 but was not returned from it

### ISSUE THREAD

**Issue by ladeiko** [OptimalBits/bull#574]
bull/lib/queue.js:726:9 but was not returned from it

**Comment by manast** [comment]
Can you please clarify? I do not see more than a one line comment in that line: https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L726

**Comment by ladeiko** [comment]
(node:56) Warning: a promise was created in a handler at /app/node_modules/bull/lib/queue.js:726:9 but was not returned from it, see http://goo.gl/rRqMUw
0|cr-serve |     at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)

**Comment by manast** [comment]
ok. I do not get that warning, but it is usually a matter of returning null for example.
