### ISSUE TITLE
job.returnvalue not populated in 3.0.0-rc.2

### ISSUE THREAD

**Issue by gswalden** [OptimalBits/bull#579]
After upgrading to `3.0.0-rc.2`, I noticed the `returnvalue` property is no longer populated. See these two demonstrations.

```js
const Queue = require('bull');

const doneQueue = new Queue('testing callback');
function doneResult(id) {
  setTimeout(function() {
    doneQueue.getJobFromId(id).then(job => {
      console.log('callback job returnvalue', job.returnvalue);
    })
  }, 1000)
}
doneQueue.process((job, done) => {
  doneResult(job.id);
  done(null, 'callback result string');
})
doneQueue.add({ testing: true });
```

```js
const Queue = require('bull');
const promiseQueue = new Queue('testing promise');
function promiseResult(id) {
  setTimeout(function () {
    promiseQueue.getJobFromId(id).then(job => {
      console.log('promise job returnvalue', job.returnvalue);
    })
  }, 1000)
}
promiseQueue.process(job => {
  promiseResult(job.id);
  return Promise.resolve('promise result string');
})
promiseQueue.add({ testing: true });
```

Upon inspecting the `job` object returned from `getJobFromId()`, I did not see any new properties containing the string I passed to `done()`.

**Comment by gswalden** [comment]
Also, here's a working code sample on `2.2.6`

```js
const Queue = require('bull');
const promiseQueue = new Queue('testing promise!');
function promiseResult(id) {
  setTimeout(function () {
    promiseQueue.getJobFromId(id).then(job => {
      console.log('promise job returnvalue', job.returnvalue);
    })
  }, 1000)
}
promiseQueue.process(job => {
  promiseResult(job.jobId);
  return Promise.resolve('promise result string');
})
promiseQueue.add({ testing: true });
```

Changes:
<img width="1071" alt="screen shot 2017-06-16 at 14 10 17" src="https://user-images.githubusercontent.com/3459542/27239109-909ee29c-529d-11e7-9d48-6b6e59a19604.png">

**Comment by manast** [comment]
Can you try this code instead:
```js
const Queue = require('bull');
const promiseQueue = new Queue('testing promise');

promiseQueue.process(job => {
  return Promise.resolve('promise result string');
})
promiseQueue.add({ testing: true });

promise.Queue.on('completed', function(job){
  console.log('promise job returnvalue', job.returnvalue);
});
```

**Comment by gswalden** [comment]
That works but it's also a separate use case, as it assumes you only want to the return value in realtime. If you want to check the return value of a job that finished 10 seconds ago, you'd be back to my original issue.

**Comment by manast** [comment]
The problem is that you are assuming that the job is completed after 1 second, and although reasonable, it is not guaranteed. I would not advice to use code like that even if it worked in a test environment.

**Comment by manast** [comment]
You can also check this passing test case:
https://github.com/OptimalBits/bull/blob/master/test/test_queue.js#L510-L529

**Comment by gswalden** [comment]
The same result occurs even if we trigger the delayed function after the `completed` event.
```js
const Queue = require('bull');
const promiseQueue = new Queue('testing');
promiseQueue.on('completed', function(job) {
  console.log('returnvalue during event listener: ' + job.returnvalue)
  setTimeout(() => {
    promiseQueue.getJobFromId(job.id).then(job => {
      console.log('returnvalue anytime after: ' + job.returnvalue)
    })
  }, 1000)
})
promiseQueue.process(job => {
  return Promise.resolve('promise result string');
})
promiseQueue.add({ testing: true });
```
Result:
```
returnvalue during event listener: promise result string
returnvalue anytime after: null
```

**Comment by gswalden** [comment]
For greater visibility, I created [gswalden/bull-test](/gswalden/bull-test)
Branch `master` is using bull v2.2.6, and you can see the [passing Travis CI test](https://travis-ci.org/gswalden/bull-test/builds/244013911)
[Pull request #1](/gswalden/bull-test/pull/1) updates to bull v3.0.0-rc.2, and the [test fails](https://travis-ci.org/gswalden/bull-test/builds/244014439)

**Comment by manast** [comment]
I am working on a fix.
