### ISSUE TITLE
Improve error handling of the calls to private method "run"

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#58]
There are several places in the code where run is called without handling the possible returned error. It actually returns a promise that could generate an error event on the queue instance.

**Comment by doublerebel** [comment]
It looks like now there are only 4 places run is called:
* [queue.js#L332](https://github.com/OptimalBits/bull/blob/7a891205d3810dac90b0c46fe975ab6bef78b528/lib/queue.js#L332)
Logs error to console

* [queue.js#L343](https://github.com/OptimalBits/bull/blob/7a891205d3810dac90b0c46fe975ab6bef78b528/lib/queue.js#L343)
Logs error to console, and rethrows to be caught by a Promise handler for queue.process

* [priority-queue.js#L88](https://github.com/OptimalBits/bull/blob/31783c509a57df4a892761bbb3b06ea2bf239692/lib/priority-queue.js#L88)
Does not log to console, returns to be caught by a Promise handler for priorityQueue.process

* [priority-queue.js#L177](https://github.com/OptimalBits/bull/blob/31783c509a57df4a892761bbb3b06ea2bf239692/lib/priority-queue.js#L177)
Unhandled error

My preference would be to return the promise as in `priority-queue.js#L88` and not log to console, forcing the user to handle the error as they like.

My issue with logging to console, is that it's hard to determine the source of a plain error without more logging context.  If the user handles all logging then they can insert whatever context necessary.

Right now `'error'` events raised on a Queue are primarily bubbled up from the redis client streams, so I think it's useful to keep that separate from the `.process` error handling.

**Comment by manast** [comment]
error handling has been vastly improved in version 3.0.0 so I will close this for now.
