### ISSUE TITLE
Passing returnValues between repeatable jobs

### ISSUE THREAD

**Issue by jozsi** [OptimalBits/bull#583]
Hello,

I'm glad to see that finally we have repeatable jobs available. The code has changed a ***lot*** compared to my previous implementation. I've spent some time figuring out what would be the best way, but I am unsure: how could I pass the returnValue (or any kind of field set on the `job` inside the `.process` handler), so I could access it from the newly created/repeated job?

My use case is very simple: I want to compare the results between two repetitions of the job.

Thanks!

**Comment by manast** [comment]
Every repetition is a new job, so the return value should be stored in the job so that it can be requested and compared with other jobs.

**Comment by jozsi** [comment]
The return value is stored, yes - but I don't know the job ID of the previous repetition. Only the latest repetitions key is stored for reference. This might be related to job relationships/dependencies/complex jobs, so I thought the easiest way would be to alter the job data before the next repetition, like:
```js
  queue.process('testing', job => {
    const result = 'my result';
    // I thought job would be referenced for creating the next repetition job
    // but wouldn't get persisted in the actual job, due to the LUA script
    job.data.previousResult = result;
    // I was wrong, because the new job will be added with the original `job.data`
    return Promise.resolve(result);
  });
```

**Comment by manast** [comment]
Ok, I think I understand what you want to achieve. So somehow being able to modify the job.data for every repetition would solve your problems right?

**Comment by jozsi** [comment]
Yes, that's correct.

**Comment by jozsi** [comment]
Done via https://github.com/OptimalBits/bull/pull/686/files
