### ISSUE TITLE
Adding a job with 3 parameters (name, data, opts) ignores given unique jobId

### ISSUE THREAD

**Issue by Oliver-G** [OptimalBits/bull#590]
In case I use `queue.add` with 3 parameter `jobId` will be an incremented integer but not the given unique identifier I defined in `JobOpts`. The desired behaviour is not usable: add a job only once until it is complete. Using `queue.add` with 2 parameter it works fine.
Here is a shorten example of my code:
```
var Queue = require('bull');
var queue = new Queue('myTasks', {redis: {port: 6379, host: '127.0.0.1', db: 3}});
var JobOpts = {
   jobId: "fixTask1",
   removeOnComplete:true
};
queue.add('customJobName', {jobCategory:'jobCat1',doSomething:'yeah'}, JobOpts).then(function(job){
   debug('job.jobId', job.jobId);
   //  job.jobId =>  an incremented integer on each queue.add
});

queue.add({jobCategory:'jobCat1',doSomething:'yeah'}, JobOpts).then(function(job){
   debug('job.jobId', job.jobId);
   //  job.jobId => "fixTask1" 
});
```

**Comment by manast** [comment]
Can you please test if you get the same behaviour in 3.0-rc3? In 3.0 the property is not called .jobId anymore but just .id (on the JobOpts it is till called jobId though).

**Comment by Oliver-G** [comment]
In 3.0-rc3 works everything fine.
