### ISSUE TITLE
Naming of job causes 'Missing process handler for job type...'

### ISSUE THREAD

**Issue by dreamcatcha** [OptimalBits/bull#599]
I have setup bull following the examples and when I add a job like this:

`myQueue.add({ MyData: MyData }, { removeOnComplete: true });`

it works fine but when I add a job name:

`myQueue.add('MyJob', { MyData: MyData }, { removeOnComplete: true});`

if gives me the error "Missing process handler for the job type MyJob"
I have created the process:

```
myQueue.process(function(job, done){
    // my processing code here
});
```

I'm at a loss to what I'm doing wrong, or if there is an issue here

**Comment by manast** [comment]
You need to define a process handler for ```MyJob```
```js
myQueue.process('MyJob', function(job, done){
    // my processing code here
});
please close if this resolves your issue.

**Comment by dreamcatcha** [comment]
Ahh, thank you very much!
