### ISSUE TITLE
Remove repeatable job based on processing result

### ISSUE THREAD

**Issue by Maximization** [OptimalBits/bull#600]
I have a cron job that runs every x seconds. After the job is done, based on the result, I'd like the previous processing run to be the last one and remove the job from the queue. Also ideally I'd like to change the cron value based on some result output. But if I can remove the repeatable job then I could accomplish this by removing the old repeatable job and adding a new one with new cron parameters.

I've tried using job.remove() and job.discard() during the 'completed' event but that wouldn't work since it would remove the current job which has just been completed and not the next repeatable job placed in the queue when the current job was moved to active.

I've also tried changing the repeat options directly through job.opts.repeat = .. but this wouldn't work for the same reason.

What's the recommended approach here? I'd be happy to provide some code if that would help paint a clearer picture.

**Comment by jozsi** [comment]
Regarding the options, see #583 - even though my scenario requires `data` to be changed, it could work with `opts` as well. It's really helpful if you express your use case/opinion before the implementation starts.

**Comment by Maximization** [comment]
Ok so here's my use case. I have a repeatable job that polls an API every 10 seconds for 15 min.

```js
queue.add({ id: '1' }, {
  repeat: {
    cron: '*/10 * * * * *', // every 10 seconds
    endDate: Date.now() + (1000 * 60 * 15), // for 15 min
  },
  removeOnComplete: true,
})

queue.process('repeatable jobs queue', async (job) => {
  // Make an API call using job.data.id
  const body = api.get(job.data.id)

  if (body.state === 'DONE_AND_CONFIRMED') {
    // We've received confirmation, do some processing
    ...
   }

  return body.state;
})
```
Let's say possible states are DONE and DONE_AND_CONFIRMED. DONE will almost always be followed by DONE_AND_CONFIRMED but DONE is not always a predecessor state for DONE_AND_CONFIRMED. On DONE_AND_CONFIRMED I want to: 1. stop the repeatable job. On DONE I want to: 2. change the cron specification of the job (or remove current one and add a new one) to every minute for 1 hour (0 * * * *). However, I only want to do this on a state change from previous state to state === 'DONE'. So only the first time I encounter it and not all the times after that. For this I can either read the cron options or set a flag on job.data. I've solved this with a flag.
```js
queue.on('completed', (job, result) => {
  if (result === 'DONE_AND_CONFIRMED') {
    // 1. Remove repeatable job
    ...
  } else if (result === 'DONE' && !stateHasChanged) {
    // 2. Change cron specification of repeatable job
    ...
    job.data.stateHasChanged = true
  }
})
```
How do I accomplish 1 and 2? (or 1 since I can just remove old job and add a new one which will have the same effect)

**Comment by manast** [comment]
Very similar to #582. Will increase priority on this issue.

**Comment by Maximization** [comment]
A heads up for when you start working on this issue.

The current hack proposed by @andrewburgess where you can get the next job iteration by adding the same job to the queue and using the return value works. However, it leaves the repeatable job in memory. While the next iteration that might look something like `repeat:__default__: 54229d8f43b07802002514c3:1499369640000` is removed the repeatable job itself `repeat:__default__: 54229d8f43b07802002514c3:*/10 * * * * *` is left behind. In some cases this might up and result to a cluttered redis. I've worked around this issue by composing the key as is done by bull and removing the key directly in redis like this
```js
const repeatKey = `${queue.toKey('repeat')}:${job.name}:${job.opts.repeat.jobId}:${job.opts.repeat.cron}`;
await queue.client.del(repeatKey);
```
The ideal implementation of this solution would also not only remove the next job iteration but also the initial repeatable job itself :)

**Comment by manast** [comment]
hmm. The repeat key could be deleted automatically after it has reached its ```endDate```. I have still to find a consequent API for removing repeatable jobs. Since the repetition is created implicitly by having an option when adding a job, it is not completely trivial to find a method that symmetrically  removes the repetition key.

**Comment by manast** [comment]
Btw, I want to change how the repeat keys are stored. Instead of a key per repeatable job, I want to use a hash and store all the keys in there. Besides keeping the key space cleaner, it is also easier to list the repeatable jobs that are currently programmed in a queue.

**Comment by Maximization** [comment]
That seems like a good idea. Will have to see if there's anything that hashes can't do (or do much slower) than regular keys can. Also hashes have a max size to be aware of. But it does seem much cleaner yeah, easier for UI libs too. In terms of API I'd say to not reinvent the wheel too much and see what's already out there in other languages. I'm not familiar in this territory I'm afraid. We're locking our production to the latest commit assuming there's going to be breaking changes that we'll have to manually look at. Let me know if I can help with testing.

**Comment by manast** [comment]
ok. Actually at the end I have settled for ZSET instead of a hash. There are several reasons for this, but the nicest one is that it fit well with the getJobs functions that we had. We can get pagination and also get in order which will be the next repeatable jobs etc. Nice for UIs.

**Comment by ritter** [comment]
I've also run in to this issue with repeat jobs that I'd like to conditionally remove after running.  It's a bit cumbersome at the moment to use a redis client, dig through, and delete the appropriate keys.

**Comment by plarsson** [comment]
The hack to add the same job again to be abled to remove a repeatable job doesn't seem to work any more in version 3.2. Is the only option right now to do a delete manually against redis?

**Comment by manast** [comment]
I am not aware of any appropiate way to do this, I will elevate the priority of this issue.

**Comment by manast** [comment]
Ok. I have a solution in the works. I just need a few unit tests and then I will submit a PR.

**Comment by shem8** [comment]
Great, let us know if we can help with something. I'm waiting for this feature too.

**Comment by manast** [comment]
Only thing missing is to fix the test so that it works in travis, locally it passes.
