### ISSUE TITLE
Add multiple repeatable jobs with the same cron pattern

### ISSUE THREAD

**Issue by Maximization** [OptimalBits/bull#601]
In my use case I have multiple repeatable jobs with the same cron pattern that are created and removed programatically. I do not know beforehand how many jobs will be at any given time.

According to this line https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L506 the uniqueness of repeatable job keys is determined by the prefix, queue name, 'repeat', job name and cron string. Which means I can only try and differentiate the keys with the queue or job name variables, both for which I need to instantiate separate queue workers to process them. This works well when the jobs are predefined before but is less convenient when jobs are added and removed on the go.

If I try to add multiple jobs with the same cron pattern they get the same key and therefore only one will exist at a given time. JobId seems to not play a role with repeatable jobs.

Is there a way to accomplish this or a workaround for the existing code?

**Comment by manast** [comment]
It is a quite interesting case what you are proposing. Without too much thought, it seems that it can be easily accomplished  if the ```repeatKey``` is generated also taking into consideration the ```opts.jobId```. This would break backwards compatibility, but it is a nice and easy to implement feature so I will see how can I fit it in.

**Comment by Maximization** [comment]
@manast Awesome! That would work neatly. Do you want to accept a PR or think it's better to do it yourself?

**Comment by manast** [comment]
PR:s are always welcome :D
