### ISSUE TITLE
v3.0 RC.4?

### ISSUE THREAD

**Issue by marshall007** [OptimalBits/bull#604]
@manast can you tag/publish another RC that includes #589, #596, and (possibly) #591? I'm assuming those are still planned for v3.0.0 since they don't include any breaking changes? It would be great if we could go ahead and start testing/using those enhancements in the project we're currently working on.

Including #591 is not a big deal if you don't have time to investigate it yet, but I'd like to get those other PRs released if possible.

Would also be great if #602 can be included as well (we have a use-case for referencing the finished timestamp). It appears that one is slated for v3.1, but I can't tell what part of that would be a breaking change.

Cheers!

**Comment by ferronrsmith** [comment]
What's the ETA for v3 ?

**Comment by manast** [comment]
I think RC4 has big chances to become 3.0. I will make a new release today.
