### ISSUE TITLE
EMFILE error create queue

### ISSUE THREAD

**Issue by indper** [OptimalBits/bull#605]
Hi,

I have a problem for Bull performance testing.

> Error reading script file { [Error: EMFILE: too many open files, open '/usr/lib/node_modules/bull/lib/commands/updateDelaySet-4.lua']
  cause:
   { [Error: EMFILE: too many open files, open '/usr/lib/node_modules/bull/lib/commands/updateDelaySet-4.lua']
     errno: -24,
     code: 'EMFILE',
     syscall: 'open',
     path: '/usr/lib/node_modules/bull/lib/commands/updateDelaySet-4.lua' },
  isOperational: true,
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/usr/lib/node_modules/bull/lib/commands/updateDelaySet-4.lua' }

> Unhandled rejection Error: EMFILE: too many open files, scandir '/usr/lib/node_modules/bull/lib/commands'
    at Error (native)

attached my program,

Thank you

[test-bullqueue.zip](https://github.com/OptimalBits/bull/files/1127092/test-bullqueue.zip)

**Comment by manast** [comment]
I think the problem is that you are creating too many queues in parallel. When a queue is created it loads several .lua scripts. If you create many queues, like hundreds or thousands, you may end having too many files open. The solution is to wait for the queue to be "ready" before opening more queues.

**Comment by manast** [comment]
Btw, after this PR https://github.com/OptimalBits/bull/pull/591 you issue should also be resolved. Will be part of the bull 3.0.0-RC4.

**Comment by indper** [comment]
Thanks for your answer.

I want to develop socket+queue server (switching server) using request-reply model. For example [NAST Request Reply](http://nats.io/documentation/concepts/nats-req-rep/). Does 'bull' support for this model? Or Do you have any recommendation to implement this model using 'bull'?

Thank you very much..

**Comment by manast** [comment]
Bull supports 1 to 1, but not 1 to N: https://github.com/OptimalBits/bull/blob/master/PATTERNS.md#message-queue

**Comment by indper** [comment]
is it possible to delete queue data on redis after queue process done?

Thanks

**Comment by manast** [comment]
1. Yes.
2. Use the option for specifying a custom job id: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd

**Comment by indper** [comment]
1. After job completed and check redis:

```
psd@ubuntu-xxx:~$ redis-cli --scan --pattern 'bull:resQue1*'
bull:resQue1:completed
bull:resQue1:id
bull:resQue1:3
```

After clean completed job:
```
psd@ubuntu-xxx:~$ redis-cli --scan --pattern 'bull:resQue1*'
bull:resQue1:id
```

So I want to delete bull:resQue1:id (housekeeping the completed queue) because when i try to create & process many queue (> 6000), i have an error:

```
Unhandled rejection Error: Ready check failed: ERR max number of clients reached
    at /usr/lib/node_modules/bull/node_modules/ioredis/lib/redis/event_handler.js:45:29
    at /usr/lib/node_modules/bull/node_modules/ioredis/lib/redis.js:412:14
    at tryCatcher (/usr/lib/node_modules/bull/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/usr/lib/node_modules/bull/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/usr/lib/node_modules/bull/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/usr/lib/node_modules/bull/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/bull/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/lib/node_modules/bull/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/bull/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/bull/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```
 

2. Do you have any example code for client side to process/handle specific jobId?

For illustration case:

Server generate unique jobID and add to the respose queue

```
  var resQueName = 'resQue' + traceid;
  var responseQueue = new Queue('resQueue', 'redis://127.0.0.1:6379');
  responseQueue.add({msg:"output", stan: stan_val}, {jobId: resQueName});
```

And a client only process specific jobID. ex: resQue1234

Thanks & Sorry for my poor english :)

**Comment by manast** [comment]
The first error is a redis issue, you have too many clients open, is not related to bull as far as I can tell.
Regarding 2. I am not sure what you want to achieve. If you want different handlers for "job types", you may want to try using named jobs (check the name parameter): 
https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd
https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueprocess

**Comment by manast** [comment]
Can we close this issue?

**Comment by indper** [comment]
Ok @manast thanks for your answer..
