### ISSUE TITLE
addOnce feature

### ISSUE THREAD

**Issue by thelinuxlich** [OptimalBits/bull#609]
The same worker that processes a repeatable job also adds it on initialization. Problem is, it is a cluster of workers and the repeatable job can be accidentally added more than once.

**Comment by manast** [comment]
I have actually realised this hazard yesterday and I am working on a solution as we speak. It would be great if you have a case that reproduces it though, so I could have it as a test case.

**Comment by thelinuxlich** [comment]
That's nice, it will allow Bull to act as a distributed cron :)

I think a simple case could be:

```js
let total = 0, iterations = 0;
sumQueue.addOnce(1, { repeat: cron: '1 * * * *'}} );
sumQueue.addOnce(2, { repeat: cron: '1 * * * *'}} ); // should just overwrite the current repeatable job instead of another process adding 2.

sumQueue.process((job, done) => {
   total = total + job.data;
   iterations++;
   if(iterations === 5) {
       sumQueue.pause();
   }
});

sumQueue.on("paused", () => {
   assert(total === 10); //
});
```

**Comment by manast** [comment]
with the solution I have an ```addOnce``` will not be needed. Adding the same job will just result in one repeatable job.

**Comment by thelinuxlich** [comment]
But will it be possible to modify the crontime afterwards?

**Comment by manast** [comment]
We will have stop/remove functions for repeatable jobs very soon, that should accomplish what you need.

**Comment by xream** [comment]
@manast Hi. I found this issue was closed. However I found adding the same job just result in another repeatable job.

Here's the code:

```js
  queue.add('first', {}, { jobId: 'first', repeat: { cron: '10 * * * * *' } }),
  queue.add('first', {}, { jobId: 'first', repeat: { cron: '2 * * 1 * 2' } })
  console.log(await queue.getRepeatableJobs())
  // [ { name: 'first',
  //   id: 'first',
  //   endDate: null,
  //   tz: null,
  //   cron: '10 * * * * *',
  //   next: 1503998590000 },
  // { name: 'first',
  //   id: 'first',
  //   endDate: null,
  //   tz: null,
  //   cron: '2 * * 1 * 2',
  //   next: 1503998582000 } ]
```

Is there anything wrong with my code?

Thank you.

**Comment by manast** [comment]
Currently, two jobs with different cron expressions are treated as two different jobs.
