### ISSUE TITLE
Option in repeat jobs to "not catching up"

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#612]
If we have added a repeatable job, the job will be repeated according to the cron specification as accurately as possible. However, if there are no workers, or if the workers are not able to process the repeatable jobs in time, the jobs will be processed faster until catching up. This may o may not be desirable depending on the use case. with a "notCatchingUp" flag we can tell bull to skip the jobs that have been left behind in time and only focus on the "future ones".

**Comment by thelinuxlich** [comment]
Do you mean, a daily job without workers keeps piling up for days?

**Comment by manast** [comment]
Exactly. This can be a desired behaviour but of course not always.

**Comment by thelinuxlich** [comment]
Actually, I think the current behavior is the exception. At least for me, Bull with repeatable jobs sounds like a distributed cron.

**Comment by manast** [comment]
Also, lets say your cron specification is very tight and your process function slow, the queue will not loose any jobs with the current implementation. I am not sure yet which behaviour should be the default one. Normally your workers are running all the time. We should of course have methods to stop/pause the repeatable jobs.

**Comment by ritter** [comment]
I'd like this option as well. I have started using the repeat option in Bull, and occasionally there aren't any workers.  When a worker does become available, I do not need it to "catch-up" but rather run the next iteration according to their schedule.

**Comment by gmcnaught** [comment]
I would like this feature as well 
- it seems if there is an immediate need, a developer  could  work around this now with short-cut logic in their code called by queue.process code to just immediately call `done(new Error('this is too old'));`, if the job data has the scheduled time attached to it?

**Comment by ritter** [comment]
@gmcnaught the inefficiency remains that it'll run every iteration until it catches up. Depending on the duration that has passed, it could be better to remove the repeat job and add it again.

**Comment by gmcnaught** [comment]
Completely agree!

**Comment by ritter** [comment]
@manast I know this is marked enhancement, do you have an idea if this would be added to v3.0.0 (since its a non-breaking change?) or are we waiting for v3.1.0 now that v3.0.0 is released?

**Comment by manast** [comment]
I actually made this the default behaviour in 3.0.0. So jobs are not catching up, if no workers are running the jobs that should have been scheduled then will not run. It makes more sense this way.

**Comment by manast** [comment]
Fixed in e5c60e62410bdb5da8aec5b881944ab98bb03887 (released in version 3.0.0)
