### ISSUE TITLE
Repeating Jobs are marked as finished but they're not completed

### ISSUE THREAD

**Issue by ekaratzaferis** [OptimalBits/bull#619]
Hi,

I've noticed in Redis that repeating jobs are under the namespace bull/myQueue/repeat/default. In there, I've found multiple jobs with the properties finishedOn, processedOn, returnvalue.

Shouldn't they be moved under bull/myQueue/bull:myQueue:completed?

To give you an example, I'm creating a new Queue and then adding 3 repeating tasks. Using cluster.fork, I'm starting 4 "consumers" which are using the queue.process method to consume the job, just like your example.

The 3 tasks are completed successfully the first time, but there seems to be a problem when they're repeated. Repeating jobs are stuck in the repeat namespace.

I'm posting the code that recreates this behavior. Hopefully, it's a mistake in my code :)

```javascript
const redis = require('redis')
const cluster = require('cluster')
const mongoose = require('mongoose')
const Bull = require('bull')

const client = redis.createClient()

function clearRedis() {
    return new Promise((resolve, reject) => {
        client.flushall((err) => {
            if (err) {
                reject()
            } else {
                console.log('Clearing Redis... Done')
                resolve()
            }
        })
    })
}

function newQueue (name) {
    var q = new Bull(name)
    return q.isReady()
}
function schedule (q, data) {
    q.add(data, {
        jobId: mongoose.Types.ObjectId(),
        repeat: {
            cron: '*/1 * * * *'
        }
    })
}

async function process () {
    var queue = await newQueue('someQueue')
    if (cluster.isMaster) {
        await clearRedis()
        // Fork workers //
        for (let i = 0; i < 4; i++) {
            cluster.fork()
        }
        cluster.on('exit', (worker) => {
            console.error(`Worker ${worker.process.pid} has stopped!`)
            console.error(worker)
        })
        schedule(queue, {ee: 1})
        schedule(queue, {ee: 2})
        schedule(queue, {ee: 3})
    } else {
        queue.process((job) => {
            console.log(`Job ${job.data.ee} is running on someQueue`)
        })
    }
}

try{
    return process()
} catch (err) {
    console.error(err)
}
```

**Comment by ekaratzaferis** [comment]
I was expecting that the code above would print this every minute:

Job 1 is running on someQueue
Job 2 is running on someQueue
Job 3 is running on someQueue

but it does not. After 5 minutes, I'm only getting this

Job 1 is running on someQueue
Job 2 is running on someQueue
Job 3 is running on someQueue
Job 1 is running on someQueue
Job 2 is running on someQueue
Job 1 is running on someQueue
Job 2 is running on someQueue

and there are jobs stuck in the repeat namespace, that are marked as finished without being executed. 

Also one out of three jobs does not ever repeat. (The other two are not repeat one time also)

**Comment by manast** [comment]
Just to eliminated moving parts, does this work without cluster, with a single producer and consumer?

**Comment by manast** [comment]
btw, regarding the job statuses. ```completed``` is a zset, it only stores the completed jobs´ ids. whereas the repeat jobs are stored as standard redis keys. finishedOn and processedOn are the time stamps where the job was finished and started to be processed respectively.

**Comment by ekaratzaferis** [comment]
```javascript
await clearRedis()
var queue = await newQueue('someQueue')
schedule(queue, {ee: 1})
schedule(queue, {ee: 2})
schedule(queue, {ee: 3})
queue.process((job) => {
    console.log(`Job ${job.data.ee} is running on someQueue`)
})
```

I've removed the cluster part. I first get

Job 1 is running on someQueue
Job 2 is running on someQueue
Job 3 is running on someQueue

and then they do repeat. I see them in the completed set and in the repeated namespace. Now the issue seems to be that the jobs are delayed. For example, after the first 3 consoles, I got the next after a minute, the other one after ~ a minute and so on. Let me try changing the advanced setting and see what happens.

**Comment by ekaratzaferis** [comment]
Ok, I've tried running the cluster example on the homepage, but I think I'm missing something.

I'm creating 2 workers, 
```javascript
var numWorkers = 2;
```
and I'm adding 2 jobs to queue
```javascript
for(var i=0; i<2; i++){
    queue.add({foo: 'bar'});
};
```
I'm getting this consoles at first
Job done by worker 1 1
Job done by worker 2 2

but then the repeating behavior is the same as described above. Every minute I get one console like this
Job done by worker 2 repeat:__default__:1500026460000

**Comment by manast** [comment]
I will try to reproduce it during the weekend. I cannot see anything wrong with the example code yet.

**Comment by ekaratzaferis** [comment]
Thank you in advance :)

**Comment by manast** [comment]
@ekaratzaferis I am sorry that I did not manage to do more on this issue. Do you have more information? have you found workarounds?
