### ISSUE TITLE
getFailed is not defined

### ISSUE THREAD

**Issue by themuflon** [OptimalBits/bull#621]
There seems to have been some refactoring of `finished()` in `jobs.js`, but not all references to getFailed were removed. [Here](https://github.com/OptimalBits/bull/blob/master/lib/job.js#L374) is the last reference to `getFailed()`.

The issue was introduced with PR #588.

**Comment by marshall007** [comment]
Appears to be defined here in [`/lib/getters.js#L114-L116`](https://github.com/OptimalBits/bull/blob/master/lib/getters.js#L114-L116).

**Comment by manast** [comment]
@themuflon Not sure I get your point. The method has just been out-refactored to a separate file, other than that is a method of the Queue class exactly as before...

**Comment by SmilyOrg** [comment]
I don't know why it's just [`getFailed()`](https://github.com/OptimalBits/bull/blob/master/lib/job.js#L374) either, maybe it was meant to be `_this.queue.getFailed()` as @themuflon mentioned?

**Comment by manast** [comment]
ah, ok. That could be it :).
