### ISSUE TITLE
Missing process handler for job type myjobtype

### ISSUE THREAD

**Issue by vkeyrockz** [OptimalBits/bull#625]
i have using bull for my project. i created a queue and attach process handler on it for a 'jobtype'.Then i add job to that queue with that 'jobtype'. sometimes jobs handled by handler and fails with the error 'missing handler' in sometimes . for example if i span job 1,2,3,4 . 2,4 got failed 1,3 got by handler. (note the mentioned order is just to describe).
my code:
job.js:
```
`const bull      = require('bull');
const conf      = require('../../conf');
const redisConf = {redis: conf.get('redis')};
require('./worker.js')
//note queue was successfully created
const productQueue = new bull('product', redisConf);
module.exports.addJob = (jobType,data,jobid)=>{
//jobType - 'myjob'
//jobid - unique job id string
productQueue.add(jobType, data, {
			delay   : 0,
			priority: 'normal',
			attempts: 1,
			//timeout : 2000,
			backOff : {type: 'exponential'},
			jobId   : jobId
		});
}`
```
worker.js

```
const bull      = require('bull');
const conf      = require('../../conf');
const redisConf = {redis: conf.get('redis')};
const productQueue = new bull('product', redisConf);
//**the job does not comes into handler sometimes**
productQueue.process('myjob', (job, done) =>{
	try{
		const credential = job.data;
		 productB.syncProducts(credential);
		done();
	} catch(err){
		done(err);
	}
});
```

**Comment by manast** [comment]
I will try to reproduce this. Btw, priority must be a number: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd

**Comment by manast** [comment]
Better yet, since I am quite sure that will work for me. Can you provide a minimal example that reproduces the issue?

**Comment by vkeyrockz** [comment]
yeah i agree with priority , i have a util function that will change priority.
```
const jobPriority = {
	'low'      : 5,
	'normal'   : 10,
	'high'     : 15,
	'immediate': 20
};
```

**Comment by manast** [comment]
Do you define only one handler of a given type or several ones? All handlers must be defined in the same event loop in the worker, otherwise there is a risk that the worker starts processing a job and since all the handlers have not been defined yet it will give you the above mentioned error.

**Comment by vkeyrockz** [comment]
Do you define only one handler of a given type or several ones?

**Comment by manast** [comment]
Exactly. What I mean is, if you have a set of handlers, these set of handlers for one given queue must be defined in the same event loop, otherwise you will get the mentioned error, because as soon as a handler is defined, the queues starts processing. So the first handler would try to fetch a job, and if that job is of a different type the error will appear.

**Comment by vkeyrockz** [comment]
now i define my queue globally in one place (i.e in same event loop) and refer and reuse that instance all over my app. its working now
