### ISSUE TITLE
[Upgrade question] From 0.2.7 to latest (3.0.0-rc.4?)

### ISSUE THREAD

**Issue by luislobo** [OptimalBits/bull#632]
Hi,
We have adopted bull very early in it's beginnings, and didn't upgrade since so far, it's been working great for US.
Anyway, we would like to upgrade to the latest, just to keep all our dependencies up to date (we do dependency updates manually, to keep our system stable). For the bull case, we never touched.
Our main concern is if there are any compatibility issues in the internal structures and/or the way things are queued. Should we consider the version upgrade as if we were migrating from one product onto a different one?
Are there any known compatibility issues while upgrading?
Thank you!

**Comment by manast** [comment]
Firstly I would recommend you to wait for version 3.0 final. But you will most probably need to migrate as if it was a new queue. Many internal data structures have changed since 0.2.7, although the API is almost backwards compatible.

**Comment by luislobo** [comment]
@manast Alright! Thank you for your insight. I'll wait for the final version. In the meantime, I might migrate our jobs apps to use the new one in a parallel implementation and deployment. Thanks!
