### ISSUE TITLE
Express App crashes when a bull job receives an error

### ISSUE THREAD

**Issue by prcongithub** [OptimalBits/bull#635]
I am not sure if I am doing this the right way. So here is the deal.
I have an express app configured with bull and bull-arena.
I have a couple of queues to which jobs get added through some routes.
But if the code written in the process() method throws an error, it crashes the express app as well.

How do I avoid crashing of the app when something goes wrong in the job processing?

**Comment by manast** [comment]
If your processing job is well written and handles errors appropriately then the main process is safe.

**Comment by prcongithub** [comment]
Is handling errors in the job processing the only way? Is there a way we could run the jobs in another node process?

**Comment by marshall007** [comment]
@manast isn't the `process(...)` callback wrapped in a promise chain when it's called? Looking at the code, I don't see how a thrown exception could possibly propagate to the main process as an uncaught exception. At worst, I think you might see an `unhandledRejection`, but I don't think those crash the process.

**Comment by manast** [comment]
```
queue.process(function(){
 return mypromise().then(function(){
  myasyncfunc(function(){
    throw Error();
  });
});
});
```

**Comment by marshall007** [comment]
@manast yea I see what you're saying. Any async functions that don't use the conventional Node callback style or promises:

```js
const Bluebird = require("bluebird");

function process(job) {
  setImmediate(() => { throw new Error() });
}

const handler = Bluebird.promisify(process);

handler({ /* job */ })
.then(
  () => console.log('success'),
  () => console.log('error')
)
.finally(
  () => console.log('not crashed')
)
```

**Comment by manast** [comment]
The promise wrapper over the process function can only catch direct exceptions in the call, or if a correct promise chain is returned. As soon as there is one async call, we loose the hability to catch any exceptions, this is just standard node, we cannot really do so much about it...

**Comment by manast** [comment]
I will close this issue now since I do not think it is bull related. Re-open if needed.
