### ISSUE TITLE
API Documentation Question

### ISSUE THREAD

**Issue by markle976** [OptimalBits/bull#639]
I see the docs are written like so:    

`interface BackoffOpts{
      type: string;
      delay: number; 
}`

Would you mind using plain JavaScript? JavaScript is a mult-paradigm language. Many of us are Functionalists and not big fans of OOP. I'd be happy to submit a merge request if you'd be ok with me changing it.

**Comment by ritter** [comment]
I would like to cast my vote to leave it as-is. Many of us other functionalists enjoy typescript and this style of documentation.

**Comment by manast** [comment]
Yes. It will be left as is. It tries to follow typescript standard which is heavily inspired by ES6. This is the future of javascript, so I do not think it is wise to go back to some other ad-hoc style.
