### ISSUE TITLE
Toureiro supported by bull v3 and node 8

### ISSUE THREAD

**Issue by barhoumio** [OptimalBits/bull#640]
Hi, i pushed a new version of Toureiro that work on node 8.x, 7.x, 6.x and 4.x, also it supported by Bull v3, it's here : 
[![npm version](https://badge.fury.io/js/bull-toureiro.svg)](https://badge.fury.io/js/bull-toureiro)
[![Build Status](https://travis-ci.org/barhoumio/bull-toureiro.svg?branch=master)](https://travis-ci.org/barhoumio/bull-toureiro)

**Comment by ferronrsmith** [comment]
awesome !

**Comment by ferronrsmith** [comment]
You can't repackage someone else's work as your own without giving credit to the original work or removed the original license. https://github.com/Epharmix/Toureiro#license

**Comment by barhoumio** [comment]
Yes, i know that and  i will add the credit of the owner in the next release 😄

**Comment by pruhstal** [comment]
@barhoumio Can you submit a pull request on the official toureiro repo?
