### ISSUE TITLE
Did .on('ready') really have to die in 3.0?

### ISSUE THREAD

**Issue by woodardj** [OptimalBits/bull#642]
I have a (possibly edge) use-case where I create a queue, which I want to immediately pause execution on as it starts up.

Currently (i.e. in 2.x series) what i'm doing is:

```
streamUpdateBuffer = Queue('stream-updates', process.env.REDIS_URL, {});

streamUpdateBuffer.on('ready', function(){
    // ...
    return streamUpdateBuffer.pause();
}
```

Is there a better way to accomplish this? (pausing a queue immediately as it's created) Or could the `'ready'` event possibly come back before final 3.0 release.

**Comment by manast** [comment]
Its still there, but not as an event, just call: ```queue.isReady()```which returns a promise that resolves when the queue is ready. However I tried to make that method not needed by waiting internally in the queue methods. I probably forgot to use it in the pause method.

**Comment by manast** [comment]
Actually we are waiting in queue##pause: https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L688

**Comment by woodardj** [comment]
Wonderful, thanks @manast ! So when I'm upgrading to 3.x series I should just get rid of my ready handler, and I can pause immediately after instantiation of the queue? Less code always makes me more happy :)
