### ISSUE TITLE
Job queue suddlenly stops running jobs

### ISSUE THREAD

**Issue by LucianoGanga** [OptimalBits/bull#643]
Hi! 

I have an app that schedules jobs in a bull queue, which has concurrency of 15 jobs max. 

I'm having some problems with it because suddenly, the queue stops processing those jobs. If I check redis, I see that the new jobs are being scheduled with no problem, so I think is not a DB connection issue. 

Any ideas of what can be happening? The logs say nothing, they just stop running. 

Thanks! And sorry for not giving so much info, but that's all I know :/ 
Luciano

**Comment by manast** [comment]
Which version of bull are you using?

**Comment by LucianoGanga** [comment]
v2.2.6, running on Node v8.1.4

**Comment by Pyker** [comment]
I have also come across this issue. Running Bull v2.2.6, Node v6.9.1 here.

**Comment by LucianoGanga** [comment]
I'm on a production environment, and it's a delicate environment that cannot be reproduced without affecting data :/ 

How stable is v3.0.0-rc5?

**Comment by manast** [comment]
rc7 is quite stable, but it has just been released. Also, the queue structure of 2.x and 3.x is not exactly the same, so you need to create new queues.

**Comment by manast** [comment]
We are on 3.0.0-c8 now. This will most probably be the last release candidate before the 3.0 release. I will close this issue afterwards.

**Comment by manast** [comment]
3.0.0 has been released and no known bug related to queue not running jobs is known.

**Comment by tskweres** [comment]
We're using "bull": "^3.12.0"

We have processes with a concurrency of 6, and a delay of 1000 between jobs. 

The queue just hangs and stops running jobs after about 2 hours. Any ideas?
