### ISSUE TITLE
Updating node 4/6 to 8

### ISSUE THREAD

**Issue by udleinati** [OptimalBits/bull#648]
Hi,

Since Node 8.x is going to be LTS and Bull is releasing a new version, I wonder why Bull should support Node 4/6? Updating to Node 8 brings new features that I'd be happy to help implement it.

**Comment by ritter** [comment]
Node 8.x isn't LTS until October 2017.  It's going to take time for companies/people to upgrade.  I personally wouldn't be so quick and harsh about dropping LTS 6.x support.

**Comment by manast** [comment]
@udleinati which features would you like to take advantage of in bull that are in node 8?

**Comment by udleinati** [comment]
@manast In fact, not much... working with async/await would be great, avoiding promise as much as possible. Thinking better about, what @ritter said make sense to me. Just for that it doesn't worth the change.

**Comment by manast** [comment]
I think you can still use that features on top of the current bull api.
