### ISSUE TITLE
Is 3.0.0-rc.5 considered production ready?

### ISSUE THREAD

**Issue by brenc** [OptimalBits/bull#649]
Just started using bull for a new project and I'm curious if 3.0.0-rc.5 is considered stable enough for production use. I assume **not** because this is a release candidate. If this is the case, I'm confused as to why `npm install bull` installs 3.0.0-rc.5 and not 2.2.6.

Which version should I be using for new projects at this point?

**Comment by manast** [comment]
3.0.0-rc should not be considered production ready, and they may change both APIs and redis data structured. However, npm seems to install the latest pre-release by default. I learnt that I can avoid this behaviour, I will do it for the next release: https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420

**Comment by brenc** [comment]
I thought that might have been the case. Thanks for clarifying!
