### ISSUE TITLE
[enhancement] use  BRPOPLPUSH instead of BLPOP for notifying waiting jobs

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#651]
Currently we have a special list ```wait:added``` used for notifying that new jobs have arrived to the queue. This works well but can be done better. If we use BRPOPLPUSH instead but using the same source and destination, we can have only one list and get rid of ```wait:added```, this simplifies code but also has another advantage, we can call ```moveToActive``` directly to avoid an extra call to BLPOP, for instance if the queue has not drained we can just keep moving jobs to the active list faster.

**Comment by milesalex** [comment]
I'm getting large amount of latency with this. 

`BRPOPLPUSH bull:transaction report:wait bull:transaction report:active 5`

Any idea how to fix this?
