### ISSUE TITLE
Jobs not being run in v.3.0.0-rc.5

### ISSUE THREAD

**Issue by gbhrdt** [OptimalBits/bull#661]
We just updated from `v.3.0.0-rc.4` to `v.3.0.0-rc.5` in our production environment and no jobs were run at all.
I don't know what caused this, but the rc-5 version definately has a bug in it. (probably related to `Improved performance, specially when having many concurrent workers.`)

**Comment by manast** [comment]
There are known bugs in rc5, thats why you should run rc7 :)

**Comment by gbhrdt** [comment]
@manast Thanks for your quick reply :-) We were using rc7, too and there was no change. Should we attach the queue's `.on('error')` handler to see what's going on?

**Comment by manast** [comment]
Check for a key ended in: ```:added```.  That list needs to exist so that the workers gets notified that jobs have been added to the queue.

**Comment by manast** [comment]
I will close this since rc8 is out, where it has a new algo for getting the jobs from the queue that would prevent jobs not being run.
