### ISSUE TITLE
3.0.0-rc.7 slow to process new messages

### ISSUE THREAD

**Issue by jcald1** [OptimalBits/bull#663]
I've been using version 2.2.6 with my code.  Adding a new message and reading it takes less than a second, but with the latest version there appears to be about a 5 second delay in reading the new messages.

**Comment by manast** [comment]
Strange, bull 3.0 is much faster than 2.2.6, it should be the opposite. Do you have some example code to reproduce it?

**Comment by jcald1** [comment]
@manast, it seems to be back to normal. There might have been something strange going on in my environment.
