### ISSUE TITLE
Repeatable job ids are not unique

### ISSUE THREAD

**Issue by Slaventsiy** [OptimalBits/bull#665]
As the title says. I add 2 very similar jobs in quick succession with no name and no custom jobId. Both result in id "repeat:__default__::1503309604000".

**Comment by manast** [comment]
Do you have a minimal code example to reproduce this?

**Comment by Slaventsiy** [comment]
it('should create two jobs with the same ids', async () => {
      const { startDate, cronExpression } = reportConfig;
      const delay = Math.max(0, startDate - Date.now());

      const options = {
        delay,
        repeat: {
          cron: cronExpression,
        },
      };

      const p1 = queue.add(reportConfig, options);
      const p2 = queue.add(reportConfig, options);
      await Promise.all([p1, p2])
        .then((jobs) => {
          assert.equal(jobs.length, 2);
          assert.equal(jobs[0].id, jobs[1].id, 'Ids are unique');
        });
    });

**Comment by manast** [comment]
perfect, thanks!.

**Comment by manast** [comment]
I have yet to run the code, but I can already say this, in this particular case, the IDs of the jobs are the same, but that is because they are the same job. The important thing is that they should only be processed once, and appear both in the wait list as in the completed sets as only one job.

**Comment by manast** [comment]
I added the test case you mentioned and it passed correctly in rc8. Please reopen if not working as expected.

**Comment by tangopium** [comment]
This issue still (or again) exists in Bull version 3.4.8. If you create repeating jobs with the same option hash, it results in the same jobId.

**Comment by manast** [comment]
@tangopium do you have a reproducible test case?
