### ISSUE TITLE
BUG: Repeat jobs duplicate if you restart the handler service in the middle of processing.

### ISSUE THREAD

**Issue by cendrizzi** [OptimalBits/bull#666]
This is specific for duplication. I personally have one process that handles the queues. This is how I can re-create this:

1. Create a queue.
2. Add a recurring job (for example */5 * * * *).
3. On the handler side ensure the handler takes enough time (setTimeout) that you can restart the parent node process while it's processing the job.
4. Once restarted and it runs through the job, it will have a duplicated job within the delayed jobs. 

For example, in my key: **bull:import_data:delayed**

I have these rows:
repeat:__default__::1503333000000
repeat:__default__::1503333000000 (oops I think I copied this wrong, I think it results in a unique key for each row, even though the jobs are actually the same)

**Result**
Finally, the job then seems to run twice in a row after this duplication (UPDATE: it only did this once, see below). So it's a pretty major issue if I'm deploying in the middle of a recurring job being processed.

Hope this helps.

**Comment by cendrizzi** [comment]
Just a further follow up. I restarted it again while processing and it reliably created another duplicate:

I have now these rows:
repeat:__default__::1503333600000
repeat:__default__::1503333900000
repeat:__default__::1503334200000

**Comment by cendrizzi** [comment]
And another follow up. 

My completed log looks like this: 
10:15 am completed
10:20 am completed
10:20 am completed
10:25 am completed
10:30 am completed

For some reason at 10:20 it ran it twice, but otherwise the duplications don't seem to result in the job being actually run more than once. Which is good.

I still can't imagine the duplicates should be in there though.

**Comment by manast** [comment]
Would you mind to test on rc8 to see if the issue is still there? If so, any chance to provide a test case that reproduces the issue?

**Comment by cendrizzi** [comment]
This still happens. I will try and come up with something good to reproduce this.

**Comment by cendrizzi** [comment]
As with the other issue you can duplicate this using my code found in this repo:

https://github.com/cendrizzi/bull-test

Instructions are in the readme.  Thanks.
