### ISSUE TITLE
Queue gets stuck and then is spammed when restarting server

### ISSUE THREAD

**Issue by Enitoni** [OptimalBits/bull#668]
I'm new to bull and redis based queueing for resource intensive stuff.

I have two queues, one to process images, another to process audio. After restarting, things work well, and suddenly the queue just refuses to keep going. Jobs aren't being running. I can even spam it with request and it will do nothing.

But when I restart the server, suddenly my computer is holding on to everything resembling memory to not die when being bombarded with ffmpeg processes and image processing jobs. https://streamable.com/w6062

Here's a sample of my audio processing queue: https://pastebin.com/7sMnZrWM

I'm not sure what I'm doing wrong. I'm also using arena and having none of my job types appear there, so I'm unable to see what exactly is going on.

**Comment by manast** [comment]
I haven't checked it in detail, but first thing I see is that you are never calling ```done```, and you are not returning any promise either. I also recommend you to either return a promise or use the callback, do not mix them.

**Comment by Enitoni** [comment]
Oh my god. I'm so sorry for wasting your time. Thank you! I wasn't calling "done" when the jobs were successfully finished.
