### ISSUE TITLE
A Working UI?

### ISSUE THREAD

**Issue by npahucki** [OptimalBits/bull#671]
For version 3 is Arena the only option for a UI? It does not seem to work very well at all, it crashes left and right and has terrible documentation. If there are any other alternatives that you know work well, I would certainly appreciate the pointers. 

Thanks.

**Comment by manast** [comment]
All I can say is that a brand new UI is going to be released in the following weeks, that is stable and has very nice features.

**Comment by npahucki** [comment]
BTW: I got Arena working acceptably, it appears the docker image they link in the docs is out of date (and or has some other instabilities). Embedding Arena in an express app and making my own docker image it works ok (even if a little minimal). 

Thanks for taking the time to comment, even though the question was not directly related to bull itself.

**Comment by vjustov** [comment]
@npahucki Can you go into some more detail of how you managed to get it working?
Im trying to migrate from kue but neither arena or taskforce work.

**Comment by manast** [comment]
@vjustov can you explain what does not work with Taskforce?
