### ISSUE TITLE
 TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by brianlovin** [OptimalBits/bull#673]
Hey team - 

We're running `bull` on our node webserver, but have recently encountered a problem where triggering events returns this error, which in turn crashes the entire web server.

```js
08/23 05:47 PM  TypeError: Cannot read property 'name' of undefined
                    at Function.Job.fromJSON (/home/nowuser/src/node_modules/bull/lib/job.js:434:32)
                    at Redis.<anonymous> (/home/nowuser/src/node_modules/bull/lib/queue.js:309:23)
                    at emitThree (events.js:135:13)
                    at Redis.emit (events.js:216:7)
                    at Redis.exports.returnReply (/home/nowuser/src/node_modules/ioredis/lib/redis/parser.js:116:14)
                    at JavascriptRedisParser.returnReply (/home/nowuser/src/node_modules/ioredis/lib/redis/parser.js:27:13)
                    at JavascriptRedisParser.execute (/home/nowuser/src/node_modules/redis-parser/lib/parser.js:574:12)
                    at Socket.<anonymous> (/home/nowuser/src/node_modules/ioredis/lib/redis/event_handler.js:107:22)
                    at emitOne (events.js:115:13)
                    at Socket.emit (events.js:210:7)
                    at addChunk (_stream_readable.js:252:12)
                    at readableAddChunk (_stream_readable.js:239:11)
                    at Socket.Readable.push (_stream_readable.js:197:10)
                    at TCP.onread (net.js:589:20)
```

I've tried wrapping all queue logic in a utility function with a try/catch:

```js
import Raven from 'raven';
const createQueue = require('../../shared/bull/create-queue');

export const addQueue = (name: string, data: any) => {
  const worker = createQueue(name);
  try {
    worker.add({ ...data });
  } catch (err) {
    Raven.captureException(err);
  }
};
```

But even with the try/catch in place things continue to fail when a job gets kicked off.

I'm not quite sure where to start debugging this - bad data in our redis store? A mismatched queue name?

Has this happened to anyone, or know of any good ways to debug this? I've tried using `[longjohn](https://github.com/mattinsler/longjohn)` to expand the stacktrace, but it doesn't add any addition info to the error above.

Thanks :)

**Comment by brianlovin** [comment]
Update:

Realize that `.add()` returns a promise, so I've updated the `addQueue` utility to:

```js
export const addQueue = (name: string, data: any) => {
  const worker = createQueue(name);
  return worker.add({ ...data }).catch(err => Raven.captureException(err))
};
```

That being said, I'm still having the same problem.

I dug deeper and did a complete `FLUSHALL` on my redis db - immediately after doing that, all keys were deleted. Within a second or two, new keys were magically reapparing with a `:stalled-check` suffix:

<img width="610" alt="screenshot 2017-08-23 20 47 01" src="https://user-images.githubusercontent.com/1923260/29648683-413cefa0-8844-11e7-99a3-bb16caae8972.png">

SO I figured that our worker deployments had some bad jobs stuck in cache or something, that just kept retrying. I completely deleted the worker deployments, ran new deploys, and *same issue* persists.

I'm seeing these `:stalled-check` jobs appearing in our prod redis db even with nothing calling them, and appearing instantly after a `FLUSHALL`

**Comment by brianlovin** [comment]
More context:

This is our queue creation:

```js
const Queue = require('bull');
const Raven = require('raven');

const redis =
  process.env.NODE_ENV === 'production'
    ? {
        port: REDIS_PORT,
        host: REDIS_URL,
        password: REDIS_PASSWORD,
      }
    : undefined; // Use the local instance of Redis in development by not passing any connection string

// Leave the options undefined if we're using the default redis connection
const options = redis && { redis: redis };

function createQueue(name /*: string */) {
  const queue = new Queue(name, options);
  queue.on('stalled', job => {
    const message = `Job#${job.id} stalled, processing again.`;
    if (process.env.NODE_ENV !== 'production') {
      console.error(message);
      return;
    }
    // In production log stalled job to Sentry
    Raven.captureException(new Error(message));
  });
  return new Queue(name, options);
}

module.exports = createQueue;
```

At this point I'm assuming we're missing the option that will tell Bull to stop trying to process stalled jobs, or something, although by the looks of it we're not touching the defaults.

Does this help at all?

**Comment by brianlovin** [comment]
Here's a wider screenshot of the Compose dashboard where we're hosting redis:

<img width="1094" alt="screenshot 2017-08-23 21 27 24" src="https://user-images.githubusercontent.com/1923260/29649601-f0bca2d6-8849-11e7-9ac8-003addd045be.png">

Notice that the `:stalled-check` jobs are composed of characters, not fields, and all have a 30s max TTL

**Comment by brianlovin** [comment]
I don't want to speak too soon, but going from `bull: 3.0.0-rc.2` => `bull: 3.0.0-rc.8` seems to have fixed the issue of new jobs crashing our web server.

I'm looking through the latest commits since `rc.2` and it looks like there was some work done on stalled job handling, so I'm guessing the fix was somewhere in there.

So while it's great to see that we got our web server back online, the only remaining issue is the `:stalled-check` jobs in the production redis db that keep getting reprocessed every 30s :)

**Comment by neilkinnish** [comment]
You're creating the queue each time you add a job is that right?

**Comment by manast** [comment]
@brianlovin The ```stalled-check``` key is a special key used so that when you have many concurrent workers, they quickly check if its time to check for stalled jobs or not, so that the check is only performed after 30 seconds (or whatever you have configured the ```stalledInterval```option. So it is completely normal, and unfortunately there is no way to hide that key since we require the EXPIRE functionality in redis that is only available for keys.

Regarding the error, you should try to enable the long traces support in bluebird to get the complete callstack. Just keep in mind this adds overhead and should not be used in production:
http://bluebirdjs.com/docs/api/promise.longstacktraces.html

**Comment by brianlovin** [comment]
@neilkinnish - looks like it; does that seem right do you, or is there a better way to approach taht setup?

@manast thanks for the info and recommendation on getting long stack traces. In our code above, are we missing any options you'd recommend to handle expiration or avoiding the `stalled-check` records from continuously being retried?

**Comment by manast** [comment]
@brianlovin the stalled script is run every 30 seconds by default, you can configure to a larger interval if you want on the queue setting called ```stalledInterval```

**Comment by neilkinnish** [comment]
@brianlovin I suppose it depends on the concurrency you want and the type of job being processed (I'm not up-to-date with latest bull version - keep in mind).

If you create the queue once and then just add to it, it will only process one of that queue type at a time of course you can have many machines or processes handling.

**Comment by manast** [comment]
@brianlovin I would like to close this issue, please can you tell me what is the status of it?

**Comment by brianlovin** [comment]
Thanks so much for the help here - things seem to be resolved now, especially after upgrading to the latest rc!

**Comment by manast** [comment]
We are on 3.0.0 final in case you haven't noticed yet :)
