### ISSUE TITLE
Improve validation of the options object

### ISSUE THREAD

**Issue by NassiHarel** [OptimalBits/bull#676]
But....
Validation is missing, for example:

```js

var queue = new Queue('test-job', opts);
queue.process(function (job, done) {
    job.progress(42);
    done(null, { width: 1280, height: 720 });
});

let options = {
    priority: 1,
    delay: 4000,
    attempts: 3,
    repeat: {},
    lifo: false,
    timeout: 2000,
    removeOnComplete: true,
    removeOnFail: true
}
queue.add({ image: 'image1.tiff' }, options);

```

Will not work because the ** repeat: {}**

Another example:
from [here](https://github.com/OptimalBits/bull/blob/master/PATTERNS.md)

```js
var opts = {
  redis: {
    opts: {
      createClient: function(type){
        switch(type){
          case 'client':
            return client;
          case 'subscriber':
            return subscriber;
          default:
            return new redis();
        }
      }
    }
  }
}

var queue = new Queue('test-job', opts);

```

Not working.... should be:

```js
var opts = {
    createClient: function (type) {
        switch (type) {
            case 'client':
                return client;
            case 'subscriber':
                return subscriber;
            default:
                return client;
        }
    }
}
var queue = new Queue('test-job', opts);

```

**Comment by weeco** [comment]
This issue should be referenced I guess: https://github.com/OptimalBits/bull/issues/315

**Comment by manast** [comment]
yes. I still believe it is better to use typescript definitions for this. Checking for options also adds a little overhead, if speed matters then we should avoid it.

**Comment by weeco** [comment]
@manast This issue can be closed then :-)

**Comment by pigaov10** [comment]
@NassiHarel I followed step by step **createClient** opts but the application caught the message below

Unhandled rejection TypeError: scripts.updateDelaySet(...).then(...).return is not a function
at /var/www/html/node/node_modules/bull/lib/queue.js:373:18

any suggestion?

**Comment by aleccool213** [comment]
this should be closed when the pr for the typescript types goes up lol
