### ISSUE TITLE
Events are not fired

### ISSUE THREAD

**Issue by NassiHarel** [OptimalBits/bull#677]
What I missed...

Producer:

```js
const Queue = require('bull');
const queue = new Queue('test-job');

const options = {
    priority: 1,
    delay: 1000,
    attempts: 3,
    lifo: false,
    timeout: 2000,
    removeOnComplete: true,
    removeOnFail: true
}

queue.on('completed', function (error) {
    console.log('completed');
}).on('error', function (error) {
    console.log('error');
}).on('active', function (job, jobPromise) {
    console.log('active');
}).on('stalled', function (job) {
    console.log('stalled');
}).on('progress', function (job, progress) {
    console.log('progress');
}).on('failed', function (job, err) {
    console.log('failed');
}).on('paused', function () {
    console.log('paused');
}).on('resumed', function (job) {
    console.log('resumed');
}).on('cleaned', function (jobs, type) {
    console.log('cleaned');
});

queue.add({ image: 'image1.tiff' }, options);
```

Consumer:

```js
const Queue = require('bull');
const queue = new Queue('test-job');

queue.process(function (job, done) {
    job.progress(42);
    done(null, { width: 1280, height: 720 });
});
```

**Comment by manast** [comment]
Because the events are generated in the consumer. You need to use global events, so instead of listening to ```completed``` you need to listen to ```global:completed```

**Comment by NassiHarel** [comment]
This is not good, because I want that the producer will be able to know about the state of the specific job it just produced, (in case of multiple producers)

**Comment by ritter** [comment]
One thing that I do, is listen for global event like @manast said. But I hold on to the `job` returned from `Queue.add` and compare them to know if its an event I'm waiting for.

**Comment by NassiHarel** [comment]
I will have to keep a Map().
But this will make my app statefull.
And this is not scale well...
Thanks

**Comment by manast** [comment]
@NassiHarel Normally the producer (can be one or many) is decoupled from the consumer (can also be one or many), so if you really need the one producer to know when his own job was processed you may rethink your design, since the kind of coupling you are asking for will probably be problematic in the end.

**Comment by NassiHarel** [comment]
A simple scenario 
```js
app.post(/calc/, async () => {
   await someBullJob();
   res({message: 'the job started successfully'})
})
```

If the consumer send events such as progress/active, who should know about it if not the producer?
The consumer should know about these events? about his own events?

**Comment by manast** [comment]
If you had only one producer then yes. But we are talking on a large distributed solution. You have to architect it in a different way as you would in a mono-process architecture. For instance, although a different case, check the patterns for some inspiration: https://github.com/OptimalBits/bull/blob/master/PATTERNS.md

what you are proposing would require that the consumers know who are the producers and then somehow only send a message to them. This is currently unfeasible, I am not sure there is any other queue system capable of doing something like that, but I would like to know.
