### ISSUE TITLE
Add method to update a job data

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#679]
We can have something like:

```
job.update(data)
```
and also:
```
queue.updateJob(jobId, data);
```

**Comment by NassiHarel** [comment]
👍🏼

**Comment by NassiHarel** [comment]
It also will be helpful to update the job options

**Comment by manast** [comment]
updating the options is much more difficult, because many options affects the status of the job, so for this issue I will only made possible to update the data. We can see if the need for updating the options is large enough to motivate such a change.

**Comment by Moulali1995** [comment]
Hi @manast 

queue.updateJob(jobId, data); is not working 
TypeError:Queue.updateJob is not a function.
Can you please help me with the above method. I can't find that method in documentation.
I'm looking to update a job data with out processing the job.
