### ISSUE TITLE
Clear repeatable jobs queue

### ISSUE THREAD

**Issue by Sicria** [OptimalBits/bull#681]
If I don't start a dev server say over the weekend, on Monday when I attempt to start it up, the queue has to catch up and then fires off thousands of queued (repeated) jobs.

Is there a way to purge the list on startup or a flag which can be added to the job ``.add()`` method which allows you to remove all previously scheduled jobs.

I thought that ``queue.empty()`` would work but it doesn't.

```
  // Empty the queue of old tasks
  queue.empty()
    .then(() => {
      // Add the processor for this queue
      queue.process(name, method);

      // Add the reoccurring task
      queue.add(name, methodData, { repeat: { cron } });
    });
```

Surely others are getting this issue, or maybe I'm just init the job incorrectly.

**Comment by manast** [comment]
Which version are you using? in 3.0.0 the repeated jobs do not accumulate anymore.

**Comment by Sicria** [comment]
Currently using ``^3.0.0-rc.4``.

**Comment by manast** [comment]
yeah, you should upgrade to 3.0.0. release candidates have several known issues, check the CHANGELOG.

**Comment by Sicria** [comment]
Thanks for your help, I'll upgrade now.
