### ISSUE TITLE
Add waiting timeout option

### ISSUE THREAD

**Issue by NassiHarel** [OptimalBits/bull#684]
Something like:

```js
const Queue = require('bull');
const queue = new Queue('test-job');

queue.on('global:waiting', function (job) {
    console.log('global:waiting');
}).on('global:waiting-timeout', function (job, err) {
   console.log('global:waiting-timeout');
})

const options = {
    timeout: 10000,
    waitingTimeout: 10000
}

queue.add({ data: 'bla' }, options);
```

**Comment by manast** [comment]
I think that the best way to implement this in the current design is that when a job arrives to a worker/consumer, it checks if the job has timed-out and in that case discard the job and emit the event. Otherwise we would need a periodic check of all the elements in the waiting list, which would add unnecessary overhead.

**Comment by weeco** [comment]
@manast If one doesn't really need a event fired in case a job timedout you could also set a TTL for the redis key no? That should be the most efficient and reliable way I think

**Comment by manast** [comment]
@weeco the jobs are inside a list, so redis EXPIRE cannot be used. Also you would probably want to have the job fail so that you can have some record of it (and if not just enable the ```removeOnFailed``` flag)

**Comment by jaulz** [comment]
Does anyone have a solution for this? Is there a way to find out the actual start time of a repeatable job? Then I could simply compare it before the job is executed and return early if necessary.

**Comment by mararrdeveloper** [comment]
Why is this closed? It would be a nice feature

**Comment by manast** [comment]
it is quite easy to do with current library, just check the timestamp field in the job and compare to now, if larger than TTL just throw an error.
