### ISSUE TITLE
Does Job.finished() work if any node picks up the job and completes it?

### ISSUE THREAD

**Issue by npahucki** [OptimalBits/bull#687]
Or does it only work if the job is completed by the same node (process) that is awaiting the promise? i.e. is it local or global?

If there is a better way of asking questions, please let me know.

**Comment by manast** [comment]
It does not matter who picks the job, so it is global.

**Comment by npahucki** [comment]
One follow up question. If a job has retries set, will the finished() only return on the final failure, or will it return on the first failure even those the job is not really 'finished' because it might succeed in one of the retries?

**Comment by manast** [comment]
it should resolve the promise when the job has been finally failed, not between retries.
