### ISSUE TITLE
Incompatible with Redis 4 or Node 8?

### ISSUE THREAD

**Issue by mikl** [OptimalBits/bull#692]
I’ve been trying to integrate Bull into a project, but it strangely fails to work. No errors, it just doesn’t seem to do anything.

I’ve made this test script:

```
const Queue = require('bull')

const testQueue = new Queue('testing')

testQueue.process(function(job, done) {
  console.log('TESTING 1-2-3', job)

  done()
})

setInterval(function () {
  testQueue.add('bingo', new Date())
}, 3300)

console.log('Testing Bull, you should see more messages popping up every 3300ms')
```

Running it produces the output from the last line of the script, but nothing futher. The process keeps running, so the Node.js runtime seems to think that something’s going on, but no output is produced.

I’m running Node.js version 8.5.0 and Redis 4.0.1.

Bull does successfully connect to Redis, and saves something in there, as per this output from `redis-cli`

```
127.0.0.1:6379> keys *
1) "bull:testing:stalled-check"
2) "bull:testing:id"
3) "bull:testing:failed"
4) "bull:testing:2"
5) "bull:testing:3"
6) "bull:testing:1"
```

Is there some undocumented incompatibility I’m hitting? As far as I can tell from the docs, this should work.

**Comment by manast** [comment]
You are adding a "named" job but you are not defining a process function for that name. Check this:
https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd
"An optional name can be added, so that only process functions defined for that name will process the job."

**Comment by mikl** [comment]
> You are adding a "named" job but you are not defining a process function for that name.

Ah, right. My bad, sorry for the misunderstanding.
