### ISSUE TITLE
Why queue is not repeatable

### ISSUE THREAD

**Issue by jirayuzanroo** [OptimalBits/bull#695]
following the below code
```js
const Queue = require('bull')

`const tmpQ = new Queue('test', {
  redis: {
    host: '127.0.0.1',
    port: 6379
  }
})

tmpQ.process('Helloworld', (job, done) => {
  console.log(new Date())
  console.log('Hello World')
  done()
})

async function test() {
  const x = await tmpQ.add('Helloworld', {
    image: 'abcded'
  }, {
    repeat: {
      cron: "*/1 * * * *"
    }
  })

}
test()`
/// i would like to set it to repeat but it cannot it just do once a time
output:
`2017-09-21T09:13:27.508Z
Hello World`
```

what was my wrong ?

**Comment by jirayuzanroo** [comment]
for package i already tried version 3.1.0 , 3.2.0
![image](https://user-images.githubusercontent.com/20275728/30688872-84281a2c-9ee9-11e7-9349-d78388b0783c.png)

**Comment by manast** [comment]
Can you check this issue and see if it resolves your problem? https://github.com/OptimalBits/bull/issues/675

**Comment by jirayuzanroo** [comment]
sorry for bothering you. i supposed to it was my machine i don't know why did not work. right now i can use it. thanks
