### ISSUE TITLE
Execution of passed object methods ?

### ISSUE THREAD

**Issue by playahater** [OptimalBits/bull#705]
Hello,
I'm trying to create a dynamic job execution based on passed object.

Please consider the following code:

```javascript
// part of Job class
var commandQueue = new Queue('command');  
commandQueue.process(job => { 
  return job.data.execute();  // this is the key point
}); 
```

```javascript
let foo = new Foo({
 key: value,
 key1: value1
});
let job = new Job(foo);
job.dispatch(); // wrapper around bull's .add method
```

```javascript
class Foo {
  constructor(params) {
    this.params = params;
  }
  public async execute() {
    // return after do stuff
  }
}
```

Now, idea is to be able to execute a class [Foo] method passed to a job.
Current problem is that i get in job.data only what i have passed in constructor [params]. No class methods available :(.
As far as i see, this is a feature and it is not currently possible due to json serialization.
Any idea how could i overcome this in bull ?

p.s. - any plans to support serialization of methods as well at some point ?

Thanx in advance,
Cheers

**Comment by manast** [comment]
I do not think it is possible to serialize functions, at least not in a trivial way, so the answer would be no, no plans to implement it.
