### ISSUE TITLE
Empty and clean jobs

### ISSUE THREAD

**Issue by nanom1t** [OptimalBits/bull#709]
Hi, 

I'm using bull in my Node.js application. It works good, but sometimes appears issues with repeated jobs especially on application restarts. In my case one or more repeated job don't runs. I've found that I can fix this issue by clearing Redis (flushdb) and restarting application. Then everything works good.

So I've decided to clean all queues on application start. I've found `emply` and `clean` methods in [documentation](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueempty). However, it is not clear for me how do they work with Redis. Should they clear Redis database after execution?

I've tried `emply` / `clean` methods and they don't clean my Redis db. So I have duplicates:
```
127.0.0.1:6379[1]> keys *
 1) "bull:vip:repeat"
 2) "bull:notify:repeat:vk-scheduler:notify-scheduler:1506930900000"
 3) "bull:notify:repeat:vk-scheduler:notify-scheduler:1506930600000"
 4) "bull:vip:repeat:scheduler:vip-scheduler:1506942000000"
 5) "bull:vip:repeat:scheduler:vip-scheduler:1506930828000"
 6) "bull:vip:id"
 7) "bull:notify:id"
 8) "bull:notify:repeat"
 9) "bull:notify:repeat:cleaner:notify-cleaner:1506996000000"
10) "bull:notify:repeat:vk-scheduler:notify-scheduler:1506930300000"
11) "bull:vip:repeat:scheduler:vip-scheduler:1506930880000"
```
In this case `vip-scheduler` should run two times per day (0 0 2,12 * * *), but there are duplicates in Redis. So I'm not sure how many times it will be executed. Does it matter what stores in Redis database?

```
queue.add('scheduler', {}, { jobId: 'vip-scheduler', repeat: { cron: '0 0 2,12 * * *' }, removeOnComplete: true, removeOnFail: true });
queue.process('scheduler', vipWorker.scheduler);
```

Thanks

**Comment by manast** [comment]
which version of bull are you using?

**Comment by nanom1t** [comment]
^3.0.0-rc.4

**Comment by manast** [comment]
ok. Please check with latest version 3.2, there are several issues fixed since that release candidate related to repeatable jobs.

**Comment by nanom1t** [comment]
Ok. I'll try new version. Thank you!

**Comment by manast** [comment]
Did it work as expected with the latest version? if so please close this issue.

**Comment by nanom1t** [comment]
I've tried v3.2.0 and it seems that this issue is not fixed. Also I've tried to reproduce this issue.

I'm using `empty` method to clean the queues before initialization. So I'm expecting that Redis database will be cleaned before queue initialization.
```
var queue = new Queue('vip', { redis: redisConfig });
queue.empty().then(function () { 
    queue.add('scheduler', {}, { jobId: 'vip-scheduler', repeat: { cron: '0 0 2,12 * * *' }, removeOnComplete: true, removeOnFail: true });
    queue.process('scheduler', vipWorker.scheduler);
    
    resolve(queue);
}).catch(function (err) {
     reject(err);
});
```
Let's see my Redis database after first initialization:
```
1) "bull:vip:repeat:scheduler:vip-scheduler:1507338000000"
2) "bull:vip:repeat"
3) "bull:vip:id"
```
Everything works as expected. Then I've changed the cron schedule for this job to '*/5 0 2,12 * * *', restarted application and got next results:
```
127.0.0.1:6379[1]> keys *
 1) "bull:vip:stalled-check"
 2) "bull:vip:repeat:scheduler:vip-scheduler:1507338000000"
 3) "bull:vip:repeat"
 4) "bull:vip:delayed"
 5) "bull:vip:id"
 6) "bull:vip:repeat:scheduler:vip-scheduler:1507633200000"
```
Now I have **two** repeated jobs. So I can suppose that the `queue.empty()` does not clear Redis db as expected. 

Let's just clear queues without adding new jobs or processing:
```
var queue = new Queue('vip', { redis: redisConfig });
queue.empty().then(function () {    
    resolve(queue);
}).catch(function (err) {
     reject(err);
});
```
The `empty` method didn't clear old jobs in queue:
```
127.0.0.1:6379[1]> keys *
1) "bull:vip:repeat:scheduler:vip-scheduler:1507338000000"
2) "bull:vip:repeat"
3) "bull:vip:id"
4) "bull:vip:repeat:scheduler:vip-scheduler:1507633200000"
```

Thank you.

**Comment by brianlovin** [comment]
Subscribing here - I've been wondering how to approach this same issue for a while now, as every application restart kept inserting duplicate repeat jobs into redis. Thanks for looking into this!

**Comment by weeco** [comment]
Same issue here, haven't figured out exactly what's going on there, but I will try to provide more details once I can. Very annoying. It seems it adds a new cronjob every time the queue.add() with repeat settings is executed. It should be ignored instead of adding another job. I am not sure if that's the case, but I will certainly investigate it as good as possible.

**Comment by derN3rd** [comment]
With version 3.3.6 I can't clear and re-create "cronjobs" on fresh deployments. At the first start it works, but after a restart no new job is created.
Am I doing something wrong or is this the same problem?
```
const cronjobQueue = new BullQueue('cronjobs', {
  redis: { db: 1, host: process.env.redisip },
})
cronjobQueue.process('newIntervalStats', () =>
  Stats.newIntervalStats()
    .catch(logError)
)
/* http for bull-arena and other stuff */
http.listen(8081, () => {
  console.log(`Worker ${version} online on port 8081.`)

  cronjobQueue
    .empty()
    .then(() =>
      Promise.all([
        cronjobQueue.add(
          'newIntervalStats',
          {},
          {
            removeOnComplete: true,
            repeat: {
              cron: '*/1 * * * *',
              tz: 'Europe/Berlin',
            },
          }
        ),
        cronjobQueue.add(
          'newTotalStats',
          {},
          {
            removeOnComplete: true,
            repeat: {
              cron: '0 0 3 * * *',
              tz: 'Europe/Berlin',
            },
          }
        ),
        /* more jobs were here, but I removed them, because the look nearly the same */
      ]).then(() => console.log('Cleaned old and added new cronjobs'))
    )
    .catch(logError)
})
```

**Comment by manast** [comment]
I'll try tomorrow, lets see what I can find...

**Comment by derN3rd** [comment]
I made a workaround that I'm using in production right now, because I didn't get it to work in any other way:

```
const redis = require('redis')
const redisClient = redis.createClient({ host: REDIS_IP, db: REDIS_DB })

const completelyCleanQueue = queueName =>
  new Promise((resolve, reject) => {
    redisClient.scan(0, 'MATCH', `bull:${queueName}:*`, (err, data) => {
      if (err) return reject(err)
      if (data[1]) {
        return Promise.all(
          data[1].map(
            entry =>
              new Promise((resolve, reject) =>
                redisClient.del(entry, (err, data) => {
                  if (err) return reject(err)
                  return resolve(data)
                })
              )
          )
        )
      }
      return resolve()
    })
  })
```
use with caution, I'm not that familiar with redis.

I'm using it in the following way:
```
myQueue.empty().then(() => completelyCleanQueue('myQueueName'))
.then(() => doWhatEverYouWant)
.catch(err => logThatError)
```

**Comment by Freundschaft** [comment]
I looked into this and the reason is that queue.empty doesnt actually clear the jobs that are in the queues.
It only clears jobs in the wait and paused queue. (https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L648)
The repeat jobs are stored with a repeat prefix, and in order to clear them, each of them needs to be deleted one by one.
In order to properly work it should run something like the imlpementation from @derN3rd

**Comment by manast** [comment]
yeah. empty just cleans the "queue", not all the jobs that have been processed by the queue :).
Maybe it should be called differently to avoid confusion, "discard" or something like that.

**Comment by Freundschaft** [comment]
a solution I used that doesnt involve adding another library is this:

```
queue.clean(0, 'delayed');
queue.clean(0, 'wait');
queue.clean(0, 'active');
queue.clean(0, 'completed');
queue.clean(0, 'failed');

let multi = queue.multi();
multi.del(queue.toKey('repeat'));
multi.exec();
```

**Comment by Sicria** [comment]
@Freundschaft Since ``queue.clean`` returns a promise it might be best to add an ``await`` for all of those to avoid any issues where you're cleaning anything that might have just been set to run.

**Comment by derN3rd** [comment]
@Sicria or simply use `Promise.all([queue.clean(),...])`

**Comment by denizdogan** [comment]
In my opinion, `Queue#empty` should actually remove *all* the entries, including completed, failed, etc. If this is not desirable, the documentation should be updated to reflect this. It currently says:

> Empties a queue deleting all the input lists and associated jobs.

The terminology is a bit confusing to me, what is an input list?

**Comment by manast** [comment]
Thats lists containing jobs that have not yet been processed.

**Comment by Freundschaft** [comment]
Any reason this isnt put in the library itself and exposed via a simple function?

**Comment by pariola** [comment]
still no fix?, cause on clean everything stucks

**Comment by PierreAndreis** [comment]
Redis is using over 1gb of ram because bull keeps the "data" and there is no way to clean up old jobs...

**Comment by mrbatista** [comment]
@manast any update? This is a critial bug...

**Comment by blazedd** [comment]
This issue is nearing a year old. Any resolution in sight?

**Comment by manast** [comment]
Ok, so I am trying to make sense of this issue because in this thread there is a mixture of different issues and there are also false expectations of some apis. I will try to clarify:
```queue.empty```  empties the "queue", meaning that all jobs that are waiting to be processed are discarded, maybe the name is not a very good one, but that is that it does. It is not a wipe all kind of thing. 
```queue.clean``` removes jobs from a given "status", for example you can remove all the jobs that are completed, failed, delayed, etc. It would be possible to implement ```empty``` with clean by calling clean several times on the "status" a job can be when waiting to be processed, such as "wait", "paused", "delayed", "priority".

Finally, repeatable jobs are a special type of job that creates an entry in the "repeat" zset. As long as an entry representing a given repeatable job is in this set, the job will repeat according to its cron values, so in order to remove it you need to use the ```queue.removeRepeatable``` method, as stated in the documentation.

If the same repeatable job is added several times it should result in a noop, otherwise it is a bug. In the version of bull at the time of this writing (3.4.7) there is no know issue regarding removing repeatable jobs.

I am willing to improve the empty and clean functionalities, it would require a major version though.

I will close this thread for now and if based on the information above you find an inconsistent behaviour please open a new issue and I will work on it as soon as possible.

**Comment by sainipradeep** [comment]
> a solution I used that doesnt involve adding another library is this:
> 
> ```
> queue.clean(0, 'delayed');
> queue.clean(0, 'wait');
> queue.clean(0, 'active');
> queue.clean(0, 'completed');
> queue.clean(0, 'failed');
> 
> let multi = queue.multi();
> multi.del(queue.toKey('repeat'));
> multi.exec();
> ```

How to clear selected named queue ?

**Comment by yundy0605** [comment]
You can try this
```
const Queue = require('bull')
const testQueue = new Queue('test')
testQueue.clean(0, 'delayed')
```
But I use the library from bull document
The code below I sure that it can work (check and clear the expired data for over 5 sec every 5 sec)
```
const Queue = require('bull')
const testQueue = new Queue('test')
setInterval(() => {
  testQueue.clean(5000)
}, 5000);
```

**Comment by atwright147** [comment]
How about `queue.clear()` to clear out all jobs from a queue?

**Comment by vdkkia** [comment]
I could handle the issue with the following code:

```
 const redisClient = new Redis({ port, host, password })
 const pipeline = redisClient.pipeline();
  const keys = await redisClient.keys("bull*");
  keys.forEach((key) => {
    pipeline.del(key);
  });
  await pipeline.exec();
```

**Comment by derN3rd** [comment]
> I could handle the issue with the following code:
> 
> ```
> const redisClient = new Redis({ port, host, password })
> const pipeline = redisClient.pipeline();
> const keys = await redisClient.keys("bull*");
> keys.forEach((key) => {
>    pipeline.del(key);
> });
> await pipeline.exec();
> ```

I wouldn't recommend this, as this will clear all queues on the redis (or at least all that have the bull prefix, which is on default config).
Also `KEYS` is having a complexity of O(N) which will block the whole redis for quite some time (even more if you have large queues).

With 3.21.0 there was a function added called queue.obliterate which will basically remove the whole queue and keys for it, but it will clean it in batches of 1000 keys, which will not block the whole redis

**Comment by vdkkia** [comment]
> queue.obliterate

But, the downside with the obliterate function is that it doesn't remove the active jobs.

**Comment by derN3rd** [comment]
> But, the downside of the obliterate function is that it doesn't remove the active jobs.

You can't stop active jobs on queue without custom code for that. But you can pass queue.obliterate({ force: true }) to `Use force = true to force obliteration even with active jobs in the queue`

**Comment by eduardobcastro** [comment]
If you have a dedicated redis for your queue, send a `FLUSHALL` to it

**Comment by bhnybrohn** [comment]
this will clear all queues,
