### ISSUE TITLE
How to reuse existing queue?

### ISSUE THREAD

**Issue by rajaraodv** [OptimalBits/bull#71]
Hi,
I have a producer.js that creates 'app'(producer) and 'worker' queue and also a worker.js that also creates 'producer' and 'worker' queues.  I have this setup to make both of interact w/ each other. I was thinking that at this point both producer and workers will reuse the queues. But I see that in fact they don't reuse the queue names, but instead each one simply creates a new queue w/ the same name. And whenever I restart my app, it creates a new pair of worker and producer queues in redis. 

Wondering how to reuse old queues w/ the same names or what's the best practice?

BTW, thanks for the library.

**Comment by albertjan** [comment]
@rajaraodv on one database there can only be one queue with the same name. So your producers and workers that are initialized with the same name use the same queue.

**Comment by albertjan** [comment]
The queue list in redis will have the name `bull:<queuename>:wait` all jobs that have been taken by a worker end up on the `bull:<queuname>:active` list.

**Comment by rajaraodv** [comment]
That's not what's happening. On the same database, I see: bull:producer:1, bull:producer:2 and so on.  The same thing happens for worker queue as well. This gets added everytime I restart the server just cause I have var producer = Queue('producer') and  var worker = Queue('worker') in my app. 

 See the pictures: 
![screen shot 2015-01-04 at 11 25 40 am](https://cloud.githubusercontent.com/assets/626337/5607174/8612d108-9404-11e4-84c1-131c1085761f.png)
![screen shot 2015-01-04 at 11 25 25 am](https://cloud.githubusercontent.com/assets/626337/5607173/861086e6-9404-11e4-889a-c5bbb408546b.png)

**Comment by albertjan** [comment]
those are the `Job`'s you have two queue's named `Workers` and `Producer` the elements ending with an int are added when you call `Job.create`

**Comment by rajaraodv** [comment]
Ah, got it!  I guess I needed to add job.remove() after the job was completed.

Thanks!
