### ISSUE TITLE
export `Job` and other things userland might need?

### ISSUE THREAD

**Issue by ianstormtaylor** [OptimalBits/bull#710]
I see in the `3.x` migration docs that it's recommended to use `Job.fromId()`, but `Job` doesn't appear to be exported?

**Comment by ianstormtaylor** [comment]
Actually, the docs also say that events now receive `jobId` instead of `job`, but I'm not seeing that happening?

**Comment by ianstormtaylor** [comment]
I also don't see the `queue.isReady()` method in the docs. Have the docs been updated for the `3.x` version at all?

**Comment by manast** [comment]
You are right, Job.fromId is private, but you can use this instead: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queuegetjob
Regading isReady, it is also private, it is not really needed in userland.

**Comment by manast** [comment]
@ianstormtaylor hopefully the pain to upgrade to 3.x is worth it. There are very important improvements all around the place.

**Comment by ianstormtaylor** [comment]
@manast thank you, I'm sure they will be. A few things were pretty painful, but once I'm on `3.x` I'll be very happy. Thank you for this library!
