### ISSUE TITLE
Is there a way to remove repeatable jobs?

### ISSUE THREAD

**Issue by asadabbas88** [OptimalBits/bull#712]
I see that removeRepeatable function is not part of 3.2.0 .. or even previous releases .. is there anything i am missing here?

**Comment by manast** [comment]
Its in master, will be available in 3.3.0 release. Hopefully released this weekend.

**Comment by asadabbas88** [comment]
Hi manast, thanks for the update .. looking forward to the release

**Comment by manast** [comment]
fixed in 3.3.0
