### ISSUE TITLE
Problem with concurency

### ISSUE THREAD

**Issue by Asp3ctus** [OptimalBits/bull#719]
When i have one queue, and i add named process to it, concurency is increased to the amount of the proccesors

For example:
const test = new Queue('test', {redis});

test.process('test1', require('./processors/test1));
test.process('test2', require('./processors/test2'));

I expect each proccessor run one at the time .. but it runs 2 at the time, if i add 3 proccesor - then it run 3 at the time.

The only work around i have found is to create seporate queue for each proccesor.

Is it supposed to work like that?

I use bull@3.3.1

**Comment by Asp3ctus** [comment]
Is it expected behavior or a bug ?

**Comment by manast** [comment]
yes it is by design.
