### ISSUE TITLE
Resolved promise upon job completion

### ISSUE THREAD

**Issue by weeco** [OptimalBits/bull#728]
I saw that Queue.add() returns a promise and I really hoped the Promise would resolve upon job completion for that specific job. I think the Promise just resolves to the inserted job.

For a stateless API Request Scheduler I would like to return a Promise which resolves to the response from the process function. This way I could use Bull to distribute all my API request under respect of rate limits across all instances. 

If it's not possible with Bull could you maybe lead me into the right direction to implement that?

**Comment by manast** [comment]
https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#jobfinished

**Comment by weeco** [comment]
Works perfectly, thanks again and sorry that I haven't noticed it in the documentation, I was looking at the Queue.add method because that's where I expected the Promise to be returned.
