### ISSUE TITLE
Warning: a promise was created in a handler, but was not returned from it

### ISSUE THREAD

**Issue by ritter** [OptimalBits/bull#734]
```
const Promise = require('bluebird');
Promise.config({'warnings': true});
```
Results:

> Warning: a promise was created in a handler at node_modules/bull/lib/queue.js:742:15 but was not returned from it, see http://goo.gl/rRqMUw

There may be others, but this is the one I see most often.

**Comment by manast** [comment]
fixed in https://github.com/OptimalBits/bull/pull/736
