### ISSUE TITLE
More documentation for JobIds

### ISSUE THREAD

**Issue by weeco** [OptimalBits/bull#743]
Currently I am using Bull as rate limiter + queue for consuming an API. There I can request userprofiles by specific IDs. I thought it would be smart to use the unique userId as jobId to avoid double processed requests (e. g. I want to request user 631 but it's already in the queue).

Right now the documentation says 

> If you attempt to add a job with an id that already exists, it will not be added.

Does that mean an exception will be thrown? Since add is supposed to return a job (that's what the documentation says) I wonder if it would return the Job with the id I've just tried to add.

That's why I am expecting a job to be returned: `add(name?: string, data: any, opts?: JobOpts): Promise<Job>` It would be Promise<Job|null> if there is a possibility it wouldn't return a job or?

**Comment by manast** [comment]
If you add a job with the same id as an existing job, the job will not be added but it will be returned, so yes, it should always return a job.

**Comment by weeco** [comment]
@manast Can you provide that information so that I can update the docs regarding this? If priority upgrading (in case someone trys to enqueue another job with the same id but higher priority)  on duplicate jobId is not implemented, consider it as enhancement request.

It would mean the world to me to see this implemented.

**Comment by manast** [comment]
When you add a job with the same id then it is just ignored, so it does not affect the priority. But basically, what you want is to update and existing job, are you not?

**Comment by weeco** [comment]
I use Bull for consuming a REST Api with rate limits. I have a few background tasks (for instance 2 million accounts which needs to be refreshed by sending a request) and I have foreground tasks (like requesting an account right now because it's needed). I use the unique account ids as job id to avoid duplicate requests (I am rate limited so I need to save as many requests as possible).

For the background tasks I insert all jobs with a priority of 9, for all foreground tasks I use a priority of 5. So assuming I have one account with the id 134 in the background queue with priority 9 and then I suddenly need the account with the id 134 immediately (so I add it with a higher priority). If Bull would upgrade the priority of this job instead of ignoring it completely the background task with id 134 will be fullfilled and the foreground task would be fullfilled in time as well.

The best thing: It wouldn't send two requests to the API!

**Comment by manast** [comment]
Wouldn't ```promote``` help in your case? https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#jobpromote

**Comment by weeco** [comment]
I don't think so, that would require me to know if the job has been queued already, also it seems to do more than just upgrading the priority (as far as I understand it will be executed as fast as possible then).

Also this should happen kinda implicit if I add an job with an existing jobId. I can't imagine a use case where this wouldn't be desired if someone uses own jobIds.

**Comment by weeco** [comment]
@manast Any update on this? Do you want to change it from better doc to enhancement if this feature doesn't exist (yet)?

In the meantime I will check if a better documentation for the jobIds is necessary.

**Comment by weeco** [comment]
Bump
