### ISSUE TITLE
Add kafka to the feature comparison table in readme

### ISSUE THREAD

**Issue by mk-pmb** [OptimalBits/bull#745]
Thanks!

**Comment by weeco** [comment]
Can you provide a github link to kafka? I can't find any job scheduler / queue message system called kafka?

**Comment by mk-pmb** [comment]
As I found out there are lots of unmaintained "kafka" packages on npm, so it's a good thing you ask for a specific one. I'd like a comparison for `kafka-node` = https://github.com/SOHU-Co/kafka-node .

**Comment by crcastle** [comment]
Apache Kafka is not a job scheduler or queue or message system -- although of those three, it is closest to a message system.

Although it does have queue-like characteristics (e.g. FIFO), Kafka's documentation describes it as a "distributed commit log" and "a distributed streaming platform".

I think the best way to make comparisons would be like this:
- Data persistence service: [Kafka](https://kafka.apache.org/) <---> [Redis](https://redis.io/)
- Client library to connect to specific data persistence service: [kafka-node](https://github.com/SOHU-Co/kafka-node) <---> [ioredis](https://github.com/luin/ioredis)
- A job queuing and processing service: ??? <---> bull

So it doesn't really make sense to compare bull directly to Kafka.  A job queuing and processing service like bull could definitely be built on top of Kafka.  Maybe someone has already done it! 😄 

@manast, I wasn't sure if it made sense to put this in bull's docs, but feel free to add it to the docs (or point me to where you'd like it added via a PR).

**Comment by zhenyulin** [comment]
I'll post a related StackOverflow thread here:
https://stackoverflow.com/questions/37990784/difference-between-redis-and-kafka
https://logz.io/blog/kafka-vs-redis/

The key takeaways are Kafka is more optimised for persistence (originally it is probably developed for log processing, which means a large size of data with the requirement to avoid data loss), while redis based solution is more light-weight, faster but suffers from data-loss, i.e. any server/node/instance restart could erase the in-memory data, which can be those unprocessed jobs in the queue.

As Kafka comes with a pub/sub solution, the producer/consumer pattern can be used to achieve what bull is providing.

**Comment by zhenyulin** [comment]
As an example of use cases, I would use Bull to manage light-weight cronjobs with some allowance of fault, such as the CI configuration update, etc.

**Comment by manast** [comment]
I will close this issue, because as mentioned before, bull is just a library built on top of redis, it does not really make sense to compare it to kafka.

**Comment by mk-pmb** [comment]
The redis devs would probably prefer you edit "suffers from data-loss" to include "(unless configured for persistence)". ;-)
