### ISSUE TITLE
Submit to http://queues.io/

### ISSUE THREAD

**Issue by bradvogel** [OptimalBits/bull#746]
Just ran across the site http://queues.io/ that appears to be a comprehensive list of queues across many languages. I noticed Kue was on there, but not Bull. Would be nice to get it on there! :)

**Comment by bradvogel** [comment]
Oh, someone beat us to it https://github.com/lukaszx0/queues.io/pull/124

**Comment by manast** [comment]
Since a PR has already been submitted I think we can close this.
