### ISSUE TITLE
Possible breaking change

### ISSUE THREAD

**Issue by tarunbatra** [OptimalBits/bull#754]
In `3.3.2`, the jobs are stored in Redis in form of:
```
repeat:__default__:<jobId>:1508794200000
```

But in `3.3.3`, this changes to something like:
```
repeat:a2156c28b92f498b9683f6088ea0f34e:1508814900000
```

My app depends on the Inclusion of JobIds in Redis keys. So this is a breaking change for me and I'm sure many others.

**Comment by manast** [comment]
I see. Can you explain in which context and how you use the jobId? The key format for repeatable jobs is a private data structure, so it is susceptible to changes even between minor and patch versions. Maybe some api is missing to achieve whatever you are doing today accessing the keys by hand, let me know so we can discuss.

**Comment by tarunbatra** [comment]
My bad. I just realized, I'm not reading the Redis keys anywhere. Please feel free to close the issue.

Plus this change should also solve #727, I guess!

**Comment by manast** [comment]
exactly! :D
