### ISSUE TITLE
Weird behaviour with repeat jobs - triggered at wrong time

### ISSUE THREAD

**Issue by tschaefe** [OptimalBits/bull#759]
Hi,

I have a really weird behaviour that I cannot find the reason for.

My current setup:
I have a queue that holds around 40 repeat jobs, all with a unique name, some of them have the same cron iteration.
In addition to that I have a special repeat job in the same queue, that is running every hour to check if new repeat jobs needs to be added or if some needs to be updated or removed, just to ensure that they are always there (like a queue manager job).

The Problem:
Whenever this regular cron job (hourly) is running (and almost he does nothing, just calls getRepeatJobs() in generell), it seems that he will also force one of the other repeat jobs to be processed.
For Example:
The hourly job is scheduled like this: "40 * * * *"
So when he is executed at: 
Process Time: 2017-10-26 02:40:00 (hourly job)

Then this job is processed as well:
JobId: repeat:10f2bb94008cac89239d9f640cfd0357:1508994000000
Configuration for cron is this: "0 0 5 * * 1-5"

The timestamp in the JobId resolves to 05:00 a.m. and not 2:40 a.m.

It seems also that this processing of an additional job is not just related to this hourly job. Other repeat jobs (when they will be processed) can also force this behaviour. But they will not always do this. really weird.

Any ideas what could went wrong?

Current used version: 3.4.0
Redis 3.2

**Comment by manast** [comment]
@tschaefe can you provide more info regarding the setup, for instance, concurrency levels, number of bull workers instances, etc ?.
Could you test this workaround: use a different queue for every cron job instead of sharing the queue with all the repeat jobs? (and let me know if it makes any difference)

**Comment by ritter** [comment]
I'm having similar issues as well with repeat jobs still.  Same as @tschaefe I have several jobs in a single queue, and more than one are triggered when they should not be.  With v3.3.2 and v3.3.3 the jobs would get removed from the delayed zset.  With v3.3.4 they remain, but are erroneously being triggered at the wrong times.

Bull v3.3.4
Node 6.11.4
Redis 3.2.6

**Comment by tschaefe** [comment]
Hi,

short update for now:

concurrency level at the moment is 10 and I just run one worker instance. I have to rewrite some code to test the mentioned workaround. I'll try to add this information as soon as possible
