### ISSUE TITLE
Queue process concurrency

### ISSUE THREAD

**Issue by ritter** [OptimalBits/bull#760]
```
const Queue = require('bull');
const test = new Queue('test');
test.process('job1', 1, () => { done(); });
test.process('job2', 10, () => { done(); });
```
Job concurrency of job1 will be 10 per worker, expected 1 per worker.

**Comment by manast** [comment]
I think it is not 10 but 11 in this particular case

**Comment by ritter** [comment]
Am I misunderstanding the process concurrency?  For the time being, I've separated the processes to unique queues.

**Comment by manast** [comment]
yes, it is not trivial to have different concurrency levels for different named jobs, we may end changing the api so that this behaviour does not come as a surprise.

**Comment by ritter** [comment]
Okay, thanks for the clarification.  I'm okay if this issue is closed.

**Comment by manast** [comment]
I can leave it as an enhancement to avoid future duplicates.

**Comment by Asp3ctus** [comment]
i would love to see this improved as well

**Comment by weeco** [comment]
Also see https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueprocess , if you scroll down a bit it's explained there.

**Comment by Asp3ctus** [comment]
@weeco yes - it's explained - but still it should not work like that. and that explanation was added after my issue #719

**Comment by weeco** [comment]
It is working by design. I don't like this and a few other behaviours either, but since these would be breaking changes I don't see them changing anytime soon.

**Comment by Asp3ctus** [comment]
well may be it could be a seperate feature or tunable behavior- i think some other people can find it usefull as well.
Let's vote :) +1

**Comment by swayam18** [comment]
+1

**Comment by manast** [comment]
If it was easy to implement, but the problem is that it requires several important changes in the core, so I do not think it is worth the effort, specially when you can just have 2 different queues to get the desired behaviour.

**Comment by chgcamp** [comment]
Except, with multiple queues seems you lose the ability to prioritize and have max concurrency across named jobs.

**Comment by MicahMartin** [comment]
bump...

**Comment by manast** [comment]
I am going to close this, since the issue has become unclear, and there is no proposed solution for it.

**Comment by tskweres** [comment]
What is the maximum amount of concurrency for a process? Anyone know?

**Comment by ciarans** [comment]
@tskweres did you ever find an answer for this?
