### ISSUE TITLE
Can I constrain processes to be ran once at a time? (handling simultaneous api requests within a queue process)

### ISSUE THREAD

**Issue by paulsoh** [OptimalBits/bull#767]
This is probably a pretty noob question, but I just have to ask 
Thanks for the great open source btw

I have a queue that syncs my local db with an external api (let's call it syncWithExternalDBQueue)
For each item in my db I would add it into the queue as following

```javascript
cron.schedule('* * * * *', function() {
  console.log(chalk.blue.bold('Syncing api with db'))
  syncWithExternalDBQueue.add({
    userId,
    params
  })
  ...
```

and inside my process it does something like this:

```javascript
syncWithExternalDBQueue.process(function(job, done) {
  if (!(job.data.userId && job.data.params)) {
    console.log('userId and params is necessary for syncing db')
    done(new Error('apiKey and apiSecret is necessary for updating balance'))
  }

  console.log('Making request')
  return axios({
    method: 'POST',
    url: 'https://db.com/userInfo',
    headers: { /* header stuff */},
    body: JSON.stringify({ userId: job.data.userId }),
    json: true
  })  
})
```

I noticed that the actual axios gets called once or not even once sometimes.
Should I move out the axios call to somewhere other than the process?

I'm aware of axios.all but I might have a lot of requests (>100) and I'm not sure if this is a good idea. Is there a way I can explicity tell the process to handle each process one at a time?

Thanks

**Comment by manast** [comment]
since you have not specified any concurrency level, and if you do not have any other workers, then it will only process one call after each other. However, you should not specify a "done" callback if you are returning promises, just use only promises or only the "done" callback.

**Comment by paulsoh** [comment]
Thanks. I somehow assumed processes were being handled concurrently.
