### ISSUE TITLE
High Memory on Big Queues (1mio+)

### ISSUE THREAD

**Issue by HashDot** [OptimalBits/bull#770]
Hi,

i use bull as a queue to fetch data with http requests. Over the time my queue reaches the 1mio completed jobs. So far so good, what is not good is the high amount of ram usage. Currently my completed jobs count is: 1,450,185 and with this my redis consumes about 3gb memory. This is pretty much. I've restarted the redis but it's still the same. Can you give me a hint how I can handle this amount of jobs? The problem is, this is only a small piece of the queue. If it is running with all the queues, I think I have more than 3 millions jobs per day. And it is growing.

Maybe it is possible to save the completed jobs in another database to keep the history. But I would prefer a solution to keep the jobs in redis but keep the completed jobs only persistent and not In-Memory.

Can you help me? :D

Greetings

**Comment by manast** [comment]
Bing redis a in-memory database it is not really possible to do what you want. My advice is that you store whatever you need from your completed job in a external database (you can do this just before the job completes), and that you enable the removeOnComplete job option: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd

**Comment by HashDot** [comment]
@manast thanks for your fast answer. I already thought that I have to solve it like that. 

Btw.: great product! keep it up!
