### ISSUE TITLE
FailedReason of null

### ISSUE THREAD

**Issue by weeco** [OptimalBits/bull#779]
I assume this exception is happening because I am inserting jobs with `{ removeOnComplete: true, removeOnFail: true }`. I am also using `Job.finished()` for all of my jobs.

> Unhandled rejection TypeError: Cannot read property 'failedReason' of null
>     at C:\Users\weeco\Documents\projectname-express\node_modules\bull\lib\job.js:402:39
>     at tryCatcher (C:\Users\weeco\Documents\projectname-express\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (C:\Users\weeco\Documents\projectname-express\node_modules\bluebird\js\release\promise.js:512:31)
>     at Promise._settlePromise (C:\Users\weeco\Documents\projectname-express\node_modules\bluebird\js\release\promise.js:569:18)
>     at Promise._settlePromise0 (C:\Users\weeco\Documents\projectname-express\node_modules\bluebird\js\release\promise.js:614:10)
>     at Promise._settlePromises (C:\Users\weeco\Documents\projectname-express\node_modules\bluebird\js\release\promise.js:693:18)
>     at Async._drainQueue (C:\Users\weeco\Documents\projectname-express\node_modules\bluebird\js\release\async.js:133:16)
>     at Async._drainQueues (C:\Users\weeco\Documents\projectname-express\node_modules\bluebird\js\release\async.js:143:10)
>     at Immediate.Async.drainQueues (C:\Users\weeco\Documents\projectname-express\node_modules\bluebird\js\release\async.js:17:14)
>     at runCallback (timers.js:781:20)
>     at tryOnImmediate (timers.js:743:5)
>     at processImmediate [as _immediateCallback] (timers.js:714:5)

**My guess:**

It seems the job has already been deleted (because it failed) and job.finished() wants to return a rejected Promise with the failed reason. When it tries to return the reason it throws an exception because the job doesn't exist anymore.

**Comment by manast** [comment]
you guess makes sense. If you can write a test case that reproduces it I can implement a fix.
