### ISSUE TITLE
queue.process(name, processor) not working when using a separate process

### ISSUE THREAD

**Issue by sylvainlap** [OptimalBits/bull#781]
Hello,

In the reference guide (https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueprocess), it is written that you can define a processing function thanks to `process(name, processor)`.

However, using this way, when the processor is a separate process (ie a string) thows a `TypeError: Cannot read property 'bind' of undefined`.

According to https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L522, if you use this way to define your processor as a separate process, `this.setHandler(name, handler);` leads to an handler to `undefined`.

**Comment by manast** [comment]
yeah you are right. I think I introduced this issue in one of my latest fixes. I will add a test and a fix ASAP.

**Comment by afham456** [comment]
HI there,  I am also getting a similar issue something like "handler.bind is not a functionTypeError: handler.bind is not a functionn at Queue.setHandler". Basically what I am trying to do is calling another queue function to add a job into the queue from inside a processor. Upon deeply inspecting I have found that my problem also resemble this case. Could you please help me regarding the same.
