### ISSUE TITLE
API doesnt allow to know when redis connection is ready

### ISSUE THREAD

**Issue by pmvrmc** [OptimalBits/bull#782]
When creating a new queue, there is no ready event for the redis connection, so we don't know if it is ready or not.
Digging through the code it looked to me that bull is only emitting redis 'error' event and not 'ready', 'reconnecting', etc.

Also the queue.isReady() will always resolve fine even if there is no connection ready:

```
const queue = new Queue('queue');
queue.isReady().then(() => {
  console.log('this is always print even if redis is down');
});
```

**Comment by levansuper** [comment]
I have the same problem. want to start a new task when the application starts but can not get the exact moment when to start the queue. when i add a new task it does not do anything if i don't setTimeout

**Comment by pmvrmc** [comment]
@levansuper I managed to work around that by using a helper function that calls the redis instance directly. This might help you:
```
const onceReady = log => (redisInstance, callback) => {
    if (redisInstance.status === 'ready') {
      return callback();
    }
    return setTimeout(() => {
      if (log) {
        log(['warn'], 'Redis connection not yet established, retrying...');
      }
      return onceReady(log)(redisInstance, callback);
    }, 500);
  };
```

**Comment by levansuper** [comment]
thanks man. i was also thinking about something like this but thought there would be a better way to do it.... it seams there is none...

**Comment by manast** [comment]
@levansuper write a snippet that reproduces you issue. What you say is completely taken care of, 
there is no need to wait for redis to be ready at all.

**Comment by pmvrmc** [comment]
@manast the problem is that if you want to wait for redis to be ready. If redis is down for example, bull doenst complain and just caches messages that are later sent. But for my case I don't want that, I want bull not to even start before redis is up.

It was failing silently for me until I had that work around

**Comment by manast** [comment]
@levansuper that code should not be necessary, but even it it were, you can just listen to the 'ready' event emitted from ioredis: 
https://github.com/luin/ioredis

**Comment by manast** [comment]
@pmvrmc how do you mean failing silently? did the jobs end in the queue when the connection was established or did the not?

**Comment by pmvrmc** [comment]
After redis is established they did, but if redis connection was never established (for some weird reason) you can never know what is going on

**Comment by maxerbox** [comment]
Check out https://github.com/luin/ioredis/blob/master/README.md#events, but you need to access to the redis instance used. In ioredis, there is an offlineQueue, which is used to store the queries and perfore them when the instance is connected

**Comment by manast** [comment]
@pmvrmc how comes, didn't you get an error event from bull?

**Comment by manast** [comment]
@pmvrmc I think the issue you have can be resolved by enabling this ioredis option: ```options.enableOfflineQueue```
Check here: https://github.com/luin/ioredis/blob/master/API.md
"By default, if there is no active connection to the Redis server, commands are added to a queue and are executed once the connection is "ready" (when enableReadyCheck is true, "ready" means the Redis server has loaded the database from disk, otherwise means the connection to the Redis server has been established). If this option is false, when execute the command when the connection isn't ready, an error will be returned."

**Comment by vance** [comment]
great work! seems to solve the wait-for-redis issue.
