### ISSUE TITLE
sandboxed job stuck when starting from a debugging node application

### ISSUE THREAD

**Issue by Freundschaft** [OptimalBits/bull#785]
Hi there,

Im using a sandboxed job and when I run my application everything works fine, but as soon as I use debugging from Webstorm I get the following message as soon as the sandboxed process spawns:

> Starting inspector on 127.0.0.1:1789 failed: address already in use

strangely enough, the job also gets stuck and never completes.
How can I properly adress this without having to fork bull? I know its related to node inspector being attached to the child process on the same port.

Thanks!

**Comment by manast** [comment]
This is a duplicate of https://github.com/OptimalBits/bull/issues/698 I do not have any solution for this at the moment.

**Comment by Freundschaft** [comment]
ah sorry, can be closed then, thanks!
