### ISSUE TITLE
is adding and querying metadata possible?

### ISSUE THREAD

**Issue by Freundschaft** [OptimalBits/bull#788]
I want to add metadata to a job, e.g. a customerId that was associated with the job.
Later I want to query running jobs that have that customerId, in order to show it to the customer on a dashboard.

is it possible to realize that without adding a layer on top of bull?

**Comment by manast** [comment]
The only data that we support is the data object specified when you create a job. We do not have indexes or other means in redis to support efficient searches. So I guess the best way would be to have a separata DB for this kind of stuff, and link every job id to its metadata counterpart in the other DB.

**Comment by Freundschaft** [comment]
alright, got it, thanks
