### ISSUE TITLE
Event fired when repeatable job is rescheduled

### ISSUE THREAD

**Issue by tdzienniak** [OptimalBits/bull#792]
Is there an event fired when repeatable job is rescheduled? It is in fact more general question: is there an event when any job is added to the queue? I was looking at the source code, but coudn't find anything.

**Comment by manast** [comment]
Actually there is the 'waiting' event, I noticed it is undocumented.

**Comment by tdzienniak** [comment]
Yes, I found that event in the source code, but it is not firing when repeatable job is rescheduled.

**Comment by manast** [comment]
yes you are right. The reason is that the repeated job always ends in the delayed set, and I noticed we are not emitting the wait event when moving a job from the delayed set to the wait queue. I will mark this a a bug.
