### ISSUE TITLE
What happen to failed jobs?

### ISSUE THREAD

**Issue by cranic** [OptimalBits/bull#8]
Hello there,

Nice package! What happen when a job fails? Will it go back to que queue as the next job or it will fail permanently?

Thx.

**Comment by jussi-kalliokoski** [comment]
:+1:

**Comment by albertjan** [comment]
there is a `queue.getFailed()` function isn't there?

**Comment by thebergamo** [comment]
Who I can actually retry a job?

**Comment by lchenay** [comment]
Here a code that i use to automatically retry job on fail.
Each job have a remainingRetry (default value defaultNBRetry that is assigned on first fail or when created job).
It have a native exponential backoff, to let temporary error to go away.

Could be easily inspired to find a generical implementation to PR in Bull.

```
queue.on('failed', function(job, err) {
        var data = job.data;
        data.remainingRetry = (data.remainingRetry || defaultNBRetry) - 1;
        data.retry = (data.retry || 0) + 1;

        if (data.remainingRetry > 0) {
            //Exponential backoff
            var delay = 5000 * Math.pow(3, data.retry);
            q.add(data, {lifo: true, job: delay});
        }
    });
```

**Comment by thebergamo** [comment]
@lchenay sounds good this implementation. 

But, when I catch the failed event, I don't know whats happen, but bull automatic retry this.(maybe my code are wrong :p) And I need set the job.isCompleted() for the job not requeue.

**Comment by manast** [comment]
retry has been implemented since some time ago so I will close this.

**Comment by slidenerd** [comment]
Quick question if you dont mind answering, how do I retry infinitely, I have a task that does an API request where it may fail several times but it has to happen once.

**Comment by manast** [comment]
you need to use a integer for the max number of attempts, but why not using a very large number? does it really make sense to retry forever?
