### ISSUE TITLE
Separate client and server instances

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#80]
Currently a Queue instance can act both as a client and as a worker. A client needs one redis connection and a worker needs 2 connections. Separating the client and server instances will be useful to reduce the amount of redis connections by 33% when many workers are needed.

**Comment by desmondmorris** [comment]
+1

**Comment by programming-kid** [comment]
+1

**Comment by cheshirecatalyst** [comment]
I would like to help with this. but am having a bit of trouble dissecting what is common to client and worker / what belongs in client, what belongs in worker. Also this would imply priority client and priority worker if i'm not mistaken, right?

**Comment by cheshirecatalyst** [comment]
bclient and eclient are exclusive to the workers correct?

**Comment by manast** [comment]
thats correct, only "client" is needed for the clients.

**Comment by manast** [comment]
but it may be the case that eclient is also useful for clients, to listen for events generated by the workers.

**Comment by binarymee** [comment]
@manast Is there any way to define a process just to execute the jobs.? I don't want the server processing http requests to process the background job, even if it is not part of request response life cycle. I want to have dedicated servers to process the BG jobs alone. 

As far as I searched, I know that it is currently work in progress. But I just wanted to know, is there any workaround now to achieve this?

**Comment by manast** [comment]
The recommended way to use bull is to have different processes, some acting as clients and others acting as dedicated workers. A process acting as worker is just one where you instantiate the queue and call the method ```process``` with your processing function.
This issue regards to reducing the amount of connections to redis. As in bull 3.0, 2 connections are always needed, independently if you instantiated the queue acting as a worker or acting as a client adding jobs to it. It could be possible to reduce the connections to 1 for queue instances that only add jobs to a queue and does not care about events. Workers on the other hand will always require 2 connections and is not possible to reduce this further with the current design.

**Comment by binarymee** [comment]
Thanks for the update @manast .

**Comment by manast** [comment]
We have now lazy connections so this is as good as it gets, and we do not need to explicitly specify if the instance is acting as a client or server without loosing anything, so I will close this now.
