### ISSUE TITLE
Does “bull” utilize multicore as node.js runs single-threaded

### ISSUE THREAD

**Issue by BestPractises2GO** [OptimalBits/bull#802]
Hello community,

according to the documentation

>     The process function can also be run in a separate process. This has several advantages:
> 
>        - The process is sandboxed so if it crashes it does not affect the worker.
>        -  You can run blocking code without affecting the queue (jobs will not stall).
>        -  Much better utilization of multi-core CPUs.
>        -  Less connections to redis.
> 
>     In order to use this feature just create a separate file with the processor.   
>     (..) This is a perfect way to run blocking code.
> 

My Question is:

does Bull utilize automatically multi-Core CPU as node.js runs on Single-Thread. And if yes, does make it sense to utilize multicore with Bull to run background tasks like massive mongodb-updates (updating my user-profile-avatar would run in req/res loop where as the updates on many many reference documents like in the friendship collection should run in background) which can take minutes or hours, so the users will not even notice when it takes a few minutes or even hours until all users of the network see the new avatar. Or does they mean with blocking code, code which blocks the Event-Loop like cpu-heavy tasks and not I/O operations like database-queries.

I would appreciate every information about that.

**Comment by manast** [comment]
Running processors as a separate process indeed implies utilising all the cores in the CPU. Regarding very long jobs, the drawback is that if the job fails all the job that has been done so far is lost unless you have some smart way to continue where it left, etc. Better to keep the jobs small independently if they are running blocking code or not.

**Comment by BestPractises2GO** [comment]
Thank you for the very fast response. In my certain use case, when I update my avatar in my MongoDB Collection "User" (which would run in the req/res loop), then  I have to update the avatar for all referencing Documents in the Collection "friendship" (which should run in a background task). The job would be automatically long, since the update for hundred of thousands friends would take minutes or hours. Do you have a tip, how you would solve this situation? Many thanks in advance.

**Comment by manast** [comment]
seems like a difficult case to solve reliably. What happens if the user changes avatar several times in a short span of time? Also, why do denormalize the avatar instead of just referencing to a separate collection "avatarUser" for example, where avatars are associated to its users?

**Comment by BestPractises2GO** [comment]
> What happens if the user changes avatar several times in a short span of time?

This is a very good question, I thought if the user updates his avatar several times in a short span of time, I could iterate all waiting Tasks in queue i.e. "active" event and abort all old tasks except the newest which belong to that particular userid. Is this possible?

The reason for duplicating information from the user documents in the friendship documents is to avoid a second query to the users collection or "avatarUser" collection to obtain all the data for displaying a users friend-list. Otherwise I would need to perform multiple queries one after another, which slows down the response time of the application significantly. The alternative MongoDB $lookup left-join operator does not support sharded collections, why I avoid using it. 
 I need to prioritize consistency vs. performance. In this particular case, consistency is not as important. for an update it will take a while until all friendship lists show the new avatar. But this is a performance-uncritical operation which can be done in the background.

What would be your advice? Thanks in advance.

**Comment by BestPractises2GO** [comment]
Solved it! Just use a Map<String, Map<String,Promise<job>> to detect old tasks by a user and remove them if necessary. Your good question mentioned me to think about it. Thanks.

**Comment by BestPractises2GO** [comment]
Solved it! Just use HashMap to detect old tasks by  user and remove them if necessary. Your good question mentioned me to think about it. Thanks.
