### ISSUE TITLE
Plan on parent-child feature

### ISSUE THREAD

**Issue by lakshmanvassar** [OptimalBits/bull#803]
I would like to know the status of parent-child job relationship feature which is announced a while ago. 

I would appreciate if you can provide a tentative deadline.

**Comment by swayam18** [comment]
Are there any on going discussions about how this will be implemented? I'd be happy to contribute if you need more eyes to look at this.

**Comment by milesalex** [comment]
Any update on this?

**Comment by milesalex** [comment]
@swayam18 @lakshmanvassar Any ideas on alternatives that handle this?

**Comment by swayam18** [comment]
@milesalex We've created our own parent-child scheduler on top of this library by leveraging a graph database to store the dependency graph. It is not very robust but it gets the job done. Here is the idea:

1) Every node in the graph stores the bull job definition (data, params etc) and its status
2) Every node that depends on other nodes has a relationship to that node

Here is the logic: 
1) Schedule the root node (i.e. the node with 0 dependencies) via queue.add(...)
2) Listen for completion events using the bull listeners
3) When a job completes, find that job and check nodes that depend on that job
4) For each node that depends on the completed job, check if all of its dependencies have been met. I.e. check every node that it depends on and see if it is done.
5) If the dependencies have been met, schedule that node. Repeat step 2.

It works pretty well, but there are race conditions and what not that make it less robust.

**Comment by roggervalf** [comment]
hi guys, parent-child feature is implemented in bullmq https://docs.bullmq.io/guide/flows
