### ISSUE TITLE
Adding jobs to the queue from a processor is not working as expected.

### ISSUE THREAD

**Issue by alswamy** [OptimalBits/bull#810]
I am having my design like this.

I am using the queue and there are two named processes. My purpose of having queue is to add jobs based on events. And the process can propagate events to the queue again. The problem I see is, the process is getting executed on adding a job, however status is not being updated. I am using the following code to know the status.

```js
 setInterval(function () {
    taskqueue.getJobCounts().then(function (result) {
        logger.info("\rQueue Status: ", result);
        //console.log("\r" + "Queue status: ", result);
    }).catch(function(){
        logger.info("Error in finding out the status of the queue");
    });
}, 10000);
````

Even I tried using Arena(https://github.com/bee-queue/arena) to monitor the queue, it's not getting update the entries.

My two process code looks like below.

A Process
```js
module.exports = function(job){

	logger.info("Starting A worker");
	logger.info("Data for Worker: ", job.data);

        //Do your work here

	//Propogate the events further
	eventController.addEvent("bworker", job.data);
	eventController.addEvent("bworker", job.data);
	eventController.addEvent("bworker", job.data);
	eventController.addEvent("bworker", job.data);
	
	logger.info("Done with A worker");
    } 
} 
```

B Process
```js
module.exports = function(eventdata){

   logger.info("Starting B worker");   
   logger.info("Data for Worker: ", eventdata.data);
   // Do your work here	
   logger.info("Done with B worker");	
}
```

And two more questions:
1. I need to add an a job from another process, Is that the right approach as per the design? What is the recommendation here.
2. Is there any other approach to monitor the queue.

also we have observed that adding jobs from a processor is not working as expected.

Thanks a lot.

**Comment by manast** [comment]
Adding jobs from a processor seems fine to me, as long as you can accept that in some situations the same job can be added twice (for example if the processor fails after adding the job). 
Regarding the status issue, I would need some example code that shows the missing status so that I can take a look into it.

**Comment by alswamy** [comment]
Thanks a lot for the quick reply.

I am posting the repo for you to test the issue.

git clone https://bitbucket.org/alswamy/task-queue
npm install
node app.js

Please use this command to send an event.
curl -d "activitytype=KPI&metric=K00&submetric=achievedValue&cycles
=ALL&uid=59a5735c2f2651e76756f8bf&cid=59c0e56e7d7ab7060afa838b&event=xworker&jobrole=J22" -X POST http://localhost:3000/sendEvent

You can check the status in console.

**Comment by alswamy** [comment]
Please look processor code at xworker.js in processes directory of the project.

**Comment by alswamy** [comment]
When I add jobs outside of the processor code. It is working fine. 

If jobs are being added from the processor code, the behaviour is crazy, adding some huge number of jobs to the queue. 

Not sure, what is going wrong.

**Comment by manast** [comment]
I cannot find that file, maybe you forgot to commit them.

**Comment by alswamy** [comment]
Sorry...my bad..its on branch task-queue-dev

you can pull it master now..I added the code to master as well...

**Comment by alswamy** [comment]
I tried even posting through CURL from the processor. It's not working even. It's strange.

**Comment by alswamy** [comment]
One more input..I tried running npm test on bull repo. This is the message I got.

sandboxed process
(node:1481) TimeoutOverflowWarning: 1.7976931348623157e+308 does not fit into a 32-bit signed integer.
Interval duration was set to 1.

my node version - 9.2.0

**Comment by manast** [comment]
node 9 is not supported. Version 6 or 8 only.

**Comment by alswamy** [comment]
I have checked with node 8.9.0 as well...

**Comment by alswamy** [comment]
Did you get a chance to look at the example code that I sent. Please let me know if you need any more information for running the example code.

**Comment by manast** [comment]
I will take a look at it later during the weekend.

**Comment by alswamy** [comment]
Thanks, Let me whenever you sometime to look at it.

**Comment by manast** [comment]
Yes I tried it. But the repo is too complex, and I do not have time to make it all work to test, etc. Cant you just provide a super minimal test code example, one file with the queue and another with the worker that reproduces the issue?

**Comment by alswamy** [comment]
I removed most of the code https://bitbucket.org/alswamy/test-repo

Please let me know it can reproduce the issues and it can be observed in the console.

**Comment by alswamy** [comment]
Hi @manast , did you get a chance to look at the problem?

**Comment by manast** [comment]
yes, but is it still too complex. I need a test where I can just run ```node test.js``` and the unexpected behaviour arises. Or even better a PR with a failing test case in our current unit tests suite.
