### ISSUE TITLE
Problem with using with typescript builded with webpack

### ISSUE THREAD

**Issue by aliksend** [OptimalBits/bull#811]
Hello

I have a problem using bull with typescript. I build typescript using webpack. 
Bull is working as expected when using with js.
Proof sample located [here](https://github.com/aliksend/bull_webpack_issue).

Hope for your help.
Thanks

**Comment by manast** [comment]
sorry, I have no idea what the error can be, seems related to redis custom commands. But why are you using webpack? you should be fine just using the typescript compiler directly...

**Comment by aliksend** [comment]
I develop a vue application with server-side rendering and for me there is only one way to be sure that client and server parts compiles the same way. Sure, I can build client part with webpack and run server part directly (using ts-node etc) but then I lose all webpack settings such as DefinePlugin, resolve.alias, also there was some problems with importing etc. I played with it some time ago and got one working way - to compile both parts with webpack. And this issue is the first problem because of this.

**Comment by n1ru4l** [comment]
@manast Hot Module Reloading

**Comment by apoorvparijat** [comment]
I encountered the same issue when using `serverless-webpack`. I am attempting to add a job to queue via a lambda in a Serverless framework setup.

The solution mentioned by @n1ru4l works. Hopefully, we can find a way to make it work without this fix.

**Comment by mrmarktyy** [comment]
@n1ru4l solution works for me. Thanks!

**Comment by greysonn** [comment]
@n1ru4l solution also worked for me, thanks.

**Comment by scowalt** [comment]
This is a duplicate of #920 

None of the solutions I saw posted worked for me. However, I was able to get this working by changing the `__dirname` resolution behavior:

```
node: {
    // required for __dirname to properly resolve
    // Also required for `bull` to work, see https://github.com/OptimalBits/bull/issues/811
    __dirname: true,
},
```

[See this for a bit more context](https://webpack.js.org/configuration/node/#node__dirname)

**Comment by skanygin** [comment]
@n1ru4l's solution works only if bundle is near node_modules. I'm configuring flow with tiny docker images and single bundle for my nestjs app in nx workspace. 

So I just put `lua` files at same folder with my `main.js`. This looks like not so cool workaround but it is quick and effitiend in this case.
Here is example:
```
// angular.json


["app.architect.build.options.assets"]: [
  "apps/routing-worker/src/assets",
  {
    "glob": "**/*.lua",
    "input": "node_modules/bull/lib/commands",
    "output": "./"
  }
]

```

You can place everywhere you prefer by changing `output` and using @n1ru4l's solution to replace `__dirname`.

**Comment by danthegoodman1** [comment]
> This is a duplicate of #920
> 
> None of the solutions I saw posted worked for me. However, I was able to get this working by changing the `__dirname` resolution behavior:
> 
> ```
> node: {
>     // required for __dirname to properly resolve
>     // Also required for `bull` to work, see https://github.com/OptimalBits/bull/issues/811
>     __dirname: true,
> },
> ```
> 
> [See this for a bit more context](https://webpack.js.org/configuration/node/#node__dirname)

This also works for bullmq! When using webpack you need this!

**Comment by sibelius** [comment]
anybody got this working with esbuild bundle ?

**Comment by Inambe** [comment]
same issue `Error: No .lua files found!` with next.js 13.

**Comment by sibelius** [comment]
You need to copy .lua files after bundling or just exclude bull from bundling, and install them later on

**Comment by Inambe** [comment]
Next.js doesn't make it easy to play with Webpack config and I just chose another queue lib. Thanks! though.

**Comment by manast** [comment]
Try to upgrade to BullMQ as it handles scripts in a better way: https://github.com/taskforcesh/bullmq

**Comment by Redbeardjunior** [comment]
> Next.js doesn't make it easy to play with Webpack config and I just chose another queue lib. Thanks! though.

did you fix it ?

**Comment by manast** [comment]
@Redbeardjunior which problem do you have? Current version of BullMQ should not have any issues with webpack.

**Comment by sibelius** [comment]
the way to fix bull when bundling is to not bundle it

move it to external and reinstall in the docker

check https://dev.to/woovi/using-webpack-to-slim-your-docker-image-1b1n

**Comment by Redbeardjunior** [comment]
> @Redbeardjunior which problem do you have? Current version of BullMQ should not have any issues with webpack.

Thank you for your reply, I started using BullMQ in my project and its working like a charm now this saved my life for now.

**Comment by Redbeardjunior** [comment]
> e way to fix bull when bundling is to not bundle it

Thank you for your suggestion, I will try this later on !
