### ISSUE TITLE
Cron (repeated) jobs calling at same time.

### ISSUE THREAD

**Issue by charanjeet5ingh** [OptimalBits/bull#813]
```js
import Queue from 'bull';
const tempQueue = new Queue('testing', 'redis://127.0.0.1:6379');
const init = async (name) => {
    tempQueue.process(name, function(job) {
        console.log(job.data);
    });
    tempQueue.add(name, { data: name }, { repeat: { cron: '*/20 * * * * *' }});
}
init('firstjob');
setTimeout(()=>{init('secondJob')}, 10000);
```

As I have the requirement to add jobs dynamically. Both the jobs are calling at exact same 20 sec.

output = 0 sec = firstjob
               20 sec = firstjob , secondjob ... so on

what i am looking for 0 sec = firstjob
                                    10 sec = secondjob
                                    20 sec = firstjob
                                    30 sec = secondjob

**Comment by manast** [comment]
This is as cron expressions work. If you want a job to repeat every 10 seconds, then:
```cron: '*/10 * * * * *' ```
If you want to specify exact second:
```cron: '10,20,30,40 * * * * *' ```
and so on...
You can find examples on valid expressions for this particular cron implementation here: 
https://github.com/harrisiirak/cron-parser/tree/master/test
