### ISSUE TITLE
Can I fire another job after completing one?

### ISSUE THREAD

**Issue by peterpme** [OptimalBits/bull#816]
:wave: AWESOME library!! You are all amazing people!

Perhaps I'm just a noob or perhaps I've been googling the wrong thing (any articles would be appreciated) but I was wondering if its a good practice to fire off another job after completing one.

Here's what I'm doing now:

1. Fire Job A
  - pass `userId`
  - process some info for user
2. On Job Complete A: `queue.on('completed')`
  - check `userId`, if it matches, fire Job B
  - if it doesn't, do nothing
3. Process Job B
  - Get `userId` from job.data
  - update flag on user 

It *seems* like there's nothing wrong with this approach, but I can be totally off!

Also, I would love to be able to open a PR and add this to the patterns if you're all willing to let me!

Thanks,
Peter

**Comment by manast** [comment]
That approach works but it also depends on your requirements. For instance, if you add a job in the ```queue.on('completed')``` you do not have full guarantees that the job B will be added. In order to guarantee it you will need to add the job in the process function of the job A instead.

**Comment by peterpme** [comment]
Hey @manast,

Thanks so much for the reply!

So what you're saying is, instead of separating the functions, I should just handle the additional scenario within Job A.

So if Job A looks like this right now:

```
await doSomething(userId)
```

it should look like this:

```
await doSomething(userId)
await updateUser(userId)
```

Thanks again!

**Comment by manast** [comment]
yes. By doing that you guarantee that the job B is always added if job A completes.

**Comment by peterpme** [comment]
Thank you!
