### ISSUE TITLE
[Question] Failed jobs after maximum retry and specific one time job

### ISSUE THREAD

**Issue by adamsaparudin** [OptimalBits/bull#824]
## Description
- There is a case for me run a function after maximum retry reached. Is there any trigger for this one ? 
- How to run scheduled one time jobs ? like cron job, but only one time.

## Bull version
3.3.5

**Comment by manast** [comment]
When the last retry is reached, you should get the ```failed``` event, so then you can call any function you like from that listener. Regarding one time scheduled jobs, just add a delayed job with the time you wish to delay.

**Comment by adamsaparudin** [comment]
Hi, thanks for you reply.

I already try with simple implementation
```javascript
const testQueue = new Queue('just test queue', redis);
testQueue.process(job => {
  console.log('hitttt')
  return Promise.reject('lalal')
})

testQueue.on('complete', (job, progress) => {
  console.log('completed')
})
testQueue.on('failed', (job, err) => {
  console.log('failed')
  someFunction()
})

testQueue.add(
  {something: 'parameters'},
  {attempts: 5, backoff: { type: 'fixed', delay: 100 }}
)
```

but the result is running `someFunction()` 5 times. What I expect is I wanted it only run once after last retry.

**Comment by tylerjbainbridge** [comment]
I'm curious about this too-

The `failed` event is emitted each on retry, not just the final failure-- I'd like a way to know when the job attempt count reaches the retry limit.

Thanks for the help-- loving bull so far.

**Comment by manast** [comment]
try ```job.attemptsMade < job.opts.attempts```

**Comment by tylerjbainbridge** [comment]
Perfect-- thank you @manast!

**Comment by kakasal** [comment]
someone please explain backoff
