### ISSUE TITLE
Cancel job before process (change state from waiting to failed)

### ISSUE THREAD

**Issue by cristianfd** [OptimalBits/bull#827]
Anyone knowns a way to cancel a job that is waiting to be process? 
I have one _producer_ (or parent) process controlling the child jobs and when one fail its send signal to kill the running process to the jobs that are active and running but I don't know how to change the waiting to failed (or another complete state) from the parent process.
I have the jobId, so I can do queue.getJob(id).then... but after I read almost all the source code I can't figure how can I do this.

**Comment by manast** [comment]
If it is in a waiting state (even delayed), you can just remove it: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#jobremove

**Comment by cristianfd** [comment]
Oh dammit, that's right.
