### ISSUE TITLE
Named Process Sent to Wrong Processor

### ISSUE THREAD

**Issue by PrestonR** [OptimalBits/bull#830]
## Description
Upon app boot-up, the following named processes, process, on the correct processors (i.e. they are routed to the correct process based on process name). However, because they are repeatable, all subsequent attempts are attempting to **process both jobs on the last auditor path defined in the sequence**

## Test code to reproduce
```
const queue = {
   auditor: new Queue('auditor', opts)
}

queue.auditor.add( 'auditor1', { repeat: { cron: '*/2 * * * *' } } );
queue.auditor.add( 'auditor2', { repeat: { cron: '* * * * *' } } );

queue.auditor.process( 'auditor1', 1, AUDITOR_PATH_1 );
queue.auditor.process( 'auditor2', 1, AUDITOR_PATH_2 );
```

AUDITOR_PATH_1 ends up getting ignored, and both auditor1 and auditor2 process on AUDITOR_PATH_2. Needless to say, AUDITOR_PATH_2 fails for auditor1 because neither processsor's code supports the other.

Are you able to confirm and reproduce this? The only work around I can think of is to just put each of them on separate queues.

## Bull version
3.3.7

## Additional information
Node 8 LTS

**Comment by PrestonR** [comment]
Wrapping that file with:

```
queue.auditor.process ( 'job1', 1, ( job ) => {
    return Promise.resolve();   
} );
```

Seems to be a decent work-around.

**Comment by manast** [comment]
yes but you loose the isolation of your process function. I have already identified the bug, a fix is in the works.

**Comment by PrestonR** [comment]
Great thanks!
