### ISSUE TITLE
Question: Configuring clustering for multiple queues

### ISSUE THREAD

**Issue by dhruska** [OptimalBits/bull#831]
Hi there,

I'm working on an application that has five Bull queues. Each queue (and corresponding process) lives in its own file. I'm following the [clustering example](https://github.com/OptimalBits/bull/blob/master/examples/cluster-queue.js), and I totally understand how I can set up clustering for one queue, but how can I do this for five queues? Do I just do this in each file, or will forking new processes for each queue cause problems?

Also, I was taking a look at the [separate processes section](https://github.com/OptimalBits/bull#separate-processes), and I'm following the pattern shown there already of having the process live in a separate file. Does this in itself enable clustering also, or do I need to explicitly run `cluster.fork()` as shown in the clustering example?

Thanks for your time - I'd be more than happy to update the documentation with another example or two or more information, once I completely understand!

**Comment by manast** [comment]
The easiest for your case is to use separate processes. Every process will be run in its own sandboxed process, you specify how many concurrent jobs you want to process when specifying the process function. This achieves a similar result as clustering but with some advantages, for one being much simpler to setup.
