### ISSUE TITLE
Distribution running: Can Bull run as a cluster with multiple server?

### ISSUE THREAD

**Issue by Tin-Nguyen** [OptimalBits/bull#836]
As I know, Bull is using Redis as its storage. I'm looking for a way to test with multiple server running for Bull queue, is it possible to run Bull queue with multiple server that we can run multiple jobs of the same queue in parallel? Thanks

**Comment by manast** [comment]
you can start as many workers as you want, either in the same machine using several CPU cores or in different machines.

**Comment by Tin-Nguyen** [comment]
Are you mentioning the cluster support at https://github.com/OptimalBits/bull#cluster-support?

**Comment by manast** [comment]
You do not need to use cluster, just run the workers in separate processes: https://github.com/OptimalBits/bull#separate-processes

**Comment by Tin-Nguyen** [comment]
Thanks.

**Comment by matija2209** [comment]
> you can start as many workers as you want, either in the same machine using several CPU cores or in different machines.

Do you have any documentations to refer to when running on multiple machines? Thanks.

**Comment by imanhpr** [comment]
> > you can start as many workers as you want, either in the same machine using several CPU cores or in different machines.
> 
> Do you have any documentations to refer to when running on multiple machines? Thanks.

I'm looking for the answer to this question but I couldn't find anything.

**Comment by manast** [comment]
@imanhpr you just run more workers, I am not sure what else can be said about this...
Btw, you probably should use BullMQ instead of Bull if you are starting to use it: https://docs.bullmq.io
