### ISSUE TITLE
localized queues - question

### ISSUE THREAD

**Issue by afrozl** [OptimalBits/bull#837]
I have a subset of each type of job that needs to be executed on specific nodes. My thinking was that each node would run an extra  processor for each type of job that would be named  by hostname, so basically

```
queue.process(runJob)
queue.add({user:123})
queue.process('hostname', runJob)
```
This approach seems to be flawed since it appears that  if a worker/processor for a host is not instantiated prior to a job being added, it immediately gets errored out by any worker on that queue:

```
Error: Missing process handler for job type hostname
    at Error (native)
    at Queue.processJob (/apps/node_modules/bull/lib/queue.js:908:25)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/apps/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/apps/node_modules/bluebird/js/release/promise.js:512:31)
```
Is this the expected behavior? My assumption was that a named processor acted like a virtual queue. Which is to say that any jobs added to that namespaced queue would remain untouched until a suitable worker came online?

**Comment by manast** [comment]
The named queues act more as a switch case, so you need to have defined processors for all the names. In your case the easiest would probably to have a queue per hostname, but maybe it does not fullfil your requirements, let me know.

**Comment by afrozl** [comment]
Additional queues for each host would be fine. I just thought the named queues approach was more elegant.  

I am starting to think that perhaps, for my expected usage patterns, it makes to have a 'scheduler' queue. This queue would accept all incoming requests from clients and based on arguments supplied would route to the appropriate processor queue. It introduces an extra step, and thus slightly more latency,  but allows me to centralize job parameters such as timeouts and retries while also giving me the flexibility of pre-processing the job submissions. This will let me do things like discard a job if it has already run in the last x interval and so on. Any thoughts on this approach?

**Comment by manast** [comment]
seems like a good approach to me.
