### ISSUE TITLE
killing jobs running in separate processes on timeout

### ISSUE THREAD

**Issue by afrozl** [OptimalBits/bull#838]
Is there a mechanism for explicitly killing spawned child processes that are 'stuck/hung'? Lets say we set a timeout of 60 seconds on a job that typically finishes in 10 seconds, is there a way to get the pid of the process and kill it after the timeout is exceeded? We have jobs that make REST calls to remote services and these will occasionally hang at this stage if the remote service does not respond. Does this need to be handled via timers within the job or is there a way to do this globally?

**Comment by afrozl** [comment]
Just to clarify - the timeout functionally works as designed - i.e. jobs are failed and retried ( if attempts remain ) after the timeout expires - unfortunately the 'hung' child process remains as a zombie process so I expect that, over time, these will accumulate unless restarted.

**Comment by manast** [comment]
@afrozl this is actually a duplicate. I hope me or somebody else has a slot of time to implement a PR, it should be pretty straightforward: https://github.com/OptimalBits/bull/issues/718
