### ISSUE TITLE
Bull 2.x Redis DB bug

### ISSUE THREAD

**Issue by timcosta** [OptimalBits/bull#839]
https://github.com/OptimalBits/bull/blob/94421ac8e8be62467a66abbafab05239e4b55384/lib/queue.js#L77

One of these vars in the _or_ should be a lowercase `db` right? That would match the ioredis options more closely according to https://github.com/luin/ioredis#connect-to-redis

**Comment by manast** [comment]
won't be fixed since 2.x is not maintained anymore.
