### ISSUE TITLE
Why aren't completed jobs removed by default?

### ISSUE THREAD

**Issue by danprince** [OptimalBits/bull#840]
Just interested to know the design decisions behind this. We just started to notice OOM errors coming in from the Redis commands Bull has been running, then checked the Redis key usage to see that it has been growing continuously.

![image](https://user-images.githubusercontent.com/1266011/34895883-809bb6b2-f7df-11e7-9cce-1e0021fc41ec.png)

Running [`Queue#clean`](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueclean) manually got rid of the errors immediately and now we're looking into how we prevent this from happening again in the future.

Our options seem to be either running a scheduled cleanup, or adding `removeOnComplete: true` to the `Queue#add` options for each of our queues.

What are the downsides of removing the jobs when completed and which strategy would you recommend for making sure we don't continue to run out of memory on our cache cluster?

Is there any way to make this a global setting for a given queue, rather than having to remember it each time `Queue#add` is called?

**Comment by manast** [comment]
The initial versions of bull did not have the ```removeOnComplete``` option, so it became natural to have it false by default. There is no global setting for it, but it seems a reasonable request, so you can file it as an issue and it will be added in next versions of bull.

**Comment by manast** [comment]
The downside of removing the jobs is that you loose some potential useful information such as the time the job took to complete, time at queue, etc. Ideally we would like to keep the N latest completed jobs, but the feature has not got proper attention yet.

**Comment by danprince** [comment]
Thanks for the quick responses! Filed a feature request in #842.
