### ISSUE TITLE
Getting the last completed job

### ISSUE THREAD

**Issue by faustbrian** [OptimalBits/bull#844]
Been going through the README and code trying to figure out how to retrieve the last completed job from a queue.

```js
const Queue = require('bull')

const videoQueue = new Queue('video transcoding', 'redis://127.0.0.1:6379');

console.log(videoQueue.getLastCompletedJob());
```

Is there some way to achieve this with Bull?

**Comment by manast** [comment]
This would probably do what you want:
```
videoQueue.on('global:completed', function(jobId){
  videoQueue.getJob(jobId).then(function(job){
    // last completed job is in job.
  }
}
```

**Comment by manast** [comment]
You have also methods for getting all the completed jobs so far, etc:
https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queuegetcompleted

**Comment by faustbrian** [comment]
Thanks, that `global:completed` was what I needed.
