### ISSUE TITLE
queue.pause() doesn't wait current jobs being processed

### ISSUE THREAD

**Issue by mahnunchik** [OptimalBits/bull#847]
## Description

`queue.pause()` doesn't wait current jobs being processed.

## Test code to reproduce

```js
process.on('SIGINT', async () => {
  await queue.pause();
  process.exit(0);
})
```

But there are active jobs in the queue.

## Bull version

`3.3.8`

**Comment by apellizzn** [comment]
Facing the same issue, it happens when i try to re-init a queue

**Comment by manast** [comment]
pause does not pause active jobs, that is working as designed. You can still wait for the active jobs by polling or listening to the completed/failed events until the active queue is completely empty.

**Comment by gabegorelick** [comment]
I don't think this is the case anymore. `queue.pause` calls `whenCurrentJobsFinished` by default: https://github.com/OptimalBits/bull/blob/146bc8ed4341ec3e54b299c22e60dc3267d8b6d1/lib/queue.js#L769-L789
