### ISSUE TITLE
Jobs stalling immediately

### ISSUE THREAD

**Issue by holm** [OptimalBits/bull#850]
We have had a few rare cases of jobs immediately stalling upon start. Originallywe wrote it off as a fluke that was unlikely to happen again. However we have now seen it happen a handful of times, so there must be something about it.

We log all the events in our logs, and this is what it looks like from the logging:

```
Jan 29 13:02:23 app/worker.2:  [0] warn: low: Job session.updateLastUsedAt[3071971-0] stalled - it will be restarted 
Jan 29 13:02:23 app/worker.2:  [0] info: low: Job session.updateLastUsedAt[3071971-0] starting 
Jan 29 13:02:23 app/worker.2:  [0] info: low: Job session.updateLastUsedAt[3071971-0] completed 
Jan 29 13:02:23 app/worker.2:  [0] info: low: Job undefined.undefined[3071971-0] starting 
Jan 29 13:02:23 app/worker.2:  [0][Err] Job undefined.undefined[3071971-1] failed 
Jan 29 13:02:23 app/worker.2:  [0] warn: low: Job undefined.undefined[3071971-1] failed 
```

The reason for the "undefined" is that the payload for the job is now empty. We remove jobs on completion, and it seems that the jobs is "readded" by the un-stall processing, but it now longer have the majority of the meta-data.

In other cases the job will not have finished before it is started again by the un-stall processing, and it looks like this:

```
Jan 29 13:02:23 app/worker.2:  [0] warn: generic: Job event.emit[3821941-0] stalled - it will be restarted 
Jan 29 13:02:23 app/worker.2:  [0] info: generic: Job event.emit[3821941-0] starting 
Jan 29 13:02:23 app/worker.2:  [0] info: generic: Job event.emit[3821941-0] starting 
Jan 29 13:02:23 app/worker.2:  [0] info: generic: Job event.emit[3821941-0] completed 
Jan 29 13:02:23 app/worker.2:  [0][Err] Error: Missing lock for job 3821941 failed 
```

Looking at the other jobs processed on that specific nodejs process, I can see in at least the latest case, another job was stalling the event loop. This seems to make sense for the errors caused here, and the the main solution to this is to ensure we either don't block the event loop that long or we have a stall timeout that is long enough.

I mostly wanted to create this issue in hope there was something that could be done to handle the side-effects of this problem, since it is hard to figure out what is the reason from the empty payload and locks are.

**Comment by manast** [comment]
It is really strange that a job that has just started gets stalled immediately, the code logic should not allow that to happen, but maybe there is some edge case that we have overlooked.
The best workaround right now is to use external processos, in that way it is ok if the job blocks the event loop, the worker code will alway be able to reset the potential stalled jobs in time:
https://github.com/OptimalBits/bull#separate-processes

**Comment by manast** [comment]
I will close this issue now for lack of activity, reopen if necessary.
