### ISSUE TITLE
Allow to create a processor for a specific job name

### ISSUE THREAD

**Issue by mahnunchik** [OptimalBits/bull#858]
## Description

Allow to create a processor in separate file (or server) for a specific job name in single queue.

## Test code to reproduce

```js
// producer.js

queue.add('foo', {});
queue.add('bar', {});
```

```js
// worker-both.js
queue.process('foo', fooFunc)
queue.process('bar', barFunc)
```

```js
// worker-only-foo.js
queue.process('foo', fooFunc)
```
The error `Missing process handler for job type` is raised in the ` worker-only-foo.js` file.

## Bull version

3.3.8

## Additional information

I don't want to launch jobs with name `bar` on some servers but I'd like to launch jobs with both names on some servers.

**Comment by manast** [comment]
Unfortunately that is not possible to achieve with current design, the workaround is to define 2 queues instead of only one.

**Comment by mahnunchik** [comment]
it is not good

**Comment by mahnunchik** [comment]
any solution except multiple queues?

**Comment by mahnunchik** [comment]
My task is:

```js
// producer.js
queue.add('foo', {});
queue.add('bar', {});
```

Usual worker.
```js
// worker-1.js
queue.process('*', fooFunc)
```

Worker to help with `foo` tasks.
```js
// worker-2.js
queue.process('foo', fooFunc)
```

**Comment by manast** [comment]
that will not work unfortunately with current queue design :/

**Comment by zebkailash** [comment]
Is this supported @manast.
