### ISSUE TITLE
Class instance as data added to queue is simplified before process it

### ISSUE THREAD

**Issue by GuillermoPena** [OptimalBits/bull#859]
## Description

I have a class like this:

class Message {
  constructor(text) { this.text = text }
  toUpper() { return this.text.toUpperCase() }
  toLower() { return this.text.toLowerCase() }
}

I have a queue with this function as proccess:

display(data) {
    console.log('Message: ' + data.message)
    console.log('To UpperCase: ' + data.message.getUpper() )
    console.log('To LowerCase: ' + data.message.getLower() )
}

I create an instance of class Message and add it to a queue

let message = new Message('Hola')
queue.add(message)

If I check message before to add to queue I can see text property and methods.
If I check message inside of display function when queue is running message, I can see only property text but not methods and job fails because queue doesn't find getUpper method.

Why does queue simplify data removing methods from it?

## Bull version 3.3.9

Excuse me for my english and thanks

**Comment by manast** [comment]
Because data is supposed to be data not a class. Data is serialized, etc. There is no way we can keep the methods of the class.
