### ISSUE TITLE
Question: Concurrency for large queues - best practices

### ISSUE THREAD

**Issue by gbhrdt** [OptimalBits/bull#863]
I have a quick question about performance: Is it better to spawn multiple workers, each calling queue.process or is it better to increase the `concurrency` of the `queue.process` method?
This is important to us, because we have very large queues, sometimes 200k jobs need to be processed in seconds.

I also saw the AdvancedSettings `lockDuration` and `stalledInterval`. Can this improve performance in any way?
Also, we noticed that jobs are processed twice in a very rare case. Can this be improved?

Any help would be very appreciated!

**Comment by manast** [comment]
It depends on several factors actually. With bull you can scale vertically (by using separate workers in the same machine (or sandboxed processors which is the recommended way to scale vertically), or you an scale horizontally by launching several workers in different machines. Currently I do not see any advantage performance wise by using several workers in the same machine, it is just better and more reliable to use sandboxed processors. 

Then you can ask yourself what kind of processing are you performing, is it CPU intensive or IO intensive? If it is CPU intensive it makes more sense to have many concurrent workers, but if it is CPU intensive you may just limit the concurrency to the amount of cores in your hardware. Also, are they low or high latency? for very low latency you may want to use standard processors, whereas for higher latency (and for most cases really) it is better to use sandboxed processors, they run in different processes, so besides being more robust also uses the hardware more efficiently, specially in the multi core case.

**Comment by manast** [comment]
Regarding jobs being processed twice, this may only happen if a job get stalled and reprocessed, while the original processor actually was not stalled and kept working. To mitigate this problem you should use sandboxed processors because they cannot stall the worker.

**Comment by gbhrdt** [comment]
@manast Thanks for your quick reply, didn't have the time to respond. This helped me very well, we will implement separate workers to improve performance now.
