### ISSUE TITLE
Dynamically create the job queues

### ISSUE THREAD

**Issue by Tin-Nguyen** [OptimalBits/bull#867]
I have a big number of jobs in a queue, now I'm about to make the process to create the queues automatically for each segmentation of data (e.g. by userId). I'm wondering how I can make the process work on multiple servers? For example, we have 5 servers running. When server A receives the request and create a new queue `QueueA`, we have to make other servers create `QueueA` as well, so the job of `QueueA` can be proceeded by all servers. 

In additional, if we have `Auto-Scaling` on my service, AWS can launch a new instance when we have in the high demand time. Does `Bull` provide a way to load the current queues from Redis?

Thanks in advanced.

**Comment by manast** [comment]
I think I understand your use case. Currently there is no built-in mechanism in Bull to notify about new queue creations. A relative simple workaround would be to use redis pubsub to notify your workers to start listening to new queues. You could also have some kind of watchdog that closes queues that have been "drained" for a long time, to save resources.

**Comment by Tin-Nguyen** [comment]
Thanks. I got your idea

**Comment by willymilimo** [comment]
@Tin-Nguyen I am interested to learn how you implemented or solved this. I also happen to need dynamically created queues with bull & redis.

**Comment by KumarAbhirup** [comment]
@Tin-Nguyen It would be really helpful if I get to know how you achieved it!

**Comment by ahmad-punch** [comment]
Hi guys any update on this thread?

Also:
From this github thread: https://github.com/OptimalBits/bull#queues-performance

Queues performance
Queues are cheap, so if you need many of them just create new ones with different names:
var userJohn = new Queue('john');
var userLisa = new Queue('lisa')

This is doable but I reckon this is not dynamic so to say not in happening at runtime.

**Comment by samirsayyad** [comment]
Hi guys, have look here:
https://github.com/samirsayyad/bullDynamicQueue

**Comment by ahmad-punch** [comment]
> Hi guys, have look here:
> https://github.com/samirsayyad/bullDynamicQueue

Any documentation / explanation would be nice.

**Comment by samirsayyad** [comment]
@ahmad-punch 
I updated the readme file, hope to be useful.
https://github.com/samirsayyad/bullDynamicQueue/blob/main/README.md

**Comment by manast** [comment]
> Hi guys any update on this thread?
> 
> Also:
> From this github thread: https://github.com/OptimalBits/bull#queues-performance
> 
> Queues performance
> Queues are cheap, so if you need many of them just create new ones with different names:
> var userJohn = new Queue('john');
> var userLisa = new Queue('lisa')
> 
> This is doable but I reckon this is not dynamic so to say not in happening at runtime.

It depends on what you mean with runtime. The only time consuming part is the connection to the redis database. However you can reuse connections (check bull documentation) to get rid of that overhead.
