### ISSUE TITLE
Bull creates "stalled" SET even when running everything in separate processes

### ISSUE THREAD

**Issue by denizdogan** [OptimalBits/bull#872]
## Description

Sometimes in my Redis GUI application I catch Bull creating a SET named "stalled" with the IDs of all of my long-running processes in it, even though I run all of my long-running processing procedures in separate processes. Is this normal? I would expect it to never create that entry when running the procedures in separate processes.

## Test code to reproduce

N/A

## Bull version

3.3.10

**Comment by manast** [comment]
The stalled set is just a set of potential stalled jobs. When the workers work normally they will clean themselves up from this set. When using separate processes the workers will normally always succeed in cleaning this set, so nothing to worry about.
