### ISSUE TITLE
Error: Cannot define the same handler twice <EVENT NAME>

### ISSUE THREAD

**Issue by a-samad** [OptimalBits/bull#874]
## Description
I have created a single queue on server startup and add multiple jobs (same job name) in it on every api request, but it gives an error when I process the job.

## Bull version
V3

## Additional information
Stack Trace:
at Queue.setHandler  /node_modules/bull/lib/queue.js:580:11
at Queue.process       /node_modules/bull/lib/queue.js:556:8

**Comment by manast** [comment]
Can you please reproducible code for this?

**Comment by manast** [comment]
Closing for lack of reproducible code.
