### ISSUE TITLE
ERR Error running script (call to f_...): @user_script:30: ERR invalid expire time in set

### ISSUE THREAD

**Issue by denizdogan** [OptimalBits/bull#875]
## Description

Pretty-printed error:

```
{
  "name": "ReplyError",
  "message":
    "ERR Error running script (call to f_d4d1d1b62afa6d576d81cfbecc482ad7e516d172): @user_script:30: ERR invalid expire time in set ",
  "command": {
    "name": "evalsha",
    "args": [
      "d4d1d1b62afa6d576d81cfbecc482ad7e516d172",
      "7",
      "bull:deniz:stalled",
      "bull:deniz:wait",
      "bull:deniz:active",
      "bull:deniz:failed",
      "bull:deniz:stalled-check",
      "bull:deniz:meta-paused",
      "bull:deniz:paused",
      "1",
      "bull:deniz:",
      "1519203661760",
      "0"
    ]
  }
}
```

## Test code to reproduce

```
const queue = new Queue('deniz', process.env.REDIS_URL, {
  settings: {
    stalledInterval: 0
  }
})
```

## Bull version

3.3.10

## Additional information

This came seemingly out of nowhere and happens as soon as I start my application.

**Comment by manast** [comment]
You cannot use stalledInterval 0.  Btw, it is not recommended to modify the internal settings of the queue. It is only in very particular cases that it makes sense to do it. What are you tying to achieve?

**Comment by manast** [comment]
ok. Then it is a bug :)

**Comment by manast** [comment]
I tried to reproduce this issue without success. Furthermore I doubled checked the code and it is indeed checking that stalledInterval must be larger than zero:
https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L909-L917

**Comment by denizdogan** [comment]
Ok, I will see if I can reproduce it again in the coming week, otherwise we can probably just close this :)

**Comment by ancmikesmullin** [comment]
FYI this error happened to me today, as well. I tried setting `0` for the first time, and this was the result. It was 100% reproduceable for me.
I worked around it by setting my `stalledInterval:` to a ridiculously high number (one year, in milliseconds).
It must be a bug. You should update the docs to stop recommending `0` as a valid value. I am on `"bull": "^3.10.0"`.

**Comment by Gappa88** [comment]
I get the same error:
```
{
  "stack": "ReplyError: ERR Error running script (call to f_d4d1d1b62afa6d576d81cfbecc482ad7e516d172): @user_script:30: ERR invalid expire time in set 
    at Object.moveUnlockedJobsToWait (/path/to/script/node_modules/bull/lib/scripts.js:380:25)
    at Queue.moveUnlockedJobsToWait (/path/to/script/node_modules/bull/lib/queue.js:862:6)
    at isReady.then (/path/to/script/node_modules/bull/lib/queue.js:789:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)",
  "message": "ERR Error running script (call to f_d4d1d1b62afa6d576d81cfbecc482ad7e516d172): @user_script:30: ERR invalid expire time in set ",
  "command": {}
}


```

I don't event need to create a producer script to recreate the error message, I have just run the following code:

```

const Bull = require('bull');
const queue = new Bull("html_pusher", {
  settings: {
    stalledInterval: 0
  },
  redis:
    { "port": 6379, "host": "10.8.0.12", "db": 3, "showFriendlyErrorStack": true, "password": xxx}
});

queue.process(1, (job, done) => {
  console.log(process.pid + ` master eseguo ${job.id} `, new Date());
  setTimeout(done, 3000);
});

queue.on('error', (err) => {
  console.log(process.pid + ` master error ${err.message}`)
});

queue.on('failed', function (job, err) {
  console.log(process.pid + ` master failed ${job.id} ${err.message}`)
});

queue.on('stalled', function (job) {
  console.log(process.pid + ` master stalled ${job.id}`)
});

queue.on('completed', async (job, result) => {
  console.log(process.pid + ` master completed ${job.id}`)
});
```



bull version : 3.10.0

**Comment by dave7280** [comment]
Same problem...

ERROR
{ ReplyError: ERR Error running script (call to f_d4d1d1b62afa6d576d81cfbecc482ad7e516d172): @user_script:80: user_script:80: too many results to unpack 
    at parseError (/root/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/root/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14)
  command: 
   { name: 'evalsha',
     args: 
      [ 'd4d1d1b62afa6d576d81cfbecc482ad7e516d172',
        '7',
        'bull:docheap:stalled',
        'bull:docheap:wait',
        'bull:docheap:active',
        'bull:docheap:failed',
        'bull:docheap:stalled-check',
        'bull:docheap:meta-paused',
        'bull:docheap:paused',
        '1',
        'bull:docheap:',
        '1563758306417',
        '30000' ] } }

**Comment by gmcnaught** [comment]
We've seen this in a few environments - but only queues with a limiter applied.

**Comment by manast** [comment]
@gmcnaught seems like there is an issue when there are a lot of rate limited jobs, will take a look.

**Comment by Robokishan** [comment]
also facing same issue prod server gone down. i have migrated queues to agendajs because of this. love to hear back
