### ISSUE TITLE
Easier way to get all jobs of all statuses

### ISSUE THREAD

**Issue by denizdogan** [OptimalBits/bull#876]
## Description

I'm looking to list all jobs of all statuses. The only way that I've found is to use Queue#getActive, Queue#getWaiting, etc. and then concatenate the return values of each of those calls. Is there a simpler way than this? If not, it would be really useful.

## Test code to reproduce

N/A

## Bull version

3.3.10

**Comment by ferronrsmith** [comment]
You could use `getJobs`

```javascript
Queue#getJobs(types);


Queue#getJobs(['waiting', 'active', 'completed', 'failed', 'delayed']);
```

**Comment by gaetansenn** [comment]
Why not handle a param object for that and if types is not present returning all jobs from all status ?
