### ISSUE TITLE
New queue created every time repeatable job runs

### ISSUE THREAD

**Issue by tigarcia** [OptimalBits/bull#878]
## Description
I may be misunderstanding things, but it appears that a new queue is created each time a repeatable job is run, and the queues never gets removed.  If you run the code below, then look at the keys in redis, each time the repeatable job runs, a new key is added.  The key looks like this: `bull:myqueue:repeat:19fddaffd14440e22f8d54b99846c822:1519770840000`.  Even after the job is complete, the key is never removed from redis. 

## Test code to reproduce

```
const Queue = require('bull');
const express = require('express');
const app = express();

function start() {
  const pushMessageQueue = Queue(
    'myqueue',
    {
      redis: {
        host: '127.0.0.1',
        port: 6379
      }
    }
  );

  pushMessageQueue.process(function(job, done) {
    console.log("Processing job", job);
    done();
  });

  pushMessageQueue.add({}, {
    jobId: 'shouldbecreatedonlyonce',
    repeat: { cron: '*/2 * * * *'}
  });
}

start();

app.listen(3000, function() {
  console.log("listening on port 3000");
});
```

## Bull version
3.3.10

**Comment by manast** [comment]
That is not a queue, it is the id of a job. If you do not want to keep them just use the ```removeOnComplete```option: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd

**Comment by tigarcia** [comment]
Got it, thanks.  So for clarity, on every completed job, a new redis key is created and never goes away unless you have  `removeOnComplete` set to true?
