### ISSUE TITLE
Why Redis 2.8.18 required?

### ISSUE THREAD

**Issue by lchenay** [OptimalBits/bull#88]
It seems to work very well with 2.8.9.

**Comment by manast** [comment]
I am not sure which is the minimum version required, but the old 2.6.12 had a bug that made pause not work, namely this one:
https://github.com/antirez/redis/issues/1668

**Comment by albertjan** [comment]
https://github.com/antirez/redis/compare/987a47b8235f6b7f38b5d9d0b5b36b7b1447f3f4...b0f3922383c6af525db6fb8a1dae6f1457602640

In this comparison you can see 2.8.11 contains the fix for that bug I suggest we lower the redis version to 2.8.17 because that's the latest version available on windows.

**Comment by manast** [comment]
ok, in that case why not just lowering to 2.8.11 as minimum requirement?

**Comment by albertjan** [comment]
Thats fine with me too.
