### ISSUE TITLE
Question: reusing Redis bclient

### ISSUE THREAD

**Issue by yulianovdey** [OptimalBits/bull#880]
Hello!

In [PATTERNS.md](https://github.com/OptimalBits/bull/blob/master/PATTERNS.md#reusing-redis-connections) it says that bull requires 3 connections, and lists two types - `client` and ~`server`~ `subscriber`. I noticed that there's also a `bclient` type that gets passed to `createClient`. Can this connection be reused as well, or is that not advised?

Thanks in advance!

**Comment by ritter** [comment]
From my experience, `bclient` was not shareable. Bull degraded terribly when I tried to share that redis connection.

**Comment by yulianovdey** [comment]
@ritter Good to know, thanks. Also you're right; I definitely meant `subscriber`.

**Comment by manast** [comment]
bclient cannot be shared because it is the client used for blocking calls, so if one instance for instance blocks it waiting for jobs to arrive to the queue, all the other instance sharing it will stall.

**Comment by yulianovdey** [comment]
@manast Makes sense, thanks for the super fast reply!

**Comment by ritter** [comment]
In regards to sharing redis connections, we are sharing `client` connections, and `subscriber` with other subscribers, but every `bclient` gets its own connection.

**Comment by joshuapaling** [comment]
Bit of extra info for future readers: the relevant source is at https://github.com/OptimalBits/bull/blob/develop/lib/queue.js#L1098

```
    return this.bclient
      .brpoplpush(this.keys.wait, this.keys.active, this.settings.drainDelay)
```

When a queue is empty, that queue opens a blocking connection to redis to wait for the next item to be added to the queue. That connection is then kept around as "the blocking connection to use next time this same queue is empty". Hence the need for one blocking connection per queue.

I've opened up a PR to make this more clear in the example code for re-using connections: https://github.com/OptimalBits/bull/pull/1714
