### ISSUE TITLE
Ignore .then handler during process method call

### ISSUE THREAD

**Issue by ks-s-a** [OptimalBits/bull#882]
## Description
I tried to add process handler and add .then call to indicate complete of processor adding.

## Test code to reproduce
```
const Queue = require('bull')
const q = new Queue('test')
q.process('first', () => console.log('processed')).then(() => {
  console.log('here!')
})
q.add('second', {})
```

## Bull version
bull@3.3.10

## Additional information
NodeJS v8.9.4

**Comment by manast** [comment]
the returned promise from process is going to be deprecated in next version. For listening to completed or failed jobs please use the events.

**Comment by ks-s-a** [comment]
@manast ok. I'v still not understood the point about process method. I would like to catch a moment when I successfully attached a handler for the task.

> For listening to completed or failed jobs please use the events.
I can't find any events, which could be convenient to use as a signal for the task handlers attaching.
