### ISSUE TITLE
Large amount of jobs kills redis

### ISSUE THREAD

**Issue by Sicria** [OptimalBits/bull#884]
## Description
I have a job which runs every 5 mins which also creates ~1500 jobs to be processed at 5 concurrency. After around 24 hours it seems that redis crashes with the following error.

``
"ReplyError: ERR Error running script (call to f_53e5e8e119d11dc8d600a89bfe21d0bcc8e76d02): @user_script:38: @user_script: 38: -MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.   \\n    at JavascriptRedisParser.returnError (/opt/node_modules/ioredis/lib/redis/parser.js:24:25)\\n    at JavascriptRedisParser.execute (/opt/node_modules/redis-parser/lib/parser.js:572:12)\\n    at Socket.<anonymous> (/opt/node_modules/ioredis/lib/redis/event_handler.js:107:22)\\n    at emitOne (events.js:115:13)\\n    at Socket.emit (events.js:210:7)\\n    at addChunk (_stream_readable.js:266:12)\\n    at readableAddChunk (_stream_readable.js:253:11)\\n    at Socket.Readable.push (_stream_readable.js:211:10)\\n    at TCP.onread (net.js:585:20)\"]
``

This occurs for each job that is queued then those jobs turn into stalled jobs.

The code is nothing special, just what's in the examples really.

**Comment by manast** [comment]
So it seems you have some local problem with disk storage: ```-MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk.```
This is hardly a bull related issue.

**Comment by Sicria** [comment]
This issue only occurred after a change to a task which was large and stalled sometimes but then was broken out into smaller jobs which creates 1500 seperate jobs. I believe the issue might be that the jobs are completed and never cleaned up, which causes Redis to fail. This only seems to be an issue after a long period of time where the jobs would be 500,000-1,000,000 runs.

Also I don't have any external scripts/commands being run on Redis so I'm unsure what the ``ERR Error running script (call to f_53e5e8e119d11dc8d600a89bfe21d0bcc8e76d02): @user_script:38: @user_script:`` part is referring to.

**Comment by manast** [comment]
still, the error is claiming that the RDB snapshot could not be persisted on disk, either there is not enough space in the disk  (https://stackoverflow.com/questions/19581059/misconf-redis-is-configured-to-save-rdb-snapshots). So you have to either guarantee that there is enough space in disk, or you need to clean jobs after completion, there are many issues already tackling that question.
