### ISSUE TITLE
Share queue between processes

### ISSUE THREAD

**Issue by Nemmo** [OptimalBits/bull#888]
Hi folks!

Can I use it like mutex? For example, run 3 processes with one shared queue having concurrency of 5 jobs in time?

**Comment by Nemmo** [comment]
Anybody knows?

**Comment by manast** [comment]
I don't think the question is clear enough, what do you mean with mutex? can you provide examples?

**Comment by Nemmo** [comment]
I have already provided an example. 

> For example, run 3 processes with one shared queue having concurrency of 5 jobs in time?

If we have a job that fetches a data from the remote resource and 3 node processes on different servers/containers. Will it work if I want limit total concurrency with 5 running jobs at a time?

**Comment by manast** [comment]
The concurrency parameter is per process function, not global.

**Comment by Nemmo** [comment]
Ok, got it. But how can I reach this? Could you help or just give a hint?

**Comment by manast** [comment]
No because I do not understand your issue. Concurrency is explained in the documentation, I do not know what you want to achieve besides what is already documented.

**Comment by Nemmo** [comment]
I just want a global concurrency between N node processes

**Comment by manast** [comment]
So if you want a global concurrency of M, just start N processes with concurrency M / N.

**Comment by Nemmo** [comment]
And what if I have N = 2 and M = 5?

**Comment by manast** [comment]
one process with concurrency 3 and another with 2. I will close this issue now, for more questions please use the gitter channel.
