### ISSUE TITLE
SyntaxError: Unexpected token u

### ISSUE THREAD

**Issue by lchenay** [OptimalBits/bull#90]
```
SyntaxError: Unexpected token u
at Object.parse (native line 0 col 0)
at Function.Job.fromData (/app/node_modules/bull/lib/job.js line 220 col 40)
var job = new Job(queue, jobId, JSON.parse(data.data), JSON.parse(data.opts));
at <unknown> (/app/node_modules/bull/lib/job.js line 36 col 18)
return Job.fromData(queue, +jobId, jobData);
at tryCatch1 (/app/node_modules/bull/node_modules/bluebird/js/main/util.js line 45 col 21)
try { return fn.call(receiver, arg); }
at Promise$_callHandler [as _callHandler] (/app/node_modules/bull/node_modules/bluebird/js/main/promise.js line 660 col 13)
x = tryCatch1(handler, receiver, value);
at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/app/node_modules/bull/node_modules/bluebird/js/main/promise.js line 675 col 18)
var x = this._callHandler(handler, receiver, promise, value);
at Promise$_settlePromiseAt [as _settlePromiseAt] (/app/node_modules/bull/node_modules/bluebird/js/main/promise.js line 845 col 14)
this._settlePromiseFromHandler(handler, receiver, value, promise);
at Promise$_settlePromises [as _settlePromises] (/app/node_modules/bull/node_modules/bluebird/js/main/promise.js line 988 col 14)
this._settlePromiseAt(i);
at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/app/node_modules/bull/node_modules/bluebird/js/main/async.js line 77 col 12)
fn.call(receiver, arg);
at Async$consumeFunctionBuffer (/app/node_modules/bull/node_modules/bluebird/js/main/async.js line 40 col 14)
self._consumeFunctionBuffer();
at process._tickDomainCallback (node.js line 463 col 13)
```

In redis, the jobs data is empty. No opts, no data, no progress, no timestamps...

```
redis:11042> HGETALL bull:jobName:606
1) "delay"
2) "0"
```

I don't know how this is even possible.

**Comment by albertjan** [comment]
Looks like `JSON.parse(opts)` tries to parse `undefined`

```
> JSON.parse(undefined)
SyntaxError: Unexpected token u
    at Object.parse (native)
    at repl:1:7
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.emit (events.js:98:17)
```

**Comment by lchenay** [comment]
Sure. 
cf https://github.com/OptimalBits/bull/blob/master/lib/job.js#L220

data.data is undefined, as data.opts.

It should not.

"hgetall bull:jobName:jobId" should contain:
* data
* opts
* progress
* delay
* timestamp

As you can see in my exemple, it contain only delay. I don't know why.

**Comment by albertjan** [comment]
Oh wait could [this](https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L382) line in the `updateDelaySet` function cause this?

**Comment by albertjan** [comment]
No it can't

**Comment by manast** [comment]
JSON parse should always be surrounded by try/catch, my bad...

**Comment by lchenay** [comment]
Yes Json.parse should inside try/catch.
But before patch, let's find how this is possible?

Given this function https://github.com/OptimalBits/bull/blob/master/lib/job.js#L43, I don't see how.
Is it related to delayed job that is new?

**Comment by manast** [comment]
Yes, well, I think the problem is that the job was removed but the jobs id still left on some queue. So when the job is being processed it just reads undefined from Redis. Bull does not remove jobs explicitly so I guess in your code you are removing the job somewhere manually. 
Checking the code that removes the object, It seems correct to me, but maybe it can happen that a job gets deleted while still exist in some other list... I guess this requires some hand-onds debugging if we manage to reproduce this bug in a deterministic way.

**Comment by lchenay** [comment]
Yes we remove job on completed and on failed event.
The remove function look great to me too.

And I think it's not related to that. Because it use the command "DEL bull:jobName:jobId".
In this case, the key "bull:jobName:jobId" exists. But it do not contain all data. Only delay exists in redis

Exemple of job that throw error:
```
redis:11042> HGETALL bull:jobName:606
1) "delay"
2) "0"
```

Exemple of a good job:
```
redis:11042> HGETALL bull:jobName:684
1) "progress"
 2) "0"
 3) "data"
 4) "{\"userId\":\"1\"}"
 5) "delay"
 6) "9250"
 7) "opts"
 8) "{\"delay\":9250,\"timeout\":60000}"
 9) "timestamp"
10) "1422520872102"
```

**Comment by manast** [comment]
yes, this is exactly what will happen if a job has been delayed, then removed, then ``ùpdateDelaySet```updates the job, but the job has been removed already, so it just writes {delay: 0}. This means that the remove method in job is not removing correctly from the delayed set...

**Comment by lchenay** [comment]
You find it!

So maybe we should call exists, before doing hset and some other command in updateDelaySet()

**Comment by manast** [comment]
checking if the job exists in updateDelaySet will resolve the symptom, but the underlying problem is a hazard of some sort. I am speculating that the call to remove job happened after the job has been read and just before calling job.moveToDelayed which in turn calls job##_moveToSet. I think the correct solution is to check if the job exists atomically when moving the job from one queue to another, and if the job does not exist throw a exception (although is more an informative exception than anything else).

**Comment by manast** [comment]
I am also seeing that moveToSet does not remove delayed jobs from the active queue, which I am not sure is correct or not. Feels like wrong right now, but I have to think more...

**Comment by manast** [comment]
this should do it. A lot of changes lately. I will not feel confident in doing a new release without more testing actually...
