### ISSUE TITLE
Global job access and status info

### ISSUE THREAD

**Issue by alexandrebodin** [OptimalBits/bull#900]
## Description

When Needing to access a job by id, you also need to know in which queue it is and have an instance of that queue to call `getJob`.

Then if you want to now the status of a job you need to call `getState` (which is really not efficient)

This makes it hard to add some abstraction to bull (e.g creating parent/child jobs).

I would love two new features:

```js
const bull = require('bull');

const queue = bull.createQueue();
// then be able to do sth la this

// The first feature is global accessors
const myJob = bull.getJob('job-id');

// the second feature is to persist the job status in the job data and not only un a redis list
if (myJob.is('active')) console.log('job is currently running');
```

This can be done in 2 PRs, 

- [ ] Add job state in job redis hash
- [ ] Refactor bull to use global unique ids for jobs and have a global redis list (this one is really a lot of work)

If this sounds good to you guys, I can work on a PR.

Cheers

**Comment by manast** [comment]
can you explain a bit more about the use case where you need ```getState``` ?

**Comment by alexandrebodin** [comment]
Hi, 

yes of course, I'm currently using bull to back a job / pipeline system for an app.

My custom jobs start a bull process. 
Which in turn starts child bull processes. 

So I'm currently having to implement a "wait for child" feature, and then deduce the status of the parent depending on the child statuses (thus the need to call getState). 

Unfortunatly, I need to persist the queue and job id of each of my child to be able to retrieve them (not convenient if the information is in a redis list for ex). So global ids would go a long way to help me access jobs without queue context.

Hope this helps :)

**Comment by alexandrebodin** [comment]
@manast Any update ?

**Comment by manast** [comment]
ok, sorry for the late response. I think I understand your issue. Child / Parent relationships are the next major improvement in bull, it is not easy to build as you noticed on top of current APIs. However the new solution must be very robust, so it needs to be well though, we have an issue where this topic is discussed: https://github.com/OptimalBits/bull/issues/340
