### ISSUE TITLE
Error: Could not remove job

### ISSUE THREAD

**Issue by PrestonR** [OptimalBits/bull#902]
## Description
So the issue is happening on the `/job/bulk` api. The error is below. It looks like, for some reason, the key in question is created, but a node is created with the same ID, and then a sub-key is created under that node, and that sub-key looks malformed.

Here is the key (ttl -1):
![image](https://user-images.githubusercontent.com/8114786/38066116-781e05dc-32bb-11e8-9822-e2e6656c83e5.png)

Here is the sub-key (notice the differing UUID and ttl 21):
![image](https://user-images.githubusercontent.com/8114786/38066132-8aa580b8-32bb-11e8-879b-f19ea84ec82c.png)

So I suspect Bull is trying to delete one of them and it's not working, so both have to be removed manually.

Might you have any information on why and how this happens? Should I set a TTL on that -1 job so it kills itself eventually anyway?

Error:
```
{
  "error": "queue error",
  "details": "Error: Could not remove job cd56bf60-32a0-11e7-93df-f3de8719305c at /app/node_modules/bull/lib/job.js:339:13"
}
```

## Bull version
3.3.9

## Additional information
Bull Arena
![image](https://user-images.githubusercontent.com/8114786/38065949-9a65c72a-32ba-11e8-9949-22bb3e15711d.png)

Redis node/key
![image](https://user-images.githubusercontent.com/8114786/38066015-d88fb92a-32ba-11e8-9ca5-b2ee1f69c201.png)

**Comment by rafaelamorim** [comment]
+1 since we started to get these errors quite frequently :(

**Comment by PrestonR** [comment]
@manast I think there is two issues.

1) Stuck active jobs.
2) Arena not being able to delete stuck active jobs.

I added a TTL to the stuck active jobs and they are failing appropriately now without a timeout error.

I'll try to get you some code to reproduce in the next few days.

**Comment by manast** [comment]
Re-open if reproducible code is provided.
