### ISSUE TITLE
Globally paused queue cannot receive job (or not shown in Arena untill queue is globally resumed)

### ISSUE THREAD

**Issue by 11arn11** [OptimalBits/bull#903]
## Description
I use Arena as a GUI

I have two workers and two queues

The worker of the first queue fills the second queue.

The second worker must start paused.

When the first worker finishes his queue, he has to resume the second one.

Now the problem...

If the second worker starts globally paused, Arena does not show the jobs added to the queue until the second queue is resumed

If the second worker starts locally paused, Arena will show the jobs added to this second queue, but the first worker will not be able to restart th second queue (according to the documentation)

how can I do?

## Worker 1

```javascript

const Queue = require('bull');

const queue_1_1 = new Queue('queue1');
const queue_1_2 = new Queue('queue2');

(async function () {

	await queue_1_1.pause();

	queue_1_1.process(function (job, done) {

		if (something) {
			queue_1_2.resume();
		}

		console.log(job.data);
		done();

	});

})();
```

## Worker 2

```javascript

const Queue = require('bull');

const queue_2_2 = new Queue('queue2');

(async function () {

	// pause globally
	// in this way, Arena will not show the jobs of queue 2 until queue 2 is resumed
	queue_2_2.pause();

	// paused locally
	// in this way I will not be able to restart the second queue externally
	// queue_2_2.pause(true);

	queue_2_2.process(function (job, done) {
		console.log(job.data);
		done();
	});

})();
```

**Comment by manast** [comment]
sorry for the late response. The bug you report is quite strange, Bull has a method called ```getWaiting``` (https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queuegetwaiting)  that returns all the waiting jobs, either if the job is running or paused, if Arena uses this method, then it should work, can you try to call the method manually to see if it returns what you expect?

**Comment by 11arn11** [comment]
processing this script

```javascript

const Queue = require('bull');

const config = require('../config');

let paused_queue = new Queue('paused', {redis : config.redis});

(async function () {

	// Before "pause"
	let waiting = await paused_queue.getWaitingCount();
	console.log(waiting);

	await paused_queue.pause();

	// After "pause"
	waiting = await paused_queue.getWaitingCount();
	console.log(waiting);

	// After "add"
	paused_queue.add({});
	paused_queue.add({});
	paused_queue.add({});
	paused_queue.add({});
	paused_queue.add({});
	paused_queue.add({});
	waiting = await paused_queue.getWaitingCount();
	console.log(waiting);

	// After "resume"
	await paused_queue.resume();
	waiting = await paused_queue.getWaitingCount();
	console.log(waiting);

	await paused_queue.close();

})();

```

this is the output

// Before "pause" 0
// After "pause" 0
// After "add" 0
// After "resume" 6


running it a second time

/ Before "pause" 6
// After "pause" 0
// After "add" 0
// After "resume" 12


it seems that when a queue is paused it always has 0 jobs

can you help me?

**Comment by 11arn11** [comment]
ok, thanks in advance for your support. Can you notify me when you get fixed?

PS.
Can you explain me this sentence? Talking about Queue.pause method...

> Adding jobs requires a LUA script to check first if the paused list exist
  and in that case it will add it there instead of the wait list.

**Comment by manast** [comment]
when the queue is paused, the redis list that keeps all the jobs called ```wait``` is renamed to ```paused```, the benefit is that we can keep listening as usually to ```wait``` but no job will be processed until it is resumed, i.e. renamed again to ```wait```

**Comment by manast** [comment]
Will close now for lack of activity, re-open if necessary.

**Comment by 11arn11** [comment]
Can you fix queue.getWaitingCount() issue?
