### ISSUE TITLE
Multiple queues not running concurrently

### ISSUE THREAD

**Issue by rudism** [OptimalBits/bull#905]
## Description

A combination of reusing Redis connections and calling the `done` function asynchronously in the queue `process` functions seems to prevent queues from being processed concurrently.

## Test code to reproduce

I have recreated it in the gist here https://gist.github.com/rudism/893c0fe7dcf1813a3c59132548b3a8e7

The `setTimeout` is a simplification for reproduction purposes only. In the real code that I've run into this I'm making an http request and then adding new jobs to the queue based on the response before calling the `done` function.

## Additional information

When run, you can see from the output (included in the gist) that it first only processes jobs for queue `0` for a while (even though at that point queue `1` has jobs in `waiting`), then at some point around 30 seconds later it switches over and only processes queue `1` for a while (and leaves queue `2` with jobs in `waiting`). If you leave it running it flips back and forth between the two. The problem is made even worse with more queues (the queues that aren't being processed can have jobs that sit in `waiting` for several minutes at a time).

Doing either of these two things seems to solve the problem:
1. Remove `createClient` from `bullOpts` on line 17 and allow Bull to manage its own redis connections.
2. Remove the `setTimeout` on line 39 and call `addJob()` and `done()` synchronously.

Doing either of those two things and running the program, the output shows jobs from both queues `0` and `1` being run concurrently without leaving jobs in the `waiting` state for long periods of time. Is this expected behavior? Is there a way to call `done` asynchronously while reusing Redis connections that doesn't result in this behavior?

**Comment by manast** [comment]
The problem may be in reusing the bclient (blocking client), it can not be reused because one queue could be drained and the blocking call will prevent the other queues sharing the connection will stall.

**Comment by rudism** [comment]
Creating a new `bclient` connection every time seems to fix the problem. I'm curious, how often do those get created, and are they closed/cleaned up automatically at any point during the queue's lifecycle?

**Comment by manast** [comment]
They only get created once per queue, and closed when the queue is closed. However there is a standing issue (TODO) where external created connections should not be closed when closing a queue using any of them.

**Comment by rudism** [comment]
Thanks, I'll close this issue since it's working as expected.

Might be worth updating the `Reusing Redis Connections` documentation/sample to make it more clear which connections can be reused and at least mention that there's one that can't.
