### ISSUE TITLE
removeOnComplete not being honored, clean throws "WRONGTYPE Operation against a key holding the wrong kind of value"

### ISSUE THREAD

**Issue by smanousos** [OptimalBits/bull#909]
redis version 3.2.6
bull version 3.3.10

 I'm both a bull and redis newbie...

I have completed jobs that won't go away.  I have the option removeOnComplete set to true when I add the job to the queue.  The jobs appear to complete successfully and are listed in the queue completed set.  For my "dispatcher" queue that set is bull:dispatcher:completed.

Here's an example of the options I use when I add the entry  (from redis "opts" key of a completed entry):
```js
{
  "omitEventBus": true,
  "attempts": 5,
  "backoff": {
    "type": "exponential",
    "delay": 2000
  },
  "timeout": 10000,
  "removeOnComplete": true,
  "removeOnFail": true,
  "delay": 0,
  "timestamp": 1523127349471
}
```

Am I doing anything wrong? How do I diagnose this? 

I thought I could get around this problem by using queue.clean(5000) to clean up everything older than 5 seconds.  I get a redis error: "WRONGTYPE Operation against a key holding the wrong kind of value".  The lib/scripts.cleanJobsInSet is trying to use a ZRANGE on the bull:dispatcher:completed set.  I think the error is raised because ZRANGE requires a type "sorted set".  TYPE  bull:dispatcher:completed is "set".

Thoughts on what's going on?

**Comment by manast** [comment]
You should definitely not have any data on the completed set if you have the ```removeOnComplete``` set to true, since in that case the job is just removed after completion, it never reaches that set at all.
