### ISSUE TITLE
Jobs processed more than once

### ISSUE THREAD

**Issue by neilkinnish** [OptimalBits/bull#91]
We're using bull on multiple machines connected to one Redis instance processing long jobs.

Starting up multiple machines (3 in total), occasionally see the same job processed on 2 machines – this only seems to happen if a machine is brought online later then the others, when it comes online it picks up a job that another machine is already working on or completed.

**Comment by manast** [comment]
I will try to reproduce this. We have unit tests for this scenario but clearly they are not complete enough.

**Comment by albertjan** [comment]
The unit test that checks this does fail sometimes.

**Comment by neilkinnish** [comment]
Yeah we are able to reproduce this quite easily, even running the consumers locally.

Note: for context, we are using a redis provider (compose)

**Comment by manast** [comment]
ok. If you could create a simple case that reproduces this it would be much easier to fix.

**Comment by neilkinnish** [comment]
of course, as soon as I get chance I will submit

**Comment by albertjan** [comment]
if I run this command:

```sh
for n in {1..100}; 
    do mocha -g "does not process a job that is being processed when a new queue starts"; 
done;
```

You get a failure fast enough. I've added some logging and this is what I'm seeing:

Normal behaviour:
```
  Queue
     a worker
1422797285333 taking lock on job 2519 16b82256-c0fc-4dc8-a967-0356d24b87a3
1422797285336 taking lock on job 2519 0eb67090-80b0-40b2-ab9e-31ca9e8333e2
1422797285337 got lock? true 2519 16b82256-c0fc-4dc8-a967-0356d24b87a3
1422797285338 got lock? false 2519 0eb67090-80b0-40b2-ab9e-31ca9e8333e2
      ✓ does not process a job that is being processed when a new queue starts (121ms)
```

You can clearly see the second queue doesn't get the lock and thus not procesing the job.

But this is what it looks like when things go awry:

```
  Queue
     a worker
1422797286326 taking lock on job 2520 5ee59b2e-3ee6-4149-943f-3e5648a2a4d1
1422797286326 got lock? true 2520 5ee59b2e-3ee6-4149-943f-3e5648a2a4d1
1422797286327 taking lock on job 2520 f012eb67-130b-42ba-acde-36635012c08d
1422797286329 taking lock on job 2520 5ee59b2e-3ee6-4149-943f-3e5648a2a4d1
1422797286330 got lock? true 2520 f012eb67-130b-42ba-acde-36635012c08d
1422797286330 got lock? true 2520 5ee59b2e-3ee6-4149-943f-3e5648a2a4d1
      1) does not process a job that is being processed when a new queue starts
```

as you can see both queue's get a lock. How this is possible I don't know.
