### ISSUE TITLE
Seperate process worker fails to launch when Node is started with --inspect flag

### ISSUE THREAD

**Issue by nirmalvp** [OptimalBits/bull#911]
## Description
When the node process is started with the --inspect flag, bull fails to start a child process for the process worker with the error message : " error: unknown option `--inspect' "

## Test code to reproduce
nodemon index.js  --inspect  --exec babel-node
## Bull version
3.3.7

**Comment by ryedin** [comment]
Confirmed this behavior.

It looks to me like you could blacklist the `--inspect` option (ie. remove it when the child processes are spawned). I don't think `--inspect` is "cluster friendly" anyway. It should probably be shed from the command that spawns the children

**Comment by manast** [comment]
Could we close this now that we have a workaround in 3.4.2 https://github.com/OptimalBits/bull/blob/master/CHANGELOG.md#v342 ?
