### ISSUE TITLE
Problem with repeatable jobs

### ISSUE THREAD

**Issue by Exitialis** [OptimalBits/bull#912]
Hello. I need to repeat job in 10 seconds, after previous completes. How can i do it? I had tried do something like that:

index.ts:
```typescript
queue.process(10, path.join(__dirname, './processors/processor.js'));
queue.add({name: 'test'}, {
    attempts: 3,
    removeOnFail: true,
    removeOnComplete: true,
    repeat: {
        cron: "*/10 * * * * *",
        endDate: new Date().getTime() + 60 * 10 * 1000
    }
});
```

processor.ts:
```typescript
import {Job} from "bull";

export default async function(job: Job) {
    console.log('Job is running: ', job.data);

    return new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve()
        }, 10000);
    })
}
```

And job is started before previous finishes. The only way I found this is to control manually and add job in the queue after previous is completed, but i need to control end time and max attempts manually.

```typescript
queue.on("completed", (job: Job) => {
    job.data.count += 1;
    if (job.data.count < 5) {
        queue.add(job.data, {
            attempts: 3,
            removeOnFail: true,
            removeOnComplete: true,
        });
    }
});
```

**Comment by manast** [comment]
Sorry for the late response. I think the easiest way to accomplish what you want to do it to add a "delayed" job, either in the process function (that would be the safest), or in the ```completed``` event. The reason it is safer to add it in the process function is that it will not complete until the job has been added, so if for some reason the "add" fails, the job will also fail and can be retried until the add also has completed. Let me know if you need more help.

**Comment by Exitialis** [comment]
I already use the approach with the addition a new delayed job in completed event. But i thought, that i just not found right way to do that. Thank you for your help.

**Comment by lxcid** [comment]
@manast would you mind showing an example of delayed job in process function?
