### ISSUE TITLE
Separate processor memory usage

### ISSUE THREAD

**Issue by emhagman** [OptimalBits/bull#917]
Latest version of Bull, Node 8.11.1

Using a separate processor that only uses `console.log` to print causes my memory to spike greatly (400Mb idle to 5Gb) when running a named task with concurrency of 1.

It almost seems like a new process is being created for each task instead of only running one at a time. When using `.fork()`, am I correct in assuming that Bull/Node creates another copy of the entire app in memory? That's all fine but it appears it is trying to create 80 copies (or however man jobs I am trying to run). My assumption was it spawned one "worker" per queue that handled the task in a separate process, not one per job.

Any thoughts?

**Comment by manast** [comment]
Will close due to inactivity.
