### ISSUE TITLE
How to Read Bull jobs in Ruby/Python/Scala, etc.?

### ISSUE THREAD

**Issue by githubandrewd** [OptimalBits/bull#918]
I have been using Bull from my API app written in Node.js, but since my application requires natural language processing, it makes sense to later move processing to some other language that has better NLP libraries.

That raises a question ... technically, it is just a Redis queue, so it is not impossible to interface with Bull jobs from other micro-services, written in other languages.

However, it doesn't seem that Bull is available in other languages, so to read a job from Python or Ruby or Java, I will need to write my own queue reader?

Is my understanding correct?

P.S. For a similar reason, I don't think I can read jobs passed to me from Rails through sidekiq because there are no sidekiq reader libraries in Node.JS from my understanding.

Please correct me if I am wrong D:.

**Comment by githubandrewd** [comment]
Ok, I found a similar question:
https://github.com/OptimalBits/bull/issues/573.

Bull is not a good idea for my use case, then.

**Comment by roggervalf** [comment]
Just for referencie, there is an in progress implementation for python https://docs.bullmq.io/python/introduction
