### ISSUE TITLE
Add a method to wipe the whole queue

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#92]
this method will remove all the data related to a given queue. The tricky part is that there can be distributed jobs running and they will produce data until they finished. So we need a way to stop/abort all the ongoing jobs and then wait for them on all workers... (may not be possible to achieve perfectly)

**Comment by prabhu** [comment]
Was banging my head to find why npm test was failing when ran for the second time. To workaround this issue, we can set a flag for such running jobs suggesting abort. Looks like there is no way to pass events when a job is being processed, probably an enhancement.

**Comment by manast** [comment]
cleant has been improved quite a bit since this issue was reported so I will close it for now.

**Comment by TomKaltz** [comment]
I still don't understand how to delete a whole queue.  Even after cleaning all jobs from my queue it still shows up in Toureiro.  What am I missing?

**Comment by manast** [comment]
@TomKaltz can you open a new issue with some example code?

**Comment by wuchuguang** [comment]
empty() can't clean queue.

restart application , queue.process run old job.

**Comment by wuchuguang** [comment]
await this.followupQueue.empty();
    await this.followupQueue.clean(0, 'active');
    await this.followupQueue.clean(0, 'completed');
    await this.followupQueue.clean(0, 'delayed');
    await this.followupQueue.clean(0, 'failed');

is ok.
