### ISSUE TITLE
queue.client.updateDelaySet is not a function

### ISSUE THREAD

**Issue by fernandocalsa** [OptimalBits/bull#920]
I'm experiencing this error
```
TypeError: queue.client.updateDelaySet is not a function
        at Object.updateDelaySet (/src/node_modules/bull/lib/scripts.js:325:25)
        at /src/node_modules/bull/lib/queue.js:360:12
        at tryCatcher (/src/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/src/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/src/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/src/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/src/node_modules/bluebird/js/release/promise.js:693:18)
        at Async._drainQueue (/src/node_modules/bluebird/js/release/async.js:133:16)
        at Async._drainQueues (/src/node_modules/bluebird/js/release/async.js:143:10)
        at Immediate.Async.drainQueues (/src/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)
```

This error occurs when I start my server, but is not happening in my local, so I think it can be a dependency problem. I've debugged it and I see that `queue.client` is an object of `Redis` class, but it lacks that method.

I'm starting my queue as
```
var client = new Redis({
  port: REDIS_PORT,
  host: REDIS_HOST,
  password: REDIS_PASSWORD
})
var subscriber = new Redis({
  port: REDIS_PORT,
  host: REDIS_HOST,
  password: REDIS_PASSWORD
})

var options = {
      createClient: function (type) {
        switch (type) {
          case 'client':
            return client
          case 'subscriber':
            return subscriber
          default:
            return new Redis()
        }
      }
    }

const queue = new Queue('test', options)
```

Am i missing something? thank you!

**Comment by manast** [comment]
The method is created dynamically by ioredis when the queue is instantiated.

**Comment by fernandocalsa** [comment]
I think I've found something, the folder `lib/commands` has only the file `index.js`. Have you seen this problem before?

**Comment by manast** [comment]
the commands are loaded from the commands directory: https://github.com/OptimalBits/bull/tree/master/lib/commands

**Comment by fernandocalsa** [comment]
I think the problem is in the docker implementation, at some point we are not passing all the files to the container, so these functions don't load. I'm trying to get more information on this, as is another team who develops it. I'll let you know if I find something else

**Comment by haywirez** [comment]
I have the same error and no idea what causes it 😢 The queue doesn't even start, redis is running on the standard port. Here's what im doing:

```
// queue.js
import Queue from 'bull'

let jobQueue = new Queue('job queue', 'redis://127.0.0.1:6379')

jobQueue.process(function(job){
  return Promise.resolve('test')
})


export default jobQueue
```

```
// api.js
import jobQueue from './queue'
///...
 router.get('/queue-test', async (ctx, next) => {
    jobQueue.add({wtf: 'helloWorld'})
    ctx.status = 204
  })
```

**Comment by manast** [comment]
@haywirez as you have seen the the poster of the issue did a mistake, it is not a problem with bull. If on the other hand you have another issue, please create a reproducible test and open a new issue so that we can take a look at it.

**Comment by maitrungduc1410** [comment]
For the problem of @haywirez, you having same problem with me, because we're using `import/export` instead of `module/exports` so by some how the compiled code is not correct.

try add this to your webpack configuration file:
```
...
entry: [
    '@babel/polyfill',
    './server.js'
  ],
...
```
In here you need to add `@babel/polyfill` to have a full ES2015+ environment. (remember to do `npm install --save-dev @babel/polyfill` first).

Then re-compile your code.

It works for me. ❤️
