### ISSUE TITLE
Looping Queue & BUGS: Queue#getJobs and priority not working

### ISSUE THREAD

**Issue by sharmilasudhakar** [OptimalBits/bull#921]
Hi,
I'm working on a list of video queue processing. In that I face the following issues,

BUG : Priority need to be perfect. For the first time I add the jobs to the queue in the paused state and then if I start the queue means it is working fine based on the priority but Inserting a new job while processing a queue is not running based on the priority and it is not working properly. 

BUG : For restarting a Queue I have moved all the jobs to the pending state. But after moving to pending state the queue get automatically processed but it is not processing based on the priority, at a time more than 2 or 3 jobs are running.  If I pause and start the queue it gets collapsed.

BUG: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queuegetjobs not listing in the bull object.

New Feature : Looping the Queue once all the jobs has been finished processing. Is this available in the bull?

I'm using the latest version bull 3.4.0

**Comment by manast** [comment]
Please divide the issues in different issues and provide reproducible code for each one of them, so we can take a deeper look at them.
