### ISSUE TITLE
A lot of processes

### ISSUE THREAD

**Issue by Exitialis** [OptimalBits/bull#923]
## Description
I could not find the reason, but too many master process are created

![image](https://user-images.githubusercontent.com/7029837/39406938-52ac6e54-4bc7-11e8-8179-bf703e23f228.png)

## Test code to reproduce

queue.ts file
```typescript
import * as Queue from "bull";
import {Job, JobOptions} from "bull";
import {Operation} from "./operation";
import {Account} from "./account";

export let queue1 = new Queue('worker1', {
    redis: {
        db: 5
    }
});

export let queue2 = new Queue('worker2', {
    redis: {
        db: 6
    }
});

export let queue3 = new Queue('worker3', {
    redis: {
        db: 7
    }
});

export let queue4 = new Queue('worker4', {
    redis: {
        db: 8
    }
});

export let queue5 = new Queue('worker5', {
    redis: {
        db: 9
    }
});

let jobOptions: JobOptions = {
    removeOnComplete: true,
    removeOnFail: true,
    attempts: 3,
    timeout: 10000,
};

export async function addToQueue1(operation: Operation, delay?: number): Promise<Job>
{
    if (delay) {
        jobOptions.delay = delay;
    }

    return await queue1.add('job1', operation.getId(), jobOptions);
}

export async function addToQueue2(operation: Operation, delay?: number): Promise<Job>
{
    if (delay) {
        jobOptions.delay = delay;
    }

    return await queue2.add('job2', operation.getId(), jobOptions);
}

export async function addToQueue3(operation: Operation, delay?: number): Promise<Job>
{
    if (delay) {
        jobOptions.delay = delay;
    }

    return await queue3.add('job3', operation.getId(), jobOptions);
}

export async function addToQueue4(operation: Operation, delay?: number): Promise<Job>
{
    if (delay) {
        jobOptions.delay = delay;
    }

    return await queue4.add('job4', operation.getId(), jobOptions);
}

export async function addToQueue5(account: Account, delay?: number): Promise<Job>
{
    if (delay) {
        jobOptions.delay = delay;
    }

    return await queue5.add('job5', account, jobOptions);
}
```

i use this file to add operations to queue from processors, for example:

worker4.ts for queue4
```typescript
export default async function(job: Job): Promise<boolean> {
    let operation = await manager.getOperation(job.data); // I add operation id to job.data and keep operation object in redis hash and here i just get this object from redis hash

    logger.debug('Operation:', operation);

    let account = await manager.getAccount(); // Get object from redis

    if (!account.isUpdated()) {
        await addToQueue4(operation, 5000);

        return true;
    }

    const api = new Api(account);

    if (operation.getStatus() === OperationStatus.CLOSED) {
        let response = await api.close(operation.getData(), operation.getId());

        logger.debug('response: ', response);
        await addToQueue1(operation);
    } else if (operation.getStatus() === OperationStatus.BANNED) {
        let response = await api.ban(operation.getData(), operation.getId());

        logger.debug('reponse', response);
        await addToQueue1(operation);
    } // etc

    return true;
}
```

## Bull version
^3.3.10

## Additional information
At the moment I have not found what the problem is. But this code runs on production about 2 days and today i found that my server was lagging and if i try to use commands like 'ls' it says to me: "Cannot allocate memory" and after that i run htop and make a screenshoot

P.S. Sorry for my English.

**Comment by noriega3** [comment]
I am also having the same issue. 

Looking through the code for child pool processes, https://github.com/OptimalBits/bull/blob/07b78257e18a86bf59066c19be14d2d9e79078d8/lib/process/child-pool.js

I have a feeling it is regarding the .on exit or in regards to something on the child process not being unbounded somehow.  I figured out what child process it is by modifying the process.title on each of my child processor files.  When my jobs are done it doesn't auto destroy the said process until the server closes.  I hope this is sort of related.

**Comment by noriega3** [comment]
looking through the issues here, it may be related to this.
https://github.com/OptimalBits/bull/pull/750

**Comment by manast** [comment]
I have added some more tests for child reuse, however they are all passing so I really cannot reproduce this issue, it would be great if you could write a test case that reproduces the problem:
https://github.com/OptimalBits/bull/commit/6a389d9381fb9930ed8adb3281ae46ed180a89fd
https://github.com/OptimalBits/bull/commit/d6357ce92bc94c025de000063ba217aee25898a7

**Comment by lxcid** [comment]
@manast thanks for the quick response! I'll still investigating my issue! I'm trying to investigate if its caused by other libraries. Making some changes to see if the memory usage stabilise! I'll reply as soon as I have a good hypothesis.

**Comment by lxcid** [comment]
@manast sorry, I have a question that kinda related to how process are generated. If I use rate limiter with max 1 and duration 1000, it will mean that it will only spawn 1 job every second (does it consider the current running job?)

**Comment by manast** [comment]
@lxcid that specific case means the queue will process max 1 job per second.

**Comment by noriega3** [comment]
Thanks for the extra test cases.  I am also investigating the issue. Note: I  also use redis in the background using shared instances within the jobs themselves, and these redis connections close once the job is complete using Promise.using/dispose

For child creation, reading the code and seeing how child processes work.  An example would be if I have 2 jobs going towards the same processor name, eventProcessA.  Job 1 goes in and starts processing.  Job 2 wants to start but bull checks that it is busy with another job (job 1), so then spawns another eventProcessA to run in parallel to complete job 2.  

Both eventProcessA's stay in memory as 2 free childs available once these jobs are complete?  Or is it supposed to gracefully close each child process once it completes?  I'm assuming the intention is to stay in memory.  I've done a .clean but that doesn't close the created child processes.

**Comment by manast** [comment]
The idea of the child pool is to reuse processes so that the performance penalization for creating a process per job is minimized. Since bull will only process as many jobs in parallel as the concurrency value, it should never create more processes than said concurrency value. A future addition could be to force the creation of new process for every new job, (and close the old process), if more isolation is required at the cost of worse latency.

**Comment by noriega3** [comment]
That makes sense.  It does perform significantly faster for future jobs when running through my tests.  I do have a suggestion that I'll make a new thread for..  But going back, I may just thought too in depth to the point where I assumed I could easily close specifically named child processes in memory by cleaning or destroying.  But now, I will probably use "*"  and letting that parallel process figure out which of my internal functions to use, with bull creating more as needed.

**Comment by kombucha** [comment]
I'm encountering the same issue, I'll try to make a small example to reproduce the issue

**Comment by DavisJaunzems** [comment]
Experiencing similar issue when new jobs are created very quickly, but the jobs themselves take a long time to execute. 
When debugging the ChildPool code create jobs A, B and C, on the first job (A) it creates a new child, for the second (since the first one is not finished) it sees that there are no free processes so it creates a new one. For the third one (depending on how long the A or B takes) it will re-use an existing process or create a new child process. I'm not sure why it keeps taking new jobs from the queue if the concurrecny is set to 1.

**Comment by manast** [comment]
@DavisJaunzems thanks for the info, this may get us a hint on how to create a test that reproduces the issue.

**Comment by DavisJaunzems** [comment]
More debugging shows that it has something to do with the job that I'm executing (it creates database connection, etc.), because when running a simple sleep job then it behaves as expected.

**Comment by manast** [comment]
@alvinwoon I'll double check the logic for spawing process to see if there is a hazard somewhere.

**Comment by manast** [comment]
@alvinwoon unfortunately I am not able to see how this hazard can happen :/
Maybe if a concise reproducible example I could find the issue.

**Comment by lxcid** [comment]
I'm not very familiar with the codebase but afaik, I believe the code in question is at `ChildPool.retain()`…

https://github.com/OptimalBits/bull/blob/9ea172098babb5c01e749c57953e9a4d1fc4bc68/lib/process/child-pool.js#L17-L42

This function forked a child process if there is no free child process to reuse (at line 32). It doesn't do any check nor limit the number of processes created…

This sandbox system get setup if we uses tell the queue we want to process the job with a process file…

https://github.com/OptimalBits/bull/blob/9ea172098babb5c01e749c57953e9a4d1fc4bc68/lib/queue.js#L685-L697

I believe `concurrency` does not control the amount of process get created, seems like `concurrency` control speed at which the scheduler schedule the jobs.

So if you have large number of job queued up, the scheduler might schedule them as fast as possible (I believe this is where rate limiter is respected), but if u does not have enough processor to keep up with the scheduler, more child will get forked.

**Comment by manast** [comment]
The concurrency controls the amount of jobs that can be processed in parallel. It is a simple loop. Whatever is the reason for this issue is much more subtile.

**Comment by lxcid** [comment]
Would it be possible to emit an event for when a child is forked? I’m not sure how it will help but we might able to log when that happen and see how it interact with limiter settings.

It’s think to control the memory, if we could manage the child process or limit its creation, it should help quite a bit.

**Comment by slifty** [comment]
We are facing this issue over at [this project](https://github.com/TechAndCheck/tech-and-check-alerts) but only when deploying to a server.

When running locally I see around 15 master.js processes when I run htop.
When running on our dev deployment we see hundreds.

(Same number of cores, same amount of RAM, the difference may be how long each job takes to complete?)

We have a few queues which in turn spawn new jobs for each other; the queues themselves are created by [this factory](https://github.com/TechAndCheck/tech-and-check-alerts/blob/9947097b93cbeadda99d871a66830c2993845517/src/server/queues/AbstractQueueFactory.js#L33-L43)

I'll update this note as we discover more about what's going on.

**Comment by stansv** [comment]
Hi @slifty! Yes, It was a little surprise for me too when I used Bull first time. Queue options are never persisted in Redis. You can have as many Queue instances per application as you want, each can have different settings. The concurrency setting is set when you're registering a processor, it is in fact specific to each process() function call, not Queue. If you'd use named processors, you can call process() multiple times. Each call will register N event loop handlers (with Node's process.nextTick()), by the amount of concurrency (default is 1).

**Comment by slifty** [comment]
Another note -- htop [shows threads as processes by default](https://superuser.com/questions/118086/why-are-there-many-processes-listed-under-the-same-title-in-htop).  If OP were to type "H" I wonder if it would collapse into just the six processes that they expect.

Maybe this issue is a combination of folks who are misunderstanding the output of htop and folks who are misunderstanding the way concurrency works across multiple queue objects (I fell into both categories).
