### ISSUE TITLE
Question: What if processing a job is done in another repo/app?

### ISSUE THREAD

**Issue by aleccool213** [OptimalBits/bull#926]
Hi there, I am in love with the features this app can give me in terms of job management.

I am working on a project which requires a job management tool to be separate from the tool that actually processes the job. 

Eg. scenario:

1. Bull gets a job
2. Bull sends a request to another app (this is the one doing the job processing)
3. Bull stores in Redis that that the job is `IN_PROGRESS`
4. Other job processing app finishes its tasks and sends a request back to Bull.
5. Bull pulls the job from Redis and changes the status to `DONE`.

If this is not supported, would this be easy to implement? Any insight would be helpful.

Thanks

P.S. I see [separate processes](https://github.com/OptimalBits/bull#separate-processes) are supported. This could technically be done by using this but I if I run 1000 jobs, I don`t want to have 1000 processing hanging around waiting for calls back to them.

**Comment by aleccool213** [comment]
mhm thanks for the insight. After more thought, I would just use Bull and manually manage my state transitions for jobs. It seems like no client functions exist to change a job to completed status but I do see one for changing it to active.

@manast Is there a client function for changing a job to completed status once I have the Job object itself?

**Comment by manast** [comment]
you do not need to change the status of the jobs, they change as they get processed in the queue. The API is quite simple, ```add``` for adding jobs to the queue, ```process``` to process them. When you add them they are in wait state until they get processed where they can end being completed or failed.

**Comment by aleccool213** [comment]
👍
