### ISSUE TITLE
Can I use bull to schedule a job to run just *once* at a specific date/time like Agenda?

### ISSUE THREAD

**Issue by adamsoffer** [OptimalBits/bull#932]

**Comment by manast** [comment]
Just delay the job until the point in time you need it to be executed.

**Comment by adamsoffer** [comment]
Thanks @manado. Would you mind providing an example? I’m not sure I follow.

In agenda, I simply call a function called “schedule”.

```
agenda.schedule('new Date(1530446400), 'printAnalyticsReport');
```

**Comment by adamsoffer** [comment]
Would it be `job.add(‘printAnalyticsReport’, { delay: 1530446400 })`?

**Comment by manast** [comment]
You have to substract the desired time from the current time:
```
const delay = (new Date("2019/10/05") - new Date())
```

**Comment by SujayPrabhu96** [comment]
Hi folks, instead of passing delay, how about setting cron job & remove on complete
```
    queue.add(
      {},
      {
        repeat: { cron: `0 15 * * *` },
        removeOnComplete: true
      }
    )
```

Issue with delay is: say, I want to run a scheduler at `15:00:00`, it is running at `15:00:10`. I suspect there is some delay where we get the delay time in `ms` and set it on queue
