### ISSUE TITLE
use native promise if available

### ISSUE THREAD

**Issue by hbakhtiyor** [OptimalBits/bull#938]
## Description
currently not using native promise when available

**Comment by manast** [comment]
Not sure we can do that since we use some useful features from Bluebird. What is your motivation to use native promises?

**Comment by ritter** [comment]
We too prefer Bluebird promises, please don't downgrade to native.

**Comment by hbakhtiyor** [comment]
better performance, if you prefer bluebird promises, i think need separate module, like https://www.npmjs.com/package/request-promise-native

**Comment by manast** [comment]
Native promises seems to be many times slower than bluebird:
http://bluebirdjs.com/docs/benchmarks.html
