### ISSUE TITLE
Support more interval definitions for repeatable jobs

### ISSUE THREAD

**Issue by cuchi** [OptimalBits/bull#942]
Hi!

We are currently migrating from [agenda](https://github.com/agenda/agenda), but there is this little problem keeping us from doing that.
The **cron** notation is a very good idea to schedule repeatable jobs, but there are cases it is impossible to use, like representing an interval definition of _every 90 minutes_. 

To support this, `RepeatOpts` could be modified to accept other formats besides **cron**, which could be:
- How many seconds or millis, like in `setInterval`
- A string to be parsed by [human-interval](https://github.com/agenda/human-interval), which is used by agenda

I do not know the complexity of this enhancement, but it could be a good idea for the next feature release, what do you think?

Maybe related to #912

**Comment by manast** [comment]
It is quite easy to implement, so we can do this for the next release.

**Comment by manast** [comment]
I think we already cover this functionality so I will close the issue, re-open if necessary.
