### ISSUE TITLE
Incomplete Documentation

### ISSUE THREAD

**Issue by pariola** [OptimalBits/bull#947]

**Comment by manast** [comment]
Can you be more precise regarding what is incomplete so that we can complete that part?

**Comment by pariola** [comment]
Thanks for the quick response 👍. I believe: 
- Delayed Jobs
- Priorities
- Threaded processing functions. ❌ I tried this but i get path does not exist)
- Schedule Jobs
- Rate Limiter
- Retries

**Comment by pariola** [comment]
Oh thanks i didn't look in there

**Comment by kakasal** [comment]
Like complete implementation of queues, processing complex operations and doning the job using promises. the documentation is insufficient
