### ISSUE TITLE
Ambiguous Queue.add arguments 

### ISSUE THREAD

**Issue by Cherry** [OptimalBits/bull#948]
## Description
Firstly, as per the documentation at https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd, you can pass `name` as an option to the Queue.add function, and only a handler designated for that name will process jobs. When a handler isn't defined for this job `name`, you receive an error similar to `Missing process handler for job type JOB_NAME`. The documentation doesn't really mention a job `type`, so diagnosing this issue took me longer than I'm willing to admit.

More importantly, the arguments for Queue.add seem to be a little ambiguous when passing a string as the `data` with options. When I passed a string such as `my-unique-id-here`, and job options such as `jobId`,`backoff`, etc. Bull processed this as a `name`, and `data`, with no `options`. As an example:

## Test code to reproduce
```javascript
'use strict';

const Queue = require('bull');

var myQueue = new Queue('my_queue');

myQueue.on('failed', function(job, err){
	console.error('Job ID %s failed', job.id, err);
});

myQueue.add('abc-123-foo', {
	attempts: 3,
	removeOnComplete: true,
	removeOnFail: true,
	backoff: {
		delay: 15000,
		type: "fixed"
	}
});

myQueue.process(function(job, done){
	console.log('Processing job', job.id, job.data);
	return done();
});

setTimeout(function(){
	myQueue.close();
}, 5000);
```

The expected result would be to see:
```
Processing job 1 'abc-123-foo'
```

The actual output is:
```
Job ID 1 failed Error: Missing process handler for job type abc-123-foo
...
```

## Bull version
Tested on Node 8.11.2 and Bull 3.4.2.

## Additional information
This can obviously be worked around by passing something like `{id: 'abc-123-foo'}` as my data, but the documentation  definitely does not make this clear. From my memory, this work in previous versions of Bull, but not since updating to 3.x.

**Comment by manast** [comment]
I am not sure I understand the issue here. Is it that you want to suggest a different signature for the ```add``` method or just a better clarification regarding the name parameter? Just for the sake of it I added an extra sentence regarding this matter.

**Comment by Cherry** [comment]
Thanks for the reply. 

According to the doc at https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd, `data` can be of any type and is the only required parameter, and then `name` and `JobOpts` are optional. As far as I can tell, there is no way to pass `data` as a string, with `JobOpts`, as you can see in my example.

**Comment by manast** [comment]
You are right, data should be an Object, however, there is no Object type we can use from typescript, so thats why we chose any, I am open for suggestions...

**Comment by manast** [comment]
fixed by using "object" as data type for arg data.
