### ISSUE TITLE
Storing the error/stacktrace when a job fails

### ISSUE THREAD

**Issue by toddbluhm** [OptimalBits/bull#95]
Hey @manast 

Is there any chance that if an error occurs/is passed to `done()`, that the error could be stored on job so that ui's (such as matador) could display the error and stack trace later to better help find and debug what caused the error?

Thanks

**Comment by manast** [comment]
Seems like a legitimate request, I will see if I can do this in the next couple of days (unless some other kind soul want to send a pull request :).

**Comment by albertjan** [comment]
I love low hanging fruit :smile:

**Comment by toddbluhm** [comment]
Sweet! Thank you both!
