### ISSUE TITLE
how to implement node specific scheduler using bull

### ISSUE THREAD

**Issue by huoff** [OptimalBits/bull#955]
## Description
I have a requirement of creating node-specific schedulers  with bull. Node specific scheduler means we can create cron tasks that run on every individual node of cluster, task on each node is standalone, and should not affect tasks on other nodes.

I tried with bull and found bull didn't support this function. Does bull support this function? how to implement this node specific scheduler using bull?

## Bull version
3.4.1

**Comment by manast** [comment]
Cant you just create a node specific queue, and add your repeatable jobs in there?
