### ISSUE TITLE
The repeated job will run forever if I am not flushdb

### ISSUE THREAD

**Issue by huoff** [OptimalBits/bull#956]
## Description
I find a bug when using bull. 
Reproduce steps:
First, I created a repeatable job with cron { cron: '*/2 * * * * *' } , the job will run every two seconds.
Then, I delete the repeat property { repeat: { cron: '*/2 * * * * *' } }. As a result, I found the job still runs every two seconds.
Last, If I go to redis, run commond "flushdb", the job will run correctly.

So I think it is not as designed, is it?  Sometimes I can not flushdb on redis, or else the data will be lost. Any method can avoid this case?

## Minimal, Working Test code to reproduce the issue.
```js
const audioQueue = new Queue('audio transcoding', 'redis://127.0.0.1:6379'); // Specify Redis connection using object
  let count = 0;

  audioQueue.process((job, done) => {
    // task
    // call done when finished
    console.log("audioJob have done!");
    done();
  });

  audioQueue.add({ audio: 'http://example.com/audio1.mp3' }, { repeat: { cron: '*/2 * * * * *' } });

  audioQueue.on('completed', () => {
    // Job completed with output result!
    count +=1;
    console.log(`The result: ${count}`);
  });
```
## Bull version
3.4.1

**Comment by manast** [comment]
Is the test code correct? I do not see it is trying to remove the job.

**Comment by billiebbb** [comment]
I have same issue with options "removeOnComplete: true".

**Comment by billiebbb** [comment]
The Solution is in #709. 
Add 'process.on('exit', exitHandler)' to do series queue.clean(0, ....

**Comment by manast** [comment]
I am going to close this now, since the example code does not reflect the description of the issue. Re-open when clarified.
