### ISSUE TITLE
[Question] Get Queue status

### ISSUE THREAD

**Issue by diegogarciaa** [OptimalBits/bull#969]
How can I get status from a queue ?
Thanks.

**Comment by manast** [comment]
What do you mean with "queue status" ?

**Comment by manast** [comment]
Queues are not "created". You add jobs to them and the jobs are moved to different redis data structures during their lifetime. So there is not really an answer to your questions as they are formulated...

**Comment by diegogarciaa** [comment]
I do not agree. Obviously queues are created... Let me try to be clear:
Step1 : Create queue
Step2: Add Jobs
Step3: Close app beforing processing all jobs
Step4: Restart app
Step5: Create a new queue with the same name
Step6: Token changes, name remain the same
Step7: Remaining unprocessed jobs starts to be processed

**Comment by manast** [comment]
token is a private variable used for event handling, why do you care about that?
