### ISSUE TITLE
Releases not tagged in git or updated in Changelog.md

### ISSUE THREAD

**Issue by aslakhellesoy** [OptimalBits/bull#97]
This makes it really hard to know what's changed between releases, which makes it scary to upgrade.

**Comment by manast** [comment]
ok, made the first tag. I can add tags for previous releases as well no problem.

**Comment by manast** [comment]
latest releases have now being tagged.

**Comment by aslakhellesoy** [comment]
Awesome - thanks!

**Comment by aslakhellesoy** [comment]
I've added PR #98 to make this easier in the future

**Comment by aslakhellesoy** [comment]
@manast looks like 0.2.4 was pushed to npm, but there is no tag in git, and no entries in `CHANGELOG.md`. It's therefore impossible to know what went into that release.

I see you updated the version in `package.json` manually. There is no need for that if you follow the release process I described in `CONTRIBUTING.md`.

**Comment by manast** [comment]
I am sorry for this. I did the release in a hurry and therefore wrong. I have fixed it manually now.

**Comment by aslakhellesoy** [comment]
Ha - I bet `npm version patch && npm publish` is even faster ;-)
