### ISSUE TITLE
Move Typescript definitions to inside the repo

### ISSUE THREAD

**Issue by aleccool213** [OptimalBits/bull#970]
## Description
This is common practice if a lot of users of the package are using Typescript. Personally I am using Typescript with this and would like types to be more close to the metal. This would encourage them to be developed upon more. Currently they are located at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bull

## Example

https://github.com/facebook/jest/tree/master/types

**Comment by manast** [comment]
it is still quite standard to have it as a separate ```@types/bull``` package which honestly is not a lot of work to do. I will close this, hopefully in the future we can port bull to typescript and no external dependencies will be needed.
