### ISSUE TITLE
If a job takes too much time to process others suck

### ISSUE THREAD

**Issue by kakasal** [OptimalBits/bull#973]
The so-called concurrency don't work. If one of my job takes too much time to process it just f*** up the whole queue system. Is there any way to run each job in separate thread? Or in such a way that others keep executing even if some process stuck.

**Comment by manast** [comment]
there is plenty of documentation regarding how to work with concurrency and/or sandboxes processors. I recommend you to study it and if you still have an issue, give us a reproducible case that we can debug.
