### ISSUE TITLE
Jobs do not run in the sequence I add them into a Queue

### ISSUE THREAD

**Issue by actraiser** [OptimalBits/bull#977]
Hello,

I would like  jobs in a queue to be processed in the sequence I add them. However, in my current setup, it seems jobs are randomly picked for processing.

I have a queue that sends request to a Product API to acquire the latest product data. Requests are limited to 1 req every 2 seconds. I queue up requests in categorized batches, e.g. my server running bull receives 100 Job requests about fetching data about toys, then the next batch of requests might be 250 jobs that fetch clothing data from the API.

So when I sent mentioned 100 Toys first and afterwards the 250 Clothing jobs into the queue, Bull seems to randomly pick a job out of the 350 to be processed. My understanding actually is, that the queue is supposed to be processed in the sequence jobs were inserted so I simplyI might have a side effect somewhere in my actual queue setup.

My queue is initialized like this. There is a limiter to respect the 1req/per 2 seconds limit and a backoff strategy when there are errors. 

```
const queueOptions = {
  redis: redisClient,
  limiter: {
    max: 1,
    duration: 2000,
  },
  settings: {
    backoffStrategies: {
      jitter: () => (
        2500 + (Math.random() * 500)
      ),
    },
  },
};

const queue = new Queue('productinfo', queueOptions);
```

I setup my fetchItem processor using the named processor pattern with an external js file like explained in the docs:

`queue.process('fetchItem', 1, './processors/fetchItem.js');`

Finally, each job is added via my controller using these options:

```
const job = await queue.add('fetchItem', req.body, {
      removeOnComplete: true,
      removeOnFail: true,
      attempts: 5,
      backoff: { type: 'jitter' },
    });
```

All 350 jobs are being processed in the end but as mentioned, not in the order I dispatched them into the queue. Is there something I have not taken into account? When I check the status in Arena, I can see that jobs are switching Status between Active, Delayed and Waiting which I assume is correct as the limiter is in effect (example picture is from the queue with more than 350 jobs as opposed to what I outlined as example above):

![queue](https://user-images.githubusercontent.com/5455/41501883-ead8b4f2-71ac-11e8-905f-5283f695afbb.png)

Maybe someone has a hint or a suggestion.

Now thinking about it - I use async/await to add the jobs into the queue. Might this be the root of the problem - like that all those hundreds of Promises are resolved in a different order than how express.js receives the requests in the first place?

Greets
-act

**Comment by actraiser** [comment]
Okay, long story short - the problem was never with Bull but how I fetched my jobs before I dispatched them into the queue. So the jobs were not in order in the first place. Bummer. 


used

**Comment by kakasal** [comment]
What is backoff? why jitter?

**Comment by actraiser** [comment]
See [here](https://github.com/OptimalBits/bull/blob/master/PATTERNS.md#custom-backoff-strategy)
