### ISSUE TITLE
Any way to keep the jobs be processed in order base on the added order？(earlier first)

### ISSUE THREAD

**Issue by ash0080** [OptimalBits/bull#979]
```js
// redis3.2-alpine
const doSomething = async function (job) {
  // await sleep(2)
  return new Date()
}
const queue = new Queue('test',
  {
    redis: CONFIG.REDIS_OPTS,
    limiter: {
      max: 1,
      duration: 500
    }
  }
)
queue.empty()
queue.process(1, (job) =>{
  return doSomething(job)
})

// do statistics
const votes= [0,0,0,0,0,0,0,0,0,0]
queue.on('completed', (job, result) => {
 // some condition fit, then repeat job
 ++votes[job.data.data]
  console.log(votes)
  queue.add(job.data, { removeOnComplete: true, removeOnFail: true, delay: 2000 }) // test point
  console.log(result.toLocaleString(), job.data)
})

for (let i = 0; i < 10; i++) {
  queue.add({ data: i }, { removeOnComplete: true })
}

```
```
2018-6-19 19:46:01 { data: 0 }
2018-6-19 19:46:01 { data: 1 }
2018-6-19 19:46:02 { data: 7 }
2018-6-19 19:46:02 { data: 3 }
2018-6-19 19:46:03 { data: 2 }
2018-6-19 19:46:03 { data: 1 }
2018-6-19 19:46:04 { data: 7 }
2018-6-19 19:46:04 { data: 5 }
2018-6-19 19:46:05 { data: 8 }
2018-6-19 19:46:05 { data: 1 }
2018-6-19 19:46:06 { data: 7 }
2018-6-19 19:46:06 { data: 5 }
```
several minutes later,
with delay only:
[ 46, 48, 47, 38, 13, 46, 38, 22, 61, 34 ] super bad

with delay + lifo: 
[ 46, 36, 50, 41, 45, 33, 50, 43, 38, 47 ] better, but not enough

without any:
[ 24, 24, 24, 27, 25, 26, 24, 26, 26, 22 ] not too bad

with lifo only: 
[ 23, 24, 21, 21, 22, 19, 19, 24, 23, 20 ] almost same

when I try to repeat the jobs in 'completed' event,  seems some jobs always be pushed away.
considering in massive practice application，I wonder some jobs will never be processed.

so my question is, is there a race condition system to make the job added earlier be processed in a high priority?
I guessed option 'lifo' is made for this, but the behavior is not as my expect, actually, there's no difference to set lifo:true in my case above

**Comment by manast** [comment]
jobs are processed in order, unless using priorities or delay. Maybe the issue with the rate limiter? it could be a be that when the rate limiter kicks in the order is not preserved anymore.

**Comment by manast** [comment]
firstly, if you can verify that it works well without the limiter and then that it does not work with the limiter. If you can write it as a test case it is much easier to fix it than if we need to reproduce it ourselves.

**Comment by ash0080** [comment]
@manast
Found a new issue, using limiter will make the CPU usage about 3 times higher
