### ISSUE TITLE
Unhandled rejection ReplyError: ERR unknown command 'evalsha'

### ISSUE THREAD

**Issue by jahanzaibajmal** [OptimalBits/bull#981]
## Description

Unhandled rejection ReplyError: ERR unknown command 'evalsha'
    at JavascriptRedisParser.returnError (C:\Users\Jahanzaib Ajmal\Desktop\cronJob\node_modules\ioredis\lib\redis\parser.js:24:25)
    at JavascriptRedisParser.execute (C:\Users\Jahanzaib Ajmal\Desktop\cronJob\node_modules\redis-parser\lib\parser.js:572:12)
    at Socket.<anonymous> (C:\Users\Jahanzaib Ajmal\Desktop\cronJob\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

## Minimal, Working Test code to reproduce the issue.

var cronJob = new Queue('cron job');

    cronJob.process(function(job, done) {
        console.log(job.data.storeID);
        console.log(job.data.jobTime);
        done();

        throw new Error('some unexpected error');
    })

    for (let element in data) {
        cronJob.add({
            data: element
        });
    };

## Bull version

"bull": "^3.4.2"

**Comment by manast** [comment]
Which version of redis are you using? evalsha was introduced in redis 2.6: https://redis.io/commands/evalsha

**Comment by jahanzaibajmal** [comment]
redis : 2.8.0

**Comment by David8500** [comment]
@manast I am getting the same issue, my redis version is 2.8.9.
**Description**
`Server Port: 3030
Server Address: 127.0.0.1
(node:11160) UnhandledPromiseRejectionWarning:   ReplyError: ERR Syntax error, try CLIENT (LIST | KILL ip:port)

  - parser.js:24 JavascriptRedisParser.returnError
    [bulb-api]/[ioredis]/lib/redis/parser.js:24:25

  - parser.js:572 JavascriptRedisParser.execute
    [bulb-api]/[redis-parser]/lib/parser.js:572:12

  - event_handler.js:107 Socket.<anonymous>
    [bulb-api]/[ioredis]/lib/redis/event_handler.js:107:22

  - events.js:116 emitOne
    events.js:116:13

  - events.js:211 Socket.emit
    events.js:211:7

  - _stream_readable.js:263 addChunk
    _stream_readable.js:263:12

  - _stream_readable.js:250 readableAddChunk
    _stream_readable.js:250:11

  - _stream_readable.js:208 Socket.Readable.push
    _stream_readable.js:208:10

  - net.js:601 TCP.onread
    net.js:601:20


(node:11160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11160) UnhandledPromiseRejectionWarning:   ReplyError: ERR unknown command 'evalsha'

  - parser.js:24 JavascriptRedisParser.returnError
    [bulb-api]/[ioredis]/lib/redis/parser.js:24:25

  - parser.js:572 JavascriptRedisParser.execute
    [bulb-api]/[redis-parser]/lib/parser.js:572:12

  - event_handler.js:107 Socket.<anonymous>
    [bulb-api]/[ioredis]/lib/redis/event_handler.js:107:22

  - events.js:116 emitOne
    events.js:116:13

  - events.js:211 Socket.emit
    events.js:211:7

  - _stream_readable.js:263 addChunk
    _stream_readable.js:263:12

  - _stream_readable.js:250 readableAddChunk
    _stream_readable.js:250:11

  - _stream_readable.js:208 Socket.Readable.push
    _stream_readable.js:208:10

  - net.js:601 TCP.onread
    net.js:601:20


(node:11160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

















`

**Comment by manast** [comment]
probably a redis provider that do not support EVALSHA command, not a bug in bull itself.

**Comment by dejibimbolaAyo** [comment]
Upgrading Redis to a recent version, 4.0 is stable

If you are on windows system and need to install a recent version of Redis. The best, for now, is highlighted in the post: [How To Install Redis 4.0.9 on Windows 10: Details](https://medium.com/@Renyxz/how-to-install-redis-4-0-9-on-windows-10-details-d130ef4aaa08)
