### ISSUE TITLE
Fix errors when removing jobs in priority queues

### ISSUE THREAD

**Issue by cbjuan** [OptimalBits/bull#983]
## Description
Removing jobs and cleaning queues when using priority queues break the queue order since some internal queues are not removed when needed.

## Minimal, Working Test code to reproduce the issue.
  * File `removeJob-7.lua` should be renamed to `removeJob-9.lua` and lacks ZREM for 'priority' and 'id' keys.
  * File `queue.js` lacks of keys 'priority' and 'id' in `multi.del(this.toKey())` statement
  * File `scripts.js`. In `remove()` method must be included the keys 'priority' and 'id' to the map

## Bull version
3.4.2

## Additional information
Opening a new PR to solve these issues

**Comment by tidusvn05** [comment]
i have the same issue. i can not remove job.

**Comment by cbjuan** [comment]
Solved in #984
