### ISSUE TITLE
Connecting to Existing publisher in Bull. 

### ISSUE THREAD

**Issue by ganeshcse2991** [OptimalBits/bull#987]
I have a php microservice (publisher) which publishes to a redis channel. I need to make use of Bull in another node js app which subscribes to the same channel. Not able to find a way to use it in Bull. I dont want to make use of existing node js subscriber since I need retry and all other mechanisms which Bull provides. Please sugest on how to proceed with this problem.

**Comment by manast** [comment]
You need to add jobs to bull using the same lua script that bull uses: https://github.com/OptimalBits/bull/blob/master/lib/commands/addJob-6.lua
