### ISSUE TITLE
Retries documentation?

### ISSUE THREAD

**Issue by alanhoff** [OptimalBits/bull#99]
Hello folks, where can I read more about retrying a job? Thx!

**Comment by albertjan** [comment]
call `job.retry()` or `queue.retryJob(job)` :smile:. There's no automatic retry capability atm. I have to find some time to write that.

you could do that yourself:

```js
queue.on.failed(function (job) {
    job.delay = 1000;
    job.retry();
});
```

**Comment by manast** [comment]
There is of course a small risk that the processor dies before the call to job.retry succeeds and then the job will never be retried. I guess a proper retry+delay will require an atomic redis lua script :/

**Comment by toddbluhm** [comment]
FYI, for anyone else running across this code/docs, I tried to get it to work using a different delay than the initial one set when I add a job to my queue, and it does not work. Currently the retry method just moves the jobId around in various redis lists, and delay is stored on the job in redis. So when you set delay here, it never updates the job in redis, thus the delay for the retried job is never updated. `retry()` will literally just retry the job as it was initial put in with no ability, currently, to change anything about that job.

Whether this is the desired behavior or not is up for discussion, I am just putting this info out here for anyone else who runs into this quirk like I did.

**Comment by albertjan** [comment]
@toddbluhm good catch. Retry is definatelly something that needs some tlc.

**Comment by jeffreywescott** [comment]
Isn't this handled with `attempts` and `delay`? I think this issue is no longer valid.

**Comment by manast** [comment]
This has been fixed some time ago with ```attempts``` option.
