### ISSUE TITLE
UUID?

### ISSUE THREAD

**Issue by christianbundy** [OptimalBits/bull#990]
Hello!

I've recently run into issues with Bull's incremental integer job IDs where I realized that a unique ID could be _very_ helpful (e.g. saving output to a file named after the job ID). After restarting Redis it looks like the job ID starts over with an ID of `1`, whereas it seems like it would be easy and useful to have these remain unique.

Would you be open to a PR replacing the incremental job ID with a UUID? Here's how we're doing it now:

```js
import 'uuidv4' from 'uuid/v4';

// ...

q.add(data, { jobId: uuidv4() })
```

Example job ID:

```
e8a3d4df-50be-44db-852e-99bf0dbbb2ad
```

Thanks for your work on this project!

**Comment by manast** [comment]
Since we already support specifying the jobId manually I do not see a big advantage to add this functionality. Bull users are used to use custom jobIds for their needs.
