### ISSUE TITLE
More info on running jobs with `tz`

### ISSUE THREAD

**Issue by pariola** [OptimalBits/bull#991]
## Description
I'm want to perform some tasks in a worker specifying  timezone, i tried using cron `30 19 * * *` and `30 20 * * *` with tz set to `Europe/Istanbul` however looking at jobs in redis, i can find that jobs are scheduled using my local/server time `Africa/Lagos`, so jobs run +2 hours later.

## Unexpected Behavior
I expected jobs to run at `08:30PM Europe/Istanbul` time but instead runs at `08:30PM Africa/Lagos` time

Please any info would really help!

Updated question!

**Comment by manast** [comment]
Can you provide a complete example that reproduces the issue?
