### ISSUE TITLE
How to query which queue is empty 

### ISSUE THREAD

**Issue by shaozi** [OptimalBits/bull#993]
after created multiple queues, is there a function to check which queues are at the moment empty?

**Comment by manast** [comment]
https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queuegetwaitingcount
if the count is 0 then the queue is empty in the sense there are no jobs waiting to be processed, but you may also check the other job status:  https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queuegetwaitingcount
