### ISSUE TITLE
Question: queue.getJobs() race condition

### ISSUE THREAD

**Issue by fyodorvi** [OptimalBits/bull#994]
From `getJobs()` implementation I can see that unlike `getJobCounts()` you don't use transaction to get the jobs, which is potentially very dangerous since you might have jobs transitioning state while you are getting every state separately:

```
queue.getJobs(['active', 'waiting']);
```
Job 1 is in waiting state.
getJobs gets 'active' jobs => [] (empty array)
Job 1 transitions to active state
getJobs gets 'waiting' jobs => [] (empty array)

Could you please tell me if I'm wrong, or clarify why it's done without a transaction or tell me it's a bug.

Thanks.

**Comment by manast** [comment]
More than a bug it has been overlooked, since the getters have not been considered very as critical methods.

**Comment by fyodorvi** [comment]
@manast PR is out
