### ISSUE TITLE
Rate limiter doesn't work

### ISSUE THREAD

**Issue by max7z** [OptimalBits/bull#998]
## Description
A Query with settings `{ limiter: { max: 1, duration: 5000 } }` doesn't work.
I want to have a job query which runs only one instance at once.

## Minimal, Working Test code to reproduce the issue.
```typescript
import * as Queue from "bull"

// @ts-ignore
const q1 = new Queue("q1", "redis://127.0.0.1:6379", { limiter: { max: 1 } })
// const q1 = new Queue("q1", "redis://127.0.0.1:6379", { limiter: { max: 1, duration: 1000 } })
// const q1 = new Queue("q1", "redis://127.0.0.1:6379")

const sleep = (delay: number) => new Promise(resolve => setTimeout(resolve(), delay))

q1.process(async (job: any, done: any) => {
  console.log("Running task with data: " + job.data.number + " " + new Date())
  await sleep(3000)
  done()
})

q1.add({ number: 1 })
q1.add({ number: 2 })
q1.add({ number: 3 })

```

This code prints nothing to console and hangs. But if I run that code without `{ limiter: { max: 1 } }`, it prints to console:

```
Running task with data: 1 Sat Jul 14 2018 07:45:52 GMT+0000 (Coordinated Universal Time)
Running task with data: 2 Sat Jul 14 2018 07:45:52 GMT+0000 (Coordinated Universal Time)
Running task with data: 3 Sat Jul 14 2018 07:45:52 GMT+0000 (Coordinated Universal Time)
```

## Bull version
v3.4.2

**Comment by manast** [comment]
You forgot to specify the "duration" of the limiter, for example 1000 ms, if you want to limit to one job per second, etc.

**Comment by max7z** [comment]
@manast I've tried already it with duration, there was the same result -- it prints nothings and hangs.
I've updated now the issue description to show that I've tried with duration as well.

**Comment by max7z** [comment]
@manast I've tried it one more time and now I see that it works with limiter: max + duration.

But it looks like if you first time use limiter only with max that queue will be broken. I've tried to use Queue.empty() method, but it doesn't help.

Here is a minimalistic demo:

```javascript
const Queue = require("bull")

const q = new Queue("name_2", "redis://127.0.0.1:6379", { limiter: { max: 1, duration: 500 } })

const sleep = delay => new Promise(resolve => setTimeout(resolve(), delay))

q.process(async (job, done) => {
  console.log("Running task with data: " + job.data.number + " " + new Date())
  await sleep(3000)
  done()
})

const main = async () => {
  await q.empty()

  q.add({ number: 10 })
  q.add({ number: 20 })
  q.add({ number: 30 })
}

main().catch(err => console.error(err))


```

This script works, but it run with wrong settings like `const q = new Queue("name_2", "redis://127.0.0.1:6379", { limiter: { max: 1 } })`, next time the same name `name_2` won't work even with correct limiter.

How can I completely erase the previous queue settings at the beginning of my scripts?
