### ISSUE TITLE
How to create a queue for a repeated async job in one thread only?

### ISSUE THREAD

**Issue by max7z** [OptimalBits/bull#999]
I have an async job with various durations -  from 500ms to 5s. I need constantly to run this job, but only in one instance at once, so that job should be run again only when the previous execution will be finished.

As I understand I should use `limiter` option to limit it. But I don't understand how to use `duration` property for my case. 

If I want to run a repeated job every 0.5s, do I need to wait when `RepeatOpts.every` feature will be published to npm? Is it possible to make with `cron` feature execution every 0.5s?

**Comment by manast** [comment]
The rate limiter's function is to avoid that jobs are processed too quickly, for example you could limit to max 1 job per second with ```{max: 1, duration: 1000}```. It does not affect parallelism, that depends on how many workers and what concurrency factor you are using. In your case, 1 worker with concurrency 1 should be enough.

**Comment by max7z** [comment]
Thank you, for my case it's really not necessary to use rateLimiter. 
Here is a demo code:

```typescript
import * as Queue from "bull"

const queue = new Queue("t2", "redis://127.0.0.1:6379")

const sleep = (delay: number) => new Promise(resolve => setTimeout(() => resolve(), delay))

queue.process(async (_, done) => {
  console.log("Running task: " + new Date())
  await sleep(1000)
  done()
})

queue.add({}, { repeat: { every: 300 } })

```
